Repository braze-inc/braze-docs, pull requests merged in 2019-05, with the labels that each got.

#56 Update explanation of Intel Deliv
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/intelligent_delivery.md
  assets/img/optimal-time-preview.png
Labels: cla-signed

#62 SDk Primer Edits
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
Labels: cla-signed

#51 API Section Revision
  _config.yml
  _docs/_api/api_campaigns.md
  _docs/_api/basics.md
  _docs/_api/endpoints.md
  _docs/_api/endpoints/email_sync.md
  _docs/_api/endpoints/email_templates.md
  _docs/_api/endpoints/export.md
  _docs/_api/endpoints/messaging.md
  _docs/_api/endpoints/subscription_group_api.md
  _docs/_api/endpoints/user_data.md
  _docs/_api/interactive.md
  _docs/_api/network_connectivity_issues.md
  _docs/_api/postman_collection.md
  _docs/_api/tls_deprecation.md
  _docs/_site_pages/api.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#85 Custom Data Storage
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_user_guide/administrative/app_settings/custom_event_and_attribute_management.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_custom_event_data.md
Labels: cla-signed

#91 Add Imagebuster to redirect JS
  _layouts/broken_page.html
  _layouts/default.html
Labels: cla-signed

#92 Leftovers
  _layouts/broken_page.html
  _layouts/default.html
Labels: cla-signed

#101 Trivial formatting fix
  _docs/_developer_guide/platform_integration_guides/ios/news_feed/news_feed_data_model.md
Labels: cla-signed

#95 Indicate IPs are valid for US 08
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
Labels: cla-signed

#99 Docs Updates
  _docs/_hidden/private_betas/x-in-y-behavior.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/message_building_by_channel/email/email_reporting.md
Labels: cla-signed

#97 inkit data fields update
  _docs/_partners/technology_partners/additional_channels/direct_mail/inkit.md
Labels: cla-signed

#71 Notification Pref Addition
  _docs/_user_guide/administrative/company_settings/notification_preferences.md
Labels: cla-signed, status: on hold / do not merge

#98 Voucherify npaw docs
  _docs/_partners/technology_partners/channel_extensions/loyalty.md
  _docs/_partners/technology_partners/channel_extensions/loyalty/voucherify.md
  _docs/_partners/technology_partners/insights/behavioral_analytics/npaw.md
  assets/img/npaw_dropdown.png
  assets/img/npaw_integration.png
  assets/img/npaw_sample_manager.png
  assets/img/npaw_sections_manager.png
  assets/img/voucherify_braze_campaign.png
  assets/img/voucherify_braze_campaign_preview.png
  assets/img/voucherify_custom_attributes.png
  assets/img/voucherify_distribution_audience.png
  assets/img/voucherify_distribution_channel.png
  assets/img/voucherify_distribution_mode.png
  assets/img/voucherify_distribution_purpose.png
  assets/img/voucherify_distribution_title.png
  assets/img/voucherify_establish_connection.png
  assets/img/voucherify_integration_directory.png
  assets/img/voucherify_new_distribution.png
  assets/img/voucherify_test.png
Labels: cla-signed

#73 Add 'dispatch_id' to Currents documentation for email events across all connectors
  _docs/_partners/braze_currents/data_storage_events/message_engagement_events.md
  _docs/_partners/technology_partners/data_and_infrastructure_agility/customer_data_platform/segment_for_currents.md
  _docs/_partners/technology_partners/insights/behavioral_analytics/amplitude_for_currents.md
  _docs/_partners/technology_partners/insights/behavioral_analytics/mixpanel_for_currents.md
Labels: cla-signed

#100 Added priority to support contact
  _docs/_hidden/other/support_contact.md
Labels: cla-signed

#94 Made server-side event triggering heading h2 class
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/in-app_message_delivery.md
Labels: cla-signed, priority: 3, status: done

#18 Roku docs
  _docs/_developer_guide/home.md
  _docs/_developer_guide/platform_integration_guides/roku.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/logging_custom_events.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/roku/initial_sdk_setup.md
Labels: cla-signed, status: on hold / do not merge

#102 jampp fixes
  _docs/_partners/technology_partners/advertising_technologies/retargeting/jampp.md
Labels: cla-signed

#89 Content Cards for Web Initial Commit
  _docs/_developer_guide/platform_integration_guides/web/content_cards.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/badges.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/data_models.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/overview.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/read_unread_indicators.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/refreshing_the_feed.md
  _docs/_hidden/private_betas/content_cards_web.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/overview.md
  assets/img/cc-feed_web.png
  config/nginx.conf.erb
Labels: cla-signed

#96 Update ios feed custom title instructions
  _docs/_developer_guide/platform_integration_guides/ios/news_feed/news_feed_integration_overview.md
Labels: cla-signed

#77 Document new Currents events for Content Cards
  _docs/_partners/braze_currents/data_storage_events/message_engagement_events.md
  _docs/_partners/technology_partners/data_and_infrastructure_agility/customer_data_platform/mparticle_for_currents.md
  _docs/_partners/technology_partners/data_and_infrastructure_agility/customer_data_platform/segment_for_currents.md
  _docs/_partners/technology_partners/insights/behavioral_analytics/amplitude_for_currents.md
  _docs/_partners/technology_partners/insights/behavioral_analytics/mixpanel_for_currents.md
Labels: cla-signed

#93 Android Q permission updates
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
Labels: cla-signed

#106 update # and in line reference
  _includes/archive/apple/initial_setup.md
Labels: cla-signed

#107 Added check if json link is invalid
  _plugins/alloy_partner.rb
Labels: cla-signed

#108 Calendar and Canvas IAM
  _docs/_hidden/misc_reference/most_engaged_channel.md
  _docs/_hidden/misc_reference/x-in-y-behavior.md
  _docs/_hidden/private_betas/canvas_in-app_messages.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#109 Link Fix
  config/nginx.conf.erb
Labels: cla-signed

#116 attribution fixes
  _docs/_partners/technology_partners/advertising_technologies/attribution/appsflyer.md
  _docs/_partners/technology_partners/advertising_technologies/attribution/branch_for_attribution.md
  _docs/_partners/technology_partners/advertising_technologies/attribution/kochava.md
  _docs/_partners/technology_partners/advertising_technologies/attribution/singular.md
  _docs/_partners/technology_partners/advertising_technologies/attribution/tune.md
Labels: cla-signed

#117 cc-android-fixes
  _docs/_developer_guide/platform_integration_guides/android/content_cards/badges.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/data_models.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/overview.md
Labels: cla-signed

#113 Create LICENSE.md
  LICENSE.md
Labels: cla-signed

#114 jampp revisions
  _docs/_partners/technology_partners/advertising_technologies/retargeting/jampp.md
  assets/img/jampp_webhook_template.png
Labels: cla-signed

#111 Clarifying that subscription groups are only available for email at t…
  _docs/_partners/braze_currents/data_storage_events/message_engagement_events.md
Labels: cla-signed

#112 Content Cards API
  _docs/_api/endpoints/email_sync.md
  _docs/_api/endpoints/messaging.md
Labels: cla-signed

#118 AMPHTML
  _docs/_hidden/private_betas/amphtml.md
Labels: cla-signed

#120 Link Fixes - iOS Docs
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/overview.md
Labels: cla-signed

#119 Weekly Deploy - May 14, 2019
  LICENSE.md
  _docs/_api/endpoints/email_sync.md
  _docs/_api/endpoints/messaging.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/badges.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/data_models.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/overview.md
  _docs/_hidden/private_betas/amphtml.md
  _docs/_partners/braze_currents/data_storage_events/message_engagement_events.md
  _docs/_partners/technology_partners/advertising_technologies/attribution/appsflyer.md
  _docs/_partners/technology_partners/advertising_technologies/attribution/branch_for_attribution.md
  _docs/_partners/technology_partners/advertising_technologies/attribution/kochava.md
  _docs/_partners/technology_partners/advertising_technologies/attribution/singular.md
  _docs/_partners/technology_partners/advertising_technologies/attribution/tune.md
  _docs/_partners/technology_partners/advertising_technologies/retargeting/jampp.md
  assets/img/jampp_webhook_template.png
Labels: cla-signed

#121 Updates to iOS Integration Documentation
  _docs/_developer_guide/platform_integration_guides/ios/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/social_data_tracking.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/data_model.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_templates.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _includes/archive/apple/initial_setup.md
Labels: cla-signed

#115 adjust updates
  _docs/_partners/technology_partners/advertising_technologies/attribution/adjust.md
Labels: cla-signed

#122 Frequency Capping by Tag
  _docs/_hidden/private_betas/frequency_capping.md
Labels: cla-signed

#123 Custom Event Storage fix:
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_user_guide/administrative/app_settings/custom_event_and_attribute_management.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_custom_event_data.md
Labels: cla-signed

#125 Leftovers 1 - May 16th, 2019
  _docs/_developer_guide/platform_integration_guides/ios/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/social_data_tracking.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/data_model.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_templates.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_hidden/private_betas/frequency_capping.md
  _docs/_partners/technology_partners/advertising_technologies/attribution/adjust.md
  _docs/_user_guide/administrative/app_settings/custom_event_and_attribute_management.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_custom_event_data.md
  _includes/archive/apple/initial_setup.md
Labels: cla-signed

#127 Connected Content campaigns process with the same priority as any oth…
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
Labels: cla-signed

#129 Add swift code to Content Cards Customization page
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization.md
Labels: cla-signed

#128 Added License Text
  LICENSE.md
Labels: cla-signed

#126 iOS Docs - Override default images for NF and Content Cards
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/news_feed/customizing_the_news_feed.md
Labels: cla-signed

#131 Fix broken links
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_templates.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/troubleshooting.md
Labels: cla-signed

#132 Add variation ID to the Content Card Object for API campaigns
  _docs/_api/endpoints/messaging.md
Labels: cla-signed

#130 API Phase 2.5
  _docs/_api/endpoints/messaging.md
  _docs/_api/errors.md
  _docs/_api/interactive.md
  _docs/_api/parameters.md
  _layouts/glossary_page.html
  assets/css/_glossary_page.scss
Labels: cla-signed

#133 Javascript highlight glossary description
  _layouts/glossary_page.html
Labels: cla-signed

#135 Updated Create API Campaign Page
  _docs/_api/api_campaigns.md
  assets/img/createapicampaigns.gif
  assets/img/selectapicampaigns.png
Labels: cla-signed
