Repository braze-inc/braze-docs, pull requests merged in 2019-11, with the labels that each got.

#634 Update IAM orientation note for iPads
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
Labels: cla-signed

#631 Update user_data.md - for users/identify endpoint
  _docs/_api/endpoints/user_data.md
Labels: cla-signed

#596 Change github base url
  _config.yml
Labels: cla-signed, hacktober, hacktoberfest

#633 Update mparticle_for_currents.md
  _docs/_partners/technology_partners/data_and_infrastructure_agility/customer_data_platform/mparticle_for_currents.md
Labels: cla-signed

#635 Content Cards 2KB Note Emphasis - BD-302
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
Labels: cla-signed

#637 Neura Redirect
  assets/js/broken_redirect_list.js
Labels: cla-signed

#636 SDK 101
  _docs/_developer_guide/platform_integration_guides/android.md
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
Labels: cla-signed

#639 Small phrasing fix
  _docs/_user_guide/data_and_analytics/custom_data/event_naming_conventions.md
Labels: cla-signed

#478 abort_message() always logs default error
  _docs/_user_guide/personalization_and_dynamic_content/liquid/aborting_messages.md
Labels: cla-signed

#546 [Blocked] Update stopwatch openUrl docs
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
Labels: cla-signed

#641 Neura Fixes
  _docs/_partners/technology_partners/data_augmentation/contextual_location/neura_actions.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#642 connected content in content cards migration guide
  _docs/_user_guide/message_building_by_channel/content_cards/migrating_from_news_feed.md
Labels: cla-signed

#643 Leftovers - November 6, 2019
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
  _docs/_partners/technology_partners/data_augmentation/contextual_location/neura_actions.md
  _docs/_user_guide/data_and_analytics/custom_data/event_naming_conventions.md
  _docs/_user_guide/message_building_by_channel/content_cards/migrating_from_news_feed.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/aborting_messages.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#652 Fixed typo
  _docs/_developer_guide/platform_integration_guides/unity/android/sdk_integration.md
Labels: cla-signed

#651 Add swift equivalents to push story docs
  _docs/_developer_guide/platform_integration_guides/ios/push_story.md
Labels: cla-signed

#649 Add ABKURLDelegate example in Swift
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
Labels: cla-signed

#650 Move location enabling docs to initial sdk setup
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/fireos/initial_sdk_setup.md
Labels: cla-signed

#647 Remove outdated iOS location docs
  _docs/_developer_guide/platform_integration_guides/ios/analytics/location_tracking.md
Labels: cla-signed

#645 Update iOS push extras docs
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/customization.md
Labels: cla-signed

#646 Add Swift examples for Store Review
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_templates.md
Labels: cla-signed

#653 Add deep link docs for activities using singletask launchmode
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/initial_sdk_setup.md
Labels: cla-signed

#648 Remove references to iOS versions before 3.0.0 + remove dry run reference
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/localization.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/action_buttons.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/troubleshooting.md
  _docs/_user_guide/data_and_analytics/tracking/uninstall_tracking.md
Labels: cla-signed

#654 BD-222 : Content Cards Custom Language
  _docs/_user_guide/message_building_by_channel/content_cards/customize.md
Labels: cla-signed

#655 Weekly Deploy - November 12, 2019
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/fireos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/localization.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_templates.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/action_buttons.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/ios/push_story.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/unity/android/sdk_integration.md
  _docs/_user_guide/data_and_analytics/tracking/uninstall_tracking.md
  _docs/_user_guide/message_building_by_channel/content_cards/customize.md
Labels: cla-signed

#663 Update uninstall_tracking.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/uninstall_tracking.md
Labels: cla-signed

#662 Removed link from abButtonId code example
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
Labels: cla-signed

#665 Amazon Moments Loyalty Block 1
  _docs/_partners/technology_partners/channel_extensions/loyalty.md
Labels: cla-signed

#656 Added warning about limitations and updated to gated
  _docs/_hidden/private_betas/frequency_capping.md
Labels: cla-signed, priority: 1

#668 Emily necciai patch 12
  _docs/_developer_guide/platform_integration_guides/android/analytics/uninstall_tracking.md
  _docs/_hidden/private_betas/frequency_capping.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/in_app_message_color_templates.md
Labels: cla-signed

#657 BD-644
  _docs/_developer_guide/platform_integration_guides/android/analytics/uninstall_tracking.md
  _docs/_hidden/private_betas/frequency_capping.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/in_app_message_color_templates.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#658 Updates to Dark Mode Docs
  _docs/_user_guide/message_building_by_channel/in-app_messages/dark-mode.md
Labels: cla-signed

#671 Delete in_app_message_color_templates.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/in_app_message_color_templates.md
Labels: cla-signed

#669 Update broken_redirect_list.js
  _docs/_user_guide/message_building_by_channel/in-app_messages/in_app_message_color_templates.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#675 BD-144
  _docs/_user_guide/onboarding_with_braze/terms_to_know.md
Labels: cla-signed

#679 unhide darkmode
  _docs/_user_guide/message_building_by_channel/in-app_messages/dark-mode.md
Labels: cla-signed

#676 BD-356 BD-358
  _docs/_user_guide/data_and_analytics/export_braze_data/segment_data_to_csv.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers.md
Labels: cla-signed

#680 Adding Dark Mode Block to IAM main page
  _docs/_user_guide/message_building_by_channel/in-app_messages.md
Labels: cla-signed

#673 [PC-1672] Add content cards integration docs for unity
  _docs/_developer_guide/platform_integration_guides/unity/android/sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/unity/ios/sdk_integration.md
  assets/img_archive/unity-ios-content-cards-listener.png
Labels: cla-signed

#661 Remove reference to deprecated method getActionWithIdentifier
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/action_buttons.md
Labels: cla-signed

#677 Update engagement_reports.md
  _docs/_user_guide/data_and_analytics/your_reports/engagement_reports.md
Labels: cla-signed

#678 added content cards docs on disabling swipe to dismiss
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
Labels: cla-signed

#548 Intelligence Suite
  Archive/documentation/_site/redirect_list.js
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/troubleshooting.md
  _docs/_help/release_notes/2019/may.md
  _docs/_hidden/misc_reference/most_engaged_channel.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/ab_testing_with_random_buckets.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/intelligent_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/scheduling_your_campaign.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/intelligence.md
  _docs/_user_guide/intelligence/intelligent_channel.md
  _docs/_user_guide/intelligence/intelligent_selection.md
  _docs/_user_guide/intelligence/intelligent_timing.md
  _docs/_user_guide/intelligence/multivariate_testing.md
  assets/img/intelligent_channel_filter.png
  assets/js/broken_redirect_list.js
  config/nginx.conf.erb
Labels: cla-signed

#685 November Release Notes
  _docs/_help/release_notes/2019/november.md
  _docs/_help/release_notes/most_recent.md
Labels: cla-signed

#687 Link Fixes
  _docs/_help/release_notes/2019.md
  _docs/_help/release_notes/2019/november.md
  _docs/_help/release_notes/most_recent.md
Labels: cla-signed

#686 Deploy - November 19, 2019
  Archive/documentation/_site/redirect_list.js
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/action_buttons.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/unity/android/sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/unity/ios/sdk_integration.md
  _docs/_help/release_notes/2019.md
  _docs/_help/release_notes/2019/may.md
  _docs/_help/release_notes/2019/november.md
  _docs/_help/release_notes/most_recent.md
  _docs/_hidden/misc_reference/most_engaged_channel.md
  _docs/_user_guide/data_and_analytics/export_braze_data/segment_data_to_csv.md
  _docs/_user_guide/data_and_analytics/your_reports/engagement_reports.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/ab_testing_with_random_buckets.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/intelligent_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/scheduling_your_campaign.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/intelligence.md
  _docs/_user_guide/intelligence/intelligent_channel.md
  _docs/_user_guide/intelligence/intelligent_selection.md
  _docs/_user_guide/intelligence/intelligent_timing.md
  _docs/_user_guide/intelligence/multivariate_testing.md
  _docs/_user_guide/message_building_by_channel/in-app_messages.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers.md
  _docs/_user_guide/onboarding_with_braze/terms_to_know.md
  assets/img/intelligent_channel_filter.png
  assets/img_archive/unity-ios-content-cards-listener.png
  assets/js/broken_redirect_list.js
  config/nginx.conf.erb
Labels: cla-signed

#688 Catching Develop up to Master
  _docs/_user_guide/message_building_by_channel/in-app_messages/dark-mode.md
Labels: cla-signed

#692 Fixing so iOS Code appears instead of tvOS code
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods.md
Labels: cla-signed

#693 Added iOS version support for app version code filter
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/new_features.md
Labels: cla-signed

#690 [PC-1692] Add note for default image support in Xamarin
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/news_feed/customizing_the_news_feed.md
Labels: cla-signed

#691 [PC-1646] update action buttons docs
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/action_buttons.md
Labels: cla-signed

#689 BD-313
  _docs/_help/best_practices/push/conversion_tracking.md
Labels: cla-signed

#684 Android/custom manager listener docs
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
Labels: cla-signed

#682 BD-360 BD-282
  _docs/_help/best_practices/news_feed.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/engagement_tools/news_feed.md
  _docs/_user_guide/engagement_tools/news_feed/creating_a_news_feed_item.md
  _docs/_user_guide/engagement_tools/news_feed/news_feed_use_cases.md
Labels: cla-signed

#699 val -> var
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
Labels: cla-signed

#698 BD-293
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/overview.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/overview.md
Labels: cla-signed

#697 BD-345 BD-320 BD-348
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
Labels: cla-signed

#696 Updated users/alias/new
  _docs/_api/endpoints/user_data.md
Labels: cla-signed

#695 BD-349
  _docs/_user_guide/engagement_tools/news_feed/news_feed_categories.md
Labels: cla-signed

#694 BD-359
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Labels: cla-signed

#700 Date of Custom Attribute, Less than BD-299
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
Labels: cla-signed

#701 Leftovers - November 22, 2019
  _docs/_api/endpoints/user_data.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/overview.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods.md
  _docs/_developer_guide/platform_integration_guides/ios/news_feed/customizing_the_news_feed.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/action_buttons.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/overview.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_help/best_practices/news_feed.md
  _docs/_help/best_practices/push/conversion_tracking.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/new_features.md
  _docs/_user_guide/engagement_tools/news_feed.md
  _docs/_user_guide/engagement_tools/news_feed/creating_a_news_feed_item.md
  _docs/_user_guide/engagement_tools/news_feed/news_feed_categories.md
  _docs/_user_guide/engagement_tools/news_feed/news_feed_use_cases.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
Labels: cla-signed

#715 BD-375
  _docs/_partners/technology_partners/channel_extensions/localization/transifex.md
Labels: cla-signed

#712 Fix links React Native iOS docs
  _docs/_developer_guide/platform_integration_guides/react_native/ios/sdk_integration.md
Labels: cla-signed

#709 Updated error codes
  _docs/_api/errors.md
Labels: cla-signed

#711 Note the restriction for Safari and Firefox needing push registration from event handler
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
Labels: cla-signed

#707 BD-309
  _docs/_user_guide/message_building_by_channel/email/link_templates.md
Labels: cla-signed

#713 BD-173
  _docs/_user_guide/administrative/access_braze/sdk_endpoints.md
Labels: cla-signed

#706 GIT-139
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
Labels: cla-signed

#705 Update Unity plugins instructions
  _docs/_developer_guide/platform_integration_guides/unity/android/sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/unity/ios/sdk_integration.md
Labels: cla-signed

#702 Update write threshold limits
  _docs/_partners/braze_currents/data_storage_events/event_delivery_sematics.md
Labels: cla-signed

#704 BD-307
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Labels: cla-signed

#710 Page Templates
  _docs/_home/metadata.md
  _docs/_home/static_video.md
  _docs/_home/templates.md
  _docs/_home/templates/api_glossary.md
  _docs/_home/templates/glossary_test_page.md
  _docs/_home/templates/help_article_template.md
  _docs/_home/templates/landing_images.md
  _docs/_home/templates/landing_multiple.md
  _docs/_home/templates/landing_multiple_images.md
  _docs/_home/templates/landing_single.md
  _docs/_home/templates/partner_page_template.md
  _docs/_home/templates/partner_page_template_video.md
  _docs/_home/templates/reference.md
  _docs/_home/templates/reference_video.md
  _docs/_home/templates/solution.md
  _docs/_home/templates/tutorial.md
  _docs/_home/templates/tutorial_video.md
  _docs/_home/templates/use_case.md
  _docs/_home/templates/use_case_video.md
Labels: cla-signed
