Repository braze-inc/braze-docs, pull requests merged in 2019-04, with the labels that each got.

#10 Glossaries
  _docs/_user_guide/data_and_analytics/configuring_reporting.md
  _docs/_user_guide/data_and_analytics/creating_a_formula.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/data_and_analytics/your_reports/engagement_reports.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/onboarding_with_braze/terms_to_know.md
  _layouts/glossary_page.html
  assets/css/_glossary_page.scss
  assets/css/application.scss
  assets/js/hash_redirect.js
Labels: cla-signed, difficulty: medium, status: in progress

#26 Rake dependency update
  Gemfile
  Gemfile.lock
Labels: cla-signed

#8 SDK Primer
  _docs/_developer_guide/platform_integration_guides/android.md
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
Labels: cla-signed, difficulty: medium, priority: 1, status: in progress

#14 Update /users/delete response to be more clear about users queued for deletion.
  _docs/_developer_guide/rest_api/user_data.md
Labels: cla-signed

#27 Remove Eclipse info from initial sdk setup
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/initial_sdk_setup.md
Labels: cla-signed

#29 Subscription Group Archiving and April RN
  _docs/_help/release_notes/2019/april.md
  _docs/_help/release_notes/most_recent.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#17 Remove cross-promotion cards from docs
  _docs/_developer_guide/platform_integration_guides/android/news_feed/card_types.md
  _docs/_developer_guide/platform_integration_guides/fireos/news_feed.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/localization.md
  _docs/_developer_guide/platform_wide/platform_features.md
  _docs/_help/best_practices/news_feed.md
  _docs/_hidden/private_betas/content_cards_for_android.md
Labels: cla-signed, status: done

#28 Add note about silent push to android docs
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
Labels: cla-signed

#30 Hidden Page Redirects
  _docs/_partners/technology_partners/additional_channels/sms/wavecell.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  config/nginx.conf.erb
Labels: cla-signed, status: done

#31 SDK Primer
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
Labels: cla-signed, status: in progress

#22 Add code snippet for background push open logging
  _docs/_developer_guide/platform_integration_guides/windows_universal/push_notifications/integration.md
Labels: cla-signed

#33 Web SDK Page Move from BP
  _docs/_help/best_practices/image_and_text_specifications.md
  _docs/_help/best_practices/spam_regulations.md
  _docs/_help/best_practices/web_sdk.md
  _docs/_user_guide/onboarding_with_braze/web_sdk.md
Labels: cla-signed

#36 Update most engaged documentation
  _docs/_hidden/private_betas/most_engaged_channel.md
Labels: cla-signed

#39 Update technical explanation
  _docs/_hidden/private_betas/most_engaged_channel.md
Labels: cla-signed

#40 Release Notes - 2
  _docs/_help/release_notes/2019/april.md
  _docs/_help/release_notes/most_recent.md
Labels: cla-signed

#41 Fix all tags not filtering correctly
  _layouts/glossary_page.html
Labels: cla-signed

#42 Weekly Deploy - April 9, 2019 -
  _docs/_help/release_notes/2019/april.md
  _docs/_help/release_notes/most_recent.md
  _docs/_hidden/private_betas/most_engaged_channel.md
  _docs/_partners/braze_currents/data_storage_events/customer_behavior_events.md
  _docs/_partners/braze_currents/data_storage_events/message_engagement_events.md
  _docs/_partners/technology_partners/data_and_infrastructure_agility/customer_data_platform/mparticle_for_currents.md
  _docs/_partners/technology_partners/data_and_infrastructure_agility/customer_data_platform/segment_for_currents.md
  _docs/_partners/technology_partners/insights/behavioral_analytics/amplitude_for_currents.md
  _docs/_partners/technology_partners/insights/behavioral_analytics/mixpanel_for_currents.md
  _layouts/glossary_page.html
  _plugins/algolia_hooks.rb
  assets/css/_glossary_page.scss
Labels: cla-signed

#38 Update IAM listener code example
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/customization.md
Labels: cla-signed, status: in progress

#43 Email Revision - v1.
  _docs/_help/best_practices/email/email_services.md
  _docs/_help/best_practices/email/managing_email_subscriptions.md
  _docs/_help/best_practices/email/technical_guidelines_and_tips.md
  _docs/_user_guide/message_building_by_channel/email/email_reporting.md
  _docs/_user_guide/onboarding_with_braze/email_setup/import_your_email_list.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ip_warming.md
  _docs/_user_guide/onboarding_with_braze/email_setup/overview_and_requirements.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#46 Added details for Push Stories integration (ported from success docs)
  _docs/_developer_guide/platform_integration_guides/ios/push_story.md
Labels: cla-signed

#45 Updated uninstall tracking documentation
  _docs/_developer_guide/platform_integration_guides/android/analytics/uninstall_tracking.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/uninstall_tracking.md
Labels: cla-signed

#50 Misc. Fixes
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  assets/js/swagger/braze_swagger.json
Labels: cla-signed

#13 User Import Rewrite
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/onboarding_with_braze/integration.md
  assets/img/csv-errors.png
  assets/img/importcsv.png
  assets/img/segment-imported-upsers.png
Labels: cla-signed, difficulty: easy, status: done

#53 Updating Looker Docs
  _docs/_partners/technology_partners/insights/business_intelligence/looker.md
  assets/img/braze-looker-action.png
  assets/img/braze_segments.png
  assets/img/custom-attributes-looker.png
  assets/img/send-looker-action.png
  assets/img/user-track-api.gif
Labels: cla-signed

#52 Add additional fields to the users/track response documentation
  _docs/_developer_guide/rest_api/user_data.md
Labels: cla-signed

#55 Redirect Old page
  assets/js/broken_redirect_list.js
Labels: cla-signed

#54 Weekly Deploy - April 16, 2019
  _docs/_developer_guide/platform_integration_guides/android/analytics/uninstall_tracking.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/uninstall_tracking.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _docs/_developer_guide/rest_api/user_data.md
  _docs/_partners/technology_partners/insights/business_intelligence/looker.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/onboarding_with_braze/integration.md
  assets/img/braze-looker-action.png
  assets/img/braze_segments.png
  assets/img/csv-errors.png
  assets/img/custom-attributes-looker.png
  assets/img/importcsv.png
  assets/img/segment-imported-upsers.png
  assets/img/send-looker-action.png
  assets/img/user-track-api.gif
  assets/js/broken_redirect_list.js
  assets/js/swagger/braze_swagger.json
Labels: cla-signed

#59 Fix html tags in search
  _includes/search_page.html
  _plugins/algolia_hooks.rb
  assets/js/documents.js
Labels: cla-signed

#60 Link Fixes
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
Labels: cla-signed

#20 Add initial Flutter SDK docs
  _docs/_developer_guide/home.md
  _docs/_developer_guide/platform_integration_guides/flutter.md
  _docs/_developer_guide/platform_integration_guides/flutter/preview.md
Labels: cla-signed, status: on hold / do not merge

#61 Leftovers
  _docs/_developer_guide/home.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/flutter.md
  _docs/_developer_guide/platform_integration_guides/flutter/preview.md
  _includes/search_page.html
  _plugins/algolia_hooks.rb
  assets/js/documents.js
Labels: cla-signed

#65 Fix broken link
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md
Labels: cla-signed

#63 Adjust Archive Thread Usage
  Rakefile
Labels: cla-signed

#66 IAM Edits
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
Labels: cla-signed

#64 IP Whitelisting
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
Labels: cla-signed

#69 Add user_aliases to the options for deleting users
  _docs/_developer_guide/rest_api/user_data.md
Labels: cla-signed

#70 Clarify the file path information for the multiple storage connector …
  _docs/_partners/braze_currents/data_storage_events/event_delivery_sematics.md
Labels: cla-signed

#68 Weekly Deploy - April 23, 2019
  Rakefile
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/rest_api/user_data.md
  _docs/_partners/braze_currents/data_storage_events/event_delivery_sematics.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
Labels: cla-signed

#74 fix prewrap for 1 line examples
  assets/css/_content.scss
  assets/js/documents.js
Labels: cla-signed

#72 Jampp Docs
  _docs/_partners/technology_partners/advertising_technologies/retargeting/jampp.md
  assets/img/jampp_method.png
  assets/img/jampp_webhook.png
Labels: cla-signed

#76 Removed https:// protocol from sdk endpoints
  _docs/_user_guide/administrative/access_braze/sdk_endpoints.md
Labels: cla-signed, difficulty: easy, priority: 2

#57 X in Y Page
  _docs/_hidden/private_betas/x-in-y-behavior.md
  assets/img/campaign-schuedule-example.png
Labels: cla-signed, status: done

#67 Remove deprecated GCM web push setup instructions pending GCM's deletion by Google.
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
  assets/img_archive/firebase_console.png
Labels: cla-signed

#79 Leftovers - April 25, 2019
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
  _docs/_hidden/private_betas/x-in-y-behavior.md
  _docs/_partners/technology_partners/advertising_technologies/retargeting/jampp.md
  _docs/_user_guide/administrative/access_braze/sdk_endpoints.md
  assets/css/_content.scss
  assets/img/campaign-schuedule-example.png
  assets/img/jampp_method.png
  assets/img/jampp_webhook.png
  assets/img_archive/firebase_console.png
  assets/js/documents.js
Labels: cla-signed

#82 inkit updates
  _docs/_partners/technology_partners/additional_channels/direct_mail/inkit.md
Labels: cla-signed

#81 Segment Endpoint Filename Breakdown
  _docs/_developer_guide/rest_api/export.md
Labels: cla-signed

#83 Leftovers 2 - April 26, 2019
  _docs/_developer_guide/rest_api/export.md
  _docs/_partners/technology_partners/additional_channels/direct_mail/inkit.md
Labels: cla-signed
