Repository braze-inc/braze-docs, pull requests merged in 2019-10, with the labels that each got.

#467 Email Bounces Correction in Report Metrics & Email Report metrics - C…
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/message_building_by_channel/email/email_reporting.md
Labels: cla-signed

#456 Remove redundant note
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/locations_and_geofences.md
Labels: cla-signed

#466 Set a Card as dismissed Method for Android- 235
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
Labels: cla-signed

#464 Unique Recipients Def - 374 & Android Support Library Link - 159
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/unity/android/sdk_integration.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
Labels: cla-signed

#395 Added left nav toggle
  _includes/left_nav_menu.html
  _layouts/broken_page.html
  _layouts/dev_guide.html
  _layouts/doc_guide.html
  _layouts/documents.html
  _layouts/featured.html
  _layouts/glossary_page.html
  _layouts/partner_page.html
  _layouts/self_help.html
  _layouts/user_guide.html
  assets/css/_navigation_menu.scss
  assets/css/_toc.scss
  assets/js/documents.js
Labels: cla-signed

#481 iOS In-App Message Customized Code Correction- 322
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
Labels: cla-signed

#486 fixed wrong link
  _docs/_developer_guide/platform_integration_guides/web/content_cards/integration.md
Labels: cla-signed

#485 fixed wrong links
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization.md
Labels: cla-signed

#500 correction
  _docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/set_up.md
Labels: cla-signed

#490 Individual Email Address Clarification.
  _docs/_hidden/other/email_private_relay_apple.md
Labels: cla-signed

#509 Image Edit
  assets/img/email-relay-whitelabel-address.png
Labels: cla-signed

#508 Remove example using deprecated callback
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
Labels: cla-signed

#506 BD-302 - Updated pinned card description
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
Labels: cla-signed

#507 BD-327 - updated bullet point formatting
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/scheduling_your_campaign.md
Labels: cla-signed

#503 Added `dismissCard()` method
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization.md
Labels: cla-signed

#511 Leftovers - October 3, 2019
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
  _docs/_hidden/other/email_private_relay_apple.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/set_up.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/scheduling_your_campaign.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  assets/img/email-relay-whitelabel-address.png
Labels: cla-signed

#512 Modified Release Notes page
  _docs/_help/release_notes.md
Labels: cla-signed

#510 Modified Help Articles page
  _docs/_help/help_articles.md
Labels: cla-signed

#505 Modified Best Practices page
  _docs/_help/best_practices.md
Labels: cla-signed

#502 Modified Webinars page
  _docs/_help/webinars.md
Labels: cla-signed

#501 Modified Deprecations page
  _docs/_help/release_notes/deprecations.md
Labels: cla-signed

#498 Modified 2018 release notes page
  _docs/_help/release_notes/2018.md
Labels: cla-signed

#499 Modified 2019 release notes page
  _docs/_help/release_notes/2019.md
Labels: cla-signed

#496 Modified 2016 release notes page
  _docs/_help/release_notes/2016.md
Labels: cla-signed

#497 Modified 2017 release notes page
  _docs/_help/release_notes/2017.md
Labels: cla-signed

#493 Modified Push Help articles page
  _docs/_help/help_articles/push.md
Labels: cla-signed

#489 Modfied Docs help articles page
  _docs/_help/help_articles/docs.md
Labels: cla-signed

#492 Modified In-App Messages help articles page
  _docs/_help/help_articles/in-app_messages.md
Labels: cla-signed

#491 Modified Email help articles page
  _docs/_help/help_articles/email.md
Labels: cla-signed

#520 Remove HTTPS from SDK Endpoints
  _docs/_api/basics.md
Labels: cla-signed, hacktober, hacktoberfest

#522 update support page
  _docs/_hidden/other/support_contact.md
Labels: cla-signed

#516 Note formatting update user guide
  _docs/_user_guide/administrative/app_settings/custom_event_and_attribute_management.md
  _docs/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md
  _docs/_user_guide/data_and_analytics/tracking/uninstall_tracking.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/data_and_analytics/your_reports/engagement_reports.md
  _docs/_user_guide/data_and_analytics/your_reports/understanding_your_app_usage_data.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/ab_testing_with_random_buckets.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/scheduling_your_campaign.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/conversion_events.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/multivariate_testing.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/rate-limiting.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_push_notifications.md
  _docs/_user_guide/engagement_tools/news_feed/creating_a_news_feed_item.md
  _docs/_user_guide/engagement_tools/segments/beacon_support.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
  _docs/_user_guide/message_building_by_channel/push/notification_channels.md
  _docs/_user_guide/onboarding_with_braze/integration.md
  _docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
Labels: cla-signed

#519 Update initial_sdk_setup for Web SDK
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
Labels: cla-signed, hacktober, hacktoberfest

#487 Modified Content Cards help articles page
  _docs/_help/help_articles/content_cards.md
Labels: cla-signed

#480 Modified API Help Articles section
  _docs/_help/help_articles/api.md
  _docs/_help/help_articles/api/delete_user.md
Labels: cla-signed

#479 Modified Account Help Articles section
  _docs/_help/help_articles/account.md
  _docs/_help/help_articles/account/locked_out.md
Labels: cla-signed

#488 Modified Data help articles page
  _docs/_help/help_articles/data.md
Labels: cla-signed

#483 Modified Campaigns and Canvas help articles section
  _docs/_help/help_articles/campaigns_and_canvas.md
Labels: cla-signed

#518 Added missing space
  _docs/_user_guide/onboarding_with_braze/email_setup/authentication.md
Labels: cla-signed

#524 Update Release Notes Main page
  _docs/_help/release_notes.md
Labels: cla-signed

#526 Weekly Deploy - October 8, 2019
  _docs/_api/basics.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_help/best_practices.md
  _docs/_help/help_articles.md
  _docs/_help/help_articles/account.md
  _docs/_help/help_articles/account/locked_out.md
  _docs/_help/help_articles/api.md
  _docs/_help/help_articles/api/delete_user.md
  _docs/_help/help_articles/campaigns_and_canvas.md
  _docs/_help/help_articles/content_cards.md
  _docs/_help/help_articles/data.md
  _docs/_help/help_articles/docs.md
  _docs/_help/help_articles/email.md
  _docs/_help/help_articles/in-app_messages.md
  _docs/_help/help_articles/push.md
  _docs/_help/help_articles/segments.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2016.md
  _docs/_help/release_notes/2017.md
  _docs/_help/release_notes/2018.md
  _docs/_help/release_notes/2019.md
  _docs/_help/release_notes/deprecations.md
  _docs/_help/webinars.md
  _docs/_hidden/other/support_contact.md
  _docs/_user_guide/administrative/app_settings/custom_event_and_attribute_management.md
  _docs/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md
  _docs/_user_guide/data_and_analytics/tracking/uninstall_tracking.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/data_and_analytics/your_reports/engagement_reports.md
  _docs/_user_guide/data_and_analytics/your_reports/understanding_your_app_usage_data.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/ab_testing_with_random_buckets.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/scheduling_your_campaign.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/conversion_events.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/multivariate_testing.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/rate-limiting.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_push_notifications.md
  _docs/_user_guide/engagement_tools/news_feed/creating_a_news_feed_item.md
  _docs/_user_guide/engagement_tools/segments/beacon_support.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
  _docs/_user_guide/message_building_by_channel/push/notification_channels.md
  _docs/_user_guide/onboarding_with_braze/email_setup/authentication.md
  _docs/_user_guide/onboarding_with_braze/integration.md
  _docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
Labels: cla-signed

#529 fixed phrasing for "pinned" property
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/data_model.md
Labels: cla-signed, hacktober, hacktoberfest

#527 Push Notification Separation - BD-301
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
  _docs/_user_guide/message_building_by_channel/push/ios_customizable_app_icon_feature.md
  _docs/_user_guide/message_building_by_channel/push/ios_notification_headers.md
  _docs/_user_guide/message_building_by_channel/push/notification_channels.md
  _docs/_user_guide/message_building_by_channel/push/notification_ids.md
  _docs/_user_guide/message_building_by_channel/push/notification_options_android.md
  _docs/_user_guide/message_building_by_channel/push/notification_options_ios.md
  _docs/_user_guide/message_building_by_channel/push/push_action_buttons.md
  _docs/_user_guide/message_building_by_channel/push/push_stories.md
  _docs/_user_guide/message_building_by_channel/push/rich_notifications.md
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
  assets/img/profile-push-prov-auth.png
  assets/img/segment-push-prov-auth.png
Labels: cla-signed

#428 Content Cards in Canvas
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/content-cards_in_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
  _docs/_user_guide/message_building_by_channel/content_cards/migrating_from_news_feed.md
  assets/img_archive/content-cards-in-canvas-analytics.png
  assets/img_archive/content-cards-in-canvas-multiple-channels.png
  assets/img_archive/content-cards-in-canvas-single-channel.png
  assets/img_archive/content-cards-in-canvas.png
Labels: cla-signed, hacktober, hacktoberfest

#530 Leftovers #2 - October 9, 2019
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/data_model.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/content-cards_in_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
  _docs/_user_guide/message_building_by_channel/content_cards/migrating_from_news_feed.md
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
  _docs/_user_guide/message_building_by_channel/push/ios_customizable_app_icon_feature.md
  _docs/_user_guide/message_building_by_channel/push/ios_notification_headers.md
  _docs/_user_guide/message_building_by_channel/push/notification_channels.md
  _docs/_user_guide/message_building_by_channel/push/notification_ids.md
  _docs/_user_guide/message_building_by_channel/push/notification_options_android.md
  _docs/_user_guide/message_building_by_channel/push/notification_options_ios.md
  _docs/_user_guide/message_building_by_channel/push/push_action_buttons.md
  _docs/_user_guide/message_building_by_channel/push/push_stories.md
  _docs/_user_guide/message_building_by_channel/push/rich_notifications.md
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
  assets/img/profile-push-prov-auth.png
  assets/img/segment-push-prov-auth.png
  assets/img_archive/content-cards-in-canvas-analytics.png
  assets/img_archive/content-cards-in-canvas-multiple-channels.png
  assets/img_archive/content-cards-in-canvas-single-channel.png
  assets/img_archive/content-cards-in-canvas.png
Labels: cla-signed

#531 Prov Push Edits
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _docs/_user_guide/message_building_by_channel/push/notification_options_ios.md
Labels: cla-signed

#532 Leftovers - 10.10.20
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _docs/_user_guide/message_building_by_channel/push/notification_options_ios.md
Labels: cla-signed

#536 Miscellaneous Ticket Fixes
  _docs/_api/endpoints/user_data.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_help/gdpr_compliance.md
  _docs/_help/help_articles/docs.md
  _docs/_help/help_articles/docs/hacktober_2019.md
  _docs/_help/release_notes/2019/september.md
  _docs/_help/release_notes/most_recent.md
  _docs/_home/api_glossary.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/ab_testing_with_random_buckets.md
  _docs/_user_guide/message_building_by_channel/email/inbox_vision.md
  assets/img/hacktoberfest_torchie2.png
Labels: cla-signed

#484 Updated web code example for multiple content cards feeds
  _docs/_developer_guide/platform_integration_guides/web/content_cards/multiple_feeds.md
Labels: cla-signed

#533 Update supported orientation mask examples
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
Labels: cla-signed

#513 Updated "Edit on Github"
  _config.yml
  _includes/feedback.html
  _layouts/documents.html
  assets/css/_feedback.scss
Labels: cla-signed

#517 Include message structure for exported content cards
  _docs/_api/endpoints/export.md
Labels: cla-signed, hacktober, hacktoberfest

#477 updated docs on gifs on android
  _includes/archive/android/gifs.md
Labels: cla-signed

#539 Weekly Deploy - October 15, 2019
  _config.yml
  _docs/_api/endpoints/export.md
  _docs/_api/endpoints/user_data.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/multiple_feeds.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_help/gdpr_compliance.md
  _docs/_help/help_articles/docs.md
  _docs/_help/help_articles/docs/hacktober_2019.md
  _docs/_help/release_notes/2019/september.md
  _docs/_help/release_notes/most_recent.md
  _docs/_home/api_glossary.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/ab_testing_with_random_buckets.md
  _docs/_user_guide/message_building_by_channel/email/inbox_vision.md
  _includes/archive/android/gifs.md
  _includes/feedback.html
  _layouts/documents.html
  assets/css/_feedback.scss
  assets/img/hacktoberfest_torchie2.png
Labels: cla-signed

#553 Delete YOUR_ACTIVITY.this, replace with context
  _docs/_developer_guide/platform_integration_guides/android/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/tracking_custom_events.md
Labels: cla-signed

#534 Update openurl example
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
Labels: cla-signed

#555 Add Kotlin examples to Social docs
  _docs/_developer_guide/platform_integration_guides/android/analytics/social_data_tracking.md
Labels: cla-signed

#556 Add Kotlin support to Advanced Usecases
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/beacon_integration.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/network_offline_mode_integration.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/runtime_configuration.md
  _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/beacon_integration.md
Labels: cla-signed

#554 Add Kotlin examples to Location Tracking and Purchase Analytics Docs
  _docs/_developer_guide/platform_integration_guides/android/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/logging_purchases.md
Labels: cla-signed

#552 Update instances of sharedInstance force unwrapping
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/fine_network_traffic_control.md
  _docs/_developer_guide/platform_integration_guides/ios/customer_feedback.md
  _docs/_home/styling_test_page.md
Labels: cla-signed

#550 Add Kotlin support to custom events page
  _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_custom_events.md
Labels: cla-signed

#549 Add kotlin to Setting User IDs page
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_user_ids.md
  _includes/archive/aliasing.md
Labels: cla-signed

#547 Add kotlin syntax for getExtras
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/key-value_pairs.md
Labels: cla-signed

#545 [Trivial] Fix deprecated openurl example
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_templates.md
Labels: cla-signed

#557 Replace instances of this with context
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/customization.md
  _docs/_developer_guide/platform_integration_guides/fireos/news_feed.md
  _docs/_developer_guide/platform_integration_guides/fireos/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/xamarin/android_and_fireos/analytics/attribute_tracking.md
  _docs/_developer_guide/platform_integration_guides/xamarin/android_and_fireos/analytics/logging_custom_events.md
  _docs/_developer_guide/platform_integration_guides/xamarin/android_and_fireos/analytics/revenue_tracking.md
  _docs/_developer_guide/platform_integration_guides/xamarin/android_and_fireos/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/xamarin/android_and_fireos/analytics/social_data_tracking.md
  _docs/_partners/technology_partners/advertising_technologies/attribution/appsflyer.md
  _docs/_partners/technology_partners/advertising_technologies/attribution/branch_for_attribution.md
  _docs/_partners/technology_partners/advertising_technologies/attribution/singular.md
  _docs/_partners/technology_partners/advertising_technologies/attribution/tune.md
  _includes/archive/android/gifs.md
Labels: cla-signed

#543 Update export.md
  _docs/_api/endpoints/export.md
Labels: cla-signed

#542 Remove unneeded semicolons in Swift examples
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/fine_network_traffic_control.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/tracking_custom_events.md
  _includes/archive/aliasing.md
Labels: cla-signed

#385 Tech Partners Landing Pages
  _docs/_partners/home.md
  _docs/_partners/technology_partners/additional_channels.md
  _docs/_partners/technology_partners/advertising_technologies.md
  _docs/_partners/technology_partners/channel_extensions.md
  _docs/_partners/technology_partners/data_and_infrastructure_agility.md
  _docs/_partners/technology_partners/insights.md
Labels: CONTRACTOR, cla-signed

#435 Modified Social page
  _docs/_partners/technology_partners/advertising_technologies/social.md
Labels: cla-signed

#431 Modified Retargeting page
  _docs/_partners/technology_partners/advertising_technologies/retargeting.md
Labels: cla-signed

#427 Modified Attribution listing
  _docs/_partners/technology_partners/advertising_technologies/attribution.md
Labels: cla-signed

#437 Modified Deeplinking page
  _docs/_partners/technology_partners/channel_extensions/deep_linking.md
Labels: cla-signed

#452 Modified Loyalty page
  _docs/_partners/technology_partners/channel_extensions/loyalty.md
Labels: cla-signed

#566 SMS API
  _docs/_api/endpoints/export.md
  _docs/_api/endpoints/messaging.md
  _docs/_api/endpoints/subscription_group_api.md
Labels: cla-signed

#587 Em/cal
  _docs/_partners/technology_partners/additional_channels.md
  _docs/_partners/technology_partners/additional_channels/calendar.md
Labels: cla-signed

#442 Modified Email orchestration page
  _docs/_partners/technology_partners/channel_extensions/email_orchestration.md
Labels: cla-signed

#451 Modified Localization page
  _docs/_partners/technology_partners/channel_extensions/localization.md
Labels: cla-signed

#453 Modified Workflow Automation page
  _docs/_partners/technology_partners/channel_extensions/workflow_automation.md
Labels: cla-signed

#458 Modified Data and Infrastructure Agility page
  _docs/_partners/technology_partners/data_and_infrastructure_agility/data_warehouses.md
Labels: cla-signed

#459 Modified Wrapper sdks page
  _docs/_partners/technology_partners/data_and_infrastructure_agility/wrapper_sdks.md
Labels: cla-signed

#457 Modified Customer data platform page
  _docs/_partners/technology_partners/data_and_infrastructure_agility/customer_data_platform.md
Labels: cla-signed

#470 Modified Business Intelligence page
  _docs/_partners/technology_partners/insights/business_intelligence.md
Labels: cla-signed

#471 Modified Crash Analytics page
  _docs/_partners/technology_partners/insights/crash_analytics.md
Labels: cla-signed

#421 Modified SMS pages as per example
  _docs/_partners/technology_partners/additional_channels/sms.md
Labels: cla-signed

#460 Modified Contextual location page
  _docs/_partners/technology_partners/data_augmentation/contextual_location.md
Labels: cla-signed

#468 Modified Recommendation page
  _docs/_partners/technology_partners/data_augmentation/recommendation.md
Labels: cla-signed

#417 Changed Instant Chat pages in Partners as per example.
  _docs/_partners/technology_partners/additional_channels/instant_chat.md
  _docs/_partners/technology_partners/additional_channels/instant_chat/messenger.md
Labels: cla-signed

#588 Alias only user docs
  _docs/_api/endpoints/user_data.md
  assets/js/broken_redirect_list.js
  config/nginx.conf.erb
Labels: cla-signed

#469 Modified Behavioral Analytics page
  _docs/_partners/technology_partners/insights/behavioral_analytics.md
Labels: cla-signed

#590 Zz/partner api update 201910
  _plugins/alloy_partner.rb
Labels: cla-signed

#591 release notes - October
  _docs/_help/release_notes/2019.md
  _docs/_help/release_notes/2019/october.md
  _docs/_help/release_notes/most_recent.md
Labels: cla-signed

#582 Remove dead eclipse link and fix deprecation warning
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
  _docs/_help/release_notes/deprecations.md
  _docs/_help/release_notes/deprecations/eclipse_setup_deprecated.md
Labels: cla-signed

#586 Update max size for content cards with calculation
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
Labels: cla-signed

#592 Remaining TP Landing Pages
  _docs/_partners/home.md
  _docs/_partners/technology_partners/additional_channels.md
  _docs/_partners/technology_partners/additional_channels/direct_mail.md
  _docs/_partners/technology_partners/additional_channels/mobile_wallet.md
  _docs/_partners/technology_partners/advertising_technologies.md
  _docs/_partners/technology_partners/channel_extensions.md
  _docs/_partners/technology_partners/channel_extensions/workflow_automation.md
  _docs/_partners/technology_partners/data_and_infrastructure_agility.md
  _docs/_partners/technology_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/technology_partners/data_augmentation.md
  _docs/_partners/technology_partners/insights.md
Labels: cla-signed

#595 Add markdown embed option to pages
  _config.yml
  _layouts/partner_page.html
  _plugins/alloy_partner.rb
  _plugins/markdown_embed.rb
Labels: cla-signed

#602 Small Visual Tweaks
  assets/css/_user_guide.scss
Labels: cla-signed

#601 Small tweaks to header styling
  assets/css/_content.scss
Labels: cla-signed, hacktober

#599 glossary style tweaks
  assets/css/_glossary_page.scss
Labels: cla-signed

#600 Footer: Making prev/next buttons smaller
  assets/css/_bottom_nav.scss
Labels: cla-signed

#581 Fix outdated FcmReceiver troubleshooting steps
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/troubleshooting.md
Labels: cla-signed

#580 Fix abButtonId capitalization in example
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
Labels: cla-signed

#579 Update outdated references to slideups
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/fireos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/unity/Analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _includes/archive/apple/initial_setup.md
Labels: cla-signed

#578 Fix outdated social media data collection information
  _docs/_developer_guide/platform_integration_guides/ios/analytics/social_data_tracking.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/carthage_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/optional_idfa_collection.md
  _includes/archive/apple/initial_setup.md
Labels: cla-signed

#594 PC-1437 - Updated Android uninstall tracking docs to mention firebase messaging service
  _docs/_developer_guide/platform_integration_guides/android/analytics/uninstall_tracking.md
Labels: cla-signed

#603 [Trivial] Fix Javadoc instances, add a few code backticks
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/setting_custom_attributes.md
Labels: cla-signed

#576 Remove references to Bio
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/unity/Analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/setting_custom_attributes.md
Labels: cla-signed

#577 Correct name of Hello Appboy
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/runtime_configuration.md
  _docs/_developer_guide/platform_integration_guides/android/sample_apps.md
  _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/runtime_configuration.md
  _docs/_developer_guide/platform_integration_guides/fireos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/fireos/sample_apps.md
Labels: cla-signed

#573 Remove additional feedback references, remove references to Honeycomb
  _docs/_api/endpoints/messaging.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/localization.md
  _docs/_developer_guide/platform_integration_guides/android/customer_feedback.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/customization.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/advanced_settings.md
  _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/localization.md
  _docs/_developer_guide/platform_integration_guides/fireos/customer_feedback.md
  _docs/_developer_guide/platform_integration_guides/fireos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/fireos/news_feed.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options.md
  _includes/archive/cordova/cordova_sdk_integration_template.md
Labels: cla-signed

#574 Fix tabbing in code examples
  _docs/_api/endpoints/messaging.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/customization.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration_baidu.md
  _docs/_developer_guide/platform_integration_guides/android/sample_apps.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/fireos/news_feed.md
  _docs/_developer_guide/platform_integration_guides/fireos/sample_apps.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/web/amp_support.md
  _docs/_hidden/private_betas/email_blacklist_endpoint.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/setting_default_values.md
  _includes/archive/cordova/cordova_sdk_integration_template.md
Labels: cla-signed

#570 Remove outdated SDWebImage warning
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options.md
Labels: cla-signed

#572 [Trivial] Fix IAM references
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
  _docs/_help/best_practices/client_integration_gallery.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/testing.md
Labels: cla-signed

#571 Make Carthage docs not dependent on outdated hardcoded version
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/carthage_integration.md
Labels: cla-signed

#569 Remove references to iOS 8 and below
  _docs/_developer_guide/platform_integration_guides/cordova/ios/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/action_buttons.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/advanced_settings.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _docs/_help/best_practices/push/message_format.md
  _includes/archive/apple/initial_setup.md
Labels: cla-signed

#568 Add information about provisional auth to the user guide
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
Labels: cla-signed

#563 Add swift example to tvos docs
  _docs/_developer_guide/platform_integration_guides/tvos/news_feed.md
Labels: cla-signed

#560 [Trivial] Update all platforms to have same warning boxes for changeUser
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/setting_user_ids.md
Labels: cla-signed

#565 Replace APNS instances with APNs
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/rich.md
  _docs/_help/best_practices/push/push_reporting.md
  _docs/_user_guide/data_and_analytics/tracking/uninstall_tracking.md
  _docs/_user_guide/message_building_by_channel/push/ios_customizable_app_icon_feature.md
Labels: cla-signed

#562 Fix a few its and spelling
  _docs/_api/endpoints/export.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration_baidu.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/tvos/news_feed.md
  _docs/_help/best_practices/client_integration_gallery.md
  _docs/_help/release_notes/deprecations.md
  _docs/_user_guide/administrative/app_settings/developer_console/event_user_log_tab.md
  _docs/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md
  _docs/_user_guide/data_and_analytics/custom_data.md
  _docs/_user_guide/data_and_analytics/tracking/influenced_opens.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/content_cards/testing.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/testing.md
  _docs/_user_guide/onboarding_with_braze/integration.md
Labels: cla-signed

#561 [Trivial] Fix apptimize example indentation
  _docs/_help/release_notes/deprecations/apptimize.md
Labels: cla-signed

#559 Add Kotlin support to Setting Custom Attributes page
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/setting_custom_attributes.md
Labels: cla-signed

#540 Add Swift examples to IAM delivery page
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md
Labels: cla-signed

#538 Add Swift examples to IAM customization page
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
Labels: cla-signed

#541 Add Swift examples to social docs
  _docs/_developer_guide/platform_integration_guides/ios/analytics/social_data_tracking.md
Labels: cla-signed

#544 Swift examples for location and gimbal docs
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/beacon_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/location_tracking.md
Labels: cla-signed

#575 Remove references to UIWebView
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
Labels: cla-signed

#535 Add additional URL Linking and Content Cards examples in Swift
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/data_model.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/refreshing_the_feed.md
Labels: cla-signed

#607 Update custom_events.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
Labels: cla-signed

#610 Update push home page
  _docs/_user_guide/message_building_by_channel/push.md
Labels: cla-signed

#609 Update onboarding_with_braze.md
  _docs/_user_guide/onboarding_with_braze.md
Labels: cla-signed

#617 Remove references to Android SDK 1.14.0
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/customization.md
  _docs/_developer_guide/platform_integration_guides/fireos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/fireos/news_feed.md
Labels: cla-signed

#616 Remove references to 3.5 year old Unity SDK releases
  _docs/_developer_guide/platform_integration_guides/unity/Analytics/logging_custom_events.md
  _docs/_developer_guide/platform_integration_guides/unity/Analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/unity/android/sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/unity/ios/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/unity/ios/sdk_integration.md
Labels: cla-signed

#615 Remove outdated Xamarin IDE screenshots
  _docs/_developer_guide/platform_integration_guides/xamarin/android_and_fireos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/xamarin/ios/sdk_integration.md
  assets/img_archive/xamarin_android_project.png
  assets/img_archive/xamarin_ios_project.png
Labels: cla-signed

#611 Split "choose platform" out as its own step, step1
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
Labels: cla-signed, hacktober, hacktoberfest, type: content

#614 Update content cards limit description
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
Labels: cla-signed

#620 Update Transifex Documentation
  _docs/_partners/technology_partners/channel_extensions/localization/transifex.md
Labels: cla-signed

#622 Canvas Variants
  _docs/_help/release_notes/2019/october.md
  _docs/_help/release_notes/most_recent.md
  _docs/_user_guide/engagement_tools/canvas/get_started/measuring_and_testing_with_canvas_analytics.md
  assets/img/canvas_var_analysis.png
Labels: cla-signed

#626 Update news_feed_categories.md
  _docs/_user_guide/engagement_tools/news_feed/news_feed_categories.md
Labels: cla-signed

#619 Update integration.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
Labels: cla-signed, hacktober, hacktoberfest

#618 Neura partnership integration documentation updates and additions
  _docs/_partners/technology_partners/data_augmentation/contextual_location/neura.md
  _docs/_partners/technology_partners/data_augmentation/contextual_location/neura_actions.md
  _docs/_partners/technology_partners/insights/behavioral_analytics/neura_insights.md
  assets/img/action-based-delivery.png
  assets/img/insights-bubble-graph.png
  assets/img/insights-moments-personas.png
  assets/img/moments-of-availability.png
  assets/img/neura-braze-api-key.png
  assets/img/segment-creation.png
Labels: cla-signed, hacktober, hacktoberfest

#623 Update message_engagement_events.md
  _docs/_partners/braze_currents/data_storage_events/message_engagement_events.md
Labels: cla-signed, hacktober, hacktoberfest

#528 App Version Code docs
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/new_features.md
Labels: cla-signed, hacktober, hacktoberfest

#613 Revamped the IAM Generations Table, new mockup
  _docs/_user_guide/message_building_by_channel/in-app_messages/generations.md
  assets/img/iam-generations-of-modals.png
Labels: cla-signed, hacktober, hacktoberfest, type: content

#608 Updating multiple feeds page for developer guide's content card section
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/data_model.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/multiple_feeds.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
Labels: cla-signed, hacktober, hacktoberfest

#627 Neura adds to TP Home
  _docs/_partners/home.md
  _docs/_partners/technology_partners/data_augmentation.md
  _docs/_partners/technology_partners/data_augmentation/contextual_location.md
  _docs/_partners/technology_partners/data_augmentation/contextual_location/neura_actions.md
  _docs/_partners/technology_partners/insights.md
  _docs/_partners/technology_partners/insights/behavioral_analytics.md
  _docs/_partners/technology_partners/insights/behavioral_analytics/neura_insights.md
Labels: cla-signed

#514 [do not merge until 10/22] ad-ids-update
  _docs/_api/endpoints/export.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/optional_gaid_collection.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: cla-signed, hacktober, hacktoberfest

#628 App Version Add to Segmentation Filters
  _docs/_developer_guide/platform_integration_guides/ios/content_cards.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#630 Hacktober Final Deploy!
  _docs/_api/endpoints/export.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/optional_gaid_collection.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/data_model.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/multiple_feeds.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
  _docs/_partners/braze_currents/data_storage_events/message_engagement_events.md
  _docs/_partners/home.md
  _docs/_partners/technology_partners/data_augmentation.md
  _docs/_partners/technology_partners/data_augmentation/contextual_location.md
  _docs/_partners/technology_partners/data_augmentation/contextual_location/neura.md
  _docs/_partners/technology_partners/data_augmentation/contextual_location/neura_actions.md
  _docs/_partners/technology_partners/insights.md
  _docs/_partners/technology_partners/insights/behavioral_analytics.md
  _docs/_partners/technology_partners/insights/behavioral_analytics/neura_insights.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/new_features.md
  _docs/_user_guide/engagement_tools/news_feed/news_feed_categories.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/generations.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  assets/img/action-based-delivery.png
  assets/img/iam-generations-of-modals.png
  assets/img/insights-bubble-graph.png
  assets/img/insights-moments-personas.png
  assets/img/moments-of-availability.png
  assets/img/neura-braze-api-key.png
  assets/img/segment-creation.png
Labels: cla-signed
