Repository braze-inc/braze-docs, pull requests merged in 2019-09, with the labels that each got.

#345 Customer Example Gallery
  _docs/_help/best_practices/client_integration_gallery.md
  assets/img/iheart_trials+npp_email.png
Labels: CONTRACTOR, cla-signed, status: in progress

#375 Notch and Creative IAM Updates
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/fullscreen.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/modal.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/slideup.md
  assets/img/full-screen-behavior.gif
  assets/img/full-screen-spec-notched.png
  assets/img/slideup-large-viewport2.png
Labels: cla-signed

#376 Customer Example Library Update
  _docs/_help/best_practices/client_integration_gallery.md
  assets/img/1800flowersalertspush.jpg
  assets/img/1800flowersrichpushlemonade.jpg
  assets/img/_DS_Store
  assets/img/airtimepushpushactionbuttonsemojis.jpeg
  assets/img/bhnppwebpush.png
  assets/img/clarityalertspush.png
  assets/img/claritymoneypushpersonalization.jpg
  assets/img/deliveroodeliverupdatepushcominghome.png
  assets/img/deliveroodeliveryupdatesvoucherpush.png
  assets/img/deliveryherowearablepushweatherpersonalization.png
  assets/img/dominosandroidpushrichnotification.png
  assets/img/dominosvouchernewsfeedcoupon.png
  assets/img/dotsconpppushtreasure1.png
  assets/img/foodpandaalertsvoucherpcmnewsfeed.jpg
  assets/img/gettcustomersurveyiam.jpg
  assets/img/gettvoucherreferiam.jpg
  assets/img/grubhubalertsemail.PNG
  assets/img/headspacenppalertsiam.png
  assets/img/hingealertspush.png
  assets/img/ibottaemailbirthdaypersonalization.png
  assets/img/ibottaonboardingconfirmationemail.PNG
  assets/img/ibottaonboardingnutiam.PNG
  assets/img/ibottaonboardingvoucheremailgreen.png
  assets/img/ibottaprimingpush.png
  assets/img/ibottavoucherpush10bonus.PNG
  assets/img/ibottavoucherreferpushactionbuttons.png
  assets/img/iheart_trials+npp_email.png
  assets/img/iheartemailpersonalizedradiostation.png
  assets/img/iheartibmpromotional.png
  assets/img/iheartprimingiam.png
  assets/img/ihearttrialsnppemail.png
  assets/img/iheartvoucherpaywallemail.png
  assets/img/lyftcustomersurveyemail.png
  assets/img/lyftmilestoneemail.png
  assets/img/lyftpcmalertspush.png
  assets/img/mytaxialertspush.jpg
  assets/img/mytaxiprimingiamemail.png
  assets/img/namshionboardingvoucherpush.jpeg
  assets/img/resqmilestoneemail.png
  assets/img/shutterflyrichpushpromotional.jpeg
  assets/img/soulcyclepushemojitesting.jpg
  assets/img/soundcloudgoproductrecemail.png
  assets/img/souqnewsfeedbeautyweek.jpg
  assets/img/uoalertspushdress1.png
  assets/img/uoalertspushpersonalized.jpg
  assets/img/uoalertswebibm.png
  assets/img/uoibmmobileweb.jpg
  assets/img/venmopcmnppemail.png
  assets/img/viberalertsvoucherviberpush.jpg
  assets/img/wagvoucheronboardingemail.png
  assets/img/westwingalertswebibm.png
  assets/img/yelpproductrecpushgf.png
  assets/img/yelpproductrecpushrich.png
Labels: CONTRACTOR, cla-signed

#378 Apptimize Deprecation
  _docs/_help/release_notes/deprecations.md
  _docs/_help/release_notes/deprecations/apptimize.md
  _docs/_help/release_notes/deprecations/eclipse_setup_deprecated.md
  _docs/_partners/home.md
  _docs/_partners/technology_partners/channel_extensions/ab_testing.md
Labels: cla-signed

#373 Added data type for should_inline_css
  _docs/_api/endpoints/email_templates.md
Labels: cla-signed

#380 Content Block API Updates
  _docs/_api/endpoints/email_sync.md
  _docs/_api/endpoints/email_templates.md
  _docs/_api/endpoints/export.md
  _docs/_api/endpoints/messaging.md
  _docs/_api/endpoints/subscription_group_api.md
Labels: cla-signed

#381 remove completion date
  _docs/_hidden/other/documentation_request.md
Labels: cla-signed

#379 AMP Metrics Update
  _docs/_hidden/private_betas/amphtml.md
Labels: cla-signed

#382 Leftovers - September 5, 2019
  _docs/_api/endpoints/email_sync.md
  _docs/_api/endpoints/email_templates.md
  _docs/_api/endpoints/export.md
  _docs/_api/endpoints/messaging.md
  _docs/_api/endpoints/subscription_group_api.md
  _docs/_help/release_notes/deprecations.md
  _docs/_help/release_notes/deprecations/apptimize.md
  _docs/_help/release_notes/deprecations/eclipse_setup_deprecated.md
  _docs/_hidden/other/documentation_request.md
  _docs/_hidden/private_betas/amphtml.md
  _docs/_partners/home.md
  _docs/_partners/technology_partners/channel_extensions/ab_testing.md
Labels: cla-signed

#388 Fixed Braze API key to be Docs API key
  Archive/academy/_config.yml
  Archive/academy/_site/404.html
  Archive/documentation/_config.yml
  Archive/documentation/_site/404.html
Labels: cla-signed

#387 Canvas Changelogs
  _docs/_help/release_notes/2019/september.md
  _docs/_help/release_notes/most_recent.md
Labels: cla-signed

#386 Firebrands Links
  _docs/_help/best_practices/client_integration_gallery.md
  _docs/_help/faqs.md
  _docs/_partners/home.md
  _docs/_user_guide/onboarding_with_braze/integration.md
Labels: cla-signed

#383 Added link to Pre-populating Custom Data Types
  _docs/_user_guide/data_and_analytics/custom_data/pre-populating_custom_data.md
Labels: cla-signed

#389 Dummy User Detection
  _docs/_help/faqs.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/user_data_collection/collection_use_case.md
  _docs/_user_guide/data_and_analytics/user_data_collection/data_collected_by_default.md
  _docs/_user_guide/data_and_analytics/user_data_collection/overview.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_archival.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
Labels: cla-signed

#390 WKWebView change
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/overview.md
Labels: cla-signed

#384 iOS Restructure p1
  _docs/_developer_guide/home.md
  _docs/_developer_guide/platform_integration_guides/ios.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/beacon_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/fine_network_traffic_control.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/localization.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/manual_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/social_data_tracking.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/badges.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/data_model.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/read_unread_indicators.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/refreshing_the_feed.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/carthage_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options.md
  _docs/_developer_guide/platform_integration_guides/ios/news_feed.md
  _docs/_developer_guide/platform_integration_guides/ios/news_feed/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/action_buttons.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/advanced_settings.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/rich.md
  _docs/_developer_guide/platform_integration_guides/sdk_changelogs.md
  _includes/archive/troubleshooting_iams.md
  assets/css/_content.scss
  assets/img/carthage.jpeg
  assets/img/cocoapods.png
Labels: cla-signed

#413 Support Contact: added firefox blocking banner, updated thank you message
  _docs/_hidden/other/support_contact.md
Labels: cla-signed

#403 fix code in td not wrapping
  assets/css/_content.scss
Labels: cla-signed

#396 Edit github button
  _config.yml
  _includes/feedback.html
  assets/css/_feedback.scss
  assets/img/GitHub-Mark-32px.png
  assets/js/documents.js
Labels: cla-signed

#407 remove sourcemap reference
  assets/js/bootstrap.js
  assets/js/swagger/swagger_ui.js
  assets/js/swagger/swagger_ui_bundle.js
  assets/js/swagger/swagger_ui_standalone_preset.js
  assets/js/swiper.js
Labels: cla-signed

#408 [Cordova Docs] added location collection docs for cordova
  _docs/_developer_guide/platform_integration_guides/cordova/android_and_fireos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/cordova/ios/initial_sdk_setup.md
Labels: cla-signed

#409 added blacklist docs for android iams
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
Labels: cla-signed

#414 Weekly Deploy - September 17, 2019
  _config.yml
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/cordova/android_and_fireos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/cordova/ios/initial_sdk_setup.md
  _docs/_hidden/other/support_contact.md
  _includes/feedback.html
  assets/css/_content.scss
  assets/css/_feedback.scss
  assets/img/GitHub-Mark-32px.png
  assets/js/bootstrap.js
  assets/js/documents.js
  assets/js/swagger/swagger_ui.js
  assets/js/swagger/swagger_ui_bundle.js
  assets/js/swagger/swagger_ui_standalone_preset.js
  assets/js/swiper.js
Labels: cla-signed

#418 Number Correction in Snowflake Doc
  _docs/_partners/technology_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
Labels: cla-signed

#293 example of using the default factory getter and enums
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
Labels: cla-signed

#420 Canvas Create_Send - HIDDEN
  _docs/_hidden/private_betas/create_send.md
Labels: cla-signed

#419 Leftovers - September 20, 2019
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
  _docs/_hidden/private_betas/create_send.md
  _docs/_partners/technology_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
Labels: cla-signed

#410 [Android] Content Card bespoke feed
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/data_models.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/multiple_feeds.md
Labels: cla-signed

#425 Add note about returning dispatch_id in the API response body
  _docs/_api/endpoints/messaging.md
Labels: cla-signed

#424 Add dispatch_id for Currents Push events in all destinations
  _docs/_partners/braze_currents/data_storage_events/message_engagement_events.md
  _docs/_partners/technology_partners/insights/behavioral_analytics/amplitude_for_currents.md
  _docs/_partners/technology_partners/insights/behavioral_analytics/mixpanel_for_currents.md
Labels: cla-signed

#429 Clarify that `appboy://action` schema is only supported in mobile app SDKs
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
Labels: cla-signed

#364 Cleanup some analytics definitions
  _docs/_user_guide/data_and_analytics/report_metrics.md
Labels: cla-signed

#430 Custom Content Card Feed
  _docs/_developer_guide/platform_integration_guides/android/content_cards/multiple_feeds.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/multiple_feeds.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
Labels: cla-signed

#426 Hacktober page
  _docs/_help/help_articles/docs/contribution.md
  _docs/_help/help_articles/docs/hacktober_2019.md
Labels: cla-signed

#406 onelogin
  _docs/_user_guide/administrative/access_braze/single_sign_on/onelogin.md
  assets/img/onelogin_1.png
  assets/img/onelogin_2.png
  assets/img/onelogin_3.png
  assets/img/onelogin_4.png
  assets/img/onelogin_5.png
  assets/img/onelogin_6.png
Labels: cla-signed

#422 roktcalendar
  _docs/_partners/home.md
  _docs/_partners/technology_partners/channel_extensions/calendar.md
  _docs/_partners/technology_partners/channel_extensions/calendar/rokt_calendar.md
  assets/img/rokt_generating_audience.png
Labels: cla-signed

#432 passkit-doc
  _docs/_partners/technology_partners/additional_channels/mobile_wallet.md
  _docs/_partners/technology_partners/additional_channels/mobile_wallet/passkit.md
Labels: cla-signed

#433 Release Notes - September 24, 2019
  _docs/_help/release_notes/2019/september.md
  _docs/_help/release_notes/most_recent.md
  _docs/_partners/home.md
Labels: cla-signed

#438 Swap Blank and Is Not Blank BD-236
  _docs/_developer_guide/platform_wide/analytics_overview.md
Labels: cla-signed

#441 Grammar Fix on Global Sub States Page - BD-317
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#443 Add LTR to Hacktober leaderboard
  _docs/_help/help_articles/docs/hacktober_2019.md
Labels: cla-signed

#440 Blacklist Page Redirect
  assets/js/broken_redirect_list.js
Labels: cla-signed

#445 Dispatch ID Note
  _docs/_help/help_articles/data/dispatch_id.md
Labels: cla-signed

#447 Em/ios13 email
  _docs/_hidden/other/email_private_relay_apple.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  assets/img/email-relay-dns-records.png
  assets/img/email-relay-whitelabel-address.png
Labels: cla-signed

#444 Rokt updates
  _docs/_partners/technology_partners/additional_channels/calendar.md
  _docs/_partners/technology_partners/additional_channels/calendar/rokt_calendar.md
Labels: cla-signed

#448 Leftovers - September 26, 2019
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_help/help_articles/data/dispatch_id.md
  _docs/_help/help_articles/docs/hacktober_2019.md
  _docs/_hidden/other/email_private_relay_apple.md
  _docs/_partners/technology_partners/additional_channels/calendar.md
  _docs/_partners/technology_partners/additional_channels/calendar/rokt_calendar.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  assets/img/email-relay-dns-records.png
  assets/img/email-relay-whitelabel-address.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#449 Fix broken link to braze documentation
  readme.md
Labels: cla-signed

#450 Email Relay Revision
  _docs/_hidden/other/email_private_relay_apple.md
  _docs/_partners/technology_partners/additional_channels/mobile_wallet/passkit.md
Labels: cla-signed

#454 Leftovers 2 - September 27, 2019
  _docs/_hidden/other/email_private_relay_apple.md
  _docs/_partners/technology_partners/additional_channels/mobile_wallet/passkit.md
  readme.md
Labels: cla-signed

#336 API Glossary list page
  _docs/_home/api_glossary.md
  _layouts/api_page.html
  _plugins/api.rb
  assets/css/_api.scss
  assets/css/application.scss
Labels: cla-signed
