Repository braze-inc/braze-docs, pull requests merged in 2019-08, with the labels that each got.

#285 Interactive images
  _docs/_home/styling_test_page.md
Labels: cla-signed

#286 281 Frequency Capping Updates
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/rate-limiting.md
Labels: cla-signed

#288 Leftovers - August 1, 2019
  _docs/_home/styling_test_page.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/rate-limiting.md
Labels: cla-signed

#290 Delete google_advertising_id.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/google_advertising_id.md
Labels: cla-signed

#291 Leftovers
  _docs/_developer_guide/platform_integration_guides/android/analytics/google_advertising_id.md
Labels: cla-signed

#294 PC-1228 manual processing policy
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/fine_network_traffic_control.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/locations_and_geofences.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/mobile_integrations.md
Labels: cla-signed

#292 Hide hidden pages from indexing
  _plugins/noindex.rb
Labels: cla-signed

#298 Weekly Deploy - August 6, 2019
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/fine_network_traffic_control.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/locations_and_geofences.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/mobile_integrations.md
  _plugins/noindex.rb
Labels: cla-signed

#299 PR and Issue Template Edits
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla-signed

#302 Update amplitude_for_currents.md
  _docs/_partners/technology_partners/insights/behavioral_analytics/amplitude_for_currents.md
Labels: cla-signed

#301 sso-updates
  _docs/_user_guide/administrative/access_braze/single_sign_on/okta.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/onelogin.md
Labels: cla-signed

#306 Fix API overview link referenece
  _docs/_site_pages/api.md
Labels: cla-signed

#305 Added Looker UTM Parameters to Domains
  _docs/_partners/braze_currents/advanced_topics/how_braze_uses_currents.md
  _docs/_partners/braze_currents/advanced_topics/s3_to_snowflake.md
  _docs/_partners/technology_partners/insights/business_intelligence/looker.md
Labels: cla-signed

#304 Broken Liquid Link Fix
  _includes/archive/in_app_message.md
Labels: cla-signed

#303 Update postman_collection.md
  _docs/_api/postman_collection.md
Labels: cla-signed

#136 Cache Correction
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
Labels: cla-signed, status: in progress

#308 SXSW Page
  _docs/_hidden/other/sxsw.md
  assets/img/sxsw-vote.png
Labels: cla-signed

#309 Leftovers - August 8, 2019
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  _docs/_api/postman_collection.md
  _docs/_hidden/other/sxsw.md
  _docs/_partners/braze_currents/advanced_topics/how_braze_uses_currents.md
  _docs/_partners/braze_currents/advanced_topics/s3_to_snowflake.md
  _docs/_partners/technology_partners/insights/behavioral_analytics/amplitude_for_currents.md
  _docs/_partners/technology_partners/insights/business_intelligence/looker.md
  _docs/_site_pages/api.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/okta.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/onelogin.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
  _includes/archive/in_app_message.md
  assets/img/sxsw-vote.png
Labels: cla-signed

#311 Jira List: Links, Typos, Corrections
  Archive/documentation/_site/redirect_list.js
  _docs/_api/basics.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/uninstall_tracking.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_templates.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/silent_push_notifications.md
  _docs/_developer_guide/platform_wide/platform_features.md
  _docs/_help/release_notes/2016/june.md
  _docs/_help/release_notes/2017/april.md
  _docs/_help/release_notes/2017/august.md
  _docs/_help/release_notes/2017/february.md
  _docs/_help/release_notes/2017/january.md
  _docs/_help/release_notes/2017/july.md
  _docs/_help/release_notes/2017/june.md
  _docs/_help/release_notes/2017/may.md
  _docs/_help/release_notes/2017/november.md
  _docs/_help/release_notes/2017/october.md
  _docs/_help/release_notes/2017/september.md
  _docs/_help/release_notes/2018/august.md
  _docs/_help/release_notes/2018/november.md
  _docs/_hidden/redirects/creating_an_in-app_message.md
  _docs/_partners/technology_partners/additional_channels/direct_mail/inkit.md
  _docs/_user_guide/administrative/access_braze/braze_instances.md
  _docs/_user_guide/administrative/app_settings/developer_console/event_user_log_tab.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/new_features.md
  _docs/_user_guide/onboarding_with_braze/learning_to_use_braze.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/conditional_logic.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/operators.md
  _includes/archive/in_app_message.md
  assets/img/abort-if.png
  assets/img/liquid-if-elsif-games.png
  assets/img/liquid-if-totalspend.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#313 Typos
  _docs/_user_guide/personalization_and_dynamic_content/liquid/operators.md
Labels: cla-signed

#314 Leftovers - Mass Link Fixes
  Archive/documentation/_site/redirect_list.js
  _docs/_api/basics.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/uninstall_tracking.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_templates.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/silent_push_notifications.md
  _docs/_developer_guide/platform_wide/platform_features.md
  _docs/_help/release_notes/2016/june.md
  _docs/_help/release_notes/2017/april.md
  _docs/_help/release_notes/2017/august.md
  _docs/_help/release_notes/2017/february.md
  _docs/_help/release_notes/2017/january.md
  _docs/_help/release_notes/2017/july.md
  _docs/_help/release_notes/2017/june.md
  _docs/_help/release_notes/2017/may.md
  _docs/_help/release_notes/2017/november.md
  _docs/_help/release_notes/2017/october.md
  _docs/_help/release_notes/2017/september.md
  _docs/_help/release_notes/2018/august.md
  _docs/_help/release_notes/2018/november.md
  _docs/_hidden/redirects/creating_an_in-app_message.md
  _docs/_partners/technology_partners/additional_channels/direct_mail/inkit.md
  _docs/_user_guide/administrative/access_braze/braze_instances.md
  _docs/_user_guide/administrative/app_settings/developer_console/event_user_log_tab.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/new_features.md
  _docs/_user_guide/onboarding_with_braze/learning_to_use_braze.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/conditional_logic.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/operators.md
  _includes/archive/in_app_message.md
  assets/img/abort-if.png
  assets/img/liquid-if-elsif-games.png
  assets/img/liquid-if-totalspend.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#318 Add Line Break between Alert Header and content
  _plugins/alert_tag.rb
Labels: cla-signed

#317 Dispatch ID Details
  _docs/_help/help_articles/data/dispatch_id.md
  _docs/_help/release_notes/2019/july.md
  _docs/_help/release_notes/2019/may.md
  _docs/_help/release_notes/most_recent.md
  _docs/_partners/braze_currents/data_storage_events/message_engagement_events.md
  _docs/_partners/technology_partners/data_and_infrastructure_agility/customer_data_platform/segment_for_currents.md
  _docs/_partners/technology_partners/insights/behavioral_analytics/amplitude_for_currents.md
  _docs/_partners/technology_partners/insights/behavioral_analytics/mixpanel_for_currents.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: cla-signed

#315 Advancement Behavior Correction
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/advancement.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
Labels: status: done

#300 Add documentation for unsetting custom notification factory
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
Labels: cla-signed

#319 voucherify-api-url
  _docs/_partners/technology_partners/channel_extensions/loyalty/voucherify.md
Labels: cla-signed

#316 Fixes typo in Content Cards code example
  _docs/_developer_guide/platform_integration_guides/web/content_cards/integration.md
Labels: cla-signed

#312 remove-feedback
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/localization.md
  _docs/_developer_guide/platform_integration_guides/android/customer_feedback.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/integration_overview.md
  _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/localization.md
  _docs/_developer_guide/platform_integration_guides/fireos/customer_feedback.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/localization.md
  _docs/_developer_guide/platform_integration_guides/ios/customer_feedback.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/customer_feedback.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/customer_feedback.md
  _docs/_developer_guide/platform_integration_guides/unity/news_feed.md
  _docs/_developer_guide/platform_integration_guides/xamarin/android_and_fireos/customer_feedback.md
  _docs/_developer_guide/platform_integration_guides/xamarin/ios/customer_feedback.md
  _docs/_developer_guide/platform_wide/platform_features.md
  _docs/_partners/technology_partners/data_and_infrastructure_agility/customer_data_platform/segment.md
  _docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#289 Android - Update docs for disable location collection by default.
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/location_tracking.md
Labels: cla-signed, status: done

#310 create-send
  _docs/_hidden/private_betas/create_send.md
Labels: cla-signed, priority: 0

#296 Snowflake Fixes and Updates
  _docs/_partners/braze_currents/advanced_topics/s3_to_snowflake.md
  _docs/_partners/technology_partners/data_and_infrastructure_agility/data_warehouses/amazon_s3.md
  _docs/_partners/technology_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
Labels: cla-signed

#325 Edited to remove references to aliases
  _docs/_hidden/private_betas/create_send.md
Labels: cla-signed

#324 fix alert spacing within details
  assets/css/_alerts.scss
Labels: cla-signed

#322 Delete feedback styles
  _docs/_developer_guide/platform_integration_guides/android/news_feed/customization.md
  _docs/_developer_guide/platform_integration_guides/fireos/news_feed.md
Labels: cla-signed

#327 Leftovers - August 15, 2019
  _docs/_developer_guide/platform_integration_guides/android/news_feed/customization.md
  _docs/_developer_guide/platform_integration_guides/fireos/news_feed.md
  _docs/_hidden/private_betas/create_send.md
  assets/css/_alerts.scss
Labels: cla-signed

#332 Wording Adjustment in Create_Send
  _docs/_hidden/private_betas/create_send.md
Labels: cla-signed

#329 PC-1266 iOS endpoint updates
  _docs/_developer_guide/eu01_us3_sdk_implementation_differences/for_ios.md
  _includes/archive/apple/initial_setup.md
Labels: cla-signed

#333 Segment Integrations Issues and Event Naming Conventions Articles
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/analytics/logging_custom_events.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/analytics/logging_custom_events.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/logging_custom_events.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/tvos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/unity/Analytics/logging_custom_events.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/logging_custom_events.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/logging_purchases.md
  _docs/_partners/technology_partners/data_and_infrastructure_agility/customer_data_platform/segment.md
  _docs/_user_guide/data_and_analytics/custom_data/event_naming_conventions.md
  _docs/_user_guide/data_and_analytics/custom_data/pre-populating_custom_data.md
  _docs/_user_guide/onboarding_with_braze/integration.md
Labels: cla-signed

#328 Update Xamarin+Android endpoint instructions
  _docs/_developer_guide/eu01_us3_sdk_implementation_differences/for_android.md
Labels: cla-signed

#334 Leftovers - August 16, 2019
  _docs/_developer_guide/eu01_us3_sdk_implementation_differences/for_android.md
  _docs/_developer_guide/eu01_us3_sdk_implementation_differences/for_ios.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/analytics/logging_custom_events.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/analytics/logging_custom_events.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/logging_custom_events.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/tvos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/unity/Analytics/logging_custom_events.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/logging_custom_events.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/logging_purchases.md
  _docs/_hidden/private_betas/create_send.md
  _docs/_partners/technology_partners/data_and_infrastructure_agility/customer_data_platform/segment.md
  _docs/_user_guide/data_and_analytics/custom_data/event_naming_conventions.md
  _docs/_user_guide/data_and_analytics/custom_data/pre-populating_custom_data.md
  _docs/_user_guide/onboarding_with_braze/integration.md
  _includes/archive/apple/initial_setup.md
Labels: cla-signed

#341 Add files via upload
  assets/img/postman_variable.png
Labels: cla-signed

#338 Update glossary label
  _layouts/glossary_page.html
  assets/css/_glossary_page.scss
Labels: cla-signed

#335 Update FireOS and Android docs for default location collection being disabled.
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/location_tracking.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/mobile_integrations.md
Labels: cla-signed, status: done

#337 Add to Android docs Content Cards methods.
  _docs/_developer_guide/platform_integration_guides/android/content_cards/data_models.md
Labels: cla-signed, status: done

#343 Miscellaneous Fixes and Ticket Closures.
  _docs/_api/endpoints/export.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization.md
  _docs/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/change_your_canvas_after_launch.md
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_template.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md
  assets/img/with_money_filter.png
  assets/img/without_money_filter.png
Labels: cla-signed

#326 azure-ad-updates
  _docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/set_up.md
  assets/img/azure_ad1.png
  assets/img/azure_ad10.png
  assets/img/azure_ad11.png
  assets/img/azure_ad12.png
  assets/img/azure_ad13.png
  assets/img/azure_ad14.png
  assets/img/azure_ad2.png
  assets/img/azure_ad3.png
  assets/img/azure_ad4.png
  assets/img/azure_ad5.png
  assets/img/azure_ad6.png
  assets/img/azure_ad7.png
  assets/img/azure_ad8.png
  assets/img/azure_ad9.png
Labels: cla-signed

#350 Update security_qualifications with new ISO 27001 info
  _docs/_developer_guide/disclosures/security_qualifications.md
Labels: cla-signed

#349 Postman Quotes Explanation
  _docs/_api/postman_collection.md
Labels: cla-signed

#348 Voucherify Early Access
  _docs/_partners/technology_partners/channel_extensions/loyalty/voucherify.md
Labels: cla-signed

#346 Talon One Early Access
  _docs/_partners/technology_partners/channel_extensions/loyalty/talonone.md
Labels: cla-signed

#347 Fivetran Early Access
  _docs/_partners/technology_partners/channel_extensions/workflow_automation/fivetran.md
Labels: cla-signed

#352 Leftovers - August 22, 2019
  _docs/_api/postman_collection.md
  _docs/_developer_guide/disclosures/security_qualifications.md
  _docs/_partners/technology_partners/channel_extensions/loyalty/talonone.md
  _docs/_partners/technology_partners/channel_extensions/loyalty/voucherify.md
  _docs/_partners/technology_partners/channel_extensions/workflow_automation/fivetran.md
Labels: cla-signed

#369 Update page description and keywords
  _includes/html_include.html
Labels: cla-signed

#370 fixes
  _docs/_help/release_notes/2019/august.md
  _docs/_help/release_notes/most_recent.md
  _docs/_hidden/private_betas/create_send.md
  _docs/_partners/braze_currents/data_storage_events/event_delivery_sematics.md
  _docs/_partners/technology_partners/channel_extensions/loyalty/voucherify.md
Labels: cla-signed

#371 Leftovers - August 29, 2019
  _docs/_help/release_notes/2019/august.md
  _docs/_help/release_notes/most_recent.md
  _docs/_hidden/private_betas/create_send.md
  _docs/_partners/braze_currents/data_storage_events/event_delivery_sematics.md
  _docs/_partners/technology_partners/channel_extensions/loyalty/voucherify.md
  _includes/html_include.html
Labels: cla-signed
