Repository braze-inc/braze-docs, pull requests merged in 2019-07, with the labels that each got.

#217 Canvas Delay Step - Beta
  _docs/_hidden/private_betas/delay_step.md
  assets/img/canvas_delay.gif
Labels: cla-signed

#215 Add geofencing liquid syntax (#211)
  _docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: cla-signed

#214 Updated links to example `appboy.xml` and `AndroidManifest.xml`
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
Labels: cla-signed

#222 Weekly Deploy - July 2, 2019
  .github/ISSUE_TEMPLATE.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_hidden/private_betas/delay_step.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  assets/img/canvas_delay.gif
Labels: cla-signed

#223 Updated Looker Link
  _docs/_partners/technology_partners/insights/business_intelligence/looker.md
Labels: cla-signed

#224 Leftovers - July 3, 2019
  _docs/_partners/technology_partners/insights/business_intelligence/looker.md
Labels: cla-signed

#226 Update frequency_capping.md
  _docs/_hidden/private_betas/frequency_capping.md
Labels: cla-signed

#227 Leftovers - 2 - July 3, 2019
  _docs/_hidden/private_betas/frequency_capping.md
Labels: cla-signed

#231 Remove limited access banner from campaign comparisons docs
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/comparing_campaigns.md
Labels: cla-signed

#32 plist config
  _docs/_developer_guide/platform_integration_guides/ios/analytics/location_tracking.md
  _includes/archive/session_tracking.md
Labels: cla-signed

#233 Connected Content support in Content Cards
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
Labels: cla-signed

#225 AB Testing Edits
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/multivariate_testing.md
  assets/img/ab_create_1.png
  assets/img/ab_create_2.gif
  assets/img/ab_create_4.png
  assets/img/ab_create_8.png
  assets/img/intelligent_selection1.png
Labels: cla-signed

#230 Add dispatch_id to list of available campaign attributes, with note a…
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: cla-signed

#228 July Release Notes - July 9
  _docs/_api/endpoints/messaging.md
  _docs/_help/release_notes/2019/july.md
  _docs/_help/release_notes/most_recent.md
  _docs/_partners/home.md
  assets/img/null_reply-to.png
Labels: cla-signed

#235 Weekly Deploy
  _docs/_api/endpoints/messaging.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/location_tracking.md
  _docs/_help/release_notes/2019/july.md
  _docs/_help/release_notes/most_recent.md
  _docs/_partners/home.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/comparing_campaigns.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/multivariate_testing.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/connected_content_retries.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  _includes/archive/session_tracking.md
  assets/img/ab_create_1.png
  assets/img/ab_create_2.gif
  assets/img/ab_create_4.png
  assets/img/ab_create_8.png
  assets/img/intelligent_selection1.png
  assets/img/null_reply-to.png
Labels: cla-signed

#244 add image to glossary
  _layouts/glossary_page.html
Labels: cla-signed

#237 SDK Changelog Image Fix
  _docs/_developer_guide/platform_integration_guides/sdk_changelogs.md
  assets/img/cordova-icon.png
  assets/img/unity-icon.png
Labels: cla-signed

#234 Removal of Custom Endpoints Mention
  _docs/_user_guide/administrative/access_braze/sdk_endpoints.md
Labels: cla-signed

#245 Add pinned icon to list of customizable content cards images for iOS
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization.md
Labels: cla-signed

#243 Added Gallery Feature
  _docs/_home/glossary_test_page.md
  _docs/_home/styling_test_page.md
  _includes/html_include.html
  _plugins/gallery.rb
  assets/css/application.scss
  assets/css/swiper.css
  assets/css/swipercustom.scss
  assets/js/swiper.js
Labels: cla-signed

#238 Adding Broadcast Notes to Messaging
  _docs/_api/endpoints/messaging.md
Labels: cla-signed

#247 Link Fix
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
Labels: cla-signed

#248 Weekly Deploy - July 16, 2019
  _docs/_api/endpoints/messaging.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/sdk_changelogs.md
  _docs/_home/glossary_test_page.md
  _docs/_home/styling_test_page.md
  _docs/_user_guide/administrative/access_braze/sdk_endpoints.md
  _includes/html_include.html
  _layouts/glossary_page.html
  _plugins/gallery.rb
  assets/css/application.scss
  assets/css/swiper.css
  assets/css/swipercustom.scss
  assets/img/cordova-icon.png
  assets/img/unity-icon.png
  assets/js/swiper.js
Labels: cla-signed

#240 Add files via upload
  assets/img/iam-advancement-behavior.png
  assets/img/push-advancement-behavior.png
Labels: cla-signed

#241 verbiage + image update
  _docs/_hidden/private_betas/Advancement_Behavior.md
Labels: cla-signed

#239 In-App Messages in Canvas & Advancement Behavior Updates
  _docs/_hidden/private_betas/Advancement_Behavior.md
  _docs/_hidden/private_betas/advancement_behavior.md
  _docs/_hidden/private_betas/canvas_in-app_messages.md
  assets/img/iam-advancement-behavior.png
  assets/img/push-advancement-behavior.png
Labels: cla-signed

#249 Leftovers - July 17, 2019
  _docs/_hidden/private_betas/Advancement_Behavior.md
  _docs/_hidden/private_betas/advancement_behavior.md
  _docs/_hidden/private_betas/canvas_in-app_messages.md
  assets/img/iam-advancement-behavior.png
  assets/img/push-advancement-behavior.png
Labels: cla-signed

#250 Users Must Have Deptartment
  _docs/_user_guide/administrative/manage_your_braze_users/adding_users_to_your_dashboard.md
  assets/img/add-user.gif
Labels: cla-signed

#253 Link fix and Content Cards Size Note
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
Labels: cla-signed

#251 Fix some en spaces -> spaces in JSON examples
  _docs/_api/endpoints/user_data.md
Labels: cla-signed

#256 Leftovers - July 18, 2019
  _docs/_api/endpoints/user_data.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
  _docs/_user_guide/administrative/manage_your_braze_users/adding_users_to_your_dashboard.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  assets/img/add-user.gif
Labels: cla-signed

#258 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla-signed

#261 Email BP Overview
  _docs/_help/best_practices/email.md
  _docs/_help/best_practices/email/overview.md
Labels: cla-signed

#260 Update location docs to reflect changes in next release
  _docs/_developer_guide/platform_integration_guides/ios/analytics/location_tracking.md
Labels: cla-signed, status: on hold / do not merge

#254 Manual integration fix Docs update
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options.md
Labels: cla-signed

#246 Add pinned icon instructions for android
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
Labels: cla-signed

#255 Add documentation for custom handling of HTML IAMs actions in Android.
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
Labels: cla-signed

#262 Weekly Deploy - July 23, 2019
  CONTRIBUTING.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options.md
  _docs/_help/best_practices/email.md
  _docs/_help/best_practices/email/overview.md
Labels: cla-signed

#259 Update push story integration for apps using `use_frameworks!`
  _docs/_developer_guide/platform_integration_guides/ios/push_story.md
Labels: cla-signed, status: on hold / do not merge

#267 Emily necciai patch 4
  _docs/_developer_guide/platform_integration_guides/ios/push_story.md
  assets/img/iheart_trials-npp_email.png
Labels: cla-signed

#269 Sanitize algolia process to remove html tags
  _includes/search_page.html
Labels: cla-signed

#270 Leftovers - July 26, 2019
  _docs/_developer_guide/platform_integration_guides/ios/push_story.md
  _includes/search_page.html
Labels: cla-signed

#273 Fixed search function
  _includes/search_page.html
Labels: cla-signed

#268 Update braze_instances.md
  _docs/_user_guide/administrative/access_braze/braze_instances.md
Labels: cla-signed, status: done

#264 Update making_an_api_call.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
Labels: cla-signed

#274 Weekly Deploy P1 - July 30, 2019
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
  _includes/search_page.html
Labels: cla-signed

#275 July 30th Release & Fixes
  _docs/_api/basics.md
  _docs/_api/endpoints/subscription_group_api.md
  _docs/_api/postman_collection.md
  _docs/_help/release_notes/2019/july.md
  _docs/_help/release_notes/most_recent.md
  _docs/_user_guide/administrative/access_braze/braze_instances.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/capturing_lapsing_users.md
  assets/img/adjust_eventapikey.png
  assets/img/advancement_behavior_rn.png
  assets/img/campaign_details.png
  assets/img/iam-in-canvas.png
  assets/js/swagger/braze_swagger.json
Labels: cla-signed, status: done

#272 Postman Updates
  _docs/_api/postman_collection.md
Labels: cla-signed

#271 Talon one partner doc en
  _docs/_partners/technology_partners/channel_extensions/loyalty/talonone.md
  _docs/_partners/technology_partners/data_and_infrastructure_agility/data_warehouses/fivetran.md
  assets/img/fivetran_add_members_gcs.png
  assets/img/fivetran_another_aws_account.png
  assets/img/fivetran_as3_external_id.png
  assets/img/fivetran_as3_iam.png
  assets/img/fivetran_as3_select_policy.png
  assets/img/fivetran_braze_developer_console.png
  assets/img/fivetran_braze_setupform_as3.png
  assets/img/fivetran_braze_setupform_gcs.png
  assets/img/fivetran_edit_bucket_permissions_gcs.png
  assets/img/fivetran_iam_new_role.png
  assets/img/fivetran_iam_policy_json.png
  assets/img/fivetran_iam_policy_meta.png
  assets/img/fivetran_iam_policy_review.png
  assets/img/fivetran_iam_role_arn.png
  assets/img/fivetran_selectbucket_gcs.png
  assets/img/talonone_auth_header.png
  assets/img/talonone_connected_content.png
  assets/img/talonone_coupon_settings.png
  assets/img/talonone_createcoupon_url.png
  assets/img/talonone_liquid_tag.png
  assets/img/talonone_request_params.png
  assets/img/talonone_save_response.png
Labels: cla-signed, status: done

#263 Messaging and Automation in Canvas Edits
  _docs/_hidden/private_betas/advancement_behavior.md
  _docs/_hidden/private_betas/canvas_in-app_messages.md
  _docs/_hidden/redirects/advancement_behavior.md
  _docs/_hidden/redirects/canvas_in-app_messages.md
  _docs/_user_guide/engagement_tools/canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/advancement.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/branching.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/change_your_canvas_after_launch.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
  _docs/_user_guide/engagement_tools/canvas/get_started/canvas.md
Labels: cla-signed

#257 Delete flanimatedimage reference
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/carthage_integration.md
Labels: cla-signed

#277 Partners addition to home page and Five Tran fixes
  _docs/_partners/home.md
  _docs/_partners/technology_partners/channel_extensions/workflow_automation/fivetran.md
Labels: cla-signed

#279 Merge conflict fix201907
  _docs/_user_guide/administrative/access_braze/braze_instances.md
Labels: cla-signed

#283 Link Fix - RN 2
  _docs/_help/release_notes/2019/july.md
Labels: cla-signed

#210 SAML SSO
  _docs/_help/help_articles/account/locked_out.md
  _docs/_help/release_notes/2017/october.md
  _docs/_help/release_notes/2018/may.md
  _docs/_hidden/redirects/okta.md
  _docs/_user_guide/administrative/access_braze/getting_your_account.md
  _docs/_user_guide/administrative/access_braze/logging_in.md
  _docs/_user_guide/administrative/access_braze/resetting_your_password.md
  _docs/_user_guide/administrative/access_braze/single_sign_on.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/okta.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/onelogin.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/restriction.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/set_up.md
  _docs/_user_guide/administrative/logging_in_and_security.md
  _docs/_user_guide/administrative/logging_in_and_security/single_sign_on.md
  _docs/_user_guide/administrative/logging_in_and_security/single_sign_on/okta_single_sign_on.md
  _docs/_user_guide/onboarding_with_braze/learning_to_use_braze.md
  _layouts/featured.html
  assets/css/_dev_guide.scss
  assets/css/_tabs.scss
  assets/img/azure_ad.png
  assets/img/okta.png
  assets/img/onelogin.png
  assets/img/samlsso.gif
  assets/img/sso1.png
  assets/img/sso2.png
  assets/img/sso3.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, status: in progress

#282 Link Fix - RN 1
  _docs/_help/release_notes/most_recent.md
Labels: cla-signed

#284 Weekly Deploy P3 - July 31, 2019
  _docs/_help/help_articles/account/locked_out.md
  _docs/_help/release_notes/2017/october.md
  _docs/_help/release_notes/2018/may.md
  _docs/_help/release_notes/2019/july.md
  _docs/_help/release_notes/most_recent.md
  _docs/_hidden/redirects/okta.md
  _docs/_user_guide/administrative/access_braze/getting_your_account.md
  _docs/_user_guide/administrative/access_braze/logging_in.md
  _docs/_user_guide/administrative/access_braze/resetting_your_password.md
  _docs/_user_guide/administrative/access_braze/single_sign_on.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/okta.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/onelogin.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/restriction.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/set_up.md
  _docs/_user_guide/administrative/logging_in_and_security.md
  _docs/_user_guide/administrative/logging_in_and_security/single_sign_on.md
  _docs/_user_guide/administrative/logging_in_and_security/single_sign_on/okta_single_sign_on.md
  _docs/_user_guide/onboarding_with_braze/learning_to_use_braze.md
  _layouts/featured.html
  assets/css/_dev_guide.scss
  assets/css/_tabs.scss
  assets/img/azure_ad.png
  assets/img/okta.png
  assets/img/onelogin.png
  assets/img/samlsso.gif
  assets/img/sso1.png
  assets/img/sso2.png
  assets/img/sso3.png
  assets/js/broken_redirect_list.js
Labels: cla-signed
