Repository braze-inc/braze-docs, pull requests merged in 2020-07, with the labels that each got.

#1292 minor endpoint typo edit
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
Labels: cla-signed

#1294 BD-586
  _docs/_help/faqs.md
Labels: cla-signed

#1296 Update initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/xamarin/android_and_fireos/initial_sdk_setup.md
Labels: cla-signed

#1297 Delete customer_feedback.md
  _docs/_developer_guide/platform_integration_guides/xamarin/android_and_fireos/customer_feedback.md
Labels: cla-signed

#1295 Add doc for unique email clicks sample query
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake/sample_queries.md
Labels: cla-signed

#1298 BD-589: Editing Campaigns Post Launch added
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/change_your_campaign_after_launch.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/scheduling_your_campaign.md
Labels: cla-signed

#1299 BD-587: Clarifying API Key as App Identifier Key in integrations
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods.md
Labels: cla-signed

#1301 Leftover Deploy - July 2, 2020
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods.md
  _docs/_developer_guide/platform_integration_guides/xamarin/android_and_fireos/customer_feedback.md
  _docs/_developer_guide/platform_integration_guides/xamarin/android_and_fireos/initial_sdk_setup.md
  _docs/_help/faqs.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake/sample_queries.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/change_your_campaign_after_launch.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/scheduling_your_campaign.md
Labels: Deploy, cla-signed

#1300 Added data type coercion table
  _docs/_user_guide/administrative/app_settings/manage_app_group/custom_event_and_attribute_management.md
Labels: cla-signed

#1302 remove "preview" from Flutter SDK
  _docs/_developer_guide/platform_integration_guides/flutter/preview.md
Labels: cla-signed

#1305 Include documentation for abs filter
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
Labels: cla-signed

#1303 [iOS Docs] Manual Integration step update for versions after 3.24.0
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options.md
Labels: cla-signed

#1306 Update kochava.md
  _docs/_partners/advertising_technologies/attribution/kochava.md
Labels: cla-signed

#1308 BD-596
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
Labels: cla-signed

#1304 Update references to cloud messageing keys/ids to say Firebase
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/unity/android/push_notifications.md
Labels: cla-signed

#1310 BD-593: Update email glossary to include soft and hard bounces
  _docs/_user_guide/message_building_by_channel/email/analytics_glossary.md
Labels: cla-signed

#1307 Clarify that user aliases don't count toward data points
  _docs/_user_guide/onboarding_with_braze/data_points.md
Labels: cla-signed

#1311 BD-592: Kochava IdentityLink Explainer Addition
  _docs/_partners/advertising_technologies/attribution/kochava.md
Labels: cla-signed

#1309 Deploy - July 7, 2020
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/flutter/preview.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options.md
  _docs/_developer_guide/platform_integration_guides/unity/android/push_notifications.md
  _docs/_partners/advertising_technologies/attribution/kochava.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/custom_event_and_attribute_management.md
  _docs/_user_guide/message_building_by_channel/email/analytics_glossary.md
  _docs/_user_guide/onboarding_with_braze/data_points.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
Labels: Deploy, cla-signed

#1315 BD-594
  _docs/_api/objects_filters/user_attributes_object.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#1314 Update Success and Services Handbook for July
  assets/download_file/Braze_Success_and_Support_Services_Handbook.pdf
Labels: cla-signed

#1316 BD-597: Misalignment on Example Request
  _docs/_api/endpoints/user_data/post_user_track.md
Labels: cla-signed

#1318 BD-588: Update Segment Documentation, Removal of Screen Method
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment.md
Labels: cla-signed

#1319 Removed gender from email subscriptions
  _docs/_help/best_practices/email/managing_email_subscriptions.md
Labels: cla-signed

#1321 Removal of his/him and her/hers language in repo, replace with them/theirs
  _docs/_api/api_key.md
  _docs/_api/basics.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/silent_push_notifications.md
  _docs/_developer_guide/platform_integration_guides/fireos/push_notifications/silent_push_notifications.md
  _docs/_developer_guide/platform_integration_guides/ios/customer_feedback.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/silent_push_notifications.md
  _docs/_help/best_practices/push/sunset_policies.md
  _docs/_help/best_practices/user_onboarding.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/campaigns_in_multiple_languages.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/scheduling_your_campaign.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/rate-limiting.md
Labels: cla-signed

#1320 BD-598
  _docs/_user_guide/message_building_by_channel/email/email_reporting.md
Labels: cla-signed

#1317 ios unity game object updated docs
  _docs/_developer_guide/platform_integration_guides/unity/ios/push_notifications.md
  assets/img/unity/ios/unity_ios_api_key.png
  assets/img/unity/ios/unity_ios_appboy_callback.png
  assets/img/unity/ios/unity_ios_disable_auto_push.png
  assets/img/unity/ios/unity_ios_enable_background.png
  assets/img/unity/ios/unity_ios_push_opened.png
  assets/img/unity/ios/unity_ios_push_received.png
  assets/img_archive/unity-ios-background-push.png
  assets/img_archive/unity-ios-disable-registration.png
  assets/img_archive/unity-ios-integrate-push.png
  assets/img_archive/unity-ios-push-opened.png
  assets/img_archive/unity-ios-push-received.png
Labels: cla-signed

#1322 Leftover Deploy - June 9, 2020
  _docs/_api/api_key.md
  _docs/_api/basics.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_api/objects_filters/user_attributes_object.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/silent_push_notifications.md
  _docs/_developer_guide/platform_integration_guides/fireos/push_notifications/silent_push_notifications.md
  _docs/_developer_guide/platform_integration_guides/ios/customer_feedback.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/silent_push_notifications.md
  _docs/_developer_guide/platform_integration_guides/unity/ios/push_notifications.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_help/best_practices/email/managing_email_subscriptions.md
  _docs/_help/best_practices/push/sunset_policies.md
  _docs/_help/best_practices/user_onboarding.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/campaigns_in_multiple_languages.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/scheduling_your_campaign.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/rate-limiting.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/message_building_by_channel/email/email_reporting.md
  assets/download_file/Braze_Success_and_Support_Services_Handbook.pdf
  assets/img/unity/ios/unity_ios_api_key.png
  assets/img/unity/ios/unity_ios_appboy_callback.png
  assets/img/unity/ios/unity_ios_disable_auto_push.png
  assets/img/unity/ios/unity_ios_enable_background.png
  assets/img/unity/ios/unity_ios_push_opened.png
  assets/img/unity/ios/unity_ios_push_received.png
  assets/img_archive/unity-ios-background-push.png
  assets/img_archive/unity-ios-disable-registration.png
  assets/img_archive/unity-ios-integrate-push.png
  assets/img_archive/unity-ios-push-opened.png
  assets/img_archive/unity-ios-push-received.png
Labels: Deploy, cla-signed

#1323 Add exported=false to com.appboy.AppboyFirebaseMessagingService
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/unity/android/sdk_integration.md
Labels: cla-signed

#1325 add bcc field for email object API spec
  _docs/_api/objects_filters/email_object.md
Labels: cla-signed

#1324 BD-601
  _docs/_hidden/other/email_validation.md
Labels: cla-signed

#1326 Leftover Deploy pt. 2 - July 10, 2020
  _docs/_api/objects_filters/email_object.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/unity/android/sdk_integration.md
  _docs/_hidden/other/email_validation.md
Labels: Deploy, cla-signed

#1327 BD-602
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
Labels: cla-signed

#1328 Update examples using recipients to be arrays rather than objects
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_campaigns.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
Labels: cla-signed

#1329 Update email_validation.md
  _docs/_hidden/other/email_validation.md
Labels: cla-signed

#1330 BD-600:clarified shopify and braze money filter differences
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
Labels: cla-signed

#1331 Update decision_split.md
  _docs/_hidden/private_betas/decision_split.md
Labels: cla-signed

#1332 Fix some search formatting
  _includes/search_page.html
  assets/js/documents.js
Labels: cla-signed

#1334 added migration section
  _docs/_user_guide/message_building_by_channel/in-app_messages/beta-preview.md
Labels: cla-signed

#1337 Solconify Docs - Phase 1
  _docs/_hidden/private_betas/view_pii.md
  _docs/_partners/insights/business_intelligence/looker.md
  _docs/_user_guide/administrative.md
  _docs/_user_guide/administrative/access_braze/braze_instances.md
  _docs/_user_guide/administrative/access_braze/getting_your_account.md
  _docs/_user_guide/administrative/access_braze/logging_in.md
  _docs/_user_guide/administrative/access_braze/sdk_endpoints.md
  _docs/_user_guide/administrative/access_braze/single_sign_on.md
  _docs/_user_guide/administrative/company_settings/security_settings.md
  _docs/_user_guide/data_and_analytics.md
  _docs/_user_guide/data_and_analytics/braze_currents.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_archival.md
  _docs/_user_guide/onboarding_with_braze/email_setup.md
  _docs/_user_guide/onboarding_with_braze/email_setup/deliverability_pitfalls_and_spam_traps.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ip_warming.md
  _docs/_user_guide/onboarding_with_braze/sms_setup.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/user_phone_numbers.md
Labels: cla-signed

#1333 Deploy - July 14, 2020
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_campaigns.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
  _docs/_hidden/other/email_validation.md
  _docs/_hidden/private_betas/decision_split.md
  _docs/_hidden/private_betas/view_pii.md
  _docs/_partners/insights/business_intelligence/looker.md
  _docs/_user_guide/administrative.md
  _docs/_user_guide/administrative/access_braze/braze_instances.md
  _docs/_user_guide/administrative/access_braze/getting_your_account.md
  _docs/_user_guide/administrative/access_braze/logging_in.md
  _docs/_user_guide/administrative/access_braze/sdk_endpoints.md
  _docs/_user_guide/administrative/access_braze/single_sign_on.md
  _docs/_user_guide/administrative/company_settings/security_settings.md
  _docs/_user_guide/data_and_analytics.md
  _docs/_user_guide/data_and_analytics/braze_currents.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_archival.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/beta-preview.md
  _docs/_user_guide/onboarding_with_braze/email_setup.md
  _docs/_user_guide/onboarding_with_braze/email_setup/deliverability_pitfalls_and_spam_traps.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ip_warming.md
  _docs/_user_guide/onboarding_with_braze/sms_setup.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/user_phone_numbers.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
  _includes/search_page.html
  assets/js/documents.js
Labels: Deploy, cla-signed

#1267 Add addAlias to appboyBridge docs
  _includes/archive/appboyBridge.md
Labels: cla-signed

#1339 Leftover Deploy - July 16, 2020
  _includes/archive/appboyBridge.md
Labels: Deploy, cla-signed

#1289 Vizbee Integration Documentation
  _docs/_partners/channel_extensions.md
  _docs/_partners/channel_extensions/deep_linking.md
  _docs/_partners/channel_extensions/deep_linking/vizbee_for_tv_deep_linking.md
  _docs/_partners/home.md
Labels: Braze Partnerships, cla-signed

#1340 BD-605: Update MMS Docs
  _docs/_user_guide/message_building_by_channel.md
  _docs/_user_guide/message_building_by_channel/sms.md
  _docs/_user_guide/message_building_by_channel/sms/mms/about_mms.md
  _docs/_user_guide/message_building_by_channel/sms/mms/faqs.md
  _docs/_user_guide/message_building_by_channel/sms/mms/mms_short_long_codes.md
Labels: cla-signed

#1312 BD-595: Removal of Facebook UID references
  _docs/_partners/advertising_technologies/social/facebook.md
Labels: cla-signed

#1335 BD-605: Amazon Personalize Documentation Add
  _docs/_partners/data_augmentation.md
  _docs/_partners/data_augmentation/recommendation.md
  _docs/_partners/data_augmentation/recommendation/amazon_personalize.md
  _docs/_partners/home.md
  assets/img/amazon_personalize/braze-personalize-arch.png
  assets/img/amazon_personalize/region.png
Labels: Braze Partnerships, cla-signed

#1343 Mass Partner Docs Grammar and Spell Check
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/android_google_tag_manager.md
  _docs/_developer_guide/platform_integration_guides/unity/android/push_notifications.md
  _docs/_hidden/other/braze faqs.md
  _docs/_partners/additional_channels/calendar/rokt_calendar.md
  _docs/_partners/additional_channels/direct_mail/inkit.md
  _docs/_partners/additional_channels/direct_mail/lob.md
  _docs/_partners/additional_channels/instant_chat/messenger.md
  _docs/_partners/additional_channels/sms/telesign.md
  _docs/_partners/additional_channels/sms/twilio.md
  _docs/_partners/additional_channels/sms/wavecell.md
  _docs/_partners/advertising_technologies/attribution/adjust.md
  _docs/_partners/advertising_technologies/attribution/appsflyer.md
  _docs/_partners/advertising_technologies/attribution/branch_for_attribution.md
  _docs/_partners/advertising_technologies/attribution/singular.md
  _docs/_partners/advertising_technologies/retargeting/jampp.md
  _docs/_partners/advertising_technologies/retargeting/remerge.md
  _docs/_partners/channel_extensions.md
  _docs/_partners/channel_extensions/creative_and_personalization/email_orchestration/stensul.md
  _docs/_partners/channel_extensions/creative_and_personalization/email_orchestration/stripo.md
  _docs/_partners/channel_extensions/creative_and_personalization/email_orchestration/taxi_for_email.md
  _docs/_partners/channel_extensions/creative_and_personalization/intelligent_creative/movable_ink.md
  _docs/_partners/channel_extensions/deep_linking.md
  _docs/_partners/channel_extensions/deep_linking/appsflyer.md
  _docs/_partners/channel_extensions/deep_linking/branch_for_deeplinking.md
  _docs/_partners/channel_extensions/localization/transifex.md
  _docs/_partners/channel_extensions/loyalty/talonone.md
  _docs/_partners/channel_extensions/loyalty/voucherify.md
  _docs/_partners/channel_extensions/workflow_automation/fivetran.md
  _docs/_partners/channel_extensions/workflow_automation/zapier_integration.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/google_cloud_storage_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/microsoft_azure_blob_storage_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mparticle.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment_personas.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake/etl_pipline_setup.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake/sample_queries.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/user_data_collection/language_codes.md
  _docs/_user_guide/message_building_by_channel/push/push_registration.md
  _docs/_user_guide/message_building_by_channel/sms/mms/faqs.md
  _docs/_user_guide/onboarding_with_braze/learning_to_use_braze.md
Labels: cla-signed

#1344 Vn
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#1345 BD-486
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_user_guide/data_and_analytics/your_reports/understanding_your_app_usage_data.md
Labels: cla-signed

#1252 Bluedot docs
  _docs/_partners/data_augmentation.md
  _docs/_partners/data_augmentation/contextual_location.md
  _docs/_partners/data_augmentation/contextual_location/bluedot.md
  _docs/_partners/home.md
  assets/img_archive/Campaign-Compose-BD.png
  assets/img_archive/Campaign-Delivery-BD.png
  assets/img_archive/Campaign-Target_users-BD.png
Labels: Braze Partnerships, cla-signed

#1211 [@sambrown3] Add Iterate partner documentation
  _docs/_partners/additional_channels.md
  _docs/_partners/additional_channels/surveys.md
  _docs/_partners/additional_channels/surveys/iterate.md
  _docs/_partners/home.md
Labels: Braze Partnerships, cla-signed

#1338 Added Change Log section to Currents docs page
  _docs/_user_guide/data_and_analytics/braze_currents.md
Labels: cla-signed

#1348 appboyBridge.addAlias for iOS SDK
  _includes/archive/appboyBridge.md
Labels: cla-signed

#1347 Update post_user_identify.md
  _docs/_api/endpoints/user_data/post_user_identify.md
Labels: cla-signed

#1346 Update docs for S3 connector with assume role
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
Labels: cla-signed

#1351 BD-610: Link Fix
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/android_google_tag_manager.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/google_tag_manager.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
Labels: cla-signed

#1350 Update X in Y filter descriptions
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#1352 BD-607
  _docs/_help/help_articles/push/push_token_migration.md
Labels: cla-signed

#1353 Added more detail to S3 encryption option
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
Labels: cla-signed

#1357 BD-615: Update Security Certificate
  _docs/_developer_guide/disclosures/security_qualifications.md
Labels: cla-signed

#1358 added backward incompatibility notes for new HTML IAM beta
  _docs/_user_guide/message_building_by_channel/in-app_messages/beta-preview.md
Labels: cla-signed

#1356 BD-608: Push subscription states update
  _docs/_partners/channel_extensions/deep_linking/vizbee_for_tv_deeplinking.md
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
Labels: cla-signed

#1355 [BD-612] Switch up ordering of Content Cards
  _docs/_developer_guide/platform_integration_guides/ios/content_cards.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/badges.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/data_model.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/read_unread_indicators.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/refreshing_the_feed.md
Labels: cla-signed

#1360 BD-616: E164 phone format edits
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/user_phone_numbers.md
  assets/img/sms/e164.png
Labels: cla-signed

#1359 Leftover Deploy - July 23, 2020
  _docs/_api/endpoints/user_data/post_user_identify.md
  _docs/_developer_guide/disclosures/security_qualifications.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/android_google_tag_manager.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/google_tag_manager.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/badges.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/data_model.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/read_unread_indicators.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/refreshing_the_feed.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
  _docs/_help/help_articles/push/push_token_migration.md
  _docs/_partners/channel_extensions/deep_linking/vizbee_for_tv_deeplinking.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/beta-preview.md
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/user_phone_numbers.md
  _includes/archive/appboyBridge.md
  assets/img/sms/e164.png
Labels: Deploy, cla-signed

#1363 clarified impressions are based on impressions
  _docs/_user_guide/data_and_analytics/report_metrics.md
Labels: cla-signed

#1364 iam beta formatting
  _docs/_user_guide/message_building_by_channel/in-app_messages/beta-preview.md
Labels: cla-signed

#1349 [MERGE ON 7/28] Documentation for the new External ID Migration feature
  _docs/_api/api_key.md
  _docs/_api/endpoints/user_data.md
  _docs/_api/endpoints/user_data/external_id_migration.md
  _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_remove.md
  _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_rename.md
Labels: cla-signed

#1279 BD-576: SSL Click Tracking Docs - CDN Configuration
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl_clicktracking.md
  assets/img/SSL/DNS_settings.png
  assets/img/SSL/SSL_certificate.png
  assets/img/SSL/crypto_settings.png
  assets/img/SSL/custom_hostname.png
  assets/img/SSL/page_rules.png
  assets/img/SSL/single_distribution1.png
  assets/img/SSL/single_distribution2.png
Labels: cla-signed

#1365 August Release Notes
  _docs/_help/release_notes/2020.md
  _docs/_help/release_notes/2020/august.md
Labels: cla-signed

#1369 BD-151
  _docs/_help/best_practices/email/email_styling_tips.md
Labels: cla-signed

#1354 Android Version Doc
  _docs/_developer_guide/platform_integration_guides/android/android_11.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  assets/img/android/android-11-one-time-permission.svg
Labels: cla-signed

#1362 ios docs
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
  assets/img/ios/ios14-app-clips.png
  assets/img/ios/ios14-approximate-location.png
  assets/img/ios/ios14-idfa.png
  assets/img/ios/ios14-safari-itp-privacy-report.jpg
Labels: cla-signed

#1371 BD-617, BD-618: Update App Review Samples and Updates to FB Audience Sync
  _docs/_hidden/private_betas/fb_app_review.md
  _docs/_hidden/private_betas/fb_audience_sync.md
Labels: cla-signed

#1372 added blurb to release notes main page
  _docs/_help/release_notes.md
Labels: cla-signed

#1370 Remove React code snippet from native docs
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
Labels: cla-signed

#1341 Update email_validation.md
  _docs/_hidden/other/email_validation.md
Labels: cla-signed

#1375 Update beta-preview.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/beta-preview.md
Labels: cla-signed

#1381 BD-622
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/overview.md
  _docs/_user_guide/message_building_by_channel/in-app_messages.md
Labels: cla-signed

#1380 BD-623
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_push_notifications.md
Labels: cla-signed

#1378 wrapper SDK comment
  _docs/_developer_guide/platform_integration_guides/android/android_11.md
Labels: cla-signed

#1373 ios docs
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
Labels: cla-signed

#1383 Leftover Deploy - July 30, 2020
  _docs/_developer_guide/platform_integration_guides/android/android_11.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/overview.md
  _docs/_hidden/other/email_validation.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_push_notifications.md
  _docs/_user_guide/message_building_by_channel/in-app_messages.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/beta-preview.md
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
Labels: Deploy, cla-signed

#1384 Inserted line break for formatting
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl_clicktracking.md
Labels: cla-signed

#1385 BD-626
  _docs/_user_guide/engagement_tools/canvas/retention_reports.md
Labels: cla-signed

#1388 clarify REST API key in security page
  _docs/_api/api_key.md
Labels: cla-signed
