Repository braze-inc/braze-docs, pull requests merged in 2020-08, with the labels that each got.

#1391 Update beta-preview.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/beta-preview.md
Labels: cla-signed

#1390 Update appboyBridge.md
  _includes/archive/appboyBridge.md
Labels: cla-signed

#1389 ios updates
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
Labels: cla-signed

#1396 Update ssl_clicktracking.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl_clicktracking.md
Labels: cla-signed

#1397 BD-620: Updating iOS developer link
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
Labels: cla-signed

#1376 Revisions to clarify Preview limitations and purchase requirement
  _docs/_user_guide/predictive_suite/predictive_churn/creating_a_churn_prediction.md
  _docs/_user_guide/predictive_suite/predictive_churn/messaging_users.md
  _docs/_user_guide/predictive_suite/predictive_churn/prediction_analytics.md
Labels: cla-signed

#1398 Added CRR info, broke up
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
Labels: cla-signed

#1399 Deploy - August 4, 2020
  _docs/_api/api_key.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
  _docs/_user_guide/engagement_tools/canvas/retention_reports.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/beta-preview.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl_clicktracking.md
  _docs/_user_guide/predictive_suite/predictive_churn/creating_a_churn_prediction.md
  _docs/_user_guide/predictive_suite/predictive_churn/messaging_users.md
  _docs/_user_guide/predictive_suite/predictive_churn/prediction_analytics.md
  _includes/archive/appboyBridge.md
Labels: Deploy, cla-signed

#1402 Update canvas_persistent_entry_properties.md
  _docs/_hidden/private_betas/canvas_persistent_entry_properties.md
Labels: cla-signed

#1401 ios - removed web sdk note
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
Labels: cla-signed

#1403 BD-634
  _docs/_api/endpoints/messaging/send_messages/post_send_messages.md
Labels: cla-signed

#1404 BD-637: Email Validation
  _docs/_user_guide/onboarding_with_braze/email_setup.md
  _docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md
  _docs/_user_guide/onboarding_with_braze/sms_setup.md
Labels: cla-signed

#1405 Update ios_14.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
Labels: cla-signed

#1408 Update ios_14.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
Labels: cla-signed

#1409 Update ios_14.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
Labels: cla-signed

#1410 Clarify thread-id behavior
  _docs/_user_guide/message_building_by_channel/push/ios/notification_options.md
Labels: cla-signed

#1411 Leftover Deploy - August 6, 2020
  _docs/_api/endpoints/messaging/send_messages/post_send_messages.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
  _docs/_hidden/private_betas/canvas_persistent_entry_properties.md
  _docs/_user_guide/message_building_by_channel/push/ios/notification_options.md
  _docs/_user_guide/onboarding_with_braze/email_setup.md
  _docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md
  _docs/_user_guide/onboarding_with_braze/sms_setup.md
Labels: Deploy, cla-signed

#1415 Fix braze logging in url
  _docs/_user_guide/administrative/access_braze.md
  _docs/_user_guide/introduction.md
  _docs/_user_guide/onboarding_with_braze/learning_to_use_braze.md
Labels: cla-signed

#1413 Add wikipedia reference on GBDT for fancy math points
  _docs/_user_guide/predictive_suite/predictive_churn.md
Labels: cla-signed

#1414 Patch Kramdown
  Gemfile
  Gemfile.lock
  _config.yml
Labels: cla-signed

#1416 BD-639: Add links that open new tab to segment documentation
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment.md
Labels: cla-signed

#1417 BD-642: Broadcast Behavior Description Edit
  _docs/_api/parameters.md
Labels: cla-signed

#1418 Deploy - August 11, 2020
  Gemfile
  Gemfile.lock
  _config.yml
  _docs/_api/parameters.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment.md
  _docs/_user_guide/administrative/access_braze.md
  _docs/_user_guide/introduction.md
  _docs/_user_guide/onboarding_with_braze/learning_to_use_braze.md
  _docs/_user_guide/predictive_suite/predictive_churn.md
Labels: Deploy, cla-signed

#1419 Clarify `/users/track` batching
  _docs/_api/endpoints/user_data/post_user_track.md
Labels: cla-signed

#1423 BD-645: Updating Messaging and Channels LAB Link
  _docs/_user_guide/message_building_by_channel.md
Labels: cla-signed

#1424 Update tv_and_ott.md
  _docs/_developer_guide/platform_wide/tv_and_ott.md
Labels: cla-signed

#1425 BD-633: Highlight note
  _docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
Labels: cla-signed

#1428 BD-643: Add Dashboard Push Example
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
  assets/img/push_example.png
Labels: cla-signed

#1426 BD-629: Adding S3 Integration error message
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
Labels: cla-signed

#1427 Leftover Deploy - Aug 14, 2020
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_developer_guide/platform_wide/tv_and_ott.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
  _docs/_user_guide/message_building_by_channel.md
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
  assets/img/push_example.png
Labels: Deploy, cla-signed

#1429 Update ios_14.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
Labels: cla-signed

#1430 Update ios_14.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
Labels: cla-signed

#1432 BD-603
  _docs/_user_guide/data_and_analytics/report_metrics.md
Labels: cla-signed

#1431 Clarify that rate-limits are per app group
  _docs/_api/basics.md
Labels: cla-signed

#1433 Update local_connected_content_variables.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
Labels: cla-signed

#1435 Update ios_14.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
Labels: cla-signed

#1437 BD-648
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: cla-signed

#1436 BD-628
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/scheduling_your_campaign.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
Labels: cla-signed

#1438 Deploy - August 18, 2020
  _docs/_api/basics.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/scheduling_your_campaign.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: Deploy

#1406 [BD-491] iOS .plist additions
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
Labels: cla-signed

#1440 Revert "[BD-491] iOS .plist additions"
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
Labels: cla-signed

#1442 BD-504: Influenced Open Definition
  _docs/_user_guide/data_and_analytics/tracking/influenced_opens.md
Labels: cla-signed

#1443 add warning about appboy.display.showInAppMessage
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
Labels: cla-signed

#1439 Update ios_14.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
Labels: cla-signed

#1444 BD-387: Segment Analytics Tracking
  _docs/_user_guide/data_and_analytics/tracking.md
  _docs/_user_guide/data_and_analytics/tracking/segment_analytics_tracking.md
  _docs/_user_guide/data_and_analytics/your_reports/viewing_and_understanding_segment_data.md
Labels: cla-signed

#1421 BD-641: Remove/Update iOS/IDFA Docs
  _docs/_partners/advertising_technologies/attribution/adjust.md
  _docs/_partners/advertising_technologies/attribution/appsflyer.md
  _docs/_partners/advertising_technologies/attribution/branch_for_attribution.md
  _docs/_partners/advertising_technologies/attribution/kochava.md
  _docs/_partners/advertising_technologies/attribution/singular.md
Labels: cla-signed

#1422 BD-635: Funnels GA Documentation Campaign and Canvas
  _docs/_hidden/private_betas/funnel_report.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/campaign_funnel_report.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/retention_reports.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_push_notifications.md
  _docs/_user_guide/engagement_tools/canvas.md
  _docs/_user_guide/engagement_tools/canvas/canvas_funnel_reports.md
  _docs/_user_guide/engagement_tools/canvas/retention_reports.md
  assets/img/funnel_report/canvas_campaign.png
  assets/img/funnel_report/funnel_report3.png
  assets/img/funnel_report/funnel_report5.png
Labels: cla-signed

#1445 Leftover Deploy - Aug 20, 2020
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
  _docs/_hidden/private_betas/funnel_report.md
  _docs/_partners/advertising_technologies/attribution/adjust.md
  _docs/_partners/advertising_technologies/attribution/appsflyer.md
  _docs/_partners/advertising_technologies/attribution/branch_for_attribution.md
  _docs/_partners/advertising_technologies/attribution/kochava.md
  _docs/_partners/advertising_technologies/attribution/singular.md
  _docs/_user_guide/data_and_analytics/tracking.md
  _docs/_user_guide/data_and_analytics/tracking/influenced_opens.md
  _docs/_user_guide/data_and_analytics/tracking/segment_analytics_tracking.md
  _docs/_user_guide/data_and_analytics/your_reports/viewing_and_understanding_segment_data.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/campaign_funnel_report.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/retention_reports.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_push_notifications.md
  _docs/_user_guide/engagement_tools/canvas.md
  _docs/_user_guide/engagement_tools/canvas/canvas_funnel_reports.md
  _docs/_user_guide/engagement_tools/canvas/retention_reports.md
  assets/img/funnel_report/canvas_campaign.png
  assets/img/funnel_report/funnel_report3.png
  assets/img/funnel_report/funnel_report5.png
Labels: Deploy, cla-signed

#1448 BD-650: Segment REST API Endpoint Edit
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment.md
Labels: cla-signed

#1407 Web SDK v3.0.0 Docs
  _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  assets/img/web-gtm/gtm-actions-tag.png
  assets/img/web-gtm/gtm-change-user.png
  assets/img/web-gtm/gtm-community-gallery-search.png
  assets/img/web-gtm/gtm-custom-event.png
  assets/img/web-gtm/gtm-debug-mode.png
  assets/img/web-gtm/gtm-disable-tracking.png
  assets/img/web-gtm/gtm-initialization-tag.png
  assets/img/web-gtm/gtm-purchase.png
  assets/img/web-gtm/gtm-tag-debugging.png
Labels: cla-signed

#1400 Transactional Messaging
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  _docs/_api/transactional_message_api_campaign.md
  assets/img/transactional_campaign_compose.png
  assets/img/transactional_email_campaign.png
Labels: cla-signed, status: on hold / do not merge

#1420 BD-640: RBN Currents
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _layouts/customer_behavior_events_glossary.html
Labels: cla-signed

#1449 add details for inbound sms currents event
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#1451 BD-651: Canvas V2 GA Release
  _docs/_hidden/private_betas/churn.md
  _docs/_user_guide/engagement_tools/canvas.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/decision_split.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/fb_app_review.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/fb_audience_sync.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
  assets/img/canvas_components/components1.png
  assets/img/canvas_components/components2.png
  assets/img/canvas_components/components3.png
  assets/img/decision-split-1.png
Labels: cla-signed

#1453 Update SSS Handbook
  assets/download_file/Braze_Success_and_Support_Services_Handbook.pdf
Labels: cla-signed

#1395 [SDK-673] iOS 14 locations docs updates
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/location_tracking.md
Labels: cla-signed

#1455 Solconify Docs - Pt.2
  _docs/_api/objects_filters/event_object.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_custom_event_data.md
  _docs/_user_guide/engagement_tools/campaigns.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/change_your_campaign_after_launch.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
Labels: cla-signed

#1456 Added Canvas LAB Playbook
  _docs/_user_guide/engagement_tools/canvas/canvas_components.md
Labels: cla-signed

#1454 September Release Notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2020.md
  _docs/_help/release_notes/2020/september.md
Labels: cla-signed

#1457 Deploy - August 25, 2020
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  _docs/_api/objects_filters/event_object.md
  _docs/_api/transactional_message_api_campaign.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2020.md
  _docs/_help/release_notes/2020/september.md
  _docs/_hidden/private_betas/churn.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_custom_event_data.md
  _docs/_user_guide/engagement_tools/campaigns.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/change_your_campaign_after_launch.md
  _docs/_user_guide/engagement_tools/canvas.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/decision_split.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/fb_app_review.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/fb_audience_sync.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _layouts/customer_behavior_events_glossary.html
  assets/download_file/Braze_Success_and_Support_Services_Handbook.pdf
  assets/img/canvas_components/components1.png
  assets/img/canvas_components/components2.png
  assets/img/canvas_components/components3.png
  assets/img/decision-split-1.png
  assets/img/transactional_campaign_compose.png
  assets/img/transactional_email_campaign.png
  assets/img/web-gtm/gtm-actions-tag.png
  assets/img/web-gtm/gtm-change-user.png
  assets/img/web-gtm/gtm-community-gallery-search.png
  assets/img/web-gtm/gtm-custom-event.png
  assets/img/web-gtm/gtm-debug-mode.png
  assets/img/web-gtm/gtm-disable-tracking.png
  assets/img/web-gtm/gtm-initialization-tag.png
  assets/img/web-gtm/gtm-purchase.png
  assets/img/web-gtm/gtm-tag-debugging.png
Labels: Deploy, cla-signed

#1458 doc: fix platform typo in bitcode section
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods.md
Labels: cla-signed

#1459 Minor typo edits
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/android_google_tag_manager.md
  _docs/_help/gdpr_compliance.md
  _docs/_partners/additional_channels/surveys/iterate.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
Labels: cla-signed

#1461 IDFA Attribution Partner Updates
  _docs/_partners/advertising_technologies/attribution/adjust.md
  _docs/_partners/advertising_technologies/attribution/appsflyer.md
  _docs/_partners/advertising_technologies/attribution/branch_for_attribution.md
  _docs/_partners/advertising_technologies/attribution/kochava.md
  _docs/_partners/advertising_technologies/attribution/singular.md
Labels: cla-signed

#1462 Update promotion_codes.md
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
Labels: cla-signed

#1460 Leftover Deploy - August 26, 2020
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/android_google_tag_manager.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods.md
  _docs/_help/gdpr_compliance.md
  _docs/_partners/additional_channels/surveys/iterate.md
  _docs/_partners/advertising_technologies/attribution/adjust.md
  _docs/_partners/advertising_technologies/attribution/appsflyer.md
  _docs/_partners/advertising_technologies/attribution/branch_for_attribution.md
  _docs/_partners/advertising_technologies/attribution/kochava.md
  _docs/_partners/advertising_technologies/attribution/singular.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
Labels: Deploy, cla-signed

#1463 Update initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
Labels: cla-signed

#1464 Update docs to reflect new 1k/minute rate limit on External ID endpoints
  _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_remove.md
  _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_rename.md
Labels: cla-signed

#1466 fix gist-it css
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
Labels: cla-signed

#1465 Update ios_14.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
Labels: cla-signed

#1467 Typo Fix in Attribution Doc
  _docs/_partners/advertising_technologies/attribution/appsflyer.md
Labels: cla-signed

#1434 BD-647: Campaign Comparison Doc
  _docs/_hidden/private_betas/campaign_comparison_updates.md
  _docs/_user_guide/data_and_analytics/your_reports/campaign_comparison.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/comparing_campaigns.md
  assets/img/campaign_comparison/campaign.png
  assets/img/campaign_comparison/campaign_main.png
  assets/img/campaign_comparison/comparison_name.png
  assets/img/campaign_comparison/create_report.png
  assets/img/campaign_comparison/download.png
  assets/img/campaign_comparison/metric.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#1468 BD-653: Inbox Vision Behavior Clarification
  _docs/_user_guide/message_building_by_channel/email/inbox_vision.md
Labels: cla-signed

#1386 [SDK-519] Updating ABKIDFADelegate documentation with iOS 14 changes.
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
Labels: cla-signed

#1469 Transactional Messaging: Minor tweaks
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
Labels: cla-signed
