Repository braze-inc/braze-docs, pull requests merged in 2020-12, with the labels that each got.

#1692 update changeUser to reference migration api
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/unity/Analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/setting_user_ids.md
Labels: cla-signed

#1689 android/ updated push customization docs
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
Labels: cla-signed

#1691 Deploy - December 1, 2020
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/swift_package_manager.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/unity/Analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/web/smart_tvs.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/setting_user_ids.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2020/december.md
  _docs/_help/release_notes/2020/november.md
  _docs/_partners/advertising_technologies/attribution/pypestream.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/jebbit.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium_audience_stream.md
  _docs/_partners/data_augmentation/contextual_location/gimbal.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/geofence_configuration.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/location_tracking.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
  _docs/_user_guide/intelligence/intelligent_channel.md
  _docs/_user_guide/message_building_by_channel/push/about.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/user_profile_fields_connected_content.md
Labels: Deploy, cla-signed

#1696 redirect from beta-preview.md to preview.md
  _docs/_user_guide/message_building_by_channel/in-app_messages.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/preview.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#1697 BD-759: Clarifying Unique Impressions Definition
  _docs/_user_guide/data_and_analytics/report_metrics.md
Labels: cla-signed

#1699 BD-760: Variant Entry Caveat
  _docs/_help/help_articles/campaigns_and_canvas/more_people_in_control_group.md
Labels: cla-signed

#1587 Global Control Group Beta
  _docs/_hidden/private_betas/global_control_group.md
  assets/img/control_group/control_group1.png
  assets/img/control_group/control_group2.png
  assets/img/control_group/control_group3.png
  assets/img/control_group/control_group4.png
  assets/img/control_group/control_group5.png
  assets/img/control_group/control_group6.png
Labels: cla-signed

#1700 Leftover Deploy - December 3, 2020
  _docs/_help/help_articles/campaigns_and_canvas/more_people_in_control_group.md
  _docs/_hidden/private_betas/global_control_group.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/message_building_by_channel/in-app_messages.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/preview.md
  assets/img/control_group/control_group1.png
  assets/img/control_group/control_group2.png
  assets/img/control_group/control_group3.png
  assets/img/control_group/control_group4.png
  assets/img/control_group/control_group5.png
  assets/img/control_group/control_group6.png
  assets/js/broken_redirect_list.js
Labels: Deploy, cla-signed

#1703 Link Fix
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/home.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/sms_sending.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#1704 Deploy - December 7, 2020
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/home.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/sms_sending.md
  assets/js/broken_redirect_list.js
Labels: Deploy, cla-signed

#1705 BD-763: Formatting Errors, Currents Update
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/rate-limiting.md
Labels: cla-signed

#1702 Browser Extensions
  _docs/_developer_guide/platform_integration_guides/web/browser_extensions.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/alternate_push_domain.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
Labels: cla-signed

#1706 Deploy - December 8, 2020
  _docs/_developer_guide/platform_integration_guides/web/browser_extensions.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/alternate_push_domain.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/rate-limiting.md
Labels: Deploy, cla-signed

#1707 Fix broken link
  _docs/_developer_guide/platform_integration_guides/web/browser_extensions.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
Labels: cla-signed

#1710 few fixes on zd page
  _docs/_partners/channel_extensions/support/zendesk.md
Labels: cla-signed

#1711 Voucherify documentation update
  _docs/_partners/channel_extensions/loyalty/voucherify.md
  assets/img/voucherify-cc-campaignId.png
  assets/img/voucherify-cc-code-published.png
  assets/img/voucherify-cc-preview.png
  assets/img/voucherify-cc-snippet.png
  assets/img/voucherify-code-published.png
  assets/img/voucherify-codes-list-csv.png
  assets/img/voucherify-create-Promotion-Codes.png
  assets/img/voucherify-create-braze-campaign.png
  assets/img/voucherify-custom-attribute-in-email.png
  assets/img/voucherify-custom-attribute.png
  assets/img/voucherify-custom-attributes-mapping.png
  assets/img/voucherify-developer-console-API-settings.png
  assets/img/voucherify-edit-email-body.png
  assets/img/voucherify-email-preview-custom-attribute.png
  assets/img/voucherify-export-Codes.png
  assets/img/voucherify-import-codes-braze.png
  assets/img/voucherify-integrations-hub.png
  assets/img/voucherify-launch-campaign.png
  assets/img/voucherify-manual-conditions.png
  assets/img/voucherify-promotion-codes-details.png
  assets/img/voucherify-promotion-codes-list-expiration.png
  assets/img/voucherify-promotion-list-copy-snippet.png
  assets/img/voucherify-promotion-list-snippet-email.png
  assets/img/voucherify-redemption.png
  assets/img/voucherify_braze_campaign.png
  assets/img/voucherify_braze_campaign_preview.png
  assets/img/voucherify_custom_attributes.png
  assets/img/voucherify_distribution_audience.png
  assets/img/voucherify_distribution_channel.png
  assets/img/voucherify_distribution_mode.png
  assets/img/voucherify_distribution_purpose.png
  assets/img/voucherify_distribution_title.png
  assets/img/voucherify_establish_connection.png
  assets/img/voucherify_integration_directory.png
  assets/img/voucherify_new_distribution.png
  assets/img/voucherify_test.png
Labels: cla-signed

#1714 BD-762, BD-764
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_templates.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/troubleshooting.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
Labels: cla-signed

#1712 Leftover Deploy - December 11, 2020
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_templates.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/web/browser_extensions.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
  _docs/_partners/channel_extensions/loyalty/voucherify.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  assets/img/voucherify-cc-campaignId.png
  assets/img/voucherify-cc-code-published.png
  assets/img/voucherify-cc-preview.png
  assets/img/voucherify-cc-snippet.png
  assets/img/voucherify-code-published.png
  assets/img/voucherify-codes-list-csv.png
  assets/img/voucherify-create-Promotion-Codes.png
  assets/img/voucherify-create-braze-campaign.png
  assets/img/voucherify-custom-attribute-in-email.png
  assets/img/voucherify-custom-attribute.png
  assets/img/voucherify-custom-attributes-mapping.png
  assets/img/voucherify-developer-console-API-settings.png
  assets/img/voucherify-edit-email-body.png
  assets/img/voucherify-email-preview-custom-attribute.png
  assets/img/voucherify-export-Codes.png
  assets/img/voucherify-import-codes-braze.png
  assets/img/voucherify-integrations-hub.png
  assets/img/voucherify-launch-campaign.png
  assets/img/voucherify-manual-conditions.png
  assets/img/voucherify-promotion-codes-details.png
  assets/img/voucherify-promotion-codes-list-expiration.png
  assets/img/voucherify-promotion-list-copy-snippet.png
  assets/img/voucherify-promotion-list-snippet-email.png
  assets/img/voucherify-redemption.png
  assets/img/voucherify_braze_campaign.png
  assets/img/voucherify_braze_campaign_preview.png
  assets/img/voucherify_custom_attributes.png
  assets/img/voucherify_distribution_audience.png
  assets/img/voucherify_distribution_channel.png
  assets/img/voucherify_distribution_mode.png
  assets/img/voucherify_distribution_purpose.png
  assets/img/voucherify_distribution_title.png
  assets/img/voucherify_establish_connection.png
  assets/img/voucherify_integration_directory.png
  assets/img/voucherify_new_distribution.png
  assets/img/voucherify_test.png
Labels: Deploy, cla-signed

#1592 SLA Compliance Doc and Tags
  _docs/_api/endpoints/email/post_blacklist.md
  _docs/_api/endpoints/email/post_email_subscription_status.md
  _docs/_api/endpoints/messaging/schedule_messages/post_delete_scheduled_messages.md
  _docs/_api/endpoints/messaging/schedule_messages/post_delete_scheduled_triggered_messages.md
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_messages.md
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_campaigns.md
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_canvases.md
  _docs/_api/endpoints/messaging/schedule_messages/post_update_scheduled_messages.md
  _docs/_api/endpoints/messaging/schedule_messages/post_update_scheduled_triggered_campaigns.md
  _docs/_api/endpoints/messaging/schedule_messages/post_update_scheduled_triggered_canvases.md
  _docs/_api/endpoints/messaging/send_messages/post_send_messages.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
  _docs/_api/endpoints/user_data/post_user_delete.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_hidden/private_betas/core_endpoints.md
Labels: cla-signed

#1716 Adjust partner page to prevent timeout during build
  _plugins/alloy_partner.rb
  assets/img/search_black_shark.svg
  assets/img/search_navy_cove.svg
  assets/img/search_white.svg
Labels: cla-signed

#1695 Huawei Push [Merge on Dec 15]
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/huawei_integration.md
Labels: cla-signed

#1719 BD-765, BD-767
  _docs/_user_guide/message_building_by_channel/email/inbox_vision.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl_clicktracking.md
Labels: cla-signed

#1693 Adobe CDP Partnership Integration
  _docs/_hidden/private_betas/adobe.md
  assets/img/adobe/braze-destination-account.png
  assets/img/adobe/braze-destination-activate.png
  assets/img/adobe/braze-destination-authentication.png
  assets/img/adobe/braze-destination-configure.png
  assets/img/adobe/braze-destination-mapping-attributes.png
  assets/img/adobe/braze-destination-mapping-complete.png
  assets/img/adobe/braze-destination-mapping-example.png
  assets/img/adobe/braze-destination-mapping-namespaces.png
  assets/img/adobe/braze-destination-mapping-source.png
  assets/img/adobe/braze-destination-mapping-target-fields.png
  assets/img/adobe/braze-destination-mapping-target.png
  assets/img/adobe/braze-destination-mapping.png
Labels: cla-signed

#1721 BD-766: Update Cloudfront Distribution Settings
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl_clicktracking.md
  assets/img/SSL/single_distribution.png
Labels: cla-signed

#1723 kellietest
  _docs/_user_guide/onboarding_with_braze/data_points.md
Labels: cla-signed

#1724 Data Retention Doc for Legal
  _docs/_api/data_retention.md
  _docs/_api/errors.md
Labels: cla-signed

#1725 Leftover Deploy - December 17, 2020
  _docs/_api/data_retention.md
  _docs/_api/errors.md
Labels: Deploy

#1726 BD-770, BD-760, BD-768
  _docs/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/fb_audience_sync.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#1728 header fix
  _docs/_hidden/private_betas/core_endpoints.md
Labels: cla-signed

#1722 Promotion Codes Update with Voucherify and Talon.One Info
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
Labels: cla-signed

#1729 Leftover Deploy Pt. 2 - December 17, 2020
  _docs/_hidden/private_betas/core_endpoints.md
  _docs/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/fb_audience_sync.md
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#1730 register service worker in non-root domain
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
Labels: cla-signed
