Repository braze-inc/braze-docs, pull requests merged in 2020-09, with the labels that each got.

#1470 Deploy - September 1, 2020
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_remove.md
  _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_rename.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_hidden/private_betas/campaign_comparison_updates.md
  _docs/_partners/advertising_technologies/attribution/appsflyer.md
  _docs/_user_guide/data_and_analytics/your_reports/campaign_comparison.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/comparing_campaigns.md
  _docs/_user_guide/message_building_by_channel/email/inbox_vision.md
  assets/img/campaign_comparison/campaign.png
  assets/img/campaign_comparison/campaign_main.png
  assets/img/campaign_comparison/comparison_name.png
  assets/img/campaign_comparison/create_report.png
  assets/img/campaign_comparison/download.png
  assets/img/campaign_comparison/metric.png
  assets/js/broken_redirect_list.js
Labels: Deploy

#1471 Added fields_to_export to users by segment export
  _docs/_api/endpoints/export/user_data/post_users_segment.md
Labels: cla-signed

#1441 [BD-491] iOS sample .plist & In-App Message Customization Addition
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
Labels: cla-signed, status: in progress

#1472 Adding timestamp to /list message endpoints
  _docs/_api/endpoints/export/campaigns/get_campaigns.md
  _docs/_api/endpoints/export/canvas/get_canvases.md
Labels: cla-signed

#1473 Leftover Deploy - September 3, 2020
  _docs/_api/endpoints/export/campaigns/get_campaigns.md
  _docs/_api/endpoints/export/canvas/get_canvases.md
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
Labels: Deploy

#1474 BD-656: Update Endpoints with new description field
  _docs/_api/endpoints/export/campaigns/get_campaign_details.md
  _docs/_api/endpoints/export/canvas/get_canvas_details.md
  _docs/_api/endpoints/export/segments/get_segment_details.md
  _docs/_api/endpoints/templates/email_templates/get_see_email_template_information.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards.md
Labels: cla-signed

#1477 Update android_11.md
  _docs/_developer_guide/platform_integration_guides/android/android_11.md
Labels: cla-signed

#1478 Update ios_14.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
Labels: cla-signed

#1479 BD-668: Update Campaign_id field
  _docs/_api/endpoints/messaging/send_messages/post_send_messages.md
Labels: cla-signed

#1482 Add more detail to UserNotifications documentation
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
Labels: cla-signed

#1483 BD-659: Exception event clarifications
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/campaign_connector.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/advancement.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/exception_events.md
  _docs/_user_guide/engagement_tools/canvas/get_started/the_basics.md
Labels: cla-signed

#1485 Simplify request form
  _docs/_hidden/other/documentation_request.md
Labels: cla-signed

#1484 Update tv_and_ott.md
  _docs/_developer_guide/platform_integration_guides/web/smart_tvs.md
  _docs/_developer_guide/platform_wide/tv_and_ott.md
Labels: cla-signed

#1486 Leftover Deploy - September 10, 2020
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/web/smart_tvs.md
  _docs/_developer_guide/platform_wide/tv_and_ott.md
  _docs/_hidden/other/documentation_request.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/campaign_connector.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/advancement.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/exception_events.md
  _docs/_user_guide/engagement_tools/canvas/get_started/the_basics.md
Labels: Deploy, cla-signed

#1487 Update ios_14.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
Labels: cla-signed

#1488 Leftover Deploy Pt.2 - September 11, 2020
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
Labels: cla-signed

#1489 Update ios_14.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
Labels: cla-signed

#1491 add smart TV to developer links
  _docs/_developer_guide/home.md
Labels: cla-signed

#1490 Minor edit to company_wide_setting doc
  _docs/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md
Labels: cla-signed

#1492 Update setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_user_ids.md
Labels: cla-signed

#1495 Small updates to GIF docs
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/customization.md
Labels: cla-signed

#1494 Documenting `send_to_existing_only` caveat
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
Labels: cla-signed

#1493 Fixing Broken Link in Email Channel Landing Page
  _docs/_user_guide/message_building_by_channel/email.md
Labels: cla-signed

#1498 BD-676, BD-664
  _docs/_help/help_articles/data/change_custom_data_type.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
  assets/img/change_custom_attribute.png
Labels: cla-signed

#1497 Deploy - September 15, 2020
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
  _docs/_developer_guide/home.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
  _docs/_help/help_articles/data/change_custom_data_type.md
  _docs/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md
  _docs/_user_guide/message_building_by_channel/email.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
  assets/img/change_custom_attribute.png
Labels: Deploy, cla-signed

#1499 Fix IDFA step formatting
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
Labels: cla-signed

#1500 3.27.0 docs - deploy with release 9/16
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
Labels: cla-signed

#1503 BD-674, BD-665
  _docs/_api/endpoints/email/post_blacklist.md
  _docs/_user_guide/message_building_by_channel/sms/user_data_migration.md
Labels: cla-signed

#1501 Leftover Deploy Pt 1. - September 16, 2020
  _docs/_api/endpoints/email/post_blacklist.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
  _docs/_user_guide/message_building_by_channel/sms/user_data_migration.md
Labels: Deploy, cla-signed

#1505 add missing css images
  assets/img/copy_icon.png
  assets/img/message-important.png
  assets/img/message-note.png
  assets/img/message-tip.png
  assets/img/message-update.png
  assets/img/message-warning.png
Labels: cla-signed

#1508 Transactional Messaging: add image for webhook postback url input
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  assets/img/transactional_webhook_url.png
Labels: cla-signed

#1510 Update get_canvases.md
  _docs/_api/endpoints/export/canvas/get_canvases.md
Labels: cla-signed

#1513 BD-675: Rename 'Compaign Comparison' to 'Report Builder
  _docs/_user_guide/data_and_analytics/your_reports.md
  _docs/_user_guide/data_and_analytics/your_reports/report_builder.md
Labels: cla-signed

#1516 Fixing campaign comparison redirect link
  assets/js/broken_redirect_list.js
Labels: cla-signed

#1512 October 2020 Release Notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2020.md
  _docs/_help/release_notes/2020/october.md
Labels: cla-signed

#1517 iOS 14 updates
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/locations_and_geofences.md
Labels: cla-signed

#1519 Fix typo of sms.InboundReceive
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#1520 Leftover Deploy - September 24, 2020
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: Deploy, cla-signed

#1523 update txn docs to include race condition note
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
Labels: cla-signed

#1521 Braze-to-braze webhooks are all 127.0.0.1 now
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
Labels: cla-signed

#1524 BD-681: Canvas step delay
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
Labels: cla-signed

#1518 Data share fields
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mparticle_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
  _docs/_partners/insights/behavioral_analytics/amplitude_for_currents.md
  _docs/_partners/insights/behavioral_analytics/mixpanel_for_currents.md
Labels: cla-signed

#1502 update smart tv docs
  _docs/_developer_guide/platform_integration_guides/web/smart_tvs.md
Labels: cla-signed

#1525 Deploy - September 29, 2020
  .ruby-version
  Gemfile
  Gemfile.lock
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/inline_image_push.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/push_story.md
  _docs/_developer_guide/platform_integration_guides/android/push_story.md
  _docs/_developer_guide/platform_integration_guides/web/smart_tvs.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mparticle_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
  _docs/_partners/insights/behavioral_analytics/amplitude_for_currents.md
  _docs/_partners/insights/behavioral_analytics/mixpanel_for_currents.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  assets/img/android/push/inline_image_push_android_1.png
Labels: Deploy, cla-signed

#1527 Update trigger_properties_object.md
  _docs/_api/objects_filters/trigger_properties_object.md
Labels: cla-signed

#1528 Update inline_image_push.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/inline_image_push.md
Labels: cla-signed
