Repository braze-inc/braze-docs, pull requests merged in 2020-10, with the labels that each got.

#1529 Clarify `/users/track` Rate-limit
  _docs/_api/basics.md
Labels: cla-signed

#1530 BD-682: Total clicks and list unsubscribes
  _docs/_user_guide/data_and_analytics/report_metrics.md
Labels: cla-signed

#1532 Update inline_image_push.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/inline_image_push.md
  assets/img/android/push/android_inline_image_notification_type.png
Labels: cla-signed

#1533 Update inline_image_push.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/inline_image_push.md
Labels: cla-signed

#1534 Leftover Deploy - October 1, 2020
  _docs/_api/basics.md
  _docs/_api/objects_filters/trigger_properties_object.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/inline_image_push.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  assets/img/android/push/android_inline_image_notification_type.png
Labels: Deploy, cla-signed

#1536 Android FCM Priority
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/advanced_settings.md
  assets/img_archive/android_advanced_settings.png
Labels: cla-signed

#1539 Fix site page exclusion
  _config.yml
  _docs/_docs_pages/404.md
  _docs/_docs_pages/api.md
  _docs/_docs_pages/cla.md
  _docs/_docs_pages/developer_guide.md
  _docs/_docs_pages/help.md
  _docs/_docs_pages/home.md
  _docs/_docs_pages/index.md
  _docs/_docs_pages/partners.md
  _docs/_docs_pages/search.md
  _docs/_docs_pages/sitemap.md
  _docs/_docs_pages/user_guide.md
  tk
Labels: cla-signed

#1540 BD-691: Day of recurring event Filter
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#1541 BD-692: Clarify CSV User Import Options
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Labels: cla-signed

#1542 Deploy - October 6, 2020
  _config.yml
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/advanced_settings.md
  _docs/_developer_guide/platform_integration_guides/unity/android/sdk_integration.md
  _docs/_docs_pages/404.md
  _docs/_docs_pages/api.md
  _docs/_docs_pages/cla.md
  _docs/_docs_pages/developer_guide.md
  _docs/_docs_pages/help.md
  _docs/_docs_pages/home.md
  _docs/_docs_pages/index.md
  _docs/_docs_pages/partners.md
  _docs/_docs_pages/search.md
  _docs/_docs_pages/sitemap.md
  _docs/_docs_pages/user_guide.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _includes/archive/unity/unitypackage_descriptions.md
  assets/img_archive/android_advanced_settings.png
  tk
Labels: Deploy, cla-signed

#1213 Kh/tealium
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium_audience_stream.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
  assets/img/tealium/braze_connection.png
  assets/img/tealium/braze_connector_marketplace.png
  assets/img/tealium/connector_summary.png
  assets/img/tealium/create_configuration.png
  assets/img/tealium/data_source.png
  assets/img/tealium/event_specs.png
  assets/img/tealium/get_code.png
  assets/img/tealium/minimize.gif
  assets/img/tealium/remote_mappings.png
  assets/img/tealium/save_publish.png
  assets/img/tealium/summary.png
  assets/img/tealium/summary_list.png
  assets/img/tealium/tealium_overview.png
  assets/img/tealium/track_user_delete.png
  assets/img/tealium/track_user_example.jpg
Labels: cla-signed

#1543 [Trivial] Remove unneeded iOS log
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
Labels: cla-signed

#1548 BD-688: URL redirect added
  assets/js/broken_redirect_list.js
Labels: cla-signed

#1549 BD-680: Clarifying CC JSON Structure
  _docs/_developer_guide/eu01_us3_sdk_implementation_differences/for_android.md
  _docs/_developer_guide/eu01_us3_sdk_implementation_differences/for_ios.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/multiple_feeds.md
Labels: cla-signed

#1550 BD-689: Clarifying iOS and Android SDK Implementation differences doc
  _docs/_developer_guide/eu01_us3_sdk_implementation_differences/for_android.md
  _docs/_developer_guide/eu01_us3_sdk_implementation_differences/for_ios.md
Labels: cla-signed

#1546 BD-686: Adding Sparkpost CDN options
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl_clicktracking.md
Labels: cla-signed

#1545 BD-696: Update Currents SMS Message Engagement Event
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#1551 BD-701: Code Snippet Formatting
  _docs/_help/help_articles/push/push_token_migration.md
Labels: cla-signed

#1552 BD-699: Clarify endpoint use
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
Labels: cla-signed

#1554 Leftover Deploy - October 8, 2020
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
  _docs/_developer_guide/eu01_us3_sdk_implementation_differences/for_android.md
  _docs/_developer_guide/eu01_us3_sdk_implementation_differences/for_ios.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/multiple_feeds.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
  _docs/_help/help_articles/push/push_token_migration.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl_clicktracking.md
  assets/js/broken_redirect_list.js
Labels: Deploy, cla-signed

#1553 Portal Documentation - MERGE ON 10/13
  _docs/_user_guide/administrative/access_braze/portal.md
  _docs/_user_guide/administrative/access_braze/product_request_example.md
Labels: cla-signed

#1526 SMS Keyword Feature Updates - MERGE ON 10/13
  _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md
  assets/img/sms/custom_category.png
  assets/img/sms/keyword_edit.png
  assets/img/sms/keyword_list.png
  assets/img/sms/multi-language.png
  assets/img/sms/multi-language2.png
  assets/img/sms/retargeting1.png
  assets/img/sms/retargeting2.png
  assets/img/sms/retargeting3.png
  assets/img/sms/sms_channel.png
  assets/img/sms/sms_currents.png
  assets/img/sms/sms_keywords.png
Labels: cla-signed

#1555 Deploy - October 13, 2020
  _docs/_developer_guide/platform_integration_guides/ios/content_cards.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/implementation_guide.md
  _docs/_user_guide/administrative/access_braze/portal.md
  _docs/_user_guide/administrative/access_braze/product_request_example.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md
  assets/img/sms/custom_category.png
  assets/img/sms/keyword_edit.png
  assets/img/sms/keyword_list.png
  assets/img/sms/multi-language.png
  assets/img/sms/multi-language2.png
  assets/img/sms/retargeting1.png
  assets/img/sms/retargeting2.png
  assets/img/sms/retargeting3.png
  assets/img/sms/sms_channel.png
  assets/img/sms/sms_currents.png
  assets/img/sms/sms_keywords.png
  assets/js/broken_redirect_list.js
Labels: Deploy, cla-signed

#1557 Typo Fix
  _docs/_user_guide/administrative/access_braze/portal.md
Labels: cla-signed

#1558 Funnel Report phrasing fix
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/campaign_funnel_report.md
  _docs/_user_guide/engagement_tools/canvas/canvas_funnel_reports.md
  assets/img/funnel_report/funnel_report5.png
Labels: cla-signed

#1559 quick updates to the keyword docs
  _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
Labels: cla-signed

#1560 BD-695: Clarifying Access Rules
  _docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#1561 BD-704: Clarifying SMS subscription group requirements
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
Labels: cla-signed

#1562 BD-708: Updating Custom Attribute Definitions
  _docs/_help/help_articles/data/change_custom_data_type.md
Labels: cla-signed

#1538 content card removal
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  assets/img/content_cards/content_card_removal_event.png
Labels: cla-signed

#1565 updated Android push docs and troubleshooting
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/troubleshooting.md
Labels: cla-signed

#1566 Product Portal Image
  _docs/_user_guide/administrative/access_braze/portal.md
  assets/img/portal.png
Labels: cla-signed

#1567 Sdk 793 androidx docs
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/font_customization.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/font_customization.md
Labels: cla-signed

#1564 Android/verbose logging updates
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
Labels: cla-signed

#1568 added allowlist enabled doc
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
Labels: cla-signed

#1570 BD-710: Custom Attributes Clarification
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
Labels: cla-signed

#1571 BD-711: Edit to /messages/send API Endpoint
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_messages.md
  _docs/_api/endpoints/messaging/schedule_messages/post_update_scheduled_messages.md
  _docs/_api/endpoints/messaging/send_messages/post_send_messages.md
Labels: cla-signed

#1569 Leftover Deploy - October 15, 2020
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_messages.md
  _docs/_api/endpoints/messaging/schedule_messages/post_update_scheduled_messages.md
  _docs/_api/endpoints/messaging/send_messages/post_send_messages.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/font_customization.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/font_customization.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/carthage_integration.md
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
  _docs/_developer_guide/platform_integration_guides/xamarin/ios/sdk_integration.md
  _docs/_help/help_articles/data/change_custom_data_type.md
  _docs/_user_guide/administrative/access_braze/portal.md
  _docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/campaign_funnel_report.md
  _docs/_user_guide/engagement_tools/canvas/canvas_funnel_reports.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
  assets/img/content_cards/content_card_removal_event.png
  assets/img/funnel_report/funnel_report5.png
  assets/img/portal.png
Labels: Deploy, cla-signed

#1572 Handbook update for jc
  assets/download_file/Braze_Success_and_Support_Services_Handbook.pdf
Labels: cla-signed

#1573 Leftover Deploy Pt.2 - 10/15/2020
  assets/download_file/Braze_Success_and_Support_Services_Handbook.pdf
Labels: Deploy, cla-signed

#1574 Updated users.export.ids description
  _docs/_api/api_key.md
Labels: cla-signed

#1575 Removed misleading sentence on User Delete
  _docs/_api/endpoints/user_data/post_user_delete.md
Labels: cla-signed

#1578 BD-678: Campaign Calendar Clarification
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/campaign_calendar.md
Labels: cla-signed

#1577 BD-702
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
Labels: cla-signed

#1556 Small updates email team - MERGE ON 10/20
  _docs/_api/endpoints/templates/email_templates/post_create_email_template.md
  _docs/_api/endpoints/templates/email_templates/post_update_email_template.md
  _docs/_user_guide/message_building_by_channel/email/link_templates.md
Labels: cla-signed

#1576 [SDK-877] Adds documentation for Swift Package Manager
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/carthage_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/swift_package_manager.md
  assets/img/ios/spm/image1.png
  assets/img/ios/spm/image2.png
  assets/img/ios/spm/image3.png
  assets/img/ios/spm/image4.png
  assets/img/ios/spm/image5.png
  assets/img/ios/spm/image6.png
  assets/img/swift.png
Labels: cla-signed

#1581 november_release_notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2020.md
  _docs/_help/release_notes/2020/november.md
Labels: cla-signed

#1582 Publish hidden documentation for Segment Cohorts early access customers
  _docs/_user_guide/engagement_tools/segments/segment_cohorts.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  assets/img/segment_cohort_as_filter1.png
  assets/img/segment_cohort_as_filter2.png
  assets/img/segment_cohort_criteria.png
  assets/img/segment_cohort_list.png
  assets/img/segment_cohort_name.png
  assets/img/segment_cohort_nav.png
  assets/img/segment_cohort_save.png
  assets/img/segment_cohort_view.png
Labels: cla-signed

#1583 Predictive Churn FAQ
  _docs/_user_guide/predictive_suite/predictive_churn/prediction_faq.md
  assets/img/churn/churn3.png
  assets/img/churn/churn4.png
  assets/img/churn/churn5.png
Labels: cla-signed

#1584 Deploy - October 20, 2020
  _docs/_api/api_key.md
  _docs/_api/endpoints/templates/email_templates/post_create_email_template.md
  _docs/_api/endpoints/templates/email_templates/post_update_email_template.md
  _docs/_api/endpoints/user_data/post_user_delete.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/carthage_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/swift_package_manager.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2020.md
  _docs/_help/release_notes/2020/november.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/campaign_calendar.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/segments/segment_cohorts.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/message_building_by_channel/email/link_templates.md
  _docs/_user_guide/predictive_suite/predictive_churn/prediction_faq.md
  assets/img/churn/churn3.png
  assets/img/churn/churn4.png
  assets/img/churn/churn5.png
  assets/img/ios/spm/image1.png
  assets/img/ios/spm/image2.png
  assets/img/ios/spm/image3.png
  assets/img/ios/spm/image4.png
  assets/img/ios/spm/image5.png
  assets/img/ios/spm/image6.png
  assets/img/segment_cohort_as_filter1.png
  assets/img/segment_cohort_as_filter2.png
  assets/img/segment_cohort_criteria.png
  assets/img/segment_cohort_list.png
  assets/img/segment_cohort_name.png
  assets/img/segment_cohort_nav.png
  assets/img/segment_cohort_save.png
  assets/img/segment_cohort_view.png
  assets/img/swift.png
Labels: Deploy, cla-signed

#1586 Sdk 898/post 11.0.0 docs updates
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
Labels: cla-signed

#1588 Adding content card removal docs to Canvas tab
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
Labels: cla-signed

#1590 BD-717: Update Sendgrid email subscriptions description
  _docs/_help/best_practices/email/managing_email_subscriptions.md
Labels: cla-signed

#1589 BD-718: Edit web integration code snippet
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed.md
Labels: cla-signed

#1591 Minor grammatical change
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
Labels: cla-signed

#1579 Add option to flag endpoint as core
  _plugins/api.rb
  assets/css/_api.scss
Labels: cla-signed

#1593 Leftover Deploy - 10/22/2020
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed.md
  _docs/_help/best_practices/email/managing_email_subscriptions.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _plugins/api.rb
  assets/css/_api.scss
Labels: Deploy, cla-signed

#1585 Canvas Updates - MERGE ON 10/26
  _docs/_user_guide/engagement_tools/canvas/canvas_components/decision_split.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/fb_audience_sync.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  assets/img_archive/Canvas_Additional_Engagement.png
  assets/img_archive/Canvas_Advancement_Behavior.png
  assets/img_archive/Canvas_Analytics.png
  assets/img_archive/Canvas_Exception_Events.png
  assets/img_archive/Canvas_Message_Edit.png
  assets/img_archive/Canvas_More_Step.png
  assets/img_archive/Canvas_Multiple_Variants.png
  assets/img_archive/Canvas_Multivariate.png
  assets/img_archive/Canvas_One_Day.png
  assets/img_archive/canvas_intelligent_selection.png
Labels: cla-signed

#1599 Deploy - October, 26, 2020
  _docs/_user_guide/engagement_tools/canvas/canvas_components/decision_split.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/fb_audience_sync.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  assets/img_archive/Canvas_Additional_Engagement.png
  assets/img_archive/Canvas_Advancement_Behavior.png
  assets/img_archive/Canvas_Analytics.png
  assets/img_archive/Canvas_Exception_Events.png
  assets/img_archive/Canvas_Message_Edit.png
  assets/img_archive/Canvas_More_Step.png
  assets/img_archive/Canvas_Multiple_Variants.png
  assets/img_archive/Canvas_Multivariate.png
  assets/img_archive/Canvas_One_Day.png
  assets/img_archive/canvas_intelligent_selection.png
Labels: Deploy, cla-signed

#1602 BD-690: Radar Product Updates
  _docs/_partners/data_augmentation/contextual_location/radar.md
Labels: cla-signed

#1601 Minor Edits to Partership Guide
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
Labels: cla-signed

#1603 BD-720: Remove Link
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
Labels: cla-signed

#1596 I palindrome i/update react native docs
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards/overview.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/sdk_integration.md
Labels: cla-signed

#1605 BD-705,BD-703
  _docs/_developer_guide/platform_integration_guides/web/amp_support.md
  _docs/_hidden/private_betas/amphtml.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/custom_keyword_handling.md
Labels: cla-signed

#1604 BD-721: Updates to Persistent Entry Properties Doc
  _docs/_hidden/private_betas/canvas_persistent_entry_properties.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md
  _docs/_user_guide/personalization_and_dynamic_content.md
  _docs/_user_guide/personalization_and_dynamic_content/canvas_persistent_entry_properties.md
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
Labels: cla-signed

#1606 Remove Telesign from Docs
  _docs/_partners/additional_channels.md
  _docs/_partners/additional_channels/sms.md
  _docs/_partners/additional_channels/sms/telesign.md
  _docs/_partners/home.md
Labels: cla-signed

#1607 Update beta-preview.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/beta-preview.md
Labels: cla-signed

#1608 Add arbitrary button IDs to preview docs
  _docs/_user_guide/message_building_by_channel/in-app_messages/beta-preview.md
Labels: cla-signed, status: on hold / do not merge

#1609 rollback
  _docs/_user_guide/message_building_by_channel/in-app_messages/beta-preview.md
Labels: cla-signed

#1594 Shopify Beta Doc - MERGE ON 10/29
  _docs/_hidden/private_betas/shopify.md
  assets/img/Shopify/arrow.jpeg
  assets/img/Shopify/shopify_connected_content1.png
  assets/img/Shopify/shopify_connected_content2.png
  assets/img/Shopify/shopify_connected_content3.png
  assets/img/Shopify/shopify_connected_content4.png
  assets/img/Shopify/shopify_connected_content5.png
  assets/img/Shopify/shopify_integration1.png
  assets/img/Shopify/shopify_integration10.png
  assets/img/Shopify/shopify_integration11.png
  assets/img/Shopify/shopify_integration12.png
  assets/img/Shopify/shopify_integration13.png
  assets/img/Shopify/shopify_integration14.png
  assets/img/Shopify/shopify_integration15.png
  assets/img/Shopify/shopify_integration16.png
  assets/img/Shopify/shopify_integration2.png
  assets/img/Shopify/shopify_integration3-6.png
  assets/img/Shopify/shopify_integration7.png
  assets/img/Shopify/shopify_integration8.png
  assets/img/Shopify/shopify_integration9.png
  assets/img/Shopify/shopify_segmentation1.png
  assets/img/Shopify/shopify_segmentation2.png
  assets/img/Shopify/shopify_segmentation3.png
  assets/img/Shopify/shopify_segmentation4.png
  assets/img/Shopify/shopify_troubleshooting1.png
  assets/img/Shopify/shopify_troubleshooting2.png
Labels: cla-signed

#1610 Update push_ttl_settings.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/push_ttl_settings.md
  assets/img/push_ttl.png
Labels: cla-signed

#1600 EduMe Partner Integration Docs - MERGE ON 10/29
  _docs/_partners/channel_extensions.md
  _docs/_partners/channel_extensions/learning.md
  _docs/_partners/channel_extensions/learning/edume.md
  _docs/_partners/home.md
Labels: Braze Partnerships, cla-signed, status: done

#1394 Pypestream Documentation Add - MERGE ON 10/29
  _docs/_partners/advertising_technologies.md
  _docs/_partners/advertising_technologies/attribution.md
  _docs/_partners/advertising_technologies/attribution/pypestream.md
  _docs/_partners/home.md
Labels: Braze Partnerships, cla-signed, status: done

#1259 Jebbit Integration Documentation - MERGE ON 10/29
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/jebbit.md
  _docs/_partners/home.md
Labels: Braze Partnerships, cla-signed, status: done

#1387 Dyspatch Partnership PR - MERGE ON 10/29
  _docs/_partners/channel_extensions.md
  _docs/_partners/channel_extensions/creative_and_personalization.md
  _docs/_partners/channel_extensions/creative_and_personalization/email_orchestration/dyspatch.md
  _docs/_partners/home.md
  assets/img/dyspatch/dyspatch_downloading.png
  assets/img/dyspatch/dyspatch_upload.png
Labels: Braze Partnerships, cla-signed, status: done

#1382 RudderStack PR - MERGE ON 10/29
  _docs/_hidden/wip_partnerships/partnership_template.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack.md
  _docs/_partners/home.md
  assets/img/RudderStack/braze_settings.png
Labels: Braze Partnerships, cla-signed, status: done

#1614 BD-722: Update Push Migration Help Article
  _docs/_help/help_articles/push/push_token_migration.md
Labels: cla-signed

#1613 Remove Wavecell Documentation
  _docs/_partners/additional_channels.md
  _docs/_partners/additional_channels/sms.md
  _docs/_partners/additional_channels/sms/wavecell.md
  _docs/_partners/home.md
Labels: cla-signed

#1616 Update beta-preview.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/beta-preview.md
Labels: cla-signed
