Repository braze-inc/braze-docs, pull requests merged in 2020-06, with the labels that each got.

#1184 IR-1366: Update /docs/api/basics/#api-limits to include the new default /users/track rate-limit
  _docs/_api/basics.md
  _docs/_api/endpoints/user_data/post_user_track.md
Labels: cla-signed

#1142 BD-523: Update Rokt Calendar docs to new integration
  _docs/_partners/additional_channels/calendar/rokt_calendar.md
Labels: cla-signed

#1202 Update post_schedule_triggered_canvases.md
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_canvases.md
Labels: cla-signed

#1201 Kh/june release notes
  _docs/_api/basics.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2020.md
  _docs/_help/release_notes/2020/june.md
Labels: cla-signed

#1200 Deploy - June 2, 2020
  _docs/_api/basics.md
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_canvases.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2020.md
  _docs/_help/release_notes/2020/june.md
  _docs/_partners/additional_channels/calendar/rokt_calendar.md
  assets/css/_content.scss
Labels: cla-signed

#1203 small change
  _docs/_partners/additional_channels/surveys.md
  _docs/_partners/additional_channels/surveys/iterate.md
Labels: cla-signed

#1205 Added "Access Denied" message
  _docs/_api/errors.md
Labels: cla-signed

#1206 Wording change for request limit
  _docs/_api/endpoints/user_data/post_user_track.md
Labels: cla-signed

#1207 notification priority note for FireOS Push
  _docs/_developer_guide/platform_integration_guides/fireos/push_notifications/troubleshooting.md
Labels: cla-signed

#1208 SDK-118 8.0.0 release documentation
  _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_sessions.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
Labels: cla-signed

#1214 api page clarifications
  _docs/_api/basics.md
  _docs/_api/endpoints/user_data/post_user_track.md
Labels: cla-signed

#1215 Leftover Deploy - June 4, 2020
  _docs/_api/basics.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_api/errors.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_sessions.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/push_notifications/troubleshooting.md
  _docs/_partners/additional_channels/surveys.md
  _docs/_partners/additional_channels/surveys/iterate.md
Labels: cla-signed

#1212 consolidated deep link advanced docs for android
  _docs/_api/objects_filters/android_objects.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking_to_in-app_resources.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/push_notifications/integration.md
  _docs/_user_guide/personalization_and_dynamic_content/deep_linking_to_in-app_content.md
Labels: cla-signed

#1209 SDK-294 - Android - added jetification docs ✈️
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
Labels: cla-signed

#1204 [SDK-158] iOS Google Tag Manager Docs
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/google_tag_manager.md
Labels: cla-signed

#1216 BD-559: Audience sync fb update
  _docs/_hidden/private_betas/fb_audience_sync.md
  assets/img/fb_audience_sync/FB2.png
  assets/img/fb_audience_sync/sync_setup.png
  assets/img/fb_audience_sync/sync_setup2.png
  assets/img/fb_audience_sync/sync_setup3.png
Labels: cla-signed

#1217 BD-556: canvas persistent entry hidden documentation
  _docs/_hidden/private_betas/canvas_persistent_entry_properties.md
  assets/img/persistent_entry_properties/PEP.png
  assets/img/persistent_entry_properties/PEP1.png
  assets/img/persistent_entry_properties/PEP12.png
  assets/img/persistent_entry_properties/PEP2.png
  assets/img/persistent_entry_properties/PEP_phone.png
  assets/img/persistent_entry_properties/PEP_phone2.png
Labels: cla-signed

#1102 Add setLanguage to web SDK
  _includes/archive/appboyBridge.md
Labels: cla-signed

#1219 BD-562
  _docs/_hidden/private_betas/promo_codes.md
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
Labels: cla-signed

#1218 Deploy - June 9, 2020
  _docs/_api/objects_filters/android_objects.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking_to_in-app_resources.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/google_tag_manager.md
  _docs/_hidden/private_betas/canvas_persistent_entry_properties.md
  _docs/_hidden/private_betas/fb_audience_sync.md
  _docs/_hidden/private_betas/promo_codes.md
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
  _docs/_user_guide/personalization_and_dynamic_content/deep_linking_to_in-app_content.md
  _includes/archive/appboyBridge.md
  assets/img/fb_audience_sync/FB2.png
  assets/img/fb_audience_sync/sync_setup.png
  assets/img/fb_audience_sync/sync_setup2.png
  assets/img/fb_audience_sync/sync_setup3.png
  assets/img/persistent_entry_properties/PEP.png
  assets/img/persistent_entry_properties/PEP1.png
  assets/img/persistent_entry_properties/PEP12.png
  assets/img/persistent_entry_properties/PEP2.png
  assets/img/persistent_entry_properties/PEP_phone.png
  assets/img/persistent_entry_properties/PEP_phone2.png
Labels: Deploy, cla-signed

#1220 BD-561: fix currents s3 permission
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
Labels: cla-signed

#1221 Typos
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/multiple_feeds.md
  _docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
Labels: cla-signed

#1228 Content card documentation, supplemented with gif
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  assets/img/content_card.gif
Labels: cla-signed

#1227 necessary edit to fix repo from breaking
  _docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
  tk
Labels: cla-signed

#1229 BD-557
  _docs/_user_guide/engagement_tools/locations_and_geofences.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/faqs.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/geofence_configuration.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/location_tracking.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/mobile_integrations.md
  assets/img/users_track_endpoint.png
Labels: cla-signed

#1230 Leftover Deploy - June 11, 2020
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/multiple_feeds.md
  _docs/_hidden/private_betas/canvas_persistent_entry_properties.md
  _docs/_hidden/private_betas/create_send.md
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
  _docs/_hidden/wip_partnerships/partnership_template.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
  _docs/_user_guide/engagement_tools/locations_and_geofences.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/faqs.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/geofence_configuration.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/location_tracking.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/mobile_integrations.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
  assets/img/content_card.gif
  assets/img/partner_template/partner_folder.png
  assets/img/users_track_endpoint.png
  assets/js/broken_redirect_list.js
  tk
Labels: Deploy, cla-signed

#1232 BD-564
  _docs/_user_guide/personalization_and_dynamic_content.md
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
  assets/img/promocodes/promocode5.png
  assets/img/promocodes/promocode7.png
Labels: cla-signed

#1233 Remove outdated coming soon labels
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/localization.md
  _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/localization.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/localization.md
Labels: cla-signed

#1234 Update WIP_guidelines.md
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
Labels: cla-signed

#1198 Update get_list_user_subscription_group_status.md
  _docs/_api/endpoints/subscription_groups/get_list_user_subscription_group_status.md
Labels: cla-signed

#1238 Updates to Partner Template Form
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
  assets/img/partner_template/partner_merge.png
Labels: cla-signed

#1241 BD-566: Update to users/identify endpoint
  _docs/_api/endpoints/user_data/post_user_identify.md
Labels: cla-signed

#1239 IAM Image Templates: Download Zip
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/fullscreen.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/modal.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/slideup.md
  assets/download_file/Braze-In-App-Message-Design-Templates.zip
Labels: cla-signed

#1242 alias link fix for IAM zip update
  _docs/_user_guide/message_building_by_channel/in-app_messages.md
Labels: cla-signed

#1235 Update integration.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
Labels: cla-signed

#1243 Update typo in regex.md
  _docs/_user_guide/engagement_tools/segments/regex.md
Labels: cla-signed

#1240 Deploy - June 16, 2020
  _docs/_api/endpoints/subscription_groups/get_list_user_subscription_group_status.md
  _docs/_api/endpoints/user_data/post_user_identify.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/localization.md
  _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/localization.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/localization.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
  _docs/_user_guide/engagement_tools/segments/regex.md
  _docs/_user_guide/message_building_by_channel/in-app_messages.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/fullscreen.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/modal.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/slideup.md
  _docs/_user_guide/personalization_and_dynamic_content.md
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
  assets/download_file/Braze-In-App-Message-Design-Templates.zip
  assets/img/partner_template/partner_merge.png
  assets/img/promocodes/promocode5.png
  assets/img/promocodes/promocode7.png
Labels: cla-signed

#1245 BD-573
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#1246 Fix search when multiple platforms
  _includes/search_page.html
  assets/js/documents.js
Labels: cla-signed

#1248 BD-574: filter categories link fix
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#1249 Update google verify
  _includes/html_include.html
Labels: cla-signed

#1254 BD-575
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/retention_reports.md
  _docs/_user_guide/engagement_tools/canvas/retention_reports.md
Labels: cla-signed

#1251 Removing recommendation to collect email address for convenience
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/setting_custom_attributes.md
Labels: cla-signed

#1236 update currents docs with the new field
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#1255 tk/canvas_typo_fix
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
Labels: cla-signed

#1256 fix typo
  _docs/_user_guide/message_building_by_channel/content_cards/reporting.md
Labels: cla-signed

#1258 Leftover Deploy - June 18, 2020
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/setting_custom_attributes.md
  _docs/_hidden/other/documentation_request.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/retention_reports.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/retention_reports.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/message_building_by_channel/content_cards/reporting.md
  _includes/html_include.html
  _includes/search_page.html
  assets/js/documents.js
Labels: Deploy, cla-signed

#1261 maintainer checkbox
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
  assets/img/partner_template/maintainers.png
Labels: cla-signed

#1158 Huawei Push
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/huawei_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration_baidu.md
  assets/img/huawei/huawei-create-app.png
  assets/img/huawei/huawei-credentials.png
  assets/img/huawei/huawei-dashboard-credentials.png
  assets/img/huawei/huawei-segmentation.png
  assets/img/huawei/huawei-test-push-composer.png
  assets/img/huawei/huawei-test-push-platforms.png
  assets/img/huawei/huawei-test-send.png
Labels: cla-signed

#1265 BD-577: Create/send endpoint clarification
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#1266 Update get_campaigns.md and get_canvas.md
  _docs/_api/endpoints/export/campaigns/get_campaigns.md
  _docs/_api/endpoints/export/canvas/get_canvases.md
Labels: cla-signed

#1268 updated huawei screenshots
  assets/img/huawei/huawei-create-app.png
  assets/img/huawei/huawei-segmentation.png
Labels: cla-signed

#1272 Update Gems
  Gemfile.lock
Labels: cla-signed

#1270 Add ABKIDFADelegateKey info
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
Labels: cla-signed

#1274 BD-581
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
Labels: cla-signed

#1275 BD-578
  _docs/_partners/advertising_technologies/social/facebook.md
Labels: cla-signed

#1269 iOS docs saying we don't display IAMs when keyboard is up
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md
Labels: cla-signed

#1276 Leftover Deploy - June 25, 2020
  Gemfile.lock
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
  _docs/_partners/advertising_technologies/social/facebook.md
  assets/img/huawei/huawei-create-app.png
  assets/img/huawei/huawei-segmentation.png
Labels: Deploy, cla-signed

#1278 BD-579: Campaign Comparison Update
  _docs/_hidden/private_betas/campaign_comparison_updates.md
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
  assets/img/campaign_comparison/compare_button.png
  assets/img/campaign_comparison/compare_note.png
  assets/img/campaign_comparison/compare_option.png
Labels: cla-signed

#1280 rs -> SDWebImage
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/carthage_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options.md
  _docs/_developer_guide/platform_integration_guides/unity/ios/sdk_integration.md
  _includes/archive/unity/unitypackage_descriptions.md
Labels: cla-signed

#1250 [TO BE MERGED 6/30] add description for BCC feature functionality
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  assets/img/email_settings/bcc_address.png
  assets/img/email_settings/require_bcc.png
Labels: cla-signed

#1281 July 2020 Release Notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2020.md
  _docs/_help/release_notes/2020/july.md
Labels: cla-signed

#1273 [TO BE MERGED 6/30] BD-555
  _docs/_hidden/private_betas/retention_reports.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/retention_reports.md
  _docs/_user_guide/engagement_tools/canvas/retention_reports.md
  assets/img/variant_view.png
  assets/img/variant_view_canvas.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, status: on hold / do not merge

#1282 refresh screenshot for Segment description
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  assets/img_archive/Segment2.png
Labels: cla-signed

#1283 BD-558: Apple Email Relay - SSO
  _docs/_hidden/private_betas/auto_advance.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/advancement.md
  _docs/_user_guide/message_building_by_channel/email.md
  _docs/_user_guide/message_building_by_channel/email/email_private_relay_apple_SSO.md
Labels: cla-signed

#1284 BD-583: Clarifying Segmentation for purchase properties
  _docs/_api/objects_filters/purchase_object.md
Labels: cla-signed

#1285 BD-580: UserTrack - Data point consumption note
  _docs/_api/endpoints/user_data/post_user_track.md
Labels: cla-signed

#1286 Update `/user/alias/new` docs for clarity
  _docs/_api/endpoints/user_data/post_user_alias.md
Labels: cla-signed

#1287 View pii
  _docs/_hidden/private_betas/view_pii.md
  assets/img/user_profile_obfuscated1.png
  assets/img/user_profile_obfuscated2.png
  assets/img/user_profile_obfuscated3.png
Labels: cla-signed

#1231 new HTML asset uploader
  _docs/_user_guide/message_building_by_channel/in-app_messages/beta-preview.md
  assets/img/iam-beta-html-asset-uploader.gif
  assets/img/iam-beta-html-dropdown.gif
  assets/img/iam-beta-html-dropdown.png
Labels: cla-signed

#1288 Deploy - June 30, 2020
  _docs/_api/endpoints/user_data/post_user_alias.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_api/objects_filters/purchase_object.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/carthage_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options.md
  _docs/_developer_guide/platform_integration_guides/unity/ios/sdk_integration.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2020.md
  _docs/_help/release_notes/2020/july.md
  _docs/_hidden/private_betas/auto_advance.md
  _docs/_hidden/private_betas/campaign_comparison_updates.md
  _docs/_hidden/private_betas/retention_reports.md
  _docs/_hidden/private_betas/view_pii.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/retention_reports.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/advancement.md
  _docs/_user_guide/engagement_tools/canvas/retention_reports.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _docs/_user_guide/message_building_by_channel/email.md
  _docs/_user_guide/message_building_by_channel/email/email_private_relay_apple_SSO.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/beta-preview.md
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
  _includes/archive/unity/unitypackage_descriptions.md
  assets/img/campaign_comparison/compare_button.png
  assets/img/campaign_comparison/compare_note.png
  assets/img/campaign_comparison/compare_option.png
  assets/img/email_settings/bcc_address.png
  assets/img/email_settings/require_bcc.png
  assets/img/iam-beta-html-asset-uploader.gif
  assets/img/iam-beta-html-dropdown.gif
  assets/img/iam-beta-html-dropdown.png
  assets/img/user_profile_obfuscated1.png
  assets/img/user_profile_obfuscated2.png
  assets/img/user_profile_obfuscated3.png
  assets/img/variant_view.png
  assets/img/variant_view_canvas.png
  assets/img_archive/Segment2.png
  assets/js/broken_redirect_list.js
Labels: Deploy, cla-signed
