Repository braze-inc/braze-docs, pull requests merged in 2021-05, with the labels that each got.

#2082 Fix Wrong words in airbridge.md
  _docs/_partners/message_orchestration/attribution/airbridge.md
Labels: cla-signed

#2080 BD-921: Update Image
  assets/img_archive/schedule_triggered1.png
Labels: cla-signed

#2083 updated kotlin sample for Content Cards customization
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
Labels: cla-signed

#2084 BD-884: Clarification on Canvas Audience Evaluation
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/delivery_types/triggered_delivery.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/decision_split.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  assets/img_archive/reevaluate_segment_membership.png
Labels: cla-signed

#2079 BD-918: User Attribute Lambda Function
  _docs/_hidden/other/core_endpoints.md
  _docs/_hidden/other/user_csv_lambda.md
  _docs/_hidden/private_betas/shopify.md
Labels: cla-signed

#2085 Added Phrasee to Public Docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/ab_testing.md
  _docs/_partners/data_and_infrastructure_agility/ab_testing/phrasee.md
  _docs/_partners/data_and_infrastructure_agility/analytics.md
  _docs/_partners/data_and_infrastructure_agility/crash_analytics.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses.md
  _docs/_partners/data_and_infrastructure_agility/support.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation.md
  _docs/_partners/data_and_infrastructure_agility/wrapper_sdks.md
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/channel_extensions.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content.md
  _docs/_partners/message_personalization/location.md
  assets/img/phrasee/10_Push_Two_Lines.png
  assets/img/phrasee/10_push_two_lines.png
  assets/img/phrasee/11_Push_MessageBody.png
  assets/img/phrasee/11_push_messagebody.png
  assets/img/phrasee/1_Create_APIKey.png
  assets/img/phrasee/1_create_apikey.png
  assets/img/phrasee/2_CampaignAccess.png
  assets/img/phrasee/2_campaignaccess.png
  assets/img/phrasee/3_Phrasee_Braze1.png
  assets/img/phrasee/3_phrasee_braze1.png
  assets/img/phrasee/4_Braze_Emailtag.png
  assets/img/phrasee/4_braze_emailtag.png
  assets/img/phrasee/5_Copy_Variant_Braze.png
  assets/img/phrasee/5_copy_variant_braze.png
  assets/img/phrasee/6_Braze_Schedule.png
  assets/img/phrasee/6_braze_schedule.png
  assets/img/phrasee/7_Braze_Send_Winner.png
  assets/img/phrasee/7_braze_send_winner.png
  assets/img/phrasee/8_Braze_Int_Drawer.png
  assets/img/phrasee/8_braze_int_drawer.png
  assets/img/phrasee/9_Braze_Push_Tag.png
  assets/img/phrasee/9_braze_push_tag.png
Labels: cla-signed, release notes

#2087 BD-923: Grammatical Fixes on SMS Subscription Page
  _docs/_user_guide/onboarding_with_braze/sms_setup/sms_subscription_groups.md
Labels: cla-signed

#2088 BD-920: Add Recommendation for Resolving Export Size Limitations
  _docs/_user_guide/data_and_analytics/export_braze_data/segment_data_to_csv.md
Labels: cla-signed

#2078 May Release Notes - MERGE ON 5/4
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2020/october.md
  _docs/_help/release_notes/2021.md
  _docs/_help/release_notes/2021/may.md
Labels: cla-signed

#2017 SDK Authentication updates
  _docs/_developer_guide/platform_wide/sdk_authentication.md
Labels: cla-signed

#2092 Update tv_and_ott.md
  _docs/_developer_guide/platform_wide/tv_and_ott.md
Labels: cla-signed

#2096 Update Simple Survey
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
  assets/img/iam/iam-survey2.png
  assets/img/iam/iam-survey3.png
Labels: cla-signed

#2097 BD-896: Update security_settings.md with 2FA recommendation
  _docs/_user_guide/administrative/company_settings/security_settings.md
Labels: cla-signed

#2098 First draft of conv corr
  _docs/_user_guide/engagement_tools/testing/conversion_correlation.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing.md
  assets/img/convcorr.png
Labels: cla-signed, status: on hold / do not merge

#2101 BD-919: Processing order of users/track endpoint components
  _docs/_api/basics.md
  _docs/_partners/message_orchestration/attribution/appsflyer.md
Labels: cla-signed

#2100 SDK-1442/ unity android docs improvement
  _docs/_developer_guide/platform_integration_guides/unity/android/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/unity/android/sdk_integration.md
  assets/img/unity/android/unity_android_full_push_listener.png
  assets/img/unity/android/unity_android_push_settings_config.png
Labels: cla-signed

#2108 Deploy Pt. 2 - May 11, 2021
  _docs/_partners/message_orchestration/attribution/branch/branch_for_attribution.md
  _docs/_user_guide/data_and_analytics/your_reports.md
Labels: Deploy, cla-signed

#2111 BD-928: Update report_metrics.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
Labels: cla-signed

#2113 Update analytics_glossary.md
  _docs/_user_guide/message_building_by_channel/email/analytics_glossary.md
Labels: cla-signed

#2116 BD-929: Update push token migration examples
  _docs/_help/help_articles/push/push_token_migration.md
Labels: cla-signed

#2115 Update faqs.md
  _docs/_help/faqs.md
Labels: cla-signed

#2119 fix searches with "/"
  _includes/search_page.html
Labels: cla-signed

#2118 Note - Segment Extension Data Points
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
Labels: cla-signed

#2109 [DI-2240] Add bad creds warnings to all the Currents docs
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/google_cloud_storage_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/microsoft_azure_blob_storage_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/available_partners.md
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
Labels: cla-signed

#2110 [SDK-1513] Cleanup a bit of IAM/NF instructions
  _docs/_api/endpoints/export/news_feed/get_news_feed_cards.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/localization.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/news_feed/news_feed_data_model.md
  _docs/_user_guide/engagement_tools/news_feed/creating_a_news_feed_item.md
  assets/img_archive/crosspromo.png
Labels: cla-signed

#2112 [Trivial] Add color reference for com_appboy_default_notification_accent_color
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
Labels: cla-signed

#2114 Add US-05 endpoints. Correct US-08 IPs for connected content/webhooks.
  _docs/_api/basics.md
  _docs/_partners/isv_partners/cohort_import.md
  _docs/_user_guide/administrative/access_braze/braze_instances.md
  _docs/_user_guide/administrative/access_braze/sdk_endpoints.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
Labels: cla-signed

#2117 Experiment Step docs
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
  assets/img/experiment_step/exp_settings.png
  assets/img/experiment_step/experiment_step.png
Labels: cla-signed

#2120 Add Audience Path Tile to Canvas Landing Page
  _docs/_user_guide/engagement_tools/canvas.md
Labels: cla-signed

#2122 Leftover Deploy - May 13, 2021
  _docs/_api/basics.md
  _docs/_api/endpoints/export/news_feed/get_news_feed_cards.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/localization.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/news_feed/news_feed_data_model.md
  _docs/_help/faqs.md
  _docs/_help/help_articles/push/push_token_migration.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/google_cloud_storage_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/microsoft_azure_blob_storage_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _docs/_partners/isv_partners/cohort_import.md
  _docs/_user_guide/administrative/access_braze/braze_instances.md
  _docs/_user_guide/administrative/access_braze/sdk_endpoints.md
  _docs/_user_guide/data_and_analytics/braze_currents/available_partners.md
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/engagement_tools/canvas.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
  _docs/_user_guide/engagement_tools/news_feed/creating_a_news_feed_item.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/message_building_by_channel/email/analytics_glossary.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
  _includes/search_page.html
  assets/img/experiment_step/exp_settings.png
  assets/img/experiment_step/experiment_step.png
  assets/img_archive/crosspromo.png
Labels: Deploy, cla-signed

#2124 Iam survey
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
  assets/img/iam/iam-survey3.png
Labels: cla-signed

#2121 BD-930: Inkit Webhook Update
  _docs/_partners/message_orchestration/additional_channels/direct_mail/inkit.md
Labels: cla-signed

#2123 BD-931: App redownload push subscription and registration behavior
  _docs/_user_guide/message_building_by_channel/push/push_registration.md
Labels: cla-signed

#2126 BD-934: Typo Fix
  _docs/_help/help_articles/email/html_looks_strange.md
Labels: cla-signed

#2129 Adds AppGroup documentation
  _docs/_developer_guide/platform_integration_guides/ios/push_story.md
Labels: cla-signed

#2128 Update customize.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
Labels: cla-signed

#2130 BD-935: Clarify phone field for user import
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Labels: cla-signed

#2132 Update message_engagement_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#2131 BD-936: Add additional context to "Push Enabled for App" filter
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#2135 Update Subscription Group docs with new UI
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#2134 Update report_metrics.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
Labels: cla-signed

#2137 fix support search
  _docs/_hidden/other/support_contact.md
Labels: cla-signed

#2138 Description YAML Update - Pt.3
  _docs/_user_guide/intelligence.md
  _docs/_user_guide/intelligence/intelligent_channel.md
  _docs/_user_guide/intelligence/intelligent_selection.md
  _docs/_user_guide/intelligence/intelligent_timing.md
  _docs/_user_guide/personalization_and_dynamic_content.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/aborting_connected_content.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/about_connected_content.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/connected_content_retries.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/public_apis.md
  _docs/_user_guide/personalization_and_dynamic_content/content_blocks.md
  _docs/_user_guide/personalization_and_dynamic_content/deep_linking_to_in-app_content.md
  _docs/_user_guide/personalization_and_dynamic_content/emoji_messaging.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/aborting_messages.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/accounting_for_null_attribute_values.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_use_cases.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
  _docs/_user_guide/predictive_suite.md
  _docs/_user_guide/predictive_suite/predictive_churn.md
  _docs/_user_guide/predictive_suite/predictive_churn/creating_a_churn_prediction.md
  _docs/_user_guide/predictive_suite/predictive_churn/messaging_users.md
  _docs/_user_guide/predictive_suite/predictive_churn/prediction_analytics.md
  _docs/_user_guide/predictive_suite/predictive_churn/prediction_analytics/prediction_quality.md
  _docs/_user_guide/predictive_suite/predictive_churn/prediction_faq.md
  _docs/_user_guide/predictive_suite/predictive_purchases.md
  _docs/_user_guide/predictive_suite/predictive_purchases/creating_a_purchase_prediction.md
  _docs/_user_guide/predictive_suite/predictive_purchases/messaging_users.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#2136 Link and Image Fix
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications.md
  assets/img/sub_group_create.png
Labels: cla-signed

#2140 Update user_profile_lifecycle.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
Labels: cla-signed

#2143 Update sdk_authentication.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
Labels: cla-signed

#2146 BD-938: Update Mixpanel for Currents Events
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
Labels: cla-signed

#2145 Update nokogiri version to 1.11.4
  Gemfile.lock
  _config.yml
Labels: cla-signed

#2141 Update data_retention.md
  _docs/_api/data_retention.md
Labels: cla-signed

#2148 Add legal comments
  _docs/_api/data_retention.md
  _docs/_developer_guide/disclosures/open_source_software_disclosure.md
  _docs/_developer_guide/disclosures/security_and_vulnerability_disclosure.md
  _docs/_developer_guide/disclosures/security_qualifications.md
  _docs/_help/dp-technical-assistance.md
  _docs/_help/innovation_statement.md
  _docs/_partners/third_party_liability.md
Labels: cla-signed

#2150 Added guidance regarding race conditions
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
Labels: cla-signed

#2147 Update data_retention.md
  _docs/_api/data_retention.md
Labels: cla-signed

#2151 [SDK-1381][Trivial] Remove China Push Sample references
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration_baidu.md
Labels: cla-signed

#2152 BD-922: Update advanced_filters.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters.md
Labels: cla-signed

#2154 Description YAML Update: Pt. 5
  _docs/_partners/canvas_steps/facebook_audience_sync.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_partners/data_and_infrastructure_agility/ab_testing/phrasee.md
  _docs/_partners/data_and_infrastructure_agility/analytics/kubit.md
  _docs/_partners/data_and_infrastructure_agility/analytics/neura_insights.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/census.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/treasure_data.md
  _docs/_partners/data_and_infrastructure_agility/support/pypestream.md
  _docs/_partners/data_and_infrastructure_agility/support/zendesk.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/fivetran.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/zapier.md
  _docs/_partners/home.md
  _docs/_partners/message_orchestration/additional_channels/mobile_wallet/passkit.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/dyspatch.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/stensul.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/stripo.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/taxi_for_email.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/jebbit.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/talonone.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/voucherify.md
  _docs/_partners/message_orchestration/learning/edume.md
  _docs/_partners/message_personalization/dynamic_content/certona.md
  _docs/_partners/message_personalization/dynamic_content/movable_ink.md
  _docs/_partners/message_personalization/dynamic_content/playable.md
  _docs/_partners/message_personalization/localization/crowdin.md
  _docs/_partners/message_personalization/localization/transifex.md
  _docs/_partners/message_personalization/location/neura_actions.md
Labels: cla-signed

#2155 Add reports_overview.md and update your_reports.md
  _docs/_user_guide/data_and_analytics/your_reports.md
  _docs/_user_guide/data_and_analytics/your_reports/reports_overview.md
Labels: cla-signed

#2157 Update custom_event_and_attribute_management.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/custom_event_and_attribute_management.md
Labels: cla-signed

#2159 BD-940: Link fix
  _docs/_api/network_connectivity_issues.md
Labels: cla-signed

#2049 Web sdk z index
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization.md
Labels: cla-signed

#1965 [SDK-1261][SDK-1262] - Update docs to reflect Web SDK deprecations
  _docs/_developer_guide/platform_integration_guides/web/analytics/disabling_tracking.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/overview.md
  _docs/_help/best_practices/in-app_messages/previous_in-app_message_generations.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
  _includes/analytics.html
Labels: cla-signed

#2160 Update simple_survey.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
Labels: cla-signed

#2089 Update sdk_authentication.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
Labels: cla-signed

#2164 BD-941: Clarify Data Limitations
  _docs/_hidden/private_betas/nested_object_support.md
Labels: cla-signed

#2165 BD-943: Link fix
  _docs/_user_guide/onboarding_with_braze/web_sdk.md
Labels: cla-signed

#2166 BD-944: Update Phone Request Parameters
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
Labels: cla-signed

#2172 update analytics image
  assets/img/iam/iam-survey-analytics.png
Labels: cla-signed

#2161 Update ios_14.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
Labels: cla-signed

#2173 Fix typo on Currents page
  _docs/_user_guide/data_and_analytics/braze_currents.md
Labels: cla-signed

#2168 Update Algolia SDK to v4
  _docs/_hidden/other/support_contact.md
  _includes/docs_search.html
  _includes/header_search.html
  _includes/html_include.html
  _includes/search_page.html
  assets/css/_contentcards.scss
  assets/css/_doc_guide.scss
  assets/css/_docs_search.scss
  assets/css/_header_search.scss
  assets/css/algolia_theme.css
  assets/css/search_page.scss
  assets/js/algolia_header_search.js
  assets/js/algolia_main_search.js
  assets/js/algolia_search.js
  assets/js/algoliasearch.min.js
  assets/js/autocomplete.jquery.min.js
  assets/js/documents.js
  assets/js/service-worker.js
Labels: cla-signed, status: on hold / do not merge

#2174 Format Cleanup on Styling Test Page
  _docs/_home/styling_test_page.md
Labels: cla-signed

#2175 Fix merge issue from term updates
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#2177 Update global_control_group.md
  _docs/_user_guide/engagement_tools/testing/global_control_group.md
Labels: cla-signed

#2178 Update screenshot
  assets/img/control_group/control_group6.png
Labels: cla-signed

#2045 [SDK-1169] Deprecate AppboyLocationService.requestInitialization(context)
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/locations_and_geofences.md
Labels: cla-signed, status: on hold / do not merge

#2179 Update global_control_group.md
  _docs/_user_guide/engagement_tools/testing/global_control_group.md
Labels: cla-signed

#2181 Update canvas_entry_properties edge case
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
Labels: cla-signed

#2182 Update push_token_migration.md
  _docs/_help/help_articles/push/push_token_migration.md
Labels: cla-signed

#2185 User Guide Introduction Page Link Update
  _docs/_user_guide/introduction.md
Labels: cla-signed

#2187 Reword link to express intent
  _docs/_api/postman_collection.md
Labels: cla-signed

#2190 BD-945: Update example request
  _docs/_partners/isv_partners/cohort_import.md
Labels: cla-signed

#2184 Update FAQs - Pt. 2
  _docs/_api/api_key.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
  _docs/_developer_guide/platform_wide/app_group_configuration.md
  _docs/_help/faqs.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
  _docs/_user_guide/engagement_tools/campaigns.md
  _docs/_user_guide/engagement_tools/campaigns/faq.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/active_user_campaigns.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/faqs.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _docs/_user_guide/message_building_by_channel/email.md
  _docs/_user_guide/message_building_by_channel/email/faq.md
  _docs/_user_guide/onboarding_with_braze/terms_to_know.md
Labels: cla-signed

#2189 Add June 2021 Release Notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2021.md
  _docs/_help/release_notes/2021/june.md
Labels: cla-signed

#2183 Web SDK - Content-Security-Policy
  _docs/_developer_guide/platform_integration_guides/web/content_security_policy.md
Labels: cla-signed
