Repository braze-inc/braze-docs, pull requests merged in 2021-02, with the labels that each got.

#1804 [trivial] Remove unneeded Stopwatch example
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/rich.md
Labels: cla-signed

#1803 Plist instructions for iOS Push Story App Group config
  _docs/_developer_guide/platform_integration_guides/ios/push_story.md
Labels: cla-signed

#1800 BD-797, BD-801
  _docs/_help/release_notes/2020/september.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#1806 Update content-cards_in_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/content-cards_in_canvas.md
Labels: cla-signed

#1795 Web SDK Cookies overview
  _docs/_developer_guide/platform_integration_guides/web/cookies_and_storage.md
Labels: cla-signed

#1808 Api key details
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
Labels: cla-signed

#1809 Content Card Canvas Docs
  _docs/_user_guide/engagement_tools/canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/advancement.md
Labels: cla-signed

#1810 Update inline_image_push.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/inline_image_push.md
Labels: cla-signed

#1805 Remove references to Stopwatch
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/fine_network_traffic_control.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/carthage_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/swift_package_manager.md
  _docs/_developer_guide/platform_integration_guides/ios/news_feed/requesting_unread_card_count.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/action_buttons.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/rich.md
  _docs/_developer_guide/platform_integration_guides/ios/sample_apps.md
  _docs/_developer_guide/platform_integration_guides/tvos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/tvos/news_feed.md
  _docs/_partners/insights/crash_analytics/apteligent.md
  _includes/archive/apple/initial_setup.md
  _includes/archive/in_app_message.md
Labels: cla-signed

#1811 Update preview.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/preview.md
Labels: cla-signed

#1812 BD-804, BD-805, BD-793
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/swift_package_manager.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#1814 Update app_group_configuration.md to not reference old app name lookup on the Stores
  _docs/_developer_guide/platform_wide/app_group_configuration.md
Labels: cla-signed

#1813 Deploy - February 2, 2021
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/inline_image_push.md
  _docs/_developer_guide/platform_integration_guides/cordova/android_and_fireos/cordova_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/fine_network_traffic_control.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/carthage_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/swift_package_manager.md
  _docs/_developer_guide/platform_integration_guides/ios/news_feed/requesting_unread_card_count.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/action_buttons.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/rich.md
  _docs/_developer_guide/platform_integration_guides/ios/push_story.md
  _docs/_developer_guide/platform_integration_guides/ios/sample_apps.md
  _docs/_developer_guide/platform_integration_guides/tvos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/tvos/news_feed.md
  _docs/_developer_guide/platform_integration_guides/web/cookies_and_storage.md
  _docs/_developer_guide/platform_wide/app_group_configuration.md
  _docs/_help/release_notes/2020/september.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_partners/insights/crash_analytics/apteligent.md
  _docs/_user_guide/administrative/access_braze/sdk_endpoints.md
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
  _docs/_user_guide/engagement_tools/canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/advancement.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/content-cards_in_canvas.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/preview.md
  _includes/archive/apple/initial_setup.md
  _includes/archive/cordova/cordova_sdk_integration_template.md
  _includes/archive/in_app_message.md
Labels: Deploy, cla-signed

#1816 Update for iOS 14.5
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
Labels: cla-signed

#1815 Fix event example request indentation
  _docs/_api/objects_filters/event_object.md
Labels: cla-signed

#1819 Leftover Deploy - February 4, 2021
  _docs/_api/objects_filters/event_object.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
Labels: Deploy, cla-signed

#1787 [SDK-1079][Docs] Adding MacOS support through Mac Catalyst
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/swift_package_manager.md
  _docs/_developer_guide/platform_integration_guides/macOS.md
  _docs/_developer_guide/platform_integration_guides/macOS/initial_sdk_setup.md
  assets/img/ios/spm/image6.png
Labels: cla-signed, status: on hold / do not merge

#1820 Data Protection Technical Assistance Guide
  _docs/_api/data_retention.md
  _docs/_developer_guide/disclosures.md
  _docs/_help/dp-technical-assistance.md
  _docs/_help/gdpr_compliance.md
  _docs/_help/home.md
  _docs/_hidden/private_betas/shopify.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_archival.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/retention_reports.md
  _docs/_user_guide/engagement_tools/canvas/retention_reports.md
  _docs/_user_guide/message_building_by_channel/sms/sms_laws_and_regulations.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/sms_laws_and_regulations.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#1767 Canvas Report Builder
  _docs/_user_guide/data_and_analytics/your_reports/report_builder.md
  assets/img/campaign_comparison/create_report.png
  assets/img/campaign_comparison/message_report.png
  assets/img/campaign_comparison/steps_report.png
  assets/img/campaign_comparison/variants_report.png
Labels: cla-signed

#1822 SDK-1106 Remove customization references for iOS CC/NF for the time being
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/read_unread_indicators.md
  _docs/_developer_guide/platform_integration_guides/ios/news_feed/customizing_the_news_feed.md
Labels: cla-signed

#1824 Update ios_14.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
Labels: cla-signed

#1821 Attribution Partner Updates - MERGE 2/9
  _docs/_partners/advertising_technologies/attribution/adjust.md
  _docs/_partners/advertising_technologies/attribution/appsflyer.md
  _docs/_partners/advertising_technologies/attribution/branch_for_attribution.md
  _docs/_partners/advertising_technologies/attribution/kochava.md
  _docs/_partners/advertising_technologies/attribution/singular.md
  assets/img/attribution/adjust.png
  assets/img/attribution/adjust2.png
  assets/img/attribution/appsflyer.png
  assets/img/attribution/branch.png
  assets/img/attribution/kochava.png
  assets/img/attribution/singular.png
Labels: cla-signed

#1827 BD-822, BD-821
  _docs/_api/objects_filters/purchase_object.md
  _docs/_hidden/private_betas/shopify.md
Labels: cla-signed

#1826 Deploy - February 9, 2020
  _docs/_api/data_retention.md
  _docs/_api/objects_filters/purchase_object.md
  _docs/_developer_guide/disclosures.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/read_unread_indicators.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/swift_package_manager.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
  _docs/_developer_guide/platform_integration_guides/ios/news_feed/customizing_the_news_feed.md
  _docs/_developer_guide/platform_integration_guides/macOS.md
  _docs/_developer_guide/platform_integration_guides/macOS/initial_sdk_setup.md
  _docs/_help/dp-technical-assistance.md
  _docs/_help/gdpr_compliance.md
  _docs/_help/home.md
  _docs/_hidden/private_betas/shopify.md
  _docs/_partners/advertising_technologies/attribution/adjust.md
  _docs/_partners/advertising_technologies/attribution/appsflyer.md
  _docs/_partners/advertising_technologies/attribution/branch_for_attribution.md
  _docs/_partners/advertising_technologies/attribution/kochava.md
  _docs/_partners/advertising_technologies/attribution/singular.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_archival.md
  _docs/_user_guide/data_and_analytics/your_reports/report_builder.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/retention_reports.md
  _docs/_user_guide/engagement_tools/canvas/retention_reports.md
  _docs/_user_guide/message_building_by_channel/sms/sms_laws_and_regulations.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/sms_laws_and_regulations.md
  assets/img/attribution/adjust.png
  assets/img/attribution/adjust2.png
  assets/img/attribution/appsflyer.png
  assets/img/attribution/branch.png
  assets/img/attribution/kochava.png
  assets/img/attribution/singular.png
  assets/img/campaign_comparison/create_report.png
  assets/img/campaign_comparison/message_report.png
  assets/img/campaign_comparison/steps_report.png
  assets/img/campaign_comparison/variants_report.png
  assets/img/ios/spm/image6.png
  assets/js/broken_redirect_list.js
Labels: Deploy, cla-signed

#1825 ios 14 data collection
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
Labels: cla-signed

#1832 Shopify Update - Removal of CC Instructions
  _docs/_hidden/private_betas/shopify.md
Labels: cla-signed

#1830 Update Dyspatch Partner Doc and Name
  _docs/_partners/channel_extensions.md
  _docs/_partners/channel_extensions/creative_and_personalization.md
  _docs/_partners/channel_extensions/creative_and_personalization/email_orchestration/dyspatch.md
  _docs/_partners/home.md
  assets/img/dyspatch/dyspatch_admin_dropdown.png
  assets/img/dyspatch/dyspatch_downloading.png
  assets/img/dyspatch/dyspatch_export.gif
  assets/img/dyspatch/dyspatch_integration_create.png
  assets/img/dyspatch/dyspatch_upload.png
Labels: cla-signed

#1833 Minor Edits to Dyspatch Integration Update
  _docs/_partners/channel_extensions/creative_and_personalization/email_orchestration/dyspatch.md
Labels: cla-signed

#1818 Pred Purchases first draft
  _docs/_user_guide/predictive_suite.md
  _docs/_user_guide/predictive_suite/predictive_purchases.md
  _docs/_user_guide/predictive_suite/predictive_purchases/creating_a_purchase_prediction.md
  _docs/_user_guide/predictive_suite/predictive_purchases/messaging_users.md
  _docs/_user_guide/predictive_suite/predictive_purchases/prediction_analytics.md
Labels: cla-signed

#1835 Leftover Deploy - February 11, 2021
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
  _docs/_hidden/private_betas/shopify.md
  _docs/_partners/channel_extensions.md
  _docs/_partners/channel_extensions/creative_and_personalization.md
  _docs/_partners/channel_extensions/creative_and_personalization/email_orchestration/dyspatch.md
  _docs/_partners/home.md
  _docs/_user_guide/predictive_suite.md
  _docs/_user_guide/predictive_suite/predictive_purchases.md
  _docs/_user_guide/predictive_suite/predictive_purchases/creating_a_purchase_prediction.md
  _docs/_user_guide/predictive_suite/predictive_purchases/messaging_users.md
  _docs/_user_guide/predictive_suite/predictive_purchases/prediction_analytics.md
  assets/img/dyspatch/dyspatch_admin_dropdown.png
  assets/img/dyspatch/dyspatch_downloading.png
  assets/img/dyspatch/dyspatch_export.gif
  assets/img/dyspatch/dyspatch_integration_create.png
  assets/img/dyspatch/dyspatch_upload.png
Labels: Deploy, cla-signed

#1836 Update movable_ink.md
  _docs/_partners/channel_extensions/creative_and_personalization/intelligent_content/movable_ink.md
Labels: cla-signed

#1839 Update email_settings.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
Labels: cla-signed

#1838 Update data_points.md
  _docs/_user_guide/onboarding_with_braze/data_points.md
Labels: cla-signed

#1840 correct SMS event name
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#1837 Update email_validation.md
  _docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md
Labels: cla-signed

#1834 SDK-1141 updated firebase manual reg docs
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/troubleshooting.md
Labels: cla-signed

#1831 iOS Push Story SPM Instruction Update
  _docs/_developer_guide/platform_integration_guides/ios/push_story.md
  assets/img_archive/ios_pushstory_10.png
Labels: cla-signed

#1841 Feb Success and Support Handbook
  assets/download_file/Braze_Success_and_Support_Services_Handbook.pdf
Labels: cla-signed

#1842 Deploy - February 16, 2021
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/ios/push_story.md
  _docs/_partners/channel_extensions/creative_and_personalization/intelligent_content/movable_ink.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/onboarding_with_braze/data_points.md
  _docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md
  assets/download_file/Braze_Success_and_Support_Services_Handbook.pdf
  assets/img_archive/ios_pushstory_10.png
Labels: Deploy

#1828 Subscription and Billing Doc - MERGE 2/17
  _docs/_user_guide/onboarding_with_braze/data_points.md
  _docs/_user_guide/onboarding_with_braze/email_setup.md
  _docs/_user_guide/onboarding_with_braze/sms_setup.md
  _docs/_user_guide/onboarding_with_braze/subscription_and_billing.md
  assets/img/subscription_and_billing1.png
  assets/img/subscription_and_billing2.png
  assets/img/subscription_and_billing3.png
  assets/img/subscription_and_billing4.png
Labels: cla-signed

#1845 Subscription and Billing Set to Hidden - Feature not yet ready MERGE 2/18 Please
  _docs/_user_guide/onboarding_with_braze/subscription_and_billing.md
Labels: cla-signed

#1846 Leftover Deploy - February 18, 2021
  _docs/_user_guide/onboarding_with_braze/data_points.md
  _docs/_user_guide/onboarding_with_braze/email_setup.md
  _docs/_user_guide/onboarding_with_braze/sms_setup.md
  _docs/_user_guide/onboarding_with_braze/subscription_and_billing.md
  assets/img/subscription_and_billing1.png
  assets/img/subscription_and_billing2.png
  assets/img/subscription_and_billing3.png
  assets/img/subscription_and_billing4.png
Labels: cla-signed

#1847 Update sdk_primer.md
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
Labels: cla-signed

#1802 ISV Partners
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_partners/isv_partners.md
  _docs/_partners/isv_partners/api_partner.md
  _docs/_partners/isv_partners/cohort_import.md
  _docs/_partners/isv_partners/currents_integration.md
Labels: Braze Partnerships, cla-signed

#1849 BD-834, BD-828, BD-835
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/insights/behavioral_analytics/amplitude_for_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/available_partners.md
  _docs/_user_guide/message_building_by_channel/email/link_templates.md
Labels: cla-signed

#1850 BD-830: Update User Import Screenshot and Repetitive Language
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  assets/img/segment-imported-upsers.png
  assets/img/segment-imported-users.png
Labels: cla-signed

#1844 appboy.xml to braze.xml
  _docs/_api/api_key.md
  _docs/_developer_guide/eu01_us3_sdk_implementation_differences/for_android.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/runtime_configuration.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/read_unread_indicators.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/html_rendered_push.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/android/sample_apps.md
  _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/runtime_configuration.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/fireos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/fireos/news_feed.md
  _docs/_developer_guide/platform_integration_guides/fireos/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/sample_apps.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/unity/android/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/unity/android/sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/xamarin/android_and_fireos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/xamarin/android_and_fireos/push_notifications.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/mobile_integrations.md
  _includes/archive/in_app_message.md
  _includes/archive/session_tracking.md
Labels: cla-signed

#1843 Update SMS Calculator (GE-136)
  _docs/_user_guide/message_building_by_channel/sms/create.md
Labels: cla-signed

#1852 BD-811: Fix Tealium Wording
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
Labels: cla-signed

#1853 Update User Subscription Group Endpoints to include relevant example …
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
Labels: cla-signed

#1851 Post Update User Subscription Endpoint Details Added
  _docs/_api/endpoints/subscription_groups/get_list_user_subscription_groups.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
Labels: cla-signed

#1856 BD-827: Newsfeed Alert
  _docs/_developer_guide/platform_integration_guides/ios/news_feed.md
Labels: cla-signed

#1855 BD-833: remove frequency capping from Beta docs
  _docs/_hidden/private_betas/frequency_capping.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/rate-limiting.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
Labels: cla-signed

#1854 Deploy - February 23, 2021
  _docs/_api/api_key.md
  _docs/_api/endpoints/subscription_groups/get_list_user_subscription_groups.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_developer_guide/eu01_us3_sdk_implementation_differences/for_android.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/runtime_configuration.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/read_unread_indicators.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/html_rendered_push.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/android/sample_apps.md
  _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/runtime_configuration.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/fireos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/fireos/news_feed.md
  _docs/_developer_guide/platform_integration_guides/fireos/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/sample_apps.md
  _docs/_developer_guide/platform_integration_guides/ios/news_feed.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
  _docs/_developer_guide/platform_integration_guides/unity/android/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/unity/android/sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/xamarin/android_and_fireos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/xamarin/android_and_fireos/push_notifications.md
  _docs/_hidden/private_betas/frequency_capping.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
  _docs/_partners/insights/behavioral_analytics/amplitude_for_currents.md
  _docs/_partners/isv_partners.md
  _docs/_partners/isv_partners/api_partner.md
  _docs/_partners/isv_partners/cohort_import.md
  _docs/_partners/isv_partners/currents_integration.md
  _docs/_user_guide/data_and_analytics/braze_currents/available_partners.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/rate-limiting.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/mobile_integrations.md
  _docs/_user_guide/message_building_by_channel/email/link_templates.md
  _docs/_user_guide/message_building_by_channel/sms/create.md
  _includes/archive/in_app_message.md
  _includes/archive/session_tracking.md
  assets/img/segment-imported-upsers.png
  assets/img/segment-imported-users.png
Labels: Deploy, cla-signed

#1857 Update multiple_feeds.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/multiple_feeds.md
Labels: cla-signed

#1780 Survey IAM draft
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
  assets/img/iam/analytics.png
  assets/img/iam/collect-attributes.png
  assets/img/iam/color-theme-picker.png
  assets/img/iam/confirmation-option.png
  assets/img/iam/confirmation-page.png
  assets/img/iam/iam-survey.png
  assets/img/iam/single-multiple-choice.png
  assets/img/iam/survey-message-type.png
Labels: cla-signed

#1860 BD-839: Dashboard Redirect
  assets/js/broken_redirect_list.js
Labels: cla-signed

#1861 Remove bounce code field from Bounce events
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#1863 Updates to IAM Videos
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/implementation_guide.md
Labels: cla-signed

#1862 Remove reference to Mobile Notifications
  _docs/_developer_guide/platform_integration_guides/unity/ios/push_notifications.md
Labels: cla-signed

#1865 Update initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
Labels: cla-signed

#1868 DP removal
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
Labels: cla-signed

#1871 Leftover Deploy - Feb 26, 2021
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/multiple_feeds.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/unity/ios/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
  assets/img/iam/analytics.png
  assets/img/iam/collect-attributes.png
  assets/img/iam/color-theme-picker.png
  assets/img/iam/confirmation-option.png
  assets/img/iam/confirmation-page.png
  assets/img/iam/iam-survey.png
  assets/img/iam/single-multiple-choice.png
  assets/img/iam/survey-message-type.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#1870 Update sdk_min_versions_tag.rb
  _plugins/sdk_min_versions_tag.rb
Labels: cla-signed
