Repository braze-inc/braze-docs, pull requests merged in 2021-07, with the labels that each got.

#2344 Update creating_geofences.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md
Labels: cla-signed

#2345 BD-982: Fixed Personalization Tags for Canvas/Campaigns
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: cla-signed

#2347 Redirects for old Hidden Beta Links
  _docs/_partners/message_personalization/dynamic_content/movable_ink.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#2311 BD-972: Update Modal Pixel Recommendations
  _docs/_help/best_practices/image_and_text_specifications.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/modal.md
  assets/img/modal-spec.png
Labels: cla-signed

#2349 Deploy - July 6, 2021
  _docs/_help/best_practices/image_and_text_specifications.md
  _docs/_partners/message_personalization/dynamic_content/movable_ink.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/modal.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  assets/img/modal-spec.png
  assets/js/broken_redirect_list.js
Labels: Deploy

#2350 Add Braze Bite on Race Conditions
  _docs/_help/best_practices/race_conditions.md
Labels: cla-signed

#2351 Update Android Push Integration Link
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/push_notifications.md
Labels: cla-signed

#2353 Link Fix Pt. 2
  _docs/_help/best_practices/image_and_text_specifications.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  assets/img/modal-spec.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#2357 BD-985: Add simple survey metrics definitions
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
Labels: cla-signed

#2356 BD-984: Clarify future timestamp behavior
  _docs/_api/objects_filters/user_attributes_object.md
Labels: cla-signed

#2352 Fix typo
  _docs/_developer_guide/platform_wide.md
Labels: cla-signed

#2342 CVR Article Improvements - Pt. 1
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
  _docs/_user_guide/message_building_by_channel/email/templates/html_email_template.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
  _docs/_user_guide/message_building_by_channel/email/transactional_message_api_campaign.md
  assets/img_archive/create_link_template.gif
  assets/img_archive/new_campaign_email.png
  assets/img_archive/upload_html_template.gif
Labels: cla-signed

#2359 BD-987: Correcting 'User ID' data point usage
  _docs/_user_guide/onboarding_with_braze/data_points.md
Labels: cla-signed

#2360 Update google_tag_manager.md
  _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
Labels: cla-signed

#2348 CVR Article Improvements - Pt. 2
  _docs/_user_guide/onboarding_with_braze/email_setup/authentication.md
  _docs/_user_guide/onboarding_with_braze/email_setup/consent_and_address_collection.md
  _docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md
  _docs/_user_guide/onboarding_with_braze/email_setup/import_your_email_list.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ip_warming.md
Labels: cla-signed

#2362 Update cookies_and_storage.md
  _docs/_developer_guide/platform_integration_guides/web/cookies_and_storage.md
Labels: cla-signed

#2363 Clarify 'Receive' options in Action-Based Delivery campaigns
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
Labels: cla-signed

#2367 Removing gendered language in email subscription doc
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#2368 BD-983; Clarify SSO support note
  _docs/_user_guide/administrative/access_braze/single_sign_on.md
Labels: cla-signed

#2369 Leftover Deploy - July 8, 2021
  _docs/_api/objects_filters/user_attributes_object.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/web/cookies_and_storage.md
  _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
  _docs/_developer_guide/platform_wide.md
  _docs/_help/best_practices/image_and_text_specifications.md
  _docs/_help/best_practices/race_conditions.md
  _docs/_user_guide/administrative/access_braze/single_sign_on.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
  _docs/_user_guide/message_building_by_channel/email/templates/html_email_template.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
  _docs/_user_guide/message_building_by_channel/email/transactional_message_api_campaign.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
  _docs/_user_guide/onboarding_with_braze/data_points.md
  _docs/_user_guide/onboarding_with_braze/email_setup/authentication.md
  _docs/_user_guide/onboarding_with_braze/email_setup/consent_and_address_collection.md
  _docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md
  _docs/_user_guide/onboarding_with_braze/email_setup/import_your_email_list.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ip_warming.md
  assets/img/modal-spec.png
  assets/img_archive/create_link_template.gif
  assets/img_archive/new_campaign_email.png
  assets/img_archive/upload_html_template.gif
  assets/js/broken_redirect_list.js
Labels: Deploy, cla-signed

#2371 Redirect broken link
  assets/js/broken_redirect_list.js
Labels: cla-signed

#2372 Link Fix - Amperity
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/amperity.md
Labels: cla-signed

#2373 Leftover Deploy - July 9, 2021
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/amperity.md
  assets/js/broken_redirect_list.js
Labels: Deploy, cla-signed

#2370 Update user_import.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Labels: cla-signed

#2375 BD-989: Clarify initial conditions
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/change_your_canvas_after_launch.md
Labels: cla-signed

#2378 Fix typo
  _docs/_user_guide/onboarding_with_braze.md
Labels: cla-signed

#2355 Update link_aliasing.md - MERGE 7/13
  _docs/_hidden/private_betas/link_aliasing.md
Labels: cla-signed

#2377 Update Email/Phone Example Requests with Tabs
  _docs/_api/endpoints/subscription_groups/get_list_user_subscription_group_status.md
  _docs/_api/endpoints/subscription_groups/get_list_user_subscription_groups.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
  assets/css/_tabs.scss
Labels: cla-signed

#2379 Use description for search
  assets/js/algolia_header_search.js
  assets/js/algolia_main_search.js
Labels: cla-signed

#2365 CVR Article Improvements - Pt.3
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/delivery_types/reeligibility.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/advancement.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/branching.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/change_your_canvas_after_launch.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/time_based_canvas.md
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/email/email_reporting.md
  assets/img_archive/Canvas_Branch_1.png
  assets/img_archive/Canvas_Branch_2.png
  assets/img_archive/Canvas_Branch_3.png
  assets/img_archive/Canvas_Branch_4.png
  assets/img_archive/Canvas_Branch_5.png
  assets/img_archive/canvas_add_variant.gif
  assets/img_archive/canvas_branch_1.gif
  assets/img_archive/canvas_branch_2.gif
  assets/img_archive/canvas_branch_3.png
  assets/img_archive/canvas_branch_4.png
  assets/img_archive/canvas_branch_5.png
  assets/img_archive/reeligibility_controls_campaign.png
  assets/img_archive/reeligibility_controls_canvas.png
  assets/img_archive/schedule_delay_after.png
  assets/img_archive/schedule_delay_immediately.png
  assets/img_archive/schedule_delay_in.png
  assets/img_archive/schedule_delay_intelligent.png
  assets/img_archive/schedule_delay_next.png
  assets/img_archive/schedule_frequency_capping.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#2381 Create email_tracking.md
  _docs/_user_guide/data_and_analytics/tracking.md
  _docs/_user_guide/data_and_analytics/tracking/email_tracking.md
  assets/img_archive/open_click_user_profile.png
Labels: cla-signed, release notes

#2382 Update post_users_segment.md
  _docs/_api/endpoints/export/user_data/post_users_segment.md
Labels: cla-signed

#2383 Add info on advantages of using Content Cards
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
Labels: cla-signed

#2385 Update jekyll dependency and algolia config
  Gemfile.lock
  _config.yml
Labels: cla-signed

#2389 Add noindex to templates
  _docs/_home/templates/get_endpoint.md
  _docs/_home/templates/post_endpoint.md
Labels: cla-signed

#2386 BD-991 - Replace semicolon with colon in JSON example
  _docs/_user_guide/data_and_analytics/custom_data/nested_object_support.md
Labels: cla-signed

#2388 Best Practices Rework - Pt.1
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/overview.md
  _docs/_help/best_practices.md
  _docs/_help/best_practices/news_feed.md
  _docs/_hidden/other/client_integration_gallery.md
  _docs/_hidden/other/user_onboarding.md
  _docs/_user_guide/engagement_tools/news_feed/creating_a_news_feed_item.md
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/in-app_messages.md
  _docs/_user_guide/message_building_by_channel/push/about.md
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#2392 Deploy Pt. 2 - July 13, 2021
  _docs/_hidden/private_betas/nested_custom_attribute_support.md
  assets/img_archive/nca_liquid.png
  assets/img_archive/nca_liquid_2.png
  assets/img_archive/nca_segmentation.png
  assets/img_archive/nca_segmentation_2.png
Labels: Deploy, cla-signed

#2393 [NO TICKET] user profile lifecycle minor typo
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
Labels: cla-signed

#2397 BD-992: Update Android Push troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/troubleshooting.md
Labels: cla-signed

#2395 BD-993: Update usage examples
  _docs/_hidden/private_betas/nested_custom_attribute_support.md
Labels: cla-signed

#2390 Update customization.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
Labels: cla-signed

#2364 Update simple_survey.md - MERGE 7/15
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
Labels: cla-signed

#2358 Add Revenue Attribution Metrics - MERGE 7/15
  _docs/_user_guide/data_and_analytics/export_braze_data/exporting_revenue_data.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/data_and_analytics/your_reports/report_builder.md
  assets/img/campaign_comparison/campaign_comparison_columns.png
Labels: cla-signed

#2394 Best Practices Rework - Pt. 2
  _docs/_help/best_practices.md
  _docs/_help/best_practices/email.md
  _docs/_help/best_practices/email/content-specific.md
  _docs/_help/best_practices/email/email_styling_tips.md
  _docs/_help/best_practices/email/overview.md
  _docs/_help/best_practices/email/technical_guidelines_and_tips.md
  _docs/_help/best_practices/email/use_cases.md
  _docs/_help/best_practices/image_and_text_specifications.md
  _docs/_help/best_practices/in-app_messages.md
  _docs/_help/best_practices/in-app_messages/in-app_message_behavior.md
  _docs/_help/best_practices/in-app_messages/in-app_message_specs.md
  _docs/_help/best_practices/in-app_messages/native_apps_only.md
  _docs/_help/best_practices/in-app_messages/overview.md
  _docs/_help/best_practices/in-app_messages/reporting.md
  _docs/_help/best_practices/in-app_messages/universal_apps_and_browsers.md
  _docs/_help/best_practices/in-app_messages/use_cases.md
  _docs/_help/best_practices/in-app_messages/web_browsers_only.md
  _docs/_help/best_practices/push.md
  _docs/_help/best_practices/push/message_format.md
  _docs/_help/best_practices/push/overview.md
  _docs/_help/best_practices/push/push_subscription_status.md
  _docs/_help/best_practices/push/use_cases.md
  _docs/_help/best_practices/web_sdk.md
  _docs/_user_guide/engagement_tools/news_feed/best_practices.md
  _docs/_user_guide/engagement_tools/testing/race_conditions.md
  _docs/_user_guide/message_building_by_channel/email.md
  _docs/_user_guide/message_building_by_channel/email/best_practices.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/email_services.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/guidelines_and_tips.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/managing_email_subscriptions.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/sunset_policies.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/best_practices.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/best_practices/prep_guide.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/best_practices/previous_in-app_message_generations.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  _docs/_user_guide/message_building_by_channel/push/about.md
  _docs/_user_guide/message_building_by_channel/push/best_practices.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/additional_android_best_practices.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/conversion_tracking.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/creating_custom_opt-in_prompts.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/detailed_push_preferences.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/message_format.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/push_reporting.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/sunset_policies.md
  _docs/_user_guide/message_building_by_channel/push/ios.md
  _docs/_user_guide/message_building_by_channel/push/ios/utilizing_badge_count.md
  _docs/_user_guide/message_building_by_channel/sms/mms/create.md
  _docs/_user_guide/onboarding_with_braze/spam_regulations.md
  assets/js/broken_redirect_list.js
Labels: cla-signed, status: in progress

#2399 Update Dimensions in IAM Design Template ZIP File
  _data/alerts.yml
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/implementation_guide.md
  assets/css/_alerts.scss
  assets/download_file/Braze-In-App-Message-Design-Templates.zip
  assets/img/ios_sdk/ios_sdk1.png
  assets/img/ios_sdk/ios_sdk2.png
  assets/img/ios_sdk/ios_sdk3.png
  assets/img/ios_sdk/ios_sdk4.png
  assets/img/message-stop.png
Labels: cla-signed

#2366 CVR Article Improvements - Pt. 4
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/delivery_types.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/delivery_types/api_triggered_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/delivery_types/scheduled_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/delivery_types/triggered_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/time_based_campaign.md
  _docs/_user_guide/onboarding_with_braze/email_setup/deliverability_pitfalls_and_spam_traps.md
  _docs/_user_guide/onboarding_with_braze/email_setup/setting_up_ips_and_domains.md
Labels: cla-signed

#2403 Update User Guide Popular Topics
  _docs/_user_guide/introduction.md
Labels: cla-signed

#2407 BD-994 - Update broken link
  _docs/_developer_guide/platform_integration_guides/ios/analytics/uninstall_tracking.md
Labels: cla-signed

#2354 [SDK-1596] Updated IAM display method on iOS
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md
Labels: cla-signed

#2398 SSL Overview Doc
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl/ssl_clicktracking.md
Labels: cla-signed

#2410 Adding Custom Attribute/Event Dev Guide Links to Data and Analytics Section
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/analytics/logging_custom_events.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/analytics/logging_custom_events.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
Labels: cla-signed

#2412 BD-995: Add comparator call-out to nested_custom_attribute_support.md
  _docs/_hidden/private_betas/nested_custom_attribute_support.md
  assets/img_archive/nca_comparator.png
Labels: cla-signed

#2413 Clarify changing control variant distribution in a Canvas after launch
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/change_your_canvas_after_launch.md
Labels: cla-signed

#2416 BD-997: Update app_id to required field in user track API documentation
  _docs/_api/objects_filters/event_object.md
  _docs/_api/objects_filters/purchase_object.md
Labels: cla-signed

#2414 Update azure_ad.md for style and formatting
  _docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
  assets/img/azure_ad10.png
  assets/img/azure_ad11.png
Labels: cla-signed

#2411 Update link_aliasing.md
  _docs/_hidden/private_betas/link_aliasing.md
  assets/img/link_aliasing_action_based_filters.png
  assets/img/link_aliasing_segmentation_filters.png
Labels: cla-signed

#2376 IAM GET /campaign/details response - MERGE 7/20
  _docs/_api/endpoints/export/campaigns/get_campaign_details.md
Labels: cla-signed

#2417 Replace markdown code elements with HTML in SMS terms glossary
  _docs/_user_guide/onboarding_with_braze/sms_setup/terms.md
Labels: cla-signed

#2420 Updating Census Integration, Linking to Census Docs
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/census.md
Labels: cla-signed

#2422 BD-999: Remove queued responses section from post_user_track.md
  _docs/_api/endpoints/user_data/post_user_track.md
Labels: cla-signed

#2387 [July 21] remove early access for survey
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
Labels: cla-signed

#2424 Deploy Pt. 2 - July 21, 2021
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/census.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
Labels: Deploy, cla-signed

#2404 SDK Data Collection Doc - MERGE 7/22
  _docs/_user_guide/data_and_analytics/user_data_collection/data_collected_by_default.md
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#2425 BD-996: Update Stensul screenshots
  _docs/_partners/message_orchestration/channel_extensions/email_templates/stensul.md
  assets/img_archive/stensul_save_options.png
  assets/img_archive/stensul_upload_options.png
  assets/img_archive/stensul_upload_success.png
Labels: cla-signed

#2426 BD-1000 - Update code snippets to match API tab formatting
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
Labels: cla-signed

#2162 Liquid Use Cases
  _docs/_user_guide/personalization_and_dynamic_content/liquid.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
  _layouts/liquid_use_case_glossary.html
Labels: cla-signed, release notes

#2428 Facebook Audience Export Integration Step Update
  _docs/_partners/message_orchestration/additional_channels/retargeting/facebook.md
  assets/img/fb/afb_1.png
  assets/img/fb/afb_2.png
  assets/img/fb/afb_3.png
  assets/img/fb/afb_4.png
  assets/img/fb/afb_5.png
Labels: cla-signed

#2433 Minor updates Talon.One docs
  _docs/_partners/message_orchestration/channel_extensions/loyalty/talonone.md
  assets/img/talonone_coupon_settings.png
Labels: cla-signed

#2430 BD-1001: Fix API key parameter not displaying in cURL examples
  _docs/_developer_guide/platform_integration_guides/fireos/push_notifications/testing.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/testing.md
Labels: cla-signed

#2431 General article scrubbing
  _docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl/ssl_clicktracking.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/short_and_long_codes.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/sms_laws_and_regulations.md
Labels: cla-signed

#2427 Cohort Import Section - Partner Docs
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/amplitude.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/appsflyer.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/kubit.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/mixpanel.md
Labels: cla-signed

#2435 BD-1003: Kubit Data Import Key Update
  _docs/_partners/data_and_infrastructure_agility/analytics/kubit.md
  assets/img/kubit/kubit.png
Labels: cla-signed

#2434 Leftover Deploy - July 22, 2021
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
  _docs/_developer_guide/platform_integration_guides/fireos/push_notifications/testing.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/testing.md
  _docs/_partners/data_and_infrastructure_agility/analytics/kubit.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/amplitude.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/appsflyer.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/kubit.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/mixpanel.md
  _docs/_partners/message_orchestration/additional_channels/retargeting/facebook.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/stensul.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/talonone.md
  _docs/_user_guide/data_and_analytics/user_data_collection/data_collected_by_default.md
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
  _docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl/ssl_clicktracking.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/short_and_long_codes.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/sms_laws_and_regulations.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
  _layouts/liquid_use_case_glossary.html
  assets/img/fb/afb_1.png
  assets/img/fb/afb_2.png
  assets/img/fb/afb_3.png
  assets/img/fb/afb_4.png
  assets/img/fb/afb_5.png
  assets/img/kubit/kubit.png
  assets/img/talonone_coupon_settings.png
  assets/img_archive/stensul_save_options.png
  assets/img_archive/stensul_upload_options.png
  assets/img_archive/stensul_upload_success.png
  assets/js/broken_redirect_list.js
Labels: Deploy, cla-signed

#2436 BD-1002: Clarify difference between Push Enabled and Push Enabled for App
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#2429 Facebook Audience Sync and Google Audience Sync Doc Update
  _docs/_partners/canvas_steps/facebook_audience_sync.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  assets/img/fb_audience_sync/google_sync7.png
  assets/img/fb_audience_sync/google_sync8.png
  assets/img/fb_audience_sync/google_sync9.png
Labels: cla-signed

#2437 Leftover Deploy Pt. 2- July, 22, 2021
  _docs/_partners/canvas_steps/facebook_audience_sync.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  assets/img/fb_audience_sync/google_sync7.png
  assets/img/fb_audience_sync/google_sync8.png
  assets/img/fb_audience_sync/google_sync9.png
Labels: cla-signed

#2438 BD-1004 - Fix broken link for IAM specs
  assets/js/broken_redirect_list.js
Labels: cla-signed

#2441 [SDK-1353] Android Appboy->Braze doc updates
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/adding_braze_js_interface.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/android_google_tag_manager.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/beacon_integration.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/localization.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/network_offline_mode_integration.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/runtime_configuration.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/social_data_tracking.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_sessions.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/uninstall_tracking.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/optional_gaid_collection.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration/baidu_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration/huawei_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/silent_push_notifications.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/android/sample_apps.md
Labels: cla-signed

#2443 SDK-1365 - added rest api docs for Conversation Push
  _docs/_api/objects_filters/messaging/android_object.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/conversation_push.md
  assets/img/android/push/conversations_android.png
Labels: cla-signed

#2400 Revert "SDK-1610 - updated kotlin android user calls"
  _docs/_developer_guide/platform_integration_guides/android/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/social_data_tracking.md
  _includes/archive/aliasing.md
Labels: cla-signed

#2444 Changing "Timezone" to "Time zone"
  _docs/_api/objects_filters/schedule_object.md
  _docs/_api/objects_filters/user_attributes_object.md
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
  _docs/_developer_guide/platform_integration_guides/web/cookies_and_storage.md
  _docs/_hidden/misc_reference/x-in-y-behavior.md
  _docs/_hidden/private_betas/canvas_in-app_messages.md
  _docs/_hidden/private_betas/link_aliasing.md
  _docs/_partners/message_orchestration/additional_channels/calendar/rokt_calendar.md
  _docs/_user_guide/administrative/company_settings/contact_information.md
  _docs/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/export_braze_data/segment_data_to_csv.md
  _docs/_user_guide/engagement_tools/campaigns/faq.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/change_your_canvas_after_launch.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: cla-signed

#2446 Update 'timezone' to 'time zone'
  _docs/_developer_guide/platform_integration_guides/ios/storage.md
Labels: cla-signed

#2445 updating SMS currents events with new fields
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#2447 Fix iOS link
  _docs/_developer_guide/platform_integration_guides/react_native/ios/sdk_integration.md
Labels: cla-signed

#2451 BD-1006: Add datetime limitation to nested_custom_attribute_support.md
  _docs/_hidden/private_betas/nested_custom_attribute_support.md
Labels: cla-signed

#2440 August 2021 Release Notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2021.md
  _docs/_help/release_notes/2021/august.md
Labels: cla-signed

#2453 Add In-App Messages FAQ
  _docs/_help/faqs.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/faq.md
Labels: cla-signed

#2449 BD-1005: Add X-Braze-Bulk header to /users/track endpoint
  _docs/_api/endpoints/user_data/post_user_track.md
Labels: cla-signed

#2454 BD-1008: Update custom_events.md with nested support for event properties
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
Labels: cla-signed

#2455 Update mParticle Endpoint Description
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle.md
Labels: cla-signed

#2450 Google Audience Sync to GA - MERGE 7/28
  _docs/_partners/canvas_steps/google_audience_sync.md
Labels: cla-signed, release notes

#2456 Deploy Pt.2 - July 28, 2021
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle.md
Labels: Deploy, cla-signed

#2457 BD-1009: Clarify uninstall_tracking.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/uninstall_tracking.md
Labels: cla-signed

#2460 Fixing 404 Broken Links with https://
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/nexla.md
Labels: cla-signed

#2459 BD-1007: Adding Segment Currents Limitation and General Article Cleanup
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  assets/img/segment/segment_currents.png
Labels: cla-signed

#2402 iOS SDK Journey
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/ios_sdk_integration.md
Labels: cla-signed

#2462 Updating Blocklist Behavior
  _docs/_user_guide/administrative/app_settings/manage_app_group/custom_event_and_attribute_management.md
Labels: cla-signed

#2465 Update nested_object_support.md
  _docs/_user_guide/data_and_analytics/custom_data/nested_object_support.md
Labels: cla-signed

#2466 Leftover Deploy - July 29, 2021
  _docs/_developer_guide/platform_integration_guides/ios/analytics/uninstall_tracking.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/ios_sdk_integration.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/nexla.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/custom_event_and_attribute_management.md
  _docs/_user_guide/data_and_analytics/custom_data/nested_object_support.md
  assets/img/segment/segment_currents.png
Labels: Deploy, cla-signed

#2463 Removing duplicate Developer Guide content
  _docs/_developer_guide/platform_integration_guides/android/content_cards/overview.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/fireos/content_cards/overview.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/overview.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/overview.md
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#2467 Pred purchases release
  _docs/_user_guide/predictive_suite.md
  _docs/_user_guide/predictive_suite/predictive_churn.md
  _docs/_user_guide/predictive_suite/predictive_churn/creating_a_churn_prediction.md
  _docs/_user_guide/predictive_suite/predictive_churn/messaging_users.md
  _docs/_user_guide/predictive_suite/predictive_churn/prediction_analytics.md
  _docs/_user_guide/predictive_suite/predictive_purchases.md
  _docs/_user_guide/predictive_suite/predictive_purchases/creating_a_purchase_prediction.md
  _docs/_user_guide/predictive_suite/predictive_purchases/messaging_users.md
  _docs/_user_guide/predictive_suite/predictive_purchases/prediction_analytics.md
  assets/img/purchasePrediction/filters.png
  assets/img/purchasePrediction/purchaseEstimatedResults.png
  assets/img/purchasePrediction/purchaseTargeting.gif
  assets/img/purchasePrediction/purchaseTargeting.png
  assets/img/purchasePrediction/purchasesStep1.png
Labels: cla-signed
