Repository braze-inc/braze-docs, pull requests merged in 2021-08, with the labels that each got.

#2469 Leftover Deploy Pt.2 - August 2, 2021
  _docs/_developer_guide/platform_integration_guides/android/content_cards/overview.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/fireos/content_cards/overview.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/overview.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/overview.md
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
  _docs/_user_guide/predictive_suite.md
  _docs/_user_guide/predictive_suite/predictive_churn.md
  _docs/_user_guide/predictive_suite/predictive_churn/creating_a_churn_prediction.md
  _docs/_user_guide/predictive_suite/predictive_churn/messaging_users.md
  _docs/_user_guide/predictive_suite/predictive_churn/prediction_analytics.md
  _docs/_user_guide/predictive_suite/predictive_purchases.md
  _docs/_user_guide/predictive_suite/predictive_purchases/creating_a_purchase_prediction.md
  _docs/_user_guide/predictive_suite/predictive_purchases/messaging_users.md
  _docs/_user_guide/predictive_suite/predictive_purchases/prediction_analytics.md
  assets/img/purchasePrediction/filters.png
  assets/img/purchasePrediction/purchaseEstimatedResults.png
  assets/img/purchasePrediction/purchaseTargeting.gif
  assets/img/purchasePrediction/purchaseTargeting.png
  assets/img/purchasePrediction/purchasesStep1.png
  assets/js/broken_redirect_list.js
Labels: Deploy, cla-signed

#2470 Reinsert overview image
  _docs/_user_guide/predictive_suite/predictive_purchases.md
  assets/img/purchasePrediction/purchasesOverview.png
Labels: cla-signed

#2468 Update liquid_use_cases.md with 30 for 30 tips
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
Labels: cla-signed

#2276 optilyz Partner Documentation - MERGE 8/3
  .gitignore
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/additional_channels.md
  _docs/_partners/message_orchestration/additional_channels/direct_mail.md
  _docs/_partners/message_orchestration/additional_channels/direct_mail/optilyz.md
  assets/img/optilyz/optilyz_compose.png
  assets/img/optilyz/optilyz_settings.png
  assets/img/optilyz/optilyz_testing.png
Labels: Braze Partnerships, cla-signed, release notes, status: done

#2421 Transcend Partnership Docs - MERGE 8/3
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/data_privacy.md
  _docs/_partners/data_and_infrastructure_agility/data_privacy/transcend.md
  _docs/_partners/home.md
Labels: Braze Partnerships, cla-signed, release notes

#2471 Link Fix
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/overview.md
Labels: cla-signed

#2473 Fix YAML issue
  _docs/_partners/data_and_infrastructure_agility/data_privacy/transcend.md
Labels: cla-signed

#2474 BD-1011: Call out report metrics glossary for Content Cards
  _docs/_user_guide/message_building_by_channel/content_cards/reporting.md
Labels: cla-signed

#2374 Tinyclues Partner Documentation - MERGE 8/3
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/tinyclues.md
  _docs/_partners/home.md
  assets/img/tinyclues/tiny_clues3.png
  assets/img/tinyclues/tiny_clues4.png
  assets/img/tinyclues/tinyclues_1.png
  assets/img/tinyclues/tinyclues_2.png
  assets/img/tinyclues/tinyclues_5.png
  assets/img/tinyclues/tinyclues_6.png
Labels: Braze Partnerships, cla-signed, release notes

#2448 Hightouch Partnership Docs - MERGE 8/3
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/hightouch.md
  _docs/_partners/home.md
  assets/img/hightouch/hightouch_braze_setup.png
  assets/img/hightouch/logo-long.png
  assets/img/hightouch/logo-white.svg
  assets/img/hightouch/logo-with-description.png
  assets/img/hightouch/logo.png
  assets/img/hightouch/logo.svg
  assets/img/hightouch/thumbnail-dark-bg.png
  assets/img/hightouch/thumbnail-white.svg
  assets/img/hightouch/thumbnail.png
  assets/img/hightouch/thumbnail.svg
Labels: Braze Partnerships, cla-signed, release notes

#2475 Minor Liquid docs update and add `assign` Content Block tip
  _docs/_user_guide/personalization_and_dynamic_content/liquid.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md
Labels: cla-signed

#2472 Deploy - August 3, 2021
  .gitignore
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/overview.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/tinyclues.md
  _docs/_partners/data_and_infrastructure_agility/data_privacy.md
  _docs/_partners/data_and_infrastructure_agility/data_privacy/transcend.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/hightouch.md
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/additional_channels.md
  _docs/_partners/message_orchestration/additional_channels/direct_mail.md
  _docs/_partners/message_orchestration/additional_channels/direct_mail/optilyz.md
  _docs/_user_guide/message_building_by_channel/content_cards/reporting.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md
  _docs/_user_guide/predictive_suite/predictive_purchases.md
  assets/img/hightouch/hightouch_braze_setup.png
  assets/img/hightouch/logo-long.png
  assets/img/hightouch/logo-white.svg
  assets/img/hightouch/logo-with-description.png
  assets/img/hightouch/logo.png
  assets/img/hightouch/logo.svg
  assets/img/hightouch/thumbnail-dark-bg.png
  assets/img/hightouch/thumbnail-white.svg
  assets/img/hightouch/thumbnail.png
  assets/img/hightouch/thumbnail.svg
  assets/img/optilyz/optilyz_compose.png
  assets/img/optilyz/optilyz_settings.png
  assets/img/optilyz/optilyz_testing.png
  assets/img/purchasePrediction/purchasesOverview.png
  assets/img/tinyclues/tiny_clues3.png
  assets/img/tinyclues/tiny_clues4.png
  assets/img/tinyclues/tinyclues_1.png
  assets/img/tinyclues/tinyclues_2.png
  assets/img/tinyclues/tinyclues_5.png
  assets/img/tinyclues/tinyclues_6.png
Labels: Deploy, cla-signed

#2476 misprint: "compliment" -> "complement"
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
Labels: cla-signed

#2477 Add tip for optimizing email preview text
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
Labels: cla-signed

#2480 Update to post_send_messages documentation
  _docs/_api/endpoints/messaging/send_messages/post_send_messages.md
Labels: cla-signed

#2482 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla-signed

#2479 BD-1013: Fix Canvas doc inconsistencies
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/change_your_canvas_after_launch.md
Labels: cla-signed

#2481 BD-1012: Remove statement that app_id is optional for email object
  _docs/_api/api_key.md
Labels: cla-signed

#2484 Update issue templates
  .github/ISSUE_TEMPLATE/technical-question---issue---bug.md
Labels: cla-signed

#2485 Update ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: cla-signed

#2486 Adding support callout in TealiumAudience and EventStream Docs
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
Labels: cla-signed

#2488 Update android_11.md
  _docs/_developer_guide/platform_integration_guides/android/android_11.md
Labels: cla-signed

#2490 Leftover Deploy - August 5, 2021
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/technical-question---issue---bug.md
  .github/PULL_REQUEST_TEMPLATE.md
  _docs/_api/api_key.md
  _docs/_api/endpoints/messaging/send_messages/post_send_messages.md
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  _docs/_developer_guide/platform_integration_guides/android/android_11.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/change_your_canvas_after_launch.md
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
Labels: cla-signed, Deploy

#2494 Fix typo in Transcend partner docs
  _docs/_partners/data_and_infrastructure_agility/data_privacy/transcend.md
Labels: cla-signed

#2491 BD-1014: Add warning about potential race conditions during campaign/Canvas creation
  _docs/_help/help_articles/campaigns_and_canvas/not_triggering.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/testing/race_conditions.md
Labels: cla-signed

#2492 BD-1015: Clarify email validation behavior
  _docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md
Labels: cla-signed

#2493 BD-1016 - Clarify local time zone information
  _docs/_user_guide/engagement_tools/campaigns/faq.md
Labels: cla-signed

#2495 [Trivial][No ticket] Remove outdated gcm note
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration/standard_integration.md
Labels: cla-signed

#2496 android/Fix package typo
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration/standard_integration.md
Labels: cla-signed

#2498 Clarify intelligent timing 'edge of window' behavior
  _docs/_user_guide/intelligence/intelligent_timing.md
Labels: cla-signed

#2497 Add additional 30 for 30 tips
  _docs/_user_guide/administrative/app_settings/manage_app_group/custom_event_and_attribute_management.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
Labels: cla-signed

#2499 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla-signed

#2300 iOS 15
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_15.md
Labels: cla-signed

#2502 Update ios_15.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_15.md
Labels: cla-signed

#2501 Deploy - Aug, 9, 2021
  .github/PULL_REQUEST_TEMPLATE.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_14.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_15.md
  _docs/_help/help_articles/campaigns_and_canvas/not_triggering.md
  _docs/_partners/data_and_infrastructure_agility/data_privacy/transcend.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/custom_event_and_attribute_management.md
  _docs/_user_guide/engagement_tools/campaigns/faq.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/testing/race_conditions.md
  _docs/_user_guide/intelligence/intelligent_timing.md
  _docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md
Labels: cla-signed, Deploy

#2504 BD-1020 - Update link
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/delivery_types/scheduled_delivery.md
Labels: cla-signed

#2503 Update ios_15.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_15.md
  assets/img/ios/ios15-notification-settings.png
  assets/img/ios/ios15-notification-summary.png
Labels: cla-signed

#2506 BD-1019: Census Delta Updates
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/census.md
Labels: cla-signed

#2509 Deploy Pt. 2 - Aug, 10, 2021
  _docs/_developer_guide/platform_integration_guides/ios/ios_15.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/census.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/delivery_types/scheduled_delivery.md
  assets/img/ios/ios15-notification-settings.png
  assets/img/ios/ios15-notification-summary.png
Labels: Deploy

#2507 BD-1018: Add note for custom attributes trigger
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/attribute_triggers.md
Labels: cla-signed

#2458 SDK 1764 - Renames for the android-sdk-ui module in documentation for Android
  _config.yml
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/font_customization.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/badges.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/data_models.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/multiple_feeds.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/refreshing_the_feed.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/customization.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/gifs.md
  _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/beacon_integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/font_customization.md
  _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/fireos/content_cards/badges.md
  _docs/_developer_guide/platform_integration_guides/fireos/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/fireos/content_cards/data_models.md
  _docs/_developer_guide/platform_integration_guides/fireos/content_cards/multiple_feeds.md
  _docs/_developer_guide/platform_integration_guides/fireos/content_cards/refreshing_the_feed.md
  _docs/_developer_guide/platform_integration_guides/fireos/customer_feedback.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/fireos/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/news_feed/customization.md
  _docs/_developer_guide/platform_integration_guides/fireos/news_feed/gifs.md
  _docs/_developer_guide/platform_integration_guides/fireos/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/xamarin/android_and_fireos/analytics.md
  _docs/_developer_guide/platform_integration_guides/xamarin/android_and_fireos/initial_sdk_setup.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
  _docs/_help/release_notes/deprecations/apptimize.md
  _docs/_home/styling_test_page.md
  _docs/_partners/data_and_infrastructure_agility/analytics/neura_insights.md
  _docs/_partners/message_orchestration/attribution/adjust.md
  _docs/_partners/message_orchestration/attribution/airbridge.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _docs/_partners/message_orchestration/attribution/branch/branch_for_attribution.md
  _docs/_partners/message_orchestration/attribution/singular.md
  _docs/_partners/message_personalization/location/neura_actions.md
  _includes/archive/aliasing.md
  _includes/archive/android/gifs.md
  _includes/archive/android/in_app_messages/customization.md
  _includes/archive/android/in_app_messages/integration.md
  _includes/archive/android/intial_sdk_setup/android_sdk_integration.md
  _includes/archive/troubleshooting_iams.md
  _incremental_config.yml
  _plugins/jekyll_asset_pipeline.rb
Labels: cla-signed

#2508 Order Completed
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
Labels: cla-signed

#2510 BD-1022: Add Tealium to Currents List
  _docs/_user_guide/data_and_analytics/braze_currents.md
Labels: cla-signed

#2512 BD-1025: Create alert and update API limits for Users by Identifier Endpoint
  _docs/_api/basics.md
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
Labels: cla-signed

#2511 [No Ticket][Trivial] Remove old android push info
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
Labels: cla-signed

#2515 BD-1027: Update SMS Analytics
  _docs/_user_guide/message_building_by_channel/sms/sms_campaign_analytics.md
Labels: cla-signed

#2516 BD-1024: Update Recipients Object Formatting
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_messages.md
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_campaigns.md
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_canvases.md
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
  _docs/_api/objects_filters/recipient_object.md
Labels: cla-signed

#2519 Update ios_15.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_15.md
Labels: cla-signed

#2483 Update React Native Documentation
  _docs/_developer_guide/home.md
  _docs/_developer_guide/platform_integration_guides/react_native/analytics.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/analytics.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/analytics/attribute_tracking.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/analytics/logging_custom_events.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/analytics/revenue_tracking.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/content_cards.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/customer_feedback.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/news_feed.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
  _docs/_developer_guide/platform_integration_guides/react_native/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/analytics.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/analytics/attribute_tracking.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/analytics/logging_custom_events.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/analytics/revenue_tracking.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/content_cards.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/customer_feedback.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/news_feed.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/react_native/test_integration.md
  _docs/_partners/data_and_infrastructure_agility/wrapper_sdks/react_native.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  assets/img/react-native/content-card-test.png
  assets/img/react-native/iam-test.png
  assets/img/react-native/push-notification-test.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#2361 Update Documentation for Nested Event Properties [ING-2385] [ING-2261]
  _docs/_user_guide/data_and_analytics/custom_data/nested_object_support.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
Labels: cla-signed

#2522 BD-1030: Update Silent Remote Notification
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/silent_push_notifications.md
Labels: cla-signed

#2523 Android 12 Upgrade Guide
  _docs/_developer_guide/platform_integration_guides/android/android_12.md
  _includes/archive/android/intial_sdk_setup/android_sdk_integration.md
Labels: cla-signed

#2525 BD-1029: Add a page for Delete Scheduled API-Triggered Canvases endpoint
  _docs/_api/endpoints/messaging.md
  _docs/_api/endpoints/messaging/schedule_messages/post_delete_scheduled_triggered_canvases.md
Labels: cla-signed

#2524 BD-1026: Clarifying Push Primer Deep Link Steps
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/push_primer.md
  _docs/_user_guide/message_building_by_channel/push/ios/create_push_primer.md
Labels: cla-signed

#2517 Fixing broken links in create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
Labels: status: done, cla-signed

#2521 Leftover Deploy - August 8, 2021
  _docs/_api/endpoints/messaging.md
  _docs/_api/endpoints/messaging/schedule_messages/post_delete_scheduled_triggered_canvases.md
  _docs/_developer_guide/home.md
  _docs/_developer_guide/platform_integration_guides/android/android_12.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/push_primer.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/silent_push_notifications.md
  _docs/_developer_guide/platform_integration_guides/react_native/analytics.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/analytics.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/analytics/attribute_tracking.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/analytics/logging_custom_events.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/analytics/revenue_tracking.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/content_cards.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/customer_feedback.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/news_feed.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
  _docs/_developer_guide/platform_integration_guides/react_native/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/analytics.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/analytics/attribute_tracking.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/analytics/logging_custom_events.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/analytics/revenue_tracking.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/content_cards.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/customer_feedback.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/news_feed.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/react_native/test_integration.md
  _docs/_partners/data_and_infrastructure_agility/wrapper_sdks/react_native.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/custom_data/nested_object_support.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/push/ios/create_push_primer.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/10dlc.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/short_and_long_codes.md
  _includes/archive/android/intial_sdk_setup/android_sdk_integration.md
  assets/img/react-native/content-card-test.png
  assets/img/react-native/iam-test.png
  assets/img/react-native/push-notification-test.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#2528 Update Android 12 Upgrade Guide based on PSM testing
  _docs/_developer_guide/platform_integration_guides/android/android_12.md
  _includes/archive/android/intial_sdk_setup/android_sdk_integration.md
Labels: cla-signed

#2529 Update conversion_correlation.md
  _docs/_user_guide/engagement_tools/testing/conversion_correlation.md
Labels: cla-signed

#2531 BD-1032: 2FA Reset
  _docs/_user_guide/administrative/company_settings/security_settings.md
Labels: cla-signed, release notes

#2530 BD-1031: Clarify API Event Object
  _docs/_api/objects_filters/event_object.md
Labels: cla-signed

#2533 BD-1034: Appsflyer Toggle
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
Labels: cla-signed

#2535 Update sdk_authentication.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
  assets/img/sdk-auth-analytics.png
Labels: cla-signed

#2514 list-unsubscribe clarifications - MERGE 8/17
  _docs/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md
Labels: cla-signed

#2538 Dev Guide Broken Links
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/multiple_feeds.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/optional_gaid_collection.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/read_unread_indicators.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/advanced_settings.md
  _docs/_developer_guide/platform_integration_guides/fireos/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/fireos/content_cards/multiple_feeds.md
  _docs/_developer_guide/platform_integration_guides/fireos/news_feed/read_unread_indicators.md
  _docs/_developer_guide/platform_integration_guides/fireos/push_notifications/advanced_settings.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/fine_network_traffic_control.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/ios/news_feed/news_feed_integration_overview.md
  _docs/_user_guide/message_building_by_channel/push/android/advanced_campaign_settings.md
  _includes/archive/android/in_app_messages/customization.md
  _includes/archive/session_tracking.md
Labels: cla-signed

#2500 Updates connected content documentation - MERGE 8/18
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
Labels: cla-signed

#2540 BD-1037: Update Canvas Persistent Entry Properties
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md
Labels: cla-signed

#2547 BD-1039: Clarify Global Control Group audience percentage post-creation
  _docs/_user_guide/engagement_tools/testing/global_control_group.md
Labels: cla-signed

#2546 TVOS Link Fix
  _docs/_developer_guide/platform_wide/tv_and_ott.md
Labels: cla-signed

#2544 Update android_12.md
  _docs/_developer_guide/platform_integration_guides/android/android_12.md
Labels: cla-signed

#2548 Use article_title as HTML title
  _includes/html_include.html
Labels: cla-signed

#2549 BD-1038: Add additional `most_recently_used_device` tags
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: cla-signed

#2550 Fix Liquid use case examples and broken alert
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
Labels: cla-signed

#2551 Remove Prefix from Tab
  _includes/html_include.html
Labels: cla-signed

#2552 Typo Fix
  _docs/_partners/data_and_infrastructure_agility/ab_testing/phrasee.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/stripo.md
Labels: cla-signed

#2553 Fix broken link for Canvas doc
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
Labels: cla-signed

#2555 Update react_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Labels: cla-signed

#2556 BD-1040: Fix typo
  _docs/_user_guide/administrative/app_settings/developer_console/internal_groups_tab.md
Labels: cla-signed

#2558 BD-1043: Move list-unsubscribe content to Email Settings page
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  _docs/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#2559 Update FY22 Success and Support Services Handbook
  _docs/_hidden/other/handbooks.md
  assets/download_file/Braze_Success_and_Support_Services_Handbook_22.pdf
Labels: cla-signed

#2560 Fix typo
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
Labels: cla-signed

#2561 Minor alert edits
  _docs/_developer_guide/platform_integration_guides/fireos/customer_feedback.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/implementation_guide.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
  _docs/_user_guide/message_building_by_channel/sms/user_data_migration.md
Labels: cla-signed

#2557 include inbound media url tag
  _docs/_user_guide/message_building_by_channel/sms/campaign/retargeting.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: cla-signed

#2489 Add User Alias Import GA [MERGE 8/24]
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  assets/download_file/braze-user-import-alias-template-csv.xlsx
  assets/img_archive/user_alias_import_1.png
Labels: cla-signed, release notes

#2534 Action Paths Component Doc EA [MERGE 8/24]
  _docs/_hidden/private_betas/canvas_action_paths.md
  assets/img/canvas_actionpath.png
Labels: cla-signed

#2564 BD-1044: Remove inapplicable News Feed report metrics
  _docs/_user_guide/data_and_analytics/report_metrics.md
Labels: cla-signed

#2539 Update nested_object_support.md
  _docs/_user_guide/data_and_analytics/custom_data/nested_object_support.md
Labels: cla-signed

#2567 BD-1042: Clarify local time zone for Canvas steps
  _docs/_user_guide/engagement_tools/campaigns/faq.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
Labels: cla-signed

#2569 Amperity Redirect
  assets/js/broken_redirect_list.js
Labels: cla-signed

#2570 Add article title to index
  _config.yml
Labels: cla-signed

#2566 Deploy - August 24, 2021
  _config.yml
  _docs/_developer_guide/platform_integration_guides/fireos/customer_feedback.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2021.md
  _docs/_help/release_notes/2021/september.md
  _docs/_hidden/other/handbooks.md
  _docs/_hidden/private_betas/canvas_action_paths.md
  _docs/_user_guide/administrative/app_settings/developer_console/internal_groups_tab.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  _docs/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md
  _docs/_user_guide/data_and_analytics/custom_data/nested_object_support.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/engagement_tools/campaigns/faq.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/retargeting.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
  _docs/_user_guide/message_building_by_channel/sms/user_data_migration.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  assets/download_file/Braze_Success_and_Support_Services_Handbook_22.pdf
  assets/download_file/braze-user-import-alias-template-csv.xlsx
  assets/img/canvas_actionpath.png
  assets/img_archive/user_alias_import_1.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#2573 Removing Beta Note for Talon.one
  _docs/_partners/message_orchestration/channel_extensions/loyalty/talonone.md
Labels: cla-signed

#2572 fix
  _docs/_user_guide/message_building_by_channel/in-app_messages/dark-mode.md
Labels: cla-signed

#2568 [SDK-1683] add ABKContentCardsTableViewControllerDelegate instructions
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization.md
Labels: cla-signed

#2575 Added Redirect for Link Causing Server Error
  assets/js/broken_redirect_list.js
Labels: cla-signed

#2596 Add Custom WebViewActivity instructions
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md
Labels: cla-signed

#2599 typo fix
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/user_profile_fields_connected_content.md
Labels: cla-signed

#2598 BD-1055: Add content cards to key-value pairs page
  _docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
  assets/img_archive/kvp_content_cards.png
Labels: cla-signed

#2600 Typo Fix
  _docs/_api/endpoints/user_data/post_user_delete.md
Labels: cla-signed

#2597 Query Invalid Phone Numbers Endpoint
  _docs/_api/endpoints/email/get_list_hard_bounces.md
  _docs/_api/endpoints/export.md
  _docs/_api/endpoints/export/sms.md
  _docs/_api/endpoints/export/sms/get_query_invalid_numbers.md
Labels: cla-signed

#2601 Deploy - August 31, 2021
  _docs/_api/endpoints/email/get_list_hard_bounces.md
  _docs/_api/endpoints/export.md
  _docs/_api/endpoints/export/sms.md
  _docs/_api/endpoints/export/sms/get_query_invalid_numbers.md
  _docs/_api/endpoints/user_data/post_user_delete.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md
  _docs/_docs_pages/sitemap.xml
  _docs/_user_guide/administrative/company_settings/security_settings.md
  _docs/_user_guide/message_building_by_channel/push/push_registration.md
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
  _docs/_user_guide/message_building_by_channel/sms/sms_subscription_group.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/sms_subscription_groups.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/user_profile_fields_connected_content.md
  _docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
  assets/img/push_changelog.png
  assets/img/push_enablement.png
  assets/img/push_example.png
  assets/img_archive/kvp_content_cards.png
Labels: cla-signed, Deploy

#2595 Apple MPP
  _docs/_user_guide/message_building_by_channel/email/mpp.md
Labels: cla-signed

#2604 Hiding new API Endpoint until release
  _docs/_api/endpoints/export/sms.md
  _docs/_api/endpoints/export/sms/get_query_invalid_numbers.md
Labels: cla-signed
