Repository braze-inc/braze-docs, pull requests merged in 2021-11, with the labels that each got.

#2844 Apply image style guide
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
  _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
  assets/img/dnd_compose_error.png
  assets/img/email_capture.png
  assets/img/email_capture_config.png
  assets/img/global_rules.png
Labels: cla-signed

#2849 Fix header search
  assets/js/algolia_header_search.js
Labels: cla-signed

#2850 Deploy - November 1, 2021
  _docs/_developer_guide/platform_integration_guides/web/amp_support.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
  _docs/_partners/canvas_steps/facebook_audience_sync.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle.md
  _docs/_user_guide/data_and_analytics/custom_data/nested_object_support.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/new_features.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
  _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
  _docs/_user_guide/message_building_by_channel/push.md
  _docs/_user_guide/message_building_by_channel/push/best_practices.md
  _docs/_user_guide/message_building_by_channel/push/push_reporting.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/short_and_long_codes.md
  _docs/_user_guide/message_building_by_channel/sms/sms_campaign_analytics.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  assets/img/canvas_components/components1.png
  assets/img/canvas_components/components2.png
  assets/img/canvas_components/components3.png
  assets/img/dnd_compose_error.png
  assets/img/email_capture.png
  assets/img/email_capture_config.png
  assets/img/global_rules.png
  assets/img/sms/canvas_trigger.png
  assets/img/sms/contact_card1.png
  assets/img/sms/filter1.png
  assets/img/sms/filter2.png
  assets/img/sms/keyword_responses.png
  assets/img/sms/multi-language2.png
  assets/img/sms/retargeting1.png
  assets/img/sms/sms_campaign_details.png
  assets/img/sms/sms_canvas.png
  assets/img/sms/sms_currents.png
  assets/img/sms/sms_historical_performance.png
  assets/img/sms/sms_keywords.png
  assets/img/sms/sms_message_body.png
  assets/img/sms/sms_subgroup_select.png
  assets/js/algolia_header_search.js
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#2657 swapped appcompat for kotlin in unity android
  _docs/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md
Labels: cla-signed

#2853 Remove unnecessary redirect
  _docs/_hidden/redirects/canvas_in-app_messages.md
Labels: cla-signed

#2852 Apply image styling guide
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/implementation_guide.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
  _docs/_user_guide/message_building_by_channel/email/gmail_promotions_tab.md
  assets/img/campaign_details.png
  assets/img/campaign_details_update.png
  assets/img/campaign_export_example.png
  assets/img/campaign_retention3.png
  assets/img/canvas_retention_report.png
  assets/img/canvas_var_analysis.png
  assets/img/convcorr.png
  assets/img/copy-content-block.png
  assets/img/jampp_method.png
  assets/img/jampp_webhook.png
  assets/img/jampp_webhook_template.png
  assets/img/link_aliasing_action_based_filters.png
  assets/img/link_aliasing_segmentation_filters.png
  assets/img/optilyz/optilyz_testing.png
  assets/img/personalized-from-name.png
Labels: cla-signed

#2751 Judo Partnership Docs
  _docs/_hidden/wip_partnerships/partnership_template.md
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content.md
  _docs/_partners/message_personalization/dynamic_content/judo.md
  assets/img/judo/braze-campaign-extras-judo-experience.png
  assets/img/judo/braze-campaign-select-custom-type.png
  assets/img/judo/braze-html-boilerplate.png
Labels: cla-signed, Braze Partnerships

#2754 Line Partnership Docs
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/additional_channels.md
  _docs/_partners/message_orchestration/additional_channels/messaging.md
  _docs/_partners/message_orchestration/additional_channels/messaging/line.md
  assets/img_archive/line_carousel_type.png
  assets/img_archive/line_channel_access_token.png
  assets/img_archive/line_content_block_token.png
  assets/img_archive/line_image_type.png
  assets/img_archive/line_preview.png
  assets/img_archive/line_segment.png
  assets/img_archive/line_sticker_type.png
  assets/img_archive/line_text_type.png
Labels: cla-signed, Braze Partnerships

#2708 BlueConic Partnership Docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/blueconic.md
  _docs/_partners/home.md
  assets/img/blueconic/Braze1.png
  assets/img/blueconic/Braze2.png
  assets/img/blueconic/Braze3.png
  assets/img/blueconic/Braze4.png
  assets/img/blueconic/Braze5.png
  assets/img/blueconic/Braze6.png
  assets/img/blueconic/Braze7.png
Labels: cla-signed, Braze Partnerships

#2821 Worthy Partnership Docs
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content.md
  _docs/_partners/message_personalization/dynamic_content/worthy.md
  assets/img/blueconic/braze1.png
  assets/img/blueconic/braze2.png
  assets/img/blueconic/braze3.png
  assets/img/blueconic/braze4.png
  assets/img/blueconic/braze5.png
  assets/img/blueconic/braze6.png
  assets/img/blueconic/braze7.png
Labels: cla-signed, Braze Partnerships

#2750 RevenueCat Partnership Docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/ab_testing.md
  _docs/_partners/data_and_infrastructure_agility/analytics.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/data_privacy.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses.md
  _docs/_partners/data_and_infrastructure_agility/payments.md
  _docs/_partners/data_and_infrastructure_agility/payments/revenuecat.md
  _docs/_partners/data_and_infrastructure_agility/support.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation.md
  _docs/_partners/data_and_infrastructure_agility/wrapper_sdks.md
  _docs/_partners/home.md
  _docs/_partners/message_orchestration/attribution.md
  _docs/_partners/message_orchestration/channel_extensions.md
  assets/img/revenuecat/braze_settings_in_revenuecat.png
Labels: cla-signed, Braze Partnerships

#2855 Fixed broken hyperlink
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
Labels: cla-signed

#2857 Fixing duplicate alias URLs
  _docs/_api/api_campaigns/api_campaigns.md
  _docs/_partners/isv_partners/api_partner.md
Labels: cla-signed

#2858 BD-1135: Fix broken link
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
Labels: cla-signed

#2861 More detail on spm obj-c flag
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/installation_methods/swift_package_manager.md
Labels: cla-signed

#2860 BD-1137: Fix duplicate report metric
  _docs/_user_guide/data_and_analytics/report_metrics.md
Labels: cla-signed

#2859 Miscellaneous clarifications based on customer feedback
  _docs/_api/endpoints/subscription_groups.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/push_primer.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/app_group_management.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_campaign_results_data.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/message_building_by_channel/email/templates/html_email_template.md
  assets/img_archive/canvas_connection_edit.gif
Labels: cla-signed

#2862 BD-1136: Clarify HTML email template location
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  assets/img/dnd_editor_workflow.png
Labels: cla-signed

#2863 Update filters.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
Labels: cla-signed

#2864 Apply image styling guide
  assets/img/email-relay-whitelabel-address.png
  assets/img/email.png
  assets/img/expires-after.png
  assets/img/in-app-message-campaign-details.png
  assets/img/in-app-message-historical-performance.png
  assets/img/in-app-message-message-performance.png
  assets/img/in-app-message-preview.png
Labels: cla-signed

#2865 BD-1139: Replace incorrect example screenshot
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  assets/img_archive/custom_footer_save_changes.png
Labels: cla-signed

#2866 BD-1138: Add iOS-specific caveat for testing Content Cards
  _docs/_user_guide/message_building_by_channel/content_cards/testing.md
Labels: cla-signed

#2867 Moving API Campaigns content from child page to landing page
  _docs/_api/api_campaigns.md
  _docs/_api/api_campaigns/api_campaigns.md
Labels: cla-signed

#2868 Update ip_warming.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ip_warming.md
Labels: cla-signed

#2869 Update api_key.md
  _docs/_api/api_key.md
Labels: cla-signed

#2872 Various edits based on customer and internal feedback
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_archival.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
  _docs/_user_guide/engagement_tools/segments/using_user_search.md
Labels: cla-signed

#2875 Leftover Deploy - November 4, 2021
  _docs/_api/api_campaigns.md
  _docs/_api/api_campaigns/api_campaigns.md
  _docs/_api/api_key.md
  _docs/_api/endpoints/subscription_groups.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/installation_methods/swift_package_manager.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/push_primer.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/app_group_management.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_campaign_results_data.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_archival.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/segments/using_user_search.md
  _docs/_user_guide/message_building_by_channel/content_cards/testing.md
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/email/templates/html_email_template.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ip_warming.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
  assets/img/dnd_editor_workflow.png
  assets/img/email-relay-whitelabel-address.png
  assets/img/email.png
  assets/img/expires-after.png
  assets/img/in-app-message-campaign-details.png
  assets/img/in-app-message-historical-performance.png
  assets/img/in-app-message-message-performance.png
  assets/img/in-app-message-preview.png
  assets/img_archive/canvas_connection_edit.gif
  assets/img_archive/custom_footer_save_changes.png
Labels: cla-signed, Deploy

#2873 Email Global Style Settings EA
  _docs/_hidden/private_betas/dnd_email_style_settings.md
  assets/img_archive/dnd_basic_styling.png
  assets/img_archive/dnd_button_styling.png
  assets/img_archive/dnd_custom_font.png
  assets/img_archive/dnd_default_override.png
  assets/img_archive/dnd_global_style_settings.png
  assets/img_archive/dnd_heading_styling.png
  assets/img_archive/dnd_text_styling.png
Labels: cla-signed

#2877 BD-1141: Change campaign_id to optional in create scheduled messages endpoint
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_messages.md
Labels: cla-signed

#2878 Fix link on Partners page
  _docs/_partners/home.md
Labels: cla-signed

#2879 Leftover Deploy Pt. 2 - November 5, 2021
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_messages.md
  _docs/_hidden/private_betas/dnd_email_style_settings.md
  _docs/_partners/home.md
  assets/img_archive/dnd_basic_styling.png
  assets/img_archive/dnd_button_styling.png
  assets/img_archive/dnd_custom_font.png
  assets/img_archive/dnd_default_override.png
  assets/img_archive/dnd_global_style_settings.png
  assets/img_archive/dnd_heading_styling.png
  assets/img_archive/dnd_text_styling.png
Labels: cla-signed, Deploy

#2880 Fix link
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content.md
Labels: cla-signed

#2881 Minor doc edits
  _docs/_hidden/other/tour.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/scheduled_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/archiving_campaigns.md
Labels: cla-signed

#2882 Fix typo "Cconfigure" -> "configure"
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
Labels: cla-signed

#2884 BD-1143: Update list of IPs that customers need to whitelist in EU for connected content
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
Labels: cla-signed

#2886 Clean up landing pages
  _docs/_user_guide/administrative.md
  _docs/_user_guide/data_and_analytics.md
  _docs/_user_guide/engagement_tools.md
  _docs/_user_guide/intelligence.md
  _docs/_user_guide/introduction.md
  _docs/_user_guide/message_building_by_channel.md
  _docs/_user_guide/onboarding_with_braze.md
  _docs/_user_guide/personalization_and_dynamic_content.md
  _docs/_user_guide/predictive_suite.md
Labels: cla-signed

#2893 Update preview.md
  _docs/_developer_guide/platform_integration_guides/flutter/preview.md
Labels: cla-signed

#2888 BD-1145: Add more testing information for Content Cards
  _docs/_user_guide/message_building_by_channel/content_cards/testing.md
  assets/img_archive/cc_debug.png
Labels: cla-signed

#2851 sdk auth [ merge November 8 ]
  _docs/_developer_guide/platform_wide/sdk_authentication.md
Labels: cla-signed

#2889 Documenting merge behavior on /users/identify/ endpoint - hidden page
  _docs/_api/endpoints/templates/email_templates/post_update_email_template.md
  _docs/_hidden/private_betas/post_user_identify_merge_behavior.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
Labels: cla-signed

#2891 Apply image styling guide to img folder
  assets/img/campaign_comparison/campaign_comparison1.png
  assets/img/campaign_comparison/campaign_comparison3.png
  assets/img/campaign_comparison/create_report.png
  assets/img/campaign_comparison/download.png
  assets/img/csv-errors.png
  assets/img/currents-role-arn.png
  assets/img/currents-s3-example.png
  assets/img/custom-attributes-looker.png
  assets/img/funnel_report/funnel_report5.png
  assets/img/phrasee/11_push_messagebody.png
  assets/img/phrasee/4_braze_emailtag.png
  assets/img/phrasee/5_copy_variant_braze.png
  assets/img/phrasee/6_braze_schedule.png
  assets/img/phrasee/7_braze_send_winner.png
  assets/img/phrasee/9_braze_push_tag.png
Labels: cla-signed

#2895 BD-1146: Fix typos and minor formatting changes
  _docs/_user_guide/message_building_by_channel/email/email_private_relay_apple_SSO.md
Labels: cla-signed

#2896 BD-1147: Add Content Cards to list of supported messaging channels for content test groups
  _docs/_user_guide/administrative/app_settings/developer_console/internal_groups_tab.md
Labels: cla-signed

#2897 Update permissions definitions to show requirements for launching existing content blocks
  _docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#2885 Miscellaneous edits based on customer and internal feedback pt. 2
  _docs/_api/basics.md
  _docs/_user_guide/administrative/app_settings/developer_console/api_settings_tab.md
  _docs/_user_guide/administrative/app_settings/developer_console/event_user_log_tab.md
  _docs/_user_guide/administrative/app_settings/developer_console/internal_groups_tab.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/testing.md
  assets/img_archive/api-key-ip-whitelisting.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#2901 BD-1151: Remove references to testing IAM with cURL
  _docs/_developer_guide/platform_wide/sending_test_messages.md
Labels: cla-signed

#2900 BD-1142: Clarify API-triggered vs. API campaign
  _docs/_api/api_campaigns.md
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
Labels: cla-signed

#2898 [SDK-2080] Manual Dynamic XCFramework Integration docs update
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/completing_integration.md
Labels: cla-signed

#2904 BD-1152: Clarify `dispatch_id` inclusion in Currents events
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#2903 Apply image styling guide
  _docs/_partners/message_orchestration/channel_extensions/loyalty/voucherify.md
  assets/img/promocodes/promocode1.png
  assets/img/promocodes/promocode11.png
  assets/img/promocodes/promocode12.png
  assets/img/promocodes/promocode5.png
  assets/img/promocodes/promocode8.png
  assets/img/tealium/braze_connection.png
  assets/img/voucherify-cc-campaignId.png
  assets/img/voucherify-cc-code-published.png
  assets/img/voucherify-cc-preview.png
  assets/img/voucherify-custom-attribute-in-email.png
  assets/img/voucherify-custom-attributes-mapping.png
  assets/img/voucherify-email-preview-custom-attribute.png
  assets/img/voucherify-export-Codes.png
  assets/img/voucherify-import-codes-braze.png
  assets/img/voucherify-integrations-hub.png
  assets/img/voucherify-promotion-list-copy-snippet.png
  assets/img/voucherify-promotion-list-snippet-email.png
Labels: cla-signed

#2899 BD-1150: Update Catalogs with templating support
  _docs/_hidden/private_betas/catalog.md
Labels: cla-signed

#2908 BD-1154: Clarify HTML Preference Center snippet
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#2909 Update read_unread_indicators.md android docs
  _docs/_developer_guide/platform_integration_guides/android/content_cards/read_unread_indicators.md
Labels: cla-signed

#2912 Image Fix
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  assets/img/open_pixel.png
Labels: cla-signed

#2883 Update data_points.md
  _docs/_user_guide/onboarding_with_braze/data_points.md
Labels: cla-signed

#2906 Apply image style guide edits
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/html_rendered_push.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
  _docs/_help/help_articles/docs/scroll_bar_overlap.md
  _docs/_partners/message_personalization/location/neura_actions.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/set_up.md
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
  _docs/_user_guide/message_building_by_channel/push/ios/notification_options.md
  assets/img/moments-of-availability.png
  assets/img/nested_object1.png
  assets/img/nested_object2.png
  assets/img/neura-braze-api-key.png
  assets/img/new_current.png
  assets/img/portal.png
  assets/img/primary-secondary-buttons.png
  assets/img/profile-push-prov-auth.png
  assets/img/purchase3.png
  assets/img/purchase4.jpg
  assets/img/purchase4.png
  assets/img/quiet_hours.png
  assets/img/range_retention.png
  assets/img/remember_me.png
  assets/img/retention_1.png
  assets/img/retention_2.png
  assets/img/retention_report_full_report.png
  assets/img/s3_tech_partners.png
  assets/img/sdk-auth-analytics.png
  assets/img/sdk-auth-settings.png
  assets/img/sso1.png
  assets/img/sso2.png
  assets/img/sso3.png
Labels: cla-signed

#2913 BD-1099: In-Browser Message
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/faq.md
Labels: cla-signed

#2915 Fix missing bracket
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
Labels: cla-signed

#2892 Apply image styling guide
  _docs/_user_guide/engagement_tools/canvas/canvas_components/decision_split.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
  _docs/_user_guide/message_building_by_channel/push/ios/create_push_primer.md
  assets/img/data-export-role-arn.png
  assets/img/date_select_retention.png
  assets/img/decision-step-analytics-4.png
  assets/img/experiment_step/exp_settings.png
  assets/img/experiment_step/experiment_step.png
  assets/img/push_primer/push_primer_2.jpg
  assets/img/push_primer/push_primer_2.png
  assets/img/push_primer/push_primer_7.jpg
  assets/img/push_primer/push_primer_7.png
Labels: cla-signed

#2916 BD-1115: Post User Segment Export Options
  _docs/_api/endpoints/export/user_data/post_users_segment.md
Labels: cla-signed

#2914 BD-1153: Update Delay Step and Message Step docs
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
  assets/img/canvas_components/components2.png
  assets/img/canvas_components/message_step1.png
  assets/img/canvas_components/message_step2.png
  assets/img/canvas_components/message_step3.png
  assets/img/canvas_components/message_step4.png
  assets/img/canvas_delay.gif
  assets/img/canvas_delay.png
Labels: cla-signed

#2917 BD-1155: Clarify Transactional Email feature
  _docs/_api/api_campaigns/transactional_api_campaign.md
  _docs/_user_guide/message_building_by_channel/email/transactional_message_api_campaign.md
Labels: cla-signed

#2890 Zeotap Partner Documentation - Merge 11/18
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/zeotap.md
  _docs/_partners/home.md
  assets/img/zeotap/zeotap1.png
  assets/img/zeotap/zeotap2.png
  assets/img/zeotap/zeotap3.png
  assets/img/zeotap/zeotap4.png
  assets/js/broken_redirect_list.js
Labels: status: in progress, cla-signed, Braze Partnerships

#2907 Update campaign analytics articles for each messaging channel
  _docs/_user_guide/data_and_analytics/your_reports.md
  _docs/_user_guide/data_and_analytics/your_reports/campaign_analytics.md
  _docs/_user_guide/data_and_analytics/your_reports/reports_overview.md
  _docs/_user_guide/message_building_by_channel/content_cards/reporting.md
  _docs/_user_guide/message_building_by_channel/email/reporting_and_analytics/email_reporting.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/reporting.md
  _docs/_user_guide/message_building_by_channel/push/push_reporting.md
  _docs/_user_guide/message_building_by_channel/sms/sms_campaign_analytics.md
  _includes/campaign_analytics.md
  assets/img/cc-campaign-details.png
  assets/img/in-app_message_canvas_reporting.png
Labels: cla-signed

#2920 [CH-3694] Remove references to other IAM "type"s besides survey
  _docs/_api/endpoints/export/campaigns/get_campaign_details.md
Labels: cla-signed

#2921 Add tagging use cases
  _docs/_user_guide/administrative/app_settings/manage_app_group/tags.md
Labels: cla-signed

#2919 Apply image styling guide
  _docs/_partners/canvas_steps/facebook_audience_sync.md
  assets/img/fb_audience_sync/google_sync10.png
  assets/img/ios/interruption-level.png
  assets/img/ios/relevance-score.png
  assets/img/regex/regeximg1.png
  assets/img/regex/regeximg2.png
  assets/img/regex/regeximg3.png
Labels: cla-signed

#2923 December 2021 Release Notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2021.md
  _docs/_help/release_notes/2021/december.md
Labels: cla-signed

#2922 Leftover Deploy - November 18, 2021
  _docs/_api/endpoints/export/campaigns/get_campaign_details.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2021.md
  _docs/_help/release_notes/2021/december.md
  _docs/_partners/canvas_steps/facebook_audience_sync.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/zeotap.md
  _docs/_partners/home.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/tags.md
  _docs/_user_guide/data_and_analytics/your_reports.md
  _docs/_user_guide/data_and_analytics/your_reports/campaign_analytics.md
  _docs/_user_guide/data_and_analytics/your_reports/reports_overview.md
  _docs/_user_guide/message_building_by_channel/content_cards/reporting.md
  _docs/_user_guide/message_building_by_channel/email/reporting_and_analytics/email_reporting.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/reporting.md
  _docs/_user_guide/message_building_by_channel/push/push_reporting.md
  _docs/_user_guide/message_building_by_channel/sms/sms_campaign_analytics.md
  _includes/campaign_analytics.md
  assets/img/cc-campaign-details.png
  assets/img/fb_audience_sync/google_sync10.png
  assets/img/in-app_message_canvas_reporting.png
  assets/img/ios/interruption-level.png
  assets/img/ios/relevance-score.png
  assets/img/regex/regeximg1.png
  assets/img/regex/regeximg2.png
  assets/img/regex/regeximg3.png
  assets/img/zeotap/zeotap1.png
  assets/img/zeotap/zeotap2.png
  assets/img/zeotap/zeotap3.png
  assets/img/zeotap/zeotap4.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#2924 Update making_an_api_call.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
Labels: cla-signed

#2910 Details style update
  _plugins/details_tag.rb
  assets/css/_content.scss
  assets/css/main.scss
Labels: cla-signed

#2925 Add alert for User Import doc
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Labels: cla-signed

#2927 Leftover Deploy Pt.2 - November 19, 2021
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
  _plugins/details_tag.rb
  assets/css/_content.scss
  assets/css/main.scss
Labels: cla-signed, Deploy

#2926 Add additional details to Global Control Group and minor reformatting
  _docs/_user_guide/engagement_tools/testing/global_control_group.md
Labels: status: in progress, cla-signed

#2928 Fix liquid syntax error
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
Labels: cla-signed

#2929 Add Testing Canvases section to match campaigns
  _docs/_user_guide/engagement_tools/campaigns.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/campaign_analytics.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/campaign_funnel_report.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/retention_reports.md
  _docs/_user_guide/engagement_tools/canvas.md
  _docs/_user_guide/engagement_tools/canvas/get_started.md
  _docs/_user_guide/engagement_tools/canvas/testing_canvases.md
  _docs/_user_guide/engagement_tools/canvas/testing_canvases/canvas_funnel_reports.md
  _docs/_user_guide/engagement_tools/canvas/testing_canvases/measuring_and_testing_with_canvas_analytics.md
  _docs/_user_guide/engagement_tools/canvas/testing_canvases/retention_reports.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#2930 Image edits for style
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/use_cases.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
  assets/img/Shopify/shopify_integration10.png
  assets/img/Shopify/shopify_integration11.png
  assets/img/Shopify/shopify_integration15.png
  assets/img/Shopify/shopify_integration16.png
  assets/img/Shopify/shopify_integration17.png
  assets/img/Shopify/shopify_integration2.png
  assets/img/Shopify/shopify_integration3-6.gif
  assets/img/Shopify/shopify_integration3-6.png
  assets/img/Shopify/shopify_integration8.png
  assets/img/Shopify/shopify_integration9.png
  assets/img/email_templates/template2.png
  assets/img/email_templates/template3.jpg
  assets/img/email_templates/template3.png
  assets/img/email_templates/template4.jpg
  assets/img/email_templates/template4.png
  assets/img/email_templates/template5.jpg
  assets/img/email_templates/template5.png
  assets/img/segment/property1.png
  assets/img/segment/property2.png
  assets/img/segment/property3.png
  assets/img/segment/property4.png
  assets/img/segment/segment_extension1.png
  assets/img/segment/segment_extension2.png
  assets/img/segment/segment_extension3.png
  assets/img/segment/segment_extension6.png
  assets/img/segment/segment_extension7.png
  assets/img/segment/segment_extension8.png
Labels: cla-signed

#2932 Edits based on customer/internal feedback
  _docs/_user_guide/data_and_analytics/your_reports/funnel_reports.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing.md
Labels: cla-signed

#2905 Add a new page to Amazon Personalize
  _docs/_partners/message_personalization/dynamic_content/amazon_personalize.md
  _docs/_partners/message_personalization/dynamic_content/amazon_personalize/amazon_personalize.md
  _docs/_partners/message_personalization/dynamic_content/amazon_personalize/workshop.md
  assets/img/amazon_personalize/content-card-campaign.png
  assets/img/amazon_personalize/min_and_max_user_percentile.png
Labels: cla-signed

#2933 BD-1158: Updating Total Clicks definition
  _docs/_user_guide/data_and_analytics/report_metrics.md
Labels: cla-signed

#2911 Remove YUI compressor, Java dependency and upgrade ruby ver
  .ruby-version
  Gemfile
  Gemfile.lock
  _plugins/alloy_partner.rb
  _plugins/jekyll_asset_pipeline.rb
  app.json
Labels: status: on hold / do not merge, cla-signed, In Review

#2934 Remove minima
  Gemfile
  Gemfile.lock
Labels: cla-signed

#2936 BD-1157: Clarify expected behavior in persistent entry properties
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md
Labels: cla-signed

#2935 Fix capitalization for YouTube
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
  _docs/_partners/message_personalization/dynamic_content/playable.md
  _includes/archive/android/universal_deep_link_delegate.md
Labels: cla-signed

#2938 Update 404 page
  _docs/_docs_pages/404.md
  _layouts/broken_page.html
  assets/css/_404.scss
  assets/img/404.png
  assets/img/docs_404.png
  assets/img/error.gif
Labels: cla-signed

#2942 Bluedot, AccuWeather, and Census partner cleanup
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/census.md
  _docs/_partners/message_personalization/location/accuweather.md
  _docs/_partners/message_personalization/location/bluedot.md
  assets/img_archive/connected_weather_push2.png
Labels: cla-signed

#2940 Image edits
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/ios_sdk_integration.md
  _docs/_user_guide/engagement_tools/testing/global_control_group.md
  _docs/_user_guide/predictive_suite/predictive_purchases/creating_a_purchase_prediction.md
  assets/img/control_group/control_group2.png
  assets/img/control_group/control_group4.png
  assets/img/control_group/control_group5.png
  assets/img/ios_sdk/ios_sdk2.png
  assets/img/purchasePrediction/purchasesStep1.png
  assets/img/purchasePrediction/purchases_step1.png
Labels: cla-signed

#2939 Improvements to IAM docs based on customer/internal feedback
  _docs/_user_guide/message_building_by_channel/in-app_messages/best_practices/prep_guide.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/best_practices/previous_in-app_message_generations.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
  _includes/archive/appboyBridge.md
Labels: cla-signed

#2943 Leftover Deploy - November 24, 2021
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/ios_sdk_integration.md
  _docs/_docs_pages/404.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/census.md
  _docs/_partners/message_personalization/location/accuweather.md
  _docs/_partners/message_personalization/location/bluedot.md
  _docs/_user_guide/engagement_tools/testing/global_control_group.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/best_practices/prep_guide.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/best_practices/previous_in-app_message_generations.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
  _docs/_user_guide/predictive_suite/predictive_purchases/creating_a_purchase_prediction.md
  _includes/archive/appboyBridge.md
  _layouts/broken_page.html
  assets/css/_404.scss
  assets/img/404.png
  assets/img/control_group/control_group2.png
  assets/img/control_group/control_group4.png
  assets/img/control_group/control_group5.png
  assets/img/docs_404.png
  assets/img/error.gif
  assets/img/ios_sdk/ios_sdk2.png
  assets/img/purchasePrediction/purchasesStep1.png
  assets/img/purchasePrediction/purchases_step1.png
  assets/img_archive/connected_weather_push2.png
Labels: Deploy

#2944 Apply image styling guide
  _docs/_developer_guide/platform_integration_guides/unreal_engine/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/tinyclues.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/treasure_data.md
  assets/img/tinyclues/tiny_clues3.png
  assets/img/tinyclues/tiny_clues4.png
  assets/img/tinyclues/tinyclues_3.png
  assets/img/tinyclues/tinyclues_4.png
  assets/img/tinyclues/tinyclues_5.png
  assets/img/tinyclues/tinyclues_6.png
Labels: cla-signed

#2945 Update message_step.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
Labels: cla-signed

#2946 Update custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
Labels: cla-signed

#2941 Update post_users_segment.md [MERGE 11/30]
  _docs/_api/endpoints/export/user_data/post_users_segment.md
Labels: cla-signed

#2813 Update report_builder.md [MERGE 11/30]
  _docs/_user_guide/data_and_analytics/your_reports/report_builder.md
Labels: cla-signed

#2948 Update Email Reporting with new analytics fields
  _docs/_user_guide/message_building_by_channel/email/reporting_and_analytics/analytics_glossary.md
  _includes/campaign_analytics.md
Labels: cla-signed

#2952 BD-1164: Typo Fix
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/archiving_campaigns.md
Labels: cla-signed

#2953 BD-1165: Company Wide Setting Removed
  _docs/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md
Labels: cla-signed

#2954 BD-1074: CC Retry Logic
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
Labels: cla-signed

#2950 BD-1163: Update catalogs beta with filtered sets use case
  _docs/_hidden/private_betas/catalog.md
  assets/img_archive/catalog_filtered_csv.png
  assets/img_archive/catalog_filtered_example.png
Labels: cla-signed

#2955 BD-1045: Content Card Custom Reporting Warning
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
  _includes/campaign_analytics.md
Labels: cla-signed

#2956 BD-1046: Add Method Links for SMS Subscription Group Setting
  _docs/_user_guide/message_building_by_channel/sms/sms_subscription_group.md
Labels: cla-signed

#2949 Apply image styling guide
  _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
  _docs/_partners/data_and_infrastructure_agility/analytics/kubit.md
  assets/img/churn/churn1.png
  assets/img/churn/churn2.png
  assets/img/kubit/kubit.png
  assets/img/web-gtm/gtm-actions-tag.png
  assets/img/web-gtm/gtm-change-user.png
  assets/img/web-gtm/gtm-custom-event.png
  assets/img/web-gtm/gtm-debug-mode.png
  assets/img/web-gtm/gtm-initialization-tag.png
  assets/img/web-gtm/gtm-purchase.png
Labels: cla-signed

#2958 IAM doc enhancements Pt.2
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  assets/img_archive/iam_intrusive.png
Labels: cla-signed
