Repository braze-inc/braze-docs, pull requests merged in 2021-01, with the labels that each got.

#1731 BD-771, BD-772, BD-773, BD-774
  _docs/_partners/insights/business_intelligence/looker.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#1734 BD-777: Documenting Matches_regex caveat
  _docs/_api/objects_filters/connected_audience.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
Labels: cla-signed

#1735 BD-776: Seed Group Behavior
  _docs/_user_guide/administrative/app_settings/developer_console/internal_groups_tab.md
Labels: cla-signed

#1738 BD-779, BD-780
  _docs/_partners/data_augmentation/contextual_location/bluedot.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#1655 Rip and Replace Guide
  _docs/_hidden/other/airship_migration.md
  assets/img/csv_filter.png
Labels: cla-signed

#1740 update high volume sending page
  _docs/_user_guide/message_building_by_channel/sms/keywords/high_volume_sending.md
Labels: cla-signed

#1743 Rename "Last Recieved Any Campaign" to "Last Recieved Any Message"
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_help/faqs.md
  _docs/_home/static_video.md
  _docs/_user_guide/data_and_analytics/user_data_collection/data_collected_by_default.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/rate-limiting.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#1749 Update nokogiri version
  Gemfile
  Gemfile.lock
Labels: cla-signed

#1747 remove beta reference in SMS Docs
  _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
Labels: cla-signed

#1750 move content card removal to its own section
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
Labels: cla-signed

#1742 sms inbound message liquid tag - MERGE ON 1/12
  _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  assets/img/keyword_example1.jpg
  assets/img/keyword_example2.jpg
Labels: cla-signed

#1754 Fix keycdn anchor
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl_clicktracking.md
Labels: cla-signed

#1752 BD-785, BD-784, BD-783
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_partners/advertising_technologies/attribution/adjust.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: cla-signed

#1756 mo/typos
  _docs/_api/objects_filters/connected_audience.md
  _docs/_api/objects_filters/email_object.md
  _docs/_user_guide/administrative/access_braze/getting_your_account.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
  _docs/_user_guide/data_and_analytics/creating_a_formula.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/change_your_canvas_after_launch.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/message_building_by_channel/content_cards/migrating_from_news_feed.md
  _docs/_user_guide/message_building_by_channel/email/analytics_glossary.md
  _docs/_user_guide/message_building_by_channel/push/ios/create_push_primer.md
  _docs/_user_guide/message_building_by_channel/sms/about_sms.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/custom_keyword_handling.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
  _docs/_user_guide/message_building_by_channel/sms/mms/mms_short_long_codes.md
  _docs/_user_guide/message_building_by_channel/sms/sms_campaign_analytics.md
  _docs/_user_guide/message_building_by_channel/sms/user_data_migration.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ip_warming.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/short_and_long_codes.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/sms_sending.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/user_data_migration.md
  _docs/_user_guide/personalization_and_dynamic_content/emoji_messaging.md
  _docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
  _docs/_user_guide/predictive_suite/predictive_churn/prediction_analytics/prediction_quality.md
Labels: cla-signed

#1755 Deploy - January 12, 2021
  Gemfile
  Gemfile.lock
  _docs/_api/objects_filters/connected_audience.md
  _docs/_api/objects_filters/email_object.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_partners/advertising_technologies/attribution/adjust.md
  _docs/_user_guide/administrative/access_braze/getting_your_account.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
  _docs/_user_guide/data_and_analytics/creating_a_formula.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/change_your_canvas_after_launch.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/content_cards/migrating_from_news_feed.md
  _docs/_user_guide/message_building_by_channel/email/analytics_glossary.md
  _docs/_user_guide/message_building_by_channel/push/ios/create_push_primer.md
  _docs/_user_guide/message_building_by_channel/sms/about_sms.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/custom_keyword_handling.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
  _docs/_user_guide/message_building_by_channel/sms/mms/mms_short_long_codes.md
  _docs/_user_guide/message_building_by_channel/sms/sms_campaign_analytics.md
  _docs/_user_guide/message_building_by_channel/sms/user_data_migration.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ip_warming.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl_clicktracking.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/short_and_long_codes.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/sms_sending.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/user_data_migration.md
  _docs/_user_guide/personalization_and_dynamic_content/emoji_messaging.md
  _docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  _docs/_user_guide/predictive_suite/predictive_churn/prediction_analytics/prediction_quality.md
  assets/img/keyword_example1.jpg
  assets/img/keyword_example2.jpg
Labels: Deploy, cla-signed

#1757 Connected Content and Liquid Capitalization
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  _docs/_api/endpoints/templates/content_blocks_templates/post_create_email_content_block.md
  _docs/_api/endpoints/templates/content_blocks_templates/post_update_content_block.md
  _docs/_api/transactional_message_api_campaign.md
  _docs/_hidden/private_betas/shopify.md
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
  _docs/_hidden/wip_partnerships/partnership_template.md
  _docs/_home/styling_test_page.md
  _docs/_home/templates/partner_page_template.md
  _docs/_home/templates/partner_page_template_video.md
  _docs/_partners/additional_channels/direct_mail/inkit.md
  _docs/_partners/additional_channels/mobile_wallet/passkit.md
  _docs/_partners/advertising_technologies/retargeting/jampp.md
  _docs/_partners/advertising_technologies/retargeting/remerge.md
  _docs/_partners/channel_extensions/creative_and_personalization/intelligent_creative/movable_ink.md
  _docs/_partners/channel_extensions/loyalty/talonone.md
  _docs/_user_guide/administrative/app_settings/developer_console/message_activity_log_tab.md
  _docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/content_cards/creative_details.md
  _docs/_user_guide/message_building_by_channel/content_cards/testing.md
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/email/link_templates.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/testing.md
  _docs/_user_guide/message_building_by_channel/sms/create.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/conditional_logic.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md
Labels: cla-signed

#1758 BD-788, BD-786
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/campaign_funnel_report.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/retention_reports.md
  _docs/_user_guide/engagement_tools/canvas/canvas_funnel_reports.md
  _docs/_user_guide/engagement_tools/canvas/retention_reports.md
Labels: cla-signed

#1760 BD-787, BD-782, BD-778, BD-775
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl_clicktracking.md
Labels: cla-signed

#1759 Leftover Deploy - January 14, 2021
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  _docs/_api/endpoints/templates/content_blocks_templates/post_create_email_content_block.md
  _docs/_api/endpoints/templates/content_blocks_templates/post_update_content_block.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_api/transactional_message_api_campaign.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
  _docs/_hidden/private_betas/shopify.md
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
  _docs/_hidden/wip_partnerships/partnership_template.md
  _docs/_home/styling_test_page.md
  _docs/_home/templates/partner_page_template.md
  _docs/_home/templates/partner_page_template_video.md
  _docs/_partners/additional_channels/direct_mail/inkit.md
  _docs/_partners/additional_channels/mobile_wallet/passkit.md
  _docs/_partners/advertising_technologies/retargeting/jampp.md
  _docs/_partners/advertising_technologies/retargeting/remerge.md
  _docs/_partners/channel_extensions/creative_and_personalization/intelligent_creative/movable_ink.md
  _docs/_partners/channel_extensions/loyalty/talonone.md
  _docs/_user_guide/administrative/app_settings/developer_console/message_activity_log_tab.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/campaign_funnel_report.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/retention_reports.md
  _docs/_user_guide/engagement_tools/canvas/canvas_funnel_reports.md
  _docs/_user_guide/engagement_tools/canvas/retention_reports.md
  _docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/content_cards/creative_details.md
  _docs/_user_guide/message_building_by_channel/content_cards/testing.md
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/email/link_templates.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/testing.md
  _docs/_user_guide/message_building_by_channel/sms/create.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl_clicktracking.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/conditional_logic.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md
Labels: Deploy, cla-signed

#1761 Update HTML Push message docs
  _docs/_user_guide/message_building_by_channel/push/types.md
Labels: cla-signed

#1762 clarify other tag managers
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
Labels: cla-signed

#1748 Segment Cohort Feature Updates - MERGE ON 1/15
  _docs/_user_guide/engagement_tools/segments/segment_cohorts.md
  assets/img/cohort/property1.png
  assets/img/cohort/property2.png
  assets/img/cohort/property3.png
  assets/img/cohort/property4.png
  assets/img/cohort/segment_cohort_as_filter1.png
  assets/img/cohort/segment_cohort_as_filter2.png
  assets/img/cohort/segment_cohort_criteria.png
  assets/img/cohort/segment_cohort_list.png
  assets/img/cohort/segment_cohort_name.png
  assets/img/cohort/segment_cohort_nav.png
  assets/img/cohort/segment_cohort_save.png
  assets/img/cohort/segment_cohort_view.png
  assets/img/segment_cohort_as_filter1.png
  assets/img/segment_cohort_as_filter2.png
  assets/img/segment_cohort_criteria.png
  assets/img/segment_cohort_list.png
  assets/img/segment_cohort_name.png
  assets/img/segment_cohort_nav.png
  assets/img/segment_cohort_save.png
  assets/img/segment_cohort_view.png
Labels: cla-signed

#1765 Folder Name Fix
  _docs/_user_guide/engagement_tools/segments/segment_cohorts.md
Labels: cla-signed

#1763 Leftover Deploy Pt. 2 - January 15, 2021
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_user_guide/engagement_tools/segments/segment_cohorts.md
  _docs/_user_guide/message_building_by_channel/push/types.md
  assets/img/cohort/property1.png
  assets/img/cohort/property2.png
  assets/img/cohort/property3.png
  assets/img/cohort/property4.png
  assets/img/cohort/segment_cohort_as_filter1.png
  assets/img/cohort/segment_cohort_as_filter2.png
  assets/img/cohort/segment_cohort_criteria.png
  assets/img/cohort/segment_cohort_list.png
  assets/img/cohort/segment_cohort_name.png
  assets/img/cohort/segment_cohort_nav.png
  assets/img/cohort/segment_cohort_save.png
  assets/img/cohort/segment_cohort_view.png
  assets/img/segment_cohort_as_filter1.png
  assets/img/segment_cohort_as_filter2.png
  assets/img/segment_cohort_criteria.png
  assets/img/segment_cohort_list.png
  assets/img/segment_cohort_name.png
  assets/img/segment_cohort_nav.png
  assets/img/segment_cohort_save.png
  assets/img/segment_cohort_view.png
Labels: Deploy, cla-signed

#1769 Partner Doc Fix
  _docs/_partners/additional_channels.md
  _docs/_partners/additional_channels/support.md
  _docs/_partners/additional_channels/support/pypestream.md
  _docs/_partners/advertising_technologies.md
  _docs/_partners/advertising_technologies/attribution.md
  _docs/_partners/channel_extensions.md
  _docs/_partners/channel_extensions/loyalty.md
  _docs/_partners/channel_extensions/loyalty/jebbit.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/home.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#1770 Deploy - January 19, 2021
  _docs/_partners/additional_channels.md
  _docs/_partners/additional_channels/support.md
  _docs/_partners/additional_channels/support/pypestream.md
  _docs/_partners/advertising_technologies.md
  _docs/_partners/advertising_technologies/attribution.md
  _docs/_partners/channel_extensions.md
  _docs/_partners/channel_extensions/loyalty.md
  _docs/_partners/channel_extensions/loyalty/jebbit.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/home.md
  assets/js/broken_redirect_list.js
Labels: Deploy, cla-signed

#1771 clarify IDFA requirements
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
Labels: cla-signed

#1772 removed button id warning
  _docs/_user_guide/message_building_by_channel/in-app_messages/preview.md
Labels: cla-signed

#1773 BD-792, BD-791
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
Labels: cla-signed

#1774 BD-728, BD-694
  _docs/_partners/advertising_technologies/attribution/kochava.md
  _docs/_partners/advertising_technologies/social/facebook.md
  assets/img/fb_connected.jpg
  assets/img/fb_connected.png
Labels: cla-signed

#1775 BD-709, BD-660
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
Labels: cla-signed

#1777 Leftover Deploy - January 21, 2021
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
  _docs/_partners/advertising_technologies/attribution/kochava.md
  _docs/_partners/advertising_technologies/social/facebook.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/preview.md
  assets/img/fb_connected.jpg
  assets/img/fb_connected.png
Labels: Deploy, cla-signed

#1778 Remove redundant reference to stopwatch in trigger iam min interval docs
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md
Labels: cla-signed

#1779 Remove reference to staging in sample webhook payload
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/campaign_alerts.md
Labels: cla-signed

#1781 add sdk device attribute settings link
  _docs/_user_guide/administrative/app_settings/manage_app_group/custom_event_and_attribute_management.md
Labels: cla-signed

#1782 Update user_permissions.md
  _docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#1783 added image styling example
  _docs/_home/styling_test_page.md
Labels: cla-signed

#1789 Remove tvOS requirement from iOS CocoaPods page
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods.md
Labels: cla-signed

#1786 sdk_min_versions plugin
  _plugins/sdk_min_versions_tag.rb
  assets/css/_sdk_min_versions.scss
  assets/css/application.scss
Labels: cla-signed

#1785 added unused link cleaner script and readme
  _docs/_developer_guide/platform_integration_guides/android/customer_feedback.md
  scripts/README.md
  scripts/unused_link_cleaner.rb
Labels: cla-signed, status: on hold / do not merge

#1784 SDK-1071 - removed droidboy links from docs
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/data_models.md
  _docs/_developer_guide/platform_integration_guides/android/customer_feedback.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/customization.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/integration_overview.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/fireos/customer_feedback.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/fireos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/fireos/news_feed.md
  _docs/_developer_guide/platform_integration_guides/fireos/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/overview.md
  _includes/archive/android/gifs.md
  _includes/archive/in_app_message.md
  _includes/archive/session_tracking.md
Labels: cla-signed

#1793 BD-795, BD-794
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#1792 [SDK-1101][Docs] Migrate Stopwatch references in News Feed public docs
  _docs/_developer_guide/platform_integration_guides/ios/news_feed/defining_a_news_feed_category.md
  _docs/_developer_guide/platform_integration_guides/ios/news_feed/news_feed_data_model.md
  _docs/_developer_guide/platform_integration_guides/ios/news_feed/news_feed_integration_overview.md
  _docs/_developer_guide/platform_integration_guides/ios/news_feed/refreshing_the_news_feed.md
  _docs/_developer_guide/platform_integration_guides/ios/news_feed/requesting_unread_card_count.md
Labels: cla-signed

#1794 Blacklist -> Blocklist
  _docs/_user_guide/administrative/app_settings/manage_app_group/custom_event_and_attribute_management.md
  assets/img_archive/customattributessearch1.png
  assets/img_archive/customeventsview1.png
  assets/img_archive/manageproperties1.png
Labels: cla-signed

#1736 Crowdin Partnership Doc - Merge 1/28
  _docs/_partners/channel_extensions.md
  _docs/_partners/channel_extensions/localization.md
  _docs/_partners/channel_extensions/localization/crowdin.md
  _docs/_partners/home.md
  assets/img/crowdin/copy_api_key_identifier.png
  assets/img/crowdin/copy_sdk_endpoint.png
  assets/img/crowdin/create_api_key.png
  assets/img/crowdin/create_web_app.png
  assets/img/crowdin/crowdin_editor_email_preview.png
  assets/img/crowdin/sync_translations.png
Labels: Braze Partnerships, cla-signed, status: done

#1796 BD-796: Update Data Sharing Schema
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/google_tag_manager.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/badges.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/read_unread_indicators.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/refreshing_the_feed.md
  _docs/_developer_guide/platform_integration_guides/ios/news_feed/news_feed_integration_overview.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/testing.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/troubleshooting.md
  assets/download_file/data-sharing-raw-table-schemas.txt
Labels: cla-signed

#1732 Partner Article Grouping
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mparticle.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_personas.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
  _docs/_partners/home.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#1797 Crowdin Edit
  _docs/_partners/channel_extensions/localization/crowdin.md
Labels: cla-signed

#1713 In-App Message iOS Implementation Guide - MERGE 1/28
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/troubleshooting.md
  assets/img/iam_implementation_guide.png
Labels: cla-signed

#1694 Playable Partnership Doc - MERGE 1/28
  _docs/_partners/channel_extensions.md
  _docs/_partners/channel_extensions/creative_and_personalization.md
  _docs/_partners/channel_extensions/creative_and_personalization/intelligent_content.md
  _docs/_partners/channel_extensions/creative_and_personalization/intelligent_content/movable_ink.md
  _docs/_partners/channel_extensions/creative_and_personalization/intelligent_content/playable.md
  _docs/_partners/home.md
  assets/js/broken_redirect_list.js
Labels: Braze Partnerships, cla-signed, status: done

#1799 Update sdk_endpoints.md
  _docs/_user_guide/administrative/access_braze/sdk_endpoints.md
Labels: cla-signed

#1801 moved template links into template itself
  _docs/_developer_guide/platform_integration_guides/cordova/android_and_fireos/cordova_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/troubleshooting.md
  _includes/archive/cordova/cordova_sdk_integration_template.md
Labels: cla-signed
