Repository braze-inc/braze-docs, pull requests merged in 2021-03, with the labels that each got.

#1874 minor updates
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
Labels: cla-signed

#1873 Revert "Braze-to-braze webhooks are all 127.0.0.1 now"
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
Labels: cla-signed

#1875 BD-843: Alloys Page Kochava Redirect
  assets/js/broken_redirect_list.js
Labels: cla-signed

#1877 Deploy - March 2, 2021
  _docs/_api/basics.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  _plugins/sdk_min_versions_tag.rb
  assets/js/broken_redirect_list.js
Labels: Deploy

#1884 [iOS Docs] Push Story Integration Steps typo
  _docs/_developer_guide/platform_integration_guides/ios/push_story.md
Labels: cla-signed

#1864 Update button_id docs to reflect arbitrary tracking ids
  _docs/_partners/insights/behavioral_analytics/amplitude_for_currents.md
  _docs/_partners/insights/behavioral_analytics/mixpanel_for_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#1879 Update get_see_email_content_blocks_information.md
  _docs/_api/endpoints/templates/content_blocks_templates/get_see_email_content_blocks_information.md
Labels: cla-signed

#1883 BD-846: Canvas Audience Step FB Facebook Version Requirements Noted
  _docs/_user_guide/engagement_tools/canvas/canvas_components/fb_audience_sync.md
Labels: cla-signed

#1882 BD-820: Image Reformatting, Custom Event Callout
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
Labels: cla-signed

#1881 BD-845: Redirect
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/connected_content_retries.md
Labels: cla-signed

#1886 Leftover Deploy - March 4, 2021
  _docs/_api/endpoints/templates/content_blocks_templates/get_see_email_content_blocks_information.md
  _docs/_developer_guide/platform_integration_guides/ios/push_story.md
  _docs/_partners/insights/behavioral_analytics/amplitude_for_currents.md
  _docs/_partners/insights/behavioral_analytics/mixpanel_for_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/fb_audience_sync.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/connected_content_retries.md
Labels: Deploy, cla-signed

#1887 Implementation Guide Link Updates
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/implementation_guide.md
Labels: cla-signed

#1888 Images and references for Purchase Prediction
  _docs/_user_guide/predictive_suite/predictive_churn/messaging_users.md
  _docs/_user_guide/predictive_suite/predictive_purchases/prediction_analytics.md
  assets/img/purchasePrediction/purchaseEstimatedResults.png
  assets/img/purchasePrediction/purchaseFilters.png
  assets/img/purchasePrediction/purchaseTargeting.gif
Labels: cla-signed

#1889 Leftover Deploy Pt. 2 - March 5, 2021
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/implementation_guide.md
  _docs/_user_guide/predictive_suite/predictive_churn/messaging_users.md
  _docs/_user_guide/predictive_suite/predictive_purchases/prediction_analytics.md
  assets/img/purchasePrediction/purchaseEstimatedResults.png
  assets/img/purchasePrediction/purchaseFilters.png
  assets/img/purchasePrediction/purchaseTargeting.gif
Labels: Deploy, cla-signed

#1872 [SDK-1097][Docs] Update SPM download instructions to use new `braze-ios-sdk` repo
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/swift_package_manager.md
  assets/img/ios/spm/image2.png
  assets/img/ios/spm/image3.png
  assets/img/ios/spm/image4.png
Labels: cla-signed

#1890 BD-847: Unsubscribe Data Deleted Upon User Archival
  _docs/_user_guide/data_and_analytics/user_data_collection/user_archival.md
Labels: cla-signed

#1891 SDK-1274 - linkable docs to cordova endpoint setting
  _docs/_developer_guide/platform_integration_guides/cordova/ios/initial_sdk_setup.md
  _includes/archive/cordova/cordova_sdk_integration_template.md
Labels: cla-signed

#1848 BD-831 (DO NOT MERGE UNTIL 3/9/21)
  _docs/_api/data_retention.md
Labels: cla-signed

#1885 Nested Object Support Documentation - MERGE 3/9
  _docs/_hidden/private_betas/nested_object_support.md
  assets/img/nested_object1.png
  assets/img/nested_object2.png
Labels: cla-signed

#1866 Subscription and Usage Update - MERGE 3/9
  _docs/_user_guide/onboarding_with_braze.md
  _docs/_user_guide/onboarding_with_braze/subscription_and_usage.md
Labels: cla-signed

#1858 New User Track Rate Limit - Base 50k (FEATURE LIVE ON 3/8)
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
Labels: cla-signed

#1893 Deploy - March 9, 2021
  _docs/_api/data_retention.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_developer_guide/platform_integration_guides/cordova/ios/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/swift_package_manager.md
  _docs/_hidden/private_betas/nested_object_support.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_archival.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md
  _docs/_user_guide/message_building_by_channel/sms/sms_campaign_analytics.md
  _docs/_user_guide/onboarding_with_braze.md
  _docs/_user_guide/onboarding_with_braze/subscription_and_usage.md
  _includes/archive/cordova/cordova_sdk_integration_template.md
  assets/img/audience_path/audience_path.png
  assets/img/audience_path/audience_path1.png
  assets/img/audience_path/audience_path2.png
  assets/img/audience_path/audience_path3.png
  assets/img/audience_path/audience_path4.png
  assets/img/ios/spm/image2.png
  assets/img/ios/spm/image3.png
  assets/img/ios/spm/image4.png
  assets/img/nested_object1.png
  assets/img/nested_object2.png
Labels: Deploy

#1894 Revert "Deploy - March 9, 2021"
  _docs/_api/data_retention.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_developer_guide/platform_integration_guides/cordova/ios/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/swift_package_manager.md
  _docs/_hidden/private_betas/nested_object_support.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_archival.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md
  _docs/_user_guide/message_building_by_channel/sms/sms_campaign_analytics.md
  _docs/_user_guide/onboarding_with_braze.md
  _docs/_user_guide/onboarding_with_braze/subscription_and_billing.md
  _includes/archive/cordova/cordova_sdk_integration_template.md
  assets/img/audience_path/audience_path.png
  assets/img/audience_path/audience_path1.png
  assets/img/audience_path/audience_path2.png
  assets/img/audience_path/audience_path3.png
  assets/img/audience_path/audience_path4.png
  assets/img/ios/spm/image2.png
  assets/img/ios/spm/image3.png
  assets/img/ios/spm/image4.png
  assets/img/nested_object1.png
  assets/img/nested_object2.png
Labels: cla-signed

#1895 Revert "Revert "Deploy - March 9, 2021""
  _docs/_api/data_retention.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_developer_guide/platform_integration_guides/cordova/ios/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/swift_package_manager.md
  _docs/_hidden/private_betas/nested_object_support.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_archival.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md
  _docs/_user_guide/message_building_by_channel/sms/sms_campaign_analytics.md
  _docs/_user_guide/onboarding_with_braze.md
  _docs/_user_guide/onboarding_with_braze/subscription_and_usage.md
  _includes/archive/cordova/cordova_sdk_integration_template.md
  assets/img/audience_path/audience_path.png
  assets/img/audience_path/audience_path1.png
  assets/img/audience_path/audience_path2.png
  assets/img/audience_path/audience_path3.png
  assets/img/audience_path/audience_path4.png
  assets/img/ios/spm/image2.png
  assets/img/ios/spm/image3.png
  assets/img/ios/spm/image4.png
  assets/img/nested_object1.png
  assets/img/nested_object2.png
Labels: cla-signed

#1896 Develop Pull From Master
  _docs/_user_guide/message_building_by_channel/sms/sms_campaign_analytics.md
Labels: cla-signed

#1880 BD-844: Report Builder Feature Updates - MERGE ON 3/10
  _docs/_user_guide/data_and_analytics/your_reports/report_builder.md
  assets/img/campaign_comparison/campaign_comparison1.png
  assets/img/campaign_comparison/campaign_comparison2.png
  assets/img/campaign_comparison/campaign_comparison3.png
Labels: cla-signed

#1897 SMS Keyword Analytics Image Add
  _docs/_user_guide/message_building_by_channel/sms/sms_campaign_analytics.md
  assets/img/sms/keyword_responses.png
Labels: cla-signed

#1898 Leftover Deploy - March 10, 2021
  _docs/_user_guide/data_and_analytics/your_reports/report_builder.md
  _docs/_user_guide/message_building_by_channel/sms/sms_campaign_analytics.md
  assets/img/campaign_comparison/campaign_comparison1.png
  assets/img/campaign_comparison/campaign_comparison2.png
  assets/img/campaign_comparison/campaign_comparison3.png
  assets/img/sms/keyword_responses.png
Labels: Deploy, cla-signed

#1905 Fix SAML SSO plan availability
  _docs/_user_guide/administrative/access_braze/single_sign_on.md
Labels: cla-signed

#1901 BD-854: Revert User Track Rate Limit
  _docs/_api/endpoints/user_data/post_user_track.md
Labels: cla-signed

#1902 BD-850: Removal of Device and Carrier Data
  _docs/_user_guide/data_and_analytics/export_braze_data.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_device_and_carrier_data.md
Labels: cla-signed

#1903 BD-852: Update Total Opens Definition
  _docs/_user_guide/data_and_analytics/report_metrics.md
Labels: cla-signed

#1904 Updated Crowdin Integration documentation
  _docs/_partners/channel_extensions/localization/crowdin.md
Labels: cla-signed

#1906 Update integration.md minor apostrophe nit
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
Labels: cla-signed

#1907 Campaign Delivery Type Restructuring, BD-849: Event Property "Is Blank" Filter Caveat
  _docs/_api/endpoints/messaging.md
  _docs/_help/release_notes/2017/january.md
  _docs/_help/release_notes/2017/march.md
  _docs/_hidden/other/support_contact.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/ab_testing_with_random_buckets.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/campaign_connector.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/delivery_types.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/delivery_types/api_triggered_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/delivery_types/reeligibility.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/delivery_types/scheduled_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/delivery_types/triggered_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/scheduling_your_campaign.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_push_notifications.md
  _docs/_user_guide/intelligence/multivariate_testing.md
  _docs/_user_guide/message_building_by_channel/push/android/rich_notifications.md
  _includes/archive/troubleshooting_iams.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#1908 BD-848: Email Best Practices, From and Reply To Addresses
  _docs/_help/best_practices/email/technical_guidelines_and_tips.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
Labels: cla-signed

#1909 Swagger Out of Date Disclaimer
  assets/js/swagger/braze_swagger.json
Labels: cla-signed

#1910 Leftover Deploy - March 11, 2021
  _docs/_api/endpoints/messaging.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration.md
  _docs/_help/best_practices/email/technical_guidelines_and_tips.md
  _docs/_help/release_notes/2017/january.md
  _docs/_help/release_notes/2017/march.md
  _docs/_hidden/other/support_contact.md
  _docs/_partners/channel_extensions/localization/crowdin.md
  _docs/_user_guide/administrative/access_braze/single_sign_on.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/export_braze_data.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_device_and_carrier_data.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/ab_testing_with_random_buckets.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/campaign_connector.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/delivery_types.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/delivery_types/api_triggered_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/delivery_types/reeligibility.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/delivery_types/scheduled_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/delivery_types/triggered_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/scheduling_your_campaign.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_push_notifications.md
  _docs/_user_guide/intelligence/multivariate_testing.md
  _docs/_user_guide/message_building_by_channel/push/android/rich_notifications.md
  _includes/archive/troubleshooting_iams.md
  assets/js/broken_redirect_list.js
  assets/js/swagger/braze_swagger.json
Labels: Deploy, cla-signed

#1912 cordova android session disable docs
  _docs/_developer_guide/platform_integration_guides/cordova/android_and_fireos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/cordova/ios/initial_sdk_setup.md
Labels: cla-signed

#1913 [Trivial] Add note about provisional auth on Unity
  _docs/_developer_guide/platform_integration_guides/unity/ios/push_notifications.md
Labels: cla-signed

#1914 Update link to Appboy.h
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods.md
Labels: cla-signed

#1915 Added SMS as an exception to inactive users
  _docs/_user_guide/data_and_analytics/user_data_collection/user_archival.md
Labels: cla-signed

#1918 BD-856, BD-857, BD-858
  _docs/_developer_guide/platform_integration_guides/web/content_cards/multiple_feeds.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/rate-limiting.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/time_based_canvas.md
  _docs/_user_guide/engagement_tools/segments/regex.md
Labels: cla-signed

#1917 BD-859: Update Services Handbook
  _docs/_docs_pages/index.md
  _docs/_hidden/other/handbooks.md
  assets/download_file/Braze_Success_and_Support_Services_Handbook21.pdf
  assets/js/broken_redirect_list.js
Labels: cla-signed

#1920 BD-838: Update Chrome Web Push Title and Message Character Limit
  _docs/_help/best_practices/image_and_text_specifications.md
Labels: cla-signed

#1922 Update edume.md
  _docs/_partners/channel_extensions/learning/edume.md
Labels: cla-signed

#1921 Update report_builder.md
  _docs/_user_guide/data_and_analytics/your_reports/report_builder.md
Labels: cla-signed

#1751 [SDK-1057] Updated iOS Push Story documentation
  _docs/_developer_guide/platform_integration_guides/ios/push_story.md
  assets/img/ios/push_story/manual1.png
  assets/img/ios/push_story/spm1.png
  assets/img/ios/push_story/spm2.png
  assets/img_archive/ios_pushstory_01.png
  assets/img_archive/ios_pushstory_02.png
  assets/img_archive/ios_pushstory_03.png
  assets/img_archive/ios_pushstory_04.png
  assets/img_archive/ios_pushstory_05.png
Labels: cla-signed

#1919 BD-825: Canvas Post Launch Queued Step Caveat
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/change_your_canvas_after_launch.md
Labels: cla-signed

#1925 BD-860: Duplicate Sentence
  _docs/_hidden/misc_reference/x-in-y-behavior.md
Labels: cla-signed

#1900 Be more clear about Connected Content caching
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
Labels: cla-signed

#1899 CDN Configuration SSL Removal - MERGE 3/16
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl_clicktracking.md
Labels: cla-signed

#1927 BD-861, BD-862
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#1928 Remove DMARC section
  _docs/_user_guide/onboarding_with_braze/email_setup/authentication.md
Labels: cla-signed

#1929 [SDK-1308] Update Unity manual integration docs for frameworks
  _docs/_developer_guide/platform_integration_guides/unity/ios/sdk_integration.md
  assets/img_archive/unity-bundle-ios.png
  assets/img_archive/unity_add_framework_search_paths.png
  assets/img_archive/unity_add_other_linker_flag.png
  assets/img_archive/unity_adding_iOS_SDK.png
Labels: cla-signed

#1931 Revise to reflect change to confidence
  _docs/_user_guide/intelligence/multivariate_testing.md
Labels: cla-signed

#1933 BD-863, BD-864, BD-865
  _docs/_partners/insights/behavioral_analytics/amplitude_for_currents.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
  _docs/_user_guide/onboarding_with_braze/data_points.md
Labels: cla-signed

#1934 Updated Regex Examples
  _docs/_user_guide/engagement_tools/segments/regex.md
  assets/img/regex/regeximg1.png
Labels: cla-signed

#1935 clarify survey reporting
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
Labels: cla-signed

#1932 Release Notes Catch Up
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2016.md
  _docs/_help/release_notes/2017.md
  _docs/_help/release_notes/2018.md
  _docs/_help/release_notes/2019.md
  _docs/_help/release_notes/2020.md
  _docs/_help/release_notes/2021.md
  _docs/_help/release_notes/2021/february.md
  _docs/_help/release_notes/2021/january.md
  _docs/_help/release_notes/2021/march.md
Labels: cla-signed

#1937 In-App Message Stop Campaign after Launch Caveat
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/implementation_guide.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
Labels: cla-signed

#1938 IAM Update
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
Labels: cla-signed

#1939 Deploy Pt. 2 - March 18, 2021
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
Labels: Deploy, cla-signed

#1941 Handbooks redirect
  assets/js/broken_redirect_list.js
Labels: cla-signed

#1942 Leftover Deploy Pt.2 - March 19, 2021
  assets/js/broken_redirect_list.js
Labels: Deploy

#1943 Update ssl_clicktracking.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl_clicktracking.md
Labels: cla-signed

#1945 changed note: added non-dismissed CC
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
Labels: cla-signed

#1946 Handbook Nomenclature Fix
  _docs/_hidden/other/handbooks.md
  assets/download_file/Braze_Success_and_Support_Services_Handbook_21.pdf
  assets/download_file/Braze_Success_and_Support_Services_Handbook_22.pdf
  assets/js/broken_redirect_list.js
Labels: cla-signed

#1947 Rename "Custom Properties" to "Properties" [ING-2089]
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
Labels: cla-signed

#1948 Update Nested Event Property Triggering Image [ING-2089]
  assets/img/nested_object2.png
Labels: cla-signed

#1944 SSL Clicktracking minor formatting edit
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl_clicktracking.md
Labels: cla-signed

#1949 Minor SMS Updates
  _docs/_user_guide/message_building_by_channel/sms/keywords.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/unknown_phone_numbers.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/best_practices.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/best_practices/high_volume_sending.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/best_practices/multi_country_sms_sending.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#1950 BD-868: Segment Extension GA
  _docs/_hidden/private_betas/shopify.md
  _docs/_user_guide/engagement_tools/segments.md
  _docs/_user_guide/engagement_tools/segments/segment_cohorts.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/onboarding_with_braze/terms_to_know.md
  assets/img/cohort/property1.png
  assets/img/cohort/property4.png
  assets/img/cohort/segment_cohort_criteria.png
  assets/img/cohort/segment_cohort_name.png
  assets/img/cohort/segment_cohort_nav.png
  assets/img/cohort/segment_cohort_save.png
  assets/img/cohort/segment_cohort_view.png
  assets/img/segment/property1.png
  assets/img/segment/property2.png
  assets/img/segment/property3.png
  assets/img/segment/property4.png
  assets/img/segment/segment_cohort_as_filter1.png
  assets/img/segment/segment_cohort_as_filter2.png
  assets/img/segment/segment_cohort_list.png
  assets/img/segment/segment_extension1.png
  assets/img/segment/segment_extension2.png
  assets/img/segment/segment_extension3.png
  assets/img/segment/segment_extension5.png
  assets/img/segment/segment_extension6.png
  assets/img/segment/segment_extension7.png
  assets/img/segment/segment_extension8.png
Labels: cla-signed

#1952 Automatically Generated -> Out of the Box
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  _docs/_api/identifier_types.md
  _docs/_developer_guide/disclosures/open_source_software_disclosure.md
  _docs/_developer_guide/platform_integration_guides/web/cookies_and_storage.md
  _docs/_help/release_notes/2019/may.md
  _docs/_help/release_notes/deprecations/apptimize.md
Labels: cla-signed

#1823 Docs for drag_and_drop_editor.md
  _docs/_api/endpoints/templates/email_templates/get_list_email_templates.md
  _docs/_api/endpoints/templates/email_templates/get_see_email_template_information.md
  _docs/_hidden/private_betas/dnd_editor_blocks.md
  _docs/_hidden/private_betas/dnd_email_template.md
  _docs/_hidden/private_betas/drag_and_drop_editor.md
  assets/img/dnd_badge_icon.png
  assets/img/dnd_compose_error.png
  assets/img/dnd_editor_workflow.png
Labels: cla-signed

#1951 BD-869: Apple Push Object Alert Clarification
  _docs/_api/objects_filters/apple_objects.md
Labels: cla-signed

#1954 Deploy - March 23, 2021
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  _docs/_api/endpoints/templates/email_templates/get_list_email_templates.md
  _docs/_api/endpoints/templates/email_templates/get_see_email_template_information.md
  _docs/_api/identifier_types.md
  _docs/_api/objects_filters/apple_objects.md
  _docs/_developer_guide/disclosures/open_source_software_disclosure.md
  _docs/_developer_guide/platform_integration_guides/web/cookies_and_storage.md
  _docs/_help/release_notes/2019/may.md
  _docs/_help/release_notes/deprecations/apptimize.md
  _docs/_hidden/other/handbooks.md
  _docs/_hidden/private_betas/dnd_editor_blocks.md
  _docs/_hidden/private_betas/dnd_email_template.md
  _docs/_hidden/private_betas/drag_and_drop_editor.md
  _docs/_hidden/private_betas/shopify.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/engagement_tools/segments.md
  _docs/_user_guide/engagement_tools/segments/segment_cohorts.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/sms/keywords.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/unknown_phone_numbers.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/best_practices.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/best_practices/high_volume_sending.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/best_practices/multi_country_sms_sending.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl_clicktracking.md
  _docs/_user_guide/onboarding_with_braze/terms_to_know.md
  assets/download_file/Braze_Success_and_Support_Services_Handbook_21.pdf
  assets/download_file/Braze_Success_and_Support_Services_Handbook_22.pdf
  assets/img/cohort/property1.png
  assets/img/cohort/property4.png
  assets/img/cohort/segment_cohort_criteria.png
  assets/img/cohort/segment_cohort_name.png
  assets/img/cohort/segment_cohort_nav.png
  assets/img/cohort/segment_cohort_save.png
  assets/img/cohort/segment_cohort_view.png
  assets/img/dnd_badge_icon.png
  assets/img/dnd_compose_error.png
  assets/img/dnd_editor_workflow.png
  assets/img/nested_object2.png
  assets/img/segment/property1.png
  assets/img/segment/property2.png
  assets/img/segment/property3.png
  assets/img/segment/property4.png
  assets/img/segment/segment_cohort_as_filter1.png
  assets/img/segment/segment_cohort_as_filter2.png
  assets/img/segment/segment_cohort_list.png
  assets/img/segment/segment_extension1.png
  assets/img/segment/segment_extension2.png
  assets/img/segment/segment_extension3.png
  assets/img/segment/segment_extension5.png
  assets/img/segment/segment_extension6.png
  assets/img/segment/segment_extension7.png
  assets/img/segment/segment_extension8.png
  assets/js/broken_redirect_list.js
Labels: Deploy, cla-signed

#1955 Japanese Translation of Innovation Statement
  _docs/_help/innovation_statement.md
Labels: cla-signed

#1956 Deploy Pt. 2 - March 24, 2021
  _docs/_help/innovation_statement.md
Labels: Deploy, cla-signed

#1961 Update screenshots
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  assets/img_archive/list_unsub_img1.png
Labels: cla-signed

#1962 add description
  _docs/_docs_pages/index.md
Labels: cla-signed

#1953 Google Audience Sync - Early Access
  _docs/_partners/advertising_technologies/social/canvas_steps.md
  _docs/_partners/advertising_technologies/social/canvas_steps/facebook_audience_sync.md
  _docs/_partners/advertising_technologies/social/canvas_steps/google_audience_sync.md
  _docs/_partners/advertising_technologies/social/facebook.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/fb_audience_sync.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/google_audience_sync.md
  assets/img/google_sync/Screen Shot 2021-03-17 at 1.27.18 PM.png
  assets/img/google_sync/google_sync1.png
  assets/img/google_sync/google_sync2.png
  assets/img/google_sync/google_sync3.png
  assets/img/google_sync/google_sync4.png
  assets/img/google_sync/google_sync5.png
  assets/img/google_sync/google_sync6.png
  assets/img/google_sync/google_sync7.png
  assets/img/google_sync/google_sync8.png
  assets/img/google_sync/google_sync9.png
Labels: cla-signed

#1959 Link Fix for Drag-and-Drop Early Access Docs
  _docs/_hidden/private_betas/dnd_editor_blocks.md
  _docs/_hidden/private_betas/dnd_email_template.md
  _docs/_hidden/private_betas/drag_and_drop_editor.md
Labels: cla-signed

#1958 Update Unity iOS instructions to include capability requirement
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/unity/ios/push_notifications.md
Labels: cla-signed

#1957 Add condition to card dismissal description
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/data_model.md
Labels: cla-signed

#1964 Leftover Deploy - March 25, 2021
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/data_model.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/unity/ios/push_notifications.md
  _docs/_docs_pages/index.md
  _docs/_hidden/private_betas/dnd_editor_blocks.md
  _docs/_hidden/private_betas/dnd_email_template.md
  _docs/_hidden/private_betas/drag_and_drop_editor.md
  _docs/_partners/advertising_technologies/social/canvas_steps.md
  _docs/_partners/advertising_technologies/social/canvas_steps/facebook_audience_sync.md
  _docs/_partners/advertising_technologies/social/canvas_steps/google_audience_sync.md
  _docs/_partners/advertising_technologies/social/facebook.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/fb_audience_sync.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/google_audience_sync.md
  assets/img/google_sync/Screen Shot 2021-03-17 at 1.27.18 PM.png
  assets/img/google_sync/google_sync1.png
  assets/img/google_sync/google_sync2.png
  assets/img/google_sync/google_sync3.png
  assets/img/google_sync/google_sync4.png
  assets/img/google_sync/google_sync5.png
  assets/img/google_sync/google_sync6.png
  assets/img/google_sync/google_sync7.png
  assets/img/google_sync/google_sync8.png
  assets/img/google_sync/google_sync9.png
  assets/img_archive/list_unsub_img1.png
Labels: Deploy

#1970 Update kramdown to 2.3.1
  Gemfile
  Gemfile.lock
  _docs/_partners/channel_extensions/support.md
  assets/img/dropdown.svg
Labels: cla-signed

#1971 Update data_retention.md
  _docs/_api/data_retention.md
Labels: cla-signed

#1968 Explain how to cache Connected Content POST calls
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
Labels: cla-signed

#1967 S&S New Handbook Upload
  assets/download_file/Braze_Success_and_Support_Services_Handbook_22.pdf
Labels: cla-signed

#1966 A2P 10DLC - SMS
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2020/june.md
  _docs/_partners/advertising_technologies/attribution/appsflyer.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/retention_reports.md
  _docs/_user_guide/engagement_tools/canvas/retention_reports.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/short_and_long_codes.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/short_and_long_codes.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid.md
Labels: cla-signed, release notes

#1972 Segment Cohort Redirect to Segment Extension
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#1960 Users/Track Limit Update - Merge 3/29
  _docs/_api/endpoints/user_data/post_user_track.md
Labels: cla-signed, release notes

#1977 Shopify Update - Phone Number Syncing
  _docs/_hidden/private_betas/shopify.md
Labels: cla-signed

#1978 Deploy - March 30, 2021
  Gemfile
  Gemfile.lock
  _docs/_api/data_retention.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options.md
  _docs/_help/best_practices/client_integration_gallery.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2020/june.md
  _docs/_hidden/private_betas/shopify.md
  _docs/_partners/advertising_technologies/attribution/appsflyer.md
  _docs/_partners/channel_extensions/support.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/retention_reports.md
  _docs/_user_guide/engagement_tools/canvas/retention_reports.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/short_and_long_codes.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/short_and_long_codes.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid.md
  assets/download_file/Braze_Success_and_Support_Services_Handbook_22.pdf
  assets/img/dropdown.svg
  assets/img_archive/HTML5-1.gif
  assets/js/broken_redirect_list.js
Labels: Deploy, cla-signed

#1973 mParticle Currents Documentation
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  assets/img/braze-feed-act1.png
  assets/img/braze-feed-act2.png
  assets/img/braze-feed-inputs.png
Labels: cla-signed

#1979 [Trivial][No ticket] Fix broken iOS links
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/fine_network_traffic_control.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/badges.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/refreshing_the_feed.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
  _docs/_developer_guide/platform_integration_guides/ios/news_feed/refreshing_the_news_feed.md
  _docs/_developer_guide/platform_integration_guides/ios/news_feed/requesting_unread_card_count.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/customization.md
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
  _includes/archive/apple/initial_setup.md
  _includes/archive/session_tracking.md
Labels: cla-signed

#1982 BD-880: Remove Device and Carriers Reference & Update Shopify Beta Doc
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/test_your_basic_integration.md
  _docs/_hidden/private_betas/shopify.md
Labels: cla-signed

#1980 content card methods
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization.md
Labels: cla-signed

#1983 Fix referenced link in an alert
  _docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
Labels: cla-signed

#1984 add subtabs option
  _docs/_home/styling_test_page.md
  _plugins/tabs.rb
  assets/css/_tabs.scss
  assets/js/documents.js
Labels: cla-signed
