Repository braze-inc/braze-docs, pull requests merged in 2021-09, with the labels that each got.

#2603 Leftover Deploy - September 1, 2021
  _docs/_api/endpoints/export/sms.md
  _docs/_api/endpoints/export/sms/get_query_invalid_numbers.md
  _docs/_user_guide/message_building_by_channel/email/mpp.md
Labels: cla-signed, Deploy

#2543 Update Search ui
  _includes/search_page.html
  assets/css/_docs_search.scss
  assets/css/_header_search.scss
  assets/js/algolia_header_search.js
  assets/js/algolia_main_search.js
  assets/js/broken_redirect_list.js
  assets/js/documents.js
Labels: cla-signed

#2606 BD-1056: Fix heading levels
  _docs/_user_guide/engagement_tools/templates_and_media/faqs.md
Labels: cla-signed

#2607 BD-1057: Unify note on REST API triggering across core SDKs
  _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/in-app_message_delivery.md
Labels: cla-signed

#2608 Minor Edits: Noting Android Specific Articles and Adding iOS 15 field to MPP
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/adding_braze_js_interface.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/androidx_integration.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/optional_gaid_collection.md
  _docs/_user_guide/message_building_by_channel/email/mpp.md
Labels: cla-signed

#2609 BD-1060: Fix missing code snippet in push notification integration.md…
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
Labels: cla-signed

#2605 [SDK-908] Make final iOS integration steps their own page
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/carthage_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/completing_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/ios_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/swift_package_manager.md
Labels: cla-signed

#2611 Revert "BD-1060: Fix missing code snippet in push notification integration.md…"
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
Labels: cla-signed

#2610 Remove geofence specific analytics claim
  _docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md
Labels: cla-signed

#2612 Update broken URL
  _docs/_api/objects_filters/user_attributes_object.md
Labels: cla-signed

#2589 Missed instruction on react-native sdk IOS setup
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Labels: cla-signed

#2487 Rework Liquid filters documentation
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
  assets/js/broken_redirect_list.js
Labels: status: in progress, cla-signed

#2615 BD-1061: Update /users/export/segment sample export
  _docs/_api/endpoints/export/user_data/post_users_segment.md
Labels: cla-signed

#2613 Leftover Deploy - September 2, 2021
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_api/objects_filters/user_attributes_object.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/adding_braze_js_interface.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/androidx_integration.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/optional_gaid_collection.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/carthage_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/completing_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/ios_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/swift_package_manager.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/in-app_message_delivery.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md
  _docs/_user_guide/engagement_tools/templates_and_media/faqs.md
  _docs/_user_guide/message_building_by_channel/email/mpp.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
  _includes/search_page.html
  assets/css/_docs_search.scss
  assets/css/_header_search.scss
  assets/js/algolia_header_search.js
  assets/js/algolia_main_search.js
  assets/js/broken_redirect_list.js
  assets/js/documents.js
Labels: cla-signed, Deploy

#2594 Alerts Cleanup - Technology Partners Section
  _docs/_partners/canvas_steps/facebook_audience_sync.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/fivetran.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _docs/_partners/message_personalization/dynamic_content/playable.md
  _docs/_partners/message_personalization/location/radar.md
Labels: cla-signed

#2619 30 for 30 Tips
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/unity/Analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/setting_user_ids.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/conversion_events.md
  _docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters.md
  _includes/archive/setting_user_ids/best_practices.md
Labels: cla-signed

#2618 Alerts Cleanup - Developer Guide Section
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
Labels: cla-signed

#2621 Liquid syntax quick fix
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: cla-signed

#2614 [SDK-908] Reorganize iOS installation methods into directory
  _docs/_api/basics.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/completing_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/installation_methods.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/installation_methods/carthage_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/installation_methods/cocoapods.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/installation_methods/manual_integration_options.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/installation_methods/swift_package_manager.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/push_story.md
  _docs/_developer_guide/platform_integration_guides/macOS/initial_sdk_setup.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#2620 button 2 message
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
Labels: cla-signed

#2622 push early access
  _docs/_user_guide/message_building_by_channel/push/ios/notification_options.md
Labels: cla-signed

#2623 Deploy - September 7, 2021
  _docs/_api/basics.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/completing_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/installation_methods.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/installation_methods/carthage_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/installation_methods/cocoapods.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/installation_methods/manual_integration_options.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/installation_methods/swift_package_manager.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/push_story.md
  _docs/_developer_guide/platform_integration_guides/macOS/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
  _docs/_developer_guide/platform_integration_guides/unity/Analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_partners/canvas_steps/facebook_audience_sync.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/fivetran.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _docs/_partners/message_personalization/dynamic_content/playable.md
  _docs/_partners/message_personalization/location/radar.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/conversion_events.md
  _docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/push/ios/notification_options.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  _includes/archive/setting_user_ids/best_practices.md
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#2627 Update text for the security event download.
  _docs/_user_guide/administrative/company_settings/security_settings.md
Labels: cla-signed

#2628 BD-1062: Clarify update of user alias alert
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Labels: cla-signed

#2629 BD-1063: Fix broken link
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
Labels: cla-signed

#2630 BD-1041: Remove duplicate data points listed under Engagement tab
  _docs/_user_guide/onboarding_with_braze/data_points.md
Labels: cla-signed

#2631 Removal of Android X
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/androidx_integration.md
Labels: cla-signed

#2632 Search page returns description
  _includes/search_page.html
Labels: cla-signed

#2633 BD-1058: Documenting IAM Dismissal Methods in Dev Guide
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization.md
  _includes/archive/android/in_app_messages/customization.md
Labels: cla-signed

#2634 Add entry for anchor text to styling_test_page.md
  _docs/_home/styling_test_page.md
Labels: cla-signed

#2624 [SDK-1827] Update react_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Labels: cla-signed

#2635 Link Fix
  _docs/_developer_guide/home.md
  _docs/_developer_guide/platform_integration_guides/cordova/initial_sdk_setup/android.md
  _docs/_partners/data_and_infrastructure_agility/wrapper_sdks/cordova.md
Labels: cla-signed

#2637 Leftover Deploy - September 9, 2021
  _docs/_developer_guide/home.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/androidx_integration.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/cordova/initial_sdk_setup/android.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization.md
  _docs/_home/styling_test_page.md
  _docs/_partners/data_and_infrastructure_agility/wrapper_sdks/cordova.md
  _docs/_user_guide/administrative/company_settings/security_settings.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
  _docs/_user_guide/onboarding_with_braze/data_points.md
  _includes/archive/android/in_app_messages/customization.md
  _includes/search_page.html
Labels: cla-signed, Deploy

#2638 BD-1064: Clarify Unix timestamps are limited to 10 digits
  _docs/_hidden/private_betas/link_aliasing.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#2639 BD-1065: Fix typo
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
Labels: cla-signed

#2640 BD-1066: Add beta note to nested_object_support.md
  _docs/_user_guide/data_and_analytics/custom_data/nested_object_support.md
Labels: cla-signed

#2641 Adding Redirects for Platform Toggle
  _docs/_developer_guide/platform_integration_guides/android.md
  _docs/_developer_guide/platform_integration_guides/cordova.md
  _docs/_developer_guide/platform_integration_guides/flutter.md
  _docs/_developer_guide/platform_integration_guides/macOS.md
  _docs/_developer_guide/platform_integration_guides/react_native.md
  _docs/_developer_guide/platform_integration_guides/roku.md
  _docs/_developer_guide/platform_integration_guides/tvos.md
  _docs/_developer_guide/platform_integration_guides/unity.md
  _docs/_developer_guide/platform_integration_guides/unity/sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/unreal_engine.md
  _docs/_developer_guide/platform_integration_guides/web.md
  _docs/_developer_guide/platform_integration_guides/windows_universal.md
  _docs/_developer_guide/platform_integration_guides/xamarin.md
Labels: cla-signed

#2643 BD-1067: Clarify references to user alias import and templates
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Labels: cla-signed

#2644 Add redirect for Android troubleshooting scenarios
  assets/js/broken_redirect_list.js
Labels: cla-signed

#2626 Alerts Cleanup - API Section
  _docs/_api/api_key.md
  _docs/_api/basics.md
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
  _docs/_api/endpoints/templates/email_templates/get_list_email_templates.md
  _docs/_api/endpoints/user_data/post_user_alias.md
  _docs/_api/endpoints/user_data/post_user_identify.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_api/objects_filters/user_attributes_object.md
Labels: cla-signed

#2648 Update mparticle_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md
Labels: cla-signed

#2650 Add redirect and fix broken link
  _docs/_user_guide/message_building_by_channel/push/best_practices.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#2651 Correct link target for "Subscription Groups"
  _docs/_user_guide/message_building_by_channel/sms/sms_laws_and_regulations.md
Labels: cla-signed

#2649 BD-1069: Add support for array of objects data type
  _docs/_hidden/private_betas/array_of_objects.md
  _docs/_hidden/private_betas/nested_custom_attribute_support.md
  assets/img_archive/array_of_objects_segmenting_1.gif
  assets/img_archive/array_of_objects_segmenting_2.png
  assets/img_archive/array_of_objects_segmenting_3.png
Labels: cla-signed

#2652 Update ios_15.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_15.md
Labels: cla-signed

#2653 BD-1070: Remove beta note
  _docs/_user_guide/engagement_tools/canvas.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
Labels: cla-signed

#2654 BD-1068: Update API rate limits
  _docs/_api/basics.md
  _docs/_api/endpoints/export/custom_events/get_custom_events.md
  _docs/_api/endpoints/user_data/post_user_alias.md
  _docs/_api/endpoints/user_data/post_user_delete.md
  _docs/_api/endpoints/user_data/post_user_identify.md
Labels: cla-signed

#2655 Apply Image Style Guide
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/capturing_lapsing_users.md
  assets/img_archive/2weeklapse1.png
  assets/img_archive/2weeklapse2.png
  assets/img_archive/2weeklapse3.jpg
  assets/img_archive/2weeklapse3.png
  assets/img_archive/2weeklapse4.png
  assets/img_archive/A_Tracking.png
  assets/img_archive/A_Tracking_2.png
  assets/img_archive/App_Setup_API.png
  assets/img_archive/Archive_pause_selected.png
  assets/img_archive/Archiving.png
  assets/img_archive/accessing_emoji_1.png
  assets/img_archive/accessing_emoji_2.png
  assets/img_archive/accessing_emoji_3.gif
  assets/img_archive/action-based-campaign.png
  assets/img_archive/action_based_geofence_trigger.png
  assets/img_archive/action_delivery_new.png
  assets/img_archive/add_app_groups.png
  assets/img_archive/add_appboy_ui.png
  assets/img_archive/add_content_extension.png
  assets/img_archive/adding_a_team.png
  assets/img_archive/app_usage.png
  assets/img_archive/approx_limit_for_IAM.png
  assets/img_archive/appsettingsview1.png
  assets/img_archive/archive_a_team.png
  assets/img_archive/authentication_rules_new.png
Labels: cla-signed

#2656 Leftover Deploy - September 16, 2021
  _docs/_api/basics.md
  _docs/_api/endpoints/export/custom_events/get_custom_events.md
  _docs/_api/endpoints/user_data/post_user_alias.md
  _docs/_api/endpoints/user_data/post_user_delete.md
  _docs/_api/endpoints/user_data/post_user_identify.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_15.md
  _docs/_hidden/private_betas/array_of_objects.md
  _docs/_hidden/private_betas/nested_custom_attribute_support.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/capturing_lapsing_users.md
  _docs/_user_guide/engagement_tools/canvas.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
  _docs/_user_guide/message_building_by_channel/push/best_practices.md
  _docs/_user_guide/message_building_by_channel/sms/sms_laws_and_regulations.md
  assets/img_archive/2weeklapse1.png
  assets/img_archive/2weeklapse2.png
  assets/img_archive/2weeklapse3.jpg
  assets/img_archive/2weeklapse3.png
  assets/img_archive/2weeklapse4.png
  assets/img_archive/A_Tracking.png
  assets/img_archive/A_Tracking_2.png
  assets/img_archive/App_Setup_API.png
  assets/img_archive/Archive_pause_selected.png
  assets/img_archive/Archiving.png
  assets/img_archive/accessing_emoji_1.png
  assets/img_archive/accessing_emoji_2.png
  assets/img_archive/accessing_emoji_3.gif
  assets/img_archive/action-based-campaign.png
  assets/img_archive/action_based_geofence_trigger.png
  assets/img_archive/action_delivery_new.png
  assets/img_archive/add_app_groups.png
  assets/img_archive/add_appboy_ui.png
  assets/img_archive/add_content_extension.png
  assets/img_archive/adding_a_team.png
  assets/img_archive/app_usage.png
  assets/img_archive/approx_limit_for_IAM.png
  assets/img_archive/appsettingsview1.png
  assets/img_archive/archive_a_team.png
  assets/img_archive/array_of_objects_segmenting_1.gif
  assets/img_archive/array_of_objects_segmenting_2.png
  assets/img_archive/array_of_objects_segmenting_3.png
  assets/img_archive/authentication_rules_new.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#2616 Out-of-the-box Content Cards Examples
  _docs/_api/parameters.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization.md
  _docs/_help/release_notes/2020/december.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/message_orchestration/additional_channels/calendar/rokt_calendar.md
  _docs/_partners/message_personalization/location/foursquare.md
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/generations.md
  assets/img/custom_interfaces.png
  assets/img/interface1.png
  assets/img/interface2.png
  assets/img/interface3.png
Labels: cla-signed

#2661 Update retention_reports.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/retention_reports.md
Labels: cla-signed

#2660 Update canvas_funnel_reports.md
  _docs/_user_guide/engagement_tools/canvas/canvas_funnel_reports.md
Labels: cla-signed

#2658 Apply Image Style Guide
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/attribute_triggers.md
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_action_buttons.md
  _docs/_user_guide/message_building_by_channel/push/android/rich_notifications.md
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
  assets/img_archive/Android_Rich_SummaryText.png
  assets/img_archive/Android_rich_image.png
  assets/img_archive/android_advanced_settings.png
  assets/img_archive/android_push_test.png
  assets/img_archive/android_rich_image.png
  assets/img_archive/android_rich_summarytext.png
  assets/img_archive/android_sessions.png
  assets/img_archive/any_value.png
  assets/img_archive/api_delivered_new.png
  assets/img_archive/conversion_event_selection.png
  assets/img_archive/new_campaign_push.png
  assets/img_archive/newcampaign_new.png
  assets/img_archive/push2.png
  assets/img_archive/push_1.png
  assets/img_archive/push_2.png
  assets/img_archive/push_3.png
  assets/img_archive/schedule.png
  assets/img_archive/super_vip.png
  assets/img_archive/targeting_error.png
  assets/img_archive/trigger_attribute.png
Labels: cla-signed

#2663 Remove "Connected Content Errors" from notification preference in doc…
  _docs/_user_guide/administrative/company_settings/notification_preferences.md
Labels: cla-signed

#2665 ios 15 docs
  _docs/_developer_guide/platform_integration_guides/ios/ios_15.md
Labels: cla-signed

#2666 Add site.baseurl prefix to URLs
  _docs/_developer_guide/platform_integration_guides/ios/ios_15.md
Labels: cla-signed

#2667 Update User Guide popular topics for Aug - Sept
  _docs/_user_guide/introduction.md
Labels: cla-signed

#2668 Apply image style guide
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/delivery_types/api_triggered_delivery.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/content-cards_in_canvas.md
  assets/img_archive/api-key-options.png
  assets/img_archive/api-key-permissions.png
  assets/img_archive/api-trigger-reeligible.png
  assets/img_archive/api_trigger_photo_social_example_1.png
  assets/img_archive/api_triggered_campaign_delivery.png
  assets/img_archive/api_triggered_creation_step.png
  assets/img_archive/api_triggered_photo_social_example_1.png
  assets/img_archive/api_triggered_reeligible.png
  assets/img_archive/content-cards-in-canvas-analytics.png
  assets/img_archive/content-cards-in-canvas-multiple-channels.png
  assets/img_archive/content-cards-in-canvas-single-channel.png
  assets/img_archive/content-cards-in-canvas.png
  assets/img_archive/conversion_event_details.png
Labels: cla-signed

#2669 October 2021 Braze Release Notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2021.md
  _docs/_help/release_notes/2021/october.md
Labels: cla-signed

#2671 BD-1077: Update tealium_overview.png
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  assets/img/tealium/tealium_overview.png
Labels: cla-signed

#2672 BD-1075: Clarify information on Sending Test Messages page
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_push_notifications.md
Labels: cla-signed

#2670 BD-1071: Update iOS Rich Notifications for style and images
  _docs/_user_guide/message_building_by_channel/push/ios/rich_notifications.md
  assets/img_archive/RichNot_AddImage.png
  assets/img_archive/RichNot_iOS10_select.png
  assets/img_archive/rich_notification_add_image.png
  assets/img_archive/rich_notification_ios.gif
  assets/img_archive/rich_notification_ios10_select.png
Labels: cla-signed

#2662 Apply Image Style Guide
  assets/img_archive/Enable_push_capabilities.png
  assets/img_archive/WebNewsFeed.png
  assets/img_archive/Webhook_template_save.png
  assets/img_archive/Wish_List_2.png
  assets/img_archive/Wish_List_Email.png
  assets/img_archive/test-in-app.png
  assets/img_archive/testemail.png
  assets/img_archive/testpush.png
  assets/img_archive/webhook-error.png
  assets/img_archive/zendesk_step2.png
Labels: cla-signed

#2674 Image edits for Company-Wide Settings page
  _docs/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md
  assets/img_archive/click_edit_f.png
  assets/img_archive/copy_url.png
  assets/img_archive/notification_preferences.png
  assets/img_archive/security_settings_new.png
  assets/img_archive/slack_f.png
  assets/img_archive/two_factor_authentication_manage_users_new.png
  assets/img_archive/two_factor_authentication_new.png
Labels: cla-signed

#2676 BD-1079: Add frequency capping limitation and minor doc cleanup
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/rate-limiting.md
Labels: cla-signed

#2680 BD-1078: Clarification for rate-limiting
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/rate-limiting.md
Labels: cla-signed

#2681 Fix typo in title
  _docs/_api/endpoints/templates/content_blocks_templates/post_create_email_content_block.md
Labels: cla-signed

#2679 Update transcend.md
  _docs/_partners/data_and_infrastructure_agility/data_privacy/transcend.md
Labels: cla-signed

#2682 Minor typo fix in code sample
  _docs/_user_guide/personalization_and_dynamic_content/liquid/operators.md
Labels: cla-signed

#2677 Apply image style guide
  _docs/_api/basics.md
  _docs/_user_guide/engagement_tools/segments/location_targeting.md
  _docs/_user_guide/message_building_by_channel/email/css_inline.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
  assets/img_archive/Create_Polygon.png
  assets/img_archive/Location_Circle.png
  assets/img_archive/Polygon2.png
  assets/img_archive/create-new-key.png
  assets/img_archive/create_link_template.gif
  assets/img_archive/create_link_template.png
  assets/img_archive/create_polygon.png
  assets/img_archive/createsegment2.png
  assets/img_archive/css-inline1.png
  assets/img_archive/css-inline2.png
  assets/img_archive/css-inline3.png
  assets/img_archive/csvexport.png
  assets/img_archive/csvexport2.png
  assets/img_archive/currents-amplitude-edit.png
  assets/img_archive/currents-amplitude-import.png
  assets/img_archive/currents-azure-blob-edit.png
  assets/img_archive/currents-main-page.png
  assets/img_archive/currents-mixpanel-edit.png
  assets/img_archive/currents-mixpanel-import.png
  assets/img_archive/currents-segment-edit.png
  assets/img_archive/email_settings_custom_new.png
  assets/img_archive/filter_recent_location.png
  assets/img_archive/location_circle.png
Labels: cla-signed

#2684 Apply Image Style Guide
  _docs/_help/help_articles/campaigns_and_canvas/conversions_low.md
  _docs/_help/help_articles/campaigns_and_canvas/locations_data_in_campaigns.md
  _docs/_help/help_articles/campaigns_and_canvas/more_people_in_control_group.md
  _docs/_help/help_articles/in-app_messages/in-app_message_impressions_appear_lower_than_expected.md
  _docs/_help/help_articles/in-app_messages/in-app_messages_not_displaying.md
  _docs/_help/help_articles/push/no_push_notification_was_received.md
  _docs/_help/help_articles/segments/segment_showing_0_users.md
  _docs/_help/help_articles/segments/segmentation_logic_with_and_or.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/delivery_types/triggered_delivery.md
  assets/img_archive/ReEligible.png
  assets/img_archive/reevaluate_segment_membership.png
  assets/img_archive/schedule_triggered1.png
  assets/img_archive/schedule_triggered22.png
  assets/img_archive/schedule_triggered32.png
  assets/img_archive/schedule_triggered43.png
  assets/img_archive/schedule_triggered6.png
  assets/img_archive/schedule_triggered7.png
  assets/img_archive/schedule_triggered8.png
  assets/img_archive/schedule_triggered_next_available.png
  assets/img_archive/terminal.png
  assets/img_archive/trouble10.png
  assets/img_archive/trouble15.png
  assets/img_archive/trouble16.png
  assets/img_archive/trouble17.png
  assets/img_archive/trouble2.png
  assets/img_archive/trouble4.png
  assets/img_archive/trouble6.png
  assets/img_archive/trouble7.png
  assets/img_archive/trouble8.png
  assets/img_archive/trouble9.png
  assets/img_archive/web-email-capture.png
Labels: cla-signed

#2685 Minor grammar updates and link fixes
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/microsoft_azure_blob_storage_for_currents.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/ab_testing_with_random_buckets.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/additional_android_best_practices.md
Labels: cla-signed

#2688 BD-1081: Manually add service worker configuration content
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
Labels: cla-signed

#2689 Adding Shortened Link for Race Condition Braze Bite
  _docs/_user_guide/engagement_tools/testing/race_conditions.md
Labels: cla-signed

#2690 Update apple_object.md
  _docs/_api/objects_filters/messaging/apple_object.md
Labels: cla-signed

#2691 Styling Test Page Updates
  _docs/_home/styling_test_page.md
  assets/img_archive/code_snippet.png
Labels: cla-signed

#2686 Apply Image Styling Guide
  _docs/_help/help_articles/campaigns_and_canvas/conversions_low.md
  _docs/_help/help_articles/in-app_messages/in-app_message_impressions_appear_lower_than_expected.md
  _docs/_help/help_articles/in-app_messages/in-app_messages_not_displaying.md
  _docs/_help/help_articles/segments/segment_showing_0_users.md
  _docs/_help/help_articles/segments/segmentation_logic_with_and_or.md
  _docs/_help/help_articles/segments/segmentation_logic_with_negative_or_filters.md
  _docs/_user_guide/administrative/app_settings/developer_console/internal_groups_tab.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/time_based_canvas.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/guidelines_and_tips.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
  assets/img_archive/Hailo_social_email.png
  assets/img_archive/Ideeli_email.png
  assets/img_archive/Livingsocial_email.png
  assets/img_archive/Restaurant_email.png
  assets/img_archive/Ruelala_email.png
  assets/img_archive/S3_AttachPolicy.png
  assets/img_archive/S3_CreatePolicy.png
  assets/img_archive/Saucey_Email.png
  assets/img_archive/preheader_example.png
  assets/img_archive/schedule_delay_after.png
  assets/img_archive/schedule_delay_immediately.png
  assets/img_archive/schedule_delay_in.png
  assets/img_archive/schedule_delay_intelligent.png
  assets/img_archive/schedule_delay_next.png
  assets/img_archive/schedule_designated.png
  assets/img_archive/schedule_immediately.png
  assets/img_archive/schedule_intelligent.png
  assets/img_archive/seed_group_campaign.png
  assets/img_archive/simple_survey_use_case_1.png
  assets/img_archive/simple_survey_use_case_2.png
  assets/img_archive/simple_survey_use_case_4.png
  assets/img_archive/time_based.png
  assets/img_archive/time_delay_after.png
  assets/img_archive/time_delay_immediately.png
  assets/img_archive/time_delay_in.png
  assets/img_archive/time_delay_on_the_next.png
  assets/img_archive/time_designated.png
  assets/img_archive/time_intelligent_timing.png
  assets/img_archive/time_local.png
  assets/img_archive/time_quiet_hours.png
  assets/img_archive/time_reeligibility.png
  assets/img_archive/trouble17.png
  assets/img_archive/us_canada.png
Labels: cla-signed

#2692 Update styling_test_page.md
  _docs/_home/styling_test_page.md
Labels: cla-signed

#2693 Alerts Cleanup for User Guide Section
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
Labels: cla-signed

#2696 Help Articles - YAML Edits
  _docs/_help/help_articles/account/locked_out.md
  _docs/_help/help_articles/api/delete_user.md
  _docs/_help/help_articles/campaigns_and_canvas/canvas_not_sending.md
  _docs/_help/help_articles/campaigns_and_canvas/conversions_low.md
  _docs/_help/help_articles/campaigns_and_canvas/locations_data_in_campaigns.md
  _docs/_help/help_articles/campaigns_and_canvas/more_people_in_control_group.md
  _docs/_help/help_articles/campaigns_and_canvas/not_triggering.md
  _docs/_help/help_articles/campaigns_and_canvas/using_custom_event_properties.md
  _docs/_help/help_articles/campaigns_and_canvas/using_event_logging.md
  _docs/_help/help_articles/content_cards/empty_content_card_feed.md
  _docs/_help/help_articles/data/change_custom_data_type.md
  _docs/_help/help_articles/data/dispatch_id.md
  _docs/_help/help_articles/docs/contribution.md
  _docs/_help/help_articles/docs/hacktober_2019.md
  _docs/_help/help_articles/docs/scroll_bar_overlap.md
  _docs/_help/help_articles/email/html_looks_strange.md
  _docs/_help/help_articles/in-app_messages/in-app_message_impressions_appear_lower_than_expected.md
  _docs/_help/help_articles/in-app_messages/in-app_messages_not_displaying.md
  _docs/_help/help_articles/push/no_push_notification_was_received.md
  _docs/_help/help_articles/push/push_error_codes.md
  _docs/_help/help_articles/push/push_token_migration.md
  _docs/_help/help_articles/segments/my_filter_options_have_changed.md
  _docs/_help/help_articles/segments/over-segmentation.md
  _docs/_help/help_articles/segments/segment_showing_0_users.md
  _docs/_help/help_articles/segments/segmentation_logic_with_and_or.md
  _docs/_help/help_articles/segments/segmentation_logic_with_negative_or_filters.md
Labels: cla-signed

#2699 removed gist-it
  _docs/_developer_guide/platform_integration_guides/web/amp_support.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
Labels: cla-signed

#2702 BD-1082: Clarify data point usage for custom event properties
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/onboarding_with_braze/data_points.md
Labels: cla-signed

#2703 Update ios_15.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_15.md
Labels: cla-signed

#2700 Apply image style guide edits
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_push_notifications.md
  _docs/_user_guide/message_building_by_channel/push/android/notification_ids.md
  _docs/_user_guide/message_building_by_channel/push/android/notification_options.md
  _docs/_user_guide/message_building_by_channel/push/ios/notification_options.md
  assets/img_archive/not_optin.png
  assets/img_archive/notchannclickdropdown.gif
  assets/img_archive/notchannels.png
  assets/img_archive/notgroupclickdropdown.gif
  assets/img_archive/notification_channel_dropdown.png
  assets/img_archive/notification_channels.png
  assets/img_archive/notification_group_dropdown.png
  assets/img_archive/notification_ids.png
  assets/img_archive/personalized_testing.png
  assets/img_archive/personalized_testing_custom.png
  assets/img_archive/personalized_testing_select.png
  assets/img_archive/test-in-app.png
  assets/img_archive/testemail.png
  assets/img_archive/testwebpush.png
Labels: cla-signed

#2704 Add React Native sample app page
  _docs/_developer_guide/platform_integration_guides/react_native/sample_app.md
Labels: cla-signed

#2705 FB and Google Audience Sync Updates
  _docs/_partners/canvas_steps/facebook_audience_sync.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  assets/img/fb_audience_sync/google_sync10.png
  assets/img/fb_audience_sync/google_sync11.png
  assets/img/fb_audience_sync/google_sync7.png
  assets/img/fb_audience_sync/google_sync8.png
  assets/img/google_sync/google_sync11.png
  assets/img/google_sync/google_sync7.png
  assets/img/google_sync/google_sync8.png
Labels: cla-signed

#2709 BD-1088: Clarify segment membership calculation with all apps selected
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
Labels: cla-signed

#2711 BD-1090: Add SMS/MMS to description for Subscription Groups
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#2710 BD-1089: Add note on _update_existing_only to Event Object
  _docs/_api/objects_filters/event_object.md
  _docs/_api/objects_filters/user_attributes_object.md
Labels: cla-signed

#2707 BD-1087: Update tags.md with steps for nested tags
  _docs/_user_guide/administrative/app_settings/manage_app_group/tags.md
  assets/img_archive/tag_nested.png
Labels: cla-signed

#2713 Update Analytics article titles
  _docs/_developer_guide/platform_integration_guides/android/analytics/disabling_tracking.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/social_data_tracking.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_sessions.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/uninstall_tracking.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/disabling_tracking.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/social_data_tracking.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/tracking_sessions.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/uninstall_tracking.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/tracking_sessions.md
Labels: cla-signed

#2712 BD-1091: Clarify sha2 and sha256 support
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
Labels: cla-signed

#2714 Apply image styling guide edits
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/troubleshooting.md
  _docs/_user_guide/data_and_analytics/custom_data/pre-populating_custom_data.md
  _docs/_user_guide/message_building_by_channel/email/templates/html_email_template.md
  assets/img_archive/Push_Window8_Toast.png
  assets/img_archive/Push_Windows_Universal_Toast.png
  assets/img_archive/prepopulate_add.png
  assets/img_archive/prepopulate_page.png
  assets/img_archive/prov_profile_refresh_step1.png
  assets/img_archive/prov_profile_refresh_step2.png
  assets/img_archive/push_cert_upload.png
  assets/img_archive/upload_html_template.gif
Labels: cla-signed

#2715 Data Point Calculation Updated
  _docs/_user_guide/onboarding_with_braze/data_points.md
Labels: cla-signed

#2716 Update broken_redirect_list.js
  assets/js/broken_redirect_list.js
Labels: cla-signed

#2718 Fix typo in triggered_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md
Labels: cla-signed

#2698 Apply Image Styling Guide
  _docs/_developer_guide/platform_integration_guides/web/content_cards/read_unread_indicators.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _docs/_user_guide/engagement_tools/segments/segment_funnels.md
  assets/img_archive/RegistrationProblem.png
  assets/img_archive/Segment_Insights_Events1.png
  assets/img_archive/Segment_Insights_Info.png
  assets/img_archive/Segment_Language_Insights.png
  assets/img_archive/Segment_Segment_Insights.png
  assets/img_archive/Select_Channel.png
  assets/img_archive/push_changelog.png
  assets/img_archive/rate_limit_daily.png
  assets/img_archive/rate_limiting_overview_2.png
  assets/img_archive/reeligibility_controls_campaign.png
  assets/img_archive/remote_notification.png
  assets/img_archive/segment_insights.png
  assets/img_archive/segment_step4.png
  assets/img_archive/target_page.png
Labels: cla-signed
