Repository braze-inc/braze-docs, pull requests merged in 2021-06, with the labels that each got.

#2191 Update data_points.md
  _docs/_user_guide/onboarding_with_braze/data_points.md
Labels: cla-signed

#2192 BD-946: Remove note on message queue
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/change_your_canvas_after_launch.md
Labels: cla-signed

#2196 Amazon Personalize Formatting Fix
  _docs/_hidden/private_betas/adobe.md
  _docs/_hidden/private_betas/shopify.md
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
  _docs/_hidden/wip_partnerships/partnership_template.md
  _docs/_home/templates/partner_page_template.md
  _docs/_home/templates/partner_page_template_video.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/fivetran.md
  _docs/_partners/message_orchestration/additional_channels/calendar/rokt_calendar.md
  _docs/_partners/message_orchestration/additional_channels/messaging/messenger.md
  _docs/_partners/message_orchestration/additional_channels/mobile_wallet/passkit.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/talonone.md
  _docs/_partners/message_orchestration/learning/edume.md
  _docs/_partners/message_personalization/dynamic_content/amazon_personalize.md
  _docs/_partners/message_personalization/dynamic_content/certona.md
  _docs/_partners/message_personalization/dynamic_content/liftigniter.md
  _docs/_partners/message_personalization/dynamic_content/playable.md
  _docs/_partners/message_personalization/localization/crowdin.md
  _docs/_partners/message_personalization/localization/transifex.md
  _docs/_partners/message_personalization/location/gimbal.md
Labels: cla-signed

#2195 [SDK-1443] iOS Docs SDWebImage manual integration
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options.md
Labels: cla-signed

#2003 Content Cards customizability update documentation related to release
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/data_model.md
  _docs/_hidden/other/airship_migration.md
Labels: cla-signed

#2198 Update FB App Requirement version
  _docs/_partners/canvas_steps/facebook_audience_sync.md
Labels: cla-signed

#2199 Remove genymotion reference
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/troubleshooting.md
Labels: cla-signed

#2200 BD-932: Update subscription/status/get endpoint
  _docs/_api/endpoints/subscription_groups/get_list_user_subscription_group_status.md
Labels: cla-signed

#2203 Metadata fix
  _docs/_api/identifier_types.md
Labels: cla-signed

#2205 Link Fixes
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/optional_gaid_collection.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
  _docs/_help/release_notes/2017/january.md
  _docs/_partners/message_orchestration/additional_channels/calendar/rokt_calendar.md
  _docs/_partners/message_orchestration/additional_channels/direct_mail/inkit.md
  _docs/_partners/message_orchestration/additional_channels/messaging/messenger.md
  _docs/_partners/message_orchestration/attribution/kochava.md
  _docs/_partners/message_personalization/location/bluedot.md
  _docs/_user_guide/introduction.md
  _docs/_user_guide/message_building_by_channel/push/web.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/public_apis.md
  _docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
Labels: cla-signed

#2206 BD-948: Link fix
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
Labels: cla-signed

#2208 BD-947: IP Warming Notifications Removed
  _docs/_user_guide/onboarding_with_braze/email_setup/ip_warming.md
Labels: cla-signed

#2211 Correct key field for SMS analytics
  _docs/_api/endpoints/export/campaigns/get_campaign_analytics.md
Labels: cla-signed

#2214 Update Settings pages for style and clarity
  _docs/_user_guide/administrative/app_settings/manage_app_group/app_group_management.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/custom_event_and_attribute_management.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/push_ttl_settings.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/tags.md
Labels: cla-signed

#2210 SDK-1610 - updated kotlin android user calls
  _docs/_developer_guide/platform_integration_guides/android/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/social_data_tracking.md
  _includes/archive/aliasing.md
Labels: cla-signed

#2209 updated android runtime config docs
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/runtime_configuration.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/accessibility.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/html_rendered_push.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/runtime_configuration.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/fireos/initial_sdk_setup/accessibility.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
Labels: cla-signed

#2218 Add files via upload
  assets/img/iam/iam-survey3.png
Labels: cla-signed

#2217 iam survey images
  assets/img/iam/iam-survey2.png
  assets/img/iam/iam-survey3.png
Labels: cla-signed

#2213 Radar Connected Content Documentation Updates
  _docs/_partners/message_personalization/location/radar.md
  assets/img/radar_example.png
Labels: Braze Partnerships, cla-signed

#2219 Update data_models.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/data_models.md
Labels: cla-signed

#2220 Add note to Intelligent Selection
  _docs/_user_guide/intelligence/intelligent_selection.md
Labels: cla-signed

#2216 BD-950, BD-951
  _docs/_user_guide/engagement_tools/canvas/canvas_components.md
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
Labels: cla-signed

#2222 Update sdk_authentication.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
Labels: cla-signed

#2223 Add basic Algolia Analytics
  _includes/html_include.html
  _includes/search_page.html
  assets/js/algolia_header_search.js
  assets/js/algolia_main_search.js
  assets/js/algolia_search.js
  assets/js/documents.js
Labels: cla-signed

#2224 Add Algolia Analytics to support page
  _docs/_hidden/other/support_contact.md
Labels: cla-signed

#2226 Fix algolia cookie duration
  assets/js/documents.js
Labels: cla-signed

#2227 Updates for style and clarity
  _docs/_user_guide/personalization_and_dynamic_content/deep_linking_to_in-app_content.md
  _docs/_user_guide/personalization_and_dynamic_content/emoji_messaging.md
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
  assets/img/promocodes/promocode2.png
  assets/img/promocodes/promocode3.png
  assets/img_archive/accessing_emoji_3.gif
  assets/img_archive/iam_utm_tags.png
  assets/img_archive/news_feed_utm_tags.png
  assets/img_archive/push_utm_tags.png
Labels: cla-signed

#2225 Update global_control_group.md
  _docs/_user_guide/engagement_tools/testing/global_control_group.md
Labels: cla-signed

#2221 Update data_models.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/data_models.md
Labels: cla-signed

#2230 Dev Guide Audit - Pt. 3
  _docs/_developer_guide/platform_integration_guides/android/news_feed/overview.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/advanced_settings.md
  _docs/_developer_guide/platform_integration_guides/cordova/android_and_fireos.md
  _docs/_developer_guide/platform_integration_guides/cordova/content_cards.md
  _docs/_developer_guide/platform_integration_guides/cordova/ios.md
  _docs/_developer_guide/platform_integration_guides/cordova/ios/cordova_integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/content_cards/data_models.md
  _docs/_developer_guide/platform_integration_guides/fireos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/fireos/news_feed/overview.md
  _docs/_developer_guide/platform_integration_guides/fireos/push_notifications/advanced_settings.md
  _docs/_developer_guide/platform_integration_guides/fireos/push_notifications/push_story.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/content_cards.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/content_cards.md
  _docs/_developer_guide/platform_integration_guides/unity/Analytics/logging_custom_events.md
  _docs/_help/release_notes/deprecations.md
Labels: cla-signed

#2232 BD-952: Link Fixes
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/initial_sdk_setup/android_sdk_integration.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2021/may.md
Labels: cla-signed

#2233 Update Connected Content section for style
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/connected_content_retries.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/public_apis.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/user_profile_fields_connected_content.md
Labels: cla-signed

#2235 Fix some search css issues
  assets/css/_header_search.scss
Labels: cla-signed

#2236 Remove javascript error from api page layout
  _layouts/api_page.html
  assets/css/_header_search.scss
Labels: cla-signed

#2234 Remove webinars from Help section
  _docs/_help/home.md
  _docs/_help/webinars.md
  _docs/_help/webinars/ab_and_multivariate_testing.md
  _docs/_help/webinars/building_a_strategy_for_android_oreo.md
  _docs/_help/webinars/canvas_entry_steps_and_conditions.md
  _docs/_help/webinars/canvas_lifecycle_testing.md
  _docs/_help/webinars/creating_segments_and_sending_campaigns.md
  _docs/_help/webinars/email_101.md
  _docs/_help/webinars/importing_user_profiles.md
  _docs/_help/webinars/measuring_success_with_braze_data.md
  _docs/_help/webinars/overview.md
  _docs/_help/webinars/personalization_and_liquid.md
  _docs/_help/webinars/sending_test_messages.md
  _docs/_help/webinars/troubleshooting_bootcamp.md
  assets/img/icons/icon-document-ribbon.png
  assets/img/icons/icon-lab.png
  assets/img/icons/icon-news.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#2212 [SDK-1443] iOS Docs SDWebImage remove extra steps
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options.md
Labels: cla-signed

#2238 Removing gendered pronouns
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_home/static_video.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/voucherify.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/time_based_campaign.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/time_based_canvas.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#2237 BD-953: Clarify the Numeric data type
  _docs/_api/objects_filters/event_object.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
Labels: cla-signed

#2240 BD-954: Fix incorrect option name
  _docs/_developer_guide/platform_integration_guides/web/smart_tvs.md
Labels: cla-signed

#2242 Update User Guide popular topics
  _docs/_user_guide/introduction.md
Labels: cla-signed

#2241 Leftover Deploy - June 10, 2021
  _docs/_api/objects_filters/event_object.md
  _docs/_api/objects_filters/user_attributes_object.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options.md
  _docs/_developer_guide/platform_integration_guides/web/smart_tvs.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_help/home.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2021/may.md
  _docs/_help/webinars.md
  _docs/_help/webinars/ab_and_multivariate_testing.md
  _docs/_help/webinars/building_a_strategy_for_android_oreo.md
  _docs/_help/webinars/canvas_entry_steps_and_conditions.md
  _docs/_help/webinars/canvas_lifecycle_testing.md
  _docs/_help/webinars/creating_segments_and_sending_campaigns.md
  _docs/_help/webinars/email_101.md
  _docs/_help/webinars/importing_user_profiles.md
  _docs/_help/webinars/measuring_success_with_braze_data.md
  _docs/_help/webinars/overview.md
  _docs/_help/webinars/personalization_and_liquid.md
  _docs/_help/webinars/sending_test_messages.md
  _docs/_help/webinars/troubleshooting_bootcamp.md
  _docs/_home/static_video.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/voucherify.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/time_based_campaign.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/time_based_canvas.md
  _docs/_user_guide/introduction.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/connected_content_retries.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/public_apis.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/user_profile_fields_connected_content.md
  _layouts/api_page.html
  assets/css/_header_search.scss
  assets/img/icons/icon-document-ribbon.png
  assets/img/icons/icon-lab.png
  assets/img/icons/icon-news.png
  assets/js/broken_redirect_list.js
Labels: Deploy, cla-signed

#2243 Add helpful resources to home page
  _docs/_docs_pages/index.md
  _layouts/doc_guide.html
  assets/css/_doc_guide.scss
Labels: cla-signed

#2244 Update initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
Labels: cla-signed

#2246 Link and redirect fix
  _docs/_developer_guide/platform_integration_guides/ios.md
  _docs/_developer_guide/platform_wide/tv_and_ott.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#2247 Fix some layout issues
  _layouts/doc_guide.html
  assets/css/_doc_guide.scss
  assets/css/_docs_search.scss
Labels: cla-signed

#2248 Update sdk_authentication.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
Labels: cla-signed

#2249 Update advanced_settings.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/advanced_settings.md
Labels: cla-signed

#2250 BD-956: mParticle Link Update
  _docs/_help/release_notes/2019/april.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle.md
  _docs/_user_guide/data_and_analytics/braze_currents.md
Labels: cla-signed

#2215 Adding Purchase Events page
  _docs/_api/objects_filters/purchase_object.md
  _docs/_user_guide/data_and_analytics/custom_data.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  assets/img/purchase1.png
  assets/img/purchase2.png
  assets/img/purchase3.png
  assets/img/purchase4.png
  assets/img/purchase5.png
Labels: cla-signed

#2231 Link Aliasing Beta Documentation
  _docs/_hidden/private_betas/amphtml.md
  _docs/_hidden/private_betas/canvas_in-app_messages.md
  _docs/_hidden/private_betas/get_campaign_url_info.md
  _docs/_hidden/private_betas/get_canvas_url_info.md
  _docs/_hidden/private_betas/link_aliasing.md
  _docs/_hidden/private_betas/nested_object_support.md
  _docs/_hidden/private_betas/view_pii.md
  assets/img/link_aliasing_click_table.png
  assets/img/link_aliasing_composer.png
Labels: cla-signed

#2245 Update content_security_policy.md
  _docs/_developer_guide/platform_integration_guides/web/content_security_policy.md
Labels: cla-signed

#2252 Updating Typo in JS initialization Code
  _docs/_developer_guide/platform_wide/sdk_authentication.md
Labels: cla-signed

#2254 android broken link
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/advanced_settings.md
Labels: cla-signed

#2253 BD-957: Update Delay Step GIF
  assets/img/canvas_delay.gif
Labels: cla-signed

#2255 BD-959: Remove Incorrect Segment Instructions
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
Labels: cla-signed

#2257 Update advanced_settings.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/advanced_settings.md
Labels: cla-signed

#2258 BD-955: Add Kafka ad_id collection information
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#2259 BD-960: Fix broken links and image sizing
  _docs/_help/best_practices/in-app_messages/previous_in-app_message_generations.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
Labels: cla-signed

#2260 Permalink Fix
  _docs/_hidden/private_betas/amphtml.md
  _docs/_hidden/private_betas/canvas_in-app_messages.md
  _docs/_hidden/private_betas/get_campaign_url_info.md
  _docs/_hidden/private_betas/get_canvas_url_info.md
  _docs/_hidden/private_betas/link_aliasing.md
  _docs/_hidden/private_betas/nested_object_support.md
  _docs/_hidden/private_betas/shopify.md
  _docs/_hidden/private_betas/twilio.md
  _docs/_hidden/private_betas/view_pii.md
Labels: cla-signed

#2261 Fix broken links and redirects
  _docs/_user_guide/administrative/access_braze/single_sign_on.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#2256 Deploy - June 15, 2021
  _docs/_api/endpoints/export/campaigns/get_campaign_analytics.md
  _docs/_api/objects_filters/purchase_object.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/advanced_settings.md
  _docs/_developer_guide/platform_integration_guides/ios.md
  _docs/_developer_guide/platform_integration_guides/web/content_security_policy.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
  _docs/_developer_guide/platform_wide/tv_and_ott.md
  _docs/_docs_pages/index.md
  _docs/_help/best_practices/in-app_messages/previous_in-app_message_generations.md
  _docs/_help/release_notes/2019/april.md
  _docs/_hidden/private_betas/get_campaign_url_info.md
  _docs/_hidden/private_betas/get_canvas_url_info.md
  _docs/_hidden/private_betas/link_aliasing.md
  _docs/_hidden/private_betas/shopify.md
  _docs/_hidden/private_betas/twilio.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _docs/_user_guide/administrative/access_braze/single_sign_on.md
  _docs/_user_guide/data_and_analytics/braze_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/custom_data.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  _layouts/doc_guide.html
  assets/css/_doc_guide.scss
  assets/css/_docs_search.scss
  assets/img/canvas_delay.gif
  assets/img/link_aliasing_click_table.png
  assets/img/link_aliasing_composer.png
  assets/img/purchase1.png
  assets/img/purchase2.png
  assets/img/purchase3.png
  assets/img/purchase4.png
  assets/img/purchase5.png
  assets/js/broken_redirect_list.js
Labels: Deploy, cla-signed

#2263 Partner Template Tweaks
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
Labels: cla-signed

#2266 Clarify iOS Action Button documentation
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/customization/action_buttons.md
Labels: cla-signed

#2268 update txn email docs
  _docs/_api/transactional_message_api_campaign.md
Labels: cla-signed

#2269 Removal of US-03 and EU-01 Implementation Differences
  _docs/_api/basics.md
  _docs/_developer_guide/eu01_us3_sdk_implementation_differences.md
  _docs/_developer_guide/eu01_us3_sdk_implementation_differences/for_android.md
  _docs/_developer_guide/eu01_us3_sdk_implementation_differences/for_ios.md
  _docs/_developer_guide/eu01_us3_sdk_implementation_differences/for_web.md
  _docs/_developer_guide/eu01_us3_sdk_implementation_differences/overview.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/tvos/initial_sdk_setup.md
  _includes/archive/apple/initial_setup.md
Labels: cla-signed

#2272 Link Fix
  _docs/_developer_guide/platform_integration_guides/xamarin/android_and_fireos/push_notifications.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#2271 Transactional Email API Campaign Endpoint and Doc GA
  _docs/_api/api_campaigns.md
  _docs/_api/api_campaigns/api_campaigns.md
  _docs/_api/api_campaigns/transactional_api_campaign.md
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  _docs/_user_guide/message_building_by_channel/email/transactional_message_api_campaign.md
Labels: cla-signed

#2274 Update Transactional Endpoint Pt. 2
  _docs/_api/api_campaigns/transactional_api_campaign.md
Labels: cla-signed

#2188 Content Card Implementation Guide Update
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/implementation_guide.md
  assets/img/cc_implementation/discount.png
  assets/img/cc_implementation/discount2.png
  assets/img/cc_implementation/full_page.png
  assets/img/cc_implementation/html_webview.png
  assets/img/cc_implementation/message_center.png
  assets/img/cc_implementation/supplementary.png
  assets/img/cc_implementation/supplementary_content.png
Labels: cla-signed

#2279 Leftover Deploy - June 17, 2021
  _config.yml
  _docs/_api/api_campaigns.md
  _docs/_api/api_campaigns/api_campaigns.md
  _docs/_api/api_campaigns/transactional_api_campaign.md
  _docs/_api/basics.md
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  _docs/_developer_guide/eu01_us3_sdk_implementation_differences.md
  _docs/_developer_guide/eu01_us3_sdk_implementation_differences/for_android.md
  _docs/_developer_guide/eu01_us3_sdk_implementation_differences/for_ios.md
  _docs/_developer_guide/eu01_us3_sdk_implementation_differences/for_web.md
  _docs/_developer_guide/eu01_us3_sdk_implementation_differences/overview.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/customization/action_buttons.md
  _docs/_developer_guide/platform_integration_guides/tvos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/xamarin/android_and_fireos/push_notifications.md
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/change_your_canvas_after_launch.md
  _docs/_user_guide/message_building_by_channel/email/transactional_message_api_campaign.md
  _includes/archive/apple/initial_setup.md
  _plugins/urlnavmenu_generator.rb
  assets/img/cc_implementation/discount.png
  assets/img/cc_implementation/discount2.png
  assets/img/cc_implementation/full_page.png
  assets/img/cc_implementation/html_webview.png
  assets/img/cc_implementation/message_center.png
  assets/img/cc_implementation/supplementary.png
  assets/img/cc_implementation/supplementary_content.png
  assets/js/broken_redirect_list.js
Labels: Deploy, cla-signed

#2265 Update popular articles for style
  _docs/_user_guide/data_and_analytics/braze_currents.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
  assets/img/email_capture_config.png
Labels: cla-signed

#2281 Update integration.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
Labels: cla-signed

#2280 BD-963: Add Cohort Import error codes table
  _docs/_partners/isv_partners/cohort_import.md
Labels: cla-signed

#2283 BD-965: Remove note to contact CSM for silent push notifications
  _docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
Labels: cla-signed

#2127 BD-925: Amperity Integration - MERGE 6/22
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/amerpity.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _docs/_partners/home.md
  _docs/_partners/message_orchestration/attribution/vizbee_for_tv_deeplinking.md
  _docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_stories.md
  assets/img/amperity/activate1.png
  assets/img/amperity/activate2.png
  assets/img/amperity/amperity2.png
  assets/img/amperity/amperity3.png
  assets/img/amperity/amperity4.png
  assets/img/amperity/amperity5.png
  assets/img/amperity/destinationconfiguration.png
Labels: Braze Partnerships, cla-signed, release notes

#2285 Fixing capitalization for custom events and custom attributes
  _docs/_api/api_key.md
  _docs/_api/objects_filters/event_object.md
  _docs/_api/objects_filters/user_attributes_object.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/android_google_tag_manager.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/beacon_integration.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/beacon_integration.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/beacon_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/unity/Analytics/logging_custom_events.md
  _docs/_developer_guide/platform_integration_guides/unity/Analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/unity/Analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_help/help_articles/campaigns_and_canvas/using_custom_event_properties.md
  _docs/_help/help_articles/segments/segment_showing_0_users.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_partners/message_personalization/location/gimbal.md
  _docs/_partners/message_personalization/location/neura_actions.md
  _docs/_user_guide/administrative/app_settings/manage_app_group.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/custom_event_and_attribute_management.md
  _docs/_user_guide/data_and_analytics/configuring_reporting.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_custom_event_data.md
  _docs/_user_guide/data_and_analytics/user_data_collection/collection_use_case.md
  _docs/_user_guide/data_and_analytics/user_data_collection/data_collected_by_default.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/conversion_events.md
  _docs/_user_guide/engagement_tools/segments/using_user_search.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
Labels: cla-signed

#2284 BD-964: Add examples for referencing custom attributes in conditional logic
  _docs/_user_guide/personalization_and_dynamic_content/liquid/conditional_logic.md
  assets/img_archive/custom_attribute_data_type.png
Labels: cla-signed

#2278 Nexla Partnership Docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/nexla.md
  _docs/_partners/home.md
Labels: Braze Partnerships, cla-signed

#2282 DIY Partnership Doc Edit
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/channel_extensions.md
  assets/img/digioh/1.png
  assets/img/digioh/2.png
  assets/img/digioh/3.png
  assets/img/digioh/4.png
  assets/img/digioh/pref_pop_examples.png
Labels: cla-signed

#2277 Digioh Partner Documentation
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/channel_extensions.md
  _docs/_partners/message_orchestration/channel_extensions/surveys.md
  _docs/_partners/message_orchestration/channel_extensions/surveys/digioh.md
Labels: Braze Partnerships, cla-signed

#2291 Clarify funnel report conversion timing window
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/campaign_funnel_report.md
  _docs/_user_guide/engagement_tools/canvas/canvas_funnel_reports.md
Labels: cla-signed

#2287 BD-966: Clarify `broadcast` parameter
  _docs/_api/endpoints/messaging/send_messages/post_send_messages.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
  _docs/_api/parameters.md
Labels: cla-signed

#2288 Add additional hmac liquid filters
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters.md
Labels: cla-signed

#2294 Removing docs from Algolia indexing
  _docs/_home/metadata.md
  _docs/_home/static_video.md
  _docs/_home/styling_test_page.md
  _docs/_home/templates.md
Labels: cla-signed

#2297 trivial misprint: visable -> visible
  _docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#2296 Make nullable params optional
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
Labels: cla-signed

#2299 catchall unity docs updates
  _docs/_developer_guide/platform_integration_guides/unity/android/sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/unity/content_cards.md
  _docs/_developer_guide/platform_integration_guides/unity/in-app_messaging.md
Labels: cla-signed

#2301 SDK-1568 - unity adm docs
  _docs/_developer_guide/platform_integration_guides/fireos/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/unity/android/adm_push_notifications.md
  _docs/_developer_guide/platform_integration_guides/unity/android/push_notifications.md
Labels: cla-signed

#2303 Segment Link Fix
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
Labels: cla-signed

#2304 BD-968: Clarify end date for scheduled messaging
  _docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/delivery_types/scheduled_delivery.md
Labels: cla-signed

#2306 Typo in Rudderstack Doc
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack.md
Labels: cla-signed

#2292 BD-961: Clarify mParticle Integration Instructions
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle.md
Labels: cla-signed

#2309 Add logContentCardClicked to RN and Cordova docs
  _docs/_developer_guide/platform_integration_guides/cordova/content_cards.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/content_cards.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/content_cards.md
Labels: cla-signed

#2308 Clarify case sensitivity for CSV imports
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Labels: cla-signed

#2310 BD-969: Liquid Syntax Fix
  _docs/_hidden/private_betas/nested_object_support.md
Labels: cla-signed

#2307 Fixing serialization example
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
Labels: cla-signed

#2312 BD-971: Add warning regarding naming custom attributes using Braze's reserved keys
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/unity/Analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
Labels: cla-signed

#2313 Add 'Teams' Braze Bite
  _docs/_user_guide/administrative/manage_your_braze_users/teams.md
Labels: cla-signed

#2315 Revert "BD-969: Liquid Syntax Fix"
  _docs/_hidden/private_betas/nested_object_support.md
Labels: cla-signed

#2293 Update docs for Nested Event Property GA — MERGE 6/29
  _docs/_api/objects_filters/event_object.md
  _docs/_api/objects_filters/purchase_object.md
  _docs/_user_guide/data_and_analytics/custom_data/nested_object_support.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#2316 Revert "BD-971: Add warning regarding naming custom attributes using Braze's reserved keys"
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/fireos/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/unity/Analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
Labels: cla-signed

#2318 Update email_settings.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  assets/open_pixel.png
Labels: cla-signed

#2321 Liquid App Group Version Bite
  _docs/_developer_guide/platform_wide/app_group_configuration.md
  _docs/_hidden/private_betas/link_aliasing.md
Labels: cla-signed

#2319 SDK-1608 - added ott docs for android/fireOS
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/ott_devices.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/ott_devices.md
  _includes/archive/android/in_app_messages/ott_iam.md
Labels: cla-signed

#2323 Update overview.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/overview.md
Labels: cla-signed

#2314 July 2021 Release Notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2021.md
  _docs/_help/release_notes/2021/july.md
Labels: cla-signed

#2324 BD-973: Fix typo
  _docs/_help/help_articles/push/no_push_notification_was_received.md
  _docs/_user_guide/data_and_analytics.md
Labels: cla-signed

#2326 Update Facebook API maximum version to v11
  _docs/_partners/canvas_steps/facebook_audience_sync.md
Labels: cla-signed

#2322 BD-911: Custom Android In-App Review Prompts
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
Labels: cla-signed

#2325 AppsFlyer - Partner Docs
  _docs/_partners/message_orchestration/attribution/appsflyer.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer_audiences.md
  assets/img/appsflyer_audiences/appsflyer_braze_connection.png
  assets/img/appsflyer_audiences/appsflyer_cohorts_as_filter.png
  assets/img/appsflyer_audiences/appsflyer_data_import_key.png
Labels: Braze Partnerships, cla-signed

#2327 Release Notes Pt. 2
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2021/july.md
  _docs/_partners/message_orchestration/attribution.md
  _docs/_partners/message_orchestration/attribution/appsflyer.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer_audiences.md
Labels: cla-signed

#2328 Update simple_survey.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
Labels: cla-signed

#2329 BD-976: Add Liquid Reference to Custom Footer Documentation
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
Labels: cla-signed

#2320 Deploy - June 29, 2021
  _docs/_api/objects_filters/event_object.md
  _docs/_api/objects_filters/purchase_object.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/ott_devices.md
  _docs/_developer_guide/platform_integration_guides/cordova/content_cards.md
  _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/ott_devices.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/overview.md
  _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/content_cards.md
  _docs/_developer_guide/platform_integration_guides/react_native/ios/content_cards.md
  _docs/_developer_guide/platform_wide/app_group_configuration.md
  _docs/_help/help_articles/push/no_push_notification_was_received.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2021.md
  _docs/_help/release_notes/2021/july.md
  _docs/_hidden/private_betas/link_aliasing.md
  _docs/_partners/canvas_steps/facebook_audience_sync.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack.md
  _docs/_partners/message_orchestration/attribution.md
  _docs/_partners/message_orchestration/attribution/appsflyer.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer_audiences.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  _docs/_user_guide/administrative/manage_your_braze_users/teams.md
  _docs/_user_guide/data_and_analytics.md
  _docs/_user_guide/data_and_analytics/custom_data/nested_object_support.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
  _includes/archive/android/in_app_messages/ott_iam.md
  assets/img/appsflyer_audiences/appsflyer_braze_connection.png
  assets/img/appsflyer_audiences/appsflyer_cohorts_as_filter.png
  assets/img/appsflyer_audiences/appsflyer_data_import_key.png
  assets/js/broken_redirect_list.js
  assets/open_pixel.png
Labels: Deploy, cla-signed

#2331 BD-977: Radar Link Update
  _docs/_partners/message_personalization/location/radar.md
Labels: cla-signed

#2333 BD-978: Add details on max length of custom attribute arrays
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
Labels: cla-signed

#2335 Alias Link Fix
  _docs/_user_guide/data_and_analytics/custom_data/nested_object_support.md
Labels: cla-signed

#2336 Deploy Pt. 2 - June 30, 2021
  _docs/_help/help_articles/data/dispatch_id.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_user_profile_api.md
  _docs/_partners/message_personalization/location/radar.md
  _docs/_user_guide/data_and_analytics/braze_currents/available_partners.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/nested_object_support.md
  assets/js/broken_redirect_list.js
Labels: Deploy

#2339 BD-980: Clarify unique impressions incrementation
  _docs/_user_guide/data_and_analytics/report_metrics.md
Labels: cla-signed

#2334 BD-974: Add simple survey use cases
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
  assets/img/iam/color-theme-picker.png
  assets/img/iam/iam-survey2.png
  assets/img_archive/simple_survey_use_case_1.png
  assets/img_archive/simple_survey_use_case_2.png
  assets/img_archive/simple_survey_use_case_3.png
  assets/img_archive/simple_survey_use_case_4.png
Labels: cla-signed
