Repository braze-inc/braze-docs, pull requests merged in 2022-05, with the labels that each got.

#3522 BD-1360: Update Success and Support Services Handbook FY23
  assets/download_file/Braze_Success_and_Support_Services_Handbook_23.pdf
Labels: cla-signed

#3523 Add local to tab
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
Labels: cla-signed

#3525 June 2022 Release Notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2022.md
  _docs/_help/release_notes/2022/june.md
Labels: cla-signed

#3504 BD-1367: Add year to sf_created_at note
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake/sample_queries.md
Labels: cla-signed

#3506 web z-index
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization/custom_styling.md
Labels: cla-signed

#3318 BD-1271: Button Actions
  _docs/_developer_guide/platform_wide/braze_actions.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
  assets/img_archive/push_primer_button_behavior.png
  assets/img_archive/push_primer_iam.png
  assets/img_archive/push_primer_trigger.png
Labels: cla-signed

#3526 Fix main search results overlap
  assets/css/_docs_search.scss
Labels: cla-signed

#3528 BD-1377: Remove extraneous brackets from request body in transactional email endpoint
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
Labels: cla-signed

#3524 Remove images of text
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_home/static_video.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  assets/img_archive/custom_event_properties_gaming.png
  assets/img_archive/webhook_test_send.png
Labels: cla-signed

#3519 BD-1358: Update Message Steps doc GA
  _docs/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
Labels: cla-signed

#3529 BD-1378: Update catalogs upload image
  assets/img_archive/catalog_CSV_upload.png
Labels: cla-signed

#3527 BD-1370: Clarify dispatch_id in response details of /campaigns/trigger/send
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
Labels: cla-signed

#3531 Move Campaign approval doc
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/archiving_campaigns.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_alerts.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_approval.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/change_your_campaign_after_launch.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/duplicating_segments_and_campaigns.md
Labels: cla-signed

#3532 Add campaign approval to release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2022/june.md
Labels: cla-signed

#3533 Remove Canvas LAB Playbook mention
  _docs/_user_guide/engagement_tools/canvas/canvas_components.md
Labels: cla-signed

#3534 Deploy Pt. 2 - May 3, 2022
  _docs/_user_guide/engagement_tools/canvas/canvas_components.md
Labels: cla-signed

#3457 Rehaul HTML preview and IAM customization
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize/color_profiles_and_css.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize/email_capture_form.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize/html_in-app_messages.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize/modal_with_css.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize/video.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/preview.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#3536 Update soft_push_prompt.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/soft_push_prompt.md
Labels: cla-signed

#3538 Clarify link templates for link aliasing
  _docs/_hidden/private_betas/link_aliasing.md
Labels: cla-signed

#3539 Clarify feature availability for Persistent entry properties
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md
Labels: cla-signed

#3541 web versions
  _docs/_developer_guide/platform_wide/braze_actions.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
Labels: cla-signed

#3540 BD-1206: Inbox Vision for DND GA
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _docs/_user_guide/message_building_by_channel/email/inbox_vision.md
  assets/img_archive/email_spam_testing.png
  assets/img_archive/inboxvision1.png
  assets/img_archive/inboxvision2.png
  assets/img_archive/inboxvision4.png
Labels: cla-signed

#3537 BD-1379: Create Cloning Canvases doc
  _docs/_hidden/private_betas/canvas_v2_101.md
  _docs/_hidden/private_betas/canvas_v2_cloning.md
  assets/img_archive/clone_to_v2_dashboard.png
  assets/img_archive/clone_to_v2_modal.png
  assets/img_archive/clone_to_v2_workflow.png
Labels: cla-signed

#3542 Leftover Deploy - May 5, 2022
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/soft_push_prompt.md
  _docs/_developer_guide/platform_wide/braze_actions.md
  _docs/_hidden/private_betas/canvas_v2_101.md
  _docs/_hidden/private_betas/canvas_v2_cloning.md
  _docs/_hidden/private_betas/link_aliasing.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _docs/_user_guide/message_building_by_channel/email/inbox_vision.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize/color_profiles_and_css.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize/email_capture_form.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize/html_in-app_messages.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize/modal_with_css.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize/video.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/preview.md
  _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
  assets/img_archive/clone_to_v2_dashboard.png
  assets/img_archive/clone_to_v2_modal.png
  assets/img_archive/clone_to_v2_workflow.png
  assets/img_archive/email_spam_testing.png
  assets/img_archive/inboxvision1.png
  assets/img_archive/inboxvision2.png
  assets/img_archive/inboxvision4.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#3544 Add kotlin coroutines dependency
  _docs/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md
Labels: cla-signed

#3492 Hightouch Cohort Import Docs - MERGE 5/9
  _docs/_partners/data_and_infrastructure_agility/analytics/kubit.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/amplitude.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/appsflyer.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/hightouch.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/kubit.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/mixpanel.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/tinyclues.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/hightouch.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer_audiences.md
  assets/img/hightouch/cohort1.png
  assets/img/hightouch/cohort2.png
  assets/img/hightouch/cohort3.png
  assets/img/hightouch/cohort4.png
  assets/img/hightouch/data_import_key.png
Labels: status: on hold / do not merge, status: done, cla-signed, Braze Partnerships

#3518 Survicate Partnership Docs - MERGE 5/9
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/channel_extensions.md
  _docs/_partners/message_orchestration/channel_extensions/surveys.md
  _docs/_partners/message_orchestration/channel_extensions/surveys/survicate.md
  assets/img/survicate/survicate_asset_1.png
  assets/img/survicate/survicate_asset_2.png
  assets/img/survicate/survicate_asset_3.png
Labels: status: on hold / do not merge, cla-signed, Braze Partnerships

#3516 Peak Partnership Docs - MERGE 5/9
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content.md
  _docs/_partners/message_personalization/dynamic_content/peak.md
Labels: status: on hold / do not merge, cla-signed, Braze Partnerships

#3503 Amperity updates - MERGE 5/9
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/amperity.md
  assets/img/amperity/amperity6.png
  assets/img/amperity/amperity7.png
Labels: cla-signed, Braze Partnerships

#3535 Dynamics 365 Customer Insights Partnership Docs - MERGE 5/9
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/dynamics_365_customer_insights.md
  _docs/_partners/home.md
Labels: cla-signed, Braze Partnerships

#3325 ViralSweep Partnership Docs - MERGE 5/9
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/channel_extensions.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/viralsweep.md
  assets/img/viralsweep/connect.gif
  assets/img/viralsweep/connect2.png
Labels: status: done, cla-signed, Braze Partnerships

#3510 Extole Partnership Docs - MERGE 5/9
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/channel_extensions.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
  assets/img/extole/extole-add-new-webhook.png
  assets/img/extole/extole-outbound-webhooks.png
  assets/img/extole/extole-webhook-live-events.png
Labels: cla-signed, Braze Partnerships

#3545 WSC Sports - Partner Docs
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content.md
  _docs/_partners/message_personalization/dynamic_content/wsc_sports.md
  assets/img/wsc_sports/braze_integration.JPG
Labels: cla-signed

#3543 BD-1382: Add tip for email editor selection
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
Labels: cla-signed

#3548 BD-1380: Remove old push primer doc
  _docs/_user_guide/message_building_by_channel/push.md
  _docs/_user_guide/message_building_by_channel/push/ios/create_push_primer.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#3549 BD-1383: Update recipient within Transactional API endpoint
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
Labels: cla-signed

#3547 Heap Partnership Docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/heap.md
  _docs/_partners/home.md
  assets/img/heap/heap1.png
  assets/img/heap/heap2.png
  assets/img/heap/heap3.png
  assets/img/heap/heap4.png
  assets/img/wsc_sports/braze_integration.jpg
Labels: cla-signed, Braze Partnerships

#3550 Heap: update data import/export descriptions
  _docs/_partners/data_and_infrastructure_agility/cohort_import/heap.md
Labels: cla-signed

#3546 Deploy - May 9, 2022
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  _docs/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/analytics/kubit.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/amplitude.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/appsflyer.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/heap.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/hightouch.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/kubit.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/mixpanel.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/tinyclues.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/amperity.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/dynamics_365_customer_insights.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/hightouch.md
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer_audiences.md
  _docs/_partners/message_orchestration/channel_extensions.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/viralsweep.md
  _docs/_partners/message_orchestration/channel_extensions/surveys.md
  _docs/_partners/message_orchestration/channel_extensions/surveys/survicate.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content.md
  _docs/_partners/message_personalization/dynamic_content/peak.md
  _docs/_partners/message_personalization/dynamic_content/wsc_sports.md
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/push.md
  _docs/_user_guide/message_building_by_channel/push/ios/create_push_primer.md
  assets/img/amperity/amperity6.png
  assets/img/amperity/amperity7.png
  assets/img/extole/extole-add-new-webhook.png
  assets/img/extole/extole-outbound-webhooks.png
  assets/img/extole/extole-webhook-live-events.png
  assets/img/heap/heap1.png
  assets/img/heap/heap2.png
  assets/img/heap/heap3.png
  assets/img/heap/heap4.png
  assets/img/hightouch/cohort1.png
  assets/img/hightouch/cohort2.png
  assets/img/hightouch/cohort3.png
  assets/img/hightouch/cohort4.png
  assets/img/hightouch/data_import_key.png
  assets/img/survicate/survicate_asset_1.png
  assets/img/survicate/survicate_asset_2.png
  assets/img/survicate/survicate_asset_3.png
  assets/img/viralsweep/connect.gif
  assets/img/viralsweep/connect2.png
  assets/img/wsc_sports/braze_integration.jpg
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#3551 WebSDKv4 updates
  _docs/_developer_guide/platform_integration_guides/web/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization/badges.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization/custom_ui.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization/key_value_pairs.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/multiple_feeds.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization/custom_styling.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization/message_dismissal.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/customization/badges.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/customization/key_value_pairs.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/integration.md
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
  _docs/_user_guide/message_building_by_channel/sms/sms_subscription_group.md
Labels: cla-signed

#3552 Update Braze Web SDK
  _includes/analytics.html
  assets/js/contentcards.js
Labels: cla-signed

#3553 BD-1381: Adding Event Property Segmentation
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  assets/img/nested_object3.png
Labels: cla-signed

#3557 BD-1384: Fix broken link
  _docs/_help/help_articles/api/delete_user.md
Labels: cla-signed

#3554 Leftover Deploy - May 12, 2022
  _docs/_developer_guide/platform_integration_guides/web/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization/badges.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization/custom_ui.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization/key_value_pairs.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/multiple_feeds.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization/custom_styling.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization/message_dismissal.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/customization/badges.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/customization/key_value_pairs.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/integration.md
  _docs/_help/help_articles/api/delete_user.md
  _docs/_hidden/private_betas/link_aliasing.md
  _docs/_hidden/private_betas/link_aliasing101.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
  _docs/_user_guide/message_building_by_channel/sms/sms_subscription_group.md
  _includes/analytics.html
  assets/img/nested_object3.png
  assets/js/broken_redirect_list.js
  assets/js/contentcards.js
Labels: cla-signed, Deploy

#3558 serviceWorkerLocation
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
Labels: cla-signed

#3556 Add reference to custom-keyword-messaging-handling
  _docs/_user_guide/message_building_by_channel/sms/non_native/double_opt_in.md
Labels: cla-signed

#3561 Update Cloning Canvases doc with CSM feedback
  _docs/_hidden/private_betas/canvas_v2_cloning.md
Labels: cla-signed

#3441 Reorganize best practices for Email
  _docs/_user_guide/message_building_by_channel/email/best_practices.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/email_services.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/email_styling.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/guidelines_and_tips.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/managing_email_subscriptions.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/sunset_policies.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/templates_styling.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/use_cases.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#3564 Deploy - May 17, 2022
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
  _docs/_hidden/private_betas/canvas_v2_cloning.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/message_building_by_channel/email/best_practices.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/email_services.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/email_styling.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/guidelines_and_tips.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/managing_email_subscriptions.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/sunset_policies.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/templates_styling.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/use_cases.md
  _docs/_user_guide/message_building_by_channel/sms/mms/about_mms.md
  _docs/_user_guide/message_building_by_channel/sms/non_native/double_opt_in.md
  assets/js/broken_redirect_list.js
  vercel.json
Labels: cla-signed, Deploy

#3565 BD-1387: Remove troubleshooting info from Email FAQ
  _docs/_user_guide/message_building_by_channel/email/faq.md
Labels: cla-signed

#3568 BD-1389: Clarify not to use Intelligent Timing for IP warming
  _docs/_user_guide/onboarding_with_braze/email_setup/ip_warming.md
Labels: cla-signed

#3570 Fix typo for Update users’ subscription group status doc
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
Labels: cla-signed

#3571 Leftover Deploy - May 19, 2022
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
  _docs/_user_guide/message_building_by_channel/email/faq.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ip_warming.md
Labels: cla-signed, Deploy

#3573 Update nokogiri version
  Gemfile.lock
Labels: cla-signed

#3566 Sdk 2496 update to braze constants
  _docs/_api/api_key.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
Labels: cla-signed

#3575 Update email_performance_dashboard.md
  _docs/_user_guide/data_and_analytics/your_analytics_dashboards/email_performance_dashboard.md
  assets/img_archive/email_performance_dashboard_1.png
  assets/img_archive/email_performance_dashboard_2.png
Labels: cla-signed

#3579 Update Canvas V2 101 doc with customer feedback
  _docs/_hidden/private_betas/canvas_v2_101.md
Labels: cla-signed

#3576 BD-1390: Update Currents to reflect that user_agent isn't used in MarkAsSpam events
  _docs/_hidden/private_betas/link_aliasing.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#3580 BD-1393: Update Historical Performance graph screenshot
  _includes/campaign_analytics.md
  assets/img/cc-historical-performance.png
Labels: cla-signed

#3581 Deploy - May 24, 2022
  Gemfile.lock
  _docs/_api/api_key.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_hidden/private_betas/canvas_v2_101.md
  _docs/_hidden/private_betas/catalog.md
  _docs/_hidden/private_betas/link_aliasing.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/your_analytics_dashboards/email_performance_dashboard.md
  _includes/campaign_analytics.md
  assets/img/cc-historical-performance.png
  assets/img_archive/email_performance_dashboard_1.png
  assets/img_archive/email_performance_dashboard_2.png
Labels: cla-signed, Deploy

#3583 braze actions
  _docs/_developer_guide/platform_wide/braze_actions.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
Labels: cla-signed

#3572 Create android_13.md
  _docs/_developer_guide/platform_integration_guides/android/android_13.md
Labels: cla-signed

#3585 BD-1395: Clarify Archiving Canvases doc
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/archiving_canvases.md
Labels: cla-signed

#3586 BD-1397: Fix broken link
  _docs/_user_guide/onboarding_with_braze/learning_to_use_braze.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#3587 BD-1396: Clarify webhook template for Punchh doc
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh.md
Labels: cla-signed

#3589 BD-1394: Clarify data export for Users by segment endpoint
  _docs/_api/endpoints/export/user_data/post_users_segment.md
Labels: cla-signed

#3588 Leftover Deploy - May 26, 2022
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_developer_guide/platform_integration_guides/android/android_13.md
  _docs/_developer_guide/platform_wide/braze_actions.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/archiving_canvases.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
  _docs/_user_guide/onboarding_with_braze/learning_to_use_braze.md
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#3594 Update rack ver
  Gemfile.lock
Labels: cla-signed

#3596 Update Data Points doc
  _docs/_user_guide/onboarding_with_braze/data_points.md
Labels: cla-signed

#3597 Leftover Deploy Pt. 2 - May 27, 2022
  Gemfile.lock
  _docs/_user_guide/onboarding_with_braze/data_points.md
Labels: cla-signed, Deploy

#3601 Update soft_push_prompt.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/soft_push_prompt.md
Labels: cla-signed

#3578 Add updated HTML engine info for DND doc
  _docs/_user_guide/message_building_by_channel/email.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
Labels: cla-signed, release notes

#3560 BD-1385: Update keyword category value - MERGE 5/18
  _docs/_user_guide/message_building_by_channel/sms/campaign/retargeting.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
Labels: cla-signed

#3595 July 2022 Release Notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2022.md
  _docs/_help/release_notes/2022/july.md
Labels: cla-signed
