Repository braze-inc/braze-docs, pull requests merged in 2022-12, with the labels that each got.

#4475 Updating user install partners
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/install_attribution.md
Labels: cla-signed

#4477 BD-1770: Remove mention of push dashboard
  _docs/_user_guide/data_and_analytics/your_analytics_dashboards/email_performance_dashboard.md
Labels: cla-signed

#4478 Update sinatra version
  Gemfile.lock
Labels: cla-signed

#4479 Replace Transifex bearer key
  _docs/_partners/message_personalization/localization/transifex.md
Labels: cla-signed

#4480 Test and seed email subject line
  _docs/_developer_guide/platform_wide/sending_test_messages.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  assets/img_archive/test_and_seed_email_subject_line.png
Labels: cla-signed

#4482 Update card_creation.md
  _docs/_hidden/private_betas/card_creation.md
Labels: cla-signed

#4473 Update defunct links to Looker
  _docs/_user_guide/data_and_analytics/braze_currents/how_braze_uses_currents.md
Labels: cla-signed

#4001 Snowflake Reader Accounts - MERGE 12/1
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
  _docs/_user_guide/data_and_analytics/braze_currents/how_braze_uses_currents.md
Labels: cla-signed

#4486 BD-1767: Add note about required MMS for Contact Cards
  _docs/_user_guide/message_building_by_channel/sms/mms/contact_card.md
Labels: cla-signed

#4484 DND IAM Title and Paragraph blocks
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/editor_blocks.md
Labels: cla-signed

#4492 Remove left nav from Data Protection Technical Assistance
  _docs/_home/dp-technical-assistance.md
Labels: cla-signed

#4469 Edited Push Token Migration
  _docs/_help/help_articles/push/push_token_migration.md
Labels: cla-signed

#4495 Fix broken link
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#4493 2717 user management
  _docs/_api/objects_filters/aliases_to_identify.md
  _docs/_api/objects_filters/user_attributes_object.md
  _docs/_user_guide/administrative/app_settings/developer_console/internal_groups_tab.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
Labels: cla-signed

#4472 BD-1764 and BD-1765: Updated for nested custom attributes and nested event properties
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  assets/img_archive/nca_personalization.png
  assets/img_archive/nca_triggered_changes.png
  assets/img_archive/nca_triggered_changes2.png
  assets/img_archive/nested_event_properties_personalization.png
  assets/img_archive/nested_event_properties_segmentation.png
  assets/img_archive/schema_generation_example.png
Labels: cla-signed

#4496 DALLE image generator in Media Library
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
  _docs/_user_guide/intelligence.md
  _docs/_user_guide/intelligence/ai_copywriting.md
  assets/img_archive/media_library_composers.png
  assets/img_archive/media_library_dalle.png
  assets/img_archive/media_library_main.png
Labels: cla-signed

#4498 Fixed broken link
  _docs/_user_guide/administrative/access_braze/sdk_endpoints.md
Labels: cla-signed

#4501 BD-1774: Update IAM Simple Survey Docs
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
Labels: cla-signed

#4502 BD-1779: Update Toovio
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/toovio.md
Labels: cla-signed

#4503 BD-1777: User archive threshold update
  _docs/_user_guide/data_and_analytics/user_data_collection/user_archival.md
Labels: cla-signed

#4507 Added nested properties to Users Track
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
Labels: cla-signed

#4465 docs updates for new idfv changes
  _docs/_api/endpoints/export/user_data/post_users_global_control_group.md
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
  _docs/_partners/message_orchestration/attribution/kochava.md
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: cla-signed

#4504 BD-1782: Update add-to-calendar-link additional options
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/add_to_calendar_links.md
Labels: cla-signed

#4510 ECOMP-Video-Block
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
Labels: cla-signed

#4506 Add alert for HTML sanitization
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
Labels: cla-signed

#4508 custom_attributes_DND
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  assets/img/dnd_custom_attributes.png
Labels: cla-signed

#4499 Punchh Updates
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh.md
  assets/img/punchh/update1.png
  assets/img/punchh/update2.png
  assets/img/punchh/update3.png
  assets/img/punchh/update4.png
  assets/img/punchh/update5.png
  assets/img/punchh/update6.png
  assets/img/punchh/update7.png
Labels: cla-signed

#4513 Update Content section for Drag and Drop Editor
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  assets/img/dnd/dnd_content.png
Labels: cla-signed

#4509 GlobalLink Translation PR
  .vercel/build.js
  _lang/fr/_api/data_retention.md
  _lang/fr/_developer_guide/platform_integration_guides/web/cookies_and_storage.md
  _lang/fr/_home/dp-technical-assistance.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
Labels: cla-signed

#4487 update braze docs request form
  _docs/_hidden/other/documentation_request.md
Labels: cla-signed

#4512 Updates to email heatmaps and email settings layout
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
  _includes/campaign_analytics.md
  assets/img/email_settings/bcc_address.png
  assets/img/email_settings/custom_footer.png
  assets/img/email_settings/custom_opt_in.png
  assets/img/email_settings/custom_unsubscribe.png
  assets/img/email_settings/display_name_address.png
  assets/img/email_settings/email_unsubscribe_header.png
  assets/img/email_settings/reply_to_address.png
  assets/img/email_settings/resubscribe_users.png
  assets/img/email_settings/test_and_seed_email_subject_line.png
  assets/img/open_pixel.png
  assets/img_archive/email_click_results_heatmap.gif
  assets/img_archive/email_heatmap_example.png
  assets/img_archive/list_unsub_img3_new.png
  assets/img_archive/test_and_seed_email_subject_line.png
Labels: cla-signed

#4518 Update Nokogiri
  Gemfile.lock
Labels: cla-signed

#4516 BD-1784: Add campaign alert behavior
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_alerts.md
Labels: cla-signed

#4519 Leftover Deploy - December 8, 2022
  .vercel/build.js
  Gemfile.lock
  _docs/_api/endpoints/export/user_data/post_users_global_control_group.md
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_api/errors.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations/swift_idfv.md
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
  _docs/_hidden/other/documentation_request.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/toovio.md
  _docs/_partners/message_orchestration/attribution/adjust.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _docs/_partners/message_orchestration/attribution/branch/branch_for_attribution.md
  _docs/_partners/message_orchestration/attribution/kochava.md
  _docs/_partners/message_orchestration/attribution/singular.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_archival.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/add_to_calendar_links.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_alerts.md
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  _includes/campaign_analytics.md
  _lang/fr/_api/data_retention.md
  _lang/fr/_developer_guide/platform_integration_guides/web/cookies_and_storage.md
  _lang/fr/_home/dp-technical-assistance.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
  assets/img/dnd/dnd_content.png
  assets/img/dnd_custom_attributes.png
  assets/img/email_settings/bcc_address.png
  assets/img/email_settings/custom_footer.png
  assets/img/email_settings/custom_opt_in.png
  assets/img/email_settings/custom_unsubscribe.png
  assets/img/email_settings/display_name_address.png
  assets/img/email_settings/email_unsubscribe_header.png
  assets/img/email_settings/reply_to_address.png
  assets/img/email_settings/resubscribe_users.png
  assets/img/email_settings/test_and_seed_email_subject_line.png
  assets/img/open_pixel.png
  assets/img/punchh/update1.png
  assets/img/punchh/update2.png
  assets/img/punchh/update3.png
  assets/img/punchh/update4.png
  assets/img/punchh/update5.png
  assets/img/punchh/update6.png
  assets/img/punchh/update7.png
  assets/img/swift_idfv.png
  assets/img_archive/email_click_results_heatmap.gif
  assets/img_archive/email_heatmap_example.png
  assets/img_archive/list_unsub_img3_new.png
  assets/img_archive/test_and_seed_email_subject_line.png
Labels: cla-signed, Deploy

#4517 Add preference_center_title to pref center pages
  _docs/_api/endpoints/preference_center/get_view_details_preference_center.md
  _docs/_api/endpoints/preference_center/post_create_preference_center.md
  _docs/_api/endpoints/preference_center/put_update_preference_center.md
Labels: cla-signed

#4522 Ck cdi events purchases
  _docs/_user_guide/data_and_analytics/cloud_ingestion.md
  assets/img/cloud_ingestion/ingestion_1.png
  assets/img/cloud_ingestion/ingestion_2.png
Labels: cla-signed

#4520 BD-1789: Remove mention of webhook timeouts
  _docs/_user_guide/administrative/company_settings/notification_preferences.md
Labels: cla-signed

#4523 idfv formatting
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations/swift_idfv.md
Labels: cla-signed

#4526 Some small tweaks to link shortening docs
  _docs/_hidden/private_betas/link_shortening.md
Labels: cla-signed

#4529 Minor style fixes
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake/sample_queries.md
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
Labels: cla-signed

#4530 [SDK-3205] web - isControl properties
  _docs/_developer_guide/platform_integration_guides/web/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/in-app_message_delivery.md
Labels: cla-signed

#4528 Add one more mention of events and purchases
  _docs/_user_guide/data_and_analytics/cloud_ingestion.md
Labels: cla-signed

#4533 Fix redirects pointing at different locations for the same URL
  assets/js/broken_redirect_list.js
Labels: cla-signed

#4464 BD-1763: Catalogs endpoints GA
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/delete_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/patch_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/post_create_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/delete_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/get_catalog_item_details.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/get_catalog_items_details_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/patch_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/delete_catalog.md
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/get_list_catalogs.md
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md
Labels: cla-signed

#4534 BD-1796: Update selections image
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/selections.md
  assets/img_archive/catalog_filtered_sets3.png
  assets/img_archive/catalog_selections3.png
Labels: cla-signed

#4462 BD-1747: Update users/track docs to include setting subscription group status
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_api/objects_filters/user_attributes_object.md
Labels: cla-signed

#4535 BD-1790: Shopify Updates, images and web SDK pre-reqs
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/scripttag_web_sdk_integration.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/setting_up_shopify.md
  assets/img/Shopify/shopify_integration77.jpg
  assets/img/Shopify/shopify_integration77.png
Labels: cla-signed

#4539 ecomp-custom-attribute-dnd
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
Labels: cla-signed

#4540 12 13 22 dashboard release
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2016.md
  _docs/_help/release_notes/2017.md
  _docs/_help/release_notes/2018.md
  _docs/_help/release_notes/2019.md
  _docs/_help/release_notes/2020.md
  _docs/_help/release_notes/2021.md
  _docs/_help/release_notes/2022.md
  _docs/_help/release_notes/2023.md
  _docs/_help/release_notes/2023/12_13_22.md
  _docs/_partners/message_personalization/dynamic_content/dynamic_yield.md
Labels: cla-signed

#4542 BD-1792: User Update GA
  _docs/_user_guide/engagement_tools/canvas/canvas_components.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/fb_audience_sync.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/google_audience_sync.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
  assets/img_archive/canvas_user_update_example.png
  assets/img_archive/canvas_user_update_remove.png
  assets/img_archive/canvas_user_update_test_preview.png
  assets/img_archive/canvas_user_update_update.png
Labels: cla-signed

#4544 BD-1800: Update Report Builder limit from 50 to 250 campaigns
  _docs/_user_guide/data_and_analytics/your_reports/report_builder.md
Labels: cla-signed

#4543 Fix incorrect link fix
  assets/js/broken_redirect_list.js
Labels: cla-signed

#4538 BD-1785: Rehaul random buckets article
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/ab_testing_with_random_buckets.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
  _docs/_user_guide/engagement_tools/testing/random_bucket_numbers.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#4545 Update DALLE image example
  assets/img_archive/media_library_dalle.png
Labels: cla-signed

#4524 idfv_uuid_link updates
  _docs/_developer_guide/platform_integration_guides/ios/analytics/disabling_tracking.md
  _docs/_developer_guide/platform_integration_guides/ios/storage.md
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
Labels: cla-signed

#4547 Edits for data docs - Pt. 1
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
Labels: cla-signed

#4546 Fussed with the term remote notifications
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/ios_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/customization/advanced_settings.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/customization/ignoring_internal_push.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/push_story.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/silent_push_notifications.md
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/ios_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/customization/advanced_settings.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/silent_push_notifications.md
Labels: cla-signed

#4548 Update datadog.md
  _docs/_hidden/private_betas/datadog.md
Labels: cla-signed

#4550 Updating Image 2 of the Dynamic Yield Integration
  assets/img/dynamic_yield/dynamic_yield2_new.png
Labels: cla-signed, Braze Partnerships

#4551 Update Image 2 of Dynamic Yield integration
  _docs/_partners/message_personalization/dynamic_content/dynamic_yield.md
Labels: cla-signed, Braze Partnerships

#4552 Update user_attributes_object.md with subscription group changes
  _docs/_api/objects_filters/user_attributes_object.md
Labels: cla-signed

#4553 Add editing best practices to IAM DND
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
Labels: cla-signed

#4494 BD-1773: Conversions dashboard
  _docs/_user_guide/data_and_analytics/your_analytics_dashboards/conversions_dashboard.md
Labels: cla-signed

#4549 Leftover Deploy - December 15, 2022
  _docs/_api/objects_filters/user_attributes_object.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/disabling_tracking.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/ios_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/customization/advanced_settings.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/customization/ignoring_internal_push.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/push_story.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/silent_push_notifications.md
  _docs/_developer_guide/platform_integration_guides/ios/storage.md
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/ios_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/customization/advanced_settings.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/silent_push_notifications.md
  _docs/_hidden/private_betas/datadog.md
  _docs/_partners/message_personalization/dynamic_content/dynamic_yield.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/data_and_analytics/your_analytics_dashboards/conversions_dashboard.md
  _docs/_user_guide/data_and_analytics/your_reports/report_builder.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/ab_testing_with_random_buckets.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/fb_audience_sync.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/google_audience_sync.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/engagement_tools/testing/random_bucket_numbers.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
  assets/img/dynamic_yield/dynamic_yield2_new.png
  assets/img_archive/canvas_user_update_example.png
  assets/img_archive/canvas_user_update_remove.png
  assets/img_archive/canvas_user_update_test_preview.png
  assets/img_archive/canvas_user_update_update.png
  assets/img_archive/media_library_dalle.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#4555 BD-1807: Update Card creation
  _docs/_hidden/private_betas/card_creation.md
Labels: cla-signed

#4556 Update create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
Labels: cla-signed

#4557 Adding subscription status + subscription groups
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
Labels: cla-signed

#4558 Fix missing images for French Site
  assets/img_archive/email_click_results_heatmap.gif
  assets/img_archive/list_unsub_img3_new.png
Labels: cla-signed

#4559 fix language preview
  .vercel/build.js
Labels: cla-signed

#4560 Changed data param name
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#4500 BD-1783: Hidden doc for Braze data transformation
  _docs/_hidden/private_betas/data_transformation.md
  assets/img/data_transformation/data_transformation1.jpg
  assets/img/data_transformation/data_transformation2.png
  assets/img/data_transformation/data_transformation4.png
  assets/img/data_transformation/data_transformation5.png
  assets/img/data_transformation/data_transformation6.jpg
  assets/img/data_transformation/data_transformation7.png
  assets/img_archive/data_transformation1.png
Labels: cla-signed

#4561 Prefer style "10DLC", not "10dlc"
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/10dlc.md
Labels: cla-signed

#4562 Backlog tickets: BD-1803, BD-1801, BD-1802, BD-1805, BD-1799, BD-1808, BD-1806
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/onboarding_with_braze/data_points.md
  _includes/campaign_analytics.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#4563 Leftover Deploy Pt. 2 - December 16, 2022
  .vercel/build.js
  _docs/_hidden/private_betas/card_creation.md
  _docs/_hidden/private_betas/data_transformation.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/10dlc.md
  _docs/_user_guide/onboarding_with_braze/data_points.md
  _includes/campaign_analytics.md
  assets/img/data_transformation/data_transformation1.jpg
  assets/img/data_transformation/data_transformation2.png
  assets/img/data_transformation/data_transformation4.png
  assets/img/data_transformation/data_transformation5.png
  assets/img/data_transformation/data_transformation6.jpg
  assets/img/data_transformation/data_transformation7.png
  assets/img_archive/data_transformation1.png
  assets/img_archive/email_click_results_heatmap.gif
  assets/img_archive/list_unsub_img3_new.png
  assets/js/broken_redirect_list.js
Labels: Deploy

#4564 Add missing punctuation to complete sentence.
  _docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
Labels: cla-signed

#4566 updating to reflect how canvas fields are included
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
Labels: cla-signed

#4565 Remove early access disclaimer
  _docs/_partners/data_and_infrastructure_agility/analytics/datadog.md
Labels: cla-signed

#4567 Update data_transformation.md
  _docs/_hidden/private_betas/data_transformation.md
Labels: cla-signed

#4570 Changes 'Custom Unsubscribe Page' screenshot to accurately show the default Braze unsubscribe page.
  assets/img/email_settings/custom_unsubscribe.png
Labels: cla-signed

#4571 Deploy - December 22, 2022
  _docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
  _docs/_hidden/private_betas/data_transformation.md
  _docs/_partners/data_and_infrastructure_agility/analytics/datadog.md
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
  assets/img/email_settings/custom_unsubscribe.png
Labels: cla-signed

#4572 Update random_bucket_numbers.md
  _docs/_user_guide/engagement_tools/testing/random_bucket_numbers.md
Labels: cla-signed

#4573 Braze Learning Language description
  _docs/_docs_pages/index.md
  _lang/fr/_docs_pages/index.md
  _layouts/doc_guide.html
Labels: cla-signed

#4574 BD-1811: Clarify Email Unsubscribe Header setting
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
Labels: cla-signed

#4575 BD-1812: Clarify Unsubscribe Event in Currents
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#4576 BD-1815: Fix broken link
  _docs/_user_guide/onboarding_with_braze/learning_to_use_braze.md
Labels: cla-signed

#4569 Update segment app selection information
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  assets/img_archive/segment_app_selection.png
  assets/img_archive/segment_step4.png
Labels: cla-signed

#4579 BD-1819: Add use case for /users/track
  _docs/_api/endpoints/user_data/post_user_track.md
Labels: cla-signed

#4577 BD-1818: Clarify iOS integration for attribution partner doc
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
Labels: cla-signed

#4581 Update image for email global style settings
  assets/img_archive/dnd_global_style_settings.png
Labels: cla-signed
