Repository braze-inc/braze-docs, pull requests merged in 2022-10, with the labels that each got.

#4171 GlobalLink Translation PR
  _lang/fr/_user_guide/message_building_by_channel/push/advanced_push_options/push_stories.md
  _lang/fr/_user_guide/message_building_by_channel/push/android/notification_channels.md
  _lang/fr/_user_guide/message_building_by_channel/push/android/rich_notifications.md
  _lang/fr/_user_guide/message_building_by_channel/push/best_practices.md
Labels: cla-signed

#4155 GlobalLink Translation PR
  _lang/fr/_includes/archive/android/gifs.md
  _lang/fr/_includes/archive/android/universal_deep_link_delegate.md
  _lang/fr/_includes/archive/appboyBridge.md
  _lang/fr/_includes/archive/apple/initial_setup.md
  _lang/fr/_includes/archive/apple/push_payload.json
  _lang/fr/_includes/archive/baidu_deprecation.md
  _lang/fr/_includes/archive/in_app_message.md
  _lang/fr/_includes/archive/ios-swift-upgrade.md
  _lang/fr/_includes/archive/setting_user_ids/aliasing.md
  _lang/fr/_includes/archive/setting_user_ids/best_practices.md
  _lang/fr/_includes/archive/setting_user_ids/naming_convention.md
  _lang/fr/_includes/archive/setting_user_ids/setting_user_ids.md
  _lang/fr/_includes/archive/short_and_long_codes.md
  _lang/fr/_includes/archive/web-v4-rename.md
  _lang/fr/_includes/archive/windows_deprecation.md
  _lang/fr/_includes/campaign_analytics.md
  _lang/fr/_includes/rate_limits.md
  _lang/fr/_includes/sdk_auth_alert.md
Labels: cla-signed

#4129 Updating user archival
  _docs/_user_guide/data_and_analytics/user_data_collection/user_archival.md
Labels: cla-signed

#4163 More wordsmithing on Segment Extensions.
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
Labels: cla-signed

#4146 GlobalLink Translation PR
  _lang/fr/_developer_guide/disclosures.md
  _lang/fr/_developer_guide/disclosures/innovation_statement.md
  _lang/fr/_developer_guide/disclosures/open_source_software_disclosure.md
  _lang/fr/_developer_guide/disclosures/security_and_vulnerability_disclosure.md
  _lang/fr/_developer_guide/disclosures/security_qualifications.md
  _lang/fr/_developer_guide/home.md
  _lang/fr/_developer_guide/platform_wide.md
  _lang/fr/_developer_guide/platform_wide/analytics_overview.md
  _lang/fr/_developer_guide/platform_wide/app_group_configuration.md
  _lang/fr/_developer_guide/platform_wide/braze_actions.md
  _lang/fr/_developer_guide/platform_wide/platform_features.md
  _lang/fr/_developer_guide/platform_wide/sdk_authentication.md
  _lang/fr/_developer_guide/platform_wide/sending_test_messages.md
  _lang/fr/_developer_guide/platform_wide/tv_and_ott.md
  _lang/fr/_user_guide/administrative/access_braze.md
  _lang/fr/_user_guide/administrative/access_braze/braze_instances.md
  _lang/fr/_user_guide/administrative/access_braze/getting_your_account.md
  _lang/fr/_user_guide/administrative/access_braze/portal.md
  _lang/fr/_user_guide/administrative/access_braze/product_request_example.md
  _lang/fr/_user_guide/administrative/access_braze/resetting_your_password.md
  _lang/fr/_user_guide/administrative/access_braze/sdk_endpoints.md
  _lang/fr/_user_guide/administrative/access_braze/single_sign_on.md
  _lang/fr/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
  _lang/fr/_user_guide/administrative/access_braze/single_sign_on/okta.md
  _lang/fr/_user_guide/administrative/access_braze/single_sign_on/onelogin.md
  _lang/fr/_user_guide/administrative/access_braze/single_sign_on/set_up.md
  _lang/fr/_user_guide/administrative/app_settings.md
  _lang/fr/_user_guide/administrative/app_settings/developer_console.md
  _lang/fr/_user_guide/administrative/app_settings/developer_console/api_settings_tab.md
  _lang/fr/_user_guide/administrative/app_settings/developer_console/event_user_log_tab.md
  _lang/fr/_user_guide/administrative/app_settings/developer_console/internal_groups_tab.md
  _lang/fr/_user_guide/administrative/app_settings/developer_console/message_activity_log_tab.md
  _lang/fr/_user_guide/administrative/app_settings/manage_app_group.md
  _lang/fr/_user_guide/administrative/app_settings/manage_app_group/app_group_management.md
  _lang/fr/_user_guide/administrative/app_settings/manage_app_group/custom_event_and_attribute_management.md
  _lang/fr/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  _lang/fr/_user_guide/administrative/app_settings/manage_app_group/push_ttl_settings.md
  _lang/fr/_user_guide/administrative/app_settings/manage_app_group/tags.md
  _lang/fr/_user_guide/administrative/company_settings.md
  _lang/fr/_user_guide/administrative/company_settings/automated_user_provisioning.md
  _lang/fr/_user_guide/administrative/company_settings/contact_information.md
  _lang/fr/_user_guide/administrative/company_settings/notification_preferences.md
  _lang/fr/_user_guide/administrative/company_settings/security_settings.md
  _lang/fr/_user_guide/administrative/manage_your_braze_users.md
  _lang/fr/_user_guide/administrative/manage_your_braze_users/adding_users_to_your_dashboard.md
  _lang/fr/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md
  _lang/fr/_user_guide/administrative/manage_your_braze_users/deleting_users_from_your_account.md
  _lang/fr/_user_guide/administrative/manage_your_braze_users/teams.md
  _lang/fr/_user_guide/administrative/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#4147 GlobalLink Translation PR
  _lang/fr/_user_guide/onboarding_with_braze.md
  _lang/fr/_user_guide/onboarding_with_braze/data_points.md
  _lang/fr/_user_guide/onboarding_with_braze/email_setup.md
  _lang/fr/_user_guide/onboarding_with_braze/email_setup/authentication.md
  _lang/fr/_user_guide/onboarding_with_braze/email_setup/consent_and_address_collection.md
  _lang/fr/_user_guide/onboarding_with_braze/email_setup/deliverability_pitfalls_and_spam_traps.md
  _lang/fr/_user_guide/onboarding_with_braze/email_setup/email_validation.md
  _lang/fr/_user_guide/onboarding_with_braze/email_setup/import_your_email_list.md
  _lang/fr/_user_guide/onboarding_with_braze/email_setup/ip_warming.md
  _lang/fr/_user_guide/onboarding_with_braze/email_setup/setting_up_ips_and_domains.md
  _lang/fr/_user_guide/onboarding_with_braze/email_setup/ssl.md
  _lang/fr/_user_guide/onboarding_with_braze/email_setup/ssl/ssl_clicktracking.md
  _lang/fr/_user_guide/onboarding_with_braze/integration.md
  _lang/fr/_user_guide/onboarding_with_braze/learning_to_use_braze.md
  _lang/fr/_user_guide/onboarding_with_braze/sms_setup.md
  _lang/fr/_user_guide/onboarding_with_braze/sms_setup/about_sms.md
  _lang/fr/_user_guide/onboarding_with_braze/sms_setup/next_steps.md
  _lang/fr/_user_guide/onboarding_with_braze/sms_setup/short_and_long_codes.md
  _lang/fr/_user_guide/onboarding_with_braze/sms_setup/sms_laws_and_regulations.md
  _lang/fr/_user_guide/onboarding_with_braze/sms_setup/sms_sending.md
  _lang/fr/_user_guide/onboarding_with_braze/sms_setup/sms_subscription_groups.md
  _lang/fr/_user_guide/onboarding_with_braze/sms_setup/terms.md
  _lang/fr/_user_guide/onboarding_with_braze/sms_setup/user_data_migration.md
  _lang/fr/_user_guide/onboarding_with_braze/spam_regulations.md
  _lang/fr/_user_guide/onboarding_with_braze/subscription_and_usage.md
  _lang/fr/_user_guide/onboarding_with_braze/terms_to_know.md
  _lang/fr/_user_guide/onboarding_with_braze/web_sdk.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/canvas_persistent_entry_properties.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/catalog.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/connected_content.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/connected_content/aborting_connected_content.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/connected_content/connected_content_retries.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/connected_content/public_apis.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/connected_content/user_profile_fields_connected_content.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/deep_linking_to_in-app_content.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/liquid.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/liquid/aborting_messages.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/liquid/conditional_logic.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/liquid/filters.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/liquid/operators.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/liquid/setting_default_values.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/overview.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/promotion_codes.md
Labels: cla-signed

#4148 GlobalLink Translation PR
  _lang/fr/_user_guide/engagement_tools/locations_and_geofences.md
  _lang/fr/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md
  _lang/fr/_user_guide/engagement_tools/locations_and_geofences/faqs.md
  _lang/fr/_user_guide/engagement_tools/locations_and_geofences/geofence_configuration.md
  _lang/fr/_user_guide/engagement_tools/locations_and_geofences/location_tracking.md
  _lang/fr/_user_guide/engagement_tools/locations_and_geofences/mobile_integrations.md
  _lang/fr/_user_guide/engagement_tools/news_feed.md
  _lang/fr/_user_guide/engagement_tools/news_feed/best_practices.md
  _lang/fr/_user_guide/engagement_tools/news_feed/creating_a_news_feed_item.md
  _lang/fr/_user_guide/engagement_tools/news_feed/news_feed_analytics_and_retargeting_data.md
  _lang/fr/_user_guide/engagement_tools/news_feed/news_feed_categories.md
  _lang/fr/_user_guide/engagement_tools/news_feed/news_feed_use_cases.md
  _lang/fr/_user_guide/engagement_tools/segments.md
  _lang/fr/_user_guide/engagement_tools/segments/beacon_support.md
  _lang/fr/_user_guide/engagement_tools/segments/creating_a_segment.md
  _lang/fr/_user_guide/engagement_tools/segments/location_targeting.md
  _lang/fr/_user_guide/engagement_tools/segments/regex.md
  _lang/fr/_user_guide/engagement_tools/segments/segment_extension.md
  _lang/fr/_user_guide/engagement_tools/segments/segment_funnels.md
  _lang/fr/_user_guide/engagement_tools/segments/segment_insights.md
  _lang/fr/_user_guide/engagement_tools/segments/segmentation_filters.md
  _lang/fr/_user_guide/engagement_tools/segments/using_user_search.md
  _lang/fr/_user_guide/engagement_tools/templates_and_media.md
  _lang/fr/_user_guide/engagement_tools/templates_and_media/archive.md
  _lang/fr/_user_guide/engagement_tools/templates_and_media/content_blocks.md
  _lang/fr/_user_guide/engagement_tools/templates_and_media/duplicate.md
  _lang/fr/_user_guide/engagement_tools/templates_and_media/faqs.md
  _lang/fr/_user_guide/engagement_tools/templates_and_media/media_library.md
  _lang/fr/_user_guide/engagement_tools/testing.md
  _lang/fr/_user_guide/engagement_tools/testing/conversion_correlation.md
  _lang/fr/_user_guide/engagement_tools/testing/global_control_group.md
  _lang/fr/_user_guide/engagement_tools/testing/multivariant_testing.md
  _lang/fr/_user_guide/engagement_tools/testing/race_conditions.md
  assets/download_file/regex-cheatsheet.pdf
  assets/img_archive/User_Profile_Social.png
Labels: cla-signed

#4149 GlobalLink Translation PR
  _lang/fr/_user_guide/message_building_by_channel/sms/non_native.md
  _lang/fr/_user_guide/message_building_by_channel/sms/non_native/custom_keyword_handling.md
  _lang/fr/_user_guide/message_building_by_channel/sms/non_native/double_opt_in.md
  _lang/fr/_user_guide/message_building_by_channel/sms/non_native/handling_unkown_phone_numbers.md
  _lang/fr/_user_guide/message_building_by_channel/sms/non_native/user_data_migration.md
  _lang/fr/_user_guide/message_building_by_channel/sms/phone_numbers.md
  _lang/fr/_user_guide/message_building_by_channel/sms/phone_numbers/10dlc.md
  _lang/fr/_user_guide/message_building_by_channel/sms/phone_numbers/best_practices.md
  _lang/fr/_user_guide/message_building_by_channel/sms/phone_numbers/best_practices/high_volume_sending.md
  _lang/fr/_user_guide/message_building_by_channel/sms/phone_numbers/best_practices/multi_country_sms_sending.md
  _lang/fr/_user_guide/message_building_by_channel/sms/phone_numbers/short_and_long_codes.md
  _lang/fr/_user_guide/message_building_by_channel/sms/phone_numbers/user_phone_numbers.md
  _lang/fr/_user_guide/message_building_by_channel/sms/sms_campaign_analytics.md
  _lang/fr/_user_guide/message_building_by_channel/sms/sms_laws_and_regulations.md
  _lang/fr/_user_guide/message_building_by_channel/sms/sms_subscription_group.md
  _lang/fr/_user_guide/message_building_by_channel/sms/user_data_migration.md
Labels: cla-signed

#4150 GlobalLink Translation PR
  _lang/fr/_user_guide/message_building_by_channel/sms/about_sms.md
  _lang/fr/_user_guide/message_building_by_channel/sms/best_practices.md
  _lang/fr/_user_guide/message_building_by_channel/sms/best_practices/know_before_send.md
  _lang/fr/_user_guide/message_building_by_channel/sms/campaign.md
  _lang/fr/_user_guide/message_building_by_channel/sms/campaign/create.md
  _lang/fr/_user_guide/message_building_by_channel/sms/campaign/retargeting.md
  _lang/fr/_user_guide/message_building_by_channel/sms/campaign/segments.md
  _lang/fr/_user_guide/message_building_by_channel/sms/faqs.md
  _lang/fr/_user_guide/message_building_by_channel/sms/keywords.md
  _lang/fr/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
  _lang/fr/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md
  _lang/fr/_user_guide/message_building_by_channel/sms/keywords/unknown_phone_numbers.md
  _lang/fr/_user_guide/message_building_by_channel/sms/mms.md
  _lang/fr/_user_guide/message_building_by_channel/sms/mms/about_mms.md
  _lang/fr/_user_guide/message_building_by_channel/sms/mms/contact_card.md
  _lang/fr/_user_guide/message_building_by_channel/sms/mms/create.md
  _lang/fr/_user_guide/message_building_by_channel/sms/mms/faqs.md
  _lang/fr/_user_guide/message_building_by_channel/sms/mms/mms_short_long_codes.md
Labels: cla-signed

#4154 GlobalLink Translation PR
  _lang/fr/_user_guide/engagement_tools/campaigns.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/conversion_events.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/creating_campaign.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/api_triggered_delivery.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/campaign_calendar.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/reeligibility.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/scheduled_delivery.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/attribute_triggers.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/campaign_connector.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/targeting_users.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/time_based_campaign.md
  _lang/fr/_user_guide/engagement_tools/campaigns/faq.md
  _lang/fr/_user_guide/engagement_tools/campaigns/getting_started.md
  _lang/fr/_user_guide/engagement_tools/campaigns/getting_started/campaign_basics.md
  _lang/fr/_user_guide/engagement_tools/campaigns/getting_started/understanding_campaign_status.md
  _lang/fr/_user_guide/engagement_tools/campaigns/ideas_and_strategies.md
  _lang/fr/_user_guide/engagement_tools/campaigns/ideas_and_strategies/active_user_campaigns.md
  _lang/fr/_user_guide/engagement_tools/campaigns/ideas_and_strategies/campaigns_in_multiple_languages.md
  _lang/fr/_user_guide/engagement_tools/campaigns/ideas_and_strategies/capturing_lapsing_users.md
  _lang/fr/_user_guide/engagement_tools/campaigns/ideas_and_strategies/getting_high_ratings.md
  _lang/fr/_user_guide/engagement_tools/campaigns/ideas_and_strategies/install_attribution.md
  _lang/fr/_user_guide/engagement_tools/campaigns/ideas_and_strategies/localizing_a_campaign.md
  _lang/fr/_user_guide/engagement_tools/campaigns/ideas_and_strategies/new_features.md
  _lang/fr/_user_guide/engagement_tools/campaigns/ideas_and_strategies/retargeting_campaigns.md
  _lang/fr/_user_guide/engagement_tools/campaigns/managing_campaigns.md
  _lang/fr/_user_guide/engagement_tools/campaigns/managing_campaigns/archiving_campaigns.md
  _lang/fr/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_alerts.md
  _lang/fr/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_approval.md
  _lang/fr/_user_guide/engagement_tools/campaigns/managing_campaigns/change_your_campaign_after_launch.md
  _lang/fr/_user_guide/engagement_tools/campaigns/managing_campaigns/duplicating_segments_and_campaigns.md
  _lang/fr/_user_guide/engagement_tools/campaigns/testing_and_more.md
  _lang/fr/_user_guide/engagement_tools/campaigns/testing_and_more/ab_testing_with_random_buckets.md
  _lang/fr/_user_guide/engagement_tools/campaigns/testing_and_more/campaign_analytics.md
  _lang/fr/_user_guide/engagement_tools/campaigns/testing_and_more/campaign_funnel_report.md
  _lang/fr/_user_guide/engagement_tools/campaigns/testing_and_more/retention_reports.md
  _lang/fr/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_push_notifications.md
  _lang/fr/_user_guide/intelligence/ai_copywriting.md
  _lang/fr/_user_guide/intelligence/faqs.md
  _lang/fr/_user_guide/intelligence/intelligent_channel.md
  _lang/fr/_user_guide/intelligence/intelligent_selection.md
  _lang/fr/_user_guide/intelligence/intelligent_timing.md
  _lang/fr/_user_guide/intelligence/multivariate_testing.md
  _lang/fr/_user_guide/predictive_suite/predictive_churn.md
  _lang/fr/_user_guide/predictive_suite/predictive_churn/creating_a_churn_prediction.md
  _lang/fr/_user_guide/predictive_suite/predictive_churn/messaging_users.md
  _lang/fr/_user_guide/predictive_suite/predictive_churn/prediction_analytics.md
  _lang/fr/_user_guide/predictive_suite/predictive_churn/prediction_analytics/prediction_quality.md
  _lang/fr/_user_guide/predictive_suite/predictive_churn/prediction_faq.md
  _lang/fr/_user_guide/predictive_suite/predictive_purchases.md
  _lang/fr/_user_guide/predictive_suite/predictive_purchases/creating_a_purchase_prediction.md
  _lang/fr/_user_guide/predictive_suite/predictive_purchases/messaging_users.md
  _lang/fr/_user_guide/predictive_suite/predictive_purchases/prediction_analytics.md
Labels: cla-signed

#4156 GlobalLink Translation PR
  _lang/fr/_hidden/misc_reference/x-in-y-behavior.md
  _lang/fr/_hidden/other/airship_migration.md
  _lang/fr/_hidden/other/braze faqs.md
  _lang/fr/_hidden/other/braze_support.md
  _lang/fr/_hidden/other/core_endpoints.md
  _lang/fr/_hidden/other/documentation_request.md
  _lang/fr/_hidden/other/ephemeral_custom_events.md
  _lang/fr/_hidden/other/generations.md
  _lang/fr/_hidden/other/handbooks.md
  _lang/fr/_hidden/other/support_contact.md
  _lang/fr/_hidden/other/user_csv_lambda.md
  _lang/fr/_hidden/private_betas/amphtml.md
  _lang/fr/_hidden/private_betas/canvas_in-app_messages.md
  _lang/fr/_hidden/private_betas/canvas_post-launch_edits.md
  _lang/fr/_hidden/private_betas/canvas_user_update.md
  _lang/fr/_hidden/private_betas/canvas_v2_101.md
  _lang/fr/_hidden/private_betas/canvas_v2_cloning.md
  _lang/fr/_hidden/private_betas/email_history.md
  _lang/fr/_hidden/private_betas/get_app_group_apps.md
  _lang/fr/_hidden/private_betas/get_campaign_url_info.md
  _lang/fr/_hidden/private_betas/get_canvas_url_info.md
  _lang/fr/_hidden/private_betas/link_shortening.md
  _lang/fr/_hidden/private_betas/message_archiving.md
  _lang/fr/_hidden/private_betas/post_update_user_subscription_group_status_v2.md
  _lang/fr/_hidden/private_betas/post_user_identify_merge_behavior.md
  _lang/fr/_hidden/private_betas/scim.md
  _lang/fr/_hidden/private_betas/scim/delete_existing_dashboard_developer.md
  _lang/fr/_hidden/private_betas/scim/get_see_developer_account_information.md
  _lang/fr/_hidden/private_betas/scim/post_create_developer_account.md
  _lang/fr/_hidden/private_betas/scim/put_update_existing_developer_account.md
  _lang/fr/_hidden/private_betas/shopify.md
  _lang/fr/_hidden/private_betas/shopify/scripttag_web_sdk_integration.md
  _lang/fr/_hidden/private_betas/shopify/setting_up_shopify.md
  _lang/fr/_hidden/private_betas/shopify/shopify_data.md
  _lang/fr/_hidden/private_betas/shopify/use_cases.md
  _lang/fr/_hidden/private_betas/view_pii.md
  _lang/fr/_hidden/redirects/advancement_behavior.md
  _lang/fr/_hidden/redirects/content_cards.md
  _lang/fr/_hidden/redirects/content_cards_for_android.md
  _lang/fr/_hidden/redirects/content_cards_for_ios.md
  _lang/fr/_hidden/redirects/content_cards_web.md
  _lang/fr/_hidden/redirects/creating_an_in-app_message.md
  _lang/fr/_hidden/redirects/currents.md
  _lang/fr/_hidden/redirects/eclipse_setup.md
  _lang/fr/_hidden/redirects/email_attachments.md
  _lang/fr/_hidden/redirects/gmail_promotion_tool.md
  _lang/fr/_hidden/redirects/in_app_message_color_templates.md
  _lang/fr/_hidden/redirects/okta.md
  _lang/fr/_hidden/redirects/sdk_changelogs.md
  _lang/fr/_hidden/redirects/subscription_group_api.md
  _lang/fr/_hidden/wip_partnerships/WIP_guidelines.md
  _lang/fr/_hidden/wip_partnerships/partnership_template.md
Labels: cla-signed

#4160 GlobalLink Translation PR
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/about.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/best_practices/previous_in-app_message_generations.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/create.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/customize/html_in-app_messages.md
Labels: cla-signed

#4161 GlobalLink Translation PR
  _lang/fr/_user_guide/message_building_by_channel/content_cards/best_practices.md
  _lang/fr/_user_guide/message_building_by_channel/content_cards/creative_details.md
  _lang/fr/_user_guide/message_building_by_channel/email.md
  _lang/fr/_user_guide/message_building_by_channel/email/best_practices/managing_email_subscriptions.md
Labels: cla-signed

#4173 Update Link Shortening FAQ
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
Labels: cla-signed

#3743 ContentCardsViewBindingHandler docs update
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/custom_styling.md
Labels: cla-signed

#4174 Update email_validation.md
  _docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md
Labels: cla-signed

#4177 BD-1640: Fix campaigns tag for API guide
  _docs/_api/home.md
Labels: cla-signed

#4175 SCIM Endpoint GA - MERGE 10/5
  _docs/_api/endpoints/scim.md
  _docs/_api/endpoints/scim/delete_existing_dashboard_user.md
  _docs/_api/endpoints/scim/get_see_user_account_information.md
  _docs/_api/endpoints/scim/post_create_user_account.md
  _docs/_api/endpoints/scim/put_update_existing_user_account.md
  _docs/_api/home.md
  _docs/_hidden/misc_reference/scim_api_apprendix.md
  _docs/_user_guide/administrative/company_settings/automated_user_provisioning.md
Labels: cla-signed

#4182 BD-1642: Add mention of catalogs endpoints
  _docs/_user_guide/personalization_and_dynamic_content/catalog.md
Labels: cla-signed

#4040 BD-1575: Catalogs filtered sets EA
  _docs/_user_guide/personalization_and_dynamic_content/catalogs.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/filtered_sets.md
  assets/img_archive/catalog_filtered_sets1.png
  assets/img_archive/catalog_filtered_sets2.png
  assets/img_archive/catalog_filtered_sets3.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#4179 Updates to Cloud Ingestion Beta
  _docs/_hidden/private_betas/snowflake_integration.md
  assets/img/cloud_ingestion/ingestion_1.png
  assets/img/cloud_ingestion/ingestion_2.png
  assets/img/cloud_ingestion/ingestion_3.png
  assets/img/cloud_ingestion/ingestion_4.png
Labels: cla-signed

#4186 Update snowflake_integration.md
  _docs/_hidden/private_betas/snowflake_integration.md
Labels: cla-signed

#4185 Add new version of success and support services handbook
  assets/download_file/Braze_Success_and_Support_Services_Handbook_23.pdf
Labels: cla-signed

#4169 Restore "BD-1605: Document Messaging History tab of user profile" [MERGE 10/6]
  _docs/_hidden/private_betas/email_history.md
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
  _docs/_user_guide/engagement_tools/segments/using_user_search.md
  assets/img_archive/profiles_engagement_tab.png
  assets/img_archive/profiles_messaging_history_tab.png
  assets/img_archive/profiles_multiple_results.png
  assets/img_archive/profiles_overview_tab.png
  assets/img_archive/profiles_social_tab.png
  assets/img_archive/profiles_social_tab_old.png
Labels: cla-signed

#4181 BD-1636: App Uninstall Troubleshooting
  _docs/_user_guide/data_and_analytics/tracking/uninstall_tracking.md
Labels: cla-signed

#4189 Update message_step.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
Labels: cla-signed

#4190 Update decision_split.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/decision_split.md
Labels: cla-signed

#4188 Reword segment extensions limit.
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
Labels: cla-signed

#4191 Update experiment_step.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
Labels: cla-signed

#4193 Update audience_paths.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md
Labels: cla-signed

#3829 [SDK-2825] InAppMessages using Flutter Streams
  _docs/_developer_guide/platform_integration_guides/flutter/inapp_messages.md
Labels: status: on hold / do not merge, cla-signed

#4195 Update security_settings.md
  _docs/_user_guide/administrative/company_settings/security_settings.md
Labels: cla-signed

#4194 BD-1646 and BD-1647: Update User Update component doc
  _docs/_hidden/private_betas/canvas_user_update.md
  assets/img_archive/canvas_user_update_composer.png
  assets/img_archive/canvas_user_update_example.png
  assets/img_archive/canvas_user_update_remove.png
  assets/img_archive/canvas_user_update_update.png
Labels: cla-signed

#4159 Updating no-code push primer messages
  _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
Labels: cla-signed

#4068 Preference center via API guide and endpoint docs EA
  _docs/_api/api_limits.md
  _docs/_api/endpoints/preference_center.md
  _docs/_api/endpoints/preference_center/get_create_url_preference_center.md
  _docs/_api/endpoints/preference_center/get_list_preference_center.md
  _docs/_api/endpoints/preference_center/get_view_details_preference_center.md
  _docs/_api/endpoints/preference_center/post_create_preference_center.md
  _docs/_api/endpoints/preference_center/put_update_preference_center.md
  _docs/_api/endpoints/templates/email_templates/post_update_email_template.md
  _docs/_api/home.md
  _docs/_user_guide/message_building_by_channel/email/css_inline.md
  _docs/_user_guide/message_building_by_channel/email/preference_center.md
Labels: cla-signed

#4196 BD-1650: Add limitation for nested custom attributes
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
Labels: cla-signed

#4197 Update page order for Endpoints sections
  _docs/_api/endpoints/preference_center.md
  _docs/_api/endpoints/scim.md
  _docs/_api/endpoints/sms.md
  _docs/_api/endpoints/subscription_groups.md
  _docs/_api/endpoints/templates.md
  _docs/_api/endpoints/user_data.md
Labels: cla-signed

#4199 Control iam
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization/key_value_pairs.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/soft_push_prompt.md
Labels: cla-signed

#4202 BD-1652: Clarify Device OS segmentation filter
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#4204 BD-1653: Fix broken link
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
Labels: cla-signed

#4205 Revert "Add new version of success and support services handbook"
  assets/download_file/Braze_Success_and_Support_Services_Handbook_23.pdf
Labels: cla-signed

#4208 Edit Message doc
  _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
Labels: cla-signed

#4207 BD-1643: Format card creation differences as table and add usage row
  _docs/_hidden/private_betas/card_creation.md
Labels: cla-signed

#4211 Update readme.md
  readme.md
Labels: cla-signed

#4212 Deploy Pt. 1 - October 11, 2022
  _docs/_api/endpoints/preference_center.md
  _docs/_api/endpoints/scim.md
  _docs/_api/endpoints/sms.md
  _docs/_api/endpoints/subscription_groups.md
  _docs/_api/endpoints/templates.md
  _docs/_api/endpoints/user_data.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization/key_value_pairs.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/soft_push_prompt.md
  _docs/_hidden/private_betas/card_creation.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs.md
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
  assets/download_file/Braze_Success_and_Support_Services_Handbook_23.pdf
Labels: cla-signed, Deploy

#4213 Update copy
  _docs/_user_guide/predictive_suite.md
Labels: cla-signed

#4214 BD-1657: Clarify Canvas entry properties details
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
Labels: cla-signed

#4215 Update push_primer_messages.md
  _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
Labels: cla-signed

#4216 BD-1656: Update Canvas performance visualization details
  _docs/_user_guide/engagement_tools/canvas/testing_canvases/measuring_and_testing_with_canvas_analytics.md
  assets/img_archive/Journey_6.png
Labels: cla-signed

#4217 Move Cloud Ingestion to public docs
  _docs/_user_guide/data_and_analytics/cloud_ingestion.md
Labels: cla-signed

#4209 Update link_shortening.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
Labels: cla-signed

#4220 BD-1658: Update user_alias to user_alias_name in user import docs
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Labels: cla-signed

#4221 BD-1658: Clarify that CSVs for user import can't contain a mix of external_ids and aliases
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Labels: cla-signed

#4218 Clarify Cloning Canvas limitations
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
  assets/img_archive/clone_to_flow_variant.png
Labels: cla-signed

#4219 Deploy Pt. 2 - October 11, 2022
  _docs/_user_guide/data_and_analytics/cloud_ingestion.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
  _docs/_user_guide/engagement_tools/canvas/testing_canvases/measuring_and_testing_with_canvas_analytics.md
  _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
  _docs/_user_guide/predictive_suite.md
  assets/img_archive/Journey_6.png
  assets/img_archive/clone_to_flow_variant.png
Labels: cla-signed, Deploy

#4222 Edits for Preference Center API docs
  _docs/_api/endpoints/preference_center/post_create_preference_center.md
  _docs/_user_guide/message_building_by_channel/email/preference_center.md
Labels: cla-signed

#4226 Handbook fix
  _docs/_hidden/other/handbooks.md
Labels: cla-signed

#4227 Leftover Deploy Pt. 1 - October 12, 2022
  _docs/_api/endpoints/preference_center/post_create_preference_center.md
  _docs/_hidden/other/handbooks.md
  _docs/_user_guide/message_building_by_channel/email/preference_center.md
Labels: cla-signed, Deploy

#4225 New article for add-to-calendar links
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/add_to_calendar_links.md
  assets/img_archive/calendar_1.png
  assets/img_archive/calendar_2.png
  assets/img_archive/calendar_3.png
  assets/img_archive/calendar_4.png
  assets/img_archive/calendar_5.png
Labels: cla-signed

#4223 removed broadcast receiver from unity android
  _docs/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md
Labels: status: on hold / do not merge, cla-signed

#4228 Update integration.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
Labels: cla-signed

#4230 Remove duplicate IAM Canvas doc
  _docs/_hidden/private_betas/canvas_in-app_messages.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
Labels: cla-signed

#4232 Add link for Preference Center endpoints
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#4231 Move AMP for Email doc
  _docs/_hidden/private_betas/amphtml.md
  _docs/_user_guide/message_building_by_channel/email/amphtml.md
  assets/img/dynamic-content.png
Labels: cla-signed

#4233 Leftover Deploy - October 13, 2022
  _docs/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
  _docs/_hidden/private_betas/amphtml.md
  _docs/_hidden/private_betas/canvas_in-app_messages.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/add_to_calendar_links.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
  _docs/_user_guide/message_building_by_channel/email/amphtml.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/sms/keywords.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/fuzzy_opt_out.md
  assets/img/dynamic-content.png
  assets/img_archive/calendar_1.png
  assets/img_archive/calendar_2.png
  assets/img_archive/calendar_3.png
  assets/img_archive/calendar_4.png
  assets/img_archive/calendar_5.png
Labels: cla-signed, Deploy

#4235 Add missing dot for canvas_entry_properties
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
Labels: cla-signed

#4237 Update SSS Handbook
  _docs/_hidden/other/handbooks.md
  assets/download_file/Braze_Success_and_Support_Services_Handbook_23v16.pdf
Labels: cla-signed

#4224 Add reference to Fuzzy Opt-Out in SMS Opt-Out docs
  _docs/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md
Labels: cla-signed

#4238 GA Fuzzy Opt-Outs
  _docs/_user_guide/message_building_by_channel/sms/keywords.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/fuzzy_opt_out.md
Labels: cla-signed, release notes

#4239 Remove Early Access Warning
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
Labels: cla-signed

#4241 Update purchase_object.md
  _docs/_api/objects_filters/purchase_object.md
Labels: cla-signed

#4240 Update custom_event_and_attribute_management.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/custom_event_and_attribute_management.md
Labels: cla-signed

#4245 Revert "GA Fuzzy Opt-Outs"
  _docs/_user_guide/message_building_by_channel/sms/keywords.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/fuzzy_opt_out.md
Labels: cla-signed

#4244 Revert "Add reference to Fuzzy Opt-Out in SMS Opt-Out docs"
  _docs/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md
Labels: cla-signed

#4243 Leftover Deploy Pt. 3 - October 14, 2022
  _docs/_api/objects_filters/purchase_object.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_hidden/other/handbooks.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/custom_event_and_attribute_management.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
  assets/download_file/Braze_Success_and_Support_Services_Handbook_23v16.pdf
Labels: cla-signed, Deploy

#4248 Revert "Revert "Add reference to Fuzzy Opt-Out in SMS Opt-Out docs"" - MERGE 10/17
  _docs/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md
Labels: cla-signed

#4246 Revert "Revert "GA Fuzzy Opt-Outs"" - MERGE 10/17
  _docs/_user_guide/message_building_by_channel/sms/keywords.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/fuzzy_opt_out.md
Labels: cla-signed

#4251 Deploy Pt. 1 - October 17, 2022
  _docs/_user_guide/message_building_by_channel/sms/keywords.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/fuzzy_opt_out.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md
Labels: cla-signed, Deploy

#4253 BD-1663: Edits for external ID rename and remove GA
  _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_remove.md
  _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_rename.md
Labels: cla-signed

#4252 BD-1666: Remove video block mentions
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
Labels: cla-signed

#4254 Update i18n.yml
  _data/i18n.yml
Labels: cla-signed

#4256 BD-1663: Part 2
  _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_remove.md
Labels: cla-signed

#4255 Remove BroadcastReceiver replace with push events
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/customization/custom_event_callback.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_help/release_notes/deprecations.md
  _docs/_help/release_notes/deprecations/custom_broadcast_receiver.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#4259 Link Fix
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md
Labels: cla-signed

#4260 Update custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
Labels: cla-signed

#4262 BD-1664: Remove coming soon notes for NCA and array of object
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
Labels: cla-signed

#4261 Update Shopify Payloads
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
Labels: cla-signed

#4263 Release Notes October
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2022.md
  _docs/_help/release_notes/2022/10_18_22.md
Labels: cla-signed

#4198 BD-1648: New catalogs endpoints EA
  _docs/_api/api_limits.md
  _docs/_api/endpoints/catalogs.md
  _docs/_api/endpoints/catalogs/catalog_items.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/delete_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/patch_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/post_create_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/delete_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/get_catalog_item_details.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/get_catalog_items_details_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/patch_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md
  _docs/_api/endpoints/catalogs/patch_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/post_create_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/synchronous_catalogs.md
  _docs/_api/endpoints/catalogs/synchronous_catalogs/delete_catalog.md
  _docs/_api/endpoints/catalogs/synchronous_catalogs/get_list_catalogs.md
  _docs/_api/endpoints/catalogs/synchronous_catalogs/post_create_catalog.md
  _docs/_api/home.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _layouts/dev_guide.html
  assets/js/broken_redirect_list.js
Labels: cla-signed

#4257 Leftover Deploy Pt. 2 - October 18, 2022
  _data/i18n.yml
  _docs/_api/api_limits.md
  _docs/_api/endpoints/catalogs.md
  _docs/_api/endpoints/catalogs/catalog_items.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/delete_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/patch_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/post_create_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/delete_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/get_catalog_item_details.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/get_catalog_items_details_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/patch_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md
  _docs/_api/endpoints/catalogs/patch_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/post_create_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/synchronous_catalogs.md
  _docs/_api/endpoints/catalogs/synchronous_catalogs/delete_catalog.md
  _docs/_api/endpoints/catalogs/synchronous_catalogs/get_list_catalogs.md
  _docs/_api/endpoints/catalogs/synchronous_catalogs/post_create_catalog.md
  _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_remove.md
  _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_rename.md
  _docs/_api/home.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/customization/custom_event_callback.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2022.md
  _docs/_help/release_notes/2022/10_18_22.md
  _docs/_help/release_notes/deprecations.md
  _docs/_help/release_notes/deprecations/custom_broadcast_receiver.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _layouts/dev_guide.html
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#4264 BD-1671: Remove video block mentions
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2022/9_20_22.md
Labels: cla-signed

#4268 Update catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
Labels: cla-signed

#4269 Update flutter data stream example to point to public repo
  _docs/_developer_guide/platform_integration_guides/flutter/content_cards.md
Labels: cla-signed

#4270 Add additional IAM DND prerequisite and update images
  _docs/_hidden/private_betas/iam_drag_and_drop/create_dnd_iam.md
  assets/img_archive/dnd_iam_background.gif
  assets/img_archive/dnd_iam_liquid.png
  assets/img_archive/dnd_iam_rows_blocks.png
Labels: cla-signed

#4265 BD-1673 and BD-1676: Edits for catalog endpoints
  _docs/_api/endpoints/catalogs.md
  _docs/_api/endpoints/catalogs/catalogs.md
  _docs/_api/endpoints/catalogs/catalogs/synchronous.md
  _docs/_api/endpoints/catalogs/catalogs/synchronous/delete_catalog.md
  _docs/_api/endpoints/catalogs/catalogs/synchronous/get_list_catalogs.md
  _docs/_api/endpoints/catalogs/catalogs/synchronous/post_create_catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
Labels: cla-signed

#4272 update to reflect PII changes
  _docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#4275 BD-1679: Remove email references from Content Block endpoints
  _docs/_api/endpoints/templates/content_blocks_templates/get_see_email_content_blocks_information.md
  _docs/_api/endpoints/templates/content_blocks_templates/post_create_email_content_block.md
  _docs/_api/endpoints/templates/content_blocks_templates/post_update_content_block.md
Labels: cla-signed

#4274 Update custom attribute filters
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
Labels: cla-signed

#4273 Update CLA for Legal
  _docs/_docs_pages/cla.md
Labels: cla-signed

#4271 BD-1674: Clarify details for creating filtered sets
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/filtered_sets.md
  assets/img_archive/catalog_filtered_sets2.png
  assets/img_archive/catalog_filtered_sets3.png
  assets/img_archive/catalog_filtered_sets4.png
Labels: cla-signed

#4278 Updates around CDI 15m sync.
  _docs/_user_guide/data_and_analytics/cloud_ingestion.md
Labels: cla-signed

#4277 Clarify filtered sets usage
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/filtered_sets.md
Labels: cla-signed

#4280 Update custom_events.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
Labels: cla-signed

#4258 added display later to unity config
  _docs/_developer_guide/platform_integration_guides/unity/in-app_messaging.md
Labels: cla-signed

#4284 Update Nokogiri
  Gemfile.lock
  Rakefile
Labels: cla-signed

#4201 Updates to docs from CSM solutions repository
  _docs/_api/api_campaigns.md
  _docs/_user_guide/data_and_analytics/braze_currents.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md
  _docs/_user_guide/engagement_tools/campaigns/faq.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/triggered_action_based.md
  _docs/_user_guide/engagement_tools/canvas/faqs.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/faqs.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/geofence_configuration.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/location_tracking.md
  _docs/_user_guide/engagement_tools/segments/segment_funnels.md
  _docs/_user_guide/message_building_by_channel/sms/best_practices.md
  _docs/_user_guide/message_building_by_channel/sms/best_practices/opt-ins.md
  _docs/_user_guide/message_building_by_channel/webhooks/braze_to_braze_webhooks.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
  assets/img/seg_filter_examples/android.png
  assets/img/seg_filter_examples/both.png
  assets/img/seg_filter_examples/global_control.png
  assets/img/seg_filter_examples/ios.png
  assets/img/seg_filter_examples/moneyspent.png
  assets/img/seg_filter_examples/push_engagement.png
  assets/img/seg_filter_examples/recent_purchase.png
  assets/img/sms/opt-in1.png
  assets/img/sms/opt-in2.png
Labels: cla-signed

#4286 Reference Link Shortening in FAQs
  _docs/_user_guide/message_building_by_channel/sms/faqs.md
Labels: cla-signed

#4288 Updating Voucherify (partner) documention
  _docs/_partners/message_orchestration/channel_extensions/loyalty/voucherify/voucherify_fetching_data_through_braze_connected_content.md
Labels: cla-signed

#4287 Update message_engagement_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#4294 Change nokogiri platform
  Gemfile.lock
Labels: cla-signed

#4292 BD-1675: Add capture example to connected content docs
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
Labels: cla-signed

#4281 Minor Fixes
  _docs/_api/home.md
  _docs/_partners/data_and_infrastructure_agility/wrapper_sdks.md
Labels: cla-signed

#4293 BD-1686: Fix broken KDoc link
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md
  _lang/fr/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md
Labels: cla-signed

#4290 Update Mparticle calculated attribute feed
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_engage.md
Labels: cla-signed

#4296 BD-1689: Link out to Hightouch docs
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/hightouch.md
Labels: cla-signed

#4295 BD-1539: Add details about live SDK version
  _docs/_developer_guide/platform_wide/app_group_configuration.md
  assets/img_archive/App_Setup_API.png
Labels: cla-signed

#4297 BD-1691: Transform table heading to lowercase in user import example
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Labels: cla-signed

#4299 Add CDI reference to user data collection page
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Labels: cla-signed

#4247 DataDog Partnership Docs - EA
  _docs/_hidden/private_betas/datadog.md
  _docs/_hidden/private_betas/tiktok.md
  assets/img/datadog.png
Labels: cla-signed, Braze Partnerships

#4302 Edits for catalog endpoint docs
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md
  _docs/_api/endpoints/catalogs/catalogs/synchronous/post_create_catalog.md
Labels: cla-signed

#4303 BD-1692: Add callout that link templates in drag and drop editor require link aliasing enabled
  _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
Labels: cla-signed

#4304 Update troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/troubleshooting.md
Labels: cla-signed

#4306 Step not ftep
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
Labels: cla-signed

#4305 Edits from KB reports
  _docs/_help/help_articles/api/delete_user.md
  _docs/_help/help_articles/segments.md
  _docs/_help/help_articles/segments/exporting_large_segments.md
  _docs/_help/help_articles/segments/segmentation_logic_with_and_or.md
  _docs/_user_guide/data_and_analytics/export_braze_data/segment_data_to_csv.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/time_based_campaign.md
  _docs/_user_guide/engagement_tools/campaigns/faq.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
  _docs/_user_guide/engagement_tools/canvas/faqs.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/faqs.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/geofence_configuration.md
  _docs/_user_guide/engagement_tools/testing/race_conditions.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/faq.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _includes/campaign_analytics.md
Labels: cla-signed

#4307 BD-1695: Clarify 200 active IAM limit doesn't apply to Canvases
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
Labels: cla-signed

#4309 BD-1694: Google tag manager Image Edit
  assets/img/web-gtm/gtm-initialization-tag.png
Labels: cla-signed

#4070 Updates to Personalized Variant for GA
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md
Labels: cla-signed

#4310 BD-1697: Update report eligibility time
  _docs/_user_guide/data_and_analytics/your_reports/report_builder.md
Labels: cla-signed

#4313 BD-1699: Update SMS message and segment distinction
  _docs/_user_guide/message_building_by_channel/sms/campaign/segments.md
Labels: cla-signed

#4315 Update link_aliasing.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
Labels: cla-signed

#4314 BD-1698: Clarify email whitespace caveat
  _data/i18n.yml
  _docs/_user_guide/message_building_by_channel/email/best_practices/guidelines_and_tips.md
  _docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md
Labels: cla-signed

#4249 Update Getting Started sections
  _docs/_user_guide/engagement_tools/campaigns/getting_started.md
  _docs/_user_guide/engagement_tools/campaigns/getting_started/campaign_basics.md
  _docs/_user_guide/engagement_tools/campaigns/getting_started/understanding_campaign_status.md
  _docs/_user_guide/engagement_tools/canvas/get_started.md
  _docs/_user_guide/engagement_tools/canvas/get_started/canvas_outlines.md
  _docs/_user_guide/engagement_tools/canvas/get_started/the_basics.md
  assets/img_archive/canvas_flow_entry_wizard.png
  assets/img_archive/canvas_flow_step.png
  assets/img_archive/canvas_flow_variants.png
  assets/img_archive/canvas_outline_cart.png
  assets/img_archive/canvas_outline_onboarding.png
  assets/img_archive/canvas_outline_resource.png
  assets/img_archive/canvas_outline_upsell.png
Labels: cla-signed

#4318 Leftover deploy - October 27, 2022
  _data/i18n.yml
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md
  _docs/_api/endpoints/catalogs/catalogs/synchronous/post_create_catalog.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/troubleshooting.md
  _docs/_help/help_articles/api/delete_user.md
  _docs/_help/help_articles/segments.md
  _docs/_help/help_articles/segments/exporting_large_segments.md
  _docs/_help/help_articles/segments/segmentation_logic_with_and_or.md
  _docs/_user_guide/data_and_analytics/export_braze_data/segment_data_to_csv.md
  _docs/_user_guide/data_and_analytics/your_reports/report_builder.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/time_based_campaign.md
  _docs/_user_guide/engagement_tools/campaigns/faq.md
  _docs/_user_guide/engagement_tools/campaigns/getting_started.md
  _docs/_user_guide/engagement_tools/campaigns/getting_started/campaign_basics.md
  _docs/_user_guide/engagement_tools/campaigns/getting_started/understanding_campaign_status.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
  _docs/_user_guide/engagement_tools/canvas/faqs.md
  _docs/_user_guide/engagement_tools/canvas/get_started.md
  _docs/_user_guide/engagement_tools/canvas/get_started/canvas_outlines.md
  _docs/_user_guide/engagement_tools/canvas/get_started/the_basics.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/faqs.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/geofence_configuration.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md
  _docs/_user_guide/engagement_tools/testing/race_conditions.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/guidelines_and_tips.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/faq.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/segments.md
  _docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md
  _includes/campaign_analytics.md
  assets/img/web-gtm/gtm-initialization-tag.png
  assets/img_archive/canvas_flow_entry_wizard.png
  assets/img_archive/canvas_flow_step.png
  assets/img_archive/canvas_flow_variants.png
  assets/img_archive/canvas_outline_cart.png
  assets/img_archive/canvas_outline_onboarding.png
  assets/img_archive/canvas_outline_resource.png
  assets/img_archive/canvas_outline_upsell.png
  assets/js/feedback.js
Labels: cla-signed, Deploy

#4320 BD-1701: Note that Inbound SMS attribution has a one-minute cache
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#4322 Update scim_api_apprendix.md
  _docs/_hidden/misc_reference/scim_api_apprendix.md
Labels: cla-signed

#4324 BD-1702: Remove Content Cards not available OOTB warning
  _includes/campaign_analytics.md
Labels: cla-signed

#4325 BD-1700 and BD-1703: Update catalogs and filtered sets docs
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/filtered_sets.md
Labels: cla-signed

#4326 BD-1704: Typo fix
  _docs/_user_guide/data_and_analytics/tracking/uninstall_tracking.md
Labels: cla-signed

#4317 Exit criteria GA - MERGE 10/31
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/exit_criteria.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#4328 Deploy - October 31, 2022
  _docs/_hidden/misc_reference/scim_api_apprendix.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/tracking/uninstall_tracking.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/exit_criteria.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/filtered_sets.md
  _includes/campaign_analytics.md
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#4329 Remove redirect for exit criteria, change permalink to alias
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/exit_criteria.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#4323 BD-1662: Update Amplitude
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_audiences.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_user_profile_api.md
  assets/img/amplitude10.png
  assets/img/amplitude5.png
  assets/img/amplitude6.png
  assets/img/amplitude7.png
  assets/img/amplitude8.png
  assets/img/amplitude9.png
Labels: cla-signed
