Repository braze-inc/braze-docs, pull requests merged in 2022-02, with the labels that each got.

#3158 Glossary share
  _layouts/glossary_page.html
  assets/css/_glossary_page.scss
  assets/js/highlight.js
Labels: cla-signed

#3161 BD-1248: Clarify case sensitivity in catalogs personalization
  _docs/_hidden/private_betas/catalog.md
Labels: cla-signed

#3162 BD-1249: Clarify delay step expected behavior
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
Labels: cla-signed

#3148 [SDK-2219] Update all docs com_appboy xml fields to com_braze
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_sessions.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/accessibility.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/read_unread_indicators.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/html_rendered_push.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/integration.md
  _docs/_developer_guide/platform_integration_guides/android/sample_apps.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/unity/in-app_messaging.md
  _docs/_developer_guide/platform_integration_guides/unity/news_feed.md
  _docs/_developer_guide/platform_integration_guides/unity/push_notifications/adm_push_notifications.md
  _docs/_developer_guide/platform_integration_guides/xamarin/initial_sdk_setup.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/mobile_integrations.md
Labels: cla-signed

#3165 Update the Max Number of Items Returned in a Filtered Set
  _docs/_hidden/private_betas/catalog.md
Labels: cla-signed

#3163 BD-1247: Link Aliasing 101
  _docs/_hidden/private_betas/link_aliasing101.md
Labels: cla-signed

#3168 Typo fix
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle.md
Labels: cla-signed

#3167 BD-1251: Add example of attachment syntax for email object
  _docs/_api/objects_filters/messaging/email_object.md
Labels: cla-signed

#3166 Partner Edits - Pt. 16
  _docs/_partners/message_orchestration/additional_channels/messaging/messenger.md
  _docs/_partners/message_orchestration/additional_channels/mobile_wallet/passkit.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify.md
  assets/img_archive/fbm-test.png
Labels: cla-signed

#3169 BD-1241: Deltas call out
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/blueconic.md
Labels: cla-signed

#3170 BD-1252: Clarify User Track endpoint messages
  _docs/_api/endpoints/user_data/post_user_track.md
Labels: cla-signed

#3171 Leftover Deploy - February 3, 2022
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_api/objects_filters/messaging/email_object.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_sessions.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/accessibility.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/read_unread_indicators.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/html_rendered_push.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/integration.md
  _docs/_developer_guide/platform_integration_guides/android/sample_apps.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/unity/in-app_messaging.md
  _docs/_developer_guide/platform_integration_guides/unity/news_feed.md
  _docs/_developer_guide/platform_integration_guides/unity/push_notifications/adm_push_notifications.md
  _docs/_developer_guide/platform_integration_guides/xamarin/initial_sdk_setup.md
  _docs/_hidden/private_betas/catalog.md
  _docs/_hidden/private_betas/link_aliasing101.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/blueconic.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle.md
  _docs/_partners/message_orchestration/additional_channels/messaging/messenger.md
  _docs/_partners/message_orchestration/additional_channels/mobile_wallet/passkit.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/mobile_integrations.md
  _layouts/glossary_page.html
  assets/css/_glossary_page.scss
  assets/img_archive/fbm-test.png
  assets/js/highlight.js
Labels: cla-signed, Deploy

#3172 BD-1253: Add callout for Transifex API deprecation
  _docs/_partners/message_personalization/localization/transifex.md
Labels: cla-signed

#3174 BD-1255: Add note for new data types coming this spring
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
Labels: cla-signed

#3175 Moving around Census to appropriate partner catagory
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/census.md
  _docs/_partners/home.md
Labels: cla-signed

#3177 Minor edits to partnership process docs
  _docs/_hidden/wip_partnerships/partnership_template.md
  assets/img/partner_template/partner_merge.png
Labels: cla-signed

#3184 Update creating_a_webhook.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
Labels: cla-signed

#3183 BD-1256: Update Canvas persistent entry properties doc
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md
  assets/img/persistent_entry_properties/PEP1.png
  assets/img/persistent_entry_properties/PEP12.png
Labels: cla-signed

#3185 BD-1258: Add missing Braze instance
  _docs/_user_guide/administrative/access_braze/braze_instances.md
Labels: cla-signed

#3181 Release Notes - March 2022
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2022.md
  _docs/_help/release_notes/2022/february.md
  _docs/_help/release_notes/2022/march.md
Labels: cla-signed

#3155 Update developer_nav.js
  assets/js/developer_nav.js
Labels: cla-signed

#3188 BD-1260: Fix changelog embed config
  _plugins/markdown_embed.rb
Labels: cla-signed

#3176 Deploy - February 8, 2021
  _docs/_api/endpoints.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2022.md
  _docs/_help/release_notes/2022/february.md
  _docs/_help/release_notes/2022/march.md
  _docs/_hidden/wip_partnerships/partnership_template.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/census.md
  _docs/_partners/home.md
  _docs/_partners/message_personalization/localization/transifex.md
  _docs/_user_guide/administrative/access_braze/braze_instances.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/your_reports/engagement_reports.md
  _docs/_user_guide/data_and_analytics/your_reports/reports_overview.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md
  _docs/_user_guide/message_building_by_channel/email/reporting_and_analytics/analytics_glossary.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  _docs/_user_guide/message_building_by_channel/webhooks/understanding_webhooks.md
  _includes/campaign_analytics.md
  _plugins/markdown_embed.rb
  assets/img/partner_template/partner_merge.png
  assets/img/persistent_entry_properties/PEP1.png
  assets/img/persistent_entry_properties/PEP12.png
  assets/js/developer_nav.js
Labels: cla-signed, Deploy

#3182 BD-1215: Revamp Content Card customization docs
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization.md
  _docs/_user_guide/message_building_by_channel/content_cards/customize.md
  assets/img_archive/cc_politer_carousel.png
  assets/img_archive/cc_politer_carousel_android.png
  assets/img_archive/cc_pyrite_crawl.png
  assets/img_archive/cc_pyrite_run.png
  assets/img_archive/cc_pyrite_walk.png
Labels: cla-signed

#3190 BD-1263: Fix link URL
  _docs/_api/basics.md
Labels: cla-signed

#3193 Link Fixes
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/completing_integration.md
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/channel_extensions.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce.md
  _docs/_partners/message_personalization/location/foursquare.md
  _docs/_user_guide/administrative/app_settings/developer_console/api_settings_tab.md
Labels: cla-signed

#3194 BD-1262: Update BlueConic data syncing behavior
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/blueconic.md
Labels: cla-signed

#3195 BD-1267: Clarify custom attribute array length increase
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
Labels: cla-signed

#3196 BD-1264: Add definitions for Contract Details metrics
  _docs/_user_guide/onboarding_with_braze/subscription_and_usage.md
Labels: cla-signed

#3191 BD-1261: Hidden endpoint doc for GET App Group Apps
  _docs/_hidden/private_betas/get_app_group_apps.md
Labels: cla-signed

#3200 Leftover Deploy - February 10, 2022
  _docs/_api/basics.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/completing_integration.md
  _docs/_hidden/private_betas/get_app_group_apps.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/blueconic.md
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/additional_channels/messaging/line.md
  _docs/_partners/message_orchestration/additional_channels/messaging/messenger.md
  _docs/_partners/message_orchestration/channel_extensions.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/yotpo.md
  _docs/_partners/message_personalization/location/foursquare.md
  _docs/_user_guide/administrative/app_settings/developer_console/api_settings_tab.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/message_building_by_channel/content_cards/customize.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/onboarding_with_braze/subscription_and_usage.md
  _includes/campaign_analytics.md
  assets/img/currents-role-arn.png
  assets/img/currents-s3-example.png
  assets/img/data-export-role-arn.png
  assets/img/s3_tech_partners.png
  assets/img_archive/cc_politer_carousel.png
  assets/img_archive/cc_politer_carousel_android.png
  assets/img_archive/cc_pyrite_crawl.png
  assets/img_archive/cc_pyrite_run.png
  assets/img_archive/cc_pyrite_walk.png
  assets/img_archive/line_preview.png
  assets/img_archive/line_segment.png
  assets/img_archive/line_templates.png
Labels: cla-signed, Deploy

#3201 Update intelligent_timing.md
  _docs/_user_guide/intelligence/intelligent_timing.md
Labels: cla-signed

#3204 BD-1268: Update objects with missing doc links
  _docs/_api/objects_filters/aliases_to_identify.md
  _docs/_api/objects_filters/event_object.md
  _docs/_api/objects_filters/messaging/email_object.md
  _docs/_api/objects_filters/purchase_object.md
  _docs/_api/objects_filters/user_attributes_object.md
Labels: cla-signed

#3140 Knak Partnership Docs
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/channel_extensions.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/knak.md
  assets/img/knak/integration-post-step-1-sync.png
  assets/img/knak/integration-post-step-2-asset-name.png
  assets/img/knak/integration-setup-step-2-add-new-integration.png
  assets/img/knak/integration-setup-step-4-add-api-key.png
Labels: cla-signed, Braze Partnerships

#3186 Wyng Partnership Docs
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content.md
  _docs/_partners/message_personalization/dynamic_content/wyng.md
  assets/img/wyng/10.png
  assets/img/wyng/11.png
  assets/img/wyng/12.png
  assets/img/wyng/14.png
  assets/img/wyng/15.jpg
  assets/img/wyng/16.jpg
  assets/img/wyng/2.png
  assets/img/wyng/3.png
  assets/img/wyng/4.png
  assets/img/wyng/5.png
  assets/img/wyng/6.png
  assets/img/wyng/8.png
  assets/img/wyng/9.png
Labels: cla-signed, Braze Partnerships

#3149 Clarisights Partnership Docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/analytics.md
  _docs/_partners/data_and_infrastructure_agility/analytics/clarisights.md
  _docs/_partners/home.md
  assets/img/clarisights/braze_flow.png
  assets/img/clarisights/braze_report.png
  assets/img/clarisights/connected.png
  assets/img/clarisights/granular_reporting.png
  assets/img/clarisights/integrations.png
  assets/img/clarisights/overall_view.png
  assets/img/clarisights/unified_dashboard.png
Labels: cla-signed, Braze Partnerships

#3210 Update post_users_segment.md
  _docs/_api/endpoints/export/user_data/post_users_segment.md
Labels: cla-signed

#3189 Lexer Partnership Docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/lexer.md
  _docs/_partners/home.md
  assets/img/lexer/braze_integrate_screen.png
  assets/img/lexer/lexer.png
  assets/img/lexer/lexer_logo.png
Labels: cla-signed, Braze Partnerships

#3212 Update Puma dependencies
  Gemfile.lock
Labels: cla-signed

#3207 Toovio - Partner Docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/toovio.md
  _docs/_partners/home.md
Labels: cla-signed, Braze Partnerships

#3206 Partner Edits Pt. 19
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/google_cloud_storage_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/microsoft_azure_blob_storage_for_currents.md
  assets/img/gcs1.png
  assets/img/gcs3.png
  assets/img/gcs4.png
  assets/img/gcs5.png
  assets/img/gcs6.png
  assets/img/google_cloud_storage.png
  assets/img/maz.png
Labels: cla-signed

#3134 Roku IAMs
  _docs/_developer_guide/platform_integration_guides/roku/in-app_messaging.md
  _docs/_developer_guide/platform_integration_guides/roku/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/roku/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/roku/initial_sdk_setup.md
  _docs/_developer_guide/platform_wide/tv_and_ott.md
  assets/img/roku/1-Platform-Selector.png
  assets/img/roku/Docs-Imagery.png
  assets/img/roku/Roku-In-App-Messages-Example.png
  assets/img/roku/Roku-In-App-Messages-Flow.png
Labels: cla-signed

#3211 Add looker action troubleshooting
  _docs/_partners/data_and_infrastructure_agility/analytics/looker.md
Labels: cla-signed

#3218 Remove the opt-in note about HTML V2 which is GA
  _docs/_user_guide/message_building_by_channel/in-app_messages/preview.md
Labels: cla-signed

#3217 BD-1269: Updates to Movable Ink
  _docs/_partners/message_personalization/dynamic_content/movable_ink.md
Labels: cla-signed

#3209 Alt text and link updates - Pt.1
  _docs/_user_guide/administrative/access_braze.md
  _docs/_user_guide/administrative/access_braze/getting_your_account.md
  _docs/_user_guide/administrative/access_braze/portal.md
  _docs/_user_guide/administrative/access_braze/resetting_your_password.md
  _docs/_user_guide/administrative/access_braze/sdk_endpoints.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/okta.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/onelogin.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/set_up.md
  _docs/_user_guide/administrative/app_settings/developer_console/api_settings_tab.md
  _docs/_user_guide/administrative/app_settings/developer_console/event_user_log_tab.md
  _docs/_user_guide/administrative/app_settings/developer_console/internal_groups_tab.md
  _docs/_user_guide/administrative/app_settings/developer_console/message_activity_log_tab.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/app_group_management.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/custom_event_and_attribute_management.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/push_ttl_settings.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/tags.md
  _docs/_user_guide/administrative/company_settings.md
  _docs/_user_guide/administrative/company_settings/contact_information.md
  _docs/_user_guide/administrative/company_settings/security_settings.md
  _docs/_user_guide/administrative/manage_your_braze_users/adding_users_to_your_dashboard.md
  _docs/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md
  _docs/_user_guide/administrative/manage_your_braze_users/deleting_users_from_your_account.md
  _docs/_user_guide/administrative/manage_your_braze_users/teams.md
  _docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/short_and_long_codes.md
  _docs/_user_guide/onboarding_with_braze/data_points.md
  _docs/_user_guide/onboarding_with_braze/email_setup.md
  _docs/_user_guide/onboarding_with_braze/email_setup/consent_and_address_collection.md
  _docs/_user_guide/onboarding_with_braze/email_setup/deliverability_pitfalls_and_spam_traps.md
  _docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md
  _docs/_user_guide/onboarding_with_braze/email_setup/import_your_email_list.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ip_warming.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl/ssl_clicktracking.md
  _docs/_user_guide/onboarding_with_braze/integration.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/about_sms.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/short_and_long_codes.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/sms_laws_and_regulations.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/sms_sending.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/sms_subscription_groups.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/terms.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/user_data_migration.md
  _docs/_user_guide/onboarding_with_braze/spam_regulations.md
  _docs/_user_guide/onboarding_with_braze/subscription_and_usage.md
  _docs/_user_guide/onboarding_with_braze/terms_to_know.md
  _docs/_user_guide/onboarding_with_braze/web_sdk.md
  _includes/archive/short_and_long_codes.md
  assets/img/email_settings/bcc_address.png
  assets/img/torchie/firebrands.png
  assets/img_archive/app_group_list.png
Labels: cla-signed

#3220 BD-1273: Update User Update Step
  _docs/_hidden/private_betas/canvas_user_update.md
Labels: cla-signed

#3222 BD-1277: Increase exposure of nested objects
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/custom_data/nested_object_support.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  assets/img/segment/segment_extension9.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#3223 Added braze_id CSV import option
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Labels: cla-signed

#3225 BD-1274: Updating iOS CC property caveats
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/data_model.md
Labels: cla-signed

#3226 BD-1275: Updates to get_campaign_analytics example
  _docs/_api/endpoints/export/campaigns/get_campaign_analytics.md
Labels: cla-signed

#3227 BD-1278: Add Ruby client library to API docs
  _docs/_api/basics.md
Labels: cla-signed

#3229 Site contrast update
  assets/css/_docs_search.scss
  assets/css/_header.scss
  assets/css/_header_search.scss
  assets/css/_navigation_menu.scss
  assets/css/main.scss
  assets/css/search_main.scss
  assets/css/search_page.scss
Labels: cla-signed

#3221 BD-1276: Update Link Aliasing
  _docs/_hidden/private_betas/link_aliasing.md
  assets/img/link_aliasing_segmentation_filters.png
Labels: cla-signed

#3230 Fix broken push data key links
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
Labels: cla-signed

#3232 Update index.md
  _docs/_docs_pages/index.md
Labels: cla-signed

#3236 BD-1280: Android Push Error Link Fix
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/troubleshooting.md
  _docs/_help/help_articles/push/push_error_codes.md
Labels: cla-signed

#3197 Push subscription state and enablement edits
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
Labels: cla-signed

#3239 BD-1283: Updates to data retention page
  _docs/_api/data_retention.md
Labels: cla-signed

#3240 BD-1282: MacOS support update
  _docs/_developer_guide/platform_integration_guides/macOS/initial_sdk_setup.md
Labels: cla-signed

#3241 BD-1279: CC Cache caveat
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
Labels: cla-signed

#3242 Typo fix
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/in-app_message_delivery.md
Labels: cla-signed

#3247 Update taxi_for_email.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/taxi_for_email.md
Labels: cla-signed

#3248 Updates to pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla-signed

#3249 Adding Roku SDK to SDK changelog list
  _docs/_developer_guide/platform_integration_guides/sdk_changelogs.md
  assets/img/roku.png
Labels: cla-signed

#3235 Standardizing creating a (messaging channel) articles
  _docs/_hidden/private_betas/canvas_in-app_messages.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/create.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  assets/img/sms_campaign_compose.png
  assets/img/sms_campaign_test.png
  assets/img/webhook_JSON1.png
  assets/img/webhook_json_1.png
  assets/img_archive/Webhook_Request_Header.png
  assets/img_archive/cc_steppington_banner.png
  assets/img_archive/cc_steppington_captioned.png
  assets/img_archive/cc_steppington_classic.png
  assets/img_archive/iam_compose.png
  assets/img_archive/push_compose.png
  assets/img_archive/webhook_compose.png
  assets/img_archive/webhook_rawtext.png
  assets/img_archive/webhook_request_header.png
Labels: cla-signed

#3245 Alt and link text edits - Help section - Pt. 1
  _docs/_help/help_articles/account/locked_out.md
  _docs/_help/help_articles/api/delete_user.md
  _docs/_help/help_articles/campaigns_and_canvas/canvas_not_sending.md
  _docs/_help/help_articles/campaigns_and_canvas/conversions_low.md
  _docs/_help/help_articles/campaigns_and_canvas/locations_data_in_campaigns.md
  _docs/_help/help_articles/campaigns_and_canvas/more_people_in_control_group.md
  _docs/_help/help_articles/campaigns_and_canvas/not_triggering.md
  _docs/_help/help_articles/campaigns_and_canvas/using_custom_event_properties.md
  _docs/_help/help_articles/campaigns_and_canvas/using_event_logging.md
  _docs/_help/help_articles/data/dispatch_id.md
  _docs/_help/help_articles/email/email_bounces.md
  _docs/_help/help_articles/email/html_looks_strange.md
  _docs/_help/help_articles/in-app_messages/in-app_messages_not_displaying.md
  _docs/_help/release_notes/2016/august.md
  _docs/_help/release_notes/2016/december.md
  _docs/_help/release_notes/2016/jantomay.md
  _docs/_help/release_notes/2016/july.md
  _docs/_help/release_notes/2016/june.md
  _docs/_help/release_notes/2016/november.md
  _docs/_help/release_notes/2016/october.md
  _docs/_help/release_notes/2016/september.md
  _docs/_help/release_notes/2017/april.md
  _docs/_help/release_notes/2017/august.md
Labels: cla-signed

#3250 Leftover Deploy - February 24, 2022
  .github/PULL_REQUEST_TEMPLATE.md
  _docs/_api/data_retention.md
  _docs/_developer_guide/platform_integration_guides/macOS/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/sdk_changelogs.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/in-app_message_delivery.md
  _docs/_help/help_articles/account/locked_out.md
  _docs/_help/help_articles/api/delete_user.md
  _docs/_help/help_articles/campaigns_and_canvas/canvas_not_sending.md
  _docs/_help/help_articles/campaigns_and_canvas/conversions_low.md
  _docs/_help/help_articles/campaigns_and_canvas/locations_data_in_campaigns.md
  _docs/_help/help_articles/campaigns_and_canvas/more_people_in_control_group.md
  _docs/_help/help_articles/campaigns_and_canvas/not_triggering.md
  _docs/_help/help_articles/campaigns_and_canvas/using_custom_event_properties.md
  _docs/_help/help_articles/campaigns_and_canvas/using_event_logging.md
  _docs/_help/help_articles/data/dispatch_id.md
  _docs/_help/help_articles/email/email_bounces.md
  _docs/_help/help_articles/email/html_looks_strange.md
  _docs/_help/help_articles/in-app_messages/in-app_messages_not_displaying.md
  _docs/_help/release_notes/2016/august.md
  _docs/_help/release_notes/2016/december.md
  _docs/_help/release_notes/2016/jantomay.md
  _docs/_help/release_notes/2016/july.md
  _docs/_help/release_notes/2016/june.md
  _docs/_help/release_notes/2016/november.md
  _docs/_help/release_notes/2016/october.md
  _docs/_help/release_notes/2016/september.md
  _docs/_help/release_notes/2017/april.md
  _docs/_help/release_notes/2017/august.md
  _docs/_hidden/private_betas/canvas_in-app_messages.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/taxi_for_email.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/create.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
  assets/img/roku.png
  assets/img/sms_campaign_compose.png
  assets/img/sms_campaign_test.png
  assets/img/webhook_JSON1.png
  assets/img/webhook_json_1.png
  assets/img_archive/Webhook_Request_Header.png
  assets/img_archive/cc_steppington_banner.png
  assets/img_archive/cc_steppington_captioned.png
  assets/img_archive/cc_steppington_classic.png
  assets/img_archive/iam_compose.png
  assets/img_archive/push_compose.png
  assets/img_archive/webhook_compose.png
  assets/img_archive/webhook_rawtext.png
  assets/img_archive/webhook_request_header.png
Labels: cla-signed, Deploy

#3251 BD-1288: Update user merge behavior
  _docs/_hidden/private_betas/post_user_identify_merge_behavior.md
Labels: cla-signed

#3255 Update message performance screenshots for each channel
  _includes/campaign_analytics.md
  assets/img_archive/email_message_performance.png
  assets/img_archive/iam_message_performance.png
  assets/img_archive/push_message_performance.png
  assets/img_archive/sms_message_performance.png
Labels: cla-signed

#3256 BD-1290: Remove rollout note
  _docs/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md
Labels: cla-signed

#3244 Alt and link text updates - Data and Analytics section
  _docs/_user_guide/data_and_analytics.md
  _docs/_user_guide/data_and_analytics/braze_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/s3_to_snowflake.md
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/transferring_data_to_redshift.md
  _docs/_user_guide/data_and_analytics/creating_a_formula.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/custom_data/event_naming_conventions.md
  _docs/_user_guide/data_and_analytics/custom_data/pre-populating_custom_data.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_apis.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_campaign_results_data.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_canvas_data.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_custom_event_data.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_news_feed_data.md
  _docs/_user_guide/data_and_analytics/export_braze_data/exporting_app_usage_data.md
  _docs/_user_guide/data_and_analytics/export_braze_data/exporting_revenue_data.md
  _docs/_user_guide/data_and_analytics/export_braze_data/opening_csv_reports_in_excel.md
  _docs/_user_guide/data_and_analytics/export_braze_data/segment_data_to_csv.md
  _docs/_user_guide/data_and_analytics/tracking/email_tracking.md
  _docs/_user_guide/data_and_analytics/tracking/influenced_opens.md
  _docs/_user_guide/data_and_analytics/tracking/segment_analytics_tracking.md
  _docs/_user_guide/data_and_analytics/tracking/uninstall_tracking.md
  _docs/_user_guide/data_and_analytics/user_data_collection/collection_use_case.md
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_archival.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
Labels: cla-signed

#3259 Update base URL & improve clarity.
  _docs/_partners/message_orchestration/learning/edume.md
Labels: cla-signed

#3261 BD-1293: Clarify multivariate test with Send Winning Variant
  _docs/_user_guide/engagement_tools/testing/multivariant_testing.md
  assets/img/ab_send_winning_variant.png
Labels: cla-signed

#3263 BD-1287: Update Link Aliasing docs for infinite links
  _docs/_hidden/private_betas/link_aliasing.md
  _docs/_hidden/private_betas/link_aliasing101.md
Labels: cla-signed

#3264 Alt and link text edits - Message Building by Channel - Pt. 1
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/content_cards/creative_details.md
  _docs/_user_guide/message_building_by_channel/content_cards/testing.md
Labels: cla-signed
