Repository braze-inc/braze-docs, pull requests merged in 2022-04, with the labels that each got.

#3401 BD-1328: Update simple survey with choice for logging responses only
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
  assets/img/iam/iam-survey-analytics.png
Labels: cla-signed

#3371 BD-1317: Add article for email performance dashboard
  _docs/_user_guide/data_and_analytics/your_analytics_dashboards.md
  _docs/_user_guide/data_and_analytics/your_analytics_dashboards/email_performance_dashboard.md
  _docs/_user_guide/data_and_analytics/your_analytics_dashboards/understanding_your_app_usage_data.md
  _docs/_user_guide/data_and_analytics/your_reports.md
  assets/img_archive/email_performance_dashboard_1.png
Labels: cla-signed, release notes

#3392 BD-1323: Updates to SMS Retargeting Filters - MERGE 4/4
  _docs/_user_guide/message_building_by_channel/sms/campaign/retargeting.md
  assets/img/sms/clicked_opened_campaign.png
  assets/img/sms/clicked_opened_campaign_canvas_tag.png
  assets/img/sms/clicked_opened_step.png
Labels: cla-signed

#3406 Deploy - April 5, 2022
  _docs/_hidden/private_betas/canvas_user_update.md
  _docs/_user_guide/data_and_analytics/your_analytics_dashboards.md
  _docs/_user_guide/data_and_analytics/your_analytics_dashboards/email_performance_dashboard.md
  _docs/_user_guide/data_and_analytics/your_analytics_dashboards/understanding_your_app_usage_data.md
  _docs/_user_guide/data_and_analytics/your_reports.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/retargeting.md
  assets/img/iam/iam-survey-analytics.png
  assets/img/sms/clicked_opened_campaign.png
  assets/img/sms/clicked_opened_campaign_canvas_tag.png
  assets/img/sms/clicked_opened_step.png
  assets/img_archive/email_performance_dashboard_1.png
Labels: cla-signed

#3409 BD-1333: Clarify regex modifiers in regex debugger callout
  _docs/_user_guide/engagement_tools/segments/regex.md
Labels: cla-signed

#3410 BD-1331: Clarify supported time formats for User attributes object
  _docs/_api/objects_filters/user_attributes_object.md
Labels: cla-signed

#3408 BD-1332: Add note about GCS to users export segment endpoint
  _docs/_api/endpoints/export/user_data/post_users_segment.md
Labels: cla-signed

#3260 Tealium Updates
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
  assets/img/tealium/create_configuration.png
  assets/img/tealium/create_source.png
  assets/img/tealium/data_source.png
  assets/img/tealium/event_specs.png
  assets/img/tealium/get_code.png
  assets/img/tealium/summary_list.png
  assets/img/tealium/track_user_delete.png
  assets/img/tealium/track_user_delete2.png
  assets/img/tealium/track_user_example.jpg
  assets/img/tealium/track_user_example.png
  assets/img/tealium/track_user_example2.png
  assets/img/tealium/update_subscription.png
Labels: cla-signed

#3405 Add May 2022 release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2022.md
  _docs/_help/release_notes/2022/may.md
  _docs/_help/release_notes/deprecations.md
Labels: cla-signed

#3407 Update Crowdin prerequisites endpoint type
  _docs/_partners/message_personalization/localization/crowdin.md
Labels: cla-signed

#3403 BD-1325: Update Catalogs doc
  _docs/_hidden/private_betas/catalog.md
  assets/img_archive/catalog_CSV_upload.png
  assets/img_archive/catalog_data_type.png
  assets/img_archive/catalog_image_link1.png
  assets/img_archive/catalog_image_link2.png
  assets/img_archive/catalog_new_name.png
  assets/img_archive/use_catalog_personalization.png
Labels: status: done, cla-signed

#3411 Deploy Pt. 2 - April 5, 2022
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_api/objects_filters/user_attributes_object.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2022.md
  _docs/_help/release_notes/2022/may.md
  _docs/_help/release_notes/deprecations.md
  _docs/_hidden/private_betas/catalog.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
  _docs/_partners/message_personalization/localization/crowdin.md
  _docs/_user_guide/engagement_tools/segments/regex.md
  assets/img/tealium/create_configuration.png
  assets/img/tealium/create_source.png
  assets/img/tealium/data_source.png
  assets/img/tealium/event_specs.png
  assets/img/tealium/get_code.png
  assets/img/tealium/summary_list.png
  assets/img/tealium/track_user_delete.png
  assets/img/tealium/track_user_delete2.png
  assets/img/tealium/track_user_example.jpg
  assets/img/tealium/track_user_example.png
  assets/img/tealium/track_user_example2.png
  assets/img/tealium/update_subscription.png
  assets/img_archive/catalog_CSV_upload.png
  assets/img_archive/catalog_data_type.png
  assets/img_archive/catalog_image_link1.png
  assets/img_archive/catalog_image_link2.png
  assets/img_archive/catalog_new_name.png
  assets/img_archive/use_catalog_personalization.png
Labels: cla-signed, Deploy

#3413 BD-1327: Update webhooks link in purchase_objects.md to direct to Braze to Braze webhooks
  _docs/_api/objects_filters/purchase_object.md
Labels: cla-signed

#3414 Clarify tile metric layout in email performance dashboard
  _docs/_user_guide/data_and_analytics/your_analytics_dashboards/email_performance_dashboard.md
Labels: cla-signed

#3415 404 Page for API
  _docs/_docs_pages/404_api.md
Labels: cla-signed

#3416 BD-1335: Add image specifications for each channel to Media Library
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
Labels: cla-signed

#3420 Transifex version update language edits
  _docs/_partners/message_personalization/localization/transifex.md
Labels: cla-signed

#3417 Update Android Notification Channel screenshots
  assets/img_archive/Enter_Channel.png
  assets/img_archive/notification_channels.png
Labels: cla-signed

#3421 BD-1337: Email History tab FAQ
  _docs/_hidden/private_betas/email_history.md
Labels: cla-signed

#3422 BD-1338: Talon.One platform updates
  _docs/_partners/message_orchestration/channel_extensions/loyalty/talonone.md
Labels: cla-signed

#3423 IAM Currents deprecated note
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#3424 BD-1339: Update email parameter description in /subscription/status/set endpoint
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
Labels: cla-signed

#3425 Alt link and text edits - Hidden folder
  _docs/_hidden/misc_reference/x-in-y-behavior.md
  _docs/_hidden/other/airship_migration.md
  _docs/_hidden/other/braze faqs.md
  _docs/_hidden/other/core_endpoints.md
  _docs/_hidden/other/generations.md
  _docs/_hidden/other/user_csv_lambda.md
  _docs/_hidden/private_betas/canvas_in-app_messages.md
  _docs/_hidden/private_betas/canvas_user_update.md
  _docs/_hidden/private_betas/get_campaign_url_info.md
  _docs/_hidden/private_betas/get_canvas_url_info.md
  _docs/_hidden/private_betas/link_aliasing.md
  _docs/_hidden/private_betas/view_pii.md
Labels: cla-signed

#3427 BD-1330: Updates Azure/Currents/Export User Segment documentation for Azure data export
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/microsoft_azure_blob_storage_for_currents.md
  assets/img/azure_data_export.png
Labels: cla-signed

#3428 BD-1168: Add Swift Methods for iOS IAM display handling
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization/handing_in_app_display.md
Labels: cla-signed

#3431 Update nokogiri to 1.13.4
  Gemfile.lock
Labels: cla-signed

#3434 Clarify messaging object usage
  _docs/_api/objects_filters/messaging/android_object.md
  _docs/_api/objects_filters/messaging/apple_object.md
  _docs/_api/objects_filters/messaging/content_cards_object.md
  _docs/_api/objects_filters/messaging/email_object.md
  _docs/_api/objects_filters/messaging/kindle_and_fireos_object.md
  _docs/_api/objects_filters/messaging/sms_object.md
  _docs/_api/objects_filters/messaging/web_objects.md
  _docs/_api/objects_filters/messaging/webhook_object.md
  _docs/_api/objects_filters/messaging/windows_objects.md
Labels: cla-signed

#3433 BD-1336: Update SAML SSO setup steps to include RelayState parameter
  _docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/okta.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/onelogin.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/set_up.md
Labels: cla-signed

#3438 BD-1254: Segment FAQ Update
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
Labels: cla-signed

#3440 Remove Action-Based examples from Scheduled bullet
  _docs/_user_guide/engagement_tools/campaigns/getting_started/campaign_basics.md
  _docs/_user_guide/engagement_tools/canvas/get_started/the_basics.md
Labels: cla-signed

#3444 Removing color (red/green) from docs
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
  _docs/_partners/data_and_infrastructure_agility/support/zendesk.md
  _docs/_partners/message_orchestration/attribution/adjust.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _docs/_partners/message_orchestration/attribution/branch/branch_for_attribution.md
  _docs/_partners/message_orchestration/attribution/kochava.md
  _docs/_partners/message_orchestration/attribution/singular.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/taxi_for_email.md
  _docs/_user_guide/message_building_by_channel/email/gmail_promotions_tab.md
  _docs/_user_guide/message_building_by_channel/push/ios/utilizing_badge_count.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/conditional_logic.md
  _docs/_user_guide/predictive_suite/predictive_churn/prediction_analytics.md
  _docs/_user_guide/predictive_suite/predictive_purchases/prediction_analytics.md
Labels: cla-signed

#3435 BD-1319: Canvas V2 101 doc
  _docs/_hidden/private_betas/canvas_v2_101.md
  assets/img_archive/canvas_v2_experience.png
Labels: cla-signed

#3447 Remove directional language: left
  _docs/_api/postman_collection.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/read_and_unread.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/baidu_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/installation_methods/swift_package_manager.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
  _docs/_developer_guide/platform_wide/sending_test_messages.md
  _docs/_hidden/wip_partnerships/partnership_template.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
  _docs/_partners/data_and_infrastructure_agility/support/zendesk.md
  _docs/_partners/message_orchestration/additional_channels/calendar/rokt_calendar.md
  _docs/_partners/message_orchestration/additional_channels/direct_mail/inkit.md
  _docs/_partners/message_orchestration/additional_channels/direct_mail/optilyz.md
  _docs/_partners/message_orchestration/additional_channels/mobile_wallet/passkit.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/tags.md
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/message_building_by_channel/email/inbox_vision.md
Labels: cla-signed

#3443 Update Hightouch permissions and setup instructions
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/hightouch.md
Labels: cla-signed

#3449 Table edits for accessibility
  _docs/_api/endpoints/email/get_list_hard_bounces.md
  _docs/_api/endpoints/email/get_query_unsubscribed_email_addresses.md
  _docs/_api/endpoints/sms/get_query_invalid_numbers.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_api/objects_filters/connected_audience.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/implementation_guide.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_hidden/other/user_csv_lambda.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_user_profile_api.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/adobe.md
Labels: cla-signed

#3430 Create google_play_privacy.md
  _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
Labels: cla-signed

#3452 Update Get Help dropdown
  assets/img/braze_support.png
Labels: cla-signed

#3453 BD-1348: Clarify Inbox Vision requirements
  _docs/_user_guide/message_building_by_channel/email/inbox_vision.md
Labels: cla-signed

#3454 BD-1347: Update Liquid templating example for nested custom attribute
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
Labels: cla-signed

#3450 Update Catalogs doc - EA - 4/19
  _docs/_hidden/private_betas/catalog.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
  assets/img_archive/catalog_multiple_items.png
Labels: cla-signed

#3458 BD-1346: Add warning to external ID migration process
  _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_rename.md
Labels: cla-signed

#3456 Remove directional language: right
  _docs/_developer_guide/platform_integration_guides/android/news_feed/customization/read_and_unread.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/baidu_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization/customizing_feed.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/customization/read_and_unread.md
  _docs/_developer_guide/platform_wide/app_group_configuration.md
  _docs/_help/release_notes/2020/october.md
  _docs/_hidden/other/braze_support.md
  _docs/_hidden/other/user_csv_lambda.md
  _docs/_hidden/private_betas/twilio.md
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
  _docs/_partners/data_and_infrastructure_agility/analytics/npaw.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/adobe.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/amperity.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_personas.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/fivetran.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _docs/_partners/message_personalization/localization/crowdin.md
  _docs/_user_guide/administrative/access_braze/portal.md
  _docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
  _docs/_user_guide/data_and_analytics/your_analytics_dashboards/understanding_your_app_usage_data.md
  _docs/_user_guide/engagement_tools/campaigns/getting_started/understanding_campaign_status.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _docs/_user_guide/engagement_tools/testing/conversion_correlation.md
  _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
  _docs/_user_guide/message_building_by_channel/email/templates/html_email_template.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/message_format.md
  _docs/_user_guide/message_building_by_channel/sms/sms_subscription_group.md
  _docs/_user_guide/message_building_by_channel/webhooks/webhook_template.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/sms_subscription_groups.md
  _docs/_user_guide/predictive_suite/predictive_churn/creating_a_churn_prediction.md
  _docs/_user_guide/predictive_suite/predictive_purchases/creating_a_purchase_prediction.md
Labels: cla-signed

#3459 Fix a typo
  _docs/_hidden/private_betas/email_history.md
Labels: cla-signed

#3373 iOS push notifications unit testing guide
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/push_story.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/unit_tests.md
Labels: cla-signed

#3462 Fix transactional email alias docs, consolidated
  _docs/_api/api_campaigns/transactional_api_campaign.md
  _docs/_user_guide/message_building_by_channel/email/transactional_message_api_campaign.md
Labels: cla-signed

#3463 Fix YAML typos
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/customization/badges.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/customization/custom_styling.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/customization/key_value_pairs.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/customization/read_and_unread.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/defining_a_news_feed_category.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/integration.md
  _docs/_hidden/other/braze_support.md
  _docs/_partners/message_orchestration/learning/edume.md
  _docs/_partners/message_personalization/localization/transifex.md
  _docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_stories.md
Labels: cla-signed

#3455 BD-1349: Replace apple_push with ios_push
  _docs/_api/endpoints/export/campaigns/get_campaign_analytics.md
  _docs/_api/endpoints/messaging/schedule_messages/post_update_scheduled_messages.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/testing.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/testing.md
  _docs/_developer_guide/platform_wide/sending_test_messages.md
  _docs/_home/templates/post_endpoint.md
Labels: cla-signed

#3474 BD-1349 Pt. 2
  _docs/_api/endpoints/messaging/schedule_messages/post_update_scheduled_messages.md
  _docs/_developer_guide/platform_wide/sending_test_messages.md
Labels: cla-signed

#3467 Update Email settings doc
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
Labels: cla-signed

#3476 BD-1355: Clarify Canvas entry properties object size limit
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
  _docs/_api/objects_filters/canvas_entry_properties_object.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
Labels: cla-signed

#3475 Add FAQ entry about audience vs. trigger behavior
  _docs/_user_guide/engagement_tools/campaigns/faq.md
  _docs/_user_guide/engagement_tools/canvas/faqs.md
Labels: cla-signed

#3477 Email preference center documentation
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#3470 Leftover Deploy - April 21, 2022
  _docs/_api/endpoints/export/campaigns/get_campaign_analytics.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
  _docs/_api/objects_filters/canvas_entry_properties_object.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/baidu_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/testing.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/testing.md
  _docs/_developer_guide/platform_integration_guides/roku/changelog.md
  _docs/_developer_guide/platform_integration_guides/web/changelog.md
  _docs/_developer_guide/platform_wide/sending_test_messages.md
  _docs/_help/release_notes/deprecations.md
  _docs/_help/release_notes/deprecations/twilio.md
  _docs/_hidden/private_betas/canvas_in-app_messages.md
  _docs/_home/templates/post_endpoint.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  _docs/_user_guide/engagement_tools/campaigns/faq.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/faqs.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _includes/rate_limits.md
  assets/img_archive/baidu_dev_portal.png
  assets/img_archive/baidu_login_dialog.png
  assets/img_archive/baidu_portal.png
  assets/img_archive/baidu_signup.png
Labels: cla-signed, Deploy

#3473 Update fontawesome fonts to v6
  assets/css/fontawesome.css
  assets/fonts/fa-brands-400.eot
  assets/fonts/fa-brands-400.svg
  assets/fonts/fa-brands-400.ttf
  assets/fonts/fa-brands-400.woff
  assets/fonts/fa-brands-400.woff2
  assets/fonts/fa-regular-400.eot
  assets/fonts/fa-regular-400.svg
  assets/fonts/fa-regular-400.ttf
  assets/fonts/fa-regular-400.woff
  assets/fonts/fa-regular-400.woff2
  assets/fonts/fa-solid-900.eot
  assets/fonts/fa-solid-900.svg
  assets/fonts/fa-solid-900.ttf
  assets/fonts/fa-solid-900.woff
  assets/fonts/fa-solid-900.woff2
  assets/fonts/fa-v4compatibility.ttf
  assets/fonts/fa-v4compatibility.woff2
Labels: status: on hold / do not merge, cla-signed, In Review

#3460 Jekyll 4 update
  Gemfile
  Gemfile.lock
Labels: cla-signed

#3478 BD-1359: Gmail promotions center updates
  _docs/_user_guide/message_building_by_channel/email/gmail_promotions_tab.md
  assets/img/copy-gmail-promo-script.gif
  assets/img/copy-gmail-promo-script.png
  assets/img/create-gmail-promo.gif
  assets/img/create-gmail-promo.png
  assets/img/gmail_preview.png
Labels: cla-signed

#3479 Update api_campaigns.md, fixing redundant alias link
  _docs/_api/api_campaigns.md
Labels: cla-signed

#3480 Noting "equals" string filter is case sensitive
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
Labels: cla-signed

#3472 Create Drag & Drop Editor Content Blocks doc - EA
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
  assets/img_archive/dnd_content_block_name.png
  assets/img_archive/dnd_content_block_personalization.png
Labels: cla-signed

#3484 Deploy - April 26, 2022
  Gemfile
  Gemfile.lock
  _docs/_api/api_campaigns.md
  _docs/_hidden/private_betas/campaign_approval.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
  _docs/_user_guide/message_building_by_channel/email/gmail_promotions_tab.md
  assets/css/fontawesome.css
  assets/fonts/fa-brands-400.eot
  assets/fonts/fa-brands-400.svg
  assets/fonts/fa-brands-400.ttf
  assets/fonts/fa-brands-400.woff
  assets/fonts/fa-brands-400.woff2
  assets/fonts/fa-regular-400.eot
  assets/fonts/fa-regular-400.svg
  assets/fonts/fa-regular-400.ttf
  assets/fonts/fa-regular-400.woff
  assets/fonts/fa-regular-400.woff2
  assets/fonts/fa-solid-900.eot
  assets/fonts/fa-solid-900.svg
  assets/fonts/fa-solid-900.ttf
  assets/fonts/fa-solid-900.woff
  assets/fonts/fa-solid-900.woff2
  assets/fonts/fa-v4compatibility.ttf
  assets/fonts/fa-v4compatibility.woff2
  assets/img/copy-gmail-promo-script.gif
  assets/img/copy-gmail-promo-script.png
  assets/img/create-gmail-promo.gif
  assets/img/create-gmail-promo.png
  assets/img/gmail_preview.png
  assets/img_archive/campaign_approval_example.png
  assets/img_archive/dnd_content_block_name.png
  assets/img_archive/dnd_content_block_personalization.png
Labels: cla-signed, Deploy

#3391 Web v4 updates
  _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_sessions.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/tracking_sessions.md
  _docs/_developer_guide/platform_integration_guides/sdk_changelogs.md
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
  _docs/_developer_guide/platform_integration_guides/web/amp_support.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/disabling_tracking.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/tracking_sessions.md
  _docs/_developer_guide/platform_integration_guides/web/browser_extensions.md
  _docs/_developer_guide/platform_integration_guides/web/changelog.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization/badges.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization/custom_ui.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/multiple_feeds.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/refreshing_the_feed.md
  _docs/_developer_guide/platform_integration_guides/web/content_security_policy.md
  _docs/_developer_guide/platform_integration_guides/web/cookies_and_storage.md
  _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization/custom_styling.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization/key_value_pairs.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization/message_dismissal.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization/open_link_in_new_tab.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/customization/badges.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/defining_a_news_feed_category.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/integration.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/alternate_push_domain.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/soft_push_prompt.md
  _docs/_developer_guide/platform_integration_guides/web/smart_tvs.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/tracking_sessions.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
  _docs/_help/release_notes/sdk_changelogs.md
  _docs/_home/styling_test_page.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_user_guide/administrative/access_braze/sdk_endpoints.md
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/location_tracking.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/best_practices/previous_in-app_message_generations.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
  _includes/archive/appboyBridge.md
  _includes/archive/web-v4-rename.md
Labels: cla-signed

#3489 Deploy Pt.2 - April 27, 2022
  _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_sessions.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/tracking_sessions.md
  _docs/_developer_guide/platform_integration_guides/sdk_changelogs.md
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
  _docs/_developer_guide/platform_integration_guides/web/amp_support.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/disabling_tracking.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/tracking_sessions.md
  _docs/_developer_guide/platform_integration_guides/web/browser_extensions.md
  _docs/_developer_guide/platform_integration_guides/web/changelog.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization/badges.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization/custom_ui.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/multiple_feeds.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/refreshing_the_feed.md
  _docs/_developer_guide/platform_integration_guides/web/content_security_policy.md
  _docs/_developer_guide/platform_integration_guides/web/cookies_and_storage.md
  _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization/custom_styling.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization/key_value_pairs.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization/message_dismissal.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization/open_link_in_new_tab.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/customization/badges.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/defining_a_news_feed_category.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/integration.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/alternate_push_domain.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/soft_push_prompt.md
  _docs/_developer_guide/platform_integration_guides/web/smart_tvs.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/tracking_sessions.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
  _docs/_help/release_notes/sdk_changelogs.md
  _docs/_home/styling_test_page.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_user_guide/administrative/access_braze/sdk_endpoints.md
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/location_tracking.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/best_practices/previous_in-app_message_generations.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
  _includes/archive/appboyBridge.md
  _includes/archive/web-v4-rename.md
Labels: cla-signed

#3487 Add machine_open to Data Sharing Schema Docs
  assets/download_file/data-sharing-raw-table-schemas.txt
Labels: cla-signed

#3488 remove references to `logContentCardsDisplayed`
  _docs/_developer_guide/platform_integration_guides/android/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/cordova/content_cards.md
  _docs/_developer_guide/platform_integration_guides/flutter/content_cards.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
  _docs/_developer_guide/platform_integration_guides/unity/content_cards.md
  _docs/_developer_guide/platform_integration_guides/web/browser_extensions.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
Labels: cla-signed

#3490 BD-1366: Typo in /users/export/ids endpoint
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
Labels: cla-signed

#3491 BD-1364: Fix typo in Analytics overview doc
  _docs/_developer_guide/platform_wide/analytics_overview.md
Labels: cla-signed

#3493 BD-1363: Update Country to be listed under minimum integration inste…
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
Labels: cla-signed

#3494 BD-1362: List supported structured data (nested custom attributes and…
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/census.md
Labels: cla-signed

#3499 Update customize.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
Labels: cla-signed

#3497 Update push_stories.md
  _docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_stories.md
Labels: cla-signed

#3486 Replace removed Appboy classes with Braze classes in docs
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/default_feed.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/unity/push_notifications/adm_push_notifications.md
  _docs/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md
  _docs/_user_guide/data_and_analytics/tracking/uninstall_tracking.md
Labels: cla-signed

#3501 BD-1371: Remove header references for email preference center
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#3500 xml example for notification channel name and description
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
Labels: cla-signed

#3507 Removal of Grouparoo partnership
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2022/april.md
  _docs/_help/release_notes/deprecations.md
  _docs/_help/release_notes/deprecations/grouparoo.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation.md
  _docs/_partners/home.md
Labels: cla-signed

#3508 Leftover Deploy - April 28, 2022
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/default_feed.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/cordova/content_cards.md
  _docs/_developer_guide/platform_integration_guides/flutter/content_cards.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/unity/content_cards.md
  _docs/_developer_guide/platform_integration_guides/unity/push_notifications/adm_push_notifications.md
  _docs/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md
  _docs/_developer_guide/platform_integration_guides/web/browser_extensions.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2022/april.md
  _docs/_help/release_notes/deprecations.md
  _docs/_help/release_notes/deprecations/grouparoo.md
  _docs/_hidden/private_betas/canvas_post-launch_edits.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/census.md
  _docs/_partners/home.md
  _docs/_user_guide/data_and_analytics/tracking/uninstall_tracking.md
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
  _docs/_user_guide/intelligence.md
  _docs/_user_guide/intelligence/ai_copywriting.md
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
  _docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_stories.md
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/create.md
  _plugins/jekyll_asset_pipeline.rb
  assets/download_file/data-sharing-raw-table-schemas.txt
  assets/img/ai_copywriter/ai_copywriter_dnd.png
  assets/img/ai_copywriter/ai_copywriter_email.png
  assets/img/ai_copywriter/ai_copywriter_iam.png
  assets/img/ai_copywriter/ai_copywriter_push.png
  assets/img/ai_copywriter/ai_copywriter_sms.png
  assets/img/ai_copywriter/gpt3.png
  assets/img_archive/canvasv2_delete_step_post-launch.png
Labels: cla-signed, Deploy

#3509 replaced html template link
  _docs/_user_guide/message_building_by_channel/in-app_messages/best_practices/previous_in-app_message_generations.md
Labels: cla-signed

#3513 BD-1368: Update Data Points to differentiate manually and automatically collected consumption
  _docs/_user_guide/onboarding_with_braze/data_points.md
Labels: cla-signed

#3515 BD-1374: Clarify time zone for <date> field
  _docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
Labels: cla-signed

#3483 Update permissions for campaign duplication - MERGE 5/3
  _docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#3496 Update header to match braze.com
  _includes/header.html
  assets/css/_braze_header.scss
  assets/css/_doc_guide.scss
  assets/css/_header.scss
  assets/css/main.scss
  assets/js/documents.js
Labels: cla-signed

#3498 BD-1369: Set subscription group status via CSV - MERGE 5/3
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  assets/img/subscription_group_import.png
Labels: cla-signed

#3517 Clarify Movable Ink Step: BD-1373, BD-1376
  _docs/_partners/message_personalization/dynamic_content/movable_ink.md
Labels: cla-signed
