Repository braze-inc/braze-docs, pull requests merged in 2022-11, with the labels that each got.

#4301 EA Shopify Substates - MERGE 11/1
  _docs/_hidden/private_betas/shopify_subscription_states.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/setting_up_shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
Labels: cla-signed

#4331 Update ios_16.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_16.md
Labels: cla-signed

#4333 BD-1682: Generalize `id` examples in Catalogs doc
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  assets/img_archive/catalog_image_link1.png
  assets/img_archive/catalog_multiple_items.png
Labels: cla-signed

#4334 BD-1706 and BD-1707: Updates to filtered sets and User Update step docs
  _docs/_hidden/private_betas/canvas_user_update.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/filtered_sets.md
  assets/img_archive/canvas_user_update_composer.png
  assets/img_archive/canvas_user_update_example.png
  assets/img_archive/canvas_user_update_remove.png
  assets/img_archive/canvas_user_update_test_preview.png
  assets/img_archive/canvas_user_update_update.png
  assets/img_archive/catalog_filtered_sets1.png
  assets/img_archive/catalog_filtered_sets2.png
Labels: cla-signed

#4335 I had the wrong API key reference..
  _docs/_hidden/private_betas/datadog.md
Labels: cla-signed

#4336 BD-1709: Clarify Content Blocks for Drag & Drop Editor functionality
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
Labels: cla-signed

#4338 Update content_blocks.md
  _docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md
Labels: cla-signed

#4342 BD-1712: Update entry properties wording
  _docs/_user_guide/message_building_by_channel/webhooks/braze_to_braze_webhooks.md
Labels: cla-signed

#4341 Updated Iterate documentation for Braze
  _docs/_partners/message_orchestration/channel_extensions/surveys/iterate.md
Labels: cla-signed

#4344 updating for something jon had to strip out
  _docs/_hidden/private_betas/datadog.md
Labels: cla-signed

#4345 Add note about GCS permission
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/google_cloud_storage_for_currents.md
Labels: cla-signed

#4346 BD-1715: Add case sensitive user fields
  _docs/_api/objects_filters/user_attributes_object.md
Labels: cla-signed

#4347 BD-1649: Add approval workflow to permissions page, clarify Publish Cards permission
  _docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_approval.md
Labels: cla-signed

#4350 Update Shopify Payload Examples
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
Labels: cla-signed

#4352 IAM and CC TvOS updates
  _docs/_developer_guide/platform_integration_guides/tvos/content_cards.md
  _docs/_developer_guide/platform_integration_guides/tvos/in-app_messaging.md
  _docs/_developer_guide/platform_integration_guides/tvos/news_feed.md
  _docs/_developer_guide/platform_integration_guides/xamarin/inapp_messages.md
  assets/img/tvos.png
  assets/img/tvos1.png
Labels: cla-signed

#4351 BD-1716: Clarify that all users are eligible for API campaigns
  _docs/_api/api_campaigns.md
  _docs/_user_guide/engagement_tools/testing/global_control_group.md
Labels: cla-signed

#4353 Leftover Deploy - November 3, 2022
  _docs/_api/api_campaigns.md
  _docs/_api/objects_filters/user_attributes_object.md
  _docs/_developer_guide/platform_integration_guides/tvos/content_cards.md
  _docs/_developer_guide/platform_integration_guides/tvos/in-app_messaging.md
  _docs/_developer_guide/platform_integration_guides/tvos/news_feed.md
  _docs/_developer_guide/platform_integration_guides/xamarin/inapp_messages.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_hidden/private_betas/datadog.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/google_cloud_storage_for_currents.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
  _docs/_partners/message_orchestration/channel_extensions/surveys/iterate.md
  _docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_approval.md
  _docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md
  _docs/_user_guide/engagement_tools/testing/global_control_group.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
  _docs/_user_guide/message_building_by_channel/webhooks/braze_to_braze_webhooks.md
  assets/img/tvos.png
  assets/img/tvos1.png
Labels: cla-signed, Deploy

#4355 Fix japanese scroll after changing language
  assets/js/documents.js
Labels: cla-signed

#4360 JJM-Week-of-11-1-22
  _docs/_api/basics.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/testing.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/uninstall_tracking.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/testing.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/uninstall_tracking.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/testing.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/xamarin/initial_sdk_setup.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_developer_guide/platform_wide/app_group_configuration.md
  _docs/_developer_guide/platform_wide/platform_features.md
  _docs/_developer_guide/platform_wide/sending_test_messages.md
  _docs/_help/release_notes/2016/october.md
  _docs/_help/release_notes/2018/january.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/app_group_management.md
  _docs/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md
  _docs/_user_guide/data_and_analytics/configuring_reporting.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/conversion_events.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/conditional_logic.md
Labels: cla-signed

#4356 GlobalLink Translation PR
  _lang/fr/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md
  _lang/fr/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
  _lang/fr/_user_guide/engagement_tools/canvas/create_a_canvas/content-cards_in_canvas.md
  _lang/fr/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _lang/fr/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
  _lang/fr/_user_guide/engagement_tools/canvas/get_started/canvas_outlines.md
  _lang/fr/_user_guide/engagement_tools/canvas/get_started/the_basics.md
  _lang/fr/_user_guide/engagement_tools/canvas/managing_canvases/archiving_canvases.md
  _lang/fr/_user_guide/engagement_tools/canvas/testing_canvases/measuring_and_testing_with_canvas_analytics.md
  _lang/fr/_user_guide/intelligence.md
  _lang/fr/_user_guide/onboarding_with_braze.md
  readme.md
Labels: cla-signed

#4359 GlobalLink Translation PR
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/best_practices/previous_in-app_message_generations.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/create.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/customize/html_in-app_messages.md
Labels: cla-signed

#4358 GlobalLink Translation PR
  _lang/fr/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _lang/fr/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#4363 BD-1722: Clarify Conversion and Funnel Report Discrepancy
  _docs/_user_guide/data_and_analytics/your_reports/funnel_reports.md
Labels: cla-signed

#4365 Update in-app_messaging.md
  _docs/_developer_guide/platform_integration_guides/tvos/in-app_messaging.md
Labels: cla-signed

#4367 DLK-529: add UTC recommendation to cloud ingestion doc
  _docs/_user_guide/data_and_analytics/cloud_ingestion.md
Labels: cla-signed

#4370 BD-1724: Update Migrating from News Feed
  _docs/_user_guide/message_building_by_channel/content_cards/migrating_from_news_feed.md
Labels: cla-signed

#4369 Update App Group Configuration
  _docs/_developer_guide/platform_wide/app_group_configuration.md
  assets/img_archive/add_appgroup.png
Labels: cla-signed

#4373 BD-1725: Update user permissions
  _docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#4375 Update email_settings.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
Labels: cla-signed

#4354 IAM Drag & Drop Editor EA
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/editor_blocks.md
  assets/img_archive/dnd_iam_blocks.png
  assets/img_archive/dnd_iam_column_customization.gif
  assets/img_archive/dnd_iam_create.gif
  assets/img_archive/dnd_iam_rows.png
  assets/img_archive/dnd_iam_rows_blocks.png
Labels: cla-signed

#4378 Update exit criteria doc to hidden
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/exit_criteria.md
Labels: cla-signed

#4377 Feature cdi
  _docs/_user_guide/data_and_analytics/cloud_ingestion.md
Labels: cla-signed

#4374 BD-1723: Update conversion_index field name
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#4343 BD-1713 and BD-1714: Fix Liquid use case examples
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
Labels: cla-signed

#4380 Deploy - November 8, 2022
  _docs/_api/endpoints/catalogs.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/delete_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/patch_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/post_create_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/delete_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/get_catalog_item_details.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/get_catalog_items_details_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/patch_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_management.md
  _docs/_api/endpoints/catalogs/catalog_management/synchronous.md
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/delete_catalog.md
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/get_list_catalogs.md
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md
  _docs/_api/endpoints/catalogs/catalogs/synchronous/get_list_catalogs.md
  _docs/_api/endpoints/catalogs/catalogs/synchronous/post_create_catalog.md
  _docs/_api/home.md
  _docs/_developer_guide/platform_integration_guides/tvos/in-app_messaging.md
  _docs/_developer_guide/platform_wide/app_group_configuration.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  _docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
  _docs/_user_guide/data_and_analytics/your_reports/funnel_reports.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/exit_criteria.md
  _docs/_user_guide/message_building_by_channel/content_cards/migrating_from_news_feed.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/editor_blocks.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
  assets/img/experiment_step/exp_settings.png
  assets/img/experiment_step/experiment_downstream_paths.gif
  assets/img/experiment_step/experiment_step.png
  assets/img/experiment_step/experiment_winning_path.png
  assets/img_archive/add_appgroup.png
  assets/img_archive/dnd_iam_blocks.png
  assets/img_archive/dnd_iam_column_customization.gif
  assets/img_archive/dnd_iam_create.gif
  assets/img_archive/dnd_iam_rows.png
  assets/img_archive/dnd_iam_rows_blocks.png
  assets/img_archive/nca_multi_criteria.png
Labels: cla-signed, Deploy

#4381 Clarify Preference Center Liquid Tag Functionality
  _docs/_user_guide/message_building_by_channel/email/preference_center.md
Labels: cla-signed

#4383 BD-1734: Update push campaign analytics
  _includes/campaign_analytics.md
Labels: cla-signed

#4384 Differentiate between DND editors for email and IAM
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop.md
Labels: cla-signed

#4388 BD-1735: Clarify updating via user import with alias needs both name and label
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Labels: cla-signed

#4385 BD-1732: Update Dynamics 365 segment instructions
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/dynamics_365_customer_insights.md
Labels: cla-signed

#4389 Add redirects for catalog management links
  assets/js/broken_redirect_list.js
Labels: cla-signed

#4387 BD-1721: Add filtered set example
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/filtered_sets.md
  assets/img_archive/catalog_filtered_sets2.png
  assets/img_archive/catalog_filtered_sets3.png
  assets/img_archive/catalog_filtered_sets4.png
  assets/img_archive/catalog_filtered_sets5.png
Labels: cla-signed

#4391 BD-1690: Add note that app badging is handled automatically by Android for push
  _docs/_user_guide/message_building_by_channel/push/ios/utilizing_badge_count.md
Labels: cla-signed

#4386 BD-1733: Add info about integer data types being rounded at large numbers
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
Labels: cla-signed

#4395 [EINFRA-518] Adds the warning to wait two min after /users/track
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
Labels: cla-signed

#4393 Add new Liquid for subscription states
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: cla-signed

#4394 BD-1720: Update Canvas version history doc
  _docs/_hidden/private_betas/canvas_version_history.md
Labels: cla-signed

#4396 Add calendar days vs. days blurb for Delay step
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
Labels: cla-signed

#4399 Fixed broken link
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
Labels: cla-signed

#4397 Leftover Deploy - November 10, 2022
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
  _docs/_hidden/private_betas/canvas_version_history.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/dynamics_365_customer_insights.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop.md
  _docs/_user_guide/message_building_by_channel/email/preference_center.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/detailed_push_preferences.md
  _docs/_user_guide/message_building_by_channel/push/ios/utilizing_badge_count.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/filtered_sets.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  _includes/campaign_analytics.md
  assets/img_archive/catalog_filtered_sets2.png
  assets/img_archive/catalog_filtered_sets3.png
  assets/img_archive/catalog_filtered_sets4.png
  assets/img_archive/catalog_filtered_sets5.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#4400 [SDK-3075] - Update React Native minimum supported version
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Labels: cla-signed

#4402 Update Braze Looker Action docs
  _docs/_partners/data_and_infrastructure_agility/analytics/looker.md
Labels: cla-signed

#4403 BD-1739: Update SCIM endpoint
  _docs/_api/endpoints/scim/post_create_user_account.md
Labels: cla-signed

#4379 EA link Shortening w/ user-level tracking - MERGE 11/14
  _docs/_hidden/private_betas/link_shortening.md
  assets/img/sms/link_shortening10.png
  assets/img/sms/retargeting4.png
  assets/img/sms/retargeting5.png
Labels: cla-signed

#4404 Deploy Pt. 1 - November 14, 2022
  _docs/_api/endpoints/scim/post_create_user_account.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md
  _docs/_developer_guide/platform_integration_guides/flutter/flutter_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/flutter/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _docs/_hidden/private_betas/link_shortening.md
  _docs/_partners/data_and_infrastructure_agility/analytics/looker.md
  _docs/_user_guide/personalization_and_dynamic_content/deep_linking_to_in-app_content.md
  assets/img/sms/link_shortening10.png
  assets/img/sms/retargeting4.png
  assets/img/sms/retargeting5.png
Labels: cla-signed, Deploy

#4382 SDK-3160 ios foreground changes
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#4407 BD-1738: Add note about reasonable network speed for videos in IAMs
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize/video.md
Labels: cla-signed

#4408 Update CODEOWNERS
  .github/CODEOWNERS
Labels: cla-signed

#4412 Edit tip alert for dark mode preview for DND email
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
Labels: cla-signed

#4415 Paragraph and List blocks for Drag & Drop Editor GA
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  assets/img/ai_copywriter/ai_copywriter_dnd.png
  assets/img/dnd/dnd_content.png
Labels: cla-signed

#4416 Remove code owners auto-tag
  .github/CODEOWNERS
Labels: cla-signed

#4417 Deploy Pt.2 – November 15, 2022
  .github/CODEOWNERS
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2022.md
  _docs/_help/release_notes/2022/11_15_22.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/faq.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize/video.md
  assets/img/ai_copywriter/ai_copywriter_dnd.png
  assets/img/dnd/dnd_content.png
Labels: cla-signed, Deploy

#4410 CommonJS Note
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
Labels: cla-signed

#4419 BD-1740 Added additional warnings and stronger language around migrating web push tokens
  _docs/_help/help_articles/push/push_token_migration.md
Labels: cla-signed

#4423 Ck cdi updates 11 16
  _docs/_user_guide/data_and_analytics/cloud_ingestion.md
  assets/img/cloud_ingestion/ingestion_5.png
Labels: cla-signed

#4424 BD-1746: Fix typo
  _docs/_user_guide/engagement_tools/campaigns/faq.md
Labels: cla-signed

#4421 BD-1741: In-app message App Store rating
  _docs/_user_guide/message_building_by_channel/in-app_messages.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/ios_app_rating_prompt.md
  assets/img_archive/app_store_app_review.png
  assets/img_archive/prime_app_review.png
Labels: cla-signed

#4425 BD-1745: Fix broken link
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Labels: cla-signed

#4362 CSM repository doc edits 2 - Pt.1
  _docs/_help/help_articles/data.md
  _docs/_help/help_articles/data/blocklisting_deletion.md
  _docs/_hidden/other/user_csv_lambda.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/best_practices.md
  _docs/_user_guide/message_building_by_channel/email/faq.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
Labels: cla-signed

#4426 Fixed links
  _docs/_developer_guide/platform_integration_guides/unity/in-app_messaging.md
Labels: cla-signed

#4428 BD-1744: Update SCIM endpoints, id field
  _docs/_api/endpoints/scim/get_see_user_account_information.md
  _docs/_api/endpoints/scim/post_create_user_account.md
Labels: cla-signed

#4422 Contentsquare Partnership Docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/analytics.md
  _docs/_partners/data_and_infrastructure_agility/analytics/contentsquare.md
  _docs/_partners/home.md
  assets/img/contentsquare_custom_events.png
Labels: cla-signed, Braze Partnerships

#4340 Sheetlabs Partnership Docs
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content.md
  _docs/_partners/message_personalization/dynamic_content/amazon_personalize.md
  _docs/_partners/message_personalization/dynamic_content/judo.md
  _docs/_partners/message_personalization/dynamic_content/movable_ink.md
  _docs/_partners/message_personalization/dynamic_content/playable.md
  _docs/_partners/message_personalization/dynamic_content/sheetlabs.md
  _docs/_partners/message_personalization/dynamic_content/wyng.md
  _docs/_partners/message_personalization/localization/sheetlabs.md
  _docs/_partners/message_personalization/location.md
Labels: cla-signed, Braze Partnerships

#4405 Tellius Partnership Docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/analytics.md
  _docs/_partners/data_and_infrastructure_agility/analytics/tellius.md
  _docs/_partners/home.md
Labels: cla-signed, Braze Partnerships

#4414 B.Layer Partnership Docs
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/channel_extensions.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/blayer.md
  assets/img/blayer/blayer2.png
  assets/img/blayer/blayer3.png
  assets/img/blayer/blayer4.png
  assets/img/blayer/blayer5.png
  assets/img/blayer/blayer6.png
Labels: cla-signed, Braze Partnerships

#4409 Wunderkind Partnership Docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/analytics.md
  _docs/_partners/data_and_infrastructure_agility/analytics/wunderkind.md
  _docs/_partners/home.md
Labels: cla-signed, Braze Partnerships

#4406 ThoughtSpot Partnership Docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/analytics.md
  _docs/_partners/data_and_infrastructure_agility/analytics/thoughtspot.md
  _docs/_partners/home.md
Labels: cla-signed, Braze Partnerships

#4431 BD-1749: Remove irrelevant uninstall screenshot
  _docs/_user_guide/data_and_analytics/tracking/uninstall_tracking.md
Labels: cla-signed

#4427 Old article audit pt.2
  _docs/_help/help_articles/campaigns_and_canvas/canvas_not_sending.md
  _docs/_help/help_articles/campaigns_and_canvas/locations_data_in_campaigns.md
  _docs/_help/help_articles/campaigns_and_canvas/not_triggering.md
  _docs/_help/help_articles/campaigns_and_canvas/using_custom_event_properties.md
  _docs/_help/help_articles/campaigns_and_canvas/using_event_logging.md
  _docs/_help/help_articles/email/email_bounces.md
  _docs/_user_guide/data_and_analytics/configuring_reporting.md
  _docs/_user_guide/data_and_analytics/custom_data/event_naming_conventions.md
  _docs/_user_guide/data_and_analytics/custom_data/pre-populating_custom_data.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_news_feed_data.md
  _docs/_user_guide/data_and_analytics/export_braze_data/exporting_revenue_data.md
  _docs/_user_guide/data_and_analytics/export_braze_data/opening_csv_reports_in_excel.md
  _docs/_user_guide/data_and_analytics/tracking/email_tracking.md
  _docs/_user_guide/data_and_analytics/tracking/influenced_opens.md
  assets/img/checkbox.png
Labels: cla-signed

#4432 Clarifying metric definition
  _docs/_user_guide/data_and_analytics/your_analytics_dashboards/email_performance_dashboard.md
Labels: cla-signed

#4418 Ada Partnership Docs
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/channel_extensions.md
  _docs/_partners/message_orchestration/channel_extensions/surveys.md
  _docs/_partners/message_orchestration/channel_extensions/surveys/ada.md
  assets/img/ada/ada-braze-1.png
  assets/img/ada/ada-braze-2.png
  assets/img/ada/ada-braze-3.png
  assets/img/ada/ada-braze-4.png
Labels: cla-signed, Braze Partnerships

#4435 Update dynamic image text and email image
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  assets/img_archive/newEmailTest.png
Labels: cla-signed

#4429 BD-1736: Add developer console access instructions on support page
  _docs/_hidden/other/braze_support.md
Labels: cla-signed

#4436 Updates language support list
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/localization.md
  _docs/_user_guide/data_and_analytics/user_data_collection/language_codes.md
Labels: cla-signed

#4438 Fixed links formatting issue
  _docs/_developer_guide/platform_integration_guides/flutter/push_notifications.md
Labels: cla-signed

#4440 Fixed incorrect information about the behavior of an array
  _docs/_developer_guide/platform_wide/platform_features.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
Labels: cla-signed

#4441 Fix Sample SCIM Code
  _docs/_api/endpoints/scim/post_create_user_account.md
Labels: cla-signed

#4442 Fix the Custom Click Handling Link in Android
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
Labels: cla-signed

#4444 BD-1754: Clarify advancement behavior for Canvas Flow
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/advancement.md
Labels: cla-signed

#4445 BD-1756 and BD-1757: Fix typos
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
Labels: cla-signed

#4447 Updating a few landing pages
  _docs/_user_guide/data_and_analytics/export_braze_data.md
  _docs/_user_guide/data_and_analytics/export_braze_data/segment_data_to_csv.md
  _docs/_user_guide/data_and_analytics/tracking.md
  _docs/_user_guide/message_building_by_channel/content_cards.md
  _docs/_user_guide/message_building_by_channel/email.md
  _docs/_user_guide/message_building_by_channel/email/gmail_promotions_tab.md
  _docs/_user_guide/message_building_by_channel/email/templates.md
  _docs/_user_guide/message_building_by_channel/in-app_messages.md
  _docs/_user_guide/message_building_by_channel/push.md
  _docs/_user_guide/message_building_by_channel/push/advanced_push_options.md
  _docs/_user_guide/message_building_by_channel/push/android.md
  _docs/_user_guide/message_building_by_channel/push/ios.md
  _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
  _docs/_user_guide/message_building_by_channel/push/web.md
  _docs/_user_guide/personalization_and_dynamic_content.md
Labels: cla-signed

#4448 Updated the SCIM endpoint documentation with new example requests and responses
  _docs/_api/endpoints/messaging.md
  _docs/_api/endpoints/scim.md
  _docs/_api/endpoints/scim/delete_existing_dashboard_user.md
  _docs/_api/endpoints/scim/get_search_existing_dashboard_user.md
  _docs/_api/endpoints/scim/get_see_user_account_information.md
  _docs/_api/endpoints/scim/post_create_user_account.md
  _docs/_api/endpoints/scim/put_update_existing_user_account.md
Labels: cla-signed

#4449 Update Punchh integration with customer use cases
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh.md
  assets/img/punchh/usecase.png
  assets/img/punchh/usecase1.png
  assets/img/punchh/usecase2.png
  assets/img/punchh/usecase3.png
  assets/img/punchh/usecase4.png
  assets/img/punchh/usecase5.png
  assets/img/punchh/usecase6.png
Labels: cla-signed

#4450 Update Shopify Email and SMS Subscriber GA
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/setting_up_shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
Labels: cla-signed

#4433 CSM Updates 2 - Pt.2
  _docs/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/zoom.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_alerts.md
  assets/img/zoom/zoom1.png
  assets/img/zoom/zoom2.png
  assets/img/zoom/zoom3.png
  assets/img/zoom/zoom4.png
  assets/img/zoom/zoom5.png
  assets/img/zoom/zoom6.png
  assets/img/zoom/zoom7.png
Labels: cla-signed

#4439 Octolis Partnership Docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/octolis.md
  _docs/_partners/home.md
  assets/img/Octolis/Braze_screen1.png
  assets/img/Octolis/Braze_screen2.png
  assets/img/Octolis/Braze_screen3.png
  assets/img/Octolis/Braze_screen4.png
  assets/img/Octolis/Braze_screen5.png
  assets/img/Octolis/braze_scheme.png
Labels: cla-signed, Braze Partnerships

#4452 Fix Octolis image name
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/octolis.md
  assets/img/Octolis/Braze_scheme.png
Labels: cla-signed

#4453 Clarify CLA field and Update Pull Request Template
  .github/PULL_REQUEST_TEMPLATE.md
  _docs/_docs_pages/cla.md
Labels: cla-signed

#4454 BD-1760: Remove line that Content Cards don't support vouchers
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
Labels: cla-signed

#4456 Clean up use cases section
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
Labels: cla-signed

#4455 Remove reference of Braze SDK in Storyly Partner Docs
  _docs/_partners/data_and_infrastructure_agility/cohort_import/storyly.md
Labels: cla-signed

#4458 Update put_update_existing_user_account.md
  _docs/_api/endpoints/scim/put_update_existing_user_account.md
Labels: cla-signed

#4459 BD-1762: Broken links in note and tabs
  _docs/_developer_guide/platform_wide/sdk_authentication.md
Labels: cla-signed

#4460 Misc API updates
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  _docs/_api/endpoints/scim/delete_existing_dashboard_user.md
  _docs/_api/endpoints/scim/get_search_existing_dashboard_user.md
  _docs/_api/endpoints/scim/get_see_user_account_information.md
  _docs/_api/endpoints/scim/post_create_user_account.md
  _docs/_api/endpoints/scim/put_update_existing_user_account.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
  _docs/_api/endpoints/templates/email_templates/post_create_email_template.md
  _includes/rate_limits.md
Labels: cla-signed

#4446 BD-1742: Update filtered sets to selections
  _docs/_user_guide/personalization_and_dynamic_content/catalogs.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/filtered_sets.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/selections.md
  assets/img_archive/catalog_filtered_sets1.png
  assets/img_archive/catalog_filtered_sets2.png
  assets/img_archive/catalog_selections1.png
  assets/img_archive/catalog_selections2.png
  assets/img_archive/catalog_selections4.png
  assets/img_archive/catalog_selections5.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#4461 BD-1711: GTM Content Card integration nuances
  _docs/_developer_guide/platform_integration_guides/web/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
  assets/img/web-gtm/gtm_content_cards.png
Labels: cla-signed

#4420 Dynamic Yield Partnership Docs
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
  _docs/_hidden/wip_partnerships/partnership_template.md
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content.md
  _docs/_partners/message_personalization/dynamic_content/amazon_personalize.md
  _docs/_partners/message_personalization/dynamic_content/dynamic_yield.md
  _docs/_partners/message_personalization/dynamic_content/wyng.md
  assets/img/dynamic_yield/dynamic_yield.png
  assets/img/dynamic_yield/dynamic_yield1.png
  assets/img/dynamic_yield/dynamic_yield2.png
  assets/img/dynamic_yield/dynamic_yield3.png
  assets/img/dynamic_yield/dynamic_yield4.png
  assets/img/dynamic_yield/dynamic_yield5.png
  assets/img/dynamic_yield/dynamic_yield6.png
  assets/img/dynamic_yield/dynamic_yield7.png
Labels: cla-signed, Braze Partnerships

#4463 Deploy - November 29, 2022
  .github/PULL_REQUEST_TEMPLATE.md
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  _docs/_api/endpoints/scim/delete_existing_dashboard_user.md
  _docs/_api/endpoints/scim/get_search_existing_dashboard_user.md
  _docs/_api/endpoints/scim/get_see_user_account_information.md
  _docs/_api/endpoints/scim/post_create_user_account.md
  _docs/_api/endpoints/scim/put_update_existing_user_account.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
  _docs/_api/endpoints/templates/email_templates/post_create_email_template.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
  _docs/_docs_pages/cla.md
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
  _docs/_hidden/wip_partnerships/partnership_template.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/storyly.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/octolis.md
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content.md
  _docs/_partners/message_personalization/dynamic_content/amazon_personalize.md
  _docs/_partners/message_personalization/dynamic_content/dynamic_yield.md
  _docs/_partners/message_personalization/dynamic_content/wyng.md
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/filtered_sets.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/selections.md
  _includes/rate_limits.md
  assets/img/Octolis/Braze_scheme.png
  assets/img/Octolis/Braze_screen1.png
  assets/img/Octolis/Braze_screen2.png
  assets/img/Octolis/Braze_screen3.png
  assets/img/Octolis/Braze_screen4.png
  assets/img/Octolis/Braze_screen5.png
  assets/img/dynamic_yield/dynamic_yield.png
  assets/img/dynamic_yield/dynamic_yield1.png
  assets/img/dynamic_yield/dynamic_yield2.png
  assets/img/dynamic_yield/dynamic_yield3.png
  assets/img/dynamic_yield/dynamic_yield4.png
  assets/img/dynamic_yield/dynamic_yield5.png
  assets/img/dynamic_yield/dynamic_yield6.png
  assets/img/dynamic_yield/dynamic_yield7.png
  assets/img/web-gtm/gtm_content_cards.png
  assets/img_archive/catalog_filtered_sets1.png
  assets/img_archive/catalog_filtered_sets2.png
  assets/img_archive/catalog_selections1.png
  assets/img_archive/catalog_selections2.png
  assets/img_archive/catalog_selections4.png
  assets/img_archive/catalog_selections5.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#4467 Fix a typo
  _docs/_help/help_articles/data/dispatch_id.md
Labels: cla-signed

#4468 BD-1766: Add note about event properties
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
Labels: cla-signed

#4471 Update image bracket
  assets/img/user_profile_process3.png
Labels: cla-signed
