Repository braze-inc/braze-docs, pull requests merged in 2022-09, with the labels that each got.

#4002 Update FAQ's for Link Shortening
  _docs/_hidden/private_betas/link_shortening.md
Labels: cla-signed

#4004 Add caveat for cloning active Canvases
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
Labels: cla-signed

#4006 Add self help FA support
  _layouts/self_help.html
  assets/css/_self_help.scss
Labels: cla-signed

#4007 Update email_setup.md
  _docs/_user_guide/onboarding_with_braze/email_setup.md
Labels: cla-signed

#4005 Landing page tweaks
  _docs/_api/home.md
  _docs/_docs_pages/index.md
  _docs/_help/home.md
  _docs/_user_guide/administrative.md
  _docs/_user_guide/introduction.md
  _docs/_user_guide/message_building_by_channel.md
  _docs/_user_guide/personalization_and_dynamic_content.md
  _docs/_user_guide/predictive_suite.md
  _layouts/api_glossary.html
  assets/css/_glossary_page.scss
  assets/img/new-icons/right-arrow.svg
  assets/img/new-icons/users2.svg
Labels: cla-signed

#4009 Leftover Deploy - September 1, 2022
  _docs/_api/home.md
  _docs/_developer_guide/platform_integration_guides/flutter/changelog.md
  _docs/_developer_guide/platform_integration_guides/react_native/changelog.md
  _docs/_developer_guide/platform_integration_guides/xamarin/ changelog.md
  _docs/_docs_pages/index.md
  _docs/_help/home.md
  _docs/_hidden/private_betas/amphtml.md
  _docs/_hidden/private_betas/link_shortening.md
  _docs/_user_guide/administrative.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
  _docs/_user_guide/introduction.md
  _docs/_user_guide/message_building_by_channel.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/fullscreen.md
  _docs/_user_guide/onboarding_with_braze/email_setup.md
  _docs/_user_guide/personalization_and_dynamic_content.md
  _docs/_user_guide/predictive_suite.md
  _layouts/api_glossary.html
  _layouts/self_help.html
  assets/css/_glossary_page.scss
  assets/css/_self_help.scss
  assets/download_file/Braze-In-App-Message-Design-Templates.zip
  assets/img/full-screen-large-viewport-landscape.png
  assets/img/full-screen-large-viewport.png
  assets/img/full-screen-spec-landscape.png
  assets/img/full-screen-spec.png
  assets/img/new-icons/right-arrow.svg
  assets/img/new-icons/users2.svg
Labels: cla-signed, Deploy

#4012 Segment extension disable daily regeneration notice update
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
Labels: cla-signed

#4010 Update initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
Labels: cla-signed

#4011 Icon fix
  _docs/_user_guide/introduction.md
  assets/img/new-icons/right-arrow.svg
  assets/img/new-icons/right-arrow2.svg
Labels: cla-signed

#4014 Site.baseurl link fixes
  _docs/_api/basics.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_recommend.md
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
Labels: cla-signed

#4015 Update browser_extensions.md
  _docs/_developer_guide/platform_integration_guides/web/browser_extensions.md
Labels: cla-signed

#4016 BD-1565: Update Local part requirements for email validation
  _docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md
Labels: cla-signed

#4013 BD-1570: Hidden page for Shopify create/update
  _docs/_hidden/private_betas/shopify_create_update.md
Labels: cla-signed

#4017 BD-1566: Update Segment replays callout
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
Labels: cla-signed

#4018 BD-1569: Update amplitude recommend cohort sync identifiers
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_recommend.md
  assets/img/amplitude.png
Labels: cla-signed

#4019 BD-1571: Clarify campaign eligibility for local time zone delivery
  _docs/_user_guide/engagement_tools/campaigns/faq.md
Labels: cla-signed

#4021 Fix main search overlay
  assets/css/_docs_search.scss
  vercel.json
Labels: cla-signed

#4023 Make Web Cust Content Card Implementation Clearer
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization/custom_ui.md
Labels: cla-signed

#4024 Shopify create update clarification
  _docs/_hidden/private_betas/shopify_create_update.md
Labels: cla-signed

#4025 braze actions ios version
  _docs/_developer_guide/platform_wide/braze_actions.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
Labels: cla-signed

#4026 BD-1573: Condense redundant content in Creating geofences
  _docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md
Labels: cla-signed

#3991 Personalized variants EA
  _docs/_user_guide/engagement_tools/testing/multivariant_testing.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md
  assets/img_archive/ab_analytics_no_optimization.png
  assets/img_archive/ab_analytics_pv_1.png
  assets/img_archive/ab_analytics_pv_2.png
  assets/img_archive/ab_analytics_pv_initial_test_1.png
  assets/img_archive/ab_analytics_pv_initial_test_2.png
  assets/img_archive/ab_analytics_wv_1.png
  assets/img_archive/ab_analytics_wv_insufficient_confidence.png
  assets/img_archive/ab_personalized_variant.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#4027 Deploy Pt.2 - September 6, 2022
  _docs/_developer_guide/platform_wide/braze_actions.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
  assets/img_archive/ab_analytics_no_optimization.png
  assets/img_archive/ab_analytics_pv_1.png
  assets/img_archive/ab_analytics_pv_2.png
  assets/img_archive/ab_analytics_pv_initial_test_1.png
  assets/img_archive/ab_analytics_pv_initial_test_2.png
  assets/img_archive/ab_analytics_wv_1.png
  assets/img_archive/ab_analytics_wv_insufficient_confidence.png
  assets/img_archive/ab_personalized_variant.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#4029 Update android_13.md
  _docs/_developer_guide/platform_integration_guides/android/android_13.md
Labels: cla-signed

#4032 BD-1572: Updating Amplitude cohort segmentation filter
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#4033 Voucherify updates
  _docs/_partners/message_orchestration/channel_extensions/loyalty/voucherify/voucherify.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/voucherify/voucherify_fetching_data_through_braze_connected_content.md
Labels: cla-signed

#4036 Remove warning about ASCII characters
  _docs/_hidden/private_betas/link_shortening.md
Labels: cla-signed

#4037 BD-1576: Update Changelog - Swift
  _docs/_developer_guide/platform_integration_guides/ios/changelog.md
  _docs/_developer_guide/platform_integration_guides/ios/changelog/objc_changelog.md
  _docs/_developer_guide/platform_integration_guides/ios/changelog/swift_changelog.md
  _docs/_developer_guide/platform_integration_guides/sdk_changelogs.md
  _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
  _plugins/sdk_min_versions_tag.rb
Labels: cla-signed

#3972 TikTok Audience Sync Beta Documentation
  _docs/_hidden/private_betas/tiktok.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  assets/img/tiktok/tiktok1.png
  assets/img/tiktok/tiktok2.png
  assets/img/tiktok/tiktok3.png
  assets/img/tiktok/tiktok4.png
  assets/img/tiktok/tiktok5.png
  assets/img/tiktok/tiktok6.png
  assets/img/tiktok/tiktok7.png
  assets/img/tiktok/tiktok8.png
Labels: cla-signed, Braze Partnerships

#4034 BD-1567: Updates to Drag & Drop Editor docs
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
Labels: cla-signed

#4041 Leftover Deploy - September 8, 2022
  _docs/_developer_guide/platform_integration_guides/android/android_13.md
  _docs/_developer_guide/platform_integration_guides/ios/changelog.md
  _docs/_developer_guide/platform_integration_guides/ios/changelog/objc_changelog.md
  _docs/_developer_guide/platform_integration_guides/ios/changelog/swift_changelog.md
  _docs/_developer_guide/platform_integration_guides/sdk_changelogs.md
  _docs/_developer_guide/platform_integration_guides/web/smart_tvs.md
  _docs/_hidden/private_betas/link_shortening.md
  _docs/_hidden/private_betas/tiktok.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/voucherify/voucherify.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/voucherify/voucherify_fetching_data_through_braze_connected_content.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
  _plugins/sdk_min_versions_tag.rb
  assets/download_file/Braze_Success_and_Support_Services_Handbook_23.pdf
  assets/img/tiktok/tiktok1.png
  assets/img/tiktok/tiktok2.png
  assets/img/tiktok/tiktok3.png
  assets/img/tiktok/tiktok4.png
  assets/img/tiktok/tiktok5.png
  assets/img/tiktok/tiktok6.png
  assets/img/tiktok/tiktok7.png
  assets/img/tiktok/tiktok8.png
Labels: cla-signed, Deploy

#4044 Fix Typo
  _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
Labels: cla-signed

#4045 update versions
  _docs/_developer_guide/platform_wide/braze_actions.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
Labels: cla-signed

#4043 BD-1579: Update avro parameters
  _docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
Labels: cla-signed

#3990 Update push_primer_messages.md
  _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
Labels: cla-signed

#4028 Fuzzy Opt-Out GA - MERGE 9/9
  _docs/_user_guide/message_building_by_channel/sms/keywords.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/fuzzy_opt_out.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md
  assets/img/sms/fuzzy1.jpg
  assets/img/sms/fuzzy2.png
Labels: cla-signed

#4046 Leftover Deploy Pt. 2 - September 9, 2022
  _docs/_developer_guide/platform_wide/braze_actions.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
  _docs/_user_guide/message_building_by_channel/sms/keywords.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/fuzzy_opt_out.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md
  assets/img/sms/fuzzy1.jpg
  assets/img/sms/fuzzy2.png
Labels: cla-signed, Deploy

#4048 BD-1584 and BD-1586: Move uninstall event to message engagement glossary and add note
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#4049 BD-1588: Fix Sendgrid Cloudfront SSL link
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl/ssl_clicktracking.md
Labels: cla-signed

#4051 Update Fuzzy Opt-Out to hidden
  _docs/_user_guide/message_building_by_channel/sms/keywords/fuzzy_opt_out.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md
Labels: cla-signed

#4050 Leftover Deploy Pt. 3 - September 9, 2022
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/fuzzy_opt_out.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl/ssl_clicktracking.md
Labels: cla-signed, Deploy

#4061 Fix gemlock ruby version
  Gemfile
  Gemfile.lock
Labels: cla-signed

#4052 BD-1590: Updated ISO Cert
  _docs/_developer_guide/disclosures/security_qualifications.md
  assets/pdf/Braze_ISO_Cert.pdf
Labels: cla-signed

#4054 Move Language Selector
  _includes/header.html
  assets/css/_braze_header.scss
  assets/js/documents.js
Labels: cla-signed

#4066 BD-1594: Clarify need to select to track links
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
  assets/img/link_management_dnd.png
  assets/img/link_management_html.png
Labels: status: done, cla-signed

#4022 New Testing Canvases doc
  _docs/_user_guide/engagement_tools/canvas/managing_canvases.md
  _docs/_user_guide/engagement_tools/canvas/testing_canvases.md
  _docs/_user_guide/engagement_tools/canvas/testing_canvases/sending_test_canvases.md
  assets/img_archive/canvas_test1.png
  assets/img_archive/canvas_test2.png
Labels: cla-signed

#4062 BD-1591: Update regex cheat sheet to dedicated page
  _docs/_hidden/misc_reference/regex_reference.md
  _docs/_user_guide/engagement_tools/segments/regex.md
  assets/download_file/regex-cheatsheet.pdf
Labels: status: done, cla-signed

#4064 Success and Support Services Handbook Update
  assets/download_file/Braze_Success_and_Support_Services_Handbook_23.pdf
Labels: status: done, cla-signed

#4055 Update personalized variant images with real data
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md
  assets/img_archive/ab_analytics_pv_1.png
  assets/img_archive/ab_analytics_pv_initial_test_2.png
Labels: status: done, cla-signed

#4056 BD-1580: Clarify user data export for Canvas components
  _docs/_user_guide/data_and_analytics/export_braze_data/export_canvas_data.md
Labels: cla-signed

#4053 BD-1560: Shopify Update/Create Doc, GA 9/13
  _docs/_hidden/private_betas/shopify_create_update.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify.md
Labels: status: done, cla-signed

#4059 BD-1582: New Catalogs endpoints - EA
  _docs/_api/endpoints/catalogs.md
  _docs/_api/endpoints/catalogs/delete_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/get_catalog_item_details.md
  _docs/_api/endpoints/catalogs/patch_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/post_create_catalog_items_bulk.md
  _docs/_api/endpoints/email.md
  _docs/_api/endpoints/export.md
  _docs/_api/endpoints/messaging.md
  _docs/_api/endpoints/sms.md
  _docs/_api/endpoints/subscription_groups.md
  _docs/_api/endpoints/templates.md
  _docs/_api/endpoints/user_data.md
  _docs/_api/home.md
  _docs/_user_guide/personalization_and_dynamic_content/catalog.md
Labels: cla-signed

#4072 Removed send_id as a Request Parameter
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_canvases.md
Labels: cla-signed

#4075 Edit limitations for Cloning Canvases doc
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
Labels: cla-signed

#4076 Add feedback note for catalogs endpoints
  _docs/_api/endpoints/catalogs/delete_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/get_catalog_item_details.md
  _docs/_api/endpoints/catalogs/patch_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/post_create_catalog_items_bulk.md
Labels: cla-signed

#4077 Leftover Deploy - September 15, 2022
  _docs/_api/endpoints/catalogs/delete_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/get_catalog_item_details.md
  _docs/_api/endpoints/catalogs/patch_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/post_create_catalog_items_bulk.md
  _docs/_api/endpoints/email/get_list_hard_bounces.md
  _docs/_api/endpoints/email/get_query_unsubscribed_email_addresses.md
  _docs/_api/endpoints/export/campaigns/get_campaign_analytics.md
  _docs/_api/endpoints/export/campaigns/get_campaign_details.md
  _docs/_api/endpoints/export/campaigns/get_campaigns.md
  _docs/_api/endpoints/export/campaigns/get_send_analytics.md
  _docs/_api/endpoints/export/canvas/get_canvas_analytics.md
  _docs/_api/endpoints/export/canvas/get_canvas_analytics_summary.md
  _docs/_api/endpoints/export/canvas/get_canvas_details.md
  _docs/_api/endpoints/export/canvas/get_canvases.md
  _docs/_api/endpoints/export/custom_events/get_custom_events.md
  _docs/_api/endpoints/export/custom_events/get_custom_events_analytics.md
  _docs/_api/endpoints/export/kpi/get_kpi_daily_new_users_date.md
  _docs/_api/endpoints/export/kpi/get_kpi_dau_date.md
  _docs/_api/endpoints/export/kpi/get_kpi_mau_30_days.md
  _docs/_api/endpoints/export/kpi/get_kpi_uninstalls_date.md
  _docs/_api/endpoints/export/news_feed/get_news_feed_card_analytics.md
  _docs/_api/endpoints/export/news_feed/get_news_feed_card_details.md
  _docs/_api/endpoints/export/news_feed/get_news_feed_cards.md
  _docs/_api/endpoints/export/purchases/get_list_product_id.md
  _docs/_api/endpoints/export/segments/get_segment.md
  _docs/_api/endpoints/export/segments/get_segment_analytics.md
  _docs/_api/endpoints/export/segments/get_segment_details.md
  _docs/_api/endpoints/export/sessions/get_sessions_analytics.md
  _docs/_api/endpoints/messaging/schedule_messages/get_messages_scheduled.md
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_messages.md
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_canvases.md
  _docs/_api/endpoints/messaging/send_messages/post_create_send_ids.md
  _docs/_api/endpoints/sms/get_query_invalid_numbers.md
  _docs/_api/endpoints/templates/content_blocks_templates/get_list_email_content_blocks.md
  _docs/_api/endpoints/templates/content_blocks_templates/get_see_email_content_blocks_information.md
  _docs/_api/endpoints/templates/content_blocks_templates/post_create_email_content_block.md
  _docs/_api/endpoints/templates/content_blocks_templates/post_update_content_block.md
  _docs/_api/endpoints/templates/email_templates/get_list_email_templates.md
  _docs/_api/endpoints/templates/email_templates/get_see_email_template_information.md
  _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_remove.md
  _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_rename.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
  readme.md
Labels: Deploy

#4078 Updating API template reference pages
  _docs/_home/templates/get_endpoint.md
  _docs/_home/templates/post_endpoint.md
  _docs/_home/templates_old/api_glossary.md
  _docs/_home/templates_old/glossary_test_page.md
  _docs/_home/templates_old/help_article_template.md
  _docs/_home/templates_old/landing_images.md
  _docs/_home/templates_old/landing_multiple.md
  _docs/_home/templates_old/landing_multiple_images.md
  _docs/_home/templates_old/landing_single.md
  _docs/_home/templates_old/partner_page_template.md
  _docs/_home/templates_old/partner_page_template_video.md
  _docs/_home/templates_old/reference.md
  _docs/_home/templates_old/reference_video.md
  _docs/_home/templates_old/solution.md
  _docs/_home/templates_old/tutorial.md
  _docs/_home/templates_old/tutorial_video.md
  _docs/_home/templates_old/use_case.md
  _docs/_home/templates_old/use_case_video.md
Labels: cla-signed

#4079 BD-1599: Liquid 5 GA
  _docs/_user_guide/personalization_and_dynamic_content/liquid.md
Labels: cla-signed

#3995 BD-1561: View PII Updates
  _docs/_hidden/private_betas/view_pii.md
  _docs/_user_guide/administrative/company_settings/security_settings.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#4082 EA Link Shortening docs moved to public section
  _docs/_home/templates/get_endpoint.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
Labels: cla-signed

#4083 Deploy Pt.1 - September 19. 2022
  _docs/_hidden/private_betas/view_pii.md
  _docs/_home/templates/get_endpoint.md
  _docs/_home/templates/post_endpoint.md
  _docs/_home/templates_old/api_glossary.md
  _docs/_home/templates_old/glossary_test_page.md
  _docs/_home/templates_old/help_article_template.md
  _docs/_home/templates_old/landing_images.md
  _docs/_home/templates_old/landing_multiple.md
  _docs/_home/templates_old/landing_multiple_images.md
  _docs/_home/templates_old/landing_single.md
  _docs/_home/templates_old/partner_page_template.md
  _docs/_home/templates_old/partner_page_template_video.md
  _docs/_home/templates_old/reference.md
  _docs/_home/templates_old/reference_video.md
  _docs/_home/templates_old/solution.md
  _docs/_home/templates_old/tutorial.md
  _docs/_home/templates_old/tutorial_video.md
  _docs/_home/templates_old/use_case.md
  _docs/_home/templates_old/use_case_video.md
  _docs/_user_guide/administrative/company_settings/security_settings.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid.md
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#4081 Update email_performance_dashboard.md
  _docs/_user_guide/data_and_analytics/your_analytics_dashboards/email_performance_dashboard.md
Labels: cla-signed

#4084 Fuzzy Opt-Out GA
  _docs/_user_guide/message_building_by_channel/sms/keywords/fuzzy_opt_out.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md
Labels: cla-signed

#4085 Revert "Fuzzy Opt-Out GA"
  _docs/_user_guide/message_building_by_channel/sms/keywords/fuzzy_opt_out.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md
Labels: cla-signed

#4087 Update integration.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/integration.md
Labels: cla-signed

#4047 BD-1585: Update data retention doc with Canvas Interactions [MERGE 9/21]
  _docs/_api/data_retention.md
Labels: cla-signed

#4091 Update ios_16.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_16.md
Labels: cla-signed

#4088 Update branch_for_attribution.md
  _docs/_partners/message_orchestration/attribution/adjust.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _docs/_partners/message_orchestration/attribution/branch/branch_for_attribution.md
  _docs/_partners/message_orchestration/attribution/singular.md
  _lang/fr/_partners/message_orchestration/attribution/adjust.md
  _lang/fr/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _lang/fr/_partners/message_orchestration/attribution/branch/branch_for_attribution.md
  _lang/fr/_partners/message_orchestration/attribution/singular.md
Labels: cla-signed

#3745 replaced hard-coded versions
  _docs/_developer_guide/platform_integration_guides/web/amp_support.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/alternate_push_domain.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/soft_push_prompt.md
Labels: cla-signed

#4092 Update create_multivariate_campaign.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
Labels: cla-signed

#4089 Clarify card creation for new and anonymous users in recurring campaigns
  _docs/_hidden/private_betas/card_creation.md
Labels: cla-signed

#4090 BD-1602: Preference Center test message behavior
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#4086 September release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2022.md
  _docs/_help/release_notes/2022/9_20_22.md
Labels: cla-signed

#4094 Documenting anonymous user device_id
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
Labels: cla-signed

#4095 Add period to sentence
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2022/9_20_22.md
Labels: cla-signed

#4096 BD-1603: Fix quotes in Liquid example
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
Labels: cla-signed

#4097 Revert "BD-1595: Update Delay step with difference between days and calendar days"
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
Labels: cla-signed

#4098 Update image for User Update
  assets/img_archive/canvas_user_update_composer.png
Labels: cla-signed

#4100 BD-1609: Fix LG Web OS Link
  _docs/_developer_guide/platform_wide/tv_and_ott.md
Labels: cla-signed

#4065 BD-1583: Add new email open segmentation filters
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#4101 Shopify Header Fix
  _docs/_hidden/private_betas/shopify_subscription_states.md
Labels: cla-signed

#4102 BD-1610: Add SMS properties for Message step callout
  _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/retargeting.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
Labels: cla-signed

#4104 BD-1612: Update user permissions table
  _docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#4105 Error fix
  _docs/_home/templates/get_endpoint.md
  _docs/_home/templates/post_endpoint.md
Labels: cla-signed

#4107 BD-1617: Clarify TvOS Push Support
  _docs/_developer_guide/platform_wide/tv_and_ott.md
Labels: cla-signed

#4110 BD-1601: Update IAM behavior to account for Android 13
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization/custom_triggering.md
Labels: cla-signed

#4112 Custom UI -> Headless UI
  _docs/_developer_guide/platform_wide/tv_and_ott.md
Labels: cla-signed

#4113 Extole update
  _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
  assets/img/extole/extole-outbound-webhooks.png
Labels: cla-signed

#4111 BD-1615: Update channel performance dashboard with SMS metrics
  _docs/_user_guide/data_and_analytics/your_analytics_dashboards/email_performance_dashboard.md
Labels: cla-signed

#4114 Leftover deploy - October 22, 2022
  _docs/_developer_guide/disclosures/innovation_statement.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization/custom_triggering.md
  _docs/_developer_guide/platform_wide/tv_and_ott.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2022/9_20_22.md
  _docs/_hidden/private_betas/shopify_subscription_states.md
  _docs/_home/templates/get_endpoint.md
  _docs/_home/templates/post_endpoint.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
  _docs/_user_guide/administrative/company_settings/security_settings.md
  _docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/data_and_analytics/your_analytics_dashboards/email_performance_dashboard.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/retargeting.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
  assets/img/extole/extole-outbound-webhooks.png
  assets/img_archive/canvas_user_update_composer.png
Labels: cla-signed, Deploy

#4115 BD-1616: Add Canvas Flow steps limit
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/faqs.md
Labels: cla-signed

#4116 Fix Code Type
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization/custom_ui.md
Labels: cla-signed

#4117 Changed in-app message display considerations
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
Labels: cla-signed

#4118 react native docs
  _docs/_developer_guide/platform_integration_guides/react_native/analytics.md
Labels: cla-signed

#4119 SSR and Vite
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
Labels: cla-signed

#4106 BD-1605: Document Messaging History tab of user profile [MERGE 9/27]
  _docs/_hidden/private_betas/email_history.md
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
  _docs/_user_guide/engagement_tools/segments/using_user_search.md
  assets/img_archive/profiles_engagement_tab.png
  assets/img_archive/profiles_messaging_history_tab.png
  assets/img_archive/profiles_multiple_results.png
  assets/img_archive/profiles_overview_tab.png
  assets/img_archive/profiles_social_tab.png
  assets/img_archive/profiles_social_tab_old.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, release notes

#4080 BD-1600: Content Blocks for Drag & Drop Editor GA
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
Labels: cla-signed

#4030 Slightly Clarify Race Condition Docs
  _docs/_user_guide/engagement_tools/testing/race_conditions.md
Labels: cla-signed

#4122 Add locale filter
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#4124 SCIM endpoint updates
  _docs/_hidden/private_betas/scim.md
  _docs/_hidden/private_betas/scim/delete_existing_dashboard_user.md
  _docs/_hidden/private_betas/scim/get_see_developer_account_information.md
  _docs/_hidden/private_betas/scim/get_see_user_account_information.md
  _docs/_hidden/private_betas/scim/post_create_developer_account.md
  _docs/_hidden/private_betas/scim/post_create_user_account.md
  _docs/_hidden/private_betas/scim/put_update_existing_developer_account.md
  _docs/_hidden/private_betas/scim/put_update_existing_user_account.md
  _docs/_hidden/private_betas/scim/scim_api_appendix.md
  _docs/_user_guide/administrative/company_settings/automated_user_provisioning.md
  _includes/rate_limits.md
Labels: cla-signed

#4126 BD-1624: Add character limit for User Update
  _docs/_hidden/private_betas/canvas_user_update.md
Labels: cla-signed

#4128 Updating API landing page
  assets/css/_glossary_page.scss
Labels: cla-signed

#4121 Path Entry and Conversions Message Engagement Events
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#4125 Deploy - September 27, 2022
  _docs/_developer_guide/platform_integration_guides/react_native/analytics.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization/custom_ui.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_hidden/private_betas/canvas_user_update.md
  _docs/_hidden/private_betas/email_history.md
  _docs/_hidden/private_betas/scim.md
  _docs/_hidden/private_betas/scim/delete_existing_dashboard_user.md
  _docs/_hidden/private_betas/scim/get_see_developer_account_information.md
  _docs/_hidden/private_betas/scim/get_see_user_account_information.md
  _docs/_hidden/private_betas/scim/post_create_developer_account.md
  _docs/_hidden/private_betas/scim/post_create_user_account.md
  _docs/_hidden/private_betas/scim/put_update_existing_developer_account.md
  _docs/_hidden/private_betas/scim/put_update_existing_user_account.md
  _docs/_hidden/private_betas/scim/scim_api_appendix.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _docs/_user_guide/administrative/company_settings/automated_user_provisioning.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/faqs.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
  _docs/_user_guide/engagement_tools/segments/using_user_search.md
  _docs/_user_guide/engagement_tools/testing/race_conditions.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _includes/rate_limits.md
  assets/css/_glossary_page.scss
  assets/img_archive/profiles_engagement_tab.png
  assets/img_archive/profiles_messaging_history_tab.png
  assets/img_archive/profiles_multiple_results.png
  assets/img_archive/profiles_overview_tab.png
  assets/img_archive/profiles_social_tab.png
  assets/img_archive/profiles_social_tab_old.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#4130 Updates for nested properties.
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  assets/img/segment/nested_segment_extensions.png
Labels: cla-signed

#4131 Update get_see_user_account_information.md
  _docs/_hidden/private_betas/scim/get_see_user_account_information.md
Labels: cla-signed

#4132 Deploy Pt. 2 - September 27, 2022
  _docs/_hidden/private_betas/scim/get_see_user_account_information.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  assets/img/segment/nested_segment_extensions.png
Labels: cla-signed, Deploy

#4133 BD-1627: Fix broken link
  _docs/_help/release_notes/2022/9_20_22.md
Labels: cla-signed

#3948 Update appboyBridge documentation to include changeUser method
  _includes/archive/appboyBridge.md
Labels: cla-signed

#4137 BD-1628: Update maximum length for arrays
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
Labels: cla-signed

#4138 I missed removing these mentions of early access.
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
Labels: cla-signed

#4136 BD-1623: Add Japanese translation of Innovation Statement
  _docs/_developer_guide/disclosures/innovation_statement.md
Labels: cla-signed

#4135 Update docs for Currents Release 2022-09-27
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
Labels: cla-signed

#4144 Add more clarity to segment extensions and show a screenshot of nested event triggering.
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  assets/img_archive/customEventPropertiesNested.png
Labels: cla-signed

#4157 Typo fix
  _docs/_help/release_notes/2020/august.md
Labels: cla-signed

#4139 GlobalLink Translation PR
  _lang/fr/_user_guide/message_building_by_channel/content_cards/about.md
  _lang/fr/_user_guide/message_building_by_channel/content_cards/best_practices.md
  _lang/fr/_user_guide/message_building_by_channel/content_cards/best_practices/know_before_send.md
  _lang/fr/_user_guide/message_building_by_channel/content_cards/create.md
  _lang/fr/_user_guide/message_building_by_channel/content_cards/creative_details.md
  _lang/fr/_user_guide/message_building_by_channel/content_cards/customize.md
  _lang/fr/_user_guide/message_building_by_channel/content_cards/migrating_from_news_feed.md
  _lang/fr/_user_guide/message_building_by_channel/content_cards/reporting.md
  _lang/fr/_user_guide/message_building_by_channel/content_cards/testing.md
  _lang/fr/_user_guide/message_building_by_channel/email.md
  _lang/fr/_user_guide/message_building_by_channel/email/about.md
  _lang/fr/_user_guide/message_building_by_channel/email/best_practices.md
  _lang/fr/_user_guide/message_building_by_channel/email/best_practices/email_services.md
  _lang/fr/_user_guide/message_building_by_channel/email/best_practices/email_styling.md
  _lang/fr/_user_guide/message_building_by_channel/email/best_practices/guidelines_and_tips.md
  _lang/fr/_user_guide/message_building_by_channel/email/best_practices/know_before_send.md
  _lang/fr/_user_guide/message_building_by_channel/email/best_practices/managing_email_subscriptions.md
  _lang/fr/_user_guide/message_building_by_channel/email/best_practices/sunset_policies.md
  _lang/fr/_user_guide/message_building_by_channel/email/best_practices/use_cases.md
  _lang/fr/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
  _lang/fr/_user_guide/message_building_by_channel/email/css_inline.md
  assets/img_archive/css-inline3.png
Labels: cla-signed

#4158 BD-1630: Fix broken link
  _docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
Labels: cla-signed

#4141 GlobalLink Translation PR
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/about.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/best_practices.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/best_practices/know_before_send.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/best_practices/prep_guide.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/best_practices/previous_in-app_message_generations.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/create.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/creative_details/fullscreen.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/creative_details/modal.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/creative_details/slideup.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/customize.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/customize/color_profiles_and_css.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/customize/email_capture_form.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/customize/html_in-app_messages.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/customize/modal_with_css.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/customize/video.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/dark-mode.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/faq.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/generations.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/reporting.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/templates.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/testing.md
Labels: cla-signed

#4103 Shopify ScriptTag GA
  _docs/_hidden/private_betas/shopify.md
  _docs/_hidden/private_betas/shopify/scripttag_web_sdk_integration.md
  _docs/_hidden/private_betas/shopify/setting_up_shopify.md
  _docs/_hidden/private_betas/shopify/shopify_data.md
  _docs/_hidden/private_betas/shopify/use_cases.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/scripttag_web_sdk_integration.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/setting_up_shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_in_braze.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/use_cases.md
  assets/img/Shopify/checkout_cart_delay.png
Labels: cla-signed

#4142 GlobalLink Translation PR
  _lang/fr/_user_guide/message_building_by_channel/email/drag_and_drop.md
  _lang/fr/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
  _lang/fr/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
  _lang/fr/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
  _lang/fr/_user_guide/message_building_by_channel/email/drag_and_drop/faq.md
  _lang/fr/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _lang/fr/_user_guide/message_building_by_channel/email/email_private_relay_apple_SSO.md
  _lang/fr/_user_guide/message_building_by_channel/email/faq.md
  _lang/fr/_user_guide/message_building_by_channel/email/gmail_promotions_tab.md
  _lang/fr/_user_guide/message_building_by_channel/email/inbox_vision.md
  _lang/fr/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _lang/fr/_user_guide/message_building_by_channel/email/mpp.md
  _lang/fr/_user_guide/message_building_by_channel/email/reporting_and_analytics.md
  _lang/fr/_user_guide/message_building_by_channel/email/reporting_and_analytics/analytics_glossary.md
  _lang/fr/_user_guide/message_building_by_channel/email/reporting_and_analytics/email_reporting.md
  _lang/fr/_user_guide/message_building_by_channel/email/templates.md
  _lang/fr/_user_guide/message_building_by_channel/email/templates/email_template.md
  _lang/fr/_user_guide/message_building_by_channel/email/templates/faq.md
  _lang/fr/_user_guide/message_building_by_channel/email/templates/html_email_template.md
  _lang/fr/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
  _lang/fr/_user_guide/message_building_by_channel/email/templates/link_template.md
  _lang/fr/_user_guide/message_building_by_channel/email/transactional_message_api_campaign.md
Labels: cla-signed

#4140 GlobalLink Translation PR
  _lang/fr/_user_guide/message_building_by_channel/push.md
  _lang/fr/_user_guide/message_building_by_channel/push/about.md
  _lang/fr/_user_guide/message_building_by_channel/push/advanced_push_options.md
  _lang/fr/_user_guide/message_building_by_channel/push/advanced_push_options/push_action_buttons.md
  _lang/fr/_user_guide/message_building_by_channel/push/advanced_push_options/push_stories.md
  _lang/fr/_user_guide/message_building_by_channel/push/android.md
  _lang/fr/_user_guide/message_building_by_channel/push/android/advanced_campaign_settings.md
  _lang/fr/_user_guide/message_building_by_channel/push/android/notification_channels.md
  _lang/fr/_user_guide/message_building_by_channel/push/android/notification_ids.md
  _lang/fr/_user_guide/message_building_by_channel/push/android/notification_options.md
  _lang/fr/_user_guide/message_building_by_channel/push/android/rich_notifications.md
  _lang/fr/_user_guide/message_building_by_channel/push/best_practices.md
  _lang/fr/_user_guide/message_building_by_channel/push/best_practices/additional_android_best_practices.md
  _lang/fr/_user_guide/message_building_by_channel/push/best_practices/conversion_tracking.md
  _lang/fr/_user_guide/message_building_by_channel/push/best_practices/creating_custom_opt-in_prompts.md
  _lang/fr/_user_guide/message_building_by_channel/push/best_practices/detailed_push_preferences.md
  _lang/fr/_user_guide/message_building_by_channel/push/best_practices/know_before_send.md
  _lang/fr/_user_guide/message_building_by_channel/push/best_practices/message_format.md
  _lang/fr/_user_guide/message_building_by_channel/push/best_practices/sunset_policies.md
  _lang/fr/_user_guide/message_building_by_channel/push/creating_a_push_message.md
Labels: cla-signed

#4145 GlobalLink Translation PR
  _lang/fr/_user_guide/message_building_by_channel/push/ios.md
  _lang/fr/_user_guide/message_building_by_channel/push/ios/advanced_campaign_settings.md
  _lang/fr/_user_guide/message_building_by_channel/push/ios/customizable_app_icons.md
  _lang/fr/_user_guide/message_building_by_channel/push/ios/notification_headers.md
  _lang/fr/_user_guide/message_building_by_channel/push/ios/notification_options.md
  _lang/fr/_user_guide/message_building_by_channel/push/ios/rich_notifications.md
  _lang/fr/_user_guide/message_building_by_channel/push/ios/utilizing_badge_count.md
  _lang/fr/_user_guide/message_building_by_channel/push/push_primer_messages.md
  _lang/fr/_user_guide/message_building_by_channel/push/push_registration.md
  _lang/fr/_user_guide/message_building_by_channel/push/push_reporting.md
  _lang/fr/_user_guide/message_building_by_channel/push/types.md
  _lang/fr/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
  _lang/fr/_user_guide/message_building_by_channel/push/web.md
  assets/img_archive/braze_optedin.png
Labels: cla-signed

#4162 BD-1632: Add delay limit
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
Labels: cla-signed

#4152 BD-1631: Clarify push token behavior for multiple users on one device
  _docs/_user_guide/message_building_by_channel/push/push_registration.md
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
  assets/img/push_token_changelog.png
Labels: cla-signed

#4167 Revert "BD-1605: Document Messaging History tab of user profile"
  _docs/_hidden/private_betas/email_history.md
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
  _docs/_user_guide/engagement_tools/segments/using_user_search.md
  assets/img_archive/profiles_engagement_tab.png
  assets/img_archive/profiles_messaging_history_tab.png
  assets/img_archive/profiles_multiple_results.png
  assets/img_archive/profiles_overview_tab.png
  assets/img_archive/profiles_social_tab.png
  assets/img_archive/profiles_social_tab_old.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#4123 BD-1606: Edits for Canvas entry properties and event properties
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
Labels: cla-signed
