Repository braze-inc/braze-docs, pull requests merged in 2022-08, with the labels that each got.

#3850 BD-1495: Restructure data point tables for clarity between billable and non-billable data points
  _docs/_user_guide/onboarding_with_braze/data_points.md
Labels: cla-signed

#3851 BD-1497: Add ios and android version references for segment app versi…
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#3852 BD-1496: Unifying standard/default terms, adding clarifications for L…
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
  _docs/_hidden/private_betas/iam_drag_and_drop/create_dnd_iam.md
  _docs/_partners/data_and_infrastructure_agility/analytics/looker.md
  _docs/_user_guide/data_and_analytics/tracking/uninstall_tracking.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/location_tracking.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: cla-signed

#3814 GlobalLink PR
  _lang/_config_fr.yml
  _lang/fr/_api/basics.md
  _lang/fr/_developer_guide/home.md
  _lang/fr/_docs_pages/404.md
  _lang/fr/_docs_pages/404_api.md
  _lang/fr/_docs_pages/api.md
  _lang/fr/_docs_pages/cla.md
  _lang/fr/_docs_pages/developer_guide.md
  _lang/fr/_docs_pages/help.md
  _lang/fr/_docs_pages/home.md
  _lang/fr/_docs_pages/index.md
  _lang/fr/_docs_pages/partners.md
  _lang/fr/_docs_pages/search.md
  _lang/fr/_docs_pages/sitemap.xml
  _lang/fr/_docs_pages/user_guide.md
  _lang/fr/_help/home.md
  _lang/fr/_partners/home.md
  _lang/fr/_user_guide/introduction.md
Labels: cla-signed

#3853 Swap release notes from month to release date
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2022.md
  _docs/_help/release_notes/2022/12_14_21.md
  _docs/_help/release_notes/2022/1_11_22.md
  _docs/_help/release_notes/2022/2_8_22.md
  _docs/_help/release_notes/2022/3_8_22.md
  _docs/_help/release_notes/2022/4_5_22.md
  _docs/_help/release_notes/2022/5_31_22.md
  _docs/_help/release_notes/2022/5_3_22.md
  _docs/_help/release_notes/2022/6_28_22.md
  _docs/_help/release_notes/2022/7_26_22.md
Labels: cla-signed

#3855 Updating sdk_min_version
  _plugins/sdk_min_versions_tag.rb
Labels: cla-signed

#3856 BD-1500: Clarify max custom attribute array size
  _docs/_developer_guide/platform_wide/analytics_overview.md
Labels: cla-signed

#3857 Deploy - August 2, 2022
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2022.md
  _docs/_help/release_notes/2022/12_14_21.md
  _docs/_help/release_notes/2022/1_11_22.md
  _docs/_help/release_notes/2022/2_8_22.md
  _docs/_help/release_notes/2022/3_8_22.md
  _docs/_help/release_notes/2022/4_5_22.md
  _docs/_help/release_notes/2022/5_31_22.md
  _docs/_help/release_notes/2022/5_3_22.md
  _docs/_help/release_notes/2022/6_28_22.md
  _docs/_help/release_notes/2022/7_26_22.md
  _docs/_hidden/private_betas/iam_drag_and_drop/create_dnd_iam.md
  _docs/_partners/data_and_infrastructure_agility/analytics/looker.md
  _docs/_user_guide/data_and_analytics/tracking/uninstall_tracking.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/location_tracking.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _docs/_user_guide/onboarding_with_braze/data_points.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  _lang/_config_fr.yml
  _lang/fr/_api/basics.md
  _lang/fr/_developer_guide/home.md
  _lang/fr/_docs_pages/404.md
  _lang/fr/_docs_pages/404_api.md
  _lang/fr/_docs_pages/api.md
  _lang/fr/_docs_pages/cla.md
  _lang/fr/_docs_pages/developer_guide.md
  _lang/fr/_docs_pages/help.md
  _lang/fr/_docs_pages/home.md
  _lang/fr/_docs_pages/index.md
  _lang/fr/_docs_pages/partners.md
  _lang/fr/_docs_pages/search.md
  _lang/fr/_docs_pages/sitemap.xml
  _lang/fr/_docs_pages/user_guide.md
  _lang/fr/_help/home.md
  _lang/fr/_partners/home.md
  _lang/fr/_user_guide/introduction.md
  _plugins/sdk_min_versions_tag.rb
Labels: cla-signed, Deploy

#3854 Lokalise - Partner Docs
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/localization.md
  _docs/_partners/message_personalization/localization/lokalise.md
  assets/img/lokalise/1_add_key.png
  assets/img/lokalise/2_translation_key_added.png
  assets/img/lokalise/3_lokalise_braze_app.png
  assets/img/lokalise/4_testing_json_lokalise.png
  assets/img/lokalise/5_edit_email.png
  assets/img/lokalise/6_integration_usage_sample.png
Labels: cla-signed, Braze Partnerships

#3787 Storyly Partnership Documentation 8/3
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/storyly.md
  _docs/_partners/home.md
Labels: cla-signed, Braze Partnerships

#3768 actionable.me Partnership Documentation 8/3
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/analytics.md
  _docs/_partners/data_and_infrastructure_agility/analytics/actionableme.md
  _docs/_partners/home.md
  assets/img/actionableme/image1.png
  assets/img/actionableme/image2.png
Labels: cla-signed, Braze Partnerships

#3860 BD-1502: Update data retention page
  _docs/_api/data_retention.md
Labels: cla-signed

#3858 BD-1498: Add user alias object payload
  _docs/_hidden/private_betas/shopify/shopify_data.md
Labels: cla-signed

#3859 BD-1499: Update Segment Currents screenshots
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  assets/img/segment/segment.png
Labels: cla-signed

#3862 BD-1501: Update audience sync docs with Canvas Flow screenshots
  _docs/_partners/canvas_steps/facebook_audience_sync.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  assets/img/fb_audience_sync/add_step.png
  assets/img/google_sync/google_sync6.png
Labels: cla-signed

#3864 Update action_paths.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md
Labels: cla-signed

#3861 Hidden partner fix and link fix
  _docs/_help/release_notes/2022/12_14_21.md
  _docs/_help/release_notes/2022/1_11_22.md
  _docs/_help/release_notes/2022/2_8_22.md
  _docs/_help/release_notes/2022/3_8_22.md
  _docs/_help/release_notes/2022/4_5_22.md
  _docs/_help/release_notes/2022/5_31_22.md
  _docs/_help/release_notes/2022/5_3_22.md
  _docs/_help/release_notes/2022/6_28_22.md
  _docs/_help/release_notes/2022/7_26_22.md
  _docs/_partners/data_and_infrastructure_agility/analytics/actionableme.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/storyly.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/iam_studio.md
  _docs/_partners/message_personalization/localization/lokalise.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
Labels: cla-signed

#3867 Deploy Pt. 2 - August 2, 2022
  _docs/_api/data_retention.md
  _docs/_help/release_notes/2022/12_14_21.md
  _docs/_help/release_notes/2022/1_11_22.md
  _docs/_help/release_notes/2022/2_8_22.md
  _docs/_help/release_notes/2022/3_8_22.md
  _docs/_help/release_notes/2022/4_5_22.md
  _docs/_help/release_notes/2022/5_31_22.md
  _docs/_help/release_notes/2022/5_3_22.md
  _docs/_help/release_notes/2022/6_28_22.md
  _docs/_help/release_notes/2022/7_26_22.md
  _docs/_hidden/private_betas/shopify/shopify_data.md
  _docs/_partners/canvas_steps/facebook_audience_sync.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/analytics.md
  _docs/_partners/data_and_infrastructure_agility/analytics/actionableme.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/storyly.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/channel_extensions.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/iam_studio.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/localization.md
  _docs/_partners/message_personalization/localization/lokalise.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
  assets/img/actionableme/image1.png
  assets/img/actionableme/image2.png
  assets/img/fb_audience_sync/add_step.png
  assets/img/google_sync/google_sync6.png
  assets/img/iam_studio/braze_campaign_editor.png
  assets/img/iam_studio/export_iam_code.png
  assets/img/iam_studio/iam_customize_button.png
  assets/img/iam_studio/iam_customize_image.png
  assets/img/iam_studio/iam_customize_text.png
  assets/img/iam_studio/iam_template_gallery.png
  assets/img/lokalise/1_add_key.png
  assets/img/lokalise/2_translation_key_added.png
  assets/img/lokalise/3_lokalise_braze_app.png
  assets/img/lokalise/4_testing_json_lokalise.png
  assets/img/lokalise/5_edit_email.png
  assets/img/lokalise/6_integration_usage_sample.png
  assets/img/segment/segment.png
Labels: cla-signed, Deploy

#3870 Update Android manual push registration
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
Labels: cla-signed

#3874 BD-1503: User CSV import subscription group
  _docs/_api/data_retention.md
  _docs/_api/objects_filters/trigger_properties_object.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_archival.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md
  _docs/_user_guide/message_building_by_channel/sms/sms_subscription_group.md
Labels: cla-signed

#3875 remove company_secret note
  _docs/_api/basics.md
Labels: cla-signed

#3876 replace windows with web link
  _docs/_api/basics.md
Labels: cla-signed

#3873 Leftover deploy - August 4, 2022
  _docs/_api/basics.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_partners/canvas_steps/facebook_audience_sync.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/sms/sms_subscription_group.md
Labels: cla-signed, Deploy

#3880 Update segment.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
Labels: cla-signed

#3878 Beta to EA update
  _docs/_hidden/private_betas/snowflake_integration.md
Labels: cla-signed

#3882 Broken link fixes
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/runtime_configuration.md
Labels: cla-signed

#3883 BD-1507: Update Azure AD instructions
  _docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
  assets/img/relaystate2.png
Labels: cla-signed

#3877 Message archiving GA
  _docs/_user_guide/data_and_analytics/export_braze_data.md
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
Labels: cla-signed

#3881 Leftover Deploy Pt.2 - August 5, 2022
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/runtime_configuration.md
  _docs/_hidden/private_betas/snowflake_integration.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
  _docs/_user_guide/data_and_analytics/export_braze_data.md
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
  assets/img/relaystate2.png
Labels: cla-signed, Deploy

#3783 Add Braze developer banner
  _docs/_developer_guide/developer_portal.md
  _docs/_developer_guide/home.md
  _docs/_developer_guide/platform_integration_guides/sdk_changelogs.md
  _docs/_docs_pages/index.md
  _docs/_help/release_notes/sdk_changelogs.md
  _docs/_user_guide/introduction.md
  _includes/header.html
  assets/img/arrow.png
  assets/img/cordova.png
  assets/img/diagram.png
  assets/img/gear.png
  assets/img/gear2.png
  assets/img/unity.png
  assets/img/unreal.png
  assets/img/xamarin.png
  assets/js/documents.js
Labels: cla-signed

#3792 Android - updated docs for new push notification event callback
  _docs/_developer_guide/platform_integration_guides/android/analytics/uninstall_tracking.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/android_tv_push.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/customization.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/customization/advanced_settings.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/customization/custom_broadcast_receiver.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/silent_push_notifications.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/customization/advanced_settings.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/silent_push_notifications.md
  _docs/_developer_guide/platform_integration_guides/unity/push_notifications/adm_push_notifications.md
  _docs/_user_guide/message_building_by_channel/push/android/advanced_campaign_settings.md
Labels: cla-signed

#3885 BD-1504: Add Tealium to customer data partners
  _docs/_user_guide/data_and_analytics/braze_currents/available_partners.md
Labels: cla-signed

#3884 Update Liquid use case library
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
Labels: cla-signed

#3887 Limitations of Test Messages
  _docs/_developer_guide/platform_wide/sending_test_messages.md
Labels: cla-signed

#3886 GlobalLink Translation PR
  _lang/fr/_user_guide/administrative.md
  _lang/fr/_user_guide/data_and_analytics.md
  _lang/fr/_user_guide/engagement_tools.md
  _lang/fr/_user_guide/engagement_tools/canvas.md
  _lang/fr/_user_guide/engagement_tools/canvas/canvas_components.md
  _lang/fr/_user_guide/engagement_tools/canvas/canvas_components/about.md
  _lang/fr/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md
  _lang/fr/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md
  _lang/fr/_user_guide/engagement_tools/canvas/canvas_components/decision_split.md
  _lang/fr/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
  _lang/fr/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
  _lang/fr/_user_guide/engagement_tools/canvas/canvas_components/fb_audience_sync.md
  _lang/fr/_user_guide/engagement_tools/canvas/canvas_components/google_audience_sync.md
  _lang/fr/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
  _lang/fr/_user_guide/engagement_tools/canvas/create_a_canvas.md
  _lang/fr/_user_guide/engagement_tools/canvas/create_a_canvas/advancement.md
  _lang/fr/_user_guide/engagement_tools/canvas/create_a_canvas/branching.md
  _lang/fr/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md
  _lang/fr/_user_guide/engagement_tools/canvas/create_a_canvas/content-cards_in_canvas.md
  _lang/fr/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _lang/fr/_user_guide/engagement_tools/canvas/create_a_canvas/exception_events.md
  _lang/fr/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
  _lang/fr/_user_guide/engagement_tools/canvas/create_a_canvas/time_based_canvas.md
  _lang/fr/_user_guide/engagement_tools/canvas/faqs.md
  _lang/fr/_user_guide/engagement_tools/canvas/get_started.md
  _lang/fr/_user_guide/engagement_tools/canvas/get_started/canvas_outlines.md
  _lang/fr/_user_guide/engagement_tools/canvas/get_started/the_basics.md
  _lang/fr/_user_guide/engagement_tools/canvas/managing_canvases.md
  _lang/fr/_user_guide/engagement_tools/canvas/managing_canvases/archiving_canvases.md
  _lang/fr/_user_guide/engagement_tools/canvas/managing_canvases/canvas_duplication.md
  _lang/fr/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
  _lang/fr/_user_guide/engagement_tools/canvas/testing_canvases.md
  _lang/fr/_user_guide/engagement_tools/canvas/testing_canvases/canvas_funnel_reports.md
  _lang/fr/_user_guide/engagement_tools/canvas/testing_canvases/measuring_and_testing_with_canvas_analytics.md
  _lang/fr/_user_guide/engagement_tools/canvas/testing_canvases/retention_reports.md
  _lang/fr/_user_guide/intelligence.md
  _lang/fr/_user_guide/introduction.md
  _lang/fr/_user_guide/message_building_by_channel.md
  _lang/fr/_user_guide/onboarding_with_braze.md
  _lang/fr/_user_guide/personalization_and_dynamic_content.md
  _lang/fr/_user_guide/predictive_suite.md
Labels: cla-signed

#3890 BD-1513: Broken dashboard link
  assets/js/broken_redirect_list.js
Labels: cla-signed

#3894 Remove limitation for cloning Canvases feature
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
Labels: cla-signed

#3893 BD-1510: Update doc with new Tracked Link Aliases page
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
  assets/img/tracked_aliases.png
Labels: cla-signed

#3896 push tag manager
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
Labels: cla-signed

#3897 BD-1518: Add additional context to SMS FAQ subscription
  _docs/_user_guide/message_building_by_channel/sms/faqs.md
Labels: cla-signed

#3898 BD-1516: Add note to docs request form
  _docs/_hidden/other/documentation_request.md
Labels: cla-signed

#3899 BD-1517: Clarify number of tracked links limitation
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
Labels: cla-signed

#3891 BD-1474: Add new filters and tags for Liquid 5
  _docs/_user_guide/personalization_and_dynamic_content/liquid.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md
Labels: cla-signed

#3902 Request submission process message
  _docs/_hidden/other/documentation_request.md
Labels: cla-signed

#3901 Fix typo
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_approval.md
Labels: cla-signed

#3903 Fix language build
  .vercel/build.js
  _lang/_config_fr.yml
Labels: cla-signed

#3904 SDK-2844
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/android_tv_push.md
Labels: cla-signed

#3671 Card creation early access
  _docs/_hidden/private_betas/card_creation.md
  assets/img_archive/card_creation.png
Labels: cla-signed

#3906 BD-1522: Remove CSS inlining mentions for DND
  _docs/_user_guide/message_building_by_channel/email/css_inline.md
  assets/img_archive/css-inline3.png
Labels: cla-signed

#3907 Fix banner overlapping search
  _includes/header.html
Labels: cla-signed

#3911 BD-1525: Add colored SDK logos
  _docs/_developer_guide/home.md
  _docs/_developer_guide/platform_integration_guides/sdk_changelogs.md
  assets/img/android.png
  assets/img/cordova.png
  assets/img/macOS_icon.png
  assets/img/reactnative_icon.png
  assets/img/roku.png
  assets/img/tvos_icon.png
  assets/img/windows_universal_icon.png
  assets/img/xamarin.png
Labels: cla-signed

#3909 BD-1509: Add order level guidance for logging purchases
  _docs/_api/objects_filters/purchase_object.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/cordova/cordova_integration.md
  _docs/_developer_guide/platform_integration_guides/flutter/analytics.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/react_native/analytics.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/unity/Analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/xamarin/analytics.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
Labels: cla-signed

#3910 BD-1511: Clarify Flex CSS Web behavior
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
Labels: cla-signed

#3888 Update link_shortening.md
  _docs/_hidden/private_betas/link_shortening.md
Labels: cla-signed

#3908 BD-1523: Update SOC 2 date and text
  _docs/_developer_guide/disclosures/security_qualifications.md
Labels: cla-signed

#3913 [SDK-2811] FireOS apikey document updates
  _docs/_developer_guide/platform_integration_guides/unity/push_notifications/adm_push_notifications.md
Labels: cla-signed

#3915 Fixes to push and {{site.baseurl}} link fixes
  _docs/_developer_guide/platform_integration_guides/android/android_12.md
  _docs/_developer_guide/platform_integration_guides/android/android_13.md
  _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/ios_16.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/web/content_security_policy.md
  _docs/_developer_guide/platform_wide/braze_actions.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2020/october.md
  _docs/_help/release_notes/2021/may.md
  _docs/_help/release_notes/2022/7_26_22.md
  _docs/_hidden/private_betas/link_shortening.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/amperity.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/lexer.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/toovio.md
  _docs/_partners/message_orchestration/additional_channels/direct_mail/optilyz.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer_audiences.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/yotpo.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/jebbit.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/viralsweep.md
  _docs/_partners/message_orchestration/channel_extensions/surveys/digioh.md
  _docs/_partners/message_personalization/dynamic_content/wyng.md
  _docs/_user_guide/engagement_tools/segments/beacon_support.md
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
  _includes/archive/setting_user_ids/aliasing.md
  _includes/archive/setting_user_ids/setting_user_ids.md
  _includes/sdk_auth_alert.md
Labels: cla-signed

#3916 BD-1526: Fix tabs and add more emphasis to capturing time properties
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
Labels: cla-signed

#3917 BD-1524: Make callout for optimal delay between endpoint calls more visible
  _docs/_api/api_limits.md
Labels: cla-signed

#3918 Add web SDK note to OTT documentation
  _docs/_developer_guide/platform_integration_guides/web/smart_tvs.md
Labels: cla-signed

#3919 Correct uppercase/lowercase
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/user_phone_numbers.md
Labels: cla-signed

#3920 Update google_tag_manager.md
  _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
Labels: cla-signed

#3921 Update intelligent_channel.md for clarity
  _docs/_user_guide/intelligence/intelligent_channel.md
Labels: cla-signed

#3922 Braze capitalization fix
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/toovio.md
  _docs/_partners/home.md
Labels: cla-signed

#3900 DataGrail Partnership Documentation
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/data_privacy.md
  _docs/_partners/data_and_infrastructure_agility/data_privacy/datagrail.md
  _docs/_partners/data_and_infrastructure_agility/data_privacy/transcend.md
  _docs/_partners/home.md
Labels: cla-signed, Braze Partnerships

#3923 Update home.md
  _docs/_partners/home.md
Labels: cla-signed

#3815 [SDK-2800] - React Native + Expo updates
  _docs/_developer_guide/platform_integration_guides/react_native/analytics.md
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
  _docs/_developer_guide/platform_integration_guides/react_native/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Labels: cla-signed

#3925 Hiding Datagrail for ad hoc deploy
  _docs/_partners/data_and_infrastructure_agility/data_privacy/datagrail.md
Labels: cla-signed

#3926 Leftover Deploy Pt. 2 - August 12. 2022
  _docs/_developer_guide/platform_integration_guides/react_native/analytics.md
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
  _docs/_developer_guide/platform_integration_guides/react_native/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
  _docs/_developer_guide/platform_integration_guides/web/smart_tvs.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/toovio.md
  _docs/_partners/data_and_infrastructure_agility/data_privacy.md
  _docs/_partners/data_and_infrastructure_agility/data_privacy/datagrail.md
  _docs/_partners/data_and_infrastructure_agility/data_privacy/transcend.md
  _docs/_partners/home.md
  _docs/_user_guide/intelligence/intelligent_channel.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/user_phone_numbers.md
Labels: cla-signed, Deploy

#3924 GA new Braze partners
  _docs/_partners/data_and_infrastructure_agility/analytics/actionableme.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/storyly.md
  _docs/_partners/data_and_infrastructure_agility/data_privacy/datagrail.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/iam_studio.md
  _docs/_partners/message_personalization/localization/lokalise.md
Labels: cla-signed

#3801 Segment Updates
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  assets/img/segment/android.png
  assets/img/segment/ios.png
  assets/img/segment/setup.png
  assets/img/segment/website.png
Labels: cla-signed

#3868 Quikly Partnership Documentation
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/additional_channels.md
  _docs/_partners/message_orchestration/additional_channels/retargeting.md
  _docs/_partners/message_orchestration/additional_channels/retargeting/quikly.md
Labels: cla-signed, Braze Partnerships

#3927 BD-1532: Update product portal image
  assets/img/portal.png
Labels: cla-signed

#3928 BD-1529: Update catalogs example
  _docs/_user_guide/personalization_and_dynamic_content/catalog.md
Labels: cla-signed

#3930 BD-1528: Document campaign search syntax
  _docs/_api/identifier_types.md
  _docs/_user_guide/engagement_tools/campaigns/faq.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/search_campaigns.md
  assets/img_archive/campaign_search.png
  assets/img_archive/campaign_search2.png
  assets/img_archive/campaign_search3.png
Labels: cla-signed

#3912 BD-1494: Canvas entry properties and event properties
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  assets/img_archive/canvas_entry_properties1.png
Labels: cla-signed

#3934 Deploy - August 16, 2022
  _docs/_api/identifier_types.md
  _docs/_partners/data_and_infrastructure_agility/analytics/actionableme.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/storyly.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _docs/_partners/data_and_infrastructure_agility/data_privacy/datagrail.md
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/additional_channels.md
  _docs/_partners/message_orchestration/additional_channels/retargeting.md
  _docs/_partners/message_orchestration/additional_channels/retargeting/quikly.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/iam_studio.md
  _docs/_partners/message_personalization/localization/lokalise.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _docs/_user_guide/engagement_tools/campaigns/faq.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/search_campaigns.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/personalization_and_dynamic_content/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  assets/img/portal.png
  assets/img/segment/android.png
  assets/img/segment/ios.png
  assets/img/segment/setup.png
  assets/img/segment/website.png
  assets/img_archive/campaign_search.png
  assets/img_archive/campaign_search2.png
  assets/img_archive/campaign_search3.png
  assets/img_archive/canvas_entry_properties1.png
Labels: cla-signed, Deploy

#3935 Update disabling_tracking.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/disabling_tracking.md
Labels: cla-signed

#3936 Update optional_gaid_collection.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/optional_gaid_collection.md
Labels: cla-signed

#3931 fix: correct request example
  _docs/_api/endpoints/messaging/schedule_messages/post_update_scheduled_triggered_canvases.md
Labels: cla-signed

#3939 BD-1534: Update purchase object example
  _docs/_api/objects_filters/purchase_object.md
Labels: cla-signed

#3938 Update refreshing_the_feed.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/refreshing_the_feed.md
Labels: cla-signed

#3941 Update badges.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/badges.md
Labels: cla-signed

#3942 BD-1535: Edit alert
  _docs/_hidden/private_betas/canvas_user_update.md
Labels: cla-signed

#3946 Update custom_styling.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/custom_styling.md
Labels: cla-signed

#3944 Fixing links broken with change from com.appboy to com.braze
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/network_offline_mode_integration.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_sessions.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/custom_styling.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/default_feed.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization/custom_listeners.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/integration.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/refreshing_the_feed.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/push_story.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/customization/advanced_settings.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/integration.md
  _docs/_developer_guide/platform_integration_guides/unity/push_notifications/adm_push_notifications.md
  _includes/archive/android/gifs.md
Labels: cla-signed

#3943 Add alert for Canvas entry properties and event properties
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
Labels: cla-signed

#3932 Update push_primer_messages.md
  _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
Labels: cla-signed

#3945 Update android_13.md
  _docs/_developer_guide/platform_integration_guides/android/android_13.md
Labels: cla-signed

#3949 BD-1539: Update money_with_currency to unsupported
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
Labels: cla-signed

#3950 Leftover Deploy - August 18, 2022
  _docs/_api/endpoints/messaging/schedule_messages/post_update_scheduled_triggered_canvases.md
  _docs/_api/objects_filters/purchase_object.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/network_offline_mode_integration.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/disabling_tracking.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_sessions.md
  _docs/_developer_guide/platform_integration_guides/android/android_13.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/badges.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/custom_styling.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/default_feed.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/refreshing_the_feed.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization/custom_listeners.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/optional_gaid_collection.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/integration.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/refreshing_the_feed.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/push_story.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/customization/advanced_settings.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/integration.md
  _docs/_developer_guide/platform_integration_guides/unity/push_notifications/adm_push_notifications.md
  _docs/_hidden/private_betas/canvas_user_update.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
  _docs/_user_guide/onboarding_with_braze/web_sdk.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
  _includes/archive/android/gifs.md
  assets/img_archive/web_push_macbook.png
  assets/img_archive/web_push_prompt.png
Labels: cla-signed, Deploy

#3952 BD-1542: Update process for upgrading to Catalogs Pro
  _docs/_user_guide/personalization_and_dynamic_content/catalog.md
Labels: cla-signed

#3951 BD-1541: Clarify deprecation of /users/track B2B webhooks in User Update
  _docs/_hidden/private_betas/canvas_user_update.md
Labels: cla-signed

#3953 fix: correct double quotes in example request
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
Labels: cla-signed

#3933 Social data tracking
  _docs/_api/objects_filters/user_attributes_object.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/social_data_tracking.md
  _docs/_developer_guide/platform_integration_guides/flutter/analytics.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/social_data_tracking.md
  _docs/_developer_guide/platform_integration_guides/react_native/analytics.md
  _docs/_developer_guide/platform_integration_guides/swift.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/social_data_tracking.md
  _docs/_developer_guide/platform_integration_guides/tvos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/social_data_tracking.md
  _docs/_developer_guide/platform_integration_guides/xamarin/analytics.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_developer_guide/platform_wide/platform_features.md
  _docs/_home/static_video.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_user_guide/engagement_tools/campaigns/getting_started/campaign_basics.md
  _docs/_user_guide/engagement_tools/canvas/get_started/the_basics.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/engagement_tools/segments/using_user_search.md
  _docs/_user_guide/onboarding_with_braze/terms_to_know.md
  _includes/archive/apple/initial_setup.md
  assets/img_archive/User_Profile_Social.png
Labels: cla-signed

#3955 BD-1536: Clarify warning alert
  _docs/_user_guide/message_building_by_channel/in-app_messages/testing.md
Labels: cla-signed

#3940 Style edits for Objects docs
  _docs/_api/objects_filters/connected_audience.md
  _docs/_api/objects_filters/event_object.md
  _docs/_api/objects_filters/recipient_object.md
  _docs/_api/objects_filters/trigger_properties_object.md
  _docs/_api/objects_filters/user_alias_object.md
  _docs/_api/objects_filters/user_attributes_object.md
Labels: cla-signed

#3957 Add soft bounce for mParticle, canvas information for Amplitude
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md
Labels: cla-signed

#3961 Edit custom font with feedback
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
Labels: cla-signed

#3962 BD-1543: Update in-app messages in Canvas for Flow
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
  assets/img_archive/canvas_priority.png
  assets/img_archive/canvas_send_settings.png
Labels: cla-signed

#3929 BD-1531: Hidden doc for Catalogs API
  _docs/_hidden/private_betas/patch_catalog_items.md
  assets/css/_api.scss
Labels: cla-signed

#3960 Deploy - August 23, 2022
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
  _docs/_api/objects_filters/connected_audience.md
  _docs/_api/objects_filters/event_object.md
  _docs/_api/objects_filters/recipient_object.md
  _docs/_api/objects_filters/trigger_properties_object.md
  _docs/_api/objects_filters/user_alias_object.md
  _docs/_api/objects_filters/user_attributes_object.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/social_data_tracking.md
  _docs/_developer_guide/platform_integration_guides/flutter/analytics.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/ios/analytics/social_data_tracking.md
  _docs/_developer_guide/platform_integration_guides/react_native/analytics.md
  _docs/_developer_guide/platform_integration_guides/swift.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/social_data_tracking.md
  _docs/_developer_guide/platform_integration_guides/tvos/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/social_data_tracking.md
  _docs/_developer_guide/platform_integration_guides/xamarin/analytics.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_developer_guide/platform_wide/platform_features.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2022.md
  _docs/_help/release_notes/2022/8_23_22.md
  _docs/_hidden/private_betas/canvas_user_update.md
  _docs/_hidden/private_betas/patch_catalog_items.md
  _docs/_home/static_video.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_user_guide/engagement_tools/campaigns/getting_started/campaign_basics.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
  _docs/_user_guide/engagement_tools/canvas/get_started/the_basics.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/engagement_tools/segments/using_user_search.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/testing.md
  _docs/_user_guide/onboarding_with_braze/terms_to_know.md
  _docs/_user_guide/personalization_and_dynamic_content/catalog.md
  _includes/archive/apple/initial_setup.md
  assets/css/_api.scss
  assets/img_archive/User_Profile_Social.png
  assets/img_archive/canvas_priority.png
  assets/img_archive/canvas_send_settings.png
Labels: cla-signed, Deploy

#3964 BD-1547: Update variable requirement for purchase object
  _docs/_api/objects_filters/purchase_object.md
Labels: cla-signed

#3965 BD-1540: Clarify filter behavior
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
Labels: cla-signed

#3966 BD-1549: Add instructions for searching exact text
  _docs/_help/help_articles/segments.md
  _docs/_help/help_articles/segments/search_exact_text.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/search_campaigns.md
Labels: cla-signed

#3967 Fix Typos in Liquid
  _docs/_partners/message_orchestration/additional_channels/mobile_wallet/passkit.md
Labels: cla-signed

#3969 BD-1552: Explicitly state that IAMs can't be triggered by purchase events
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/in-app_message_delivery.md
  _includes/archive/in_app_message.md
Labels: cla-signed

#3971 BD-1550: Clarify only one promo code is used
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
  assets/img/promocodes/promocode2.png
Labels: cla-signed

#3970 BD-1553: Add troubleshooting steps to enable verbose logging for GTM
  _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
  assets/img/web-gtm/gtm_verbose_logging.png
Labels: cla-signed

#3963 [SDK-2798] - React Native push notifications update
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Labels: cla-signed

#3937 Clarification for Devs Inexperienced with Push
  _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
Labels: cla-signed

#3973 Update amplitude_recommend.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_recommend.md
Labels: cla-signed

#3974 updated expo android config docs
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
Labels: cla-signed

#3968 Updating Voucherify (partner) documentation.
  _docs/_partners/message_orchestration/channel_extensions/loyalty/voucherify.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/voucherify/voucherify.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/voucherify/voucherify_distribution_with_braze_custom_attributes.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/voucherify/voucherify_fetching_data_through_braze_connected_content.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/voucherify/voucherify_using_braze_promotion_codes_list.md
  assets/img/voucherify-cc-campaignId.png
  assets/img/voucherify-cc-code-published.png
  assets/img/voucherify-cc-preview.png
  assets/img/voucherify-create-Promotion-Codes.png
  assets/img/voucherify-custom-attribute-in-email.png
  assets/img/voucherify-custom-attribute.png
  assets/img/voucherify-custom-attributes-mapping.png
  assets/img/voucherify-email-preview-custom-attribute.png
  assets/img/voucherify-export-Codes.png
  assets/img/voucherify-integrations-hub.png
  assets/img/voucherify-manual-conditions.png
  assets/img/voucherify-promotion-codes-details.png
  assets/img/voucherify-promotion-codes-list-expiration.png
  assets/img/voucherify-promotion-list-copy-snippet.png
  assets/img/voucherify-promotion-list-snippet-email.png
  assets/img/voucherify-redemption.png
  assets/img/voucherify/voucherify_cc_app_keys.png
  assets/img/voucherify/voucherify_cc_cache.png
  assets/img/voucherify/voucherify_cc_campaignId.png
  assets/img/voucherify/voucherify_cc_custom_code_email.png
  assets/img/voucherify/voucherify_cc_endpoint.png
  assets/img/voucherify/voucherify_cc_join_once.png
  assets/img/voucherify/voucherify_cc_limiter.png
  assets/img/voucherify/voucherify_cc_retry.png
  assets/img/voucherify/voucherify_cc_save_parameter.png
  assets/img/voucherify/voucherify_cc_script_overview.png
  assets/img/voucherify/voucherify_cc_sourceId_unique_publication.png
  assets/img/voucherify/voucherify_custom_attributes_API_key.png
  assets/img/voucherify/voucherify_custom_attributes_channel.png
  assets/img/voucherify/voucherify_custom_attributes_code.png
  assets/img/voucherify/voucherify_custom_attributes_consents.png
  assets/img/voucherify/voucherify_custom_attributes_distribution.png
  assets/img/voucherify/voucherify_custom_attributes_email_body.png
  assets/img/voucherify/voucherify_custom_attributes_email_preview.png
  assets/img/voucherify/voucherify_custom_attributes_enter_API_key.png
  assets/img/voucherify/voucherify_custom_attributes_fields_mapping.png
  assets/img/voucherify/voucherify_custom_attributes_integrations.png
  assets/img/voucherify/voucherify_custom_attributes_manual_message.png
  assets/img/voucherify/voucherify_custom_attributes_name_distribution.png
  assets/img/voucherify/voucherify_custom_attributes_name_distribution_choose_segment.png
  assets/img/voucherify/voucherify_custom_attributes_plus.png
  assets/img/voucherify/voucherify_promotion_code_list.png
  assets/img/voucherify/voucherify_promotion_code_list_created.png
  assets/img/voucherify/voucherify_promotion_code_snippet.png
  assets/img/voucherify/voucherify_promotion_create_list.png
  assets/img/voucherify/voucherify_promotion_export_codes.png
  assets/img/voucherify/voucherify_promotion_import_codes.png
  assets/img/voucherify/voucherify_promotion_liquid_email.png
  assets/img/voucherify/voucherify_promotion_list_expiration.png
  assets/img/voucherify/voucherify_promotion_upload_csv.png
Labels: cla-signed

#3975 fix sdk versions
  _docs/_developer_guide/platform_wide/braze_actions.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
Labels: cla-signed

#3976 dynamic cards ios version
  _docs/_hidden/private_betas/card_creation.md
Labels: cla-signed

#3978 BD-1556: Add that the regenerate schema option (NCA) will only be allowed once every 24 hours
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
Labels: cla-signed

#3954 GlobalLink Translation PR
  _lang/fr/_user_guide/data_and_analytics/braze_currents.md
  _lang/fr/_user_guide/data_and_analytics/braze_currents/available_partners.md
  _lang/fr/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
  _lang/fr/_user_guide/data_and_analytics/braze_currents/event_glossary.md
  _lang/fr/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _lang/fr/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _lang/fr/_user_guide/data_and_analytics/braze_currents/how_braze_uses_currents.md
  _lang/fr/_user_guide/data_and_analytics/braze_currents/s3_to_snowflake.md
  _lang/fr/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
  _lang/fr/_user_guide/data_and_analytics/braze_currents/transferring_data_to_redshift.md
  _lang/fr/_user_guide/data_and_analytics/configuring_reporting.md
  _lang/fr/_user_guide/data_and_analytics/creating_a_formula.md
  _lang/fr/_user_guide/data_and_analytics/custom_data.md
  _lang/fr/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _lang/fr/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md
  _lang/fr/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
  _lang/fr/_user_guide/data_and_analytics/custom_data/custom_events.md
  _lang/fr/_user_guide/data_and_analytics/custom_data/event_naming_conventions.md
  _lang/fr/_user_guide/data_and_analytics/custom_data/pre-populating_custom_data.md
  _lang/fr/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _lang/fr/_user_guide/data_and_analytics/export_braze_data.md
  _lang/fr/_user_guide/data_and_analytics/export_braze_data/export_apis.md
  _lang/fr/_user_guide/data_and_analytics/export_braze_data/export_campaign_results_data.md
  _lang/fr/_user_guide/data_and_analytics/export_braze_data/export_canvas_data.md
  _lang/fr/_user_guide/data_and_analytics/export_braze_data/export_custom_event_data.md
  _lang/fr/_user_guide/data_and_analytics/export_braze_data/export_news_feed_data.md
  _lang/fr/_user_guide/data_and_analytics/export_braze_data/export_troubleshooting.md
  _lang/fr/_user_guide/data_and_analytics/export_braze_data/exporting_app_usage_data.md
  _lang/fr/_user_guide/data_and_analytics/export_braze_data/exporting_revenue_data.md
  _lang/fr/_user_guide/data_and_analytics/export_braze_data/faqs.md
  _lang/fr/_user_guide/data_and_analytics/export_braze_data/opening_csv_reports_in_excel.md
  _lang/fr/_user_guide/data_and_analytics/export_braze_data/segment_data_to_csv.md
  _lang/fr/_user_guide/data_and_analytics/report_metrics.md
  _lang/fr/_user_guide/data_and_analytics/tracking.md
  _lang/fr/_user_guide/data_and_analytics/tracking/email_tracking.md
  _lang/fr/_user_guide/data_and_analytics/tracking/influenced_opens.md
  _lang/fr/_user_guide/data_and_analytics/tracking/segment_analytics_tracking.md
  _lang/fr/_user_guide/data_and_analytics/tracking/uninstall_tracking.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection/best_practices.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection/collection_use_case.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection/language_codes.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection/user_archival.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
  _lang/fr/_user_guide/data_and_analytics/your_analytics_dashboards.md
  _lang/fr/_user_guide/data_and_analytics/your_analytics_dashboards/email_performance_dashboard.md
  _lang/fr/_user_guide/data_and_analytics/your_analytics_dashboards/understanding_your_app_usage_data.md
  _lang/fr/_user_guide/data_and_analytics/your_reports.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/campaign_analytics.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/engagement_reports.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/funnel_reports.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/report_builder.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/reports_overview.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/retention_reports.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/viewing_and_understanding_segment_data.md
Labels: cla-signed

#3959 BD-1544: Hidden doc for Canvas version history
  _docs/_hidden/private_betas/canvas_version_history.md
  assets/img_archive/canvas_version_history.png
Labels: cla-signed

#3980 BD-1537: Using JSON in KVP to access extras
  _docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
Labels: cla-signed

#3982 fix permission options
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
Labels: cla-signed

#3987 BD-1558: Update Changelog list
  _docs/_developer_guide/platform_integration_guides/flutter/changelog.md
  _docs/_developer_guide/platform_integration_guides/react_native/changelog.md
  _docs/_developer_guide/platform_integration_guides/sdk_changelogs.md
  _docs/_developer_guide/platform_integration_guides/xamarin/ changelog.md
Labels: cla-signed

#3989 Clarify peak event counts
  .github/PULL_REQUEST_TEMPLATE.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
Labels: cla-signed

#3992 Update tv_and_ott.md
  _docs/_developer_guide/platform_wide/tv_and_ott.md
Labels: cla-signed

#3981 Doc edits related to Canvas Flow webinar questions
  _docs/_user_guide/engagement_tools/canvas/best_practices.md
  _docs/_user_guide/engagement_tools/canvas/faqs.md
Labels: cla-signed

#3994 BD-1559: Clarify link aliasing requirements to track metrics
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
Labels: cla-signed

#3999 BD-1564: Remove duplicate field and doc edits
  _docs/_hidden/private_betas/amphtml.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#4000 Edit description for Social Icon editor block
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
Labels: cla-signed
