Repository braze-inc/braze-docs, pull requests merged in 2023-06, with the labels that each got.

#5526 Update managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#5530 BD-2169: Update catalogs endpoint troubleshooting description
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/patch_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/post_create_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/put_update_catalog_items.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/put_update_catalog_item.md
Labels: cla-signed

#5532 Update field limit from 30 to 500 for Create catalog endpoint
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md
Labels: cla-signed

#5525 BD-2157: New row as Content Block for drag-and-drop editor
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/faq.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
Labels: cla-signed

#5527 Update SalesWings Partnership Docs
  _docs/_partners/data_and_infrastructure_agility/analytics/saleswings.md
  assets/img/saleswings/braze_api_endpoint_for_lead_scoring.png
  assets/img/saleswings/braze_api_key_lead_scoring.png
  assets/img/saleswings/creating_api_key_in_braze_lead_scoring.png
Labels: cla-signed

#5533 Minor tweaks to SalesWings docs
  _docs/_partners/data_and_infrastructure_agility/analytics/saleswings.md
Labels: cla-signed

#5499 [SDK-3752] Change AppboyUnityPlayerActivity to BrazeUnityPlayerActivity
  _docs/_developer_guide/platform_integration_guides/unity/advanced_use_cases.md
  _docs/_developer_guide/platform_integration_guides/unity/push_notifications/adm_push_notifications.md
  _docs/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md
Labels: cla-signed

#5509 Updates to SMS Phone numbers doc
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/user_phone_numbers.md
  assets/img/sms/invalid_banner.png
Labels: cla-signed

#5518 BD-2163: /purchases/revenue_series and /purchases/quantity_series endpoint docs
  _docs/_api/endpoints/export.md
  _docs/_api/endpoints/export/purchases/get_number_of_purchases.md
  _docs/_api/endpoints/export/purchases/get_revenue_series.md
  _docs/_api/home.md
Labels: cla-signed

#5539 Update link
  _docs/_api/endpoints/export/purchases/get_list_product_id.md
Labels: cla-signed

#5540 Update navigation.md
  _docs/_user_guide/administrative/access_braze/navigation.md
Labels: cla-signed

#5541 Remove Content Block reference in Email overview
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
Labels: cla-signed

#5542 Update post_create_preference_center.md
  _docs/_api/endpoints/preference_center/post_create_preference_center.md
Labels: cla-signed

#5543 Leftover Deploy Pt. 2 - June 2, 2023
  _docs/_api/endpoints/export.md
  _docs/_api/endpoints/export/purchases/get_list_product_id.md
  _docs/_api/endpoints/export/purchases/get_number_of_purchases.md
  _docs/_api/endpoints/export/purchases/get_revenue_series.md
  _docs/_api/endpoints/preference_center/post_create_preference_center.md
  _docs/_api/home.md
  _docs/_user_guide/administrative/access_braze/navigation.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
Labels: cla-signed, Deploy

#5547 Add Postman link pt. 2
  _docs/_api/endpoints/export/purchases/get_revenue_series.md
Labels: cla-signed

#5546 Add Postman link pt. 1
  _docs/_api/endpoints/export/purchases/get_number_of_purchases.md
Labels: cla-signed

#5534 BD-2165: DND Preference Center GA - MERGE 6/5
  _docs/_user_guide/message_building_by_channel/email/preference_center.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/dnd_preference_center.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/overview.md
Labels: cla-signed

#5552 Remove dev_guide from hidden docs
  _docs/_hidden/other/airship_migration.md
  _docs/_hidden/other/credit_ratios.md
  _docs/_hidden/other/devices_and_carriers.md
  _docs/_hidden/other/ephemeral_custom_events.md
  _docs/_hidden/other/handbooks.md
  _docs/_hidden/other/user_csv_lambda.md
  _docs/_hidden/private_betas/canvas_approval.md
  _docs/_hidden/private_betas/canvas_comments.md
  _docs/_hidden/private_betas/canvas_drafts.md
  _docs/_hidden/private_betas/criteo_audience_sync.md
  _docs/_hidden/private_betas/data_transformation.md
  _docs/_hidden/private_betas/dnd_content_blocks_preview.md
  _docs/_hidden/private_betas/idle_campaigns.md
  _docs/_hidden/private_betas/linkedin_audience_sync.md
  _docs/_hidden/private_betas/recommendations.md
  _docs/_hidden/private_betas/sql_segments_tables.md
  _docs/_hidden/private_betas/test_connectors.md
Labels: cla-signed

#5549 Update react_sdk_setup.md to state 0.68+ min version
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Labels: cla-signed

#5553 Update sql_segments.md
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
Labels: cla-signed

#5554 Remove EA Banner from link shortening docs
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
Labels: cla-signed

#5558 BD-2174: Update IAM reporting note on body clicks to include custom code
  _includes/campaign_analytics.md
Labels: cla-signed

#5559 BD-2177: Fix links
  _docs/_user_guide/message_building_by_channel/whatsapp/faqs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md
Labels: cla-signed

#5561 BD-2179: Custom header support for SparkPost and SendGrid
  _docs/_api/objects_filters/messaging/email_object.md
Labels: cla-signed

#5560 BD-2178: Add max time for re-eligibility
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/reeligibility.md
Labels: cla-signed

#5556 Add Databricks to the Cloud Data Ingestion documentation
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
  assets/img/cloud_ingestion/ingestion_16.png
  assets/img/cloud_ingestion/ingestion_17.png
  assets/img/cloud_ingestion/ingestion_18.png
Labels: cla-signed

#5562 BD-2167: Add FAQs for Gmail promo tab
  _docs/_user_guide/message_building_by_channel/email/html_editor/gmail_promotions_tab.md
Labels: cla-signed

#5557 Add Swift SDK links for Branch deeplinking example
  _docs/_partners/message_orchestration/attribution/branch/branch_for_deeplinking.md
Labels: cla-signed

#5555 Edits for Creating a Canvas
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  assets/img/add_canvas_conversions.png
  assets/img/canvas_details.png
  assets/img_archive/Canvas_API_Triggered_Delivery.png
  assets/img_archive/Canvas_Action_Based_Delivery.png
  assets/img_archive/Canvas_Scheduled_Delivery.png
Labels: cla-signed

#5566 Update S3 snippet
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
Labels: cla-signed

#5570 BD-2183: Swap incorrect screenshots
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
Labels: cla-signed

#5571 BD-2187: Fix link
  _docs/_api/endpoints/sms/get_query_invalid_numbers.md
Labels: cla-signed

#5573 BD-2186: Clarify credit usage for SQL Segments
  _docs/_user_guide/data_and_analytics/query_builder.md
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
Labels: cla-signed

#5574 docs: Update Airbridge document link
  _docs/_partners/message_orchestration/attribution/airbridge.md
Labels: cla-signed

#5575 Update segment_insights.md
  _docs/_user_guide/engagement_tools/segments/segment_insights.md
Labels: cla-signed

#5576 Update Zoom registration
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/zoom.md
Labels: cla-signed

#5577 BD-2114: Update GTM docs w/ optional push setup
  _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
Labels: cla-signed

#5578 Update "Canvas: The Basics" to "Canvas Basics"
  _docs/_docs_pages/index.md
Labels: cla-signed

#5579 BD-2170: Update user update Liquid example
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
Labels: cla-signed

#5565 BD-2175: Update Item Recommendations
  _docs/_hidden/private_betas/recommendations.md
Labels: cla-signed

#5581 Updates to movable ink
  _docs/_partners/message_personalization/dynamic_content/movable_ink.md
  assets/img/movable_ink/web2.png
Labels: cla-signed

#5582 Add redirects for CDI
  assets/js/broken_redirect_list.js
Labels: cla-signed

#5580 Pulling out PV and WV for search optimization
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/optimizations.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#5583 Update mentions of "drag & drop editor" to "drag-and-drop editor"
  _docs/_user_guide/message_building_by_channel/email.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/dnd_preference_center.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/overview.md
  _docs/_user_guide/message_building_by_channel/in-app_messages.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/editor_blocks.md
Labels: cla-signed

#5586 BD-2192: Update Canvas image
  assets/img_archive/add_components_flow.png
Labels: cla-signed

#5587 BD-2193: Add stopping Content Cards info
  _docs/_hidden/private_betas/idle_campaigns.md
Labels: cla-signed

#5588 Update heap.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/heap.md
Labels: cla-signed

#5585 Update the Census partner doc text and screenshots
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/census.md
  assets/img/census/add_service.png
  assets/img/census/census_1.png
  assets/img/census/census_2.png
  assets/img/census/census_3.png
Labels: cla-signed

#5590 Develop master merge
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/census.md
  assets/img/census/add_service.png
  assets/img/census/census_1.png
  assets/img/census/census_2.png
  assets/img/census/census_3.png
Labels: cla-signed

#5591 Census updates
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/census.md
  assets/img/census/add_service.png
  assets/img/census/census_1.png
  assets/img/census/census_2.png
  assets/img/census/census_3.png
Labels: cla-signed

#5592 BD-2190: IAM priority for Canvas
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
Labels: cla-signed

#5593 [CO-1626] Indicate that the free tier of storage is included with each plan
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
Labels: cla-signed

#5595 BD-2191: Add keyboard shortcuts for Canvas comments
  _docs/_hidden/private_betas/canvas_comments.md
Labels: cla-signed

#5594 Reminder to make Redshift Clusters publically accessable
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
Labels: cla-signed

#5598 BD-2201: Update Catalogs pro CSV requirements and screenshot
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  assets/img_archive/catalog_CSV_upload.png
Labels: cla-signed

#5600 Shopify catalogs (Hidden)
  _docs/_hidden/private_betas/phone_number_capture.md
  _docs/_hidden/private_betas/recommendations.md
  _docs/_hidden/private_betas/shopify_catalogs.md
Labels: cla-signed

#5597 BD-2199: Hidden Shopify multiple store support
  _docs/_hidden/private_betas/multiple_stores.md
  assets/img/multiple_stores.png
  assets/img/multiple_stores2.png
Labels: cla-signed

#5605 BD-2198: Add minimum SDK version
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
Labels: cla-signed

#5607 BD-2197: Clarify merge behavior details
  _docs/_api/endpoints/user_data/post_users_merge.md
Labels: cla-signed

#5606 Make some updates to CDI overview pages
  _docs/_user_guide/data_and_analytics/cloud_ingestion.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
Labels: cla-signed

#5601 Deploy - June 13, 2023
  _docs/_api/endpoints/user_data/post_users_merge.md
  _docs/_hidden/private_betas/canvas_comments.md
  _docs/_hidden/private_betas/canvas_drafts.md
  _docs/_hidden/private_betas/idle_campaigns.md
  _docs/_hidden/private_betas/multiple_stores.md
  _docs/_hidden/private_betas/phone_number_capture.md
  _docs/_hidden/private_betas/recommendations.md
  _docs/_hidden/private_betas/shopify_catalogs.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/heap.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/census.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
  _docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/whatsapp/overview.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  assets/img/census/add_service.png
  assets/img/census/census_1.png
  assets/img/census/census_2.png
  assets/img/census/census_3.png
  assets/img/multiple_stores.png
  assets/img/multiple_stores2.png
  assets/img_archive/add_components_flow.png
  assets/img_archive/catalog_CSV_upload.png
Labels: cla-signed, Deploy

#5611 Add verify to request
  _docs/_hidden/other/documentation_request.md
Labels: cla-signed

#5612 Remove EA alert
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
Labels: cla-signed

#5617 Update segment_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
Labels: cla-signed

#5618 Update standard_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
Labels: cla-signed

#5610 Changing references to "open source"
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization/custom_view_controller.md
  _docs/_user_guide/onboarding_with_braze/terms_to_know.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid.md
Labels: cla-signed

#5613 BD-2120: Add merge user profiles to Collection best practices
  _docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md
Labels: cla-signed

#5619 Deploy Pt.2 - June 14, 2023
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization/custom_view_controller.md
  _docs/_hidden/other/documentation_request.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _docs/_partners/isv_partners.md
  _docs/_partners/isv_partners/best_practices.md
  _docs/_partners/isv_partners/data_transformation.md
  _docs/_partners/isv_partners/snowflake_datasharing.md
  _docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
  _docs/_user_guide/onboarding_with_braze/terms_to_know.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid.md
  assets/img/snowflake.png
  assets/img/snowflake2.png
Labels: Deploy

#5373 Content card customizing styles
  _docs/_developer_guide/customization_guides/content_cards.md
  _docs/_developer_guide/customization_guides/content_cards/customizing_behavior.md
  _docs/_developer_guide/customization_guides/content_cards/customizing_feed.md
  _docs/_developer_guide/customization_guides/content_cards/customizing_styles.md
  _docs/_user_guide/message_building_by_channel/content_cards/creative_details.md
  assets/js/broken_redirect_list.js
Labels: status: on hold / do not merge, cla-signed

#5624 Update post_create_catalog.md
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md
Labels: cla-signed

#5622 BD-2210: Clarify changes to email settings
  _docs/_user_guide/administrative/app_settings/email_settings.md
  _docs/_user_guide/message_building_by_channel/email/faq.md
Labels: cla-signed

#5614 BD-2204: New parameter to export specific custom attributes for /users/export/segment
  _docs/_api/endpoints/export/user_data/post_users_segment.md
Labels: cla-signed

#5563 Update to Winning Path for one-time entry [Merge 6/15]
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/winning_path.md
  assets/img/experiment_step/experiment_one_time.png
  assets/img/experiment_step/experiment_one_time_results.png
Labels: cla-signed

#5625 Update popular topics in docs based on Google Analytics
  _docs/_docs_pages/index.md
  _docs/_help/home.md
Labels: cla-signed

#5626 Leftover Deploy - June 15, 2023
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/adding_braze_js_interface.md
  _docs/_docs_pages/index.md
  _docs/_help/home.md
  _docs/_user_guide/administrative/app_settings/email_settings.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/winning_path.md
  _docs/_user_guide/message_building_by_channel/email/faq.md
  assets/img/experiment_step/experiment_one_time.png
  assets/img/experiment_step/experiment_one_time_results.png
Labels: cla-signed, Deploy

#5627 Update overview.md - remove bcc from 'Advanced' functionality
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
Labels: cla-signed

#5628 Fix incorrect image reference
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/safari_mobile_push.md
Labels: cla-signed

#5545 Content Cards Logging Analytics
  _docs/_developer_guide/customization_guides/content_cards/logging_analytics.md
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
Labels: cla-signed

#5631 #BD-2194 Commenting on email templates
  _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
  assets/img/email_templates/template_comment.png
Labels: cla-signed

#5596 [DATALAKE] update schemas to remove deprecated view and add experiment_step
  assets/download_file/data-sharing-raw-table-schemas.txt
Labels: cla-signed

#5629 ContentCards GIF Support note
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/integration.md
  _docs/_user_guide/message_building_by_channel/content_cards/creative_details.md
Labels: cla-signed

#5632 BD-2213 Audience Sync to Facebook
  _docs/_partners/canvas_steps/facebook_audience_sync.md
Labels: cla-signed

#5634 Docs Style Suggestions
  _docs/_user_guide/data_and_analytics/analytics/conversions_dashboard.md
  _docs/_user_guide/data_and_analytics/analytics/email_performance_dashboard.md
  _docs/_user_guide/data_and_analytics/analytics/understanding_your_app_usage_data.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
  _docs/_user_guide/data_and_analytics/data_points.md
Labels: cla-signed

#5635 BD-2215: Add EA alert
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
Labels: cla-signed

#5636 [Partners] Updated WYNG intro wording
  _docs/_partners/message_personalization/dynamic_content/wyng.md
  _lang/fr/_partners/message_personalization/dynamic_content/wyng.md
Labels: cla-signed

#5640 BD-2218: Fix incorrect link
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
Labels: cla-signed

#5642 BD-2217: Fix custom footer image
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#5643 BD-2214: Updates to google audience sync
  _docs/_partners/canvas_steps/google_audience_sync.md
Labels: cla-signed

#5641 BD-2212: Update phone capture template form for EA
  _docs/_hidden/private_betas/phone_number_capture.md
  assets/img_archive/dnd_iam_phone_capture_analytics.png
  assets/img_archive/dnd_iam_phone_capture_example2.png
  assets/img_archive/dnd_iam_phone_capture_template.png
Labels: cla-signed

#5645 BD-2219: Clarify PUT and PATCH methods for catalog endpoints
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/patch_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/put_update_catalog_items.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/patch_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/put_update_catalog_item.md
Labels: cla-signed

#5647 Update templates landing page
  _docs/_home/templates.md
Labels: cla-signed

#5649 Page formatting updates for ISV
  _docs/_partners/isv_partners/api_partner.md
  _docs/_partners/isv_partners/best_practices.md
  _docs/_partners/isv_partners/cohort_import.md
  _docs/_partners/isv_partners/currents_integration.md
  _docs/_partners/isv_partners/data_transformation.md
  _docs/_partners/isv_partners/snowflake_datasharing.md
Labels: cla-signed

#5650 Docs Edit Suggestions
  _docs/_user_guide/data_and_analytics/reporting/report_builder.md
  _docs/_user_guide/data_and_analytics/reporting/retention_reports.md
  _docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/create.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/best_practices/high_volume_sending.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/best_practices/multi_country_sms_sending.md
  _docs/_user_guide/message_building_by_channel/sms/sms_laws_and_regulations.md
  _docs/_user_guide/message_building_by_channel/sms/sms_subscription_group.md
Labels: cla-signed

#5651 Update influenced_opens.md
  _docs/_user_guide/data_and_analytics/tracking/influenced_opens.md
Labels: cla-signed

#5652 Add quick links to Braze navigation article
  _docs/_user_guide/administrative/access_braze/navigation.md
  assets/img/navigation/quick_links.png
Labels: cla-signed

#5653 Zendesk updates
  _docs/_partners/data_and_infrastructure_agility/support/zendesk.md
  assets/img_archive/zendesk1.png
  assets/img_archive/zendesk2.png
  assets/img_archive/zendesk3.png
Labels: cla-signed

#5655 Deploy part 2 - June 21, 2023
  _docs/_home/templates.md
  _docs/_partners/data_and_infrastructure_agility/support/zendesk.md
  _docs/_partners/isv_partners/api_partner.md
  _docs/_partners/isv_partners/best_practices.md
  _docs/_partners/isv_partners/cohort_import.md
  _docs/_partners/isv_partners/currents_integration.md
  _docs/_partners/isv_partners/data_transformation.md
  _docs/_partners/isv_partners/snowflake_datasharing.md
  _docs/_user_guide/administrative/access_braze/navigation.md
  _docs/_user_guide/data_and_analytics/reporting/report_builder.md
  _docs/_user_guide/data_and_analytics/reporting/retention_reports.md
  _docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md
  _docs/_user_guide/data_and_analytics/tracking/influenced_opens.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/create.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/best_practices/high_volume_sending.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/best_practices/multi_country_sms_sending.md
  _docs/_user_guide/message_building_by_channel/sms/sms_laws_and_regulations.md
  _docs/_user_guide/message_building_by_channel/sms/sms_subscription_group.md
  assets/img/navigation/quick_links.png
  assets/img_archive/zendesk1.png
  assets/img_archive/zendesk2.png
  assets/img_archive/zendesk3.png
Labels: cla-signed, Deploy

#5657 BD-2220: Add AI copywriter to DND IAM docs
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
Labels: cla-signed

#5658 BD-2223 New Screenshots for Item Recommendations
  _docs/_hidden/private_betas/recommendations.md
  assets/img/add_personalization.png
  assets/img/item_recommendation_create.png
Labels: cla-signed

#5659 Remove "please"
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/safari_mobile_push.md
  _docs/_user_guide/administrative/privacy/managing_consent.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/message_building_by_channel/email/amphtml.md
Labels: cla-signed

#5661 Update Liquid platform capitalization
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
Labels: cla-signed

#5662 Update React Native push docs
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
Labels: cla-signed

#5663 BD-2202: Add additional example of raw text webhook
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  assets/img_archive/webhook_rawtext_URL-encoded.png
Labels: cla-signed

#5665 Fix dev guide layout
  _layouts/dev_guide.html
Labels: cla-signed

#5667 add DeleteObject back to data export tab for S3
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
Labels: cla-signed

#5668 Update AI copywriting with DND IAM change
  _docs/_user_guide/intelligence/ai_copywriting.md
Labels: cla-signed

#5669 Update phone capture to make SDK requirements more explicit
  _docs/_hidden/private_betas/phone_number_capture.md
Labels: cla-signed

#5670 Leftover Deploy Pt.2 - June 22, 2023
  _docs/_api/endpoints/messaging/schedule_messages/post_delete_scheduled_triggered_canvases.md
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/safari_mobile_push.md
  _docs/_hidden/private_betas/phone_number_capture.md
  _docs/_hidden/private_betas/recommendations.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
  _docs/_user_guide/administrative/privacy/managing_consent.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/intelligence/ai_copywriting.md
  _docs/_user_guide/intelligence/intelligent_timing.md
  _docs/_user_guide/message_building_by_channel/email/amphtml.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
  _layouts/dev_guide.html
  assets/img/add_personalization.png
  assets/img/item_recommendation_create.png
  assets/img_archive/webhook_rawtext_URL-encoded.png
Labels: cla-signed, Deploy

#5675 Add tip and GIF for AI copywriter in IAM DND
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  assets/img_archive/dnd_iam_ai_copywriter.gif
Labels: cla-signed

#5676 User Data Collection edits
  _docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md
  _docs/_user_guide/data_and_analytics/user_data_collection/collection_use_case.md
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_archival.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
Labels: cla-signed

#5680 Custom Data edit suggestions
  _docs/_user_guide/data_and_analytics/custom_data.md
  _docs/_user_guide/data_and_analytics/custom_data/blocklist_delete_custom_data.md
  _docs/_user_guide/data_and_analytics/custom_data/event_naming_conventions.md
  _docs/_user_guide/data_and_analytics/custom_data/pre-populating_custom_data.md
Labels: cla-signed

#5683 BD-2133: Clarify custom event property segmentation
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
Labels: cla-signed

#5682 Hide /users/subscription docs
  _docs/_api/endpoints/email.md
  _docs/_api/endpoints/email/delete_remove_subscription_state.md
  _docs/_api/endpoints/email/get_query_by_email_or_phone.md
  _docs/_api/home.md
Labels: cla-signed

#5684 BD-2230 Editing old Content Blocks with Link Aliasing enabled
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
Labels: cla-signed

#5685 Add CORS requirement for custom fonts
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
Labels: cla-signed

#5686 BD-2184: Add missing SQL tables to reference page
  _docs/_hidden/private_betas/sql_segments_tables.md
Labels: cla-signed

#5616 [SDK-3674] FF Unity
  _docs/_developer_guide/platform_wide/feature_flags/create.md
Labels: cla-signed

#5674 Roku markdown
  _docs/_developer_guide/platform_integration_guides/roku/analytics/logging_custom_events.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/roku/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/roku/initial_sdk_setup.md
Labels: cla-signed

#5673 [SDK-3842] ff roku
  _docs/_developer_guide/platform_wide/feature_flags/about.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
  _docs/_developer_guide/platform_wide/feature_flags/faq.md
Labels: cla-signed

#5688 BD-2231: Update privacy portal headers
  _docs/_user_guide/privacy_portal.md
Labels: cla-signed

#5687 BD-2229: Updates to Shopify multiple store support
  _docs/_hidden/private_betas/multiple_stores.md
Labels: cla-signed

#5679 BD-2225: Clarify merge behavior
  _docs/_api/endpoints/user_data/post_users_merge.md
Labels: cla-signed

#5677 June 2023 release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023.md
  _docs/_help/release_notes/2023/6_27_23.md
Labels: cla-signed, release notes

#5690 Style edits for API rate limits doc
  _docs/_api/api_limits.md
Labels: cla-signed

#5693 BD-2234 Changes to AI Copywriting
  _docs/_user_guide/intelligence/ai_copywriting.md
Labels: cla-signed

#5602 BD-2189: Saving Drafts for Canvas GA
  _docs/_hidden/private_betas/canvas_drafts.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/archiving_canvases.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/canvas_drafts.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/canvas_version_history.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
Labels: cla-signed

#5696 Add saving drafts for Canvas to release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023/6_27_23.md
Labels: cla-signed

#5698 Deploy Pt. 2 - June 27, 2023
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023/6_27_23.md
  _docs/_hidden/private_betas/canvas_drafts.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/archiving_canvases.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/canvas_drafts.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/canvas_version_history.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
  _docs/_user_guide/intelligence/ai_copywriting.md
Labels: cla-signed, Deploy

#5697 Update customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
Labels: cla-signed

#5700 BD-2233 Deprecation of Dismiss Notification
  _docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_action_buttons.md
  assets/img_archive/push_action_buttons_android.png
Labels: cla-signed

#5701 Minor edits for archiving segments
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
Labels: cla-signed

#5702 clarify web openSession calls last
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
Labels: cla-signed

#5703 BD-2236 Update state_change_source in Message Engagements Events
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#5704 BD-2237 Update Query Builder credits tracker screenshot
  _docs/_user_guide/data_and_analytics/query_builder.md
  assets/img_archive/query_builder_credits.png
Labels: cla-signed

#5705 BD-2228: Update report metrics with WhatsApp
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _includes/campaign_analytics.md
  assets/img/whatsapp_message_performance.png
Labels: cla-signed

#5706 BD-2238: Cloning Canvases with branching now supported
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
Labels: cla-signed

#5708 Pull Content Card metric dropdown into main article
  _includes/campaign_analytics.md
Labels: cla-signed

#5707 flutter remove underscores
  _docs/_developer_guide/platform_integration_guides/flutter/content_cards.md
  _docs/_developer_guide/platform_integration_guides/flutter/inapp_messages.md
Labels: cla-signed

#5709 BD-2239 Blur personal information in screenshot
  assets/img/whatsapp/whatsapp8.png
Labels: cla-signed

#5710 Feature Flags on Flutter SDK
  _docs/_developer_guide/platform_wide/feature_flags/about.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
  _docs/_developer_guide/platform_wide/feature_flags/faq.md
Labels: cla-signed

#5712 Leftover Deploy - June 29, 2023
  _docs/_developer_guide/platform_integration_guides/flutter/content_cards.md
  _docs/_developer_guide/platform_integration_guides/flutter/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_developer_guide/platform_wide/feature_flags/about.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
  _docs/_developer_guide/platform_wide/feature_flags/faq.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/query_builder.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_action_buttons.md
  _includes/campaign_analytics.md
  assets/img/whatsapp/whatsapp8.png
  assets/img/whatsapp_message_performance.png
  assets/img_archive/push_action_buttons_android.png
  assets/img_archive/query_builder_credits.png
Labels: Deploy

#5713 BD-2107 Enable Verbose Logging in Unity editor
  _docs/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md
  _docs/_developer_guide/platform_integration_guides/unity/sdk_integration/ios.md
Labels: cla-signed

#5715 Add tab query and cookie
  _plugins/tabs.rb
  assets/js/documents.js
Labels: cla-signed

#5716 Update customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
Labels: cla-signed

#5717 Update message_engagement_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#5718 BD-2240 Update Live Activities FAQ
  _docs/_developer_guide/platform_integration_guides/swift/live_activities/faq.md
Labels: cla-signed

#5714 Replace Content Card creative details images
  _docs/_user_guide/message_building_by_channel/content_cards/creative_details.md
  assets/img/content_card_banner.png
  assets/img/content_card_captioned.png
  assets/img/content_card_classic.png
Labels: cla-signed

#5719 Update message_engagement_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#5720 Update customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
Labels: cla-signed
