Repository braze-inc/braze-docs, pull requests merged in 2023-10, with the labels that each got.

#6257 BD-2465: Clarify control group details for editing Canvas after launch
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
Labels: cla-signed

#6226 sdk device brand data
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
Labels: cla-signed

#6243 [SDK-4096] Update In-App Messaging for Unity
  _docs/_developer_guide/platform_integration_guides/unity/in-app_messaging.md
Labels: cla-signed

#6215 Add note about IDFV being disabled by default in Swift SDK 7.0.0
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations/swift_idfv.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/swift_idfv.md
Labels: status: on hold / do not merge, cla-signed

#6259 Revert "Add note about IDFV being disabled by default in Swift SDK 70.0"
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations/swift_idfv.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/swift_idfv.md
Labels: cla-signed

#6255 BD-2471 WhatsApp Updates
  _docs/_user_guide/message_building_by_channel/whatsapp/faqs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md
  _includes/campaign_analytics.md
Labels: cla-signed

#6261 Update best_practices.md
  _docs/_partners/isv_partners/best_practices.md
Labels: cla-signed

#6258 BD-2464 Add details about updated phone numbers and subscription groups
  _docs/_user_guide/message_building_by_channel/sms/sms_subscription_group.md
Labels: cla-signed

#6260 Add note about IDFV being disabled by default in Swift SDK 70.0
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations/swift_idfv.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/swift_idfv.md
Labels: cla-signed

#6254 BD-2466 Adding pod target explanation for push stories
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/push_story.md
Labels: cla-signed

#6264 Deploy - October 3, 2023
  _docs/_api/api_limits.md
  _docs/_api/basics.md
  _docs/_api/endpoints/cdi.md
  _docs/_api/endpoints/cdi/get_integration_list.md
  _docs/_api/endpoints/cdi/get_job_sync_status.md
  _docs/_api/endpoints/cdi/post_job_sync.md
  _docs/_api/home.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations/swift_idfv.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/swift_idfv.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/push_story.md
  _docs/_developer_guide/platform_integration_guides/unity/in-app_messaging.md
  _docs/_help/help_articles/email.md
  _docs/_help/help_articles/email/html_looks_strange.md
  _docs/_help/help_articles/email/open_rates.md
  _docs/_hidden/private_betas/campaign_data_retention.md
  _docs/_partners/isv_partners/best_practices.md
  _docs/_partners/message_orchestration/attribution/branch/branch_for_deeplinking.md
  _docs/_partners/message_personalization/location/radar.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_custom_event_data.md
  _docs/_user_guide/data_and_analytics/export_braze_data/exporting_revenue_data.md
  _docs/_user_guide/data_and_analytics/reporting.md
  _docs/_user_guide/data_and_analytics/reporting/reports_overview.md
  _docs/_user_guide/data_and_analytics/reporting/revenue_report.md
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/feature_flags.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _docs/_user_guide/message_building_by_channel/email/email_setup/consent_and_address_collection.md
  _docs/_user_guide/message_building_by_channel/email/faq.md
  _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/templates/simple_survey.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/unknown_phone_numbers.md
  _docs/_user_guide/message_building_by_channel/sms/sms_subscription_group.md
  _docs/_user_guide/message_building_by_channel/whatsapp/faqs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/user_messages.md
  _docs/_user_guide/message_building_by_channel/whatsapp/overview.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md
  _docs/_user_guide/sage_ai/predictive_suite/predictive_churn/prediction_analytics/prediction_quality.md
  _includes/campaign_analytics.md
  _includes/rate_limits.md
  assets/img/custom_events_report_filters.png
  assets/img/revenue_report.png
  assets/img/revenue_report_product_breakdown.png
  assets/img_archive/Export_events.png
  assets/img_archive/Export_revenue_graph.png
  assets/img_archive/Export_revenue_product_breakdown.png
  assets/img_archive/custom_event_analytics_example.png
  assets/img_archive/rest-api-key.png
  assets/img_archive/view-api-key.png
Labels: cla-signed

#6265 Add payload size limitation for CDI
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
Labels: cla-signed

#6256 BD-2474: Copying campaigns across workspaces GA - MERGE 10/5
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/copying_to_workspace.md
Labels: cla-signed, release notes

#6268 FF Impressions
  _docs/_developer_guide/platform_wide/feature_flags/create.md
Labels: cla-signed

#6263 BD-2483 AI SQL Generator
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
  assets/img/ai_sql_generator.png
Labels: cla-signed

#6270 BD-2488 Incorrect link for API triggered campaigns
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_campaigns.md
Labels: cla-signed

#6267 BD-2469: Feature Flag experiments
  _docs/_developer_guide/platform_wide/feature_flags.md
  _docs/_developer_guide/platform_wide/feature_flags/experiments.md
  assets/img/feature_flags/feature_flag_experiment_override.png
Labels: cla-signed

#6272 Fix format issue
  _docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md
Labels: cla-signed

#6275 Updated instances of "banner" content cards to "imageOnly"
  _docs/_developer_guide/customization_guides/content_cards/creating_custom_content_cards.md
  _docs/_developer_guide/customization_guides/content_cards/logging_analytics.md
  _docs/_developer_guide/customization_guides/customization_overview.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/customization/key_value_pairs.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/integration.md
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/content_cards/creative_details.md
Labels: cla-signed

#6276 BD-2480: New article for language settings
  _docs/_user_guide/administrative/access_braze.md
  _docs/_user_guide/administrative/access_braze/language.md
  assets/img_archive/language_dashboard.png
Labels: cla-signed

#6274 BD-2489: Clarify limitations with event properties
  _docs/_user_guide/message_building_by_channel/push/android/push_max.md
Labels: cla-signed

#6278 Fix product limits on number of attributes
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
Labels: cla-signed

#5813 Swift v7.0.0 UUID
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations/swift_idfv.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/swift_idfv.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6279 BD-2482: Add side-by-side integration links for Rudderstack
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack/rudderstack.md
Labels: cla-signed

#6277 Update overview.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
Labels: cla-signed

#6273 CSS tweaks
  assets/css/_details.scss
  assets/css/application.scss
  assets/css/main.scss
Labels: cla-signed

#6283 Leftover Deploy - October 5, 2023
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_campaigns.md
  _docs/_developer_guide/customization_guides/content_cards/creating_custom_content_cards.md
  _docs/_developer_guide/customization_guides/content_cards/logging_analytics.md
  _docs/_developer_guide/customization_guides/customization_overview.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations/swift_idfv.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/swift_idfv.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/customization/key_value_pairs.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/integration.md
  _docs/_developer_guide/platform_wide/feature_flags.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
  _docs/_developer_guide/platform_wide/feature_flags/experiments.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack/rudderstack.md
  _docs/_user_guide/administrative/access_braze.md
  _docs/_user_guide/administrative/access_braze/language.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
  _docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/copying_to_workspace.md
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/content_cards/creative_details.md
  _docs/_user_guide/message_building_by_channel/push/android/push_max.md
  assets/css/_details.scss
  assets/css/application.scss
  assets/css/main.scss
  assets/img/ai_sql_generator.png
  assets/img/feature_flags/feature_flag_experiment_override.png
  assets/img_archive/language_dashboard.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#6285 BD-2495: Fix incorrect permalink and parent page links
  _docs/_api/endpoints/cdi.md
  _docs/_api/endpoints/cdi/get_job_sync_status.md
Labels: cla-signed

#6289 BD-2499: Currents Field Transformations can apply only to string type
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
Labels: cla-signed

#6287 Add note about databricks instance types and warmup time
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
Labels: cla-signed

#6290 BD-2492 Remove old FAQ on link shortening custom domain
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
Labels: cla-signed

#6291 Liquid OKR: add Liquid use cases to the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla-signed

#6292 Update docs ticket confirmation message
  _docs/_hidden/other/documentation_request.md
Labels: cla-signed

#6293 BD-2459: Update images and add exit criteria for Create a Canvas
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  assets/img/quiet_hours.png
  assets/img_archive/message_setup_settings_flow.png
Labels: cla-signed

#6262 BD-2479 Metrics for deliveries and sends
  _docs/_user_guide/data_and_analytics/report_metrics.md
Labels: cla-signed

#6295 BD-2502: Remove mention of IAM in intelligent timing
  _docs/_user_guide/sage_ai/intelligence/intelligent_timing.md
Labels: cla-signed

#6282 [DLK-1268] Add Private Network documentation for redshift
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
  assets/img/cloud_ingestion/ingestion_6.png
Labels: cla-signed

#6298 BD-2493 Clarify user permissions
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#6296 BD-2470: Clean up link aliasing and link template articles
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
Labels: cla-signed

#6297 Update onetrust.md
  _docs/_partners/data_and_infrastructure_agility/data_privacy/onetrust.md
Labels: cla-signed

#6299 BD-2496: User import allows strings with commas with use of double quotes
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Labels: cla-signed

#6300 BD-2503 Fix error in the example request for SCIM GET endpoint
  _docs/_api/endpoints/scim/get_search_existing_dashboard_user.md
Labels: cla-signed

#6301 Make Josh and Rachel code owners for Liquid use cases
  .github/CODEOWNERS
Labels: cla-signed

#6303 BD-2494: Add time limit for evaluation window for action paths
  _docs/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md
Labels: cla-signed

#6302 BD-2402: Add example for updating field in an existing array of objects
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
Labels: cla-signed

#6304 BD-2504: Add caveat for being globally unsubscribed
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#6247 [SDK-4094] Note that we support Dark Mode by default on Swift and ObjC Content Cards
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization/custom_styling.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/integration.md
Labels: cla-signed

#6281 BD-2476 Create SPM and Cocoapods section for Rich Push
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/customization/rich_notifications.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/push_story.md
  assets/img_archive/rich_notification.png
  assets/img_archive/rich_notification2.png
Labels: cla-signed

#6306 BD-2508: Merging user profiles GA
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
Labels: cla-signed, release notes

#6222 BD-2448: Updating user profile by email or phone number GA - MERGE 10/10
  _docs/_api/endpoints/user_data/post_users_merge.md
  _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
  _docs/_user_guide/data_and_analytics/data_transformation/overview.md
  _docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md
Labels: cla-signed, release notes

#6308 [CO-2007] Update profile merge behavior documentation
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
Labels: cla-signed

#6309 BD-2509 Add tip to AI SQL Generator
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
Labels: cla-signed

#6284 BD-2485: Updating mParticle Audience Forwarding to reflect recent update
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle.md
  assets/img_archive/mparticle5.png
Labels: cla-signed

#6156 Q3 feedback and Liquid audit
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
Labels: cla-signed

#6310 Deploy - October 10, 2023
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  _docs/_api/endpoints/cdi.md
  _docs/_api/endpoints/cdi/get_job_sync_status.md
  _docs/_api/endpoints/scim/get_search_existing_dashboard_user.md
  _docs/_api/endpoints/user_data/post_users_merge.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization/custom_styling.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/customization/rich_notifications.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/push_story.md
  _docs/_hidden/other/documentation_request.md
  _docs/_hidden/private_betas/ai_step.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle.md
  _docs/_partners/data_and_infrastructure_agility/data_privacy/onetrust.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events/nested_objects.md
  _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
  _docs/_user_guide/data_and_analytics/data_transformation/overview.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties/canvas_persistent_entry_properties.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
  _docs/_user_guide/onboarding_faq.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
  _docs/_user_guide/sage_ai/intelligence/intelligent_timing.md
  assets/img/ai_step1.png
  assets/img/ai_step2.png
  assets/img/ai_step3.png
  assets/img/ai_step4.png
  assets/img/ai_step5.png
  assets/img/cloud_ingestion/ingestion_6.png
  assets/img/quiet_hours.png
  assets/img_archive/message_setup_settings_flow.png
  assets/img_archive/mparticle5.png
  assets/img_archive/rich_notification.png
  assets/img_archive/rich_notification2.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#6311 Add a period
  _docs/_api/endpoints/cdi/get_job_sync_status.md
Labels: cla-signed

#6312 Fix Liquid syntax error with raw tags
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#6313 Fix incorrect searchableAttributes for Algolia
  _config.yml
Labels: cla-signed

#6314 Deploy pt.2 - October 10, 2023
  _config.yml
  _docs/_api/endpoints/cdi/get_job_sync_status.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed, Deploy

#6269 BD-2484 Performance data by segment
  _docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md
  assets/img_archive/segment_breakdown.png
  assets/img_archive/segment_breakdown_results.png
  assets/img_archive/variables_panel.png
Labels: cla-signed

#6317 Update font size of API
  assets/css/_api.scss
Labels: cla-signed

#6318 Removed duplicate IDFV article
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/swift_idfv.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/swift_idfv.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6319 BD-2505: Clarify merge behavior for custom attributes in user profiles
  _docs/_api/endpoints/user_data/post_users_merge.md
Labels: cla-signed

#6305 BD-2498: Update block sample message in Message Activity Log
  _docs/_user_guide/administrative/app_settings/message_activity_log_tab.md
Labels: cla-signed

#6271 BD-2477: Update in-app message reporting with conversion guidance
  _includes/campaign_analytics.md
Labels: cla-signed

#6320 BD-2486: Clarifying unsubscribes behavior with duplicate emails
  _docs/_user_guide/message_building_by_channel/email/best_practices/managing_email_subscriptions.md
Labels: cla-signed

#6323 BD-2510: Clarify Content Block updating behavior for drag-and-drop email editor
  _docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
Labels: cla-signed

#6325 BD-2507: Add workaround for viewing all link templates
  _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
Labels: cla-signed

#6321 BD-2475 Rename appboyBridge to brazeBridge
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize/html_in-app_messages.md
Labels: cla-signed

#6315 BD-2478: Reformatting report metric glossary to use new glossary layout
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _layouts/report_metrics.html
Labels: cla-signed

#6288 Cohort Import restructuring
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_audiences.md
  _docs/_partners/data_and_infrastructure_agility/analytics/kubit.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/amplitude.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/appsflyer.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/appsflyer_audiences.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/hightouch.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/kubit.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/mixpanel.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/hightouch.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/hightouch/hightouch.md
  _docs/_partners/message_orchestration/attribution/appsflyer.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _docs/_partners/message_personalization/dynamic_content/storyly.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6328 Leftover Deploy - October 12, 2023
  _docs/_api/endpoints/cdi/get_job_sync_status.md
  _docs/_api/endpoints/user_data/post_users_merge.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/swift_idfv.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/swift_idfv.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_audiences.md
  _docs/_partners/data_and_infrastructure_agility/analytics/kubit.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/amplitude.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/appsflyer.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/appsflyer_audiences.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/hightouch.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/kubit.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/mixpanel.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/hightouch.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/hightouch/hightouch.md
  _docs/_partners/message_orchestration/attribution/appsflyer.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _docs/_partners/message_personalization/dynamic_content/storyly.md
  _docs/_user_guide/administrative/app_settings/message_activity_log_tab.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md
  _docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/managing_email_subscriptions.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize/html_in-app_messages.md
  _includes/campaign_analytics.md
  _layouts/report_metrics.html
  assets/css/_api.scss
  assets/img_archive/segment_breakdown.png
  assets/img_archive/segment_breakdown_results.png
  assets/img_archive/variables_panel.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#6324 [SDK-4256] IAM Display Option .later deprecated for .reenqueue
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/setting_delegates.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/in-app_message_delivery.md
Labels: cla-signed

#6329 Revert "[SDK-4256] IAM Display Option .later deprecated for .reenqueue"
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/setting_delegates.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/in-app_message_delivery.md
Labels: cla-signed

#6331 BD-2491: Add new column to navigation table
  _docs/_user_guide/administrative/access_braze/navigation.md
Labels: cla-signed

#6334 BD-2526 Unhide Test Currents connectors
  _docs/_hidden/private_betas/test_connectors.md
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6335 Update experiments.md
  _docs/_developer_guide/platform_wide/feature_flags/experiments.md
Labels: cla-signed

#6336 Leftover Deploy pt.2 - October 13, 2023
  _docs/_developer_guide/platform_wide/feature_flags/experiments.md
  _docs/_hidden/private_betas/test_connectors.md
  _docs/_user_guide/administrative/access_braze/navigation.md
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#6337 BD-2514 Add detail to WhatsApp opt-in
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/handling_unknown_numbers.md
Labels: cla-signed

#6338 BD-2517 Update images in User Profiles
  assets/img_archive/profiles_engagement_tab.png
  assets/img_archive/profiles_messaging_history_tab.png
  assets/img_archive/user_profile2.png
Labels: cla-signed

#6341 BD-2529: Fix incorrect term
  _docs/_user_guide/administrative/access_braze/navigation.md
Labels: cla-signed

#6155 Add "Launch and Manage Content Blocks" user permission
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#6343 BD-2521 Update Deprecations article with appboyBridge
  _docs/_help/release_notes/deprecations.md
Labels: cla-signed

#6344 Update Winning Path in Experiment Paths with clarifying screenshots
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/winning_path.md
  assets/img/experiment_step/experiment_path_distribution.png
  assets/img/experiment_step/experiment_winning_path_recurring.png
  assets/img/experiment_step/experiment_winning_settings.png
  assets/img/experiment_step/experiment_winning_statistical.png
Labels: cla-signed

#6345 BD-2525: Add tips for encoding emails in URL and using `email` parameter
  _docs/_api/endpoints/email/get_list_hard_bounces.md
Labels: cla-signed

#6346 Update triggered_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md
Labels: cla-signed

#6347 Add `push_tokens` for Export user profile by segment
  _docs/_api/endpoints/export/user_data/post_users_segment.md
Labels: cla-signed

#6307 BD-2497: Back-in-stock feature for Shopify catalogs EA - MERGE 10/17
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_catalogs/back_in_stock.md
  assets/img/back_in_stock_settings.png
  back_in_stock_settings.png
Labels: cla-signed

#6348 BD-2535: Fix Data Transformation link
  _docs/_user_guide/data_and_analytics/data_transformation/overview.md
Labels: cla-signed

#6351 Deploy - October 17, 2023
  _docs/_api/endpoints/email/get_list_hard_bounces.md
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023.md
  _docs/_help/release_notes/2023/10_17_23.md
  _docs/_help/release_notes/deprecations.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_catalogs/back_in_stock.md
  _docs/_user_guide/administrative/access_braze/navigation.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/data_and_analytics/data_transformation/overview.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/winning_path.md
  assets/img/back_in_stock_settings.png
  assets/img/experiment_step/experiment_path_distribution.png
  assets/img/experiment_step/experiment_winning_path_recurring.png
  assets/img/experiment_step/experiment_winning_settings.png
  assets/img/experiment_step/experiment_winning_statistical.png
  back_in_stock_settings.png
Labels: cla-signed, Deploy

#6349 BD-2528: Clarify email self-service setup is only for onboarding customers
  _docs/_user_guide/message_building_by_channel/email/email_setup/setting_up_ips_and_domains.md
Labels: cla-signed

#6350 BD-2516: Add steps for setting up Google Postmaster Tools account
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
  assets/img_archive/domain_authentication.png
  assets/img_archive/domain_verification.png
Labels: cla-signed

#6353 BD-2533 Fix character code
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Labels: cla-signed

#6354 BD-2536 Update custom domain requirements
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
Labels: cla-signed

#6339 BD-2506: Content Card expiration in Canvas
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_by_channel/content-cards_in_canvas.md
Labels: cla-signed

#6360 [SDK-4149] Add note on Carthage for Swift SDK
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/overview.md
Labels: cla-signed

#6359 Remove mentions of specific channels
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/copying_to_workspace.md
Labels: cla-signed

#6368 Ck cdi email phone 1
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/overview.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_by_channel/content-cards_in_canvas.md
Labels: cla-signed

#6369 BD-2541: Remove "JSON" from "What's copied across workspaces"
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/copying_to_workspace.md
Labels: cla-signed

#6358 Update for CDI including email and phone support
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
Labels: cla-signed

#6367 BD-2518 Change whitelisting to allowlisting
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
  _docs/_api/objects_filters/schedule_object.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
  _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
  _docs/_help/release_notes/2016/october.md
  _docs/_hidden/other/support_contact.md
  _docs/_user_guide/administrative/app_settings/company_settings/security_settings.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md
  _docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/sms/faqs.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
  _lang/fr/_api/basics.md
Labels: cla-signed

#6357 BD-2532 and BD-2512: Update Home (overview) page and adds support for LaTeX
  _docs/_user_guide/data_and_analytics/analytics.md
  _docs/_user_guide/data_and_analytics/analytics/home_dashboard.md
  _docs/_user_guide/data_and_analytics/analytics/understanding_your_app_usage_data.md
  _docs/_user_guide/data_and_analytics/export_braze_data/exporting_app_usage_data.md
  _includes/html_include.html
  assets/img_archive/home_dashboard.png
  assets/img_archive/home_dashboard_breakdown.png
  assets/img_archive/home_dashboard_export.png
  assets/img_archive/home_dashboard_metric_tile.png
  assets/img_archive/home_dashboard_select_date.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6370 BD-2539: Fix typo in code snippet for updating custom nested attributes
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
Labels: cla-signed

#6371 Fixing Lytics PR due to CLA-signing issue
  _docs/_hidden/wip_partnerships/lytics/lytics.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/lytics.md
  _docs/_partners/home.md
  assets/img/lytics/authorization_method.png
  assets/img/lytics/braze_authorization.png
  assets/img/lytics/braze_backfill.png
  assets/img/lytics/braze_job.png
  assets/img/lytics/braze_jobauth.png
  assets/img/lytics/braze_jobtype.png
  assets/img/lytics/configure_job.png
  assets/img/lytics/create_token.png
  assets/img/lytics/data_manager.png
Labels: cla-signed, Braze Partnerships

#6363 add config error in job_status error types
  _docs/_api/endpoints/cdi/get_job_sync_status.md
Labels: cla-signed

#6327 [SDK-3429] Swift - Document BrazeDelegate.(_:noMatchingTriggerForEvent)
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/in-app_message_delivery.md
Labels: cla-signed

#6376 Include info about retargeting by tag
  _docs/_hidden/private_betas/campaign_data_retention.md
Labels: cla-signed

#6375 Update create_multivariate_campaign.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
Labels: cla-signed

#6130 BD-2399 Amperity overhaul
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/amperity.md
  assets/img/amperity/braze_settings.png
  assets/img/amperity/custom_attributes_filters.png
  assets/img/amperity/data_template_name.png
  assets/img/amperity/destination_name.png
  assets/img/amperity/edit_campaign_attributes.png
  assets/img/amperity/search_custom_attributes_filters.png
  assets/img/amperity/select_segments.png
Labels: cla-signed

#6326 BD-2511: Update email template article
  _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
  assets/img/email_templates/template2.png
Labels: cla-signed

#6377 BD-2537: Remove promotion code link from IAM
  _docs/_user_guide/message_building_by_channel/in-app_messages/about.md
Labels: cla-signed

#6378 Remove Lytics from WIP folder
  _docs/_hidden/wip_partnerships/lytics/lytics.md
Labels: cla-signed

#6379 BD-2500: Include user permissions for email self-service
  _docs/_user_guide/message_building_by_channel/email/email_setup/setting_up_ips_and_domains.md
Labels: cla-signed

#6382 BD-2530: Add best practices for submitting a support case
  _docs/_help/support.md
Labels: cla-signed

#6384 BD-2545 Small edit for blacklist alert
  _docs/_api/endpoints/email/post_blacklist.md
Labels: cla-signed

#6380 BD-2522 Media Library benefits
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
Labels: cla-signed

#6373 BD-2543 WhatsApp hidden page
  _docs/_hidden/private_betas/whatsapp_response_messaging.md
  assets/img/whatsapp/whatsapp_message_variants.png
  assets/img/whatsapp/whatsapp_response_messages.png
  assets/img/whatsapp/whatsapp_templates.png
  assets/img/whatsapp/whatsapp_test_phone_number.png
Labels: cla-signed

#6386 BD-2547: Fix AMP email opens metric definition
  _docs/_user_guide/message_building_by_channel/email/amphtml.md
Labels: cla-signed

#6387 Remove old EA banners
  _docs/_api/endpoints/user_data/post_user_track.md
Labels: cla-signed

#6388 Delete back_in_stock_settings.png
  back_in_stock_settings.png
Labels: cla-signed

#6330 [SDK-4256] IAM Display Option .later deprecated for .reenqueue
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/setting_delegates.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/in-app_message_delivery.md
Labels: cla-signed

#6389 [SDK-4150] Add docs with further details about IAM buttons
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/setting_delegates.md
Labels: cla-signed

#6392 BD-2549: Clarify quick push entry point
  _docs/_hidden/private_betas/quick_push.md
Labels: cla-signed

#6393 Remove "chat" from ChatGPT
  _docs/_user_guide/sage_ai/generative_ai/ai_content_qa.md
Labels: cla-signed

#6394 BD-2478: Fixes for missing glossary items
  _docs/_user_guide/data_and_analytics/report_metrics.md
Labels: cla-signed

#6398 Spellcheck edits: "Project" to "project"
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
Labels: cla-signed

#6396 Spellcheck edits: Creating a catalog
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
Labels: cla-signed

#6403 Add US-07.
  _docs/_api/basics.md
  _docs/_home/styling_test_page.md
  _docs/_partners/isv_partners/cohort_import.md
  _docs/_user_guide/administrative/access_braze/sdk_endpoints.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
  _lang/fr/_api/basics.md
  _lang/fr/_partners/isv_partners/cohort_import.md
  _lang/fr/_user_guide/administrative/access_braze/braze_instances.md
  _lang/fr/_user_guide/administrative/access_braze/sdk_endpoints.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/redshift.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/snowflake.md
  _lang/fr/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
Labels: cla-signed

#6404 Fix sample GeoJSON file
  _docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md
Labels: cla-signed

#6405 BD-2554 Huawei Client Secret renaming
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/huawei_integration.md
Labels: cla-signed

#6400 Spellcheck edits: Sheetdb to SheetDB
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/localizing_a_campaign.md
Labels: cla-signed

#6402 Spellcheck edits: Update to "Creation"
  _docs/_user_guide/message_building_by_channel/content_cards/create/card_creation.md
Labels: cla-signed

#6399 Spellcheck edits: IDFA and ad ID
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#6401 Spellcheck edits: Remove "CSM"
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
Labels: cla-signed

#6409 Spellcheck edits: Remove sentence
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
Labels: cla-signed

#6406 Spellcheck edits: Add hyphen
  _docs/_user_guide/message_building_by_channel/sms/mms/contact_card.md
Labels: cla-signed

#6408 Spellcheck edits: Remove COM/CSM
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/10dlc.md
Labels: cla-signed

#6410 Spellcheck edits: User Guide section
  _docs/_user_guide/administrative/access_braze/navigation.md
  _docs/_user_guide/administrative/app_settings/custom_event_and_attribute_management.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/teams.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/administrative/privacy/spam_regulations.md
  _docs/_user_guide/data_and_analytics/analytics/email_performance_dashboard.md
  _docs/_user_guide/data_and_analytics/braze_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
  _docs/_user_guide/data_and_analytics/reporting.md
  _docs/_user_guide/data_and_analytics/reporting/global_control_group_reporting.md
  _docs/_user_guide/data_and_analytics/reporting/report_builder.md
  _docs/_user_guide/data_and_analytics/reporting/reports_overview.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/scheduled_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/time_based_campaign.md
  _docs/_user_guide/engagement_tools/campaigns/getting_started/campaign_basics.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/active_user_campaigns.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/copying_to_workspace.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_comments.md
  _docs/_user_guide/engagement_tools/canvas/get_started/the_basics.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/canvas_version_history.md
  _docs/_user_guide/engagement_tools/canvas/testing_canvases/measuring_and_testing_with_canvas_analytics.md
  _docs/_user_guide/engagement_tools/segments/regex.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/engagement_tools/segments/segment_insights.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/content_cards/creative_details.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/guidelines_and_tips.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize/video.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/dark-mode.md
  _docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_action_buttons.md
  _docs/_user_guide/message_building_by_channel/push/android/rich_notifications.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/message_format.md
  _docs/_user_guide/message_building_by_channel/push/ios/advanced_campaign_settings.md
  _docs/_user_guide/message_building_by_channel/push/ios/rich_notifications.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/retargeting.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/sms_double_opt_in.md
  _docs/_user_guide/message_building_by_channel/sms/sms_setup.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  _docs/_user_guide/message_building_by_channel/webhooks/understanding_webhooks.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md
  _docs/_user_guide/onboarding_faq.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/public_apis.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
  _docs/_user_guide/sage_ai/intelligence/faqs.md
  _docs/_user_guide/sage_ai/intelligence/intelligent_timing.md
Labels: cla-signed

#6412 BD-2552 update contact emails information in cloud ingestion
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
Labels: cla-signed

#6418 Add definition for conversion window
  _docs/_user_guide/data_and_analytics/report_metrics.md
Labels: cla-signed

#6407 Fix UI for Huawei push integration
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/huawei_integration.md
Labels: cla-signed

#6420 BD-2551: Fixing small typo in Treasure Data
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/treasure_data/treasure_data.md
Labels: cla-signed

#6419 Clarify prerequisites for self-service email setup
  _docs/_user_guide/message_building_by_channel/email/email_setup/setting_up_ips_and_domains.md
Labels: cla-signed

#6374 Update dnd_email_style_settings.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
Labels: cla-signed

#6422 Fix duplicate metric filter
  _docs/_user_guide/data_and_analytics/report_metrics.md
Labels: cla-signed

#6425 Spellcheck edits: ".txt" to text
  _docs/_partners/data_and_infrastructure_agility/ab_testing/phrasee/phrasee.md
Labels: cla-signed

#6429 Spellcheck edits: Lytics
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/lytics.md
Labels: cla-signed

#6426 Spellcheck edits: "CSM" to "customer success manager"
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
Labels: cla-signed

#6428 Spellcheck edits: "quieries" to "queries"
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/treasure_data/treasure_data.md
Labels: cla-signed

#6383 BD-2542: Olo Partner Documentation
  _docs/_hidden/wip_partnerships/partnership_template.md
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/olo.md
  _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
  _includes/create_transformation.md
Labels: cla-signed, Braze Partnerships
