Repository braze-inc/braze-docs, pull requests merged in 2023-01, with the labels that each got.

#4583 Jjm week 12 27 22
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization/setting_delegates.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/setting_delegates.md
  _docs/_partners/message_personalization/localization/transifex.md
  _docs/_user_guide/administrative.md
  _docs/_user_guide/onboarding_with_braze/integration.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
  assets/img_archive/Connected_Content_Syntax.png
  assets/img_archive/TransifexUI.png
  assets/img_archive/terminal.png
Labels: cla-signed

#4586 BD-1821: Update "in_local_time" behavior
  _docs/_api/objects_filters/schedule_object.md
Labels: cla-signed

#4587 Deploy - January 3, 2023
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_api/objects_filters/schedule_object.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization/setting_delegates.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/setting_delegates.md
  _docs/_docs_pages/index.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _docs/_partners/message_personalization/localization/transifex.md
  _docs/_user_guide/administrative.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _docs/_user_guide/engagement_tools/testing/random_bucket_numbers.md
  _docs/_user_guide/onboarding_with_braze/integration.md
  _docs/_user_guide/onboarding_with_braze/learning_to_use_braze.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
  _lang/fr/_docs_pages/index.md
  _layouts/doc_guide.html
  assets/img_archive/Connected_Content_Syntax.png
  assets/img_archive/TransifexUI.png
  assets/img_archive/dnd_global_style_settings.png
  assets/img_archive/segment_app_selection.png
  assets/img_archive/segment_step4.png
  assets/img_archive/terminal.png
Labels: cla-signed, Deploy

#4585 first pass of users merge documentation
  _docs/_api/api_limits.md
  _docs/_api/endpoints/user_data.md
  _docs/_api/endpoints/user_data/post_users_merge.md
  _docs/_api/home.md
  _includes/rate_limits.md
Labels: cla-signed

#4591 French Fix
  assets/img_archive/Connected_Content_Syntax.png
  assets/img_archive/TransifexUI.png
  assets/img_archive/terminal.png
Labels: cla-signed

#4593 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla-signed

#4582 Connected Content only supports GET
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
Labels: cla-signed

#4594 Minor rewording
  _docs/_user_guide/message_building_by_channel/email/inbox_vision.md
Labels: cla-signed

#4595 BD-1804: Remove home top text and update user guide top text
  _docs/_docs_pages/index.md
  _docs/_user_guide/introduction.md
Labels: cla-signed

#4599 Add location module information.
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
Labels: cla-signed

#4597 Data doc edits pt. 2
  _docs/_user_guide/data_and_analytics.md
  _docs/_user_guide/data_and_analytics/user_data_collection.md
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
  _docs/_user_guide/onboarding_with_braze/integration.md
  assets/img_archive/User_Search_Nonunique.png
  assets/img_archive/user_profile2.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#4603 BD-1825: Link Fix
  assets/js/broken_redirect_list.js
Labels: cla-signed

#4602 BD-1824: Update Appsflyer Datapoint
  _docs/_user_guide/onboarding_with_braze/data_points.md
Labels: cla-signed

#4601 Appboy -> Braze docs updates
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/custom_styling.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/default_feed.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization/message_dismissal.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/customization/click_listener.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/customization/custom_styling.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/baidu_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/huawei_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
Labels: cla-signed

#4596 Leftover Deploy - January 5, 2023
  .github/PULL_REQUEST_TEMPLATE.md
  _docs/_api/endpoints/user_data/post_users_merge.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/custom_styling.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/default_feed.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization/message_dismissal.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/customization/click_listener.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/customization/custom_styling.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/baidu_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/huawei_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_docs_pages/index.md
  _docs/_user_guide/data_and_analytics.md
  _docs/_user_guide/data_and_analytics/user_data_collection.md
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/data_and_analytics/your_reports.md
  _docs/_user_guide/data_and_analytics/your_reports/devices_and_carriers.md
  _docs/_user_guide/data_and_analytics/your_reports/global_control_group_reporting.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
  _docs/_user_guide/engagement_tools/testing/global_control_group.md
  _docs/_user_guide/introduction.md
  _docs/_user_guide/message_building_by_channel/email/inbox_vision.md
  _docs/_user_guide/message_building_by_channel/email/preference_center.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/preference_center.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/preference_center_via_api.md
  _docs/_user_guide/onboarding_with_braze/data_points.md
  _docs/_user_guide/onboarding_with_braze/integration.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
  assets/download_file/data-sharing-raw-table-schemas.txt
  assets/img/device_and_carriers.png
  assets/img_archive/User_Search_Nonunique.png
  assets/img_archive/user_profile2.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#4607 Add FF Swift code snippets
  _docs/_hidden/private_betas/creating_feature_flags.md
Labels: cla-signed

#4609 Update rudderstack.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack.md
Labels: cla-signed

#4608 Add 'state' to preference center API
  _docs/_api/endpoints/preference_center/post_create_preference_center.md
  _docs/_api/endpoints/preference_center/put_update_preference_center.md
Labels: cla-signed

#4611 fix: preference center docs
  _docs/_api/endpoints/preference_center/post_create_preference_center.md
  _docs/_user_guide/message_building_by_channel/email/preference_center.md
Labels: cla-signed

#4610 Jjm 1 6 23
  _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  assets/img_archive/reachable_users.png
Labels: cla-signed

#4613 Add french language dropdown
  _includes/header.html
  _includes/html_include.html
  assets/js/documents.js
Labels: cla-signed

#4612 Shopify Historical Backfill - Beta
  _docs/_hidden/private_betas/shopify_backfil.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/change_your_campaign_after_launch.md
  assets/img/Shopify/backfill1.jpg
  assets/img/Shopify/backfill2.png
  assets/img/Shopify/backfill3.png
Labels: cla-signed

#4617 BD-1822: Clarify email preference center details
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/preference_center.md
Labels: cla-signed

#4616 Currents updates - 1/10
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _docs/_partners/isv_partners/currents_integration.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
Labels: cla-signed

#4621 Add comment regarding image ownership
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
Labels: cla-signed

#4622 Update conversions_dashboard.md
  _docs/_user_guide/data_and_analytics/your_analytics_dashboards/conversions_dashboard.md
Labels: cla-signed

#4619 January 2023 release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023.md
  _docs/_help/release_notes/2023/1_10_23.md
Labels: cla-signed

#4623 BD-1833: Edit for preference center tile
  _docs/_user_guide/message_building_by_channel/email/preference_center.md
Labels: cla-signed

#4624 Update data_points.md
  _docs/_user_guide/onboarding_with_braze/data_points.md
Labels: cla-signed

#4625 BD-1831: Include session data for merge behavior
  _docs/_hidden/private_betas/post_user_identify_merge_behavior.md
Labels: cla-signed

#4626 Deploy - January 10, 2023
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  _docs/_api/endpoints/preference_center/post_create_preference_center.md
  _docs/_api/endpoints/preference_center/put_update_preference_center.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_api/objects_filters/user_attributes_object.md
  _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023.md
  _docs/_help/release_notes/2023/1_10_23.md
  _docs/_hidden/private_betas/canvas_drafts.md
  _docs/_hidden/private_betas/post_user_identify_merge_behavior.md
  _docs/_hidden/private_betas/shopify_backfil.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _docs/_partners/isv_partners/currents_integration.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/your_analytics_dashboards/conversions_dashboard.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/change_your_campaign_after_launch.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/email/preference_center.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/preference_center.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
  _docs/_user_guide/onboarding_with_braze/data_points.md
  _includes/header.html
  _includes/html_include.html
  _includes/search_page.html
  assets/css/securitiai.css
  assets/img/Shopify/backfill1.jpg
  assets/img/Shopify/backfill2.png
  assets/img/Shopify/backfill3.png
  assets/img_archive/canvas_draft1.png
  assets/img_archive/reachable_users.png
  assets/js/documents.js
Labels: cla-signed, Deploy

#4629 BD-1832: Expand on Braze Reader Accounts
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
Labels: cla-signed

#4630 Fix language selector with home page
  assets/js/documents.js
Labels: cla-signed

#4605 Increase segment extension limit
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
Labels: cla-signed

#4631 Deploy Pt. 2 - January 11, 2023
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  assets/js/documents.js
Labels: Deploy

#4638 BD-1837: Minor edit
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
Labels: cla-signed

#4636 Reporting minor cleanup
  _docs/_user_guide/data_and_analytics/braze_currents/how_braze_uses_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/s3_to_snowflake.md
  _docs/_user_guide/data_and_analytics/creating_a_formula.md
  _docs/_user_guide/data_and_analytics/tracking/email_tracking.md
  _docs/_user_guide/data_and_analytics/tracking/segment_analytics_tracking.md
  _docs/_user_guide/data_and_analytics/your_analytics_dashboards.md
Labels: cla-signed

#4640 delete accidental duplicate: "out out"
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
Labels: cla-signed

#4634 Redshift Cloud Data Ingestion Updates - EA
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion.md
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/overview.md
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/redshift.md
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/snowflake.md
  assets/img/cloud_ingestion/ingestion_1.png
  assets/img/cloud_ingestion/ingestion_2.png
Labels: cla-signed

#4641 Update intel select with re-eligiblity docs
  _docs/_user_guide/intelligence/faqs.md
  _docs/_user_guide/intelligence/intelligent_selection.md
Labels: cla-signed

#4632 Change paid prediction limit from 3 to 5
  _docs/_user_guide/predictive_suite/predictive_churn/creating_a_churn_prediction.md
  _docs/_user_guide/predictive_suite/predictive_purchases/creating_a_purchase_prediction.md
Labels: cla-signed

#4642 Leftover Deploy - January 12, 2023
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
  _docs/_user_guide/data_and_analytics/braze_currents/how_braze_uses_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/s3_to_snowflake.md
  _docs/_user_guide/data_and_analytics/creating_a_formula.md
  _docs/_user_guide/data_and_analytics/tracking/email_tracking.md
  _docs/_user_guide/data_and_analytics/tracking/segment_analytics_tracking.md
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion.md
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/overview.md
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/redshift.md
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/snowflake.md
  _docs/_user_guide/data_and_analytics/your_analytics_dashboards.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
  _docs/_user_guide/intelligence/faqs.md
  _docs/_user_guide/intelligence/intelligent_selection.md
  _docs/_user_guide/predictive_suite/predictive_churn/creating_a_churn_prediction.md
  _docs/_user_guide/predictive_suite/predictive_purchases/creating_a_purchase_prediction.md
  assets/img/cloud_ingestion/ingestion_1.png
  assets/img/cloud_ingestion/ingestion_2.png
Labels: cla-signed, Deploy

#4627 EA user level click tracking for shortened SMS links
  _docs/_hidden/private_betas/link_shortening.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
Labels: cla-signed

#4646 Punchh Updates
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/code_generation.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/punchh.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/voucherify.md
  assets/img/punchh/punchh7.png
  assets/img/punchh/punchh8.png
  assets/img/punchh/punchh9.png
Labels: cla-signed

#4637 BD-1835: Clarify Apple Private Relay details
  _docs/_user_guide/message_building_by_channel/email/email_private_relay_apple_SSO.md
Labels: cla-signed

#4635 GlobalLink Translation PR
  _lang/fr/_home/dp-technical-assistance.md
  _lang/fr/_home/metadata.md
  _lang/fr/_home/static_video.md
  _lang/fr/_home/styling_test_page.md
  _lang/fr/_home/templates.md
  _lang/fr/_home/templates/get_endpoint.md
  _lang/fr/_home/templates/post_endpoint.md
  _lang/fr/_home/templates_old/api_glossary.md
  _lang/fr/_home/templates_old/glossary_test_page.md
  _lang/fr/_home/templates_old/help_article_template.md
  _lang/fr/_home/templates_old/landing_images.md
  _lang/fr/_home/templates_old/landing_multiple.md
  _lang/fr/_home/templates_old/landing_multiple_images.md
  _lang/fr/_home/templates_old/landing_single.md
  _lang/fr/_home/templates_old/partner_page_template.md
  _lang/fr/_home/templates_old/partner_page_template_video.md
  _lang/fr/_home/templates_old/reference.md
  _lang/fr/_home/templates_old/reference_video.md
  _lang/fr/_home/templates_old/solution.md
  _lang/fr/_home/templates_old/tutorial.md
  _lang/fr/_home/templates_old/tutorial_video.md
  _lang/fr/_home/templates_old/use_case.md
  _lang/fr/_home/templates_old/use_case_video.md
Labels: cla-signed

#4652 Fix developer guide platform navigation for multi language
  assets/js/developer_nav.js
Labels: cla-signed

#4654 BD-1849: Fix mention of selections
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
Labels: cla-signed

#4649 Data doc edits pt. 3
  _docs/_api/data_retention.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/onboarding_with_braze/data_points.md
Labels: cla-signed

#4643 SQL Segment Extensions EA [MERGE 1/17]
  _docs/_hidden/private_betas/sql_segments.md
  assets/img_archive/sql_segments_create.png
  assets/img_archive/sql_segments_editor.png
  assets/img_archive/sql_segments_usage.png
Labels: cla-signed

#4648 Building accessible messages
  _docs/_help/accessibility.md
Labels: cla-signed, release notes

#4656 Clarify save as drafts for Canvas
  _docs/_hidden/private_betas/canvas_drafts.md
Labels: cla-signed

#4658 Proposed style change
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/user_phone_numbers.md
Labels: cla-signed

#4659 Adding trigger event type
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md
Labels: cla-signed

#4664 Update canvas_api_id field definition in Currents exit events
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#4657 BD-1850: Clarify cohort_changes for user cohort endpoint
  _docs/_partners/isv_partners/cohort_import.md
Labels: cla-signed

#4644 Minor WhatsApp updates to reflect new sign-up UI
  _docs/_user_guide/message_building_by_channel/whatsapp/create.md
  _docs/_user_guide/message_building_by_channel/whatsapp/overview.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
Labels: cla-signed

#4606 Add documentation for Braze Swift SDK setup
  _data/alerts.yml
  _docs/_developer_guide/home.md
  _docs/_developer_guide/platform_integration_guides/android.md
  _docs/_developer_guide/platform_integration_guides/cordova.md
  _docs/_developer_guide/platform_integration_guides/flutter.md
  _docs/_developer_guide/platform_integration_guides/ios.md
  _docs/_developer_guide/platform_integration_guides/ios/changelog.md
  _docs/_developer_guide/platform_integration_guides/ios/changelog/objc_changelog.md
  _docs/_developer_guide/platform_integration_guides/ios/changelog/swift_changelog.md
  _docs/_developer_guide/platform_integration_guides/macOS.md
  _docs/_developer_guide/platform_integration_guides/react_native.md
  _docs/_developer_guide/platform_integration_guides/roku.md
  _docs/_developer_guide/platform_integration_guides/sdk_changelogs.md
  _docs/_developer_guide/platform_integration_guides/swift.md
  _docs/_developer_guide/platform_integration_guides/swift/changelog.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/completing_integration.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/installation_methods.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/installation_methods/carthage_integration.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/installation_methods/cocoapods.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/installation_methods/manual_integration_options.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/installation_methods/swift_package_manager.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/ios_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/other_sdk_customizations.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/overview.md
  _docs/_developer_guide/platform_integration_guides/tvos.md
  _docs/_developer_guide/platform_integration_guides/unity.md
  _docs/_developer_guide/platform_integration_guides/unreal_engine.md
  _docs/_developer_guide/platform_integration_guides/web.md
  _docs/_developer_guide/platform_integration_guides/windows_universal.md
  _docs/_developer_guide/platform_integration_guides/xamarin.md
  _includes/archive/ios-swift-upgrade.md
  assets/css/_alerts.scss
  assets/css/_lang_override.scss
  assets/img/swift/cocoapods/braze_example_workspace.png
  assets/img/swift/interruption-level.png
  assets/img/swift/ios14-approximate-location.png
  assets/img/swift/ios14-idfa.png
  assets/img/swift/ios15-notification-settings.png
  assets/img/swift/ios15-notification-summary.png
  assets/img/swift/push_story/abkstoriesview_class.png
  assets/img/swift/push_story/abkstoriesview_outlet.png
  assets/img/swift/push_story/abkstoriesview_size.png
  assets/img/swift/push_story/add_app_groups.png
  assets/img/swift/push_story/add_content_extension.png
  assets/img/swift/push_story/enable_background_mode.png
  assets/img/swift/push_story/manual1.png
  assets/img/swift/push_story/notificationcontentextension_plist.png
  assets/img/swift/push_story/spm1.png
  assets/img/swift/push_story/spm2.png
  assets/img/swift/relevance-score.png
  assets/img/swift/spm/add_package.png
  assets/img/swift/spm/importsdk_example.png
  assets/img/swift/spm/swiftpackages.png
Labels: cla-signed

#4667 Update Rack version 2.2.6.2
  Gemfile.lock
Labels: cla-signed

#4671 BD-1856: Add quotation mark for POST example
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
Labels: cla-signed

#4645 Query Builder EA [MERGE 1/19]
  _docs/_user_guide/data_and_analytics.md
  _docs/_user_guide/data_and_analytics/query_builder.md
  assets/img_archive/query_builder.png
  assets/img_archive/query_builder_q1.png
  assets/img_archive/query_builder_q2.png
  assets/img_archive/query_builder_q3.png
  assets/img_archive/query_builder_q4.png
  assets/img_archive/query_builder_q5.png
  assets/img_archive/query_builder_q6.png
  assets/img_archive/query_builder_q7.png
Labels: cla-signed

#4677 Update data_retention.md
  _docs/_api/data_retention.md
Labels: cla-signed

#4676 BD-1852: Clarify Has App filter
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#4678 BD-1858: Fix request example
  _docs/_api/endpoints/preference_center/put_update_preference_center.md
Labels: cla-signed

#4647 BD-1843: Add note regarding event removal
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
Labels: cla-signed

#4686 Update 1_10_23.md
  _docs/_help/release_notes/2023/1_10_23.md
Labels: cla-signed

#4687 Data doc edits pt. 4
  _docs/_api/data_retention.md
Labels: cla-signed

#4693 Audit docs for negative language
  _docs/_api/api_limits.md
  _docs/_api/endpoints/export/user_data/post_users_global_control_group.md
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
  _docs/_help/help_articles/data/dispatch_id.md
  _docs/_help/help_articles/push/no_push_notification_was_received.md
  _docs/_help/release_notes.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/analytics/looker.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/voucherify/voucherify_fetching_data_through_braze_connected_content.md
  _docs/_partners/message_personalization/dynamic_content/sheetlabs.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/branching.md
  _docs/_user_guide/message_building_by_channel/sms/faqs.md
  _docs/_user_guide/onboarding_with_braze/data_points.md
  _docs/_user_guide/onboarding_with_braze/sms_setup/sms_sending.md
  _docs/_user_guide/onboarding_with_braze/subscription_and_usage.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
Labels: cla-signed

#4694 Massaged references to the SDK
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/soft_push_prompt.md
  _docs/_developer_guide/platform_wide/app_group_configuration.md
  _docs/_user_guide/administrative/app_settings/developer_console/internal_groups_tab.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/localizing_a_campaign.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/best_practices/previous_in-app_message_generations.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize/email_capture_form.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize/html_in-app_messages.md
Labels: cla-signed

#4692 BD-1860: Update rate limit for User Update step
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
  assets/img_archive/canvas_user_update_composer.png
  assets/img_archive/canvas_user_update_example.png
  assets/img_archive/canvas_user_update_remove.png
  assets/img_archive/canvas_user_update_test_preview.png
  assets/img_archive/canvas_user_update_update.png
Labels: cla-signed

#4697 BD-1813_1864
  _docs/_user_guide/data_and_analytics/your_reports/funnel_reports.md
Labels: cla-signed

#4698 Revert "Add comment regarding image ownership"
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
Labels: cla-signed

#4701 Update shopify_data_in_braze.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_in_braze.md
Labels: cla-signed

#4703 Update treasure_data.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/treasure_data.md
Labels: cla-signed

#4704 BD-1866: Fix link
  _docs/_partners/message_personalization/location/radar.md
Labels: cla-signed

#4700 Minor Overview Updates - User Guide
  _docs/_user_guide/administrative/app_settings/developer_console.md
  _docs/_user_guide/administrative/app_settings/developer_console/event_user_log_tab.md
  _docs/_user_guide/administrative/app_settings/developer_console/internal_groups_tab.md
  _docs/_user_guide/administrative/app_settings/manage_app_group.md
  _docs/_user_guide/data_and_analytics/export_braze_data.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_campaign_results_data.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_canvas_data.md
  _docs/_user_guide/data_and_analytics/tracking.md
  _docs/_user_guide/engagement_tools/campaigns.md
  _docs/_user_guide/engagement_tools/campaigns/getting_started.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more.md
  _docs/_user_guide/engagement_tools/canvas.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
  _docs/_user_guide/engagement_tools/locations_and_geofences.md
  _docs/_user_guide/engagement_tools/news_feed.md
  _docs/_user_guide/engagement_tools/news_feed/best_practices.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing.md
  _docs/_user_guide/message_building_by_channel/content_cards.md
  _docs/_user_guide/message_building_by_channel/content_cards/best_practices.md
  _docs/_user_guide/message_building_by_channel/email/best_practices.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop.md
  _docs/_user_guide/message_building_by_channel/email/templates.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/best_practices.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/best_practices/previous_in-app_message_generations.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop.md
  _docs/_user_guide/message_building_by_channel/push.md
  _docs/_user_guide/message_building_by_channel/push/advanced_push_options.md
  _docs/_user_guide/message_building_by_channel/push/android.md
  _docs/_user_guide/message_building_by_channel/push/android/advanced_campaign_settings.md
  _docs/_user_guide/message_building_by_channel/push/best_practices.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/additional_android_best_practices.md
  _docs/_user_guide/message_building_by_channel/push/ios.md
  _docs/_user_guide/message_building_by_channel/sms.md
  _docs/_user_guide/message_building_by_channel/sms/best_practices.md
  _docs/_user_guide/message_building_by_channel/sms/keywords.md
  _docs/_user_guide/message_building_by_channel/sms/non_native.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs.md
Labels: cla-signed

#4663 Update Segment links
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
Labels: cla-signed

#4639 Update GTM docs
  _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/google_tag_manager.md
Labels: cla-signed

#4665 FF layout
  _docs/_developer_guide/platform_wide/feature_flags.md
  _docs/_developer_guide/platform_wide/feature_flags/about.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
  _docs/_developer_guide/platform_wide/feature_flags/use_cases.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
  assets/img/feature_flags/feature-flags-create.png
  assets/img/feature_flags/feature-flags-list.png
  assets/img/feature_flags/feature-flags-rollout.gif
  assets/img/feature_flags/feature-flags-rollout.png
  assets/img/feature_flags/feature-flags-targeting.png
  assets/img/feature_flags/feature-flags-use-case-canvas-experiment-step.png
  assets/img/feature_flags/feature-flags-use-case-canvas-flow.png
  assets/img/feature_flags/feature-flags-use-case-livechat-1.png
  assets/img/feature_flags/feature-flags-use-case-loyalty.png
  assets/img/feature_flags/feature-flags-use-case-navigation-link-1.png
  assets/img/feature_flags/feature-flags-use-case-navigation-link-2.png
Labels: cla-signed

#4588 Pre and post-launch checklist for Canvas
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/pre_post_launch_checklist.md
  assets/img_archive/canvas_checklist1.png
Labels: cla-signed

#4705 Explanation and image
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/winning_path.md
  assets/img/experiment_step/experiment_onetime_workaround.png
Labels: cla-signed

#4708 Add section article tile
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies.md
Labels: cla-signed

#4706 Liquid use case german to english
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
Labels: cla-signed

#4709 Update get_started.md
  _docs/_user_guide/engagement_tools/canvas/get_started.md
Labels: cla-signed

#4710 Remove Treasure data hosted video
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/treasure_data.md
Labels: cla-signed

#4711 Minor backlog tickets
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
Labels: cla-signed

#4712 BD-1867: Add section about merge_updates behavior
  _docs/_api/endpoints/user_data/post_users_merge.md
Labels: cla-signed

#4714 Update shopify.md to replace Spotify typo
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify.md
Labels: cla-signed

#4675 expo 47 and react native updates
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Labels: cla-signed

#4319 Feature Flags Beta
  _docs/_developer_guide/platform_wide/feature_flags.md
  _docs/_developer_guide/platform_wide/feature_flags/about.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
  _docs/_developer_guide/platform_wide/feature_flags/use_cases.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
  assets/img/feature_flags/feature-flags-create.png
  assets/img/feature_flags/feature-flags-list.png
  assets/img/feature_flags/feature-flags-rollout.gif
  assets/img/feature_flags/feature-flags-rollout.png
  assets/img/feature_flags/feature-flags-targeting.png
  assets/img/feature_flags/feature-flags-use-case-canvas-experiment-step.png
  assets/img/feature_flags/feature-flags-use-case-canvas-flow.png
  assets/img/feature_flags/feature-flags-use-case-livechat-1.png
  assets/img/feature_flags/feature-flags-use-case-loyalty.png
  assets/img/feature_flags/feature-flags-use-case-navigation-link-1.png
  assets/img/feature_flags/feature-flags-use-case-navigation-link-2.png
Labels: cla-signed

#4716 WhatsApp FAQ
  _docs/_user_guide/message_building_by_channel/whatsapp/faqs.md
Labels: cla-signed

#4717 Airbridge updates
  _docs/_partners/message_orchestration/attribution/airbridge.md
  assets/img/airbridge/airbridge_integration_step_1.png
  assets/img/airbridge/airbridge_integration_step_2.png
Labels: cla-signed

#4719 Specify Subscription Group Type
  _docs/_user_guide/message_building_by_channel/email/preference_center/preference_center.md
Labels: cla-signed

#4718 Update preference_center_via_api.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/preference_center_via_api.md
Labels: cla-signed

#4720 Fix invalid yaml for FR
  _lang/fr/_developer_guide/platform_integration_guides/cordova/content_cards.md
  _lang/fr/_developer_guide/platform_integration_guides/ios/content_cards.md
  _lang/fr/_developer_guide/platform_integration_guides/web/content_cards.md
Labels: cla-signed

#4653 BD-1847: Update Canvas details endpoint fields
  _docs/_api/endpoints/export/canvas/get_canvas_details.md
Labels: cla-signed

#4679 GlobalLink Translation PR
  _lang/fr/_api/api_campaigns.md
  _lang/fr/_api/api_limits.md
  _lang/fr/_api/basics.md
  _lang/fr/_api/endpoints.md
  _lang/fr/_api/endpoints/catalogs.md
  _lang/fr/_api/endpoints/catalogs/catalog_items.md
  _lang/fr/_api/endpoints/catalogs/catalog_items/asynchronous.md
  _lang/fr/_api/endpoints/catalogs/catalog_items/asynchronous/delete_catalog_items_bulk.md
  _lang/fr/_api/endpoints/catalogs/catalog_items/asynchronous/patch_catalog_items_bulk.md
  _lang/fr/_api/endpoints/catalogs/catalog_items/asynchronous/post_create_catalog_items_bulk.md
  _lang/fr/_api/endpoints/catalogs/catalog_items/synchronous.md
  _lang/fr/_api/endpoints/catalogs/catalog_items/synchronous/delete_catalog_item.md
  _lang/fr/_api/endpoints/catalogs/catalog_items/synchronous/get_catalog_item_details.md
  _lang/fr/_api/endpoints/catalogs/catalog_items/synchronous/get_catalog_items_details_bulk.md
  _lang/fr/_api/endpoints/catalogs/catalog_items/synchronous/patch_catalog_item.md
  _lang/fr/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md
  _lang/fr/_api/endpoints/catalogs/catalog_management.md
  _lang/fr/_api/endpoints/catalogs/catalog_management/synchronous.md
  _lang/fr/_api/endpoints/catalogs/catalog_management/synchronous/delete_catalog.md
  _lang/fr/_api/endpoints/catalogs/catalog_management/synchronous/get_list_catalogs.md
  _lang/fr/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md
  _lang/fr/_api/endpoints/email.md
  _lang/fr/_api/endpoints/email/get_list_hard_bounces.md
  _lang/fr/_api/endpoints/email/get_query_unsubscribed_email_addresses.md
  _lang/fr/_api/endpoints/email/post_blacklist.md
  _lang/fr/_api/endpoints/email/post_blocklist.md
  _lang/fr/_api/endpoints/email/post_email_subscription_status.md
  _lang/fr/_api/endpoints/email/post_remove_hard_bounces.md
  _lang/fr/_api/endpoints/email/post_remove_spam.md
  _lang/fr/_api/endpoints/export.md
  _lang/fr/_api/endpoints/export/campaigns/get_campaign_analytics.md
  _lang/fr/_api/endpoints/export/campaigns/get_campaign_details.md
  _lang/fr/_api/endpoints/export/campaigns/get_campaigns.md
  _lang/fr/_api/endpoints/export/campaigns/get_send_analytics.md
  _lang/fr/_api/endpoints/export/canvas/get_canvas_analytics.md
  _lang/fr/_api/endpoints/export/canvas/get_canvas_analytics_summary.md
  _lang/fr/_api/endpoints/export/canvas/get_canvas_details.md
Labels: cla-signed

#4681 GlobalLink Translation PR
  _lang/fr/_hidden/private_betas/get_canvas_url_info.md
  _lang/fr/_hidden/private_betas/link_shortening.md
  _lang/fr/_hidden/private_betas/post_user_identify_merge_behavior.md
  _lang/fr/_hidden/private_betas/tiktok.md
  _lang/fr/_hidden/wip_partnerships/WIP_guidelines.md
  _lang/fr/_hidden/wip_partnerships/partnership_template.md
  _lang/fr/_home/metadata.md
  _lang/fr/_home/static_video.md
  _lang/fr/_home/styling_test_page.md
  _lang/fr/_home/templates/get_endpoint.md
  _lang/fr/_home/templates/post_endpoint.md
  _lang/fr/_home/templates_old/api_glossary.md
  _lang/fr/_home/templates_old/glossary_test_page.md
  _lang/fr/_home/templates_old/help_article_template.md
  _lang/fr/_home/templates_old/landing_images.md
  _lang/fr/_home/templates_old/landing_multiple.md
  _lang/fr/_home/templates_old/landing_multiple_images.md
  _lang/fr/_home/templates_old/landing_single.md
  _lang/fr/_home/templates_old/partner_page_template.md
  _lang/fr/_home/templates_old/partner_page_template_video.md
  _lang/fr/_home/templates_old/reference.md
  _lang/fr/_home/templates_old/reference_video.md
  _lang/fr/_home/templates_old/solution.md
  _lang/fr/_home/templates_old/tutorial.md
Labels: cla-signed

#4683 GlobalLink Translation PR
  _lang/fr/_api/endpoints/user_data/post_user_identify.md
  _lang/fr/_api/endpoints/user_data/post_user_track.md
  _lang/fr/_api/errors.md
  _lang/fr/_api/home.md
  _lang/fr/_api/identifier_types.md
  _lang/fr/_api/network_connectivity_issues.md
  _lang/fr/_api/objects_filters/aliases_to_identify.md
  _lang/fr/_api/objects_filters/canvas_entry_properties_object.md
  _lang/fr/_api/objects_filters/connected_audience.md
  _lang/fr/_api/objects_filters/event_object.md
  _lang/fr/_api/objects_filters/messaging/android_object.md
  _lang/fr/_api/objects_filters/messaging/apple_object.md
  _lang/fr/_api/objects_filters/messaging/content_cards_object.md
  _lang/fr/_api/objects_filters/messaging/email_object.md
  _lang/fr/_api/objects_filters/messaging/kindle_and_fireos_object.md
  _lang/fr/_api/objects_filters/messaging/sms_object.md
  _lang/fr/_api/objects_filters/messaging/web_objects.md
  _lang/fr/_api/objects_filters/messaging/webhook_object.md
  _lang/fr/_api/objects_filters/messaging/windows_objects.md
  _lang/fr/_api/objects_filters/purchase_object.md
  _lang/fr/_api/objects_filters/recipient_object.md
  _lang/fr/_api/objects_filters/schedule_object.md
  _lang/fr/_api/objects_filters/trigger_properties_object.md
  _lang/fr/_api/objects_filters/user_alias_object.md
  _lang/fr/_api/objects_filters/user_attributes_object.md
  _lang/fr/_api/parameters.md
  _lang/fr/_api/postman_collection.md
  _lang/fr/_developer_guide/disclosures/innovation_statement.md
  _lang/fr/_developer_guide/disclosures/open_source_software_disclosure.md
  _lang/fr/_developer_guide/disclosures/security_and_vulnerability_disclosure.md
  _lang/fr/_developer_guide/disclosures/security_qualifications.md
Labels: cla-signed

#4684 GlobalLink Translation PR
  _lang/fr/_api/endpoints/export/canvas/get_canvases.md
  _lang/fr/_api/endpoints/export/custom_events/get_custom_events.md
  _lang/fr/_api/endpoints/export/custom_events/get_custom_events_analytics.md
  _lang/fr/_api/endpoints/export/kpi/get_kpi_daily_new_users_date.md
  _lang/fr/_api/endpoints/export/kpi/get_kpi_dau_date.md
  _lang/fr/_api/endpoints/export/kpi/get_kpi_mau_30_days.md
  _lang/fr/_api/endpoints/export/kpi/get_kpi_uninstalls_date.md
  _lang/fr/_api/endpoints/export/news_feed/get_news_feed_card_analytics.md
  _lang/fr/_api/endpoints/export/news_feed/get_news_feed_card_details.md
  _lang/fr/_api/endpoints/export/news_feed/get_news_feed_cards.md
  _lang/fr/_api/endpoints/export/purchases/get_list_product_id.md
  _lang/fr/_api/endpoints/export/segments/get_segment.md
  _lang/fr/_api/endpoints/export/segments/get_segment_analytics.md
  _lang/fr/_api/endpoints/export/segments/get_segment_details.md
  _lang/fr/_api/endpoints/export/sessions/get_sessions_analytics.md
  _lang/fr/_api/endpoints/export/user_data/post_users_global_control_group.md
  _lang/fr/_api/endpoints/export/user_data/post_users_identifier.md
  _lang/fr/_api/endpoints/export/user_data/post_users_segment.md
  _lang/fr/_api/endpoints/messaging.md
  _lang/fr/_api/endpoints/messaging/schedule_messages/get_messages_scheduled.md
  _lang/fr/_api/endpoints/messaging/schedule_messages/post_delete_scheduled_messages.md
  _lang/fr/_api/endpoints/messaging/schedule_messages/post_delete_scheduled_triggered_canvases.md
  _lang/fr/_api/endpoints/messaging/schedule_messages/post_delete_scheduled_triggered_messages.md
  _lang/fr/_api/endpoints/messaging/schedule_messages/post_schedule_messages.md
  _lang/fr/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_campaigns.md
  _lang/fr/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_canvases.md
  _lang/fr/_api/endpoints/messaging/schedule_messages/post_update_scheduled_messages.md
  _lang/fr/_api/endpoints/messaging/schedule_messages/post_update_scheduled_triggered_campaigns.md
  _lang/fr/_api/endpoints/messaging/schedule_messages/post_update_scheduled_triggered_canvases.md
  _lang/fr/_api/endpoints/messaging/send_messages/post_create_send_ids.md
  _lang/fr/_api/endpoints/messaging/send_messages/post_send_messages.md
Labels: cla-signed

#4685 GlobalLink Translation PR
  _lang/fr/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  _lang/fr/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
  _lang/fr/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
  _lang/fr/_api/endpoints/preference_center.md
  _lang/fr/_api/endpoints/preference_center/get_create_url_preference_center.md
  _lang/fr/_api/endpoints/preference_center/get_list_preference_center.md
  _lang/fr/_api/endpoints/preference_center/get_view_details_preference_center.md
  _lang/fr/_api/endpoints/preference_center/post_create_preference_center.md
  _lang/fr/_api/endpoints/preference_center/put_update_preference_center.md
  _lang/fr/_api/endpoints/scim.md
  _lang/fr/_api/endpoints/scim/delete_existing_dashboard_user.md
  _lang/fr/_api/endpoints/scim/get_search_existing_dashboard_user.md
  _lang/fr/_api/endpoints/scim/get_see_user_account_information.md
  _lang/fr/_api/endpoints/scim/post_create_user_account.md
  _lang/fr/_api/endpoints/scim/put_update_existing_user_account.md
  _lang/fr/_api/endpoints/sms.md
  _lang/fr/_api/endpoints/sms/get_query_invalid_numbers.md
  _lang/fr/_api/endpoints/sms/post_remove_invalid_numbers.md
  _lang/fr/_api/endpoints/subscription_groups.md
  _lang/fr/_api/endpoints/subscription_groups/get_list_user_subscription_group_status.md
  _lang/fr/_api/endpoints/subscription_groups/get_list_user_subscription_groups.md
  _lang/fr/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
  _lang/fr/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
  _lang/fr/_api/endpoints/templates.md
  _lang/fr/_api/endpoints/templates/content_blocks_templates/get_list_email_content_blocks.md
  _lang/fr/_api/endpoints/templates/content_blocks_templates/get_see_email_content_blocks_information.md
  _lang/fr/_api/endpoints/templates/content_blocks_templates/post_create_email_content_block.md
  _lang/fr/_api/endpoints/templates/content_blocks_templates/post_update_content_block.md
  _lang/fr/_api/endpoints/templates/email_templates/get_list_email_templates.md
  _lang/fr/_api/endpoints/templates/email_templates/get_see_email_template_information.md
  _lang/fr/_api/endpoints/templates/email_templates/post_create_email_template.md
  _lang/fr/_api/endpoints/templates/email_templates/post_update_email_template.md
  _lang/fr/_api/endpoints/user_data.md
  _lang/fr/_api/endpoints/user_data/external_id_migration.md
  _lang/fr/_api/endpoints/user_data/external_id_migration/post_external_ids_remove.md
  _lang/fr/_api/endpoints/user_data/external_id_migration/post_external_ids_rename.md
  _lang/fr/_api/endpoints/user_data/post_user_alias.md
  _lang/fr/_api/endpoints/user_data/post_user_delete.md
Labels: cla-signed

#4680 GlobalLink Translation PR
  _lang/fr/_partners/data_and_infrastructure_agility/workflow_automation/census.md
  _lang/fr/_partners/data_and_infrastructure_agility/workflow_automation/fivetran.md
  _lang/fr/_partners/data_and_infrastructure_agility/workflow_automation/hightouch.md
  _lang/fr/_partners/data_and_infrastructure_agility/workflow_automation/nexla.md
  _lang/fr/_partners/data_and_infrastructure_agility/workflow_automation/zapier.md
  _lang/fr/_partners/home.md
  _lang/fr/_partners/isv_partners/api_partner.md
  _lang/fr/_partners/isv_partners/cohort_import.md
  _lang/fr/_partners/isv_partners/currents_integration.md
  _lang/fr/_partners/message_orchestration/additional_channels/calendar/rokt_calendar.md
  _lang/fr/_partners/message_orchestration/additional_channels/direct_mail/inkit.md
  _lang/fr/_partners/message_orchestration/additional_channels/direct_mail/lob.md
  _lang/fr/_partners/message_orchestration/additional_channels/direct_mail/optilyz.md
  _lang/fr/_partners/message_orchestration/additional_channels/messaging/line.md
  _lang/fr/_partners/message_orchestration/additional_channels/messaging/messenger.md
  _lang/fr/_partners/message_orchestration/additional_channels/mobile_wallet/passkit.md
  _lang/fr/_partners/message_orchestration/additional_channels/retargeting/facebook.md
  _lang/fr/_partners/message_orchestration/additional_channels/retargeting/jampp.md
  _lang/fr/_partners/message_orchestration/additional_channels/retargeting/quikly.md
  _lang/fr/_partners/message_orchestration/additional_channels/retargeting/remerge.md
  _lang/fr/_partners/message_orchestration/attribution/adjust.md
  _lang/fr/_partners/message_orchestration/attribution/airbridge.md
  _lang/fr/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _lang/fr/_partners/message_orchestration/attribution/appsflyer/appsflyer_audiences.md
  _lang/fr/_partners/message_orchestration/attribution/branch/branch_for_attribution.md
  _lang/fr/_partners/message_orchestration/attribution/branch/branch_for_deeplinking.md
  _lang/fr/_partners/message_orchestration/attribution/kochava.md
  _lang/fr/_partners/message_orchestration/attribution/singular.md
Labels: cla-signed

#4713 BD-1862: Clarify use of email addresses/phone numbers as external IDs
  _includes/archive/setting_user_ids/best_practices.md
  _includes/archive/setting_user_ids/naming_convention.md
  _includes/archive/setting_user_ids/setting_user_ids.md
Labels: cla-signed

#4722 BD-1873: Clarify delivery validation for Canvas advancement
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/advancement.md
Labels: cla-signed

#4724 Tweaking Algolia
  _docs/_developer_guide/platform_integration_guides/android/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/integration.md
  _docs/_developer_guide/platform_integration_guides/cordova/initial_sdk_setup/android.md
  _docs/_developer_guide/platform_integration_guides/cordova/initial_sdk_setup/ios.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
  _docs/_user_guide/data_and_analytics/braze_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _docs/_user_guide/data_and_analytics/your_reports.md
  _docs/_user_guide/engagement_tools/campaigns.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/creating_campaign.md
  _docs/_user_guide/engagement_tools/canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/locations_and_geofences.md
  _docs/_user_guide/engagement_tools/segments.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _docs/_user_guide/engagement_tools/segments/segment_funnels.md
  _docs/_user_guide/engagement_tools/templates_and_media.md
  _docs/_user_guide/engagement_tools/testing/global_control_group.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing.md
  _docs/_user_guide/intelligence.md
  _docs/_user_guide/intelligence/intelligent_selection.md
  _docs/_user_guide/message_building_by_channel/content_cards.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/email.md
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
  _docs/_user_guide/message_building_by_channel/in-app_messages.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/sms.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/create.md
  _docs/_user_guide/message_building_by_channel/sms/mms/about_mms.md
  _docs/_user_guide/message_building_by_channel/sms/mms/create.md
  _docs/_user_guide/message_building_by_channel/webhooks.md
  _docs/_user_guide/onboarding_with_braze/data_points.md
  _docs/_user_guide/onboarding_with_braze/subscription_and_usage.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  _docs/_user_guide/predictive_suite.md
  _docs/_user_guide/predictive_suite/predictive_purchases.md
Labels: cla-signed

#4691 GlobalLink Translation PR
  _lang/fr/_partners/message_personalization/dynamic_content/amazon_personalize/amazon_personalize.md
  _lang/fr/_partners/message_personalization/dynamic_content/amazon_personalize/workshop.md
  _lang/fr/_partners/message_personalization/dynamic_content/certona.md
  _lang/fr/_partners/message_personalization/dynamic_content/dynamic_yield.md
  _lang/fr/_partners/message_personalization/dynamic_content/judo.md
  _lang/fr/_partners/message_personalization/dynamic_content/liftigniter.md
  _lang/fr/_partners/message_personalization/dynamic_content/movable_ink.md
  _lang/fr/_partners/message_personalization/dynamic_content/peak.md
  _lang/fr/_partners/message_personalization/dynamic_content/sheetlabs.md
  _lang/fr/_partners/message_personalization/dynamic_content/wsc_sports.md
  _lang/fr/_partners/message_personalization/dynamic_content/wyng.md
  _lang/fr/_partners/message_personalization/localization/crowdin.md
  _lang/fr/_partners/message_personalization/localization/lokalise.md
  _lang/fr/_partners/message_personalization/localization/transifex.md
  _lang/fr/_partners/message_personalization/location/accuweather.md
  _lang/fr/_partners/message_personalization/location/bluedot.md
  _lang/fr/_partners/message_personalization/location/foursquare.md
  _lang/fr/_partners/message_personalization/location/gimbal.md
  _lang/fr/_partners/message_personalization/location/radar.md
  _lang/fr/_partners/third_party_liability.md
  _lang/fr/_user_guide/administrative.md
  _lang/fr/_user_guide/administrative/access_braze/braze_instances.md
  _lang/fr/_user_guide/administrative/access_braze/portal.md
  _lang/fr/_user_guide/administrative/access_braze/product_request_example.md
  _lang/fr/_user_guide/administrative/access_braze/resetting_your_password.md
  _lang/fr/_user_guide/administrative/access_braze/sdk_endpoints.md
  _lang/fr/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
  _lang/fr/_user_guide/administrative/access_braze/single_sign_on/okta.md
  _lang/fr/_user_guide/administrative/access_braze/single_sign_on/onelogin.md
  _lang/fr/_user_guide/administrative/access_braze/single_sign_on/set_up.md
Labels: cla-signed

#4690 GlobalLink Translation PR
  _lang/fr/_partners/data_and_infrastructure_agility/cohort_import/tinyclues.md
  _lang/fr/_partners/data_and_infrastructure_agility/crash_analytics.md
  _lang/fr/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _lang/fr/_partners/data_and_infrastructure_agility/customer_data_platform/octolis.md
  _lang/fr/_partners/data_and_infrastructure_agility/data_privacy.md
  _lang/fr/_partners/data_and_infrastructure_agility/data_warehouses.md
  _lang/fr/_partners/data_and_infrastructure_agility/data_warehouses/snowflake/sample_queries.md
  _lang/fr/_partners/data_and_infrastructure_agility/payments.md
  _lang/fr/_partners/data_and_infrastructure_agility/support.md
  _lang/fr/_partners/data_and_infrastructure_agility/workflow_automation.md
Labels: cla-signed

#4688 GlobalLink Translation PR
  _lang/fr/_partners/message_orchestration/channel_extensions/ecommerce/shopify/scripttag_web_sdk_integration.md
  _lang/fr/_partners/message_orchestration/channel_extensions/ecommerce/shopify/setting_up_shopify.md
  _lang/fr/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify.md
  _lang/fr/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_in_braze.md
  _lang/fr/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
  _lang/fr/_partners/message_orchestration/channel_extensions/ecommerce/shopify/use_cases.md
  _lang/fr/_partners/message_orchestration/channel_extensions/ecommerce/yotpo.md
  _lang/fr/_partners/message_orchestration/channel_extensions/email_templates/dyspatch.md
  _lang/fr/_partners/message_orchestration/channel_extensions/email_templates/iam_studio.md
  _lang/fr/_partners/message_orchestration/channel_extensions/email_templates/knak.md
  _lang/fr/_partners/message_orchestration/channel_extensions/email_templates/stensul.md
  _lang/fr/_partners/message_orchestration/channel_extensions/email_templates/stripo.md
  _lang/fr/_partners/message_orchestration/channel_extensions/email_templates/taxi_for_email.md
  _lang/fr/_partners/message_orchestration/channel_extensions/loyalty/extole.md
  _lang/fr/_partners/message_orchestration/channel_extensions/loyalty/jebbit.md
  _lang/fr/_partners/message_orchestration/channel_extensions/loyalty/punchh.md
  _lang/fr/_partners/message_orchestration/channel_extensions/loyalty/viralsweep.md
  _lang/fr/_partners/message_orchestration/channel_extensions/loyalty/voucherify.md
  _lang/fr/_partners/message_orchestration/channel_extensions/loyalty/voucherify/voucherify.md
  _lang/fr/_partners/message_orchestration/channel_extensions/loyalty/voucherify/voucherify_distribution_with_braze_custom_attributes.md
  _lang/fr/_partners/message_orchestration/channel_extensions/loyalty/voucherify/voucherify_fetching_data_through_braze_connected_content.md
  _lang/fr/_partners/message_orchestration/channel_extensions/loyalty/voucherify/voucherify_using_braze_promotion_codes_list.md
  _lang/fr/_partners/message_orchestration/channel_extensions/surveys/ada.md
  _lang/fr/_partners/message_orchestration/channel_extensions/surveys/digioh.md
  _lang/fr/_partners/message_orchestration/channel_extensions/surveys/iterate.md
  _lang/fr/_partners/message_orchestration/learning/edume.md
  _lang/fr/_partners/message_personalization.md
  _lang/fr/_partners/message_personalization/dynamic_content.md
  _lang/fr/_partners/message_personalization/dynamic_content/amazon_personalize.md
Labels: cla-signed

#4682 GlobalLink Translation PR
  _lang/fr/_home/templates_old/tutorial_video.md
  _lang/fr/_home/templates_old/use_case.md
  _lang/fr/_home/templates_old/use_case_video.md
  _lang/fr/_partners/canvas_steps/facebook_audience_sync.md
  _lang/fr/_partners/canvas_steps/google_audience_sync.md
  _lang/fr/_partners/data_and_infrastructure_agility.md
  _lang/fr/_partners/data_and_infrastructure_agility/ab_testing/phrasee.md
  _lang/fr/_partners/data_and_infrastructure_agility/ab_testing/phrasee/phrasee.md
  _lang/fr/_partners/data_and_infrastructure_agility/ab_testing/phrasee/phrasee_react.md
  _lang/fr/_partners/data_and_infrastructure_agility/analytics/actionableme.md
  _lang/fr/_partners/data_and_infrastructure_agility/analytics/amplitude.md
  _lang/fr/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_audiences.md
  _lang/fr/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _lang/fr/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_user_profile_api.md
  _lang/fr/_partners/data_and_infrastructure_agility/analytics/clarisights.md
  _lang/fr/_partners/data_and_infrastructure_agility/analytics/contentsquare.md
  _lang/fr/_partners/data_and_infrastructure_agility/analytics/datadog.md
  _lang/fr/_partners/data_and_infrastructure_agility/analytics/kubit.md
  _lang/fr/_partners/data_and_infrastructure_agility/analytics/looker.md
  _lang/fr/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _lang/fr/_partners/data_and_infrastructure_agility/analytics/neura_insights.md
  _lang/fr/_partners/data_and_infrastructure_agility/analytics/npaw.md
  _lang/fr/_partners/data_and_infrastructure_agility/analytics/snowplow.md
  _lang/fr/_partners/data_and_infrastructure_agility/analytics/thoughtspot.md
  _lang/fr/_partners/data_and_infrastructure_agility/analytics/wunderkind.md
  _lang/fr/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
  _lang/fr/_partners/data_and_infrastructure_agility/cloud_storage/google_cloud_storage_for_currents.md
  _lang/fr/_partners/data_and_infrastructure_agility/cohort_import/heap.md
Labels: cla-signed

#4689 GlobalLink Translation PR
  _lang/fr/_api/endpoints/user_data/post_users_merge.md
  _lang/fr/_api/objects_filters/schedule_object.md
  _lang/fr/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md
  _lang/fr/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
  _lang/fr/_developer_guide/platform_integration_guides/android/content_cards/customization/custom_styling.md
  _lang/fr/_developer_guide/platform_integration_guides/android/content_cards/customization/default_feed.md
  _lang/fr/_developer_guide/platform_integration_guides/android/in-app_messaging/customization/message_dismissal.md
  _lang/fr/_developer_guide/platform_integration_guides/android/in-app_messaging/implementation_guide.md
  _lang/fr/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
  _lang/fr/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _lang/fr/_developer_guide/platform_integration_guides/android/news_feed/customization/click_listener.md
  _lang/fr/_developer_guide/platform_integration_guides/android/news_feed/customization/custom_styling.md
  _lang/fr/_developer_guide/platform_integration_guides/android/news_feed/integration.md
  _lang/fr/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/baidu_integration.md
  _lang/fr/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/huawei_integration.md
  _lang/fr/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _lang/fr/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization/setting_delegates.md
  _lang/fr/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/setting_delegates.md
  _lang/fr/_docs_pages/index.md
  _lang/fr/_partners/message_personalization/localization/transifex.md
  _lang/fr/_user_guide/administrative.md
  _lang/fr/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  _lang/fr/_user_guide/data_and_analytics.md
  _lang/fr/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _lang/fr/_user_guide/data_and_analytics/your_reports.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/devices_and_carriers.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/global_control_group_reporting.md
  _lang/fr/_user_guide/engagement_tools/segments/creating_a_segment.md
  _lang/fr/_user_guide/engagement_tools/segments/segment_extension.md
  _lang/fr/_user_guide/engagement_tools/segments/user_profiles.md
  _lang/fr/_user_guide/engagement_tools/testing/global_control_group.md
  _lang/fr/_user_guide/engagement_tools/testing/random_bucket_numbers.md
  _lang/fr/_user_guide/introduction.md
  _lang/fr/_user_guide/message_building_by_channel/email/inbox_vision.md
  _lang/fr/_user_guide/message_building_by_channel/email/preference_center.md
  _lang/fr/_user_guide/message_building_by_channel/email/preference_center/preference_center.md
  _lang/fr/_user_guide/message_building_by_channel/email/preference_center/preference_center_via_api.md
  _lang/fr/_user_guide/onboarding_with_braze/data_points.md
  _lang/fr/_user_guide/onboarding_with_braze/integration.md
  _lang/fr/_user_guide/onboarding_with_braze/learning_to_use_braze.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
Labels: cla-signed

#4672 update french documentation to be on par with English (based on BD-1472)
  _docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md
  _lang/fr/_user_guide/onboarding_with_braze/email_setup/email_validation.md
Labels: cla-signed

#4730 Defensive docs updates
  _docs/_api/endpoints/export/user_data/post_users_global_control_group.md
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  _docs/_api/identifier_types.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/use_cases/carousel_view.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/flutter/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization/customizing_feed.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization/use_cases/carousel_view.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/unity/push_notifications/android.md
  _docs/_developer_guide/platform_integration_guides/web/cookies_and_storage.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/integration.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_developer_guide/platform_wide/braze_actions.md
  _docs/_developer_guide/platform_wide/tv_and_ott.md
  _docs/_help/release_notes/2019/may.md
  _docs/_help/release_notes/deprecations/apptimize.md
  _docs/_hidden/wip_partnerships/partnership_template.md
  _docs/_home/static_video.md
  _docs/_partners/data_and_infrastructure_agility/analytics/snowplow.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/setting_up_shopify.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/intelligence/ai_copywriting.md
  _docs/_user_guide/message_building_by_channel/content_cards.md
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/content_cards/creative_details.md
  _docs/_user_guide/message_building_by_channel/content_cards/customize.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/about.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize/html_in-app_messages.md
  _docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_action_buttons.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/segments.md
  _docs/_user_guide/message_building_by_channel/sms/faqs.md
  _docs/_user_guide/onboarding_with_braze/data_points.md
  _docs/_user_guide/onboarding_with_braze/learning_to_use_braze.md
Labels: cla-signed

#4661 2/1 Currents Event Release
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#4731 Clarify link aliasing
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
Labels: cla-signed

#4732 Data Allowances Tweaks
  _docs/_user_guide/onboarding_with_braze/data_points.md
Labels: cla-signed

#4738 BD-1882: Apple Private Relay for Sparkpost steps
  _docs/_user_guide/message_building_by_channel/email/email_private_relay_apple_SSO.md
Labels: cla-signed

#4736 Remove Baidu and Windows
  _docs/_api/endpoints/export/campaigns/get_campaign_analytics.md
  _docs/_api/endpoints/export/user_data/post_users_global_control_group.md
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_messages.md
  _docs/_api/endpoints/messaging/send_messages/post_send_messages.md
  _docs/_api/objects_filters.md
  _docs/_api/objects_filters/messaging/windows_objects.md
  _docs/_developer_guide/home.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/baidu_integration.md
  _docs/_developer_guide/platform_integration_guides/sdk_changelogs.md
  _docs/_developer_guide/platform_integration_guides/windows_universal.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/logging_custom_events.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/tracking_sessions.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/changelog.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/windows_universal/push_notifications.md
  _docs/_developer_guide/platform_wide/sending_test_messages.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_campaign_results_data.md
  _docs/_user_guide/data_and_analytics/your_analytics_dashboards/understanding_your_app_usage_data.md
  _docs/_user_guide/data_and_analytics/your_reports/viewing_and_understanding_segment_data.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/campaigns_in_multiple_languages.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/localizing_a_campaign.md
  _docs/_user_guide/intelligence/intelligent_channel.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/conversion_tracking.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/detailed_push_preferences.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/message_format.md
  _docs/_user_guide/onboarding_with_braze/spam_regulations.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  _lang/fr/_api/endpoints/messaging/schedule_messages/post_schedule_messages.md
  _lang/fr/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/baidu_integration.md
Labels: cla-signed

#4737 Finessed the user/track rate limit
  _docs/_api/api_limits.md
  _includes/rate_limits.md
Labels: cla-signed

#4741 Misc backlog
  _docs/_api/endpoints/export/user_data/post_users_global_control_group.md
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#4734 BD-1879: Hidden doc for campaign status
  _docs/_hidden/private_betas/idle_campaigns.md
Labels: cla-signed

#4742 BD-1880: Clarify malformed rows
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  assets/img/importcsv.png
Labels: cla-signed

#4745 More Algolia tweaks
  _docs/_user_guide/data_and_analytics/braze_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md
  _docs/_user_guide/message_building_by_channel/content_cards.md
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/email.md
  _docs/_user_guide/message_building_by_channel/in-app_messages.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/about.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
Labels: cla-signed

#4746 BD-1883: Fix info for merge update field
  _docs/_api/endpoints/user_data/post_users_merge.md
Labels: cla-signed

#4744 Search rank update
  _docs/_user_guide/data_and_analytics/your_reports/reports_overview.md
Labels: cla-signed
