Repository braze-inc/braze-docs, pull requests merged in 2023-12, with the labels that each got.

#6570 BD-2648: Add detail for annotated emails in Gmail Promotions tab
  _docs/_user_guide/message_building_by_channel/email/html_editor/gmail_promotions_tab.md
Labels: cla-signed

#6566 Update create.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
Labels: cla-signed

#6532 Add additional notes for Expo Notifications
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Labels: cla-signed

#6499 BD-2565: Add reference links for user IDs and user aliasing in SDK docs
  _includes/archive/setting_user_ids/aliasing.md
  _includes/archive/setting_user_ids/best_practices.md
Labels: cla-signed

#6562 Update sdk_authentication.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
Labels: cla-signed

#6573 BD-2630: Clarifications for "Messages Sent" metric for Content Cards
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/message_building_by_channel/content_cards/migrating_from_news_feed.md
  _includes/campaign_analytics.md
Labels: cla-signed

#6574 BD-2655: Remove "Launch and Manage Content Blocks" permission
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#6579 Postman audit: Update permission phrasing pt. 5
  _docs/_api/endpoints/email/post_blacklist.md
Labels: cla-signed

#6575 Postman audit: Update permission phrasing pt. 1
  _docs/_api/endpoints/email/post_email_subscription_status.md
Labels: cla-signed

#6577 Postman audit: Update permission phrasing pt. 3
  _docs/_api/endpoints/email/post_remove_hard_bounces.md
Labels: cla-signed

#6578 Postman audit: Update permission phrasing pt. 4
  _docs/_api/endpoints/email/post_blocklist.md
Labels: cla-signed

#6582 fix reference to campaigns in canvas section
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
Labels: cla-signed

#6581 Changed instances of "BSON ID" to "Braze ID"
  _docs/_hidden/private_betas/sql_segments_tables.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _lang/fr/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _lang/fr/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#6585 Postman audit fixes pt.1
  _docs/_api/endpoints/export/user_data/post_users_segment.md
Labels: cla-signed

#6587 Postman audit fixes pt.2
  _docs/_api/endpoints/export/user_data/post_users_global_control_group.md
Labels: cla-signed

#6547 BD-2626: Preview user paths in Canvas EA [MERGE 12/5]
  _docs/_hidden/private_betas/preview_user_paths.md
  assets/img/preview_user_path_example.png
  assets/img/preview_user_path_results_example.png
Labels: status: done, cla-signed

#6563 Update datalake raw schemas to exclude retrysend event
  assets/download_file/data-sharing-raw-table-schemas.txt
Labels: cla-signed

#6589 BD-2659: Conversions dashboard GA
  _docs/_hidden/private_betas/conversions_dashboard_v2.md
  _docs/_user_guide/data_and_analytics/analytics/conversions_dashboard.md
Labels: cla-signed

#6596 Reverting accidental change to '.ruby-version', moving back to '2.7.4'
  .ruby-version
Labels: cla-signed, dependencies

#6593 BD-2632: Clarify active feature flags definition
  _docs/_developer_guide/platform_wide/feature_flags/about.md
Labels: cla-signed

#6595 Postman audit pt1 - SCIM GET
  _docs/_api/endpoints/scim/get_search_existing_dashboard_user.md
Labels: cla-signed

#6597 BD-2660: Update FAQ for Facebook Leads article
  _docs/_partners/data_and_infrastructure_agility/leads_capture/facebook_via_zapier.md
Labels: cla-signed

#6598 BD-2658: Move spam blocking alert to different article
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Labels: cla-signed

#6601 Update email_html_react.md
  _docs/_hidden/private_betas/email_html_react.md
Labels: cla-signed

#6602 Leftover Deploy - December 7, 2023
  .ruby-version
  _docs/_api/endpoints/scim/get_search_existing_dashboard_user.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
  _docs/_developer_guide/platform_wide/feature_flags/about.md
  _docs/_hidden/private_betas/campaign_data_retention.md
  _docs/_hidden/private_betas/email_html_react.md
  _docs/_hidden/private_betas/recommendations.md
  _docs/_partners/data_and_infrastructure_agility/leads_capture/facebook_via_zapier.md
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/sage_ai.md
  _docs/_user_guide/sage_ai/recommendations.md
  assets/img/item_recs_1.png
  assets/img/item_recs_2-1.png
  assets/img/item_recs_2-2.png
  assets/img/item_recs_3.png
  assets/img/item_recs_4.png
  assets/img/item_recs_analytics_1.png
  assets/img/item_recs_analytics_2.png
  assets/img/item_recs_analytics_3.png
Labels: cla-signed

#6600 BD-2643: Update existing Android Push Notification docs (XMPP deprication)
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  assets/img/android/push_integration/create_a_service_account/add-fcm-api-admin.png
  assets/img/android/push_integration/create_a_service_account/complete-service-account-creation.png
  assets/img/android/push_integration/create_a_service_account/enter-service-account-details.png
  assets/img/android/push_integration/create_a_service_account/select-create-service-account.png
  assets/img/android/push_integration/generate_json_credentials/select-create-new-key.png
  assets/img/android/push_integration/generate_json_credentials/select-create.png
  assets/img/android/push_integration/generate_json_credentials/select-manage-keys.png
  assets/img/android/push_integration/set_up_automatic_token_registration/copy-sender-id.png
  assets/img/android/push_integration/set_up_automatic_token_registration/select-project-settings.png
  assets/img/android/push_integration/upload_json_credentials/select-app-settings.png
  assets/img/android/push_integration/upload_json_credentials/upload-json-file.png
Labels: cla-signed

#6608 Fix issue with email capture hidden doc
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/email_capture.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/phone_number_capture.md
Labels: cla-signed

#6609 Deploy – December 11, 2023
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_user_guide/data_and_analytics/reporting/engagement_reports.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/personalized_paths.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/email_capture.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/phone_number_capture.md
  assets/img/android/push_integration/create_a_service_account/add-fcm-api-admin.png
  assets/img/android/push_integration/create_a_service_account/complete-service-account-creation.png
  assets/img/android/push_integration/create_a_service_account/enter-service-account-details.png
  assets/img/android/push_integration/create_a_service_account/select-create-service-account.png
  assets/img/android/push_integration/generate_json_credentials/select-create-new-key.png
  assets/img/android/push_integration/generate_json_credentials/select-create.png
  assets/img/android/push_integration/generate_json_credentials/select-manage-keys.png
  assets/img/android/push_integration/set_up_automatic_token_registration/copy-sender-id.png
  assets/img/android/push_integration/set_up_automatic_token_registration/select-project-settings.png
  assets/img/android/push_integration/upload_json_credentials/select-app-settings.png
  assets/img/android/push_integration/upload_json_credentials/upload-json-file.png
Labels: cla-signed, Deploy

#6610 BD-2672 Add WhatsApp to Frequency capping docs
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
  assets/img_archive/rate_limiting_overview_2.png
Labels: cla-signed

#6612 [SMS-1368] Update WhatsApp object specification to support repsonse messages
  _docs/_api/objects_filters/messaging/whats_app_object.md
Labels: cla-signed

#6611 BD-2662 Add missing definitions
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#6606 Postman Audit
  _docs/_api/endpoints/templates/content_blocks_templates/get_list_email_content_blocks.md
  _docs/_api/endpoints/templates/content_blocks_templates/get_see_email_content_blocks_information.md
  _docs/_api/endpoints/templates/content_blocks_templates/post_create_email_content_block.md
  _docs/_api/endpoints/templates/content_blocks_templates/post_update_content_block.md
  _docs/_api/endpoints/templates/email_templates/get_list_email_templates.md
  _docs/_api/endpoints/templates/email_templates/get_see_email_template_information.md
  _docs/_api/endpoints/templates/email_templates/post_create_email_template.md
  _docs/_api/endpoints/templates/email_templates/post_update_email_template.md
  _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_remove.md
  _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_rename.md
  _docs/_api/endpoints/user_data/post_user_alias.md
  _docs/_api/endpoints/user_data/post_user_delete.md
  _docs/_api/endpoints/user_data/post_user_identify.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_api/endpoints/user_data/post_users_alias_update.md
  _docs/_api/endpoints/user_data/post_users_merge.md
Labels: cla-signed

#6616 BD-2654: Update step 5 of Amazon S3 partner doc
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
Labels: cla-signed

#6619 BD-2670: Clarify data point consumption for User Update step
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
Labels: cla-signed

#6617 BD-2673: Email Insights dashboard GA
  _docs/_hidden/private_betas/email_engagement.md
  _docs/_user_guide/data_and_analytics/analytics/email_performance_dashboard.md
  _docs/_user_guide/message_building_by_channel/email/reporting_and_analytics/analytics_glossary.md
  assets/img_archive/mailbox_provider_time_engagement.png
  assets/img_archive/time_engagement.png
  assets/img_archive/time_engagement_day.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6571 BD-2629: Clarify post-launch editing
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
Labels: cla-signed

#6621 BD-2668: Add dispatch_id for Unique Clicks metric
  _docs/_user_guide/message_building_by_channel/email/reporting_and_analytics/analytics_glossary.md
  _includes/campaign_analytics.md
Labels: cla-signed

#6618 BD-2612: Add external_id to Message Archiving file references
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
Labels: cla-signed

#6622 BD-2657: Add example for deduplication behavior
  _docs/_user_guide/message_building_by_channel/email/best_practices/managing_email_subscriptions.md
Labels: cla-signed

#6625 Postman audit pt2
  _docs/_api/endpoints/preference_center/get_create_url_preference_center.md
  _docs/_api/endpoints/preference_center/get_list_preference_center.md
  _docs/_api/endpoints/preference_center/get_view_details_preference_center.md
  _docs/_api/endpoints/preference_center/post_create_preference_center.md
  _docs/_api/endpoints/preference_center/put_update_preference_center.md
  _docs/_api/endpoints/scim/delete_existing_dashboard_user.md
  _docs/_api/endpoints/scim/get_search_existing_dashboard_user.md
  _docs/_api/endpoints/scim/get_see_user_account_information.md
  _docs/_api/endpoints/scim/post_create_user_account.md
  _docs/_api/endpoints/scim/put_update_existing_user_account.md
Labels: cla-signed

#6624 BD-2674 Hotfix: fixing 404s from developer guide homepage
  _docs/_developer_guide/home.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6627 Postman audit: Add prerequisites header for API endpoint docs
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/delete_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/patch_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/post_create_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/put_update_catalog_items.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/delete_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/get_catalog_item_details.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/get_catalog_items_details_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/patch_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/put_update_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/delete_catalog.md
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/get_list_catalogs.md
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md
  _docs/_api/endpoints/email/get_list_hard_bounces.md
  _docs/_api/endpoints/email/get_query_unsubscribed_email_addresses.md
  _docs/_api/endpoints/email/post_blacklist.md
  _docs/_api/endpoints/email/post_blocklist.md
  _docs/_api/endpoints/email/post_email_subscription_status.md
  _docs/_api/endpoints/email/post_remove_hard_bounces.md
  _docs/_api/endpoints/email/post_remove_spam.md
  _docs/_api/endpoints/export/campaigns/get_campaign_analytics.md
  _docs/_api/endpoints/export/campaigns/get_campaign_details.md
  _docs/_api/endpoints/export/campaigns/get_campaigns.md
  _docs/_api/endpoints/export/campaigns/get_send_analytics.md
  _docs/_api/endpoints/export/canvas/get_canvas_analytics.md
  _docs/_api/endpoints/export/canvas/get_canvas_analytics_summary.md
  _docs/_api/endpoints/export/canvas/get_canvas_details.md
  _docs/_api/endpoints/export/canvas/get_canvases.md
  _docs/_api/endpoints/messaging/schedule_messages/get_messages_scheduled.md
  _docs/_api/endpoints/messaging/schedule_messages/post_delete_scheduled_messages.md
  _docs/_api/endpoints/messaging/schedule_messages/post_delete_scheduled_triggered_canvases.md
  _docs/_api/endpoints/messaging/schedule_messages/post_delete_scheduled_triggered_messages.md
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_messages.md
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_campaigns.md
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_canvases.md
  _docs/_api/endpoints/messaging/schedule_messages/post_update_scheduled_messages.md
  _docs/_api/endpoints/messaging/schedule_messages/post_update_scheduled_triggered_campaigns.md
  _docs/_api/endpoints/messaging/schedule_messages/post_update_scheduled_triggered_canvases.md
  _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_remove.md
  _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_rename.md
  _docs/_api/endpoints/user_data/post_user_alias.md
  _docs/_api/endpoints/user_data/post_user_delete.md
  _docs/_api/endpoints/user_data/post_user_identify.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_api/endpoints/user_data/post_users_alias_update.md
  _docs/_api/endpoints/user_data/post_users_merge.md
Labels: cla-signed

#6626 Update for subscription group graph
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  assets/img_archive/subscription_group_graph.png
Labels: cla-signed

#6623 Add company id to support contact
  _docs/_hidden/other/support_contact.md
Labels: cla-signed

#6555 BD-2625: Updating "Twitter" to "X" when applicable
  _docs/_partners/message_personalization/dynamic_content/playable.md
  _docs/_user_guide/personalization_and_dynamic_content/deep_linking_to_in-app_content.md
Labels: cla-signed

#6605 December 2023 release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023.md
  _docs/_help/release_notes/2023/12_12_23.md
Labels: cla-signed, release notes

#6628 Minor fixes for X (formerly Twitter)
  _docs/_api/objects_filters/user_attributes_object.md
  _docs/_home/templates_old/api_glossary.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/adobe/event_forwarding_extension.md
  _docs/_partners/message_orchestration/attribution/adjust.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _docs/_partners/message_orchestration/attribution/branch/branch_for_attribution.md
  _docs/_partners/message_orchestration/attribution/kochava.md
  _docs/_partners/message_orchestration/attribution/singular.md
  _docs/_user_guide/engagement_tools/segments/segment_funnels.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/personalization_and_dynamic_content/deep_linking_to_in-app_content.md
Labels: cla-signed

#6630 copy 404 file to root path
  Rakefile
Labels: cla-signed

#6631 Fix 404 typo
  Rakefile
Labels: cla-signed

#6633 Postman audit pt 3
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_canvases.md
  _docs/_api/endpoints/messaging/schedule_messages/post_update_scheduled_messages.md
  _docs/_api/endpoints/messaging/schedule_messages/post_update_scheduled_triggered_canvases.md
Labels: cla-signed

#6553 BD-2628: Add detail for telephone redirects in Gmail
  _docs/_partners/message_orchestration/attribution/branch/branch_for_deeplinking.md
Labels: cla-signed

#6629 BD-2671: Instructions for updating existing Currents
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
  _includes/updating_currents.md
Labels: cla-signed

#6636 Auto redirect to 404 language to default page
  _layouts/broken_page.html
Labels: cla-signed

#6638 Add list-unsubscribe redirect
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6613 Remove very old documentation on PII and NON_PII tables in Datalake
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
Labels: cla-signed

#6634 BD-2678 Change description for Manage media library permission
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#6639 Add note about dynamic sending domains + IP pools
  _docs/_user_guide/administrative/app_settings/email_settings.md
Labels: cla-signed

#6640 Update Manage Media Library Assets
  _docs/_hidden/misc_reference/scim_api_appendix.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/teams.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#6641 Update description for Access Dev Console permission
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#6644 BD-2616 update modal screenshots and workflow
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
  assets/img/segment/segment_extension_modal.png
  assets/img/segment/select_a_template.png
  assets/img_archive/sql_segments_regenerate.png
Labels: cla-signed

#6645 fix 404 redirect
  _layouts/broken_page.html
Labels: cla-signed

#6580 Update flywheel.md
  _docs/_help/release_notes/2023/3_7_23.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/flywheel.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/growthloop.md
  _docs/_partners/home.md
  assets/js/broken_redirect_list.js
Labels: cla-signed, Braze Partnerships

#6615 BD-2642 Migration guide for Google cloud messaging api deprecation
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/migrating_to_firebase_cloud_messaging.md
  assets/img/android/push_integration/migration/upload_json_credentials/upload-json-file.png
  assets/img/android/push_integration/migration/verify-sender-id/verify-sender-id.png
Labels: cla-signed

#6647 BD-2685: 404 fix
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/aborting_connected_content.md
Labels: cla-signed

#6649 BD-2683: Update campaign interaction data EA note
  _docs/_hidden/private_betas/campaign_data_retention.md
Labels: cla-signed

#6650 Hotfix - Adding 'Early Access' banner to FCM docs
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/migrating_to_firebase_cloud_messaging.md
  _includes/firebase_cloud_messaging/early_access_banner.md
Labels: cla-signed

#6643 Leftover deploy - December 14, 2023
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/migrating_to_firebase_cloud_messaging.md
  _docs/_help/release_notes/2023/3_7_23.md
  _docs/_hidden/misc_reference/scim_api_appendix.md
  _docs/_hidden/private_betas/campaign_data_retention.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/flywheel.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/growthloop.md
  _docs/_partners/home.md
  _docs/_user_guide/administrative/app_settings/email_settings.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/teams.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/aborting_connected_content.md
  _includes/firebase_cloud_messaging/early_access_banner.md
  _includes/updating_currents.md
  _layouts/broken_page.html
  assets/img/android/push_integration/migration/upload_json_credentials/upload-json-file.png
  assets/img/android/push_integration/migration/verify-sender-id/verify-sender-id.png
  assets/img/segment/segment_extension_modal.png
  assets/img/segment/select_a_template.png
  assets/img_archive/sql_segments_regenerate.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#6642 Revert image and minor edits for list-unsubscribe header
  _docs/_user_guide/administrative/app_settings/email_settings.md
  assets/img_archive/list_unsub_img1.png
Labels: cla-signed

#6651 Leftover Deploy pt.2 - December 14, 2023
  _docs/_user_guide/administrative/app_settings/email_settings.md
  assets/img_archive/list_unsub_img1.png
Labels: cla-signed, Deploy

#6652 BD-2679 Remove content card limit
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
Labels: cla-signed

#6637 Add push clarification to canvas rate limiting docs
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
Labels: cla-signed

#6654 API fixes found during endpoint audit
  _docs/_api/endpoints/messaging/live_activity/update.md
  _docs/_api/endpoints/messaging/send_messages/post_create_send_ids.md
  _docs/_api/endpoints/messaging/send_messages/post_send_messages.md
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
Labels: cla-signed

#6648 Update docs with correct archival avoidance step.
  _docs/_hidden/other/user_archival.md
  assets/img_archive/user_archival_policy3.png
Labels: cla-signed

#6656 Postman prerequisites fixes
  _docs/_api/endpoints/export/custom_events/get_custom_events.md
  _docs/_api/endpoints/export/custom_events/get_custom_events_analytics.md
  _docs/_api/endpoints/export/kpi/get_kpi_daily_new_users_date.md
  _docs/_api/endpoints/export/kpi/get_kpi_dau_date.md
  _docs/_api/endpoints/export/kpi/get_kpi_mau_30_days.md
  _docs/_api/endpoints/export/kpi/get_kpi_uninstalls_date.md
  _docs/_api/endpoints/export/news_feed/get_news_feed_card_analytics.md
  _docs/_api/endpoints/export/news_feed/get_news_feed_card_details.md
  _docs/_api/endpoints/export/news_feed/get_news_feed_cards.md
  _docs/_api/endpoints/export/purchases/get_list_product_id.md
  _docs/_api/endpoints/export/purchases/get_number_of_purchases.md
  _docs/_api/endpoints/export/purchases/get_revenue_series.md
  _docs/_api/endpoints/export/segments/get_segment.md
  _docs/_api/endpoints/export/segments/get_segment_analytics.md
  _docs/_api/endpoints/export/segments/get_segment_details.md
  _docs/_api/endpoints/export/sessions/get_sessions_analytics.md
  _docs/_api/endpoints/export/user_data/post_users_global_control_group.md
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_api/endpoints/sms/get_query_invalid_numbers.md
  _docs/_api/endpoints/sms/post_remove_invalid_numbers.md
  _docs/_api/endpoints/subscription_groups/get_list_user_subscription_group_status.md
  _docs/_api/endpoints/subscription_groups/get_list_user_subscription_groups.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
Labels: cla-signed

#6569 Shopify overhaul
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/Shopify_Features/shopify_backfill.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/Shopify_Features/shopify_catalogs.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/Shopify_Features/shopify_catalogs/back_in_stock.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/Shopify_Features/shopify_user_identity.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/Using_Shopify/shopify_data_in_braze.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/Using_Shopify/use_cases.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/getting_started_shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/scripttag_web_sdk_integration.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/setting_up_shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_overview.md
  assets/img/Shopify/shop_setup_1.png
  assets/img/Shopify/shop_setup_2.png
  assets/img/Shopify/shop_setup_3a.png
  assets/img/Shopify/shop_setup_3b.png
  assets/img/Shopify/shop_setup_4.png
  assets/img/Shopify/shop_setup_5.png
  assets/img/Shopify/shop_setup_6.png
  assets/img/Shopify/shop_setup_7.png
  assets/img/Shopify/shop_setup_8.png
  assets/img/Shopify/shop_setup_9.png
  assets/img/Shopify/shop_setup_advanced_abandonment.png
  assets/img/Shopify/shop_setup_advanced_productid.png
  assets/img/Shopify/shop_usermerge_canvas.png
  assets/img/Shopify/shop_usermerge_canvas_delay.png
  assets/img/Shopify/shop_usermerge_canvas_entrycriteria.png
  assets/img/Shopify/shop_usermerge_canvas_userupdate.png
  assets/img/Shopify/shop_usermerge_canvas_webhook.png
  assets/img/Shopify/shopify_usersyncing_subscribercollection.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6506 Update media_library.md
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
Labels: cla-signed

#6659 Fix capitalization of third-party provider
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
Labels: cla-signed

#6660 Fix Liquid snippet
  _docs/_hidden/other/user_archival.md
Labels: cla-signed

#6661 Deploy - December 18, 2023
  _docs/_hidden/other/user_archival.md
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
Labels: Deploy

#6662 Add additional subtext to 404
  _docs/_docs_pages/404.md
  _lang/fr/_docs_pages/404.md
  _layouts/broken_page.html
Labels: cla-signed

#6646 BD-2677 Add information on segmentation filtering
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#6664 BD-2690 email capture updates
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/email_capture.md
Labels: cla-signed

#6657 BD-2684 Update sms double opt-in description
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#6665 BD-2686 Add note to link shortening testing
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
Labels: cla-signed

#6667 Remove non-inclusive language
  _docs/_developer_guide/platform_wide/feature_flags/create.md
Labels: cla-signed

#6666 BD-2682 Update user attributes with warnings
  _docs/_api/objects_filters/user_attributes_object.md
Labels: cla-signed

#6668 Update deprecations.md
  _docs/_help/release_notes/deprecations.md
Labels: cla-signed

#6669 Update web-v4-rename.md
  _includes/archive/web-v4-rename.md
Labels: cla-signed

#6658 Remove SHARE button types from docs
  _docs/_hidden/private_betas/sql_segments_tables.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _lang/fr/_hidden/private_betas/sql_segments_tables.md
  _lang/fr/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#6670 Minor edits
  _docs/_user_guide/personalization_and_dynamic_content/liquid/aborting_messages.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/conditional_logic.md
Labels: cla-signed

#6672 BD-2692 Add an additional line for the AndroidManifest.xml file
  _docs/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md
Labels: cla-signed

#6671 Update code_generation.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/code_generation.md
Labels: cla-signed

#6674 BD-2688: Add note for Experiment Paths step not editable after Canvas launch
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
Labels: cla-signed

#6675 Fix merge_updates JSON formatting.
  _docs/_api/endpoints/user_data/post_users_merge.md
Labels: cla-signed

#6677 Fixing broken link in iOS in-app messaging
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6663 Fix redirect due to capitalization
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6678 Leftover Deploy - December 21, 2023
  _docs/_api/endpoints/user_data/post_users_merge.md
  _docs/_api/objects_filters/user_attributes_object.md
  _docs/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
  _docs/_docs_pages/404.md
  _docs/_help/release_notes/deprecations.md
  _docs/_hidden/private_betas/sql_segments_tables.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/code_generation.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/email_capture.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/aborting_messages.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/conditional_logic.md
  _includes/archive/web-v4-rename.md
  _lang/fr/_docs_pages/404.md
  _lang/fr/_hidden/private_betas/sql_segments_tables.md
  _lang/fr/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _layouts/broken_page.html
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#6676 BD-2675: Clarify HTML attributes for email editors
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
Labels: cla-signed

#6679 BD-2681: Add "2XX response" detail for returning valid JSON
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
Labels: cla-signed
