Repository braze-inc/braze-docs, pull requests merged in 2023-03, with the labels that each got.

#4927 Reword IP Range to IPs for Webhook IP Whitelist
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
Labels: cla-signed

#4876 [Untracked] React Native docs - edit Swift snippet
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Labels: cla-signed

#4923 WhatsApp credit ratios doc (hidden)
  _docs/_hidden/other/credit_ratios.md
Labels: cla-signed

#4899 GlobalLink Translation PR
  _lang/fr/_api/endpoints/export/campaigns/get_campaign_analytics.md
  _lang/fr/_api/endpoints/export/canvas/get_canvas_analytics.md
  _lang/fr/_developer_guide/platform_integration_guides/flutter/content_cards.md
  _lang/fr/_developer_guide/platform_integration_guides/flutter/flutter_sdk_integration.md
  _lang/fr/_developer_guide/platform_integration_guides/flutter/inapp_messages.md
  _lang/fr/_developer_guide/platform_integration_guides/react_native/push_notifications.md
  _lang/fr/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md
  _lang/fr/_developer_guide/platform_integration_guides/unity/sdk_integration/ios.md
  _lang/fr/_developer_guide/platform_wide/feature_flags.md
  _lang/fr/_help/release_notes/2022/7_26_22.md
  _lang/fr/_help/release_notes/2023.md
  _lang/fr/_help/release_notes/2023/2_7_23.md
  _lang/fr/_hidden/private_betas/navigation.md
  _lang/fr/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/attribute_triggers.md
  _lang/fr/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md
  _lang/fr/_user_guide/engagement_tools/canvas/testing_canvases/sending_test_canvases.md
  _lang/fr/_user_guide/intelligence.md
  _lang/fr/_user_guide/intelligence/ai_copywriting.md
  _lang/fr/_user_guide/intelligence/intelligent_channel.md
  _lang/fr/_user_guide/intelligence/intelligent_selection.md
  _lang/fr/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
  _lang/fr/_user_guide/message_building_by_channel/push/best_practices.md
  _lang/fr/_user_guide/onboarding_with_braze/data_points.md
Labels: cla-signed

#4932 BD-1952: Add tile
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization.md
Labels: cla-signed

#4912 BD-1948: Note that Push Story doesn't dismiss upon click on Android
  _docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_stories.md
Labels: cla-signed

#4882 Custom Domains for Link Shortening - MERGE 3/1
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
  assets/img/custom_domain.png
  assets/img/custom_domain2.png
Labels: cla-signed

#4935 Card creation GA
  _docs/_user_guide/message_building_by_channel/content_cards.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/content_cards/create/card_creation.md
Labels: cla-signed, release notes

#4936 Live activities update 3 2 23
  _docs/_api/endpoints/messaging/live_activity.md
  _docs/_api/endpoints/messaging/live_activity/update.md
  _docs/_developer_guide/platform_integration_guides/swift.md
  _docs/_developer_guide/platform_integration_guides/swift/live_activities.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/integration.md
  assets/img/LiveActivities1.png
  assets/img/LiveActivities2.png
  assets/img/LiveActivities3.png
Labels: cla-signed

#4940 Update the canvas entry criteria with text provided by legal
  _docs/_hidden/private_betas/pinterest_audience_sync.md
  _docs/_hidden/private_betas/snapchat_audience_sync.md
  _docs/_hidden/private_betas/tiktok.md
  _docs/_partners/canvas_steps/facebook_audience_sync.md
  _docs/_partners/canvas_steps/google_audience_sync.md
Labels: cla-signed

#4942 Missing import for flutter (ios) set up
  _docs/_developer_guide/platform_integration_guides/flutter/flutter_sdk_integration.md
Labels: cla-signed

#4941 Update Connected Content docs to provide context for :rerender
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/user_profile_fields_connected_content.md
Labels: cla-signed

#4945 Dashboard fix and legal text update for canvas audience sync
  _docs/_hidden/private_betas/pinterest_audience_sync.md
  _docs/_hidden/private_betas/snapchat_audience_sync.md
  _docs/_hidden/private_betas/tiktok.md
  _docs/_partners/canvas_steps/facebook_audience_sync.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_user_guide/data_and_analytics/analytics.md
  _docs/_user_guide/data_and_analytics/custom_data.md
Labels: cla-signed

#4948 Fix duplicated analytics section on French site
  _lang/fr/_user_guide/data_and_analytics/analytics/conversions_dashboard.md
  _lang/fr/_user_guide/data_and_analytics/analytics/email_performance_dashboard.md
  _lang/fr/_user_guide/data_and_analytics/analytics/understanding_your_app_usage_data.md
  _lang/fr/_user_guide/data_and_analytics/your_analytics_dashboards.md
  _lang/fr/_user_guide/data_and_analytics/your_reports.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/campaign_analytics.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/devices_and_carriers.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/engagement_reports.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/funnel_reports.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/global_control_group_reporting.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/report_builder.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/reports_overview.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/retention_reports.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/viewing_and_understanding_segment_data.md
Labels: cla-signed

#4943 Remove Neura
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/analytics.md
  _docs/_partners/data_and_infrastructure_agility/analytics/neura_insights.md
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/location.md
  _docs/_partners/message_personalization/location/neura_actions.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/geofence_configuration.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/location_tracking.md
Labels: cla-signed

#4947 Leftover Deploy Pt. 2 - March 3, 2023
  _docs/_developer_guide/platform_integration_guides/flutter/flutter_sdk_integration.md
  _docs/_hidden/private_betas/pinterest_audience_sync.md
  _docs/_hidden/private_betas/snapchat_audience_sync.md
  _docs/_hidden/private_betas/tiktok.md
  _docs/_partners/canvas_steps/facebook_audience_sync.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/analytics.md
  _docs/_partners/data_and_infrastructure_agility/analytics/neura_insights.md
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/location.md
  _docs/_partners/message_personalization/location/neura_actions.md
  _docs/_user_guide/data_and_analytics/analytics.md
  _docs/_user_guide/data_and_analytics/custom_data.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/geofence_configuration.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/location_tracking.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/user_profile_fields_connected_content.md
  _lang/fr/_user_guide/data_and_analytics/analytics/conversions_dashboard.md
  _lang/fr/_user_guide/data_and_analytics/analytics/email_performance_dashboard.md
  _lang/fr/_user_guide/data_and_analytics/analytics/understanding_your_app_usage_data.md
  _lang/fr/_user_guide/data_and_analytics/your_analytics_dashboards.md
  _lang/fr/_user_guide/data_and_analytics/your_reports.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/campaign_analytics.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/devices_and_carriers.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/engagement_reports.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/funnel_reports.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/global_control_group_reporting.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/report_builder.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/reports_overview.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/retention_reports.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/viewing_and_understanding_segment_data.md
Labels: cla-signed, Deploy

#4944 Add 500 active CC campaign note
  _docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
Labels: cla-signed

#4952 Table list edits pt.1
  _docs/_user_guide/administrative/app_settings/developer_console/message_activity_log_tab.md
  _docs/_user_guide/administrative/company_settings/security_settings.md
  _docs/_user_guide/data_and_analytics/query_builder.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _includes/archive/short_and_long_codes.md
Labels: cla-signed

#4951 BD-1951: Update Okta SSO steps
  _docs/_user_guide/administrative/access_braze/single_sign_on/okta.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/onelogin.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/set_up.md
Labels: cla-signed

#4950 BD-1956: Updates to WA Credit page
  _docs/_hidden/other/credit_ratios.md
Labels: cla-signed

#4955 10DLC Updates - 4-6 week review period
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/10dlc.md
  _includes/archive/short_and_long_codes.md
Labels: cla-signed

#4933 RudderStack for Currents - MERGE 3/7
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack/rudderstack.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack/rudderstack_for_currents.md
Labels: cla-signed

#4957 Remove EA note from report builder charts
  _docs/_user_guide/data_and_analytics/reporting/report_builder.md
Labels: cla-signed

#4956 update docs with preference center options values
  _docs/_api/endpoints/preference_center/get_view_details_preference_center.md
  _docs/_api/endpoints/preference_center/post_create_preference_center.md
  _docs/_api/endpoints/preference_center/put_update_preference_center.md
Labels: cla-signed

#4958 Update user_permissions.md
  _docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#4959 Add reset styles to DND IAM
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  assets/img_archive/dnd_iam_copypaste_styles.png
  assets/img_archive/dnd_iam_reset_styles.gif
Labels: cla-signed

#4961 CO-1330 updates catalog endpoint docs to remove fields-do-not-match error
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/post_create_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md
  _lang/fr/_api/endpoints/catalogs/catalog_items/asynchronous/post_create_catalog_items_bulk.md
  _lang/fr/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md
Labels: cla-signed

#4960 Add March 2023 release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023.md
  _docs/_help/release_notes/2023/3_7_23.md
Labels: cla-signed, release notes

#4963 Add additional dnd HTML attribute link use case
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
Labels: cla-signed

#4965 Sisu data tile fix
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/business_intelligence.md
  _docs/_partners/home.md
Labels: cla-signed

#4967 Update deprecated link to new method
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/customization/action_buttons.md
Labels: cla-signed

#4969 Remove Currents events - Revert 3/28
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023/2_7_23.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#4971 Update Company notification preferences
  _docs/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md
Labels: cla-signed

#4972 Edits to Canvas approval workflow
  _docs/_hidden/private_betas/canvas_approval.md
  assets/img_archive/canvas_approval_summary.png
Labels: cla-signed

#4970 Update create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
Labels: cla-signed

#4973 WA Credit ratios legal updates
  _docs/_hidden/other/credit_ratios.md
Labels: cla-signed

#4966 Moving data points article out of onboarding into data section and add a redirect
  _docs/_user_guide/data_and_analytics.md
  _docs/_user_guide/data_and_analytics/data_points.md
  _docs/_user_guide/onboarding_with_braze/data_points.md
Labels: cla-signed

#4974 Move changelog to bottom of navigation in dev guide
  _docs/_developer_guide/platform_integration_guides/sdk_changelogs.md
Labels: cla-signed

#4782 Note about local time delivery
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/winning_path.md
Labels: cla-signed

#4984 BD-1962: Remove EA note from IAM DND
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
Labels: cla-signed

#4985 BD-1961: Add CC troubleshooting
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
Labels: cla-signed

#4981 Updated the API documentation for the new live activity endpoint
  _docs/_api/basics.md
  _docs/_api/endpoints/messaging.md
  _docs/_api/endpoints/messaging/live_activity/update.md
  _docs/_api/home.md
Labels: cla-signed

#4987 BD-1965: Add audience export instructions for facebook
  _docs/_partners/message_orchestration/additional_channels/retargeting/facebook.md
Labels: cla-signed

#4989 Typo in javascript example
  _docs/_developer_guide/platform_wide/feature_flags/create.md
Labels: cla-signed

#4855 [SDK-3025] Swift Docs - In-App Messages
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/custom_app_store_review_prompt.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/behavior_on_click.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/custom_app_store_review_prompt.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/custom_triggering.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/custom_view_controller.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/customizing_orientation.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/handing_in_app_display.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/handling_in_app_display.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/key_value_pairs.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/modal_dismissal.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/setting_delegates.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/implementation_guide/shareplay.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/troubleshooting.md
  assets/img/full-screen-header-text.png
  assets/img/full-screen-image.png
  assets/img/modal-full-image.png
  assets/img/modal-header-text.png
  assets/img/swift/supported_interface_orientations_xcode.png
Labels: cla-signed

#4992 Update react_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Labels: cla-signed

#4993 Fix links
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl.md
Labels: cla-signed

#4996 BD-1967: Clarify Phrasee requirements
  _docs/_partners/data_and_infrastructure_agility/ab_testing/phrasee/phrasee.md
  _docs/_partners/data_and_infrastructure_agility/ab_testing/phrasee/phrasee_react.md
Labels: cla-signed

#4997 Leftover Deploy - March 9, 2023
  _docs/_api/basics.md
  _docs/_api/endpoints/export.md
  _docs/_api/endpoints/messaging.md
  _docs/_api/endpoints/messaging/live_activity/update.md
  _docs/_api/home.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
  _docs/_partners/data_and_infrastructure_agility/ab_testing/phrasee/phrasee.md
  _docs/_partners/data_and_infrastructure_agility/ab_testing/phrasee/phrasee_react.md
  _docs/_partners/message_orchestration/additional_channels/retargeting/facebook.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/winning_path.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
  _layouts/dev_guide.html
Labels: cla-signed, Deploy

#4998 Fixes for CDI docs
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/redshift.md
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/snowflake.md
Labels: cla-signed

#4999 BD-1962: Push primer and best practices edits
  _docs/_user_guide/message_building_by_channel/push.md
  _docs/_user_guide/message_building_by_channel/push/best_practices.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/creating_custom_opt-in_prompts.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/detailed_push_preferences.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/push_primer_messages.md
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#5002 Update rack 2.2.6.3
  Gemfile.lock
Labels: cla-signed

#5003 BD-1969: Updates to Singular and Branch code snippets
  _docs/_partners/message_orchestration/attribution/branch/branch_for_attribution.md
  _docs/_partners/message_orchestration/attribution/singular.md
Labels: cla-signed

#4982 Merkury Partnership Docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/analytics.md
  _docs/_partners/data_and_infrastructure_agility/analytics/merkury.md
  _docs/_partners/home.md
Labels: cla-signed, Braze Partnerships

#5004 Move unused hidden docs (excluding beta and EA) to a special folder out of main docs
  _docs/_developer_guide/platform_integration_guides/windows_universal.md
  _docs/_hidden/archive_docs/android_11.md
  _docs/_hidden/archive_docs/android_12.md
  _docs/_hidden/archive_docs/baidu_integration.md
  _docs/_hidden/archive_docs/generations.md
  _docs/_hidden/archive_docs/interactive.md
  _docs/_hidden/archive_docs/ios_14.md
  _docs/_hidden/archive_docs/ios_15.md
  _docs/_hidden/archive_docs/previous_in-app_message_generations.md
  _docs/_hidden/archive_docs/product_request_example.md
  _docs/_hidden/archive_docs/windows_object.md
  _docs/_hidden/archive_docs/windows_universal/analytics.md
  _docs/_hidden/archive_docs/windows_universal/analytics/location_tracking.md
  _docs/_hidden/archive_docs/windows_universal/analytics/logging_custom_events.md
  _docs/_hidden/archive_docs/windows_universal/analytics/logging_purchases.md
  _docs/_hidden/archive_docs/windows_universal/analytics/setting_custom_attributes.md
  _docs/_hidden/archive_docs/windows_universal/analytics/setting_user_ids.md
  _docs/_hidden/archive_docs/windows_universal/analytics/tracking_sessions.md
  _docs/_hidden/archive_docs/windows_universal/changelog.md
  _docs/_hidden/archive_docs/windows_universal/initial_sdk_setup.md
  _docs/_hidden/archive_docs/windows_universal/push_notifications.md
  _docs/_hidden/misc_reference/scim_api_appendix.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/best_practices/prep_guide.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/generations.md
Labels: cla-signed

#5005 Removed double curly braces in examples, since they were not rendering
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/testing.md
  _docs/_developer_guide/platform_wide/sending_test_messages.md
Labels: cla-signed

#4988 BD-1955: Update segmentation article
  _docs/_help/help_articles/segments/segmentation_logic_with_and_or.md
  assets/img_archive/or_operator_segment.png
Labels: status: in progress, cla-signed

#5010 Leftover deploy - March 13, 2023
  Gemfile.lock
  _docs/_api/api_limits.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/testing.md
  _docs/_developer_guide/platform_integration_guides/windows_universal.md
  _docs/_developer_guide/platform_wide/sending_test_messages.md
  _docs/_help/help_articles/segments/segmentation_logic_with_and_or.md
  _docs/_hidden/archive_docs/android_11.md
  _docs/_hidden/archive_docs/android_12.md
  _docs/_hidden/archive_docs/baidu_integration.md
  _docs/_hidden/archive_docs/generations.md
  _docs/_hidden/archive_docs/interactive.md
  _docs/_hidden/archive_docs/ios_14.md
  _docs/_hidden/archive_docs/ios_15.md
  _docs/_hidden/archive_docs/previous_in-app_message_generations.md
  _docs/_hidden/archive_docs/product_request_example.md
  _docs/_hidden/archive_docs/windows_object.md
  _docs/_hidden/archive_docs/windows_universal/analytics.md
  _docs/_hidden/archive_docs/windows_universal/analytics/location_tracking.md
  _docs/_hidden/archive_docs/windows_universal/analytics/logging_custom_events.md
  _docs/_hidden/archive_docs/windows_universal/analytics/logging_purchases.md
  _docs/_hidden/archive_docs/windows_universal/analytics/setting_custom_attributes.md
  _docs/_hidden/archive_docs/windows_universal/analytics/setting_user_ids.md
  _docs/_hidden/archive_docs/windows_universal/analytics/tracking_sessions.md
  _docs/_hidden/archive_docs/windows_universal/changelog.md
  _docs/_hidden/archive_docs/windows_universal/initial_sdk_setup.md
  _docs/_hidden/archive_docs/windows_universal/push_notifications.md
  _docs/_hidden/misc_reference/scim_api_appendix.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/analytics.md
  _docs/_partners/data_and_infrastructure_agility/analytics/merkury.md
  _docs/_partners/home.md
  _docs/_partners/message_orchestration/attribution/branch/branch_for_attribution.md
  _docs/_partners/message_orchestration/attribution/singular.md
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/redshift.md
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/snowflake.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/best_practices/prep_guide.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/generations.md
  _docs/_user_guide/message_building_by_channel/push.md
  _docs/_user_guide/message_building_by_channel/push/best_practices.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/creating_custom_opt-in_prompts.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/detailed_push_preferences.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/push_primer_messages.md
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
  assets/img_archive/or_operator_segment.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#5011 Note about audience limits and a/b tests
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
Labels: cla-signed

#5013 BD-1971: Update references to Samoa time as "one of the first" instead of "the first" time zone
  _docs/_user_guide/intelligence/faqs.md
  _docs/_user_guide/intelligence/intelligent_timing.md
Labels: cla-signed

#5014 BD-1972: Add info about changing control variant percentage after launching Canvas
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
Labels: cla-signed

#5006 Update Currents events for Currents partners, audit event dictionary
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#5021 Standardized rendering of "email"
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/campaign_connector.md
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
Labels: cla-signed

#5008 Feature flags FAQ
  _docs/_developer_guide/platform_wide/feature_flags.md
  _docs/_developer_guide/platform_wide/feature_flags/about.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
  _docs/_developer_guide/platform_wide/feature_flags/faq.md
  _docs/_developer_guide/platform_wide/feature_flags/use_cases.md
Labels: cla-signed

#5022 BD-1977: Currents release note fix
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023/2_7_23.md
Labels: cla-signed

#5024 Remove EA banner for /users/merge endpoint
  _docs/_api/endpoints/user_data/post_users_merge.md
Labels: cla-signed

#4983 WhatsApp API object documentation - MERGE 3/15
  _docs/_api/endpoints/messaging/send_messages/post_send_messages.md
  _docs/_api/objects_filters.md
  _docs/_api/objects_filters/messaging/android_object.md
  _docs/_api/objects_filters/messaging/content_cards_object.md
  _docs/_api/objects_filters/messaging/email_object.md
  _docs/_api/objects_filters/messaging/whats_app_object.md
Labels: cla-signed

#4934 WhatsApp GA
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md
  _docs/_user_guide/message_building_by_channel.md
  _docs/_user_guide/message_building_by_channel/whatsapp.md
  _docs/_user_guide/message_building_by_channel/whatsapp/create.md
  _docs/_user_guide/message_building_by_channel/whatsapp/faqs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/opt-ins_and_opt-outs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/overview.md
  _docs/_user_guide/message_building_by_channel/whatsapp/quick_replies.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign_analytics.md
  _includes/campaign_analytics.md
  assets/img/whatsapp/whatsapp2.png
  assets/img/whatsapp/whatsapp3.png
  assets/img/whatsapp/whatsapp6.png
  assets/img/whatsapp/whatsapp7.png
  assets/img/whatsapp/whatsapp8.png
Labels: cla-signed

#5020 New create catalog in browser feature
  _docs/_user_guide/personalization_and_dynamic_content/catalogs.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  assets/img_archive/add_catalog_fields.png
  assets/img_archive/add_catalog_items.png
  assets/img_archive/catalog_new_name.png
  assets/img_archive/create_catalog_option.png
  assets/img_archive/in_browser_catalog.png
  assets/img_archive/update_catalog_step1.png
  assets/img_archive/update_catalog_step2.png
Labels: cla-signed

#5025 Add picture links to FB partner page
  _docs/_partners/message_orchestration/additional_channels/retargeting/facebook.md
Labels: cla-signed

#5001 Drag & Drop Email Preference Center EA
  _docs/_hidden/private_betas/preference_center.md
  assets/img/preference_center/preference_center1.png
  assets/img/preference_center/preference_center10.png
  assets/img/preference_center/preference_center11.png
  assets/img/preference_center/preference_center2.png
  assets/img/preference_center/preference_center3.png
  assets/img/preference_center/preference_center4.png
  assets/img/preference_center/preference_center5.png
  assets/img/preference_center/preference_center6.png
  assets/img/preference_center/preference_center7.png
  assets/img/preference_center/preference_center8.png
  assets/img/preference_center/preference_center9.png
Labels: cla-signed

#4976 GlobalLink Translation PR
  _lang/fr/_user_guide/predictive_suite/predictive_churn/prediction_analytics/prediction_quality.md
  _lang/fr/_user_guide/predictive_suite/predictive_purchases/creating_a_purchase_prediction.md
  _lang/fr/_user_guide/predictive_suite/predictive_purchases/prediction_analytics.md
Labels: cla-signed

#4979 GlobalLink Translation PR
  _lang/fr/_api/data_retention.md
  _lang/fr/_home/dp-technical-assistance.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
Labels: cla-signed

#5026 BD-1979: Update time saving details
  _docs/_api/objects_filters/user_attributes_object.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
Labels: cla-signed

#5000 GlobalLink Translation PR
  _lang/fr/_developer_guide/platform_integration_guides/android/content_cards/customization/custom_styling.md
  _lang/fr/_developer_guide/platform_integration_guides/android/content_cards/customization/default_feed.md
  _lang/fr/_developer_guide/platform_integration_guides/android/content_cards/customization/key_value_pairs.md
  _lang/fr/_developer_guide/platform_integration_guides/flutter/flutter_sdk_integration.md
  _lang/fr/_developer_guide/platform_integration_guides/web/push_notifications/safari_mobile_push.md
  _lang/fr/_developer_guide/platform_wide/feature_flags.md
  _lang/fr/_docs_pages/cla.md
  _lang/fr/_partners/data_and_infrastructure_agility.md
  _lang/fr/_partners/data_and_infrastructure_agility/business_intelligence.md
  _lang/fr/_partners/data_and_infrastructure_agility/business_intelligence/sisu_data.md
  _lang/fr/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _lang/fr/_partners/data_and_infrastructure_agility/customer_data_platform/actioniq.md
  _lang/fr/_partners/data_and_infrastructure_agility/workflow_automation.md
  _lang/fr/_partners/data_and_infrastructure_agility/workflow_automation/airbyte.md
  _lang/fr/_partners/data_and_infrastructure_agility/workflow_automation/flywheel.md
  _lang/fr/_partners/data_and_infrastructure_agility/workflow_automation/hightouch.md
  _lang/fr/_partners/data_and_infrastructure_agility/workflow_automation/hightouch/hightouch.md
  _lang/fr/_partners/data_and_infrastructure_agility/workflow_automation/hightouch/hightouch_personalization_api.md
  _lang/fr/_partners/data_and_infrastructure_agility/workflow_automation/mozart_data.md
  _lang/fr/_partners/home.md
  _lang/fr/_partners/message_orchestration.md
  _lang/fr/_partners/message_orchestration/channel_extensions.md
  _lang/fr/_partners/message_orchestration/channel_extensions/email_templates.md
  _lang/fr/_partners/message_orchestration/channel_extensions/email_templates/sageflo.md
  _lang/fr/_partners/message_orchestration/channel_extensions/loyalty.md
  _lang/fr/_partners/message_orchestration/channel_extensions/loyalty/nift.md
  _lang/fr/_partners/message_personalization.md
  _lang/fr/_partners/message_personalization/dynamic_content.md
  _lang/fr/_partners/message_personalization/dynamic_content/komo.md
  _lang/fr/_partners/message_personalization/localization.md
  _lang/fr/_partners/message_personalization/localization/phrase.md
  _lang/fr/_partners/message_personalization/location.md
  _lang/fr/_partners/message_personalization/location/loplat.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/attribute_triggers.md
  _lang/fr/_user_guide/engagement_tools/campaigns/ideas_and_strategies/campaigns_in_multiple_languages.md
  _lang/fr/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md
  _lang/fr/_user_guide/engagement_tools/canvas/create_a_canvas/content-cards_in_canvas.md
  _lang/fr/_user_guide/engagement_tools/segments.md
  _lang/fr/_user_guide/engagement_tools/segments/location_targeting.md
  _lang/fr/_user_guide/engagement_tools/segments/regex.md
  _lang/fr/_user_guide/engagement_tools/segments/user_lookup.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/creative_details/slideup.md
  _lang/fr/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md
  _lang/fr/_user_guide/onboarding_with_braze/email_setup.md
  _lang/fr/_user_guide/onboarding_with_braze/email_setup/authentication.md
  _lang/fr/_user_guide/onboarding_with_braze/email_setup/consent_and_address_collection.md
  _lang/fr/_user_guide/onboarding_with_braze/email_setup/deliverability_pitfalls_and_spam_traps.md
  _lang/fr/_user_guide/onboarding_with_braze/email_setup/email_validation.md
  _lang/fr/_user_guide/onboarding_with_braze/email_setup/import_your_email_list.md
  _lang/fr/_user_guide/onboarding_with_braze/email_setup/ip_warming.md
  _lang/fr/_user_guide/onboarding_with_braze/email_setup/setting_up_ips_and_domains.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/promotion_codes.md
Labels: cla-signed

#5027 Adjust details styling
  _plugins/details_tag.rb
  assets/css/_content.scss
  assets/css/main.scss
Labels: cla-signed

#5015 GlobalLink Translation PR
  _docs/_docs_pages/cla.md
  _lang/fr/_user_guide/message_building_by_channel/email/preference_center/preference_center_via_api.md
  _lang/fr/_user_guide/message_building_by_channel/email/reporting_and_analytics/email_reporting.md
  _lang/fr/_user_guide/message_building_by_channel/email/templates.md
  _lang/fr/_user_guide/message_building_by_channel/email/templates/email_template.md
  _lang/fr/_user_guide/message_building_by_channel/email/templates/link_template.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/about.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/dark-mode.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/testing.md
  _lang/fr/_user_guide/message_building_by_channel/push.md
  _lang/fr/_user_guide/message_building_by_channel/push/advanced_push_options/push_stories.md
  _lang/fr/_user_guide/message_building_by_channel/push/android.md
  _lang/fr/_user_guide/message_building_by_channel/push/best_practices.md
  _lang/fr/_user_guide/message_building_by_channel/push/best_practices/conversion_tracking.md
  _lang/fr/_user_guide/message_building_by_channel/push/ios.md
  _lang/fr/_user_guide/message_building_by_channel/push/push_registration.md
  _lang/fr/_user_guide/message_building_by_channel/sms/best_practices/opt-ins.md
  _lang/fr/_user_guide/message_building_by_channel/sms/keywords.md
  _lang/fr/_user_guide/message_building_by_channel/sms/mms/about_mms.md
  _lang/fr/_user_guide/message_building_by_channel/sms/non_native.md
  _lang/fr/_user_guide/message_building_by_channel/sms/phone_numbers/user_phone_numbers.md
  _lang/fr/_user_guide/message_building_by_channel/webhooks.md
  _lang/fr/_user_guide/onboarding_with_braze/email_setup.md
  _lang/fr/_user_guide/onboarding_with_braze/sms_setup/about_sms.md
  _lang/fr/_user_guide/personalization_and_dynamic_content.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/catalogs.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/connected_content.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/connected_content/aborting_connected_content.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/connected_content/connected_content_retries.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/deep_linking_to_in-app_content.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/liquid.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/liquid/aborting_messages.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/liquid/conditional_logic.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/liquid/filters.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/liquid/setting_default_values.md
  _lang/fr/_user_guide/predictive_suite/predictive_churn.md
  _lang/fr/_user_guide/predictive_suite/predictive_purchases.md
Labels: cla-signed

#5016 GlobalLink Translation PR
  _lang/fr/_user_guide/data_and_analytics/tracking/segment_analytics_tracking.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection/language_codes.md
  _lang/fr/_user_guide/engagement_tools.md
  _lang/fr/_user_guide/engagement_tools/campaigns.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/api_triggered_delivery.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/time_based_campaign.md
  _lang/fr/_user_guide/engagement_tools/campaigns/ideas_and_strategies.md
  _lang/fr/_user_guide/engagement_tools/campaigns/ideas_and_strategies/active_user_campaigns.md
  _lang/fr/_user_guide/engagement_tools/campaigns/managing_campaigns.md
  _lang/fr/_user_guide/engagement_tools/campaigns/managing_campaigns/search_campaigns.md
  _lang/fr/_user_guide/engagement_tools/campaigns/testing_and_more.md
  _lang/fr/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md
  _lang/fr/_user_guide/engagement_tools/canvas/create_a_canvas.md
  _lang/fr/_user_guide/engagement_tools/canvas/create_a_canvas/advancement.md
  _lang/fr/_user_guide/engagement_tools/canvas/create_a_canvas/content-cards_in_canvas.md
  _lang/fr/_user_guide/engagement_tools/canvas/create_a_canvas/exit_criteria.md
  _lang/fr/_user_guide/engagement_tools/canvas/ideas_and_strategies.md
  _lang/fr/_user_guide/engagement_tools/canvas/managing_canvases/archiving_canvases.md
  _lang/fr/_user_guide/engagement_tools/canvas/testing_canvases.md
  _lang/fr/_user_guide/engagement_tools/canvas/testing_canvases/sending_test_canvases.md
  _lang/fr/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md
  _lang/fr/_user_guide/engagement_tools/locations_and_geofences/location_tracking.md
  _lang/fr/_user_guide/engagement_tools/segments.md
  _lang/fr/_user_guide/engagement_tools/templates_and_media.md
  _lang/fr/_user_guide/engagement_tools/templates_and_media/media_library.md
  _lang/fr/_user_guide/intelligence/ai_copywriting.md
  _lang/fr/_user_guide/intelligence/intelligent_channel.md
  _lang/fr/_user_guide/intelligence/intelligent_selection.md
  _lang/fr/_user_guide/intelligence/intelligent_timing.md
  _lang/fr/_user_guide/message_building_by_channel.md
  _lang/fr/_user_guide/message_building_by_channel/content_cards/create.md
  _lang/fr/_user_guide/message_building_by_channel/content_cards/create/card_creation.md
  _lang/fr/_user_guide/message_building_by_channel/content_cards/creative_details.md
  _lang/fr/_user_guide/message_building_by_channel/content_cards/migrating_from_news_feed.md
  _lang/fr/_user_guide/message_building_by_channel/email.md
  _lang/fr/_user_guide/message_building_by_channel/email/css_inline.md
  _lang/fr/_user_guide/message_building_by_channel/email/drag_and_drop.md
  _lang/fr/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
  _lang/fr/_user_guide/message_building_by_channel/email/gmail_promotions_tab.md
  _lang/fr/_user_guide/message_building_by_channel/email/inbox_vision.md
  _lang/fr/_user_guide/message_building_by_channel/email/preference_center.md
Labels: cla-signed

#5017 GlobalLink Translation PR
  _lang/fr/_api/endpoints/messaging/live_activity.md
  _lang/fr/_api/endpoints/messaging/live_activity/update.md
  _lang/fr/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  _lang/fr/_api/endpoints/preference_center.md
  _lang/fr/_api/endpoints/preference_center/get_create_url_preference_center.md
  _lang/fr/_api/endpoints/preference_center/get_list_preference_center.md
  _lang/fr/_api/endpoints/preference_center/get_view_details_preference_center.md
  _lang/fr/_api/endpoints/preference_center/post_create_preference_center.md
  _lang/fr/_api/endpoints/preference_center/put_update_preference_center.md
  _lang/fr/_developer_guide/platform_integration_guides/android/push_notifications/fireos/testing.md
  _lang/fr/_developer_guide/platform_integration_guides/ios/push_notifications/testing.md
  _lang/fr/_developer_guide/platform_integration_guides/sdk_changelogs.md
  _lang/fr/_developer_guide/platform_integration_guides/swift.md
  _lang/fr/_developer_guide/platform_integration_guides/swift/live_activities.md
  _lang/fr/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md
  _lang/fr/_developer_guide/platform_integration_guides/web/in-app_messaging/customization.md
  _lang/fr/_developer_guide/platform_integration_guides/web/push_notifications/safari_mobile_push.md
  _lang/fr/_developer_guide/platform_integration_guides/xamarin/analytics.md
  _lang/fr/_developer_guide/platform_integration_guides/xamarin/changelog.md
  _lang/fr/_developer_guide/platform_integration_guides/xamarin/inapp_messages.md
  _lang/fr/_developer_guide/platform_integration_guides/xamarin/initial_sdk_setup.md
  _lang/fr/_developer_guide/platform_integration_guides/xamarin/news_feed.md
  _lang/fr/_help/release_notes/2022/7_26_22.md
  _lang/fr/_hidden/other/credit_ratios.md
  _lang/fr/_hidden/private_betas/canvas_approval.md
  _lang/fr/_hidden/private_betas/shopify_backfil.md
  _lang/fr/_hidden/private_betas/tiktok.md
  _lang/fr/_partners/canvas_steps/facebook_audience_sync.md
  _lang/fr/_partners/data_and_infrastructure_agility/workflow_automation/hightouch/hightouch_personalization_api.md
  _lang/fr/_user_guide/administrative/access_braze.md
  _lang/fr/_user_guide/administrative/access_braze/getting_your_account.md
  _lang/fr/_user_guide/administrative/access_braze/portal.md
  _lang/fr/_user_guide/administrative/app_settings.md
  _lang/fr/_user_guide/administrative/app_settings/developer_console.md
  _lang/fr/_user_guide/administrative/app_settings/developer_console/message_activity_log_tab.md
  _lang/fr/_user_guide/administrative/app_settings/manage_app_group.md
  _lang/fr/_user_guide/administrative/app_settings/manage_app_group/app_group_management.md
  _lang/fr/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  _lang/fr/_user_guide/administrative/company_settings.md
  _lang/fr/_user_guide/administrative/company_settings/notification_preferences.md
  _lang/fr/_user_guide/administrative/company_settings/security_settings.md
  _lang/fr/_user_guide/administrative/manage_your_braze_users.md
  _lang/fr/_user_guide/data_and_analytics/analytics.md
  _lang/fr/_user_guide/data_and_analytics/braze_currents/transferring_data_to_redshift.md
  _lang/fr/_user_guide/data_and_analytics/export_braze_data.md
  _lang/fr/_user_guide/data_and_analytics/export_braze_data/export_campaign_results_data.md
  _lang/fr/_user_guide/data_and_analytics/export_braze_data/exporting_app_usage_data.md
  _lang/fr/_user_guide/data_and_analytics/export_braze_data/exporting_revenue_data.md
  _lang/fr/_user_guide/data_and_analytics/reporting.md
  _lang/fr/_user_guide/data_and_analytics/reporting/campaign_analytics.md
  _lang/fr/_user_guide/data_and_analytics/reporting/global_control_group_reporting.md
  _lang/fr/_user_guide/data_and_analytics/tracking.md
  _lang/fr/_user_guide/data_and_analytics/tracking/email_tracking.md
  _lang/fr/_user_guide/data_and_analytics/tracking/influenced_opens.md
Labels: cla-signed

#5028 Catalog updates API
  _docs/_api/api_limits.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/delete_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/patch_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/post_create_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/delete_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/get_catalog_item_details.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/get_catalog_items_details_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/patch_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/delete_catalog.md
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/get_list_catalogs.md
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md
  _includes/rate_limits.md
Labels: cla-signed

#5030 Add CDI as option to upload user data instead of CSV
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Labels: cla-signed

#5032 BD-1981: Update WA credit ratios doc
  _docs/_hidden/other/credit_ratios.md
Labels: cla-signed

#5031 Adjust left nav expand level
  assets/js/developer_nav.js
Labels: cla-signed

#5036 Fix heading level
  _docs/_hidden/private_betas/pinterest_audience_sync.md
Labels: cla-signed

#5034 Update opt-ins_and_opt-outs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/opt-ins_and_opt-outs.md
Labels: cla-signed

#5035 Update credit_ratios.md
  _docs/_hidden/other/credit_ratios.md
Labels: cla-signed

#4891 Localization docs
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_for_currents.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/campaigns_in_multiple_languages.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/localizing_a_campaign.md
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies.md
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/localization.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#5039 Fix release note year
  _docs/_help/release_notes/2023.md
Labels: cla-signed

#5037 Endpoint updates pt. 2
  _docs/_api/endpoints/export/custom_events/get_custom_events.md
  _docs/_api/endpoints/export/custom_events/get_custom_events_analytics.md
  _docs/_api/endpoints/export/kpi/get_kpi_daily_new_users_date.md
  _docs/_api/endpoints/export/kpi/get_kpi_dau_date.md
  _docs/_api/endpoints/export/kpi/get_kpi_mau_30_days.md
  _docs/_api/endpoints/export/kpi/get_kpi_uninstalls_date.md
  _docs/_api/endpoints/export/news_feed/get_news_feed_card_analytics.md
  _docs/_api/endpoints/export/news_feed/get_news_feed_card_details.md
  _docs/_api/endpoints/export/news_feed/get_news_feed_cards.md
  _docs/_api/endpoints/export/purchases/get_list_product_id.md
  _docs/_api/endpoints/export/segments/get_segment.md
  _docs/_api/endpoints/export/segments/get_segment_analytics.md
  _docs/_api/endpoints/export/segments/get_segment_details.md
  _docs/_api/endpoints/export/sessions/get_sessions_analytics.md
  _docs/_api/endpoints/export/user_data/post_users_global_control_group.md
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_api/endpoints/scim/delete_existing_dashboard_user.md
  _docs/_api/endpoints/scim/get_search_existing_dashboard_user.md
  _docs/_api/endpoints/scim/get_see_user_account_information.md
  _docs/_api/endpoints/scim/put_update_existing_user_account.md
  _docs/_api/endpoints/sms/get_query_invalid_numbers.md
  _docs/_api/endpoints/templates/content_blocks_templates/get_list_email_content_blocks.md
  _docs/_api/endpoints/templates/content_blocks_templates/get_see_email_content_blocks_information.md
  _docs/_api/endpoints/templates/content_blocks_templates/post_create_email_content_block.md
  _docs/_api/endpoints/templates/content_blocks_templates/post_update_content_block.md
  _docs/_api/endpoints/user_data.md
  _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_remove.md
  _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_rename.md
  _docs/_api/endpoints/user_data/post_user_alias.md
  _docs/_api/endpoints/user_data/post_user_delete.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_api/endpoints/user_data/post_users_alias_update.md
  _docs/_api/endpoints/user_data/post_users_merge.md
  _docs/_api/home.md
Labels: cla-signed

#5047 BD-1983: Update full-screen to fullscreen
  _docs/_developer_guide/platform_integration_guides/roku/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/integration.md
  _docs/_help/release_notes/2017/july.md
  _docs/_help/release_notes/2019/august.md
  _docs/_hidden/archive_docs/generations.md
  _docs/_hidden/archive_docs/previous_in-app_message_generations.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/about.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/best_practices/prep_guide.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/fullscreen.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/push_primer_messages.md
  _docs/_user_guide/onboarding_with_braze/web_sdk.md
Labels: cla-signed

#5046 BD-1980: Add alert to mParticle data types section
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle.md
Labels: cla-signed

#5045 Update credit ratios permalink
  _docs/_hidden/other/credit_ratios.md
Labels: cla-signed

#5048 Updates to sends campaign analytics metric
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/message_building_by_channel/email/reporting_and_analytics/analytics_glossary.md
Labels: cla-signed

#5053 BD-1988, BD-1985, Updates to Currents
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#5058 Leftover Deploy Pt. 2 - March 17, 2023
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed, Deploy

#5054 Update localizing_a_campaign.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/localizing_a_campaign.md
Labels: cla-signed

#5052 BD-1990: Clarify Azure export step
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/microsoft_azure_blob_storage_for_currents.md
Labels: cla-signed

#5055 BD-1984: Update empty Content Card feed help article with Card Creation
  _docs/_help/help_articles/content_cards/empty_content_card_feed.md
Labels: cla-signed

#5019 BD-1976: Custom SQL in query builder EA
  _docs/_user_guide/data_and_analytics/query_builder/custom_sql.md
Labels: cla-signed

#5067 BD-1987: Clarify merge behavior for /users/identify and /users/merge
  _docs/_api/endpoints/user_data/post_user_identify.md
  _docs/_api/endpoints/user_data/post_users_merge.md
Labels: cla-signed

#5066 Add additional ID type support
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/overview.md
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/redshift.md
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/snowflake.md
Labels: cla-signed

#5068 GlobalLink Translation PR
  _lang/fr/_partners/message_personalization.md
  _lang/fr/_partners/message_personalization/dynamic_content.md
  _lang/fr/_partners/message_personalization/dynamic_content/amazon_personalize.md
  _lang/fr/_partners/message_personalization/dynamic_content/amazon_personalize/amazon_personalize.md
  _lang/fr/_partners/message_personalization/dynamic_content/amazon_personalize/workshop.md
  _lang/fr/_partners/message_personalization/dynamic_content/certona.md
  _lang/fr/_partners/message_personalization/dynamic_content/dynamic_yield.md
  _lang/fr/_partners/message_personalization/dynamic_content/judo.md
  _lang/fr/_partners/message_personalization/dynamic_content/komo.md
  _lang/fr/_partners/message_personalization/dynamic_content/liftigniter.md
  _lang/fr/_partners/message_personalization/dynamic_content/movable_ink.md
  _lang/fr/_partners/message_personalization/dynamic_content/peak.md
  _lang/fr/_partners/message_personalization/dynamic_content/playable.md
  _lang/fr/_partners/message_personalization/dynamic_content/sheetlabs.md
  _lang/fr/_partners/message_personalization/dynamic_content/worthy.md
  _lang/fr/_partners/message_personalization/dynamic_content/wsc_sports.md
  _lang/fr/_partners/message_personalization/dynamic_content/wyng.md
  _lang/fr/_partners/message_personalization/localization.md
  _lang/fr/_partners/message_personalization/localization/crowdin.md
  _lang/fr/_partners/message_personalization/localization/lokalise.md
  _lang/fr/_partners/message_personalization/localization/phrase.md
  _lang/fr/_partners/message_personalization/localization/transifex.md
  _lang/fr/_partners/message_personalization/location.md
  _lang/fr/_partners/message_personalization/location/accuweather.md
  _lang/fr/_partners/message_personalization/location/bluedot.md
  _lang/fr/_partners/message_personalization/location/foursquare.md
  _lang/fr/_partners/message_personalization/location/gimbal.md
  _lang/fr/_partners/message_personalization/location/loplat.md
  _lang/fr/_partners/message_personalization/location/radar.md
  _lang/fr/_partners/third_party_liability.md
  _lang/fr/_user_guide/administrative/access_braze/single_sign_on/okta.md
  _lang/fr/_user_guide/administrative/access_braze/single_sign_on/onelogin.md
  _lang/fr/_user_guide/administrative/access_braze/single_sign_on/set_up.md
  _lang/fr/_user_guide/administrative/app_settings/developer_console/message_activity_log_tab.md
  _lang/fr/_user_guide/administrative/company_settings/security_settings.md
  _lang/fr/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md
  _lang/fr/_user_guide/administrative/manage_your_braze_users/user_permissions.md
  _lang/fr/_user_guide/data_and_analytics.md
  _lang/fr/_user_guide/data_and_analytics/analytics.md
  _lang/fr/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _lang/fr/_user_guide/data_and_analytics/custom_data.md
  _lang/fr/_user_guide/data_and_analytics/data_points.md
  _lang/fr/_user_guide/data_and_analytics/query_builder.md
  _lang/fr/_user_guide/data_and_analytics/reporting/report_builder.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _lang/fr/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
  _lang/fr/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/winning_path.md
  _lang/fr/_user_guide/engagement_tools/locations_and_geofences/geofence_configuration.md
  _lang/fr/_user_guide/engagement_tools/locations_and_geofences/location_tracking.md
  _lang/fr/_user_guide/engagement_tools/segments/segmentation_filters.md
  _lang/fr/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/create.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _lang/fr/_user_guide/message_building_by_channel/sms/phone_numbers/10dlc.md
  _lang/fr/_user_guide/onboarding_with_braze/data_points.md
  _lang/fr/_user_guide/onboarding_with_braze/email_setup/ssl.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/connected_content/user_profile_fields_connected_content.md
Labels: cla-signed

#5073 Add DallE ownership note
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
Labels: cla-signed

#5076 Shopify Historical Backfill GA
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_backfill.md
Labels: cla-signed

#5077 BD-1992: Update AppsFlyer Android and Unity snippets
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
Labels: cla-signed

#5081 Issue #5056 - Update external_id_remove response
  _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_remove.md
Labels: cla-signed

#5083 Partner tile audit
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/channel_extensions.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates.md
  _docs/_partners/message_personalization/location.md
Labels: cla-signed

#5040 Edits for endpoint docs - Pt. 1
  _docs/_api/endpoints/export/campaigns/get_campaign_analytics.md
  _docs/_api/endpoints/export/campaigns/get_campaign_details.md
  _docs/_api/endpoints/export/campaigns/get_campaigns.md
  _docs/_api/endpoints/export/campaigns/get_send_analytics.md
  _docs/_api/endpoints/export/canvas/get_canvas_analytics.md
  _docs/_api/endpoints/export/canvas/get_canvas_analytics_summary.md
  _docs/_api/endpoints/export/canvas/get_canvas_details.md
  _docs/_api/endpoints/export/canvas/get_canvases.md
  _docs/_api/endpoints/messaging/send_messages/post_create_send_ids.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
  _docs/_api/endpoints/preference_center/get_create_url_preference_center.md
  _docs/_api/endpoints/preference_center/get_list_preference_center.md
  _docs/_api/endpoints/preference_center/get_view_details_preference_center.md
  _docs/_api/endpoints/preference_center/post_create_preference_center.md
  _docs/_api/endpoints/preference_center/put_update_preference_center.md
  _docs/_api/endpoints/subscription_groups/get_list_user_subscription_group_status.md
  _docs/_api/endpoints/subscription_groups/get_list_user_subscription_groups.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
  _docs/_api/endpoints/templates/email_templates/get_list_email_templates.md
  _docs/_api/endpoints/templates/email_templates/get_see_email_template_information.md
  _docs/_api/endpoints/templates/email_templates/post_create_email_template.md
  _docs/_api/endpoints/templates/email_templates/post_update_email_template.md
Labels: cla-signed

#5084 Remove version references from GPT
  _docs/_user_guide/intelligence/ai_copywriting.md
Labels: cla-signed

#5087 Update identifier_types.md
  _docs/_api/identifier_types.md
Labels: cla-signed

#5089 Hide Device & Carriers doc
  _docs/_hidden/other/devices_and_carriers.md
  _docs/_user_guide/data_and_analytics/reporting.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#5090 BD-1998: Credit Ratios Doc with Meta Updates
  _docs/_hidden/other/credit_ratios.md
Labels: cla-signed

#5086 SDK-3561
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize/html_in-app_messages.md
Labels: cla-signed

#5091 BD-1995: Add Google updates to google audience syncing, removing lookalike audiences
  _docs/_partners/canvas_steps/google_audience_sync.md
Labels: cla-signed

#5097 BD-1996: Add caveat for action paths and in-app messages
  _docs/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md
Labels: cla-signed

#5096 BD-2001: Add FAQ to DND IAM on segmenting based on button clicks
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
Labels: cla-signed

#5095 BD-2004: Fix link
  _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
Labels: cla-signed

#5098 BD-2005: Update Content Card composer images with new preview design
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  assets/img/cc_pin_to_top.png
  assets/img/content_card_compose.png
Labels: cla-signed

#5099 BD-1997: Update multi-criteria segmentation example
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
  assets/img_archive/nca_multi_criteria.png
Labels: cla-signed

#5093 BD-2000: Add examples for User Update JSON editor
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
Labels: cla-signed

#5100 BD-2007: Update alert for campaign approval
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_approval.md
Labels: cla-signed

#5101 BD-2002: Remove devices and carriers crumbs
  _docs/_hidden/private_betas/navigation.md
Labels: cla-signed

#5106 Update bundle jekyll version and algolia config
  Gemfile
  Gemfile.lock
  _config.yml
Labels: cla-signed

#5108 Add WhatsApp tile to partner page
  _docs/_partners/home.md
Labels: cla-signed

#5071 BD-1986: New article for message_extras Liquid tag
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
Labels: cla-signed

#5104 BD-2006: Add troubleshooting scenario for FB Audience sync
  _docs/_partners/canvas_steps/facebook_audience_sync.md
Labels: cla-signed

#5110 BD-2010: Add new SSS Handbook
  _docs/_hidden/other/handbooks.md
  assets/download_file/Braze_Success_and_Support_Services_Handbook_24.pdf
Labels: cla-signed

#5109 Leftover Deploy Pt. 2 - March 24, 2023
  Gemfile
  Gemfile.lock
  _config.yml
  _docs/_hidden/other/handbooks.md
  _docs/_partners/canvas_steps/facebook_audience_sync.md
  _docs/_partners/home.md
  _docs/_user_guide/message_building_by_channel/whatsapp/overview.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
  assets/download_file/Braze_Success_and_Support_Services_Handbook_24.pdf
Labels: cla-signed, Deploy

#5111 Make a note that we need special configuration for other DataDog sites
  _docs/_partners/data_and_infrastructure_agility/analytics/datadog.md
Labels: cla-signed

#5112 Merge Master back to develop
  _docs/_partners/data_and_infrastructure_agility/analytics/datadog.md
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
Labels: cla-signed

#4953 [SDK-3024] Swift Docs - Push Notifications
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/push_story.md
  _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
  _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/behavior_on_click.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/setting_delegates.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/other_sdk_customizations.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/customization.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/customization/action_buttons.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/customization/advanced_settings.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/customization/badges.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/customization/custom_sounds.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/customization/ignoring_internal_push.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/customization/rich_notifications.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/push_primer.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/push_story.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/silent_push_notifications.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/testing.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/unit_tests.md
  _docs/_developer_guide/platform_integration_guides/xamarin/initial_sdk_setup.md
  _docs/_user_guide/administrative/app_settings/developer_console/message_activity_log_tab.md
  _docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_stories.md
  _docs/_user_guide/onboarding_with_braze/integration.md
  _lang/fr/_developer_guide/platform_integration_guides/swift.md
  _lang/fr/_developer_guide/platform_integration_guides/swift/push_notifications/integration.md
  assets/img/swift/push_story/manual1.png
  assets/img/swift/push_story/notificationcontentextension_plist.png
  assets/img/swift/push_story/spm1.png
  assets/img/swift/push_story/spm2.png
  assets/img_archive/AppleProvisioningOptions.png
  assets/img_archive/Enable_push_capabilities.png
  assets/img_archive/background_mode.png
  assets/img_archive/ios-notification-category.png
  assets/img_archive/push_cert_gen.png
Labels: cla-signed

#5107 Update to Canvas approval
  _docs/_hidden/private_betas/canvas_approval.md
Labels: cla-signed

#5113 Updates prerequisites
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Labels: cla-signed

#5117 BD-2012: Add SparkPost to key-value pairs
  _docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
Labels: cla-signed

#5115 Update to Content Card Abort
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#5092 BD-1991: add message_extras to Currents events - MERGE 3/28
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#5118 BD-2000 pt2: Replace app_id and subscription_group_id with variables
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
Labels: cla-signed

#5120 BD-2018: Add domain requirements to custom domains
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
Labels: cla-signed

#5119 BD-2014: Add abort events to currents events and glossary
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#5121 BD-2015 Add additional exception events to Canvas exit criteria
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/exit_criteria.md
Labels: cla-signed

#5122 BD-2017: Update field type
  _docs/_api/endpoints/export/canvas/get_canvas_details.md
Labels: cla-signed

#5060 Josh Updates (TK->JM)
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
Labels: cla-signed

#5123 Update react_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Labels: cla-signed

#5128 Update message_extras.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
Labels: cla-signed

#5124 Expanding the live_activity/update endpoint docs with crucial Apple d…
  _docs/_api/endpoints/messaging/live_activity/update.md
Labels: cla-signed

#5131 BD-2022: Edit rate limit section for /messages/send
  _docs/_api/endpoints/messaging/send_messages/post_send_messages.md
  _includes/rate_limits.md
Labels: cla-signed

#5132 BD-2023: Unify glossary and IAM reporting page for unique impressions
  _includes/campaign_analytics.md
Labels: cla-signed

#5133 Update sms_subscription_group.md
  _docs/_user_guide/message_building_by_channel/sms/sms_subscription_group.md
Labels: cla-signed

#5139 GlobalLink Translation PR
  _lang/fr/_user_guide/data_and_analytics/your_reports/retention_reports.md
  _lang/fr/_user_guide/data_and_analytics/your_reports/viewing_and_understanding_segment_data.md
  _lang/fr/_user_guide/engagement_tools.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/conversion_events.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/api_triggered_delivery.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/campaign_calendar.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/scheduled_delivery.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/time_based_campaign.md
  _lang/fr/_user_guide/engagement_tools/campaigns/getting_started/understanding_campaign_status.md
  _lang/fr/_user_guide/engagement_tools/campaigns/ideas_and_strategies.md
  _lang/fr/_user_guide/engagement_tools/campaigns/ideas_and_strategies/active_user_campaigns.md
  _lang/fr/_user_guide/engagement_tools/campaigns/ideas_and_strategies/add_to_calendar_links.md
  _lang/fr/_user_guide/engagement_tools/campaigns/ideas_and_strategies/best_practices.md
  _lang/fr/_user_guide/engagement_tools/campaigns/ideas_and_strategies/install_attribution.md
  _lang/fr/_user_guide/engagement_tools/campaigns/ideas_and_strategies/new_features.md
  _lang/fr/_user_guide/engagement_tools/campaigns/ideas_and_strategies/zoom.md
  _lang/fr/_user_guide/engagement_tools/campaigns/managing_campaigns.md
  _lang/fr/_user_guide/engagement_tools/campaigns/managing_campaigns/archiving_campaigns.md
  _lang/fr/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_approval.md
Labels: cla-signed

#5140 GlobalLink Translation PR
  _lang/fr/_user_guide/engagement_tools/locations_and_geofences/faqs.md
  _lang/fr/_user_guide/engagement_tools/locations_and_geofences/geofence_configuration.md
  _lang/fr/_user_guide/engagement_tools/news_feed/news_feed_analytics_and_retargeting_data.md
  _lang/fr/_user_guide/engagement_tools/news_feed/news_feed_categories.md
  _lang/fr/_user_guide/engagement_tools/news_feed/news_feed_use_cases.md
  _lang/fr/_user_guide/engagement_tools/segments/beacon_support.md
  _lang/fr/_user_guide/engagement_tools/segments/location_targeting.md
  _lang/fr/_user_guide/engagement_tools/segments/regex.md
  _lang/fr/_user_guide/engagement_tools/templates_and_media/archive.md
  _lang/fr/_user_guide/engagement_tools/templates_and_media/content_blocks.md
  _lang/fr/_user_guide/engagement_tools/templates_and_media/duplicate.md
  _lang/fr/_user_guide/engagement_tools/testing/conversion_correlation.md
Labels: cla-signed
