Repository braze-inc/braze-docs, pull requests merged in 2023-05, with the labels that each got.

#5339 [CO-1493] Mention that schema generation uses sampling
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
Labels: cla-signed

#5340 Audit mentions of endpoints
  _docs/_help/help_articles/push/push_token_migration.md
  _docs/_hidden/archive_docs/ios_14.md
  _docs/_hidden/other/airship_migration.md
  _docs/_hidden/other/user_csv_lambda.md
  _docs/_hidden/private_betas/get_app_group_apps.md
  _docs/_hidden/private_betas/get_campaign_url_info.md
  _docs/_hidden/private_betas/get_canvas_url_info.md
  _docs/_hidden/private_betas/sql_segments_tables.md
  _docs/_partners/data_and_infrastructure_agility/ab_testing/phrasee/phrasee.md
  _docs/_partners/data_and_infrastructure_agility/analytics/looker.md
  _docs/_partners/data_and_infrastructure_agility/analytics/thoughtspot.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/tinyclues.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/adobe/adobe.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/amperity.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/lexer.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_engage.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/toovio.md
  _docs/_partners/data_and_infrastructure_agility/support/pypestream.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/census.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/hightouch/hightouch.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/nexla.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/zapier.md
  _docs/_partners/isv_partners/cohort_import.md
  _docs/_partners/message_orchestration/additional_channels/mobile_wallet/passkit.md
  _docs/_partners/message_orchestration/additional_channels/retargeting/quikly.md
  _docs/_partners/message_orchestration/attribution/adjust.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer_audiences.md
  _docs/_partners/message_orchestration/attribution/branch/branch_for_attribution.md
  _docs/_partners/message_orchestration/attribution/singular.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
  _docs/_partners/message_personalization/dynamic_content/komo.md
  _docs/_partners/message_personalization/dynamic_content/peak.md
  _docs/_partners/message_personalization/dynamic_content/wyng.md
  _docs/_user_guide/message_building_by_channel/whatsapp/opt-ins_and_opt-outs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_phone_numbers.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
  _docs/_user_guide/onboarding_faq.md
Labels: cla-signed

#5337 BD-2082: Add details about variant distribution
  _docs/_user_guide/engagement_tools/testing/multivariant_testing.md
Labels: cla-signed

#5349 BD-2086: Clarify wording for data points
  _docs/_user_guide/data_and_analytics/data_points.md
Labels: cla-signed

#5345 Deploy - May 2, 2023
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
  _docs/_api/endpoints/templates/content_blocks_templates/post_update_content_block.md
  _docs/_help/help_articles/push/push_token_migration.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023.md
  _docs/_help/release_notes/2023/5_2_23.md
  _docs/_hidden/archive_docs/ios_14.md
  _docs/_hidden/other/airship_migration.md
  _docs/_hidden/other/user_csv_lambda.md
  _docs/_hidden/private_betas/get_app_group_apps.md
  _docs/_hidden/private_betas/get_campaign_url_info.md
  _docs/_hidden/private_betas/get_canvas_url_info.md
  _docs/_hidden/private_betas/sql_segments_tables.md
  _docs/_partners/data_and_infrastructure_agility/ab_testing/phrasee/phrasee.md
  _docs/_partners/data_and_infrastructure_agility/analytics/looker.md
  _docs/_partners/data_and_infrastructure_agility/analytics/thoughtspot.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/tinyclues.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/adobe/adobe.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/amperity.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/lexer.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_engage.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/toovio.md
  _docs/_partners/data_and_infrastructure_agility/support/pypestream.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/census.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/hightouch/hightouch.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/nexla.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/zapier.md
  _docs/_partners/isv_partners/cohort_import.md
  _docs/_partners/message_orchestration/additional_channels/mobile_wallet/passkit.md
  _docs/_partners/message_orchestration/additional_channels/retargeting/quikly.md
  _docs/_partners/message_orchestration/attribution/adjust.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer_audiences.md
  _docs/_partners/message_orchestration/attribution/branch/branch_for_attribution.md
  _docs/_partners/message_orchestration/attribution/singular.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
  _docs/_partners/message_personalization/dynamic_content/komo.md
  _docs/_partners/message_personalization/dynamic_content/peak.md
  _docs/_partners/message_personalization/dynamic_content/wyng.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/delete_users.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/data_points.md
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/whatsapp/opt-ins_and_opt-outs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_phone_numbers.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
  _docs/_user_guide/onboarding_faq.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/faq.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md
Labels: cla-signed, Deploy

#5352 Remove extra P that was breaking WhatsApp phone number links
  _docs/_user_guide/message_building_by_channel/whatsapp.md
Labels: cla-signed

#5353 Add forward slash
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/toovio.md
Labels: cla-signed

#5342 [SDK-3535] Add NCA code samples for iOS
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
Labels: cla-signed

#5355 BD-2087: Update to remove Authy and duplicate company settings doc
  _docs/_user_guide/administrative/company_settings.md
  _docs/_user_guide/administrative/company_settings/contact_information.md
  _docs/_user_guide/administrative/company_settings/notification_preferences.md
  _docs/_user_guide/administrative/company_settings/security_settings.md
  _docs/_user_guide/administrative/manage_your_braze_users.md
  _docs/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md
  assets/img/remember_me.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#5357 Minor edits - Section pages for endpoints
  _docs/_api/endpoints/catalogs.md
  _docs/_api/endpoints/email.md
  _docs/_api/endpoints/export.md
  _docs/_api/endpoints/messaging.md
  _docs/_api/endpoints/preference_center.md
  _docs/_api/endpoints/scim.md
  _docs/_api/endpoints/sms.md
  _docs/_api/endpoints/subscription_groups.md
  _docs/_api/endpoints/templates.md
  _docs/_api/endpoints/user_data.md
Labels: cla-signed

#5360 Add integration list to cloud_ingestion doc
  _docs/_user_guide/data_and_analytics/cloud_ingestion.md
Labels: cla-signed

#5361 BD-2093: Fix push notification abort and Canvas/ID styling
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#5362 Code owners updates for support page
  .github/CODEOWNERS
Labels: cla-signed

#5310 BD-2072: Add WhatsApp Events to Currents - MERGE 5/4
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#5343 Update react_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Labels: cla-signed

#5370 BD-2096: Update note for Message Extras tag
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
Labels: cla-signed

#5369 Emphasize RedShift security groups note
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
Labels: cla-signed

#5366 BD-2094: Update Canvas FAQ with IAM info
  _docs/_user_guide/engagement_tools/canvas/faqs.md
Labels: cla-signed

#5372 [DLK-1007] Adding generated docs for new events added in data lake
  assets/download_file/data-sharing-raw-table-schemas.txt
Labels: cla-signed

#5375 Update supported_personalization_tags.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: cla-signed

#5376 fix broken link to integrations page for CDI
  _docs/_user_guide/data_and_analytics/cloud_ingestion.md
Labels: cla-signed

#5365 BD-2088: Document meta throughput limit in WhatsApp FAQ
  _docs/_user_guide/message_building_by_channel/whatsapp/faqs.md
Labels: cla-signed

#5379 BD-2100: Updates to heap
  _docs/_partners/data_and_infrastructure_agility/cohort_import/heap.md
Labels: cla-signed

#5382 BD-2099: Selections and in-browser editing for catalogs GA
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/selections.md
Labels: cla-signed

#5383 BD-2102: Fix wording
  _docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
Labels: cla-signed

#5371 BD-2089: Add alert and clarify support details for trigger_properties
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_canvases.md
  _docs/_api/objects_filters/trigger_properties_object.md
Labels: cla-signed

#5381 Tweaking ISV docs for breadcrumb formatting
  _docs/_partners/isv_partners.md
  _docs/_partners/isv_partners/api_partner.md
  _docs/_partners/isv_partners/cohort_import.md
  _docs/_partners/isv_partners/currents_integration.md
Labels: cla-signed

#5386 BD-2101: Comments in Canvas EA - MERGE 5/9
  _docs/_hidden/private_betas/canvas_comments.md
  assets/img_archive/canvas_comments.png
Labels: cla-signed

#5394 Fix EA alert
  _docs/_hidden/private_betas/canvas_comments.md
Labels: cla-signed

#5392 BD-2104: Add redirect
  assets/js/broken_redirect_list.js
Labels: cla-signed

#5391 Added boosted articles for Swift
  _docs/_developer_guide/platform_integration_guides/swift/analytics/tracking_sessions.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/overview.md
  _docs/_developer_guide/platform_integration_guides/swift/sample_apps.md
Labels: cla-signed

#5390 Add Rudderstack to currents partners
  _docs/_user_guide/data_and_analytics/braze_currents/available_partners.md
Labels: cla-signed

#5389 BD-2073: Hidden Test Currents Connector page
  _docs/_hidden/private_betas/test_connectors.md
Labels: cla-signed

#5082 Expanding nested custom attributes via the SDK
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
Labels: status: in progress, cla-signed

#5378 Deploy - May 9, 2023
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_canvases.md
  _docs/_api/endpoints/preference_center.md
  _docs/_api/objects_filters/trigger_properties_object.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/tracking_sessions.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/overview.md
  _docs/_developer_guide/platform_integration_guides/swift/sample_apps.md
  _docs/_hidden/private_betas/canvas_comments.md
  _docs/_hidden/private_betas/critereo_audience_sync.md
  _docs/_hidden/private_betas/test_connectors.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/heap.md
  _docs/_partners/isv_partners.md
  _docs/_partners/isv_partners/api_partner.md
  _docs/_partners/isv_partners/cohort_import.md
  _docs/_partners/isv_partners/currents_integration.md
  _docs/_user_guide/data_and_analytics/braze_currents/available_partners.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
  _docs/_user_guide/engagement_tools/canvas/faqs.md
  _docs/_user_guide/message_building_by_channel/email/preference_center.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/overview.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/preference_center.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/preference_center_via_api.md
  _docs/_user_guide/message_building_by_channel/whatsapp.md
  _docs/_user_guide/message_building_by_channel/whatsapp/create.md
  _docs/_user_guide/message_building_by_channel/whatsapp/faqs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/overview.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/selections.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  assets/download_file/data-sharing-raw-table-schemas.txt
  assets/img/criteo/criteo.png
  assets/img/criteo/criteo1.png
  assets/img/criteo/criteo10.png
  assets/img/criteo/criteo11.png
  assets/img/criteo/criteo12.png
  assets/img/criteo/criteo2.png
  assets/img/criteo/criteo3.png
  assets/img/criteo/criteo4.png
  assets/img/criteo/criteo5.png
  assets/img/criteo/criteo6.png
  assets/img/criteo/criteo7.png
  assets/img/criteo/criteo8.png
  assets/img/criteo/criteo9.png
  assets/img_archive/canvas_comments.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#5388 Built out steps for deep links in React Native
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
Labels: cla-signed

#5397 Fix query builder screenshots
  _docs/_user_guide/data_and_analytics/query_builder.md
Labels: cla-signed

#5384 BD-2091: Add abort messages for Liquid Use Case Library
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
Labels: cla-signed

#5399 Rename critereo_audience_sync.md to criteo_audience_sync.md
  _docs/_hidden/private_betas/criteo_audience_sync.md
Labels: cla-signed

#5400 Edits for mentions of external ID
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
  _docs/_api/endpoints/user_data/external_id_migration.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_help/help_articles/push/push_token_migration.md
  _docs/_home/templates_old/api_glossary.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/overview.md
  _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
  _docs/_user_guide/onboarding_faq.md
Labels: cla-signed

#5401 BD-2103: Merge user profiles EA
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
Labels: cla-signed

#5405 BD-2108: Fix typo
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
Labels: cla-signed

#5396 Update React Native iOS setup code snippets
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Labels: cla-signed

#5407 Update array_of_objects.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md
Labels: cla-signed

#5409 Leftover Deploy - May 11, 2023
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
  _docs/_api/endpoints/user_data/external_id_migration.md
  _docs/_developer_guide/platform_integration_guides/cordova/changelog.md
  _docs/_developer_guide/platform_integration_guides/cordova/content_cards.md
  _docs/_developer_guide/platform_integration_guides/cordova/cordova_integration.md
  _docs/_developer_guide/platform_integration_guides/cordova/initial_sdk_setup/android.md
  _docs/_developer_guide/platform_integration_guides/cordova/initial_sdk_setup/ios.md
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_help/help_articles/push/push_token_migration.md
  _docs/_hidden/private_betas/criteo_audience_sync.md
  _docs/_home/templates_old/api_glossary.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
  _docs/_user_guide/data_and_analytics/query_builder.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
  _docs/_user_guide/engagement_tools/testing/global_control_group.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/overview.md
  _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
  _docs/_user_guide/onboarding_faq.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
Labels: cla-signed, Deploy

#5410 BD-2015: Webhook campaign analytics
  _docs/_user_guide/data_and_analytics/reporting/campaign_analytics.md
  _docs/_user_guide/message_building_by_channel/webhooks.md
  _docs/_user_guide/message_building_by_channel/webhooks/reporting.md
  _includes/campaign_analytics.md
  assets/img/campaign_details_webhook.png
  assets/img/icons/content_card.svg
  assets/img/icons/email.svg
  assets/img/icons/in-app_message.svg
  assets/img/icons/news_feed.svg
  assets/img/icons/push.svg
  assets/img/icons/sms.svg
  assets/img/icons/webhook.svg
  assets/img/icons/whatsapp.svg
  assets/img/webhook_message_performance.png
Labels: cla-signed

#5413 Update api_limits.md
  _docs/_api/api_limits.md
Labels: cla-signed

#5414 Re-add miscellaneous Swift docs
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
Labels: cla-signed

#5406 Update nested_custom_attribute_support.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
Labels: cla-signed

#5416 Add French Maintenance banner
  _includes/header.html
  assets/js/documents.js
Labels: cla-signed

#5417 SDK-3710 / expo update fields
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Labels: cla-signed

#5420 Audience Sync Pro Section - MERGE 5/15
  _docs/_partners/canvas_steps.md
  _docs/_partners/canvas_steps/facebook_audience_sync.md
  _docs/_partners/canvas_steps/faq.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_partners/canvas_steps/overview.md
  _docs/_partners/canvas_steps/pinterest_audience_sync.md
  _docs/_partners/canvas_steps/snapchat_audience_sync.md
  _docs/_partners/canvas_steps/tiktok_audience_sync.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/audience_sync.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/fb_audience_sync.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/google_audience_sync.md
  assets/img/audience_sync/audience_sync.png
  assets/img/audience_sync/audience_sync2.png
  assets/img/audience_sync/audience_sync3.png
  assets/img/audience_sync/audience_sync4.png
  assets/img/audience_sync/audience_sync5.png
  assets/img/audience_sync/audience_sync6.png
  assets/img/audience_sync/fb_sync.png
  assets/img/audience_sync/fb_sync2.png
  assets/img/audience_sync/fb_sync3.png
  assets/img/audience_sync/g_sync.png
  assets/img/audience_sync/g_sync2.png
  assets/img/audience_sync/g_sync3.png
  assets/img/audience_sync/pinterest_sync.png
  assets/img/audience_sync/pinterest_sync2.png
  assets/img/audience_sync/pinterest_sync3.png
  assets/img/audience_sync/snapchat.png
  assets/img/audience_sync/snapchat2.png
  assets/img/audience_sync/snapchat3.png
  assets/img/audience_sync/tiktok.png
  assets/img/audience_sync/tiktok2.png
  assets/img/audience_sync/tiktok3.png
Labels: cla-signed

#5411 BD-2097: Clarify details for blocklist and deleting custom data
  _docs/_user_guide/administrative/app_settings/manage_app_group/custom_event_and_attribute_management.md
  _docs/_user_guide/data_and_analytics/custom_data/blocklist_delete_custom_data.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
Labels: cla-signed

#5422 BD-2115: Clarify details for Canvas drafts
  _docs/_hidden/private_betas/canvas_drafts.md
Labels: cla-signed

#5424 BD-2116: Updates to commenting for Canvas
  _docs/_hidden/private_betas/canvas_comments.md
  assets/img_archive/canvas_comments.png
Labels: cla-signed

#5403 Add Cordova samples for Feature Flag usage
  _docs/_developer_guide/platform_wide/feature_flags/create.md
Labels: cla-signed

#5430 BD-2111: Guidance on managing consent
  _docs/_user_guide/administrative.md
  _docs/_user_guide/administrative/privacy.md
  _docs/_user_guide/administrative/privacy/managing_consent.md
  _docs/_user_guide/administrative/privacy/spam_regulations.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#5431 Update navigation.md
  _docs/_user_guide/administrative/access_braze/navigation.md
Labels: cla-signed

#5432 Deploy Pt. 2 - May 16, 2023
  _docs/_developer_guide/platform_wide/feature_flags/create.md
  _docs/_hidden/private_betas/canvas_comments.md
  _docs/_user_guide/administrative.md
  _docs/_user_guide/administrative/access_braze/navigation.md
  _docs/_user_guide/administrative/privacy.md
  _docs/_user_guide/administrative/privacy/managing_consent.md
  _docs/_user_guide/administrative/privacy/spam_regulations.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
  assets/img_archive/canvas_comments.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#5436 Update amphtml.md
  _docs/_user_guide/message_building_by_channel/email/amphtml.md
Labels: cla-signed

#5438 BD-2122: Remove support of specific shopify data events
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
Labels: cla-signed

#5439 Add access note to query builder
  _docs/_user_guide/data_and_analytics/query_builder.md
Labels: cla-signed

#5418 BD-2109: Message extras Liquid tag GA - MERGE 5/18
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
Labels: cla-signed

#5442 BD-2124: Clarify info on how to get on approved sender's list
  _docs/_user_guide/message_building_by_channel/email/html_editor/gmail_promotions_tab.md
Labels: cla-signed

#5443 Update message_archiving.md
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
Labels: cla-signed

#5441 Update get_campaign_analytics.md
  _docs/_api/endpoints/export/campaigns/get_campaign_analytics.md
Labels: cla-signed

#5446 Update get_list_product_id.md
  _docs/_api/endpoints/export/purchases/get_list_product_id.md
Labels: cla-signed

#5449 Typo in SSL doc
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl.md
Labels: cla-signed

#5448 LinkedIn Audience Sync - EA (MERGE 5/18)
  _docs/_hidden/private_betas/linkedin_audience_sync.md
  _docs/_partners/canvas_steps/tiktok_audience_sync.md
  assets/img/linkedin/linkedin.png
  assets/img/linkedin/linkedin1.png
  assets/img/linkedin/linkedin10.png
  assets/img/linkedin/linkedin11.png
  assets/img/linkedin/linkedin17.png
  assets/img/linkedin/linkedin2.png
  assets/img/linkedin/linkedin20.png
  assets/img/linkedin/linkedin3.png
  assets/img/linkedin/linkedin4.png
  assets/img/linkedin/linkedin5.png
  assets/img/linkedin/linkedin6.png
  assets/img/linkedin/linkedin7.png
  assets/img/linkedin/linkedin8.png
  assets/img/linkedin/linkedin9.png
  assets/img/tiktok/tiktok10.png
  assets/img/tiktok/tiktok17.png
  assets/img/tiktok/tiktok9.png
Labels: cla-signed

#5447 Add note about setting UNNotificationActionOptions in iOS action buttons
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/customization/action_buttons.md
Labels: cla-signed

#5450 Leftover deploy - May 18, 2023
  _docs/_api/endpoints/export/campaigns/get_campaign_analytics.md
  _docs/_api/endpoints/export/news_feed/get_news_feed_cards.md
  _docs/_api/endpoints/export/purchases/get_list_product_id.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/customization/action_buttons.md
  _docs/_hidden/private_betas/linkedin_audience_sync.md
  _docs/_partners/canvas_steps/tiktok_audience_sync.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
  _docs/_user_guide/data_and_analytics/query_builder.md
  _docs/_user_guide/message_building_by_channel/email/amphtml.md
  _docs/_user_guide/message_building_by_channel/email/html_editor/gmail_promotions_tab.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
  assets/img/linkedin/linkedin.png
  assets/img/linkedin/linkedin1.png
  assets/img/linkedin/linkedin10.png
  assets/img/linkedin/linkedin11.png
  assets/img/linkedin/linkedin17.png
  assets/img/linkedin/linkedin2.png
  assets/img/linkedin/linkedin20.png
  assets/img/linkedin/linkedin3.png
  assets/img/linkedin/linkedin4.png
  assets/img/linkedin/linkedin5.png
  assets/img/linkedin/linkedin6.png
  assets/img/linkedin/linkedin7.png
  assets/img/linkedin/linkedin8.png
  assets/img/linkedin/linkedin9.png
  assets/img/tiktok/tiktok10.png
  assets/img/tiktok/tiktok17.png
  assets/img/tiktok/tiktok9.png
Labels: cla-signed, Deploy

#5451 Fix markdown start index
  assets/css/_content.scss
Labels: cla-signed

#5453 Update get_list_catalogs.md
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/get_list_catalogs.md
Labels: cla-signed

#5454 Fix heading
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/get_list_catalogs.md
Labels: cla-signed

#5456 Fix heading pt. 3
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/post_create_catalog_items_bulk.md
Labels: cla-signed

#5458 Fixing trust score discrepancy on 10DLC
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/10dlc.md
Labels: cla-signed

#5455 Fix heading pt. 2
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md
Labels: cla-signed

#5459 BD-2121: Add templated IAM behavior to IAM FAQ
  _docs/_user_guide/message_building_by_channel/in-app_messages/faq.md
Labels: cla-signed

#5462 Include Snowflake support for message_extras tag
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
Labels: cla-signed

#5460 BD-2128: Add suggestions for time operator
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
Labels: cla-signed

#5464 BD-2127: Simple survey data type for multiple vs single choice
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/templates/simple_survey.md
Labels: cla-signed

#5469 BD-2134: Clarify Canvas and campaign user entry
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/targeting_users.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
Labels: cla-signed

#5471 add link to better examples
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
Labels: cla-signed

#5473 Update message_engagement_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#5475 BD-2131: Update exporting revenue report
  _docs/_user_guide/data_and_analytics/export_braze_data/exporting_revenue_data.md
Labels: cla-signed

#5476 Deploy - May 23, 2023
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/post_create_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/get_list_catalogs.md
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
  _docs/_user_guide/data_and_analytics/export_braze_data/exporting_revenue_data.md
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/targeting_users.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/intelligence.md
  _docs/_user_guide/intelligence/ai_content_qa.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/faq.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/templates/simple_survey.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/10dlc.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
  assets/css/_content.scss
  assets/img/content_qa_ai.png
Labels: Deploy

#5477 BD-2143: Personalized variant custom events change
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md
  assets/css/_content.scss
  assets/img_archive/ab_analytics_pv_3.png
Labels: cla-signed

#5230 Tangerine Partnership Documentation
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/location.md
  _docs/_partners/message_personalization/location/tangerine.md
Labels: status: done, cla-signed, Braze Partnerships

#5481 BD-2144: Add sentence about catalogs storage limit
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
Labels: cla-signed

#5482 BD-2142: Clarify CSV file size maximum
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
Labels: cla-signed

#5480 Update clarisights.md
  _docs/_partners/data_and_infrastructure_agility/analytics/clarisights.md
Labels: cla-signed

#5483 Update viewing_and_understanding_segment_data.md
  _docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md
Labels: cla-signed

#5474 OneTrust Partnership Docs
  _docs/_hidden/wip_partnerships/partnership_template.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/data_privacy.md
  _docs/_partners/data_and_infrastructure_agility/data_privacy/onetrust.md
  _docs/_partners/data_and_infrastructure_agility/data_privacy/transcend.md
  _docs/_partners/home.md
  _docs/_partners/message_orchestration/additional_channels/calendar/rokt_calendar.md
  _docs/_partners/message_orchestration/additional_channels/direct_mail/inkit.md
  _docs/_partners/message_orchestration/additional_channels/mobile_wallet/passkit.md
  _docs/_partners/message_orchestration/additional_channels/retargeting/quikly.md
  _lang/fr/_hidden/wip_partnerships/partnership_template.md
  assets/img/onetrust/onetrust.png
  assets/img/onetrust/onetrust10.png
  assets/img/onetrust/onetrust2.png
  assets/img/onetrust/onetrust3.png
  assets/img/onetrust/onetrust4.png
  assets/img/onetrust/onetrust5.png
  assets/img/onetrust/onetrust6.png
  assets/img/onetrust/onetrust7.png
  assets/img/onetrust/onetrust8.png
  assets/img/onetrust/onetrust9.png
Labels: status: done, cla-signed, Braze Partnerships

#5470 SalesWings Partnership Docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/analytics.md
  _docs/_partners/data_and_infrastructure_agility/analytics/saleswings.md
  _docs/_partners/home.md
  assets/img/saleswings/braze_api_endpoint_for_lead_scoring.png
  assets/img/saleswings/braze_api_key_lead_scoring.png
  assets/img/saleswings/creating_api_key_in_braze_lead_scoring.png
  assets/img/saleswings/example_lead_scoring_builder_braze_lead_scoring.png
  assets/img/saleswings/marketo_sales_insights_alternative_for_braze.png
  assets/img/saleswings/prioritized_account_list_braze_lead_scoring.png
  assets/img/saleswings/prioritized_lead_or_contact_list_braze_lead_scoring.png
  assets/img/saleswings/saleswings_braze_lead_scoring_integration_settings.png
  assets/img/saleswings/saleswings_email_campaign_attribution_dashboard.png
  assets/img/saleswings/smart_watch_alerts.png
Labels: cla-signed, Braze Partnerships

#5472 Kognitiv Partnership Docs
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/channel_extensions.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/kognitiv.md
Labels: status: done, cla-signed, Braze Partnerships

#5426 Regal - Partnership Docs
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/additional_channels.md
  _docs/_partners/message_orchestration/additional_channels/messaging.md
  _docs/_partners/message_orchestration/additional_channels/messaging/regal.md
  assets/img/regal/copy_webhook_url.png
  assets/img/regal/edit_webhook.png
  assets/img/regal/request_header.png
  assets/img/regal/webhook_rawtext.png
Labels: status: done, cla-signed, Braze Partnerships

#5435 Smartling Partnership Documentation
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/localization.md
  _docs/_partners/message_personalization/localization/smartling.md
  assets/img/smartling/smartling-braze-settings.png
  assets/img/smartling/smartling-content-blocks-list.png
Labels: status: done, cla-signed, Braze Partnerships

#5429 Sendbird Partnership Docs
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/additional_channels.md
  _docs/_partners/message_orchestration/additional_channels/messaging.md
  _docs/_partners/message_orchestration/additional_channels/messaging/sendbird.md
  assets/img/sendbird/sendbird-dashboard-integrations-1.png
  assets/img/sendbird/sendbird-dashboard-integrations.png
  assets/img/sendbird/sendbird-dashboard-template.png
  assets/img/sendbird/sendbird-notification-builder.png
  assets/img/sendbird/use-cases.png
Labels: status: done, cla-signed, Braze Partnerships

#5433 Fresh Relevance Partnership Docs
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content.md
  _docs/_partners/message_personalization/dynamic_content/fresh_relevance.md
Labels: status: done, cla-signed, Braze Partnerships

#5484 Minor edits to Content QA with AI
  _docs/_user_guide/intelligence/ai_content_qa.md
Labels: cla-signed

#5487 BD-2147: Fix personalization links from raw tag
  _docs/_user_guide/personalization_and_dynamic_content/liquid/faq.md
Labels: cla-signed

#5486 BD-2059: Adding reporting/export behavior to cloud data storage partners
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/google_cloud_storage_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/microsoft_azure_blob_storage_for_currents.md
Labels: cla-signed

#5489 Edits from Postman audit
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/delete_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/patch_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/post_create_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/put_update_catalog_items.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/delete_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/get_catalog_items_details_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/patch_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/put_update_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md
  _docs/_api/endpoints/preference_center.md
  _docs/_api/endpoints/preference_center/get_create_url_preference_center.md
  _docs/_api/endpoints/preference_center/get_list_preference_center.md
  _docs/_api/endpoints/preference_center/get_view_details_preference_center.md
  _docs/_api/endpoints/preference_center/post_create_preference_center.md
  _docs/_api/endpoints/preference_center/put_update_preference_center.md
  _docs/_api/endpoints/subscription_groups/get_list_user_subscription_groups.md
Labels: cla-signed

#5490 Remove dev formatting from partner docs
  _docs/_partners/message_orchestration/additional_channels/messaging/sendbird.md
Labels: cla-signed

#5491 Add more detail about subscription groups permission
  _docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#5485 Stylitics Partnership Docs
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content.md
  _docs/_partners/message_personalization/dynamic_content/stylitics.md
  assets/img/stylitics.png
Labels: status: done, cla-signed, Braze Partnerships

#5493 BD-2151: Add md5 hashing example to s3 bucket export
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
Labels: cla-signed

#5496 BD-2155: Update mention of Inbox Vision
  _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
Labels: cla-signed

#5495 BD-2154: Update QB max rows and look back
  _docs/_user_guide/data_and_analytics/query_builder.md
Labels: cla-signed

#5498 Update faqs.md
  _docs/_user_guide/engagement_tools/templates_and_media/faqs.md
Labels: cla-signed

#5500 Added rate limit for requestRefresh
  _docs/_developer_guide/platform_integration_guides/android/content_cards/refreshing_the_feed.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/refreshing_the_feed.md
Labels: cla-signed

#5502 Update vizbee_for_tv_deeplinking.md
  _docs/_partners/message_orchestration/attribution/vizbee_for_tv_deeplinking.md
Labels: cla-signed

#5503 remove firebase-core dependency from android push docs
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
Labels: cla-signed

#5437 WhatsApp Updates
  _docs/_user_guide/message_building_by_channel/sms/campaign/retargeting.md
  _docs/_user_guide/message_building_by_channel/whatsapp.md
  _docs/_user_guide/message_building_by_channel/whatsapp/faqs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing.md
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/handling_unknown_numbers.md
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/opt-ins_and_opt-outs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/user_messages.md
  _docs/_user_guide/message_building_by_channel/whatsapp/quick_replies.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_phone_numbers.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/user_retargeting.md
  assets/img/whatsapp/whatsapp19.png
  assets/img/whatsapp/whatsapp20.png
  assets/img/whatsapp/whatsapp21.png
  assets/img/whatsapp/whatsapp22.png
  assets/img/whatsapp/whatsapp23.png
  assets/img/whatsapp/whatsapp24.png
  assets/img/whatsapp/whatsapp25.png
  assets/img/whatsapp/whatsapp26.png
  assets/img/whatsapp/whatsapp27.png
Labels: cla-signed

#5467 BD-2118: Update BigQuery Table Example
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
Labels: cla-signed

#5444 BD-2125: New /users/subscription endpoint
  _docs/_api/endpoints/email.md
  _docs/_api/endpoints/email/delete_remove_subscription_state.md
  _docs/_api/endpoints/email/get_list_hard_bounces.md
  _docs/_api/endpoints/email/get_query_by_email_or_phone.md
  _docs/_api/endpoints/email/get_query_unsubscribed_email_addresses.md
  _docs/_api/endpoints/email/post_blocklist.md
  _docs/_api/endpoints/email/post_email_subscription_status.md
  _docs/_api/endpoints/email/post_remove_hard_bounces.md
  _docs/_api/endpoints/email/post_remove_spam.md
  _docs/_api/home.md
Labels: cla-signed

#5511 BD-2161: Clarify link tracking behavior
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
Labels: cla-signed

#5512 BD-2159: Document schema generation caveat
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
Labels: cla-signed

#5510 BD-2136: Winning Path updates
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/winning_path.md
  assets/img/experiment_step/experiment_path_distribution.png
  assets/img/experiment_step/experiment_winning_path.png
Labels: cla-signed

#5492 Release Notes 5/30/23
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023.md
  _docs/_help/release_notes/2023/5_30_23.md
Labels: cla-signed

#5506 Deploy - May 30, 2023
  _docs/_api/endpoints/email.md
  _docs/_api/endpoints/email/delete_remove_subscription_state.md
  _docs/_api/endpoints/email/get_list_hard_bounces.md
  _docs/_api/endpoints/email/get_query_by_email_or_phone.md
  _docs/_api/endpoints/email/get_query_unsubscribed_email_addresses.md
  _docs/_api/endpoints/email/post_blocklist.md
  _docs/_api/endpoints/email/post_email_subscription_status.md
  _docs/_api/endpoints/email/post_remove_hard_bounces.md
  _docs/_api/endpoints/email/post_remove_spam.md
  _docs/_api/home.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/refreshing_the_feed.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/refreshing_the_feed.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023.md
  _docs/_help/release_notes/2023/5_30_23.md
  _docs/_home/dp-technical-assistance.md
  _docs/_partners/message_orchestration/attribution/vizbee_for_tv_deeplinking.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/query_builder.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/winning_path.md
  _docs/_user_guide/engagement_tools/templates_and_media/faqs.md
  _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/retargeting.md
  _docs/_user_guide/message_building_by_channel/whatsapp.md
  _docs/_user_guide/message_building_by_channel/whatsapp/faqs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing.md
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/handling_unknown_numbers.md
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/opt-ins_and_opt-outs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/user_messages.md
  _docs/_user_guide/message_building_by_channel/whatsapp/quick_replies.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_phone_numbers.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/user_retargeting.md
  _includes/campaign_analytics.md
  assets/img/experiment_step/experiment_path_distribution.png
  assets/img/experiment_step/experiment_winning_path.png
  assets/img/whatsapp/whatsapp19.png
  assets/img/whatsapp/whatsapp20.png
  assets/img/whatsapp/whatsapp21.png
  assets/img/whatsapp/whatsapp22.png
  assets/img/whatsapp/whatsapp23.png
  assets/img/whatsapp/whatsapp24.png
  assets/img/whatsapp/whatsapp25.png
  assets/img/whatsapp/whatsapp26.png
  assets/img/whatsapp/whatsapp27.png
Labels: cla-signed, Deploy

#5466 BD-2135: Update Credit Ratios Doc (MERGE 6/1)
  _docs/_hidden/other/credit_ratios.md
Labels: cla-signed

#5514 BD-2156: Edit email footer details
  _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
Labels: cla-signed

#5515 BD-2160: Update card creation screenshot
  _docs/_user_guide/message_building_by_channel/content_cards/create/card_creation.md
  assets/img_archive/card_creation.png
Labels: cla-signed

#5516 BD-2164: Clarify exit criteria details
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/exit_criteria.md
  assets/img_archive/exit_criteria_example.png
Labels: cla-signed

#5521 Update flywheel.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/flywheel.md
Labels: cla-signed

#5519 Update link_shortening.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
Labels: cla-signed

#5523 BD-2140: Clarify entry controls for Canvas
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  assets/img_archive/entry_controls.png
  assets/img_archive/user_lookup.png
Labels: cla-signed

#5513 BD-2166: Facebook audience sync updates
  _docs/_partners/canvas_steps/facebook_audience_sync.md
  _docs/_partners/message_orchestration/additional_channels/retargeting/facebook.md
Labels: cla-signed
