Repository braze-inc/braze-docs, pull requests merged in 2023-08, with the labels that each got.

#5904 Deploy Pt. 2 - August 1, 2023
  _docs/_hidden/other/10dlc_application.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/set_up.md
  _docs/_user_guide/data_and_analytics/braze_currents/available_partners.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/opt-ins_and_opt-outs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md
  _layouts/broken_page.html
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#5905 Add missing fr images
  assets/img/tiktok/tiktok10.png
  assets/img/tiktok/tiktok17.png
  assets/img/tiktok/tiktok9.png
Labels: cla-signed

#5906 Leftover deploy - August 1, 2023
  assets/img/tiktok/tiktok10.png
  assets/img/tiktok/tiktok17.png
  assets/img/tiktok/tiktok9.png
Labels: cla-signed, Deploy

#5907 Spelling error, legal tweak
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/user_phone_numbers.md
Labels: cla-signed

#5912 Update user_phone_numbers.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/user_phone_numbers.md
Labels: cla-signed

#5914 BD-2335: Shopify catalogs GA
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_catalogs.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/use_cases.md
  _docs/_user_guide/message_building_by_channel/push/android/notification_channels.md
Labels: cla-signed

#5870 Update sql_segments.md
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
Labels: cla-signed

#5910 Changed all links in the Xamarin docs from Swift SDK to legacy iOS SDK
  _docs/_developer_guide/platform_integration_guides/xamarin/analytics.md
  _docs/_developer_guide/platform_integration_guides/xamarin/content_cards.md
  _docs/_developer_guide/platform_integration_guides/xamarin/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/xamarin/push_notifications.md
Labels: cla-signed

#5915 Deploy pt 4 - August 2, 2023
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/customization/action_buttons.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/xamarin/analytics.md
  _docs/_developer_guide/platform_integration_guides/xamarin/content_cards.md
  _docs/_developer_guide/platform_integration_guides/xamarin/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/xamarin/push_notifications.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_catalogs.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/use_cases.md
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
  _docs/_user_guide/message_building_by_channel/push/android/notification_channels.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/user_phone_numbers.md
Labels: cla-signed, Deploy

#5917 BD-2336: Update Live Activities FAQ
  _docs/_developer_guide/platform_integration_guides/swift/live_activities/faq.md
Labels: cla-signed

#5918 remove segment group call
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
Labels: cla-signed

#5884 BD-2323 User Subscription Status clarification
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/opt-ins_and_opt-outs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
  assets/img/whatsapp/whatsapp_json_editor.png
Labels: cla-signed

#5775 Update in-app message documentation for React Native
  _docs/_developer_guide/platform_integration_guides/react_native/inapp_messages.md
Labels: status: on hold / do not merge, cla-signed

#5921 BD-2337 Update Abort Logic Documentation
  _docs/_user_guide/personalization_and_dynamic_content/liquid/aborting_messages.md
Labels: cla-signed

#5920 Update older intel redirects
  assets/js/broken_redirect_list.js
Labels: cla-signed

#5853 Update React Native setup docs for Turbo Modules
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Labels: cla-signed

#5919 BD-2340: Remove reference of theme tags
  _docs/_user_guide/personalization_and_dynamic_content/liquid.md
Labels: cla-signed

#5916 BD-2334: Conversions dashboard v2 EA
  _docs/_hidden/private_betas/conversions_dashboard_v2.md
  assets/css/_content.scss
  assets/img_archive/conversions2_details.png
  assets/img_archive/conversions2_over_time.png
Labels: cla-signed

#5922 Leftover deploy - August 3, 2023
  _docs/_developer_guide/platform_integration_guides/react_native/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/swift/live_activities/faq.md
  _docs/_hidden/private_betas/conversions_dashboard_v2.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _docs/_user_guide/message_building_by_channel/push/about.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/message_format.md
  _docs/_user_guide/message_building_by_channel/push/ios/rich_notifications.md
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/opt-ins_and_opt-outs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/aborting_messages.md
  assets/css/_content.scss
  assets/img/whatsapp/whatsapp_json_editor.png
  assets/img_archive/conversions2_details.png
  assets/img_archive/conversions2_over_time.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#5923 BD-2339 Update conditional logic
  _docs/_user_guide/personalization_and_dynamic_content/liquid/conditional_logic.md
  assets/img/value_null.png
Labels: cla-signed

#5911 BD-2332: Card creation in Canvas EA
  _docs/_user_guide/message_building_by_channel/content_cards/create/card_creation.md
  assets/img_archive/card_creation_canvas.png
Labels: cla-signed

#5924 Update workspace management with react images
  _docs/_user_guide/administrative/app_settings/app_group_management.md
  assets/img_archive/app_settings_react.png
  assets/img_archive/rename_workspace.gif
Labels: cla-signed

#5925 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla-signed

#5926 404
  _layouts/broken_page.html
Labels: cla-signed

#5932 BD-2347 Appsflyer Integration Documentation Clarification Request
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
Labels: cla-signed

#5933 BD-2322: Save and launch Content Block
  _docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md
  assets/img/copy-content-block.png
Labels: cla-signed

#5934 BD-2348 Fullscreen IAMs on Web SDK
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/create.md
Labels: cla-signed

#5935 BD-2346: Update response
  _docs/_api/endpoints/export/campaigns/get_send_analytics.md
Labels: cla-signed

#5936 BD-2342: Add domain reputation for email deliverability
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
Labels: cla-signed

#5931 404 and redirect audit pt.1 (August 2023)
  _docs/_api/objects_filters/schedule_object.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization/handling_in_app_display.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/troubleshooting.md
  _docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
  _docs/_help/release_notes/2019/november.md
  _docs/_help/release_notes/2020/april.md
  _docs/_help/release_notes/2021/april.md
  _docs/_help/release_notes/2021/august.md
  _docs/_help/release_notes/2021/september.md
  _docs/_hidden/archive_docs/baidu_integration.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/scheduled_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/time_based_campaign.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/advancement.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/time_based_canvas.md
  _docs/_user_guide/engagement_tools/canvas/faqs.md
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/pre_post_launch_checklist.md
  _docs/_user_guide/introduction.md
  _docs/_user_guide/message_building_by_channel/email/email_setup/ip_warming.md
  _docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize/color_profiles_and_css.md
  _docs/_user_guide/message_building_by_channel/sms/faqs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/opt-ins_and_opt-outs.md
  _docs/_user_guide/onboarding_with_braze/learning_to_use_braze.md
  _docs/_user_guide/sage_ai/intelligence/faqs.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#5940 Revert #5934
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/create.md
Labels: cla-signed

#5941 BD-2348 Fullscreen IAM orientation
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/create.md
Labels: cla-signed

#5939 Deploy - August 8, 2023
  .github/PULL_REQUEST_TEMPLATE.md
  _docs/_api/endpoints/export/campaigns/get_send_analytics.md
  _docs/_api/objects_filters/schedule_object.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization/handling_in_app_display.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/troubleshooting.md
  _docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
  _docs/_help/release_notes/2019/november.md
  _docs/_help/release_notes/2020/april.md
  _docs/_help/release_notes/2021/april.md
  _docs/_help/release_notes/2021/august.md
  _docs/_help/release_notes/2021/september.md
  _docs/_hidden/archive_docs/baidu_integration.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _docs/_user_guide/administrative/app_settings/app_group_management.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users.md
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/scheduled_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/time_based_campaign.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/advancement.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/time_based_canvas.md
  _docs/_user_guide/engagement_tools/canvas/faqs.md
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/pre_post_launch_checklist.md
  _docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md
  _docs/_user_guide/introduction.md
  _docs/_user_guide/message_building_by_channel/content_cards/create/card_creation.md
  _docs/_user_guide/message_building_by_channel/email/email_setup/ip_warming.md
  _docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize/color_profiles_and_css.md
  _docs/_user_guide/message_building_by_channel/sms.md
  _docs/_user_guide/message_building_by_channel/sms/faqs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/opt-ins_and_opt-outs.md
  _docs/_user_guide/onboarding_with_braze/learning_to_use_braze.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/conditional_logic.md
  _docs/_user_guide/sage_ai/intelligence/faqs.md
  _layouts/broken_page.html
  assets/img/copy-content-block.png
  assets/img/value_null.png
  assets/img_archive/app_settings_react.png
  assets/img_archive/card_creation_canvas.png
  assets/img_archive/rename_workspace.gif
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#5943 Update overview.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
Labels: cla-signed

#5946 BD-2352 Update Facebook ad account requirements
  _docs/_partners/canvas_steps/facebook_audience_sync.md
Labels: cla-signed

#5944 Add documentation for users_merge_with_email
  _docs/_api/endpoints/user_data/post_users_merge.md
Labels: cla-signed

#5945 BD-2341 New page on WhatsApp user docs: best practices
  _docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
  _docs/_user_guide/message_building_by_channel/whatsapp.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_best_practices.md
  assets/img/whatsapp/whatsapp_block_report.png
  assets/img/whatsapp/whatsapp_unsubscribe.png
Labels: cla-signed

#5947 Fix spacing
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_best_practices.md
Labels: cla-signed

#5888 Update Android docs for FCM fallback service
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
Labels: cla-signed

#5672 Feedback for Canvas entry properties and event properties
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
Labels: cla-signed

#5948 BD-2353 Add examples to Currents doc
  _docs/_partners/data_and_infrastructure_agility/cohort_import/heap.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack/rudderstack_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/treasure_data/treasure_data_for_currents.md
Labels: cla-signed

#5950 BD-2355: Update Conversions v2 with conversion funnel
  _docs/_hidden/private_betas/conversions_dashboard_v2.md
  assets/img_archive/conversions2_funnel.png
Labels: cla-signed

#5951 BD-2350: Clarify data retention for SQL Segment Extensions
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
Labels: cla-signed

#5952 Update intelligent_timing.md
  _docs/_user_guide/sage_ai/intelligence/intelligent_timing.md
Labels: cla-signed

#5955 BD-2356: Remove EA note from Content QA
  _docs/_user_guide/sage_ai/generative_ai/ai_content_qa.md
Labels: cla-signed

#5957 Remove bot filter to blank pages
  _docs/_docs_pages/robots.txt
  vercel.json
Labels: cla-signed

#5942 Feature Flags
  _docs/_developer_guide/platform_wide/feature_flags.md
  _docs/_developer_guide/platform_wide/feature_flags/about.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
  _docs/_developer_guide/platform_wide/feature_flags/use_cases.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  assets/img/feature_flags/feature-flags-filter-name.png
  assets/img/feature_flags/feature-flags-filter-selection.png
  assets/img/feature_flags/feature-flags-manage-permission.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#5908 Limitations for copying across workspaces
  _docs/_hidden/private_betas/copying_to_workspace.md
Labels: cla-signed

#5958 Update incorrect link reference
  _docs/_developer_guide/platform_wide/sending_test_messages.md
Labels: cla-signed

#5959 404 audit part 1
  _docs/_help/release_notes/2017/august.md
  _lang/fr/_help/release_notes/2017/august.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#5949 Broken link audit pt.2 (August 2023)
  _docs/_help/release_notes/2022/11_15_22.md
  _docs/_home/templates_old/api_glossary.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/mozart_data.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/creating_campaign.md
  _docs/_user_guide/message_building_by_channel/email/about.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _docs/_user_guide/message_building_by_channel/email/email_setup.md
  _docs/_user_guide/message_building_by_channel/email/email_setup/ip_warming.md
  _docs/_user_guide/message_building_by_channel/email/html_editor/gmail_promotions_tab.md
  _docs/_user_guide/message_building_by_channel/email/transactional_message_api_campaign.md
  _docs/_user_guide/onboarding_with_braze/learning_to_use_braze.md
  _docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#5930 BD-2306: Adding examples to teams doc
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/teams.md
  assets/img_archive/scenario1.png
  assets/img_archive/scenario2.png
  assets/img_archive/team_permissions_scenario1.gif
  assets/img_archive/team_permissions_scenario2.gif
Labels: cla-signed

#5960 Leftover Deploy - August 10, 2023
  _docs/_api/endpoints/user_data/post_users_merge.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
  _docs/_developer_guide/platform_wide/feature_flags.md
  _docs/_developer_guide/platform_wide/feature_flags/about.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
  _docs/_developer_guide/platform_wide/feature_flags/use_cases.md
  _docs/_developer_guide/platform_wide/sending_test_messages.md
  _docs/_docs_pages/robots.txt
  _docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
  _docs/_help/release_notes/2017/august.md
  _docs/_help/release_notes/2022/11_15_22.md
  _docs/_hidden/private_betas/conversions_dashboard_v2.md
  _docs/_hidden/private_betas/copying_to_workspace.md
  _docs/_home/templates_old/api_glossary.md
  _docs/_partners/canvas_steps/facebook_audience_sync.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/heap.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack/rudderstack_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/treasure_data/treasure_data_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/mozart_data.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/teams.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/creating_campaign.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
  _docs/_user_guide/message_building_by_channel/email/about.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _docs/_user_guide/message_building_by_channel/email/email_setup.md
  _docs/_user_guide/message_building_by_channel/email/email_setup/email_validation.md
  _docs/_user_guide/message_building_by_channel/email/email_setup/ip_warming.md
  _docs/_user_guide/message_building_by_channel/email/html_editor/gmail_promotions_tab.md
  _docs/_user_guide/message_building_by_channel/email/transactional_message_api_campaign.md
  _docs/_user_guide/message_building_by_channel/whatsapp.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_best_practices.md
  _docs/_user_guide/onboarding_with_braze/learning_to_use_braze.md
  _docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
  _docs/_user_guide/sage_ai/generative_ai/ai_content_qa.md
  _docs/_user_guide/sage_ai/intelligence/intelligent_timing.md
  _lang/fr/_help/release_notes/2017/august.md
  assets/img/feature_flags/feature-flags-filter-name.png
  assets/img/feature_flags/feature-flags-filter-selection.png
  assets/img/feature_flags/feature-flags-manage-permission.png
  assets/img/whatsapp/whatsapp_block_report.png
  assets/img/whatsapp/whatsapp_unsubscribe.png
  assets/img_archive/conversions2_funnel.png
  assets/img_archive/scenario1.png
  assets/img_archive/scenario2.png
  assets/img_archive/team_permissions_scenario1.gif
  assets/img_archive/team_permissions_scenario2.gif
  assets/js/broken_redirect_list.js
  vercel.json
Labels: cla-signed, Deploy

#5666 Content card banner
  _docs/_developer_guide/customization_guides/content_cards.md
  _docs/_developer_guide/customization_guides/content_cards/creating_custom_content_cards.md
  _docs/_developer_guide/customization_guides/content_cards/customizing_behavior.md
  _docs/_developer_guide/customization_guides/content_cards/customizing_styles.md
  _docs/_developer_guide/customization_guides/content_cards/examples.md
  _docs/_developer_guide/customization_guides/content_cards/examples/banner.md
  _docs/_developer_guide/customization_guides/content_cards/examples/carousel_view.md
  _docs/_developer_guide/customization_guides/content_cards/examples/message_inbox.md
  _docs/_developer_guide/customization_guides/customization_overview.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/integration.md
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
  assets/img/content_cards/content-card-message-inbox-with-kvps.png
  assets/js/broken_redirect_list.js
  assets/js/developer_nav.js
Labels: status: in progress, cla-signed

#5961 Update post_users_merge.md
  _docs/_api/endpoints/user_data/post_users_merge.md
Labels: cla-signed

#5954 Document prioritziation for merging users by email
  _docs/_api/endpoints/user_data/post_users_merge.md
Labels: cla-signed

#5963 Fixing YAML spacing
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#5964 Leftover deploy pt. 2 - August 10, 2023
  _docs/_api/endpoints/user_data/post_users_merge.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed, Deploy

#5962 BD-2360 Add link to React Native doc
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
Labels: cla-signed

#5965 BD-2358 Update Currents partners page
  _docs/_user_guide/data_and_analytics/braze_currents/available_partners.md
Labels: cla-signed

#5883 Create ios_17.md
  _docs/_developer_guide/platform_integration_guides/swift/ios_17.md
Labels: status: on hold / do not merge, cla-signed

#5968 Updates for curly brackets - Pt. 1
  _docs/_api/identifier_types.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/roku/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/web/amp_support.md
  _docs/_developer_guide/platform_wide/sending_test_messages.md
  _docs/_help/release_notes/2019/july.md
  _docs/_help/release_notes/2020/may.md
  _docs/_partners/message_personalization/dynamic_content/certona.md
  _docs/_user_guide/message_building_by_channel/webhooks/braze_to_braze_webhooks.md
Labels: cla-signed

#5967 BD-2281 Update Current Docs about user IDs
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
Labels: cla-signed

#5937 BD-2344: Push Max EA
  _docs/_user_guide/message_building_by_channel/push/android/push_max.md
  assets/img_archive/push_max_campaigns.png
  assets/img_archive/push_max_canvas.png
  assets/img_archive/time_to_live.png
Labels: cla-signed

#5970 Update aliasing.md
  _includes/archive/setting_user_ids/aliasing.md
Labels: cla-signed

#5972 BD-2359: Add detail for target entry audience
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
Labels: cla-signed

#5973 Update nested_custom_attribute_support.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
Labels: cla-signed

#5975 404 audit
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/overview.md
  _docs/_developer_guide/platform_wide/sending_test_messages.md
  _docs/_help/help_articles/account/locked_out.md
  _docs/_help/help_articles/segments/segmentation_logic_with_and_or.md
  _docs/_help/release_notes/2019/november.md
  _docs/_help/release_notes/2020/july.md
  _docs/_help/release_notes/2020/october.md
  _docs/_help/release_notes/2020/september.md
  _docs/_help/release_notes/2021/october.md
  _docs/_help/release_notes/2023/12_13_22.md
  _docs/_partners/message_orchestration/additional_channels/messaging/line.md
  _docs/_partners/message_orchestration/additional_channels/messaging/messenger.md
  _docs/_user_guide/data_and_analytics/creating_a_formula.md
  _docs/_user_guide/data_and_analytics/tracking/email_tracking.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/conversion_events.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/scheduled_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/segments/segment_insights.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
  _docs/_user_guide/message_building_by_channel/email/apple_mail/mpp.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/email_styling.md
  _docs/_user_guide/message_building_by_channel/email/faq.md
  _docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#5976 Deploy pt. 2 - August 15, 2023
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/overview.md
  _docs/_developer_guide/platform_wide/sending_test_messages.md
  _docs/_help/help_articles/account/locked_out.md
  _docs/_help/help_articles/segments/segmentation_logic_with_and_or.md
  _docs/_help/release_notes/2019/november.md
  _docs/_help/release_notes/2020/july.md
  _docs/_help/release_notes/2020/october.md
  _docs/_help/release_notes/2020/september.md
  _docs/_help/release_notes/2021/october.md
  _docs/_help/release_notes/2023/12_13_22.md
  _docs/_partners/message_orchestration/additional_channels/messaging/line.md
  _docs/_partners/message_orchestration/additional_channels/messaging/messenger.md
  _docs/_user_guide/data_and_analytics/creating_a_formula.md
  _docs/_user_guide/data_and_analytics/tracking/email_tracking.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/conversion_events.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/scheduled_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/segments/segment_insights.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
  _docs/_user_guide/message_building_by_channel/email/apple_mail/mpp.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/email_styling.md
  _docs/_user_guide/message_building_by_channel/email/faq.md
  _docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md
  assets/js/broken_redirect_list.js
Labels: Deploy

#5979 Fix small typo
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
  _lang/fr/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
Labels: cla-signed

#5977 Feedback update 202308
  _config.yml
  _data/i18n.yml
  _docs/_docs_pages/cla.md
  _docs/_hidden/other/documentation_request.md
  _docs/_hidden/other/support_contact.md
  _includes/feedback.html
  _lang/fr/_hidden/other/documentation_request.md
  assets/css/_feedback.scss
  assets/js/feedback.js
Labels: cla-signed

#5987 Update prediction_quality.md
  _docs/_user_guide/sage_ai/predictive_suite/predictive_churn/prediction_analytics/prediction_quality.md
Labels: cla-signed

#5988 Clarify omitted media item for copying across workspaces
  _docs/_hidden/private_betas/copying_to_workspace.md
Labels: cla-signed

#5938 BD-2342: Authentication and encryption tables for email deliverability GA
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
Labels: cla-signed

#5989 Minor edits
  _docs/_hidden/private_betas/copying_to_workspace.md
Labels: cla-signed

#5783 BD-2271: Content Block width and email template width styling for drag-and-drop email
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
  assets/img_archive/dnd_content_block_width.png
  assets/img_archive/dnd_email_template_width.png
Labels: status: in progress, cla-signed

#5990 Update Segment Extensions
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  assets/img/segment/property5.png
  assets/img/segment/segment_extension1.png
Labels: cla-signed

#5994 Minor SSO edits
  _docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/okta.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/onelogin.md
Labels: cla-signed

#5996 Fix extra support question
  _docs/_hidden/other/support_contact.md
Labels: cla-signed

#5995 Leftover deploy - August 17, 2023
  _config.yml
  _data/i18n.yml
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
  _docs/_docs_pages/cla.md
  _docs/_hidden/other/documentation_request.md
  _docs/_hidden/other/support_contact.md
  _docs/_hidden/private_betas/copying_to_workspace.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/okta.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/onelogin.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/set_up.md
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
  _docs/_user_guide/sage_ai/predictive_suite/predictive_churn/prediction_analytics/prediction_quality.md
  _includes/feedback.html
  _lang/fr/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
  _lang/fr/_hidden/other/documentation_request.md
  assets/css/_feedback.scss
  assets/img/segment/property5.png
  assets/img/segment/segment_extension1.png
  assets/img_archive/dnd_content_block_width.png
  assets/img_archive/dnd_email_template_width.png
  assets/js/feedback.js
Labels: cla-signed

#5998 Task-based edit Amazon S3 to Snowflake
  _docs/_user_guide/data_and_analytics/braze_currents/s3_to_snowflake.md
Labels: cla-signed

#5999 BD-2374 Update key
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
Labels: cla-signed

#6000 Task-based edit export Canvas data
  _docs/_user_guide/data_and_analytics/export_braze_data/export_canvas_data.md
Labels: cla-signed

#6001 CO-1825 CO-1900 Increase rate limits on catalogs API endpoint.
  _docs/_api/api_limits.md
  _includes/rate_limits.md
Labels: cla-signed

#6004 BD-2375 Custom Modal with CSS broken link
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize.md
Labels: cla-signed

#5953 BD-2354 Add click tracking
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
  _docs/_user_guide/sage_ai/intelligence/intelligent_channel.md
Labels: cla-signed

#6003 Task-based edits Sending Test Messages
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md
Labels: cla-signed

#6006 BD-2370 Segment partner article update
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
Labels: cla-signed

#6008 Another redirect for intelligence
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6010 BD-2372: Replace reference to API docs with API identifier docs
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/completing_integration.md
Labels: cla-signed

#6007 Update sdk_authentication.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
Labels: cla-signed

#5229 Content Card Developer Refresh
  _docs/_developer_guide/customization_guides.md
  _docs/_developer_guide/customization_guides/content_cards.md
  _docs/_developer_guide/customization_guides/content_cards/creating_custom_content_cards.md
  _docs/_developer_guide/customization_guides/content_cards/customizing_behavior.md
  _docs/_developer_guide/customization_guides/content_cards/customizing_feed.md
  _docs/_developer_guide/customization_guides/content_cards/customizing_styles.md
  _docs/_developer_guide/customization_guides/content_cards/logging_analytics.md
  _docs/_developer_guide/customization_guides/customization_overview.md
  _docs/_developer_guide/disclosures.md
  _docs/_developer_guide/platform_integration_guides.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/GIFs.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/badges.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/custom_styling.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/default_feed.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/handling_clicks_manually.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/key_value_pairs.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/read_and_unread.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/swipe_to_dismiss.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/use_cases.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/use_cases/carousel_view.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/multiple_feeds.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/refreshing_the_feed.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/customization/badges.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/customization/carousel_view.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/customization/customizing_feed.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/customization/handling_clicks_manually.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/customization/read_unread_indicators.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/multiple_feeds.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization/badges.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization/custom_styling.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization/custom_ui.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization/key_value_pairs.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization/read_and_unread.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/multiple_feeds.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/refreshing_the_feed.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/content-cards_in_canvas.md
  _docs/_user_guide/message_building_by_channel/content_cards.md
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/content_cards/creative_details.md
  _docs/_user_guide/message_building_by_channel/content_cards/customize.md
  assets/img/content_cards/content-card-customization-attributes.png
  assets/img/content_cards/content-card-customization-empty.png
  assets/img/content_cards/content-card-message-inbox-with-kvps.png
  assets/js/broken_redirect_list.js
  assets/js/developer_nav.js
Labels: status: in progress, cla-signed

#6011 Update partnership guidelines
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
  assets/img/partner_template/partnership_clone.png
  assets/img/partner_template/partnership_fork.png
Labels: cla-signed

#6012 BD-2377: Clarify message_extras is not available for IAMs
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
Labels: cla-signed

#6015 BD-2373 Image nuance
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/slideup.md
Labels: cla-signed

#6018 Update Puma to 6.31
  Gemfile.lock
Labels: cla-signed

#6017 BD-2380: Estimated real open rate EA
  _includes/campaign_analytics.md
Labels: cla-signed

#6016 August 2023 release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023.md
  _docs/_help/release_notes/2023/8_22_23.md
Labels: cla-signed

#6020 Fix wording
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023/8_22_23.md
Labels: cla-signed

#6022 Update post_users_merge.md
  _docs/_api/endpoints/user_data/post_users_merge.md
Labels: cla-signed

#6023 BD-2381 Search by user alias
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
Labels: cla-signed

#6021 BD-2382 Add uBlock callout
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
Labels: cla-signed

#6002 [SDK-4023] Public docs for disabling dark mode in Content Cards and IAMs in ObjC
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization/custom_styling.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization/handling_in_app_display.md
Labels: cla-signed

#6025 fix 404 tracking
  _layouts/broken_page.html
Labels: cla-signed

#6027 Remove duplciate filter and fix missing punctuation
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#6014 BD-2379: Save custom template EA [MERGE 8/24]
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  assets/img_archive/dnd_iam_save_as_template.png
  assets/img_archive/dnd_iam_select_template.png
Labels: cla-signed

#6029 Update local_connected_content_variables.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
Labels: cla-signed

#6030 Update time_based_campaign.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/time_based_campaign.md
Labels: cla-signed

#6026 Antavo Loyalty Cloud - Partner Docs
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/channel_extensions.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/antavo.md
  assets/img/antavo/braze_profile.png
  assets/img/antavo/connect_braze.png
  assets/img/antavo/data_field_mapping.png
Labels: cla-signed, Braze Partnerships

#5980 Ketch - Partner Docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/ketch.md
  _docs/_partners/home.md
  assets/img/ketch/ketch1.png
Labels: cla-signed, Braze Partnerships

#6034 BD-2384 Export CSV
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#6035 BD-2390: Update catalog results and selections limits
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/selections.md
Labels: cla-signed

#6009 BD-2330: Correcting behavior for selecting a notification channel
  _docs/_user_guide/message_building_by_channel/push/android/notification_channels.md
Labels: cla-signed

#6033 BD-2386: Add Meta experiment information from Legal
  _docs/_user_guide/message_building_by_channel/whatsapp.md
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/experiments.md
Labels: cla-signed

#6013 OfferFit partner docs
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content.md
  _docs/_partners/message_personalization/dynamic_content/offerfit.md
  assets/img/offerfit/of_integration_workflow.png
  assets/img/offerfit/of_use_case_example.png
Labels: cla-signed

#6037 Update sms_double_opt_in.md
  _docs/_hidden/private_betas/sms_double_opt_in.md
Labels: cla-signed

#6039 Clean up: Changing "info" into "information"
  _docs/_api/endpoints/user_data/post_user_identify.md
  _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
  _docs/_help/help_articles/data/blocklisting_deletion.md
  _docs/_help/release_notes/2021/december.md
  _docs/_home/templates/get_endpoint.md
  _docs/_home/templates/post_endpoint.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
  _docs/_partners/message_orchestration/channel_extensions/surveys/iterate.md
  _docs/_user_guide/administrative/app_settings/company_settings/automated_user_provisioning.md
  _docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md
  _docs/_user_guide/message_building_by_channel/email/inbox_vision.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md
  _docs/_user_guide/sage_ai/predictive_suite/predictive_churn/creating_a_churn_prediction.md
  _docs/_user_guide/sage_ai/predictive_suite/predictive_events/creating_an_event_prediction.md
Labels: cla-signed

#6028 Simon Data - Partner Docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/simondata.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/toovio.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/treasure_data.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/zeotap.md
  _docs/_partners/home.md
  assets/img/simon_data/BrazeActions.png
  assets/img/simon_data/BrazeTraitSyncing.png
  assets/img/simon_data/ConnecttoBraze.png
Labels: cla-signed

#6038 remove early access notice for bigquery
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
Labels: cla-signed

#6040 BD-2393 Liquid use case missing }
  _docs/_user_guide/personalization_and_dynamic_content/liquid/conditional_logic.md
Labels: cla-signed

#6042 Update dispatch_id wording.
  _docs/_help/help_articles/data/dispatch_id.md
Labels: cla-signed

#6044 BD-2395: Update Braze Learning links
  _docs/_user_guide/engagement_tools/canvas/get_started/canvas_outlines.md
Labels: cla-signed

#6047 BD-2394 Update Purchase Event article
  _docs/_api/objects_filters/purchase_object.md
Labels: cla-signed

#6048 Fixing an errant large image
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/targeting_users.md
Labels: cla-signed

#6050 [CLIP-751] SAML SSO: Clarify ‘Sign-on URL’ for different providers
  _docs/_user_guide/administrative/access_braze/single_sign_on/set_up.md
Labels: cla-signed

#6053 Update security_qualifications.md
  _docs/_developer_guide/disclosures/security_qualifications.md
Labels: cla-signed

#6024 DND IAM doc updates [MERGE 8/29]
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/editor_blocks.md
Labels: status: done, cla-signed

#6049 BD-2383: Hidden doc for new email engagement dashboard graphs
  _docs/_hidden/private_betas/email_engagement.md
  assets/img_archive/mailbox_provider_time_engagement.png
Labels: cla-signed

#6056 Update push_notifications.md
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
Labels: cla-signed

#6057 Update broken_redirect_list.js
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6058 Task-based edits Audience Paths
  _docs/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md
Labels: cla-signed

#6060 Push notifications patch
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
Labels: cla-signed

#6059 Task edit: DND content blocks
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
Labels: cla-signed

#6061 Deploy - August 29, 2023
  _docs/_api/endpoints/user_data/post_user_identify.md
  _docs/_api/objects_filters/purchase_object.md
  _docs/_developer_guide/disclosures/security_qualifications.md
  _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
  _docs/_help/help_articles/data/blocklisting_deletion.md
  _docs/_help/help_articles/data/dispatch_id.md
  _docs/_help/release_notes/2021/december.md
  _docs/_hidden/private_betas/email_engagement.md
  _docs/_hidden/private_betas/sms_double_opt_in.md
  _docs/_home/templates/get_endpoint.md
  _docs/_home/templates/post_endpoint.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/simondata.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/toovio.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/treasure_data.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/zeotap.md
  _docs/_partners/home.md
  _docs/_partners/message_orchestration/channel_extensions/surveys/iterate.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/set_up.md
  _docs/_user_guide/administrative/app_settings/company_settings/automated_user_provisioning.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
  _docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/targeting_users.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md
  _docs/_user_guide/engagement_tools/canvas/get_started/canvas_outlines.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
  _docs/_user_guide/message_building_by_channel/email/inbox_vision.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/editor_blocks.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/conditional_logic.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md
  _docs/_user_guide/sage_ai/predictive_suite/predictive_churn/creating_a_churn_prediction.md
  _docs/_user_guide/sage_ai/predictive_suite/predictive_events/creating_an_event_prediction.md
  assets/img/simon_data/BrazeActions.png
  assets/img/simon_data/BrazeTraitSyncing.png
  assets/img/simon_data/ConnecttoBraze.png
  assets/img_archive/mailbox_provider_time_engagement.png
  assets/js/broken_redirect_list.js
  assets/pdf/Braze_ISO_Cert.pdf
Labels: cla-signed, Deploy

#6062 new liquid tag just dropped (`${app.{api_id}}`)
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: cla-signed

#6063 Minor edits to User permissions
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#6046 [SDK-4063] Unity Appboy to Braze
  _docs/_developer_guide/platform_integration_guides/unity/push_notifications/adm_push_notifications.md
  _lang/fr/_developer_guide/platform_integration_guides/android/in-app_messaging/customization/custom_listeners.md
  _lang/fr/_developer_guide/platform_integration_guides/android/storage.md
  _lang/fr/_developer_guide/platform_integration_guides/cordova/cordova_integration.md
  _lang/fr/_developer_guide/platform_integration_guides/cordova/initial_sdk_setup/android.md
  _lang/fr/_developer_guide/platform_integration_guides/cordova/initial_sdk_setup/ios.md
  _lang/fr/_developer_guide/platform_integration_guides/unity/advanced_use_cases.md
  _lang/fr/_developer_guide/platform_integration_guides/unity/push_notifications/adm_push_notifications.md
  _lang/fr/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md
  _lang/fr/_includes/archive/android/gifs.md
Labels: cla-signed

#6064 reverts #6062
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: cla-signed

#6067 Task-based edit: Gmail Promotions
  _docs/_user_guide/message_building_by_channel/email/html_editor/gmail_promotions_tab.md
  assets/img/create-gmail-promo.png
  assets/img/gmail_promo_discount_details.png
  assets/img_archive/gmail_promo_discount.png
Labels: cla-signed

#6069 brazeLogging=true
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
Labels: cla-signed

#6045 update docs to include whatsapp events
  assets/download_file/data-sharing-raw-table-schemas.txt
Labels: cla-signed

#6041 Add new fields for message archiving
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
Labels: cla-signed

#5978 BD-2357: Updates for team-level campaign and Canvas approval permissions - MERGE 8/31
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_approval.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/canvas_approval.md
Labels: cla-signed

#6052 Redpoint - Partner Docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/redpoint.md
  _docs/_partners/home.md
  assets/img/redpoint/rpi_to_braze_append_export_format.png
  assets/img/redpoint/rpi_to_braze_auto_variables.png
  assets/img/redpoint/rpi_to_braze_build_braze_segment.png
  assets/img/redpoint/rpi_to_braze_channel_config_general.png
  assets/img/redpoint/rpi_to_braze_channel_config_post_execution.png
  assets/img/redpoint/rpi_to_braze_channel_config_specific.png
  assets/img/redpoint/rpi_to_braze_custom_attributes.png
  assets/img/redpoint/rpi_to_braze_doc_injector_mappings.png
  assets/img/redpoint/rpi_to_braze_export_directory_setup.png
  assets/img/redpoint/rpi_to_braze_export_format_config.png
  assets/img/redpoint/rpi_to_braze_record_example.png
  assets/img/redpoint/rpi_to_braze_rpi_canvas.png
  assets/img/redpoint/rpi_to_braze_upsert_export_format.png
Labels: cla-signed

#6071 Leftover Deploy - August 31, 2023
  _docs/_developer_guide/disclosures/security_qualifications.md
  _docs/_developer_guide/platform_integration_guides/unity/push_notifications/adm_push_notifications.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/redpoint.md
  _docs/_partners/home.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_approval.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/canvas_approval.md
  _docs/_user_guide/message_building_by_channel/email/html_editor/gmail_promotions_tab.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  _lang/fr/_developer_guide/platform_integration_guides/android/in-app_messaging/customization/custom_listeners.md
  _lang/fr/_developer_guide/platform_integration_guides/android/storage.md
  _lang/fr/_developer_guide/platform_integration_guides/cordova/cordova_integration.md
  _lang/fr/_developer_guide/platform_integration_guides/cordova/initial_sdk_setup/android.md
  _lang/fr/_developer_guide/platform_integration_guides/cordova/initial_sdk_setup/ios.md
  _lang/fr/_developer_guide/platform_integration_guides/unity/advanced_use_cases.md
  _lang/fr/_developer_guide/platform_integration_guides/unity/push_notifications/adm_push_notifications.md
  _lang/fr/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md
  _lang/fr/_includes/archive/android/gifs.md
  assets/download_file/data-sharing-raw-table-schemas.txt
  assets/img/create-gmail-promo.png
  assets/img/gmail_promo_discount_details.png
  assets/img/redpoint/rpi_to_braze_append_export_format.png
  assets/img/redpoint/rpi_to_braze_auto_variables.png
  assets/img/redpoint/rpi_to_braze_build_braze_segment.png
  assets/img/redpoint/rpi_to_braze_channel_config_general.png
  assets/img/redpoint/rpi_to_braze_channel_config_post_execution.png
  assets/img/redpoint/rpi_to_braze_channel_config_specific.png
  assets/img/redpoint/rpi_to_braze_custom_attributes.png
  assets/img/redpoint/rpi_to_braze_doc_injector_mappings.png
  assets/img/redpoint/rpi_to_braze_export_directory_setup.png
  assets/img/redpoint/rpi_to_braze_export_format_config.png
  assets/img/redpoint/rpi_to_braze_record_example.png
  assets/img/redpoint/rpi_to_braze_rpi_canvas.png
  assets/img/redpoint/rpi_to_braze_upsert_export_format.png
  assets/img_archive/gmail_promo_discount.png
Labels: cla-signed, Deploy

#6073 Update sync_catalogs_data.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md
Labels: cla-signed

#6075 BD-2404 Update Shopify requirements
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify.md
Labels: cla-signed

#6074 Message Activity Log
  _docs/_user_guide/personalization_and_dynamic_content/liquid/aborting_messages.md
Labels: cla-signed

#6076 BD-2403: Add Data Privacy Protection Framework link to Privacy Portal
  _docs/_user_guide/privacy_portal.md
Labels: cla-signed
