Repository braze-inc/braze-docs, pull requests merged in 2023-04, with the labels that each got.

#5175 [SDK-3529] Update RN recommended integration in public docs
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _lang/fr/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Labels: cla-signed

#5177 BD-2018: Remove twitter Liquid tag
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: cla-signed

#5134 Clarify /users/merge details
  _docs/_api/endpoints/user_data/post_users_merge.md
Labels: cla-signed

#4800 BD-1868: Updates to Gmail Promotion Setup feature
  _docs/_user_guide/message_building_by_channel/email/gmail_promotions_tab.md
  assets/img/create-gmail-promo.png
Labels: cla-signed

#5174 BD-2026: Add WhatsApp Phone Number page
  _docs/_user_guide/message_building_by_channel/whatsapp.md
  _docs/_user_guide/message_building_by_channel/whatsapp/opt-ins_and_opt-outs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/overview.md
  _docs/_user_guide/message_building_by_channel/whatsapp/quick_replies.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_phone_numbers.md
Labels: cla-signed

#5178 Update analytics.md
  _docs/_developer_guide/platform_integration_guides/xamarin/analytics.md
Labels: cla-signed

#5179 Update analytics.md
  _docs/_developer_guide/platform_integration_guides/react_native/analytics.md
Labels: cla-signed

#5181 Adding SMS to intelligent channel docs
  _docs/_user_guide/intelligence/intelligent_channel.md
Labels: cla-signed

#5183 Updating interactions list
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/campaign_connector.md
Labels: cla-signed

#5185 BD-2027: Add /users/track with email address EA
  _docs/_api/endpoints/user_data/post_user_track.md
Labels: cla-signed

#5184 BD-2029: Zeotap Symphony
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/zeotap.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/zeotap/symphony.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/zeotap/zeotap.md
  assets/img/zeotap/zeotap5.png
  assets/img/zeotap/zeotap6.jpg
  assets/img/zeotap/zeotap7.png
  assets/img/zeotap/zeotap8.png
Labels: cla-signed

#5187 BD-2030: Update Manage Approval Settings details
  _docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#5186 BD-2033: Update 2FA SSO security settings
  _docs/_user_guide/administrative/company_settings/security_settings.md
Labels: cla-signed

#5170 breadcrumbs tweaks
  _docs/_help/home.md
  _docs/_partners/data_and_infrastructure_agility.md
  _layouts/api_glossary.html
  _layouts/api_page.html
  _layouts/customer_behavior_events_glossary.html
  _layouts/doc_guide.html
  _layouts/documents.html
  _layouts/glossary_page.html
  _layouts/liquid_use_case_glossary.html
  _layouts/message_engagement_events_glossary.html
  _layouts/partner_page.html
  _layouts/self_help.html
  _layouts/user_guide.html
  assets/css/_api.scss
  assets/css/_content.scss
  assets/css/_dev_guide.scss
  assets/css/_glossary_page.scss
  assets/css/_partner_page.scss
  assets/css/_self_help.scss
  assets/css/_user_guide.scss
Labels: cla-signed

#5188 Release notes for April
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023.md
  _docs/_help/release_notes/2023/4_4_23.md
  assets/img/doc-breadcrumbs.png
Labels: cla-signed

#5198 Update prediction_faq.md
  _docs/_user_guide/predictive_suite/predictive_churn/prediction_faq.md
Labels: cla-signed

#5200 BD-2035: Update campaign abort event to be included in checkboxes
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#5199 Breadcrumbs fixes, assign dev_guide layout to hidden pages
  _docs/_hidden/other/airship_migration.md
  _docs/_hidden/other/core_endpoints.md
  _docs/_hidden/other/credit_ratios.md
  _docs/_hidden/other/devices_and_carriers.md
  _docs/_hidden/other/ephemeral_custom_events.md
  _docs/_hidden/other/handbooks.md
  _docs/_hidden/other/user_csv_lambda.md
  _docs/_hidden/private_betas/canvas_approval.md
  _docs/_hidden/private_betas/canvas_drafts.md
  _docs/_hidden/private_betas/canvas_version_history.md
  _docs/_hidden/private_betas/data_transformation.md
  _docs/_hidden/private_betas/dnd_content_blocks_preview.md
  _docs/_hidden/private_betas/idle_campaigns.md
  _docs/_hidden/private_betas/navigation.md
  _docs/_hidden/private_betas/pinterest_audience_sync.md
  _docs/_hidden/private_betas/preference_center.md
  _docs/_hidden/private_betas/snapchat_audience_sync.md
  _docs/_hidden/private_betas/sql_segments_tables.md
  _docs/_hidden/private_betas/tiktok.md
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
  _docs/_hidden/wip_partnerships/partnership_template.md
  assets/css/_api.scss
  assets/css/_dev_guide.scss
  assets/css/_user_guide.scss
Labels: cla-signed

#5201 BD-2036: Add Shopify user checkout flow behavior explanation
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
Labels: cla-signed

#5202 Add Okta screenshot
  _docs/_user_guide/administrative/access_braze/single_sign_on/okta.md
  assets/img/Okta/okta5.png
Labels: cla-signed

#5206 BD-2038: Documenting A/B testing caveat
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
Labels: cla-signed

#5204 Edits for Message extras Liquid tag
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
  assets/img_archive/message_extras1.png
  assets/img_archive/message_extras2.png
Labels: cla-signed

#5189 Update in-app_messaging.md
  _docs/_developer_guide/platform_integration_guides/tvos/in-app_messaging.md
Labels: cla-signed

#5192 [EINFRA-697] Update note on gmail local part. Requires 2 chars, not 5.
  _docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md
Labels: cla-signed

#5203 BD-2032: Updates to currents fields
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#5207 Fix current event formatting
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#5205 Leftover Deploy - April 6, 2023
  _docs/_developer_guide/platform_integration_guides/tvos/in-app_messaging.md
  _docs/_hidden/other/airship_migration.md
  _docs/_hidden/other/core_endpoints.md
  _docs/_hidden/other/credit_ratios.md
  _docs/_hidden/other/devices_and_carriers.md
  _docs/_hidden/other/ephemeral_custom_events.md
  _docs/_hidden/other/handbooks.md
  _docs/_hidden/other/user_csv_lambda.md
  _docs/_hidden/private_betas/canvas_approval.md
  _docs/_hidden/private_betas/canvas_drafts.md
  _docs/_hidden/private_betas/canvas_version_history.md
  _docs/_hidden/private_betas/data_transformation.md
  _docs/_hidden/private_betas/dnd_content_blocks_preview.md
  _docs/_hidden/private_betas/idle_campaigns.md
  _docs/_hidden/private_betas/navigation.md
  _docs/_hidden/private_betas/pinterest_audience_sync.md
  _docs/_hidden/private_betas/preference_center.md
  _docs/_hidden/private_betas/snapchat_audience_sync.md
  _docs/_hidden/private_betas/sql_segments_tables.md
  _docs/_hidden/private_betas/tiktok.md
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
  _docs/_hidden/wip_partnerships/partnership_template.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/okta.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
  _docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
  _docs/_user_guide/predictive_suite/predictive_churn/prediction_faq.md
  assets/css/_api.scss
  assets/css/_dev_guide.scss
  assets/css/_user_guide.scss
  assets/img/Okta/okta5.png
  assets/img_archive/message_extras1.png
  assets/img_archive/message_extras2.png
Labels: cla-signed, Deploy

#5193 GlobalLink Translation PR
  _docs/_home/styling_test_page.md
  _lang/fr/_home/static_video.md
  _lang/fr/_home/styling_test_page.md
  _lang/fr/_home/templates_old/tutorial_video.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
  _lang/fr/_user_guide/engagement_tools/campaigns/ideas_and_strategies.md
  _lang/fr/_user_guide/engagement_tools/campaigns/ideas_and_strategies/localizing_a_campaign.md
  _lang/fr/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_approval.md
  _lang/fr/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md
  _lang/fr/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
  _lang/fr/_user_guide/engagement_tools/canvas/ideas_and_strategies.md
  _lang/fr/_user_guide/engagement_tools/canvas/ideas_and_strategies/localization.md
  _lang/fr/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
  _lang/fr/_user_guide/engagement_tools/segments/user_profiles.md
  _lang/fr/_user_guide/engagement_tools/templates_and_media/media_library.md
  _lang/fr/_user_guide/intelligence/ai_copywriting.md
  _lang/fr/_user_guide/intelligence/faqs.md
  _lang/fr/_user_guide/intelligence/intelligent_timing.md
  _lang/fr/_user_guide/message_building_by_channel.md
  _lang/fr/_user_guide/message_building_by_channel/content_cards/create.md
  _lang/fr/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
  _lang/fr/_user_guide/message_building_by_channel/email/reporting_and_analytics/analytics_glossary.md
  _lang/fr/_user_guide/message_building_by_channel/email/templates/email_template.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/about.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/best_practices/prep_guide.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/create.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/creative_details/fullscreen.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/customize/html_in-app_messages.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _lang/fr/_user_guide/message_building_by_channel/push.md
  _lang/fr/_user_guide/message_building_by_channel/push/advanced_push_options/push_stories.md
  _lang/fr/_user_guide/message_building_by_channel/push/best_practices.md
  _lang/fr/_user_guide/message_building_by_channel/push/best_practices/detailed_push_preferences.md
  _lang/fr/_user_guide/message_building_by_channel/push/best_practices/push_primer_messages.md
  _lang/fr/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
  _lang/fr/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
  _lang/fr/_user_guide/message_building_by_channel/sms/campaign/retargeting.md
  _lang/fr/_user_guide/message_building_by_channel/sms/sms_subscription_group.md
  _lang/fr/_user_guide/message_building_by_channel/whatsapp.md
  _lang/fr/_user_guide/message_building_by_channel/whatsapp/create.md
  _lang/fr/_user_guide/message_building_by_channel/whatsapp/faqs.md
  _lang/fr/_user_guide/message_building_by_channel/whatsapp/opt-ins_and_opt-outs.md
  _lang/fr/_user_guide/message_building_by_channel/whatsapp/overview.md
  _lang/fr/_user_guide/message_building_by_channel/whatsapp/quick_replies.md
  _lang/fr/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
  _lang/fr/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign_analytics.md
  _lang/fr/_user_guide/onboarding_with_braze/web_sdk.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/catalogs.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
Labels: cla-signed

#5211 BD-2040: Switch "date" to "time"
  _docs/_help/help_articles/data/change_custom_data_type.md
Labels: cla-signed

#5212 BD-2039: Audit all currents events
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#5191 Navigation updates for React EA
  _docs/_hidden/private_betas/navigation.md
  assets/img/navigation/global_header_compare.png
  assets/img/navigation/global_header_new.png
  assets/img/navigation/sidebar_behavior.gif
  assets/img/navigation/sidebar_compare.png
  assets/img/navigation/sidebar_new.png
Labels: cla-signed

#5216 Include mentions of product carousel
  _docs/_user_guide/message_building_by_channel/email/gmail_promotions_tab.md
Labels: cla-signed

#5208 Help article edits
  _docs/_help/help_articles/account/locked_out.md
  _docs/_help/help_articles/api/attribute_name_id_across_sources.md
  _docs/_help/help_articles/campaigns_and_canvas/canvas_not_sending.md
  _docs/_help/help_articles/campaigns_and_canvas/conversions_low.md
  _docs/_help/help_articles/campaigns_and_canvas/locations_data_in_campaigns.md
  _docs/_help/help_articles/campaigns_and_canvas/using_custom_event_properties.md
  _docs/_help/help_articles/campaigns_and_canvas/using_event_logging.md
  _docs/_help/help_articles/data/blocklisting_deletion.md
  _docs/_help/help_articles/data/change_custom_data_type.md
  _docs/_help/help_articles/data/dispatch_id.md
  _docs/_help/help_articles/email/email_bounces.md
  _docs/_help/help_articles/push/push_error_codes.md
  _docs/_help/help_articles/push/push_token_migration.md
Labels: cla-signed

#5221 BD-2045: Remove note regarding Geofence package limitation
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/locations_and_geofences.md
  _docs/_user_guide/engagement_tools/locations_and_geofences.md
Labels: cla-signed

#5220 Link Audit - API and Partner Docs
  _docs/_api/basics.md
  _docs/_api/endpoints/export/user_data/post_users_global_control_group.md
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_api/endpoints/preference_center/put_update_preference_center.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
  _docs/_api/objects_filters/event_object.md
  _docs/_api/objects_filters/messaging/email_object.md
  _docs/_api/objects_filters/messaging/sms_object.md
  _docs/_api/objects_filters/messaging/whats_app_object.md
  _docs/_api/objects_filters/purchase_object.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/cordova/cordova_integration.md
  _docs/_developer_guide/platform_integration_guides/cordova/initial_sdk_setup/ios.md
  _docs/_developer_guide/platform_integration_guides/flutter/flutter_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/unity/push_notifications/android.md
  _docs/_developer_guide/platform_integration_guides/unity/sdk_integration/ios.md
  _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
  _docs/_developer_guide/platform_integration_guides/xamarin/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/xamarin/news_feed.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_developer_guide/platform_wide/tv_and_ott.md
  _docs/_hidden/archive_docs/android_12.md
  _docs/_hidden/archive_docs/ios_14.md
  _docs/_home/dp-technical-assistance.md
  _docs/_partners/data_and_infrastructure_agility/ab_testing/phrasee/phrasee_react.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/storyly.md
  _docs/_partners/data_and_infrastructure_agility/crash_analytics/apteligent.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack/rudderstack.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _docs/_partners/data_and_infrastructure_agility/support/pypestream.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/hightouch/hightouch_personalization_api.md
  _docs/_partners/data_and_infrastructure_agility/wrapper_sdks.md
  _docs/_partners/message_orchestration/additional_channels/calendar/rokt_calendar.md
  _docs/_partners/message_orchestration/additional_channels/direct_mail/inkit.md
  _docs/_partners/message_orchestration/attribution/adjust.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer_audiences.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/punchh.md
  _docs/_partners/message_personalization/dynamic_content/dynamic_yield.md
  _docs/_partners/message_personalization/dynamic_content/movable_ink.md
  _docs/_partners/message_personalization/location/bluedot.md
Labels: cla-signed

#5222 Fix incorrect article name in tile
  _docs/_user_guide/data_and_analytics/analytics.md
Labels: cla-signed

#5226 Update zoom.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/zoom.md
Labels: cla-signed

#5227 updated kotlin instructions for setting verbose logging
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
Labels: cla-signed

#5234 Verify and update push recommendations
  _docs/_user_guide/message_building_by_channel/push/about.md
Labels: cla-signed

#5228 BD-2037: Add specs to Push Stories
  _docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_stories.md
Labels: cla-signed

#5233 clarifying the FAQ for multiple WABA connections
  _docs/_user_guide/message_building_by_channel/whatsapp/faqs.md
Labels: cla-signed

#5236 Final Link Audit, User Guide
  _docs/_user_guide/data_and_analytics/analytics/email_performance_dashboard.md
  _docs/_user_guide/data_and_analytics/braze_currents/s3_to_snowflake.md
  _docs/_user_guide/data_and_analytics/creating_a_formula.md
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md
  _docs/_user_guide/engagement_tools/testing/global_control_group.md
  _docs/_user_guide/message_building_by_channel/email/email_private_relay_apple_SSO.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
  _docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
Labels: cla-signed

#5237 Edits for Gmail Promotion Setup
  _docs/_user_guide/message_building_by_channel/email/gmail_promotions_tab.md
  assets/img_archive/gmail_promo_discount.png
  assets/img_archive/product_carousel.png
Labels: cla-signed

#5239 Update nokogiri to 1.14.3
  Gemfile.lock
Labels: cla-signed

#5240 fix broken links
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/swipe_to_dismiss.md
  _docs/_developer_guide/platform_integration_guides/android/storage.md
  _docs/_developer_guide/platform_integration_guides/cordova/initial_sdk_setup/android.md
  _docs/_developer_guide/platform_integration_guides/unity/content_cards.md
  _docs/_developer_guide/platform_integration_guides/unity/news_feed.md
Labels: cla-signed

#5242 BD-2048: Currents tweaks
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#5244 BD-2051: Fix typo
  _docs/_hidden/private_betas/data_transformation.md
Labels: cla-signed

#5209 Most Popular Products docs page
  _docs/_hidden/private_betas/recommendations.md
  assets/img/most_popular_products.png
  assets/img/most_popular_products_personalize.png
Labels: cla-signed

#5245 Update dnd_content_blocks.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
Labels: cla-signed

#5241 BD-2046: Adobe event forwarding documentation
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/actioniq.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/adobe.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/adobe/adobe.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/adobe/event_forwarding_extension.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/amperity.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/blueconic.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/dynamics_365_customer_insights.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/lexer.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mparticle.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/octolis.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/toovio.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/treasure_data.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/zeotap.md
  assets/img/efe.png
  assets/img/efe2.png
Labels: cla-signed

#5247 BD-2041: Clarify details about Message step
  _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
Labels: cla-signed

#5243 Reorganize Email section
  _docs/_user_guide/message_building_by_channel/email.md
  _docs/_user_guide/message_building_by_channel/email/amphtml.md
  _docs/_user_guide/message_building_by_channel/email/apple_mail.md
  _docs/_user_guide/message_building_by_channel/email/apple_mail/email_private_relay_apple_SSO.md
  _docs/_user_guide/message_building_by_channel/email/apple_mail/mpp.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop.md
  _docs/_user_guide/message_building_by_channel/email/html_editor.md
  _docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/email/html_editor/css_inline.md
  _docs/_user_guide/message_building_by_channel/email/html_editor/gmail_promotions_tab.md
  _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
  _docs/_user_guide/message_building_by_channel/email/templates/html_email_template.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#5225 Data Transformation Update - MERGE 4/17
  _docs/_hidden/private_betas/data_transformation.md
  assets/img/data_transformation/data_transformation10.png
  assets/img/data_transformation/data_transformation11.png
  assets/img/data_transformation/data_transformation8.png
  assets/img/data_transformation/data_transformation9.png
Labels: cla-signed

#5248 Deploy - April 17, 2023
  _docs/_hidden/private_betas/data_transformation.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
  _docs/_user_guide/message_building_by_channel/email.md
  _docs/_user_guide/message_building_by_channel/email/amphtml.md
  _docs/_user_guide/message_building_by_channel/email/apple_mail.md
  _docs/_user_guide/message_building_by_channel/email/apple_mail/email_private_relay_apple_SSO.md
  _docs/_user_guide/message_building_by_channel/email/apple_mail/mpp.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop.md
  _docs/_user_guide/message_building_by_channel/email/html_editor.md
  _docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/email/html_editor/css_inline.md
  _docs/_user_guide/message_building_by_channel/email/html_editor/gmail_promotions_tab.md
  _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
  _docs/_user_guide/message_building_by_channel/email/templates/html_email_template.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
  assets/img/data_transformation/data_transformation10.png
  assets/img/data_transformation/data_transformation11.png
  assets/img/data_transformation/data_transformation8.png
  assets/img/data_transformation/data_transformation9.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#5249 User guide Introduction -> Home, fix duplicate IAM alias
  _docs/_user_guide/introduction.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional.md
Labels: cla-signed

#5251 BD-2050: Update "Sending messages within specific hours" Section for Intelligent Timing
  _docs/_user_guide/intelligence/intelligent_timing.md
Labels: cla-signed

#5253 BD-2049: Update AppsFlyer broken link
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
Labels: cla-signed

#5255 Update empty_content_card_feed.md
  _docs/_help/help_articles/content_cards/empty_content_card_feed.md
Labels: cla-signed

#5256 Add anchor link
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
Labels: cla-signed

#5238 Update to blocklist in Android IAM registration docs
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
Labels: cla-signed

#5260 BD-2053: Add EA banner for updating subscription group status
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
Labels: cla-signed

#5261 BD-2055: Add more info for 5XX errors
  _docs/_api/errors.md
Labels: cla-signed

#5057 [SDK-3028] Add advanced used cases for Swift
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/android_google_tag_manager.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/beacon_integration.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/localization.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/google_tag_manager.md
  _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/beacon_integration.md
  _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/fine_network_traffic_control.md
  _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/google_tag_manager.md
  _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
  _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/localization.md
  _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/locations_and_geofences.md
  _docs/_partners/message_personalization/location/gimbal.md
  _docs/_user_guide/engagement_tools/segments.md
  _docs/_user_guide/engagement_tools/segments/beacon_support.md
  _docs/_user_guide/engagement_tools/segments/location_targeting.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#5266 BD-2057 and BD-2058: Updates to Android GIFs customization articles
  _includes/archive/android/gifs.md
Labels: cla-signed

#5268 Update message_extras.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
Labels: cla-signed

#5223 Deliverability Center EA - MERGE 4/20
  _docs/_user_guide/data_and_analytics/analytics.md
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
  assets/img_archive/deliverability_center1.png
  assets/img_archive/deliverability_center2.png
Labels: cla-signed

#5267 Clarify Content Block behavior for drag and drop vs Liquid
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
Labels: cla-signed

#5235 [SDK-3289] Update miscellaneous references and code snippets for Swift SDK
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
Labels: cla-signed

#5273 Currents fields updates
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#5274 BD-2061: Fix broken link
  _docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
Labels: cla-signed

#5275 Leftover Deploy - April 20, 2023
  _docs/_api/errors.md
  _docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
  _docs/_user_guide/data_and_analytics/analytics.md
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
  _includes/archive/android/gifs.md
  assets/img_archive/deliverability_center1.png
  assets/img_archive/deliverability_center2.png
Labels: cla-signed, Deploy

#5276 BD-2062: Update request to PUT
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/put_update_catalog_items.md
Labels: cla-signed

#5278 Fix typos in Cloud Data Ingestion article
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion.md
Labels: cla-signed

#5269 Update nested_custom_attribute_support.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
Labels: cla-signed

#5280 GlobalLink Translation PR
  _lang/fr/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
Labels: cla-signed

#5281 GlobalLink Translation PR
  _lang/fr/_developer_guide/platform_integration_guides/web/cookies_and_storage.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
Labels: cla-signed

#5282 BD-2065: Update calendar days to 24-48
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#5270 Update array_of_objects.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md
Labels: cla-signed

#5285 Remove push primer prerequisites
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
Labels: cla-signed

#5288 Typo in RudderStack Docs
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack/rudderstack_for_currents.md
Labels: cla-signed

#5289 Query Builder GA
  _docs/_user_guide/data_and_analytics/query_builder.md
  _docs/_user_guide/data_and_analytics/query_builder/custom_sql.md
  assets/img_archive/query_builder.png
  assets/img_archive/query_builder_credits.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, release notes

#5279 BD-2060: Include info for authentication for email file attachments
  _docs/_api/objects_filters/messaging/email_object.md
Labels: cla-signed

#5294 [DLK-931] Update data sharing raw table schemas to latest
  assets/download_file/data-sharing-raw-table-schemas.txt
Labels: cla-signed

#5291 Update sql_segments.md
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
Labels: cla-signed

#5290 BD-2068: Clarify race conditions scenario
  _docs/_user_guide/engagement_tools/testing/race_conditions.md
Labels: cla-signed

#5292 BD-2071: Clarify limit for time_to_live
  _docs/_api/objects_filters/messaging/android_object.md
Labels: cla-signed

#5296 BD-2063: Add redirect link for frequency capping
  assets/js/broken_redirect_list.js
Labels: cla-signed

#5297 [MOPS-2956] Change Abort event documentation to reflect actual behavior
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#5299 BD-2067: Add link to Safari mobile web push in general web push doc
  _docs/_user_guide/message_building_by_channel/push/web.md
Labels: cla-signed

#5277 [SDK-3556] Add rate limiting note for `requestContentCardsRefresh` (iOS, Android, Web)
  _docs/_developer_guide/platform_integration_guides/android/content_cards/refreshing_the_feed.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/refreshing_the_feed.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/refreshing_the_feed.md
Labels: cla-signed

#5301 Revert "[SDK-3556] Add rate limiting note for `requestContentCardsRefresh` (iOS, Android, Web)"
  _docs/_developer_guide/platform_integration_guides/android/content_cards/refreshing_the_feed.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/refreshing_the_feed.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/refreshing_the_feed.md
Labels: cla-signed

#5286 BD-2047: Update slideup docs
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/slideup.md
  assets/img/slideup-large-viewport.png
  assets/img/slideup-spec.png
  assets/img/slideup-tablet.png
Labels: cla-signed

#5305 Style audit for units of measurement
  _docs/_api/endpoints/user_data.md
  _docs/_api/objects_filters/event_object.md
  _docs/_api/objects_filters/messaging/email_object.md
  _docs/_api/objects_filters/purchase_object.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/overview.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/customization/custom_styling.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/customization/custom_styling.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/integration.md
  _docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
  _docs/_hidden/archive_docs/previous_in-app_message_generations.md
  _docs/_hidden/other/user_csv_lambda.md
  _docs/_user_guide/administrative/access_braze/sdk_endpoints.md
  _docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/engagement_tools/news_feed/creating_a_news_feed_item.md
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/content_cards/creative_details.md
  _docs/_user_guide/message_building_by_channel/email/amphtml.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/email_styling.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/guidelines_and_tips.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
  _docs/_user_guide/message_building_by_channel/email/templates/html_email_template.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/fullscreen.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/modal.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/slideup.md
  _docs/_user_guide/message_building_by_channel/push/about.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/message_format.md
  _docs/_user_guide/message_building_by_channel/push/ios/rich_notifications.md
  _docs/_user_guide/message_building_by_channel/sms/mms/about_mms.md
  _docs/_user_guide/message_building_by_channel/sms/mms/contact_card.md
  _docs/_user_guide/message_building_by_channel/sms/mms/create.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
  _lang/fr/_api/objects_filters/messaging/email_object.md
Labels: cla-signed

#5306 Typo in prediction_faq.md
  _docs/_user_guide/predictive_suite/predictive_churn/prediction_faq.md
Labels: cla-signed

#5304 Added missing mixpanel email events
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
Labels: cla-signed

#5293 Liquid FAQ and related edits
  _docs/_help/faqs.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/conditional_logic.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/faq.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/operators.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: cla-signed

#5309 SDK-3646
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization/custom_listeners.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/android/sample_apps.md
  _docs/_developer_guide/platform_integration_guides/android/storage.md
  _includes/archive/android/universal_deep_link_delegate.md
Labels: cla-signed

#5312 Update WIP_guidelines.md for new ISV partner prcoesses
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
Labels: cla-signed

#5313 Update message_extras.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
Labels: cla-signed

#5263 BD-2054: Update limitations for catalogs - MERGE 4/27
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/selections.md
Labels: cla-signed

#5315 Move CDI to data and analytics section
  _docs/_user_guide/data_and_analytics.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/redshift.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/snowflake.md
  _docs/_user_guide/data_and_analytics/user_data_collection.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#5258 Update SQL Segments with credits information
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
  assets/img_archive/sql_segments_credits.png
Labels: cla-signed

#5320 Update html_in-app_messages.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize/html_in-app_messages.md
Labels: cla-signed

#5316 BD-2077: Update "text" to "paragraph"
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
Labels: cla-signed

#5323 BD-1848: Link to push primers in Android push integration
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
Labels: cla-signed

#5322 BD-2081: Canvas version history GA
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/archiving_canvases.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/canvas_duplication.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/canvas_version_history.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
Labels: cla-signed

#5321 Retire braze instances
  _docs/_user_guide/administrative/access_braze.md
  _docs/_user_guide/administrative/access_braze/braze_instances.md
  _docs/_user_guide/administrative/access_braze/sdk_endpoints.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#5325 BD-2079: Update Segment.io docs links
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
Labels: cla-signed

#5326 BD-2064: Updates to Treasure Data query building
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/treasure_data.md
Labels: cla-signed

#5329 Punchh broken link fix
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/punchh.md
Labels: cla-signed

#5328 BD-2074: Update Push Enabled filter to include provisional push users
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#5327 BD-2056: Clarify CC first impressions requirements
  _docs/_user_guide/message_building_by_channel/content_cards/create/card_creation.md
Labels: cla-signed

#5318 BD-2066: Clarify null attribute values for Liquid
  _docs/_user_guide/personalization_and_dynamic_content/liquid/conditional_logic.md
Labels: cla-signed

#5332 Updates to Inkit integration steps
  _docs/_partners/message_orchestration/additional_channels/direct_mail/inkit.md
Labels: cla-signed

#5333 [SDK-3628] Clarify color is accent color
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
Labels: cla-signed

#5334 BD-2078: Add Canvas approval user permission details
  _docs/_hidden/private_betas/canvas_approval.md
  assets/img_archive/canvas_approval.png
  assets/img_archive/canvas_approval_user_permissions.png
Labels: cla-signed

#5335 BD-2083: Update Braze Learning path links for Liquid
  _docs/_user_guide/personalization_and_dynamic_content/liquid.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/faq.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md
Labels: cla-signed

#5336 BD-2084: Fix mentions of user subscription state for email
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#5317 BD-2075: Add "push_tokens" to fields_to_export chart
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
Labels: cla-signed

#5295 Include attachment details in email message archiving - MERGE 5/2
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
Labels: cla-signed

#5271 Update post_update_content_block.md to fix optional parameters
  _docs/_api/endpoints/templates/content_blocks_templates/post_update_content_block.md
Labels: cla-signed
