Repository braze-inc/braze-docs, pull requests merged in 2023-09, with the labels that each got.

#6077 `{{app.${api_id}}}` liquid tag
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: cla-signed

#6072 BD-2401 WhatsApp updates
  _docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
Labels: cla-signed

#6078 BD-2405 Add limitations to Shopify catalog article
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_catalogs.md
Labels: cla-signed

#6055 Redirect en path to root
  vercel.json
Labels: cla-signed

#5699 Global search EA
  _docs/_user_guide/administrative/access_braze.md
  _docs/_user_guide/administrative/access_braze/global_search.md
  assets/img_archive/global_search.png
Labels: cla-signed

#6079 Task-based edit: Security Settings
  _docs/_user_guide/administrative/app_settings/company_settings/security_settings.md
Labels: cla-signed

#6080 Task-based edit: Inbox Vision
  _docs/_user_guide/message_building_by_channel/email/inbox_vision.md
Labels: cla-signed

#6082 BD-2405 Quick fix with new info for ticket
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_catalogs.md
Labels: cla-signed

#6083 Task-based edit: User Permissions
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#6070 Refine Country Setting by API rules
  _docs/_api/objects_filters/user_attributes_object.md
Labels: cla-signed

#6065 BD-2366: Data transformation GA - MERGE 9/5
  _docs/_hidden/private_betas/data_transformation.md
  _docs/_user_guide/data_and_analytics.md
  _docs/_user_guide/data_and_analytics/data_transformation.md
  _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
  _docs/_user_guide/data_and_analytics/data_transformation/overview.md
  _docs/_user_guide/data_and_analytics/data_transformation/use_cases.md
  assets/img/data_transformation/data_transformation10.png
  assets/img/data_transformation/data_transformation3.png
Labels: cla-signed

#6085 Minor edits to feature flags FAQ
  _docs/_developer_guide/platform_wide/feature_flags/faq.md
Labels: cla-signed

#6032 BD-2385: Push Max and promotion codes caveat
  _docs/_user_guide/message_building_by_channel/push/android/push_max.md
Labels: cla-signed

#6084 Deploy - September 5, 2023
  _docs/_api/objects_filters/user_attributes_object.md
  _docs/_developer_guide/platform_wide/feature_flags/faq.md
  _docs/_hidden/private_betas/data_transformation.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_catalogs.md
  _docs/_user_guide/administrative/access_braze.md
  _docs/_user_guide/administrative/access_braze/global_search.md
  _docs/_user_guide/administrative/app_settings/company_settings/security_settings.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/data_and_analytics.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md
  _docs/_user_guide/data_and_analytics/data_transformation.md
  _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
  _docs/_user_guide/data_and_analytics/data_transformation/overview.md
  _docs/_user_guide/data_and_analytics/data_transformation/use_cases.md
  _docs/_user_guide/message_building_by_channel/email/inbox_vision.md
  _docs/_user_guide/message_building_by_channel/push/android/push_max.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/aborting_messages.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  _docs/_user_guide/privacy_portal.md
  assets/img/data_transformation/data_transformation10.png
  assets/img/data_transformation/data_transformation3.png
  assets/img_archive/global_search.png
  vercel.json
Labels: cla-signed, Deploy

#6086 Email as identifier updates to Data Transformation docs
  _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
  _docs/_user_guide/data_and_analytics/data_transformation/overview.md
Labels: cla-signed

#6087 Deploy pt. 2 - September 5, 2023
  _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
  _docs/_user_guide/data_and_analytics/data_transformation/overview.md
Labels: cla-signed, Deploy

#6090 BD-2411 Update RudderStack screenshot
  assets/img/RudderStack/braze_settings.png
Labels: cla-signed

#6089 BD-2407 add SMS legal disclaimer
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/user_phone_numbers.md
Labels: cla-signed

#6091 Edits to Data Transformation overview
  _docs/_user_guide/data_and_analytics/data_transformation/overview.md
Labels: cla-signed

#6092 liquid formatting
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: cla-signed

#6093 Task-based edit: Cloning Canvases
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
Labels: cla-signed

#6094 Update supported_personalization_tags.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: cla-signed

#6095 Update image in support doc
  _docs/_help/support.md
  assets/img_archive/get_help.png
Labels: cla-signed

#6096 BD-2396: Add image for email setup steps
  _docs/_user_guide/message_building_by_channel/email/email_setup/setting_up_ips_and_domains.md
  assets/img_archive/email_setup_rdns_records.png
Labels: cla-signed

#6098 Task-based edit: Custom Keyword Handling
  _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
  assets/img/sms/canvas_trigger.png
  assets/img/sms/keyword_edit2.png
  assets/img/sms/keyword_home.png
  assets/img/sms/sms_custom_keyword.png
  assets/img/sms/sms_custom_step.png
  assets/img/sms/sms_keywords.png
Labels: cla-signed

#6099 Fix support contact other and system not showing form.
  _docs/_hidden/other/support_contact.md
Labels: cla-signed

#6100 Update mparticle.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle.md
Labels: cla-signed

#6101 Remove mparticle from cohort import
  _docs/_partners/data_and_infrastructure_agility/cohort_import/mparticle.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6102 Added a note about determining SDK version through the dashboard
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
  assets/img/live-sdk-version.png
Labels: cla-signed

#6103 Leftover deploy - September 7, 2023
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
  _docs/_help/support.md
  _docs/_hidden/other/support_contact.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/mparticle.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle.md
  _docs/_user_guide/data_and_analytics/data_transformation/overview.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/search_campaigns.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
  _docs/_user_guide/message_building_by_channel/email/email_setup/setting_up_ips_and_domains.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/user_phone_numbers.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  assets/img/RudderStack/braze_settings.png
  assets/img/live-sdk-version.png
  assets/img/sms/canvas_trigger.png
  assets/img/sms/keyword_edit2.png
  assets/img/sms/keyword_home.png
  assets/img/sms/sms_custom_keyword.png
  assets/img/sms/sms_custom_step.png
  assets/img/sms/sms_keywords.png
  assets/img_archive/email_setup_rdns_records.png
  assets/img_archive/get_help.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#6104 BD-2414 Remove MMS Canadian references
  _docs/_user_guide/message_building_by_channel/sms/mms/mms_short_long_codes.md
Labels: cla-signed

#6105 Leftover Deploy Pt. 2 - September 7, 2023
  _docs/_user_guide/message_building_by_channel/sms/mms/mms_short_long_codes.md
Labels: cla-signed, Deploy

#6106 Q3 feedback - Deliverability Center typos
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
Labels: cla-signed

#6107 BD-2412 Clarify the Dismissal Date
  _docs/_api/endpoints/messaging/live_activity/update.md
Labels: cla-signed

#6110 BD-2415: Add email to key-value pairs intro
  _docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
Labels: cla-signed

#6109 BD-2409: Quick Push EA
  _docs/_hidden/private_betas/quick_push.md
  assets/img_archive/quick_push_1.png
  assets/img_archive/quick_push_2.png
  assets/img_archive/quick_push_3.png
Labels: cla-signed

#6115 Updated screenshots: Capturing Lapsing Users
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/capturing_lapsing_users.md
  assets/img_archive/2weeklapse1.png
  assets/img_archive/2weeklapse2.png
  assets/img_archive/2weeklapse3.png
  assets/img_archive/2weeklapse4.png
Labels: cla-signed

#6097 Task-based edit: Push Action Buttons
  _docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_action_buttons.md
Labels: cla-signed

#6116 Q3 Docs feedback: Seed Groups
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/targeting_users.md
Labels: cla-signed

#6117 Edits for Intelligent Selection
  _docs/_user_guide/sage_ai/intelligence/intelligent_selection.md
Labels: cla-signed

#6119 Edits to Internal Groups doc
  _docs/_user_guide/administrative/app_settings/internal_groups_tab.md
Labels: cla-signed

#6120 Fix API request URL
  _docs/_partners/message_personalization/location/accuweather.md
Labels: cla-signed

#6121 Fix API request URL pt. 2
  _docs/_partners/message_personalization/location/accuweather.md
Labels: cla-signed

#6118 BD-2057 pt2: Clarify only HTML IAMs don't need special libraries
  _includes/archive/android/gifs.md
Labels: cla-signed

#6123 BD-2420: Add rate limit callout for Cloud Data Ingestion
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
Labels: cla-signed

#6124 Fix Liquid Use Cases pt.1
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
Labels: cla-signed

#6125 Deploy - September 12, 2023
  _docs/_api/endpoints/messaging/live_activity/update.md
  _docs/_hidden/private_betas/quick_push.md
  _docs/_partners/message_personalization/location/accuweather.md
  _docs/_user_guide/administrative/app_settings/internal_groups_tab.md
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/targeting_users.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/capturing_lapsing_users.md
  _docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_action_buttons.md
  _docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
  _docs/_user_guide/sage_ai/generative_ai/ai_content_qa.md
  _docs/_user_guide/sage_ai/intelligence/intelligent_selection.md
  _includes/archive/android/gifs.md
  assets/img_archive/2weeklapse1.png
  assets/img_archive/2weeklapse2.png
  assets/img_archive/2weeklapse3.png
  assets/img_archive/2weeklapse4.png
  assets/img_archive/quick_push_1.png
  assets/img_archive/quick_push_2.png
  assets/img_archive/quick_push_3.png
Labels: cla-signed, Deploy

#6114 Update sdk_data_collection.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_user_guide/data_and_analytics/user_data_collection.md
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
Labels: cla-signed

#6127 BD-2418 updated short and long code throughput
  _includes/archive/short_and_long_codes.md
Labels: cla-signed

#6128 Expand customization guides by default
  _config.yml
Labels: cla-signed

#6129 BD-2419: Clarification for Content Card testing requirements
  _docs/_user_guide/message_building_by_channel/content_cards/testing.md
Labels: cla-signed

#6112 BD-2416: Clarify click action behavior in edge case
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization/behavior_on_click.md
  _docs/_developer_guide/platform_integration_guides/roku/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/behavior_on_click.md
Labels: cla-signed

#6131 BD-2422: Predictive Suite data point clarification
  _docs/_user_guide/sage_ai/predictive_suite.md
  _docs/_user_guide/sage_ai/predictive_suite/predictive_churn/messaging_users.md
  _docs/_user_guide/sage_ai/predictive_suite/predictive_events.md
  _docs/_user_guide/sage_ai/predictive_suite/predictive_events/messaging_users.md
  assets/img_archive/predictive_churn_filters.png
  assets/img_archive/predictive_event_filters.png
Labels: cla-signed

#6132 Liquid use case edits pt.2
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
Labels: cla-signed

#6133 Edits for drag-and-drop email editor articles
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _docs/_user_guide/message_building_by_channel/email/html_editor.md
  _docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
Labels: cla-signed

#6135 BD-2421: Add note for exit criteria
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/exit_criteria.md
Labels: cla-signed

#6134 Task-based edit: User Subscriptions
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#6140 BD-2423 Fix steps numbering - Zapier
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/zapier.md
Labels: cla-signed

#6142 Missing nav updates pt.2
  _docs/_api/objects_filters/messaging/email_object.md
  _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_help/help_articles/campaigns_and_canvas/using_custom_event_properties.md
  _docs/_home/static_video.md
  _docs/_home/templates_old/partner_page_template_video.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _docs/_partners/message_orchestration/additional_channels/calendar/rokt_calendar.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _docs/_user_guide/message_building_by_channel/sms/faqs.md
Labels: cla-signed

#6141 Q3 feedback: Updating web push article with use cases and more structure
  _docs/_user_guide/message_building_by_channel/push/web.md
Labels: cla-signed

#6145 BD-2429 Fix error in user permissions
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#6146 BD-2430: Add missing Data Transformation user permissions
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#6149 Add user permissions for feature flags and preference centers
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#6151 Typo fix and minor edits
  _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
Labels: cla-signed

#6154 Liquid Use Case edit pt.3
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
Labels: cla-signed

#6159 Revert "BD-2400: Sage Torchie EA"
  _docs/_hidden/private_betas/sage_torchie.md
  assets/img/sage_torchie/sage_torchie1.jpg
  assets/img/sage_torchie/sage_torchie2.png
  assets/img/sage_torchie/sage_torchie3.png
  assets/img/sage_torchie/sage_torchie4.png
  assets/img/sage_torchie/sage_torchie5.png
  assets/img/sage_torchie/sage_torchie6.png
  assets/img/sage_torchie/sage_torchie_icon.png
Labels: cla-signed

#6157 BD-2432: Connected Content limits cannot be increased
  _docs/_partners/isv_partners/best_practices.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
Labels: cla-signed

#6160 Deliverability Center GA
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
Labels: cla-signed

#6161 Add missing page title
  _docs/_user_guide/message_building_by_channel/content_cards/creative_details.md
Labels: cla-signed

#6152 BD-2428 Add Permissions Sets info to SCIM docs
  _docs/_api/endpoints/scim/delete_existing_dashboard_user.md
  _docs/_api/endpoints/scim/get_search_existing_dashboard_user.md
  _docs/_api/endpoints/scim/get_see_user_account_information.md
  _docs/_api/endpoints/scim/post_create_user_account.md
  _docs/_api/endpoints/scim/put_update_existing_user_account.md
  _docs/_hidden/misc_reference/scim_api_appendix.md
Labels: cla-signed

#6167 BD-2151 Clarify Message Archiving note
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
Labels: cla-signed

#6163 September release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023.md
  _docs/_help/release_notes/2023/9_19_23.md
Labels: cla-signed, release notes

#6169 Add app instances to glossary
  _docs/_user_guide/onboarding_with_braze/terms_to_know.md
Labels: cla-signed

#6166 Deploy - September 19, 2023
  _docs/_api/endpoints/scim/delete_existing_dashboard_user.md
  _docs/_api/endpoints/scim/get_search_existing_dashboard_user.md
  _docs/_api/endpoints/scim/get_see_user_account_information.md
  _docs/_api/endpoints/scim/post_create_user_account.md
  _docs/_api/endpoints/scim/put_update_existing_user_account.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/setting_delegates.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023.md
  _docs/_help/release_notes/2023/9_19_23.md
  _docs/_hidden/misc_reference/scim_api_appendix.md
  _docs/_hidden/private_betas/sage_torchie.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _docs/_partners/isv_partners/best_practices.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
  _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
  _docs/_user_guide/message_building_by_channel/content_cards/creative_details.md
  _docs/_user_guide/onboarding_with_braze/terms_to_know.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
  assets/img/sage_torchie/sage_torchie1.jpg
  assets/img/sage_torchie/sage_torchie2.png
  assets/img/sage_torchie/sage_torchie3.png
  assets/img/sage_torchie/sage_torchie4.png
  assets/img/sage_torchie/sage_torchie5.png
  assets/img/sage_torchie/sage_torchie6.png
  assets/img/sage_torchie/sage_torchie_icon.png
  assets/img_archive/deliverability_center_msnds.png
Labels: cla-signed, Deploy

#6170 Redirect ko to en
  vercel.json
Labels: cla-signed

#6148 Move language select
  _includes/header.html
  assets/css/_header.scss
Labels: cla-signed

#6172 Deploy pt.2 - September 19, 2023
  _includes/header.html
  assets/css/_header.scss
  vercel.json
Labels: cla-signed, Deploy

#6150 Update ios_17.md
  _docs/_developer_guide/platform_integration_guides/swift/ios_17.md
Labels: cla-signed

#6164 Update ios_17.md
  _docs/_developer_guide/platform_integration_guides/swift/ios_17.md
Labels: cla-signed

#6173 BD-2436 Fix list styling typo
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
Labels: cla-signed

#6174 Fix redirects for list-unsubscribe header
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6176 Update data_transformation.md
  _docs/_partners/isv_partners/data_transformation.md
Labels: cla-signed

#6175 Minor edits to Contributing to Braze docs help article
  _docs/_help/help_articles/docs/contribution.md
Labels: cla-signed

#6177 Update data_transformation.md
  _docs/_partners/isv_partners/data_transformation.md
Labels: cla-signed

#6165 Liquid use case pt.4
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
Labels: cla-signed

#6179 Liquid use case edit pt.5
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
Labels: cla-signed

#6181 Fix release notes year
  _docs/_help/release_notes/2023.md
Labels: cla-signed

#6184 rf/wafaq
  _docs/_user_guide/message_building_by_channel/whatsapp/faqs.md
Labels: cla-signed

#6185 Task-based edit: Managing Custom Data
  _docs/_user_guide/data_and_analytics/custom_data/managing_custom_data.md
  assets/img_archive/prepopulate_add.png
  assets/img_archive/prepopulate_page.png
Labels: cla-signed

#6186 BD-2443 WhatsApp added to subscription groups
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#6187 Deploy - September 20, 2023
  _docs/_developer_guide/platform_integration_guides/swift/ios_17.md
  _docs/_help/help_articles/docs/contribution.md
  _docs/_help/release_notes/2023.md
  _docs/_partners/isv_partners/data_transformation.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/custom_data/managing_custom_data.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
  _docs/_user_guide/message_building_by_channel/whatsapp/faqs.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
  assets/img_archive/prepopulate_add.png
  assets/img_archive/prepopulate_page.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6188 Style edits to iOS 17 upgrade guide
  _docs/_developer_guide/platform_integration_guides/swift/ios_17.md
Labels: cla-signed

#6189 Update heap.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/heap.md
Labels: cla-signed

#6190 Update amplitude_audiences.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_audiences.md
Labels: cla-signed

#6193 Update image reference
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_audiences.md
  assets/img/amplitude11.png
Labels: cla-signed

#6194 Update thoughtspot.md
  _docs/_partners/data_and_infrastructure_agility/analytics/thoughtspot.md
Labels: cla-signed

#6196 BD-2444 update Mixpanel redirect
  _docs/_partners/data_and_infrastructure_agility/cohort_import/mixpanel.md
Labels: cla-signed

#6197 Update sisu_data.md
  _docs/_partners/data_and_infrastructure_agility/business_intelligence/sisu_data.md
Labels: cla-signed

#6198 Remove "unknown" from language codes
  _docs/_user_guide/data_and_analytics/user_data_collection/language_codes.md
Labels: cla-signed

#6195 BD-2440 API Updates to include WhatsApp
  _docs/_api/endpoints/export/campaigns/get_campaign_analytics.md
Labels: cla-signed

#6200 BD-2445: Change deprecations from landing page to reference
  _docs/_help/release_notes/deprecations.md
Labels: cla-signed

#6199 Update sms_double_opt_in.md
  _docs/_hidden/private_betas/sms_double_opt_in.md
Labels: cla-signed

#6203 Leftover deploy - September 21, 2023
  _docs/_api/endpoints/export/campaigns/get_campaign_analytics.md
  _docs/_developer_guide/platform_integration_guides/swift/ios_17.md
  _docs/_help/release_notes/deprecations.md
  _docs/_hidden/private_betas/sms_double_opt_in.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_audiences.md
  _docs/_partners/data_and_infrastructure_agility/analytics/thoughtspot.md
  _docs/_partners/data_and_infrastructure_agility/business_intelligence/sisu_data.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/heap.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/mixpanel.md
  _docs/_user_guide/data_and_analytics/user_data_collection/language_codes.md
  assets/img/amplitude11.png
Labels: cla-signed

#6182 BD-2437: Campaign Interaction Data Retention EA
  _docs/_hidden/private_betas/campaign_data_retention.md
  assets/img/restore_interaction_data.png
Labels: cla-signed

#6204 Task-based edit: Facebook Audience Export
  _docs/_partners/message_orchestration/additional_channels/retargeting/facebook.md
Labels: cla-signed

#6205 BD-2446 update double opt-in best practices
  _docs/_user_guide/message_building_by_channel/sms/best_practices/opt-ins.md
  _docs/_user_guide/message_building_by_channel/sms/keywords.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/fuzzy_opt_out.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/sms_double_opt_in.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/unknown_phone_numbers.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6206 Leftover deploy pt. 2 - September 22, 2023
  _docs/_api/endpoints/messaging/live_activity/update.md
  _docs/_developer_guide/platform_integration_guides/swift/live_activities/faq.md
  _docs/_developer_guide/platform_integration_guides/swift/live_activities/live_activities.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023/3_7_23.md
  _docs/_hidden/private_betas/campaign_data_retention.md
  _docs/_partners/message_orchestration/additional_channels/retargeting/facebook.md
  _docs/_user_guide/message_building_by_channel/sms/best_practices/opt-ins.md
  _docs/_user_guide/message_building_by_channel/sms/keywords.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/fuzzy_opt_out.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/sms_double_opt_in.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/unknown_phone_numbers.md
  assets/img/restore_interaction_data.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#6207 BD-2450 remove non-native sms section
  _docs/_user_guide/message_building_by_channel/sms/non_native.md
  _docs/_user_guide/message_building_by_channel/sms/non_native/custom_keyword_handling.md
  _docs/_user_guide/message_building_by_channel/sms/non_native/double_opt_in.md
  _docs/_user_guide/message_building_by_channel/sms/non_native/handling_unkown_phone_numbers.md
  _docs/_user_guide/message_building_by_channel/sms/non_native/user_data_migration.md
  _docs/_user_guide/message_building_by_channel/sms/sms_setup/user_data_migration.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6208 Fix numbering for opt-ins
  _docs/_user_guide/message_building_by_channel/sms/best_practices/opt-ins.md
Labels: cla-signed

#6209 Style edits for Keyword Processing landing
  _docs/_user_guide/message_building_by_channel/sms/keywords.md
Labels: cla-signed

#6211 Task-based edit: Selections
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/selections.md
  assets/img_archive/catalog_selections6.png
Labels: cla-signed

#6213 Task-based edit: Azure Active Directory
  _docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
Labels: cla-signed

#6210 Add Microsoft SNDS metrics
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
Labels: cla-signed

#6201 [SDK-2983] Update React Native In-App Message Docs
  _lang/fr/_developer_guide/platform_integration_guides/react_native/inapp_messages.md
Labels: cla-signed

#6218 Q3 feedback preference center
  _docs/_api/endpoints/preference_center/get_create_url_preference_center.md
Labels: cla-signed

#6219 fix infinite loop code sample
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
Labels: cla-signed

#6220 BD-2439: Clarify Summary page for Canvas workflow
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/time_based_canvas.md
Labels: cla-signed

#6202 Update conversions_dashboard_v2.md
  _docs/_hidden/private_betas/conversions_dashboard_v2.md
  assets/img_archive/conversions2_details.png
  assets/img_archive/conversions2_funnel.png
Labels: cla-signed

#6216 Make App Groups clearer on iOS push stories
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/push_story.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/push_story.md
Labels: cla-signed

#6221 Deploy - September 26, 2023
  _docs/_api/endpoints/preference_center/get_create_url_preference_center.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/push_story.md
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/push_story.md
  _docs/_hidden/private_betas/conversions_dashboard_v2.md
  _docs/_hidden/private_betas/copying_to_workspace.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
  _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/time_based_canvas.md
  _docs/_user_guide/message_building_by_channel/sms/best_practices/opt-ins.md
  _docs/_user_guide/message_building_by_channel/sms/keywords.md
  _docs/_user_guide/message_building_by_channel/sms/non_native.md
  _docs/_user_guide/message_building_by_channel/sms/non_native/custom_keyword_handling.md
  _docs/_user_guide/message_building_by_channel/sms/non_native/double_opt_in.md
  _docs/_user_guide/message_building_by_channel/sms/non_native/handling_unkown_phone_numbers.md
  _docs/_user_guide/message_building_by_channel/sms/non_native/user_data_migration.md
  _docs/_user_guide/message_building_by_channel/sms/sms_setup/user_data_migration.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/selections.md
  _lang/fr/_developer_guide/platform_integration_guides/react_native/inapp_messages.md
  assets/img_archive/catalog_selections6.png
  assets/img_archive/conversions2_details.png
  assets/img_archive/conversions2_funnel.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#6223 Spelling fixes
  _docs/_user_guide/data_and_analytics/analytics/conversions_dashboard.md
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
  _docs/_user_guide/data_and_analytics/data_transformation/use_cases.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_custom_event_data.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/reeligibility.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/mobile_integrations.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
  _docs/_user_guide/engagement_tools/testing/race_conditions.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
Labels: cla-signed

#6224 Touch ups Creating a Catalog
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
Labels: cla-signed

#6225 Touch up Creating an Event Prediction
  _docs/_user_guide/sage_ai/predictive_suite/predictive_events/creating_an_event_prediction.md
  assets/img/purchasePrediction/purchases_step1.png
Labels: cla-signed

#6227 BD-2455: Incorrect link on Reports Overview page
  _docs/_user_guide/data_and_analytics/reporting/reports_overview.md
Labels: cla-signed

#6228 BD-2454: Fixed incorrect filter options for number attributes
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
Labels: cla-signed

#6229 BD-2451 Add IP Warming nuance
  _docs/_user_guide/message_building_by_channel/email/email_setup/ip_warming.md
Labels: cla-signed

#6230 Update Segment Extensions digest screenshot
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  assets/img/segment/segment_extension5.png
Labels: cla-signed

#6232 Update aborting_messages.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/aborting_messages.md
Labels: cla-signed

#6233 Minor search fixes
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment.md
  _docs/_user_guide/administrative/app_settings.md
  _docs/_user_guide/sage_ai/intelligence/intelligent_selection.md
Labels: cla-signed

#6235 Q3 feedback: Replace catalog selections example image
  assets/img_archive/catalog_selections3.png
Labels: cla-signed

#6236 Docs Q3 feedback
  _docs/_api/identifier_types.md
  _docs/_api/objects_filters/messaging/email_object.md
  _docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_approval.md
Labels: cla-signed

#6237 Fixes for Microsoft SNDS with Deliverability Center
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
Labels: cla-signed

#6239 BD-2462 Update Data Transformation
  _docs/_user_guide/data_and_analytics/data_transformation/overview.md
Labels: cla-signed

#6240 BD-2463 Remove canvas_step fields from users.canvas.entry in the Currents Events glossary
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#6241 BD-2461: Engagement Report links expire after 1 hour
  _docs/_user_guide/data_and_analytics/reporting/engagement_reports.md
Labels: cla-signed

#6242 BD-2460: iOS simulator can test push notifications as of Xcode 14
  _docs/_developer_guide/platform_integration_guides/flutter/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/troubleshooting.md
Labels: cla-signed

#6245 Leftover deploy - September 28, 2023
  _docs/_api/identifier_types.md
  _docs/_api/objects_filters/messaging/email_object.md
  _docs/_developer_guide/platform_integration_guides/flutter/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/troubleshooting.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment.md
  _docs/_user_guide/administrative/app_settings.md
  _docs/_user_guide/data_and_analytics/analytics/conversions_dashboard.md
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/data_transformation/overview.md
  _docs/_user_guide/data_and_analytics/data_transformation/use_cases.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_custom_event_data.md
  _docs/_user_guide/data_and_analytics/reporting/engagement_reports.md
  _docs/_user_guide/data_and_analytics/reporting/reports_overview.md
  _docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/reeligibility.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_approval.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/mobile_integrations.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
  _docs/_user_guide/engagement_tools/testing/race_conditions.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/email/email_setup/ip_warming.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/aborting_messages.md
  _docs/_user_guide/sage_ai/intelligence/intelligent_selection.md
  _docs/_user_guide/sage_ai/predictive_suite/predictive_events/creating_an_event_prediction.md
  assets/img/purchasePrediction/purchases_step1.png
  assets/img/segment/segment_extension5.png
  assets/img_archive/catalog_selections3.png
Labels: cla-signed

#6238 BD-2457 Create Revenue Report article
  _docs/_user_guide/data_and_analytics/export_braze_data/exporting_revenue_data.md
  _docs/_user_guide/data_and_analytics/reporting.md
  _docs/_user_guide/data_and_analytics/reporting/reports_overview.md
  _docs/_user_guide/data_and_analytics/reporting/revenue_report.md
  assets/img/revenue_report.png
  assets/img/revenue_report_product_breakdown.png
  assets/img_archive/Export_revenue_graph.png
  assets/img_archive/Export_revenue_product_breakdown.png
Labels: cla-signed

#6244 BD-2438: Clarify info for universal links
  _docs/_partners/message_orchestration/attribution/branch/branch_for_deeplinking.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
Labels: cla-signed

#6248 BD-2467: Add "Last Seen" information to API overview
  _docs/_api/basics.md
  assets/img_archive/rest-api-key.png
  assets/img_archive/view-api-key.png
Labels: cla-signed

#6249 Conversions not conversations
  _docs/_user_guide/engagement_tools/canvas/canvas_components/feature_flags.md
Labels: cla-signed

#6162 [DLK-1253] add api docs for new CDI apis
  _docs/_api/api_limits.md
  _docs/_api/endpoints/cdi.md
  _docs/_api/endpoints/cdi/get_integration_list.md
  _docs/_api/endpoints/cdi/get_job_sync_status.md
  _docs/_api/endpoints/cdi/post_job_sync.md
  _docs/_api/home.md
  _includes/rate_limits.md
Labels: status: done, cla-signed

#6231 Clarify campaign interaction data
  _docs/_hidden/private_betas/campaign_data_retention.md
Labels: cla-signed

#6250 BD-2456 Update screenshots for Custom Events Report
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_custom_event_data.md
  assets/img/custom_events_report_filters.png
  assets/img_archive/Export_events.png
  assets/img_archive/custom_event_analytics_example.png
Labels: cla-signed

#6246 BD-2376: New help article for handling triggering server clicks
  _docs/_help/help_articles/email.md
  _docs/_help/help_articles/email/html_looks_strange.md
  _docs/_help/help_articles/email/open_rates.md
  _docs/_user_guide/message_building_by_channel/email/faq.md
Labels: cla-signed

#6251 Update simple_survey.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/templates/simple_survey.md
Labels: cla-signed

#6253 Spelling edits pt.2
  _docs/_user_guide/message_building_by_channel/email/email_setup/consent_and_address_collection.md
  _docs/_user_guide/message_building_by_channel/email/faq.md
  _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/unknown_phone_numbers.md
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/user_messages.md
  _docs/_user_guide/message_building_by_channel/whatsapp/overview.md
  _docs/_user_guide/sage_ai/predictive_suite/predictive_churn/prediction_analytics/prediction_quality.md
Labels: cla-signed

#6234 BD-2458: Add info about user aliases to Radar
  _docs/_partners/message_personalization/location/radar.md
Labels: cla-signed
