Repository braze-inc/braze-docs, pull requests merged in 2023-11, with the labels that each got.

#6424 update CUE version to 0.1.1929+8f844ba
  assets/download_file/data-sharing-raw-table-schemas.txt
Labels: cla-signed

#6449 BD-2560: Clarify push device options for multiple devices
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
  assets/img_archive/push_recent_device.png
Labels: cla-signed

#6452 doc: removed catalogs_flexible_pricing related docs
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/put_update_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md
Labels: cla-signed

#6447 Highlighted signing the CLA a little more
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
Labels: cla-signed

#6454 BD-2572 Add eligibility window to SMS double opt-in
  _docs/_user_guide/message_building_by_channel/sms/keywords/sms_double_opt_in.md
Labels: cla-signed

#6453 Remove quick create references
  _docs/_user_guide/administrative/access_braze.md
  _docs/_user_guide/administrative/access_braze/global_search.md
  assets/img/global_search/global_search.png
Labels: cla-signed

#6455 Clarify "Launch and Manage Content Blocks" permission
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#6456 Update link
  _docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md
Labels: cla-signed

#6458 Leftover deploy - November 2, 2023
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/put_update_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
  _docs/_user_guide/administrative/access_braze.md
  _docs/_user_guide/administrative/access_braze/global_search.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/editor_blocks.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/phone_number_capture.md
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/sms_double_opt_in.md
  assets/download_file/data-sharing-raw-table-schemas.txt
  assets/img/global_search/global_search.png
  assets/img_archive/dnd_iam_select_template.png
  assets/img_archive/push_recent_device.png
Labels: cla-signed, Deploy

#6459 Style edits
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
Labels: cla-signed

#6460 BD-2574 Updated minimum SDK version for Push Max
  _docs/_user_guide/message_building_by_channel/push/android/push_max.md
Labels: cla-signed

#6461 Style edits pt. 2
  _docs/_user_guide/getting_started/web_sdk.md
Labels: cla-signed

#6462 Style edits pt. 3
  _docs/_user_guide/getting_started/integration.md
Labels: cla-signed

#6467 "Block" to "block"
  _docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md
Labels: cla-signed

#6465 Fix weird capitalization inconsistency
  _docs/_user_guide/data_and_analytics/reporting/campaign_analytics.md
  _docs/_user_guide/engagement_tools/campaigns.md
Labels: cla-signed

#6466 Fix capitalization inconsistencies
  _docs/_user_guide/sage_ai/predictive_suite/predictive_churn/prediction_faq.md
Labels: cla-signed

#6464 BD-2573: Clarify that confidence only shows up when an optimization is selected
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md
Labels: cla-signed

#6469 Remove line break
  _docs/_user_guide/message_building_by_channel/email/email_setup/email_validation.md
Labels: cla-signed

#6468 Fix regular expression bit
  _docs/_user_guide/message_building_by_channel/email/email_setup/email_validation.md
Labels: cla-signed

#6470 Remove "new" from simple survey
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/templates/simple_survey.md
Labels: cla-signed

#6446 BD-2561: Personalized Paths beta [MERGE 11/6]
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/personalized_paths.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/winning_path.md
  assets/img/experiment_step/experiment_personalized_delay_group_complete.png
  assets/img/experiment_step/experiment_personalized_delay_group_pending.png
  assets/img/experiment_step/experiment_personalized_path.png
  assets/img/experiment_step/experiment_personalized_percentages.png
  assets/img/experiment_step/experiment_personalized_settings.png
Labels: cla-signed

#6414 Update EROR for GA [MERGE 11/6]
  _includes/campaign_analytics.md
Labels: cla-signed

#6474 BD-2577 fix phone number formatting JSON responses
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
Labels: cla-signed

#6476 BD-2562: Remove square brackets from example request
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
Labels: cla-signed

#6416 BD-2438: Instructions for universal links and App Links
  _docs/_help/help_articles/email.md
  _docs/_help/help_articles/email/universal_links.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _docs/_partners/message_orchestration/attribution/branch/branch_for_deeplinking.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  assets/img_archive/universal_links_1b.png
  assets/img_archive/universal_links_1d.png
Labels: cla-signed, In Review

#6433 BD-2553: Update "About feature flags" with ff experiments
  _docs/_developer_guide/platform_wide/feature_flags/about.md
  assets/img/feature_flags/feature-flag-use-case-campaign-experiment.png
Labels: cla-signed

#6475 BD-2575: Hidden doc for updated email HTML editor
  _docs/_hidden/private_betas/email_html_react.md
  assets/img_archive/email_html_editor_updated.png
Labels: cla-signed

#6081 Getting started: Developer section
  _docs/_developer_guide/platform_integration_guides/ios.md
  _docs/_developer_guide/platform_integration_guides/macOS.md
  _docs/_developer_guide/platform_integration_guides/tv_and_ott.md
  _docs/_developer_guide/platform_integration_guides/tvos.md
  _docs/_developer_guide/platform_wide.md
  _docs/_developer_guide/platform_wide/app_group_configuration.md
  _docs/_developer_guide/platform_wide/feature_flags.md
  _docs/_developer_guide/platform_wide/feature_flags/about.md
  _docs/_developer_guide/platform_wide/getting_started.md
  _docs/_developer_guide/platform_wide/getting_started/analytics_overview.md
  _docs/_developer_guide/platform_wide/getting_started/architecture_overview.md
  _docs/_developer_guide/platform_wide/getting_started/integration_overview.md
  _docs/_developer_guide/platform_wide/getting_started/platform_overview.md
  _docs/_developer_guide/platform_wide/platform_features.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
  _docs/_user_guide/getting_started.md
  _docs/_user_guide/getting_started/overview.md
  _docs/_user_guide/getting_started/web_sdk.md
  _plugins/gallery.rb
  assets/css/_content.scss
  assets/css/_navigation_menu.scss
  assets/css/_toc.scss
  assets/css/main.scss
  assets/css/swiper.css
  assets/css/swipercustom.scss
  assets/img/getting-started/braze_listen_understand_act.png
  assets/img/getting-started/crawl-example.png
  assets/img/getting-started/data-graphic-2.png
  assets/img/getting-started/data-graphic.png
  assets/img/getting-started/getting-started-integrate-flower.png
  assets/img/getting-started/getting-started-segment.png
  assets/img/getting-started/getting-started-vertically-integrated-stack.png
  assets/img/getting-started/import-export.png
  assets/img/getting-started/messaging-channel-graphic.png
  assets/img/getting-started/messaging-channels.png
  assets/img/getting-started/putting-it-all-together.png
  assets/img/getting-started/run-example.png
  assets/img/getting-started/walk-example.png
  assets/img/getting_started/channels.png
  assets/js/broken_redirect_list.js
  assets/js/developer_nav.js
  assets/js/swiper.js
Labels: cla-signed

#6442 Update how DNS records are provided
  _docs/_user_guide/message_building_by_channel/email/apple_mail/email_private_relay_apple_SSO.md
Labels: cla-signed

#6482 Deploy pt.2 - November 7, 2023
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  _docs/_developer_guide/platform_integration_guides/ios.md
  _docs/_developer_guide/platform_integration_guides/macOS.md
  _docs/_developer_guide/platform_integration_guides/tv_and_ott.md
  _docs/_developer_guide/platform_integration_guides/tvos.md
  _docs/_developer_guide/platform_wide.md
  _docs/_developer_guide/platform_wide/app_group_configuration.md
  _docs/_developer_guide/platform_wide/feature_flags.md
  _docs/_developer_guide/platform_wide/feature_flags/about.md
  _docs/_developer_guide/platform_wide/getting_started.md
  _docs/_developer_guide/platform_wide/getting_started/analytics_overview.md
  _docs/_developer_guide/platform_wide/getting_started/architecture_overview.md
  _docs/_developer_guide/platform_wide/getting_started/integration_overview.md
  _docs/_developer_guide/platform_wide/getting_started/platform_overview.md
  _docs/_developer_guide/platform_wide/platform_features.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
  _docs/_help/help_articles/email.md
  _docs/_help/help_articles/email/universal_links.md
  _docs/_hidden/private_betas/email_html_react.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _docs/_partners/message_orchestration/attribution/branch/branch_for_deeplinking.md
  _docs/_user_guide/getting_started.md
  _docs/_user_guide/getting_started/overview.md
  _docs/_user_guide/getting_started/web_sdk.md
  _docs/_user_guide/message_building_by_channel/email/apple_mail/email_private_relay_apple_SSO.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _plugins/gallery.rb
  assets/css/_content.scss
  assets/css/_navigation_menu.scss
  assets/css/_toc.scss
  assets/css/main.scss
  assets/css/swiper.css
  assets/css/swipercustom.scss
  assets/img/feature_flags/feature-flag-use-case-campaign-experiment.png
  assets/img/getting-started/braze_listen_understand_act.png
  assets/img/getting-started/crawl-example.png
  assets/img/getting-started/data-graphic-2.png
  assets/img/getting-started/data-graphic.png
  assets/img/getting-started/getting-started-integrate-flower.png
  assets/img/getting-started/getting-started-segment.png
  assets/img/getting-started/getting-started-vertically-integrated-stack.png
  assets/img/getting-started/import-export.png
  assets/img/getting-started/messaging-channel-graphic.png
  assets/img/getting-started/messaging-channels.png
  assets/img/getting-started/putting-it-all-together.png
  assets/img/getting-started/run-example.png
  assets/img/getting-started/walk-example.png
  assets/img/getting_started/channels.png
  assets/img_archive/email_html_editor_updated.png
  assets/img_archive/universal_links_1b.png
  assets/img_archive/universal_links_1d.png
  assets/js/broken_redirect_list.js
  assets/js/developer_nav.js
  assets/js/swiper.js
Labels: cla-signed, Deploy

#6481 Clarify EROR is not retroactive
  _includes/campaign_analytics.md
Labels: cla-signed

#6413 BD-2548: Updating Content Calendar docs for new UI
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/campaign_calendar.md
  assets/img/campaign_calendar/content_calendar_messaging_analytics.png
  assets/img/campaign_calendar/content_calendar_sends.png
Labels: cla-signed

#6483 "Articles" to "articles"
  _docs/_developer_guide/platform_wide/getting_started.md
Labels: cla-signed

#6485 Small edits
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/setting_up_shopify.md
Labels: cla-signed

#6486 Add redirect for incorrect dashboard link
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6450 BD-2557: Typeform Partner Documentation
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/channel_extensions.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/olo.md
  _docs/_partners/message_orchestration/channel_extensions/surveys.md
  _docs/_partners/message_orchestration/channel_extensions/surveys/typeform.md
  _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
  _includes/create_transformation.md
  assets/img/typeform/data_transformation_typeform.png
  assets/img/typeform/typeform_add_webhook.png
  assets/img/typeform/typeform_custom_event.png
  assets/img/typeform/typeform_test_request.png
  assets/img/typeform/typeform_test_result.png
Labels: cla-signed, Braze Partnerships

#6448 BD-2567 Create Heap analytics article
  _docs/_partners/data_and_infrastructure_agility/analytics/heap.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/heap.md
Labels: cla-signed

#6487 Fix incorrect heading levels and table break syntax
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
Labels: cla-signed

#6479 BD-2579: Personalized Paths analytics addition
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/personalized_paths.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/winning_path.md
  _docs/_user_guide/sage_ai.md
  assets/img/experiment_step/experiment_personalized_analytics_tab1.png
  assets/img/experiment_step/experiment_personalized_analytics_tab1_2.png
  assets/img/experiment_step/experiment_personalized_analytics_tab2.png
Labels: cla-signed

#6491 BD-2590: Fix URL missing a slash
  _docs/_user_guide/getting_started/web_sdk.md
Labels: cla-signed

#6492 BD-2583: Clarify Snowflake credit usage is feature-independent
  _docs/_user_guide/data_and_analytics/query_builder.md
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
Labels: cla-signed

#6478 [Untracked] Add Flutter version requirements to public docs
  _docs/_developer_guide/platform_integration_guides/flutter/flutter_sdk_integration.md
Labels: cla-signed

#6493 BD-2581: New UI for blocklisting custom attributes and events
  _docs/_user_guide/administrative/app_settings/custom_event_and_attribute_management.md
  assets/img_archive/blocklist_custom_attr.png
Labels: cla-signed

#6494 BD-2563: Clarify behavior for deleting variants after Canvas launch
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
Labels: cla-signed

#6496 BD-2568: Add weekly scheduled delivery details
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  assets/img_archive/Canvas_Scheduled_Delivery.png
Labels: cla-signed

#6497 Minor edits
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
Labels: cla-signed

#6498 BD-2559: Update list of trigger types for action-based campaign delivery
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/campaign_calendar.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md
Labels: cla-signed

#6501 BD-2600 remove EA alert for SMS double opt-in
  _docs/_user_guide/message_building_by_channel/sms/keywords/sms_double_opt_in.md
Labels: cla-signed

#6504 Update the_basics.md
  _docs/_user_guide/engagement_tools/canvas/get_started/the_basics.md
Labels: cla-signed

#6503 Global search GA
  _docs/_user_guide/administrative/access_braze/global_search.md
Labels: cla-signed

#6505 Update delete_user.md
  _docs/_help/help_articles/api/delete_user.md
Labels: cla-signed

#6510 Update media_library.md
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
Labels: cla-signed

#6511 Update ai_content_qa.md
  _docs/_user_guide/sage_ai/generative_ai/ai_content_qa.md
Labels: cla-signed

#6513 Add legal edit for custom fonts in drag-and-drop email style settings
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
Labels: cla-signed

#6390 November 2023 release notes
  _docs/_docs_pages/index.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023.md
  _docs/_help/release_notes/2023/11_14_23.md
  _includes/release_type.md
Labels: cla-signed

#6514 Deploy - November 14, 2023
  _docs/_developer_guide/platform_integration_guides/flutter/flutter_sdk_integration.md
  _docs/_docs_pages/index.md
  _docs/_help/help_articles/api/delete_user.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023.md
  _docs/_help/release_notes/2023/11_14_23.md
  _docs/_user_guide/administrative/access_braze/global_search.md
  _docs/_user_guide/administrative/app_settings/custom_event_and_attribute_management.md
  _docs/_user_guide/data_and_analytics/query_builder.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/campaign_calendar.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/get_started/the_basics.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
  _docs/_user_guide/getting_started/web_sdk.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/sms_double_opt_in.md
  _docs/_user_guide/sage_ai/generative_ai/ai_content_qa.md
  _includes/release_type.md
  assets/img_archive/Canvas_Scheduled_Delivery.png
  assets/img_archive/blocklist_custom_attr.png
Labels: cla-signed, Deploy

#6500 Add documentation on React Native push notification events
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
Labels: cla-signed

#6515 BD-2598: Add 404 HTTP status code
  _docs/_partners/isv_partners/currents_integration.md
Labels: cla-signed

#6517 feature flags updates
  _docs/_developer_guide/platform_wide/feature_flags/create.md
  _docs/_developer_guide/platform_wide/feature_flags/experiments.md
Labels: cla-signed

#6519 Remove mentions of wizard
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/customization/advanced_settings.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/huawei_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/customization/advanced_settings.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/customization/custom_sounds.md
  _docs/_developer_guide/platform_wide/sending_test_messages.md
  _docs/_help/help_articles/campaigns_and_canvas/canvas_not_sending.md
  _docs/_hidden/private_betas/multiple_stores.md
  _docs/_hidden/private_betas/whatsapp_response_messaging.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/census.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/scripttag_web_sdk_integration.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/setting_up_shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_backfill.md
  _docs/_partners/message_orchestration/channel_extensions/surveys/survicate.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/capturing_lapsing_users.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/create.md
  _docs/_user_guide/message_building_by_channel/push/android/advanced_campaign_settings.md
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/create.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/segments.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  _docs/_user_guide/message_building_by_channel/whatsapp/overview.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md
  _lang/fr/_help/help_articles/campaigns_and_canvas/canvas_not_sending.md
  _lang/fr/_help/help_articles/campaigns_and_canvas/more_people_in_control_group.md
Labels: cla-signed

#6520 Update popular topics and fix plural inconsistency
  _docs/_api/endpoints/user_data/post_user_delete.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_docs_pages/index.md
Labels: cla-signed

#6521 Removing x-braze-bulk as the header is non-functional
  _docs/_api/endpoints/user_data/post_user_track.md
Labels: cla-signed

#6522 BD-2602: Changing an outdated link and sneaking in a lil test while I'm toodling
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/customization.md
Labels: cla-signed

#6523 Standards edit: JPG to JPEG
  _docs/_hidden/archive_docs/previous_in-app_message_generations.md
  _docs/_user_guide/engagement_tools/news_feed/creating_a_news_feed_item.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/email_styling.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/fullscreen.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/modal.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/slideup.md
  _docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_stories.md
  _docs/_user_guide/message_building_by_channel/sms/mms/about_mms.md
  _docs/_user_guide/message_building_by_channel/sms/mms/create.md
Labels: cla-signed

#6516 Reorganize December release notes
  _docs/_help/release_notes/2021/april.md
  _docs/_help/release_notes/2021/august.md
  _docs/_help/release_notes/2021/december.md
  _docs/_help/release_notes/2021/february.md
  _docs/_help/release_notes/2021/january.md
  _docs/_help/release_notes/2021/july.md
  _docs/_help/release_notes/2021/june.md
  _docs/_help/release_notes/2021/march.md
  _docs/_help/release_notes/2021/may.md
  _docs/_help/release_notes/2021/november.md
  _docs/_help/release_notes/2021/october.md
  _docs/_help/release_notes/2021/september.md
  _docs/_help/release_notes/2022.md
  _docs/_help/release_notes/2022/12_13_22.md
  _docs/_help/release_notes/2022/12_14_21.md
  _docs/_help/release_notes/2023.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6526 Style edit: "ecommerce" not "e-commerce"
  _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
  _docs/_developer_guide/platform_wide/feature_flags/about.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
  _docs/_developer_guide/platform_wide/getting_started/analytics_overview.md
  _docs/_help/release_notes/2021/december.md
  _docs/_help/release_notes/2021/october.md
  _docs/_help/release_notes/2022/5_31_22.md
  _docs/_home/static_video.md
  _docs/_partners/data_and_infrastructure_agility/analytics/wunderkind.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack/rudderstack.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/yotpo.md
  _docs/_partners/message_personalization/dynamic_content/amazon_personalize/workshop.md
  _docs/_user_guide/administrative/app_settings/tags.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/custom_data/events.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/install_attribution.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties/canvas_persistent_entry_properties.md
  _docs/_user_guide/engagement_tools/segments/segment_insights.md
  _docs/_user_guide/getting_started/workspaces.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
Labels: cla-signed

#6527 Raghavnarain3 patch users merge users identify
  _docs/_api/endpoints/user_data/post_user_identify.md
  _docs/_api/endpoints/user_data/post_users_merge.md
Labels: cla-signed

#6488 BD-2524: Clarify partner limitation for array of objects and nested custom attributes
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
Labels: cla-signed

#6529 Add a period
  _docs/_partners/canvas_steps/tiktok_audience_sync.md
Labels: cla-signed

#6507 Update ai_copywriting.md
  _docs/_user_guide/sage_ai/generative_ai/ai_copywriting.md
Labels: cla-signed

#6536 Fix capitalization of third-party provider
  _docs/_user_guide/sage_ai/generative_ai/ai_copywriting.md
Labels: cla-signed

#6530 [DLK-1447] Update User Deletes docs to talk about integration type
  _docs/_user_guide/data_and_analytics/cloud_ingestion/delete_users.md
  assets/img/cloud_ingestion/deletion_1.png
Labels: cla-signed

#6534 BD-2610 Finish updating appboyBridge with brazeBridge
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/integration.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize/html_in-app_messages.md
  _includes/archive/appboyBridge.md
Labels: cla-signed

#6535 BD-2611 update SQL Segment Extensions automatic membership regeneration
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
Labels: cla-signed

#6495 BD-2589: Add AI Query Builder section to Query Builder
  _docs/_user_guide/data_and_analytics/query_builder.md
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
  assets/img_archive/query_builder_ai_tab.png
Labels: cla-signed, In Review

#6533 Removed arguments from BrazeActivityLifecycleCallbackListener
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
Labels: cla-signed

#6490 Recurly - Partner Docs (to be merged 11/21)
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/payments.md
  _docs/_partners/data_and_infrastructure_agility/payments/recurly.md
  _docs/_partners/home.md
Labels: cla-signed, Braze Partnerships

#6537 BD-2609: Update guidance re: Unsubscribe URL Tags
  _docs/_user_guide/message_building_by_channel/email/custom_email_footer.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: cla-signed

#6540 BD-2569: Add integration method note
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
Labels: cla-signed

#6539 Fix email footer links
  _docs/_user_guide/message_building_by_channel/email.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/managing_email_subscriptions.md
Labels: cla-signed

#6541 BD-2603: Add quotes to Liquid example
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
Labels: cla-signed

#6542 BD-2607: Update image for Audience Sync step
  _docs/_partners/canvas_steps/overview.md
  assets/img/audience_sync/audience_sync4.png
Labels: cla-signed

#6543 Deploy - November 21, 2023
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/integration.md
  _docs/_partners/canvas_steps/overview.md
  _docs/_partners/canvas_steps/tiktok_audience_sync.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/payments.md
  _docs/_partners/data_and_infrastructure_agility/payments/recurly.md
  _docs/_partners/home.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/smartersends.md
  _docs/_partners/message_personalization.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/delete_users.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
  _docs/_user_guide/data_and_analytics/query_builder.md
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
  _docs/_user_guide/message_building_by_channel/email.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/managing_email_subscriptions.md
  _docs/_user_guide/message_building_by_channel/email/custom_email_footer.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize/html_in-app_messages.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  _docs/_user_guide/sage_ai/generative_ai/ai_copywriting.md
  _includes/archive/appboyBridge.md
  assets/img/audience_sync/audience_sync4.png
  assets/img/cloud_ingestion/deletion_1.png
  assets/img_archive/query_builder_ai_tab.png
Labels: cla-signed, Deploy

#6544 BD-2608: Rate limiting and Canvas components
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
Labels: cla-signed

#6546 BD-2604: User email addresses must be unique for a workspace
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/adding_users_to_your_dashboard.md
Labels: cla-signed

#6548 Fix IAM traditional editor redirects
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6545 BD-2623: Email capture form EA
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/email_capture.md
Labels: cla-signed

#6550 BD-2620 Update link shortening FAQ
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
Labels: cla-signed

#6525 Facebook Lead Ads via Zapier documentation
  _docs/_partners/data_and_infrastructure_agility/leads_capture.md
  _docs/_partners/data_and_infrastructure_agility/leads_capture/facebook_via_zapier.md
  _docs/_partners/home.md
  _layouts/partner_page.html
  assets/img/fb_lead_ads_zapier/configuration_example.png
  assets/img/fb_lead_ads_zapier/create_zap1.png
  assets/img/fb_lead_ads_zapier/create_zap2.png
  assets/img/fb_lead_ads_zapier/create_zap3.png
  assets/img/fb_lead_ads_zapier/create_zap4.png
  assets/img/fb_lead_ads_zapier/create_zap5.png
  assets/img/fb_lead_ads_zapier/facebook-zapier.png
  assets/img/fb_lead_ads_zapier/integration1.png
  assets/img/fb_lead_ads_zapier/integration2.png
Labels: cla-signed

#6551 BD-2627: Add note about dashboard time zone for catalog time field
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
Labels: cla-signed

#6552 BD-2634: Remove EA for already GA'd feature
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
Labels: cla-signed

#6554 Deploy - November 28, 2023
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_partners/data_and_infrastructure_agility/leads_capture.md
  _docs/_partners/data_and_infrastructure_agility/leads_capture/facebook_via_zapier.md
  _docs/_partners/home.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/adding_users_to_your_dashboard.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/email_capture.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _layouts/partner_page.html
  assets/img/fb_lead_ads_zapier/configuration_example.png
  assets/img/fb_lead_ads_zapier/create_zap1.png
  assets/img/fb_lead_ads_zapier/create_zap2.png
  assets/img/fb_lead_ads_zapier/create_zap3.png
  assets/img/fb_lead_ads_zapier/create_zap4.png
  assets/img/fb_lead_ads_zapier/create_zap5.png
  assets/img/fb_lead_ads_zapier/facebook-zapier.png
  assets/img/fb_lead_ads_zapier/integration1.png
  assets/img/fb_lead_ads_zapier/integration2.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#6531 BD-2580 New Segmentation Filters article
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _layouts/api_glossary.html
  _layouts/glossary_page.html
Labels: cla-signed

#6559 BD-2645: Unhide Cloud Data Ingestion endpoint docs
  _docs/_api/endpoints/cdi.md
  _docs/_api/endpoints/cdi/get_integration_list.md
  _docs/_api/endpoints/cdi/get_job_sync_status.md
  _docs/_api/endpoints/cdi/post_job_sync.md
  _docs/_api/home.md
Labels: cla-signed

#6560 BD-2650 Fix Liquid use case operator
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
Labels: cla-signed

#6564 List unsub header desc correction
  _docs/_user_guide/administrative/app_settings/email_settings.md
Labels: cla-signed

#6565 Leftover Deploy - November 30, 2023
  _docs/_api/endpoints/cdi.md
  _docs/_api/endpoints/cdi/get_integration_list.md
  _docs/_api/endpoints/cdi/get_job_sync_status.md
  _docs/_api/endpoints/cdi/post_job_sync.md
  _docs/_api/home.md
  _docs/_api/identifier_types.md
  _docs/_user_guide/administrative/app_settings/email_settings.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
  _layouts/api_glossary.html
  _layouts/glossary_page.html
Labels: cla-signed, Deploy

#6567 BD-2638 Update WhatsApp message engagement events
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed
