Repository braze-inc/braze-docs, pull requests merged in 2023-02, with the labels that each got.

#4747 Algolia Tweaks 3
  _docs/_developer_guide/platform_integration_guides/android/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
  _docs/_developer_guide/platform_integration_guides/ios/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/overview.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
  _docs/_help/help_articles/api/delete_user.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2022/4_5_22.md
  _docs/_help/release_notes/2023/1_10_23.md
  _docs/_help/support.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify.md
  _docs/_user_guide/data_and_analytics.md
  _docs/_user_guide/data_and_analytics/analytics.md
  _docs/_user_guide/data_and_analytics/your_reports.md
  _docs/_user_guide/message_building_by_channel/push/push_reporting.md
  _docs/_user_guide/onboarding_with_braze.md
  _docs/_user_guide/onboarding_with_braze/learning_to_use_braze.md
Labels: cla-signed

#4748 Fix font awesome 6 setup
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/customization.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/customization.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/customization.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/customization.md
  _docs/_help/faqs.md
  _docs/_partners/isv_partners.md
  _includes/analytics.html
  _plugins/sdk_min_versions_tag.rb
  assets/css/fontawesome.css
  assets/webfonts/fa-brands-400.ttf
  assets/webfonts/fa-brands-400.woff2
  assets/webfonts/fa-regular-400.ttf
  assets/webfonts/fa-regular-400.woff2
  assets/webfonts/fa-solid-900.ttf
  assets/webfonts/fa-solid-900.woff2
  assets/webfonts/fa-v4compatibility.ttf
  assets/webfonts/fa-v4compatibility.woff2
Labels: cla-signed

#4752 BD-1866: Fix custom attributes string character limit
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
Labels: cla-signed

#4756 BD-1884: Add trigger conditions for Punchh events
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/punchh.md
Labels: cla-signed

#4726 BD-1872: Add custom opt-in info
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#4750 Fix details for Canvas endpoint
  _docs/_api/endpoints/export/canvas/get_canvas_details.md
Labels: cla-signed

#4754 GlobalLink Translation PR
  _lang/fr/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  _lang/fr/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
  _lang/fr/_developer_guide/platform_integration_guides/web/google_tag_manager.md
  _lang/fr/_help/release_notes/2023/1_10_23.md
  _lang/fr/_hidden/private_betas/canvas_drafts.md
  _lang/fr/_hidden/private_betas/shopify_backfil.md
  _lang/fr/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _lang/fr/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _lang/fr/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md
  _lang/fr/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack.md
  _lang/fr/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _lang/fr/_user_guide/data_and_analytics/braze_currents/s3_to_snowflake.md
  _lang/fr/_user_guide/data_and_analytics/creating_a_formula.md
  _lang/fr/_user_guide/data_and_analytics/tracking/segment_analytics_tracking.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion.md
  _lang/fr/_user_guide/data_and_analytics/your_analytics_dashboards.md
  _lang/fr/_user_guide/engagement_tools/campaigns/managing_campaigns/change_your_campaign_after_launch.md
  _lang/fr/_user_guide/engagement_tools/segments/creating_a_segment.md
  _lang/fr/_user_guide/engagement_tools/segments/segment_extension.md
  _lang/fr/_user_guide/engagement_tools/templates_and_media/media_library.md
  _lang/fr/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _lang/fr/_user_guide/message_building_by_channel/email/preference_center.md
  _lang/fr/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
  _lang/fr/_user_guide/onboarding_with_braze/data_points.md
  _lang/fr/_user_guide/predictive_suite/predictive_churn/creating_a_churn_prediction.md
  _lang/fr/_user_guide/predictive_suite/predictive_purchases/creating_a_purchase_prediction.md
Labels: cla-signed

#4674 Add tabs for Data retention doc
  _docs/_api/data_retention.md
Labels: cla-signed

#4759 Update Flutter Docs to reference Swift SDK methods
  _docs/_developer_guide/platform_integration_guides/flutter/content_cards.md
  _docs/_developer_guide/platform_integration_guides/flutter/flutter_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/flutter/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/flutter/push_notifications.md
Labels: cla-signed

#4765 GlobalLink Translation PR
  _lang/fr/_api/data_retention.md
Labels: cla-signed

#4751 docs: first pass of users alias update documentation
  _docs/_api/api_limits.md
  _docs/_api/endpoints/user_data.md
  _docs/_api/endpoints/user_data/external_id_migration.md
  _docs/_api/endpoints/user_data/post_user_alias.md
  _docs/_api/endpoints/user_data/post_user_delete.md
  _docs/_api/endpoints/user_data/post_user_identify.md
  _docs/_api/endpoints/user_data/post_users_alias_update.md
  _docs/_api/endpoints/user_data/post_users_merge.md
  _docs/_api/home.md
  _includes/rate_limits.md
Labels: cla-signed

#4767 Algolia tweaks 5
  _docs/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md
  _docs/_developer_guide/platform_integration_guides/unity/sdk_integration/ios.md
Labels: cla-signed

#4768 Unhide feature flags
  _docs/_developer_guide/platform_wide/feature_flags.md
  _docs/_developer_guide/platform_wide/feature_flags/about.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
  _docs/_developer_guide/platform_wide/feature_flags/use_cases.md
Labels: cla-signed

#4769 Update nested_custom_attribute_support.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
Labels: cla-signed

#4760 Update subscription group update sources - 2/7
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/attribute_triggers.md
Labels: cla-signed

#4761 Reference ability to set subscription group status - 2/7
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
Labels: cla-signed

#4739 First draft of question and answer
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
Labels: cla-signed

#4772 Unhide SQL Segment Extensions
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
Labels: cla-signed

#4775 Update channel list for PV
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
Labels: cla-signed

#4753 BD-1885: Copy and paste styles for DND IAM editor [MERGE 2/7]
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  assets/img_archive/dnd_iam_copypaste_styles.png
Labels: cla-signed

#4660 SQL segments tables
  _docs/_hidden/private_betas/sql_segments_tables.md
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
Labels: cla-signed

#4777 Clarify User Merge Behaviour
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
Labels: cla-signed

#4779 BD-1894: Update screenshots for GPT3 and churn predictions
  _docs/_user_guide/intelligence/ai_copywriting.md
  assets/img/ai_copywriter/gpt3.png
  assets/img/churn/churn1.png
Labels: cla-signed

#4651 Add content cards documentation for Swift SDK
  _docs/_developer_guide/platform_integration_guides/swift/content_cards.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/customization.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/customization/badges.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/customization/carousel_view.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/customization/customizing_feed.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/customization/handling_clicks_manually.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/customization/read_unread_indicators.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/multiple_feeds.md
  assets/img/cc_implementation/ios-unread-badge.png
Labels: cla-signed

#4762 BD-1887: Deliverability for Chinese Android devices
  _docs/_user_guide/message_building_by_channel/push/best_practices.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/chinese_push_deliverability..md
Labels: cla-signed

#4584 Navigation EA – MERGE 2/7
  _docs/_hidden/private_betas/navigation.md
  assets/img/navigation/global_header_compare.png
  assets/img/navigation/global_header_new.png
  assets/img/navigation/global_header_old.png
  assets/img/navigation/global_header_switch.png
  assets/img/navigation/sidebar_compare.png
  assets/img/navigation/sidebar_new.png
  assets/img/navigation/sidebar_old.png
Labels: cla-signed

#4784 BD-1897 and BD-1898: Edits for email settings and fallback font
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
Labels: cla-signed

#4783 BD-1888: Clarify /users/merge behavior
  _docs/_api/endpoints/user_data/post_user_identify.md
  _docs/_api/endpoints/user_data/post_users_merge.md
Labels: cla-signed

#4778 BD-1876: Add tips for cloning Canvases
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
Labels: cla-signed

#4786 Remove TCPA as it is up for amendment
  _docs/_user_guide/message_building_by_channel/sms/sms_laws_and_regulations.md
Labels: cla-signed

#4785 Feb 7th 2023 release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023.md
  _docs/_help/release_notes/2023/12_13_22.md
  _docs/_help/release_notes/2023/1_10_23.md
  _docs/_help/release_notes/2023/2_7_23.md
Labels: cla-signed

#4787 Redshift updates added to mirror Snowflake
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion.md
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/overview.md
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/redshift.md
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/snowflake.md
  assets/img/cloud_ingestion/ingestion_10.png
  assets/img/cloud_ingestion/ingestion_6.png
  assets/img/cloud_ingestion/ingestion_7.png
  assets/img/cloud_ingestion/ingestion_8.png
  assets/img/cloud_ingestion/ingestion_9.png
Labels: cla-signed

#4781 Deploy - February 7, 2023
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
  _docs/_api/endpoints/user_data/post_user_identify.md
  _docs/_api/endpoints/user_data/post_users_merge.md
  _docs/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md
  _docs/_developer_guide/platform_integration_guides/unity/sdk_integration/ios.md
  _docs/_developer_guide/platform_wide/feature_flags.md
  _docs/_developer_guide/platform_wide/feature_flags/about.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
  _docs/_developer_guide/platform_wide/feature_flags/use_cases.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023.md
  _docs/_help/release_notes/2023/12_13_22.md
  _docs/_help/release_notes/2023/1_10_23.md
  _docs/_help/release_notes/2023/2_7_23.md
  _docs/_hidden/private_betas/navigation.md
  _docs/_hidden/private_betas/sql_segments_tables.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion.md
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/overview.md
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/redshift.md
  _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/snowflake.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/attribute_triggers.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
  _docs/_user_guide/intelligence/ai_copywriting.md
  _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _docs/_user_guide/message_building_by_channel/push/best_practices.md
  _docs/_user_guide/message_building_by_channel/push/best_practices/chinese_push_deliverability..md
  _docs/_user_guide/message_building_by_channel/sms/sms_laws_and_regulations.md
  assets/img/ai_copywriter/gpt3.png
  assets/img/churn/churn1.png
  assets/img/cloud_ingestion/ingestion_10.png
  assets/img/cloud_ingestion/ingestion_6.png
  assets/img/cloud_ingestion/ingestion_7.png
  assets/img/cloud_ingestion/ingestion_8.png
  assets/img/cloud_ingestion/ingestion_9.png
  assets/img/navigation/global_header_compare.png
  assets/img/navigation/global_header_new.png
  assets/img/navigation/global_header_old.png
  assets/img/navigation/global_header_switch.png
  assets/img/navigation/sidebar_compare.png
  assets/img/navigation/sidebar_new.png
  assets/img/navigation/sidebar_old.png
  assets/img_archive/dnd_iam_copypaste_styles.png
Labels: cla-signed, Deploy

#4789 BD-1894 Part 2: Update winning path screenshot with one-time entry
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/winning_path.md
  assets/img/experiment_step/experiment_onetime_workaround.png
Labels: cla-signed

#4790 Fix broken links from renaming parent page
  _docs/_user_guide/data_and_analytics/analytics/conversions_dashboard.md
  _docs/_user_guide/data_and_analytics/analytics/email_performance_dashboard.md
  _docs/_user_guide/data_and_analytics/analytics/understanding_your_app_usage_data.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#4791 Update 2_7_23.md
  _docs/_help/release_notes/2023/2_7_23.md
Labels: cla-signed

#4792 Fix typo in release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023/2_7_23.md
Labels: cla-signed

#4794 Deploy Pt 2 - February 7, 2022
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2023/2_7_23.md
  _docs/_user_guide/data_and_analytics/analytics/conversions_dashboard.md
  _docs/_user_guide/data_and_analytics/analytics/email_performance_dashboard.md
  _docs/_user_guide/data_and_analytics/analytics/understanding_your_app_usage_data.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/winning_path.md
  assets/img/experiment_step/experiment_onetime_workaround.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#4796 Fix Image Location Dnd Content Block
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
Labels: cla-signed

#4798 Add missing currents fields to experiment current events
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#4795 BD-1875: Add info about testing campaigns and Canvases
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md
  _docs/_user_guide/engagement_tools/canvas/testing_canvases/sending_test_canvases.md
Labels: cla-signed

#4793 [SDK-3288] Update Flutter SDK Swift docs - Part 2
  _docs/_developer_guide/platform_integration_guides/flutter/content_cards.md
  _docs/_developer_guide/platform_integration_guides/flutter/flutter_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/flutter/inapp_messages.md
Labels: cla-signed

#4799 Algolia tweaks pt.5
  _docs/_user_guide/data_and_analytics/braze_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
  _docs/_user_guide/intelligence.md
  _docs/_user_guide/intelligence/intelligent_channel.md
  _docs/_user_guide/intelligence/intelligent_selection.md
  _docs/_user_guide/onboarding_with_braze.md
  _docs/_user_guide/onboarding_with_braze/data_points.md
  _docs/_user_guide/onboarding_with_braze/subscription_and_usage.md
Labels: cla-signed

#4774 [SDK-3384] React Native Swift SDK migration docs; rename Appboy -> Braze
  _docs/_developer_guide/platform_integration_guides/react_native/changelog.md
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
  _docs/_developer_guide/platform_integration_guides/react_native/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/react_native/sample_app.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2022/7_26_22.md
  _lang/fr/_developer_guide/platform_integration_guides/react_native/inapp_messages.md
  _lang/fr/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _lang/fr/_help/release_notes/2022/7_26_22.md
  _lang/fr/_help/release_notes/2023/1_10_23.md
Labels: status: on hold / do not merge, cla-signed

#4770 Technology Partners / Airbridge: Update Braze Server-to-server Integration
  _docs/_partners/message_orchestration/attribution/airbridge.md
  assets/img/airbridge/airbridge_integration_step_2.png
Labels: cla-signed

#4801 Airbridge formatting updates
  _docs/_partners/message_orchestration/attribution/airbridge.md
Labels: cla-signed

#4773 GlobalLink Translation PR
  _lang/fr/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
  _lang/fr/_help/accessibility.md
  _lang/fr/_help/release_notes.md
  _lang/fr/_help/release_notes/2017/october.md
  _lang/fr/_help/release_notes/2023/12_13_22.md
  _lang/fr/_hidden/private_betas/canvas_drafts.md
  _lang/fr/_hidden/private_betas/sql_segments.md
  _lang/fr/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _lang/fr/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _lang/fr/_partners/data_and_infrastructure_agility/customer_data_platform/segment.md
  _lang/fr/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _lang/fr/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_engage.md
  _lang/fr/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _lang/fr/_partners/isv_partners/cohort_import.md
  _lang/fr/_partners/message_orchestration/channel_extensions/ecommerce/shopify/scripttag_web_sdk_integration.md
  _lang/fr/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_in_braze.md
  _lang/fr/_partners/message_orchestration/channel_extensions/loyalty/punchh.md
  _lang/fr/_partners/message_orchestration/channel_extensions/loyalty/punchh/code_generation.md
  _lang/fr/_partners/message_orchestration/channel_extensions/loyalty/punchh/punchh.md
  _lang/fr/_partners/message_orchestration/channel_extensions/loyalty/voucherify.md
  _lang/fr/_user_guide/data_and_analytics.md
  _lang/fr/_user_guide/data_and_analytics/braze_currents/available_partners.md
  _lang/fr/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _lang/fr/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _lang/fr/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
  _lang/fr/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _lang/fr/_user_guide/data_and_analytics/query_builder.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _lang/fr/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md
  _lang/fr/_user_guide/engagement_tools/canvas/create_a_canvas/exit_criteria.md
  _lang/fr/_user_guide/message_building_by_channel/email/email_private_relay_apple_SSO.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _lang/fr/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
  _lang/fr/_user_guide/message_building_by_channel/sms/phone_numbers/user_phone_numbers.md
  _lang/fr/_user_guide/message_building_by_channel/whatsapp/create.md
  _lang/fr/_user_guide/message_building_by_channel/whatsapp/overview.md
  _lang/fr/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
  _lang/fr/_user_guide/onboarding_with_braze/data_points.md
  _lang/fr/_user_guide/onboarding_with_braze/email_setup/email_validation.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
Labels: cla-signed

#4804 BD-1901: Update frequency capping rules per app group limit
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
Labels: cla-signed

#4803 adding click stat to campaign and sms stats to canvas api documentation
  _docs/_api/endpoints/export/campaigns/get_campaign_analytics.md
  _docs/_api/endpoints/export/canvas/get_canvas_analytics.md
Labels: cla-signed

#4805 html on tvos
  _docs/_developer_guide/platform_wide/tv_and_ott.md
Labels: cla-signed

#4807 BD-1903: Update string limit for custom attributes
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_home/static_video.md
Labels: cla-signed

#4810 BD-1900: Add nested object indexing guidance
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_in_braze.md
Labels: cla-signed

#4811 Update amphtml.md
  _docs/_user_guide/message_building_by_channel/email/amphtml.md
Labels: cla-signed

#4813 rename braze-react-native-sdk
  _docs/_developer_guide/platform_integration_guides/react_native/changelog.md
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
  _docs/_developer_guide/platform_integration_guides/react_native/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/react_native/sample_app.md
Labels: cla-signed

#4758 New WhatsApp Features
  _docs/_user_guide/message_building_by_channel/sms.md
  _docs/_user_guide/message_building_by_channel/whatsapp.md
  _docs/_user_guide/message_building_by_channel/whatsapp/create.md
  _docs/_user_guide/message_building_by_channel/whatsapp/opt-ins_and_opt-outs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/quick_replies.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
  assets/img/whatsapp/whatsapp11.png
  assets/img/whatsapp/whatsapp111.png
  assets/img/whatsapp/whatsapp112.png
  assets/img/whatsapp/whatsapp113.png
  assets/img/whatsapp/whatsapp114.png
  assets/img/whatsapp/whatsapp115.png
  assets/img/whatsapp/whatsapp116.png
  assets/img/whatsapp/whatsapp117.png
  assets/img/whatsapp/whatsapp118.png
  assets/img/whatsapp/whatsapp119.png
  assets/img/whatsapp/whatsapp12.png
  assets/img/whatsapp/whatsapp120.png
  assets/img/whatsapp/whatsapp121.png
  assets/img/whatsapp/whatsapp122.png
  assets/img/whatsapp/whatsapp13.png
  assets/img/whatsapp/whatsapp14.png
  assets/img/whatsapp/whatsapp15.png
  assets/img/whatsapp/whatsapp16.png
  assets/img/whatsapp/whatsapp17.png
  assets/img/whatsapp/whatsapp18.png
Labels: cla-signed

#4815 Leftover Deploy Pt. 2 - February 10, 2023
  _docs/_developer_guide/platform_integration_guides/react_native/changelog.md
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
  _docs/_developer_guide/platform_integration_guides/react_native/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/react_native/sample_app.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_home/static_video.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_in_braze.md
  _docs/_user_guide/message_building_by_channel/email/amphtml.md
  _docs/_user_guide/message_building_by_channel/sms.md
  _docs/_user_guide/message_building_by_channel/whatsapp.md
  _docs/_user_guide/message_building_by_channel/whatsapp/create.md
  _docs/_user_guide/message_building_by_channel/whatsapp/opt-ins_and_opt-outs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/quick_replies.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
  assets/img/whatsapp/whatsapp11.png
  assets/img/whatsapp/whatsapp111.png
  assets/img/whatsapp/whatsapp112.png
  assets/img/whatsapp/whatsapp113.png
  assets/img/whatsapp/whatsapp114.png
  assets/img/whatsapp/whatsapp115.png
  assets/img/whatsapp/whatsapp116.png
  assets/img/whatsapp/whatsapp117.png
  assets/img/whatsapp/whatsapp118.png
  assets/img/whatsapp/whatsapp119.png
  assets/img/whatsapp/whatsapp12.png
  assets/img/whatsapp/whatsapp120.png
  assets/img/whatsapp/whatsapp121.png
  assets/img/whatsapp/whatsapp122.png
  assets/img/whatsapp/whatsapp13.png
  assets/img/whatsapp/whatsapp14.png
  assets/img/whatsapp/whatsapp15.png
  assets/img/whatsapp/whatsapp16.png
  assets/img/whatsapp/whatsapp17.png
  assets/img/whatsapp/whatsapp18.png
Labels: cla-signed, Deploy

#4816 BD-1889: Update requirements for simple survey
  _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
Labels: cla-signed

#4809 BD-1902: Update experiment step conversion currents event
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#4825 Revert "BD-1901: Update frequency capping rules per app group limit"
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
Labels: cla-signed

#4819 GlobalLink Translation PR
  _lang/fr/_api/data_retention.md
Labels: cla-signed

#4822 GlobalLink Translation PR
  _lang/fr/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/connected_content.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/liquid.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  _lang/fr/_user_guide/predictive_suite.md
  _lang/fr/_user_guide/predictive_suite/predictive_churn.md
  _lang/fr/_user_guide/predictive_suite/predictive_purchases.md
Labels: cla-signed

#4826 BD-1896, BD-1891: Update OTT support list
  _docs/_developer_guide/platform_wide/tv_and_ott.md
Labels: cla-signed

#4828 BD-1904: Add note about Android verbose logging
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
Labels: cla-signed

#4830 Updated JavaScript bridge note to include Swift
  _docs/_user_guide/message_building_by_channel/in-app_messages/customize/html_in-app_messages.md
Labels: cla-signed

#4831 New paragraph and list styling for email global style settings
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
  assets/img_archive/dnd_basic_styling.png
  assets/img_archive/dnd_button_styling.png
  assets/img_archive/dnd_default_override.png
  assets/img_archive/dnd_fallbacks.png
  assets/img_archive/dnd_global_style_settings.png
  assets/img_archive/dnd_list_styling.png
  assets/img_archive/dnd_paragraph_styling.png
  assets/img_archive/dnd_text_styling.png
  assets/img_archive/dnd_title_styling.png
Labels: cla-signed

#4835 BD-1908: Fix typo
  _docs/_user_guide/administrative/manage_your_braze_users.md
Labels: cla-signed

#4812 Update FCM Push documentation
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  assets/img_archive/cloud_messaging_legacy_disabled.png
  assets/img_archive/cloud_messaging_legacy_enabled.png
Labels: cla-signed

#4838 BD-1910: SendGrid and SparkPost fixes
  _docs/_help/release_notes/2019/may.md
  _docs/_hidden/private_betas/sql_segments_tables.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _docs/_partners/message_orchestration/attribution/branch/branch_for_deeplinking.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _docs/_user_guide/message_building_by_channel/email/email_private_relay_apple_SSO.md
  _docs/_user_guide/message_building_by_channel/email/reporting_and_analytics/analytics_glossary.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl.md
  _docs/_user_guide/onboarding_with_braze/email_setup/ssl/ssl_clicktracking.md
Labels: cla-signed

#4836 Pinterest and Snapchat Audience Sync
  _docs/_hidden/private_betas/pinterest_audience_sync.md
  _docs/_hidden/private_betas/snapchat_audience_sync.md
  assets/img/pinterest/pinterest1.png
  assets/img/pinterest/pinterest10.png
  assets/img/pinterest/pinterest11.png
  assets/img/pinterest/pinterest2.png
  assets/img/pinterest/pinterest3.png
  assets/img/pinterest/pinterest4.png
  assets/img/pinterest/pinterest5.png
  assets/img/pinterest/pinterest6.png
  assets/img/pinterest/pinterest7.png
  assets/img/pinterest/pinterest8.png
  assets/img/pinterest/pinterest9.png
  assets/img/snapchat/snapchat1.png
  assets/img/snapchat/snapchat2.png
  assets/img/snapchat/snapchat3.png
  assets/img/snapchat/snapchat4.png
  assets/img/snapchat/snapchat5.png
  assets/img/snapchat/snapchat6.png
  assets/img/snapchat/snapchat7.png
Labels: cla-signed

#4839 BD-1909: Update /users/identify docs
  _docs/_api/endpoints/user_data/post_user_identify.md
  _docs/_api/endpoints/user_data/post_users_merge.md
  _docs/_hidden/private_betas/post_user_identify_merge_behavior.md
Labels: cla-signed

#4788 Attribution code snippet updates
  _docs/_partners/message_orchestration/attribution/adjust.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _docs/_partners/message_orchestration/attribution/branch/branch_for_attribution.md
  _docs/_partners/message_orchestration/attribution/kochava.md
  _docs/_partners/message_orchestration/attribution/singular.md
Labels: cla-signed

#4817 Jjm update sdk intros
  _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/overview.md
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
  _docs/_developer_guide/platform_wide.md
  _docs/_developer_guide/platform_wide/platform_features.md
  _docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
  _docs/_help/release_notes/2017/july.md
  _docs/_help/release_notes/2017/june.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/scripttag_web_sdk_integration.md
  _docs/_user_guide/message_building_by_channel/content_cards.md
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
  _docs/_user_guide/onboarding_with_braze.md
  _docs/_user_guide/onboarding_with_braze/learning_to_use_braze.md
  _docs/_user_guide/onboarding_with_braze/web_sdk.md
Labels: cla-signed

#4840 Update kochava.md
  _docs/_partners/message_orchestration/attribution/kochava.md
Labels: cla-signed

#4843 Image fix for french docs
  assets/img_archive/dnd_default_override.png
  assets/img_archive/dnd_text_styling.png
Labels: cla-signed

#4842 Update idle_campaigns.md
  _docs/_hidden/private_betas/idle_campaigns.md
Labels: cla-signed

#4845 BD-1915: Add blocklist permission caveat
  _docs/_api/endpoints/email/post_blacklist.md
  _docs/_api/endpoints/email/post_blocklist.md
Labels: cla-signed

#4846 BD-1916: Update Currents event fields
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#4844 Sunset alerts for creating and duplicating Canvases with original experience
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/duplicating_segments_and_campaigns.md
  _docs/_user_guide/engagement_tools/canvas.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/branching.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/exception_events.md
  _docs/_user_guide/engagement_tools/canvas/faqs.md
  _docs/_user_guide/engagement_tools/canvas/get_started/canvas_outlines.md
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/pre_post_launch_checklist.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
Labels: cla-signed

#4850 Remove API glossary and clean up references
  _docs/_api/endpoints/messaging.md
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_messages.md
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_campaigns.md
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_canvases.md
  _docs/_api/endpoints/messaging/send_messages/post_send_messages.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
  _docs/_api/parameters.md
Labels: cla-signed

#4848 [CO-1261] Updated documentations for catalog APIs to support JSON data type
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/patch_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/post_create_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/patch_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md
Labels: cla-signed

#4852 BD-1914: Update lifetime users description
  _docs/_user_guide/data_and_analytics/analytics/understanding_your_app_usage_data.md
Labels: cla-signed

#4851 BD-1913: Blocklisting or deleting custom data
  _docs/_user_guide/data_and_analytics/custom_data.md
  _docs/_user_guide/data_and_analytics/custom_data/blocklist_delete_custom_data.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/custom_data/pre-populating_custom_data.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  assets/img_archive/blocklist_warning.png
Labels: cla-signed

#4853 404 audit
  assets/js/broken_redirect_list.js
Labels: cla-signed

#4854 BD-1918: Update abort Currents event
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#4735 About Content Cards revamp
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
  assets/css/_content.scss
  assets/img_archive/cc_placement_banner.png
  assets/img_archive/cc_placement_inbox.png
  assets/img_archive/cc_placements.png
  assets/img_archive/cc_usecase_event.png
  assets/img_archive/cc_usecase_onboarding.png
  assets/img_archive/cc_usecase_promo.png
  assets/img_archive/cc_usecase_recommendation.png
Labels: cla-signed

#4818 External Feedback Pt. 1
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_campaigns.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
  _docs/_api/endpoints/user_data/post_user_alias.md
  _docs/_api/endpoints/user_data/post_user_identify.md
  _docs/_api/errors.md
  _docs/_api/identifier_types.md
  _docs/_api/objects_filters/canvas_entry_properties_object.md
  _docs/_api/objects_filters/event_object.md
  _docs/_api/objects_filters/purchase_object.md
  _docs/_api/objects_filters/recipient_object.md
  _docs/_api/objects_filters/trigger_properties_object.md
  _docs/_api/objects_filters/user_attributes_object.md
  _docs/_user_guide/data_and_analytics.md
  _docs/_user_guide/data_and_analytics/catalogs.md
  _docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
Labels: cla-signed

#4827 [SDK-3029] Swift SDK docs - Storage page
  _docs/_developer_guide/platform_integration_guides/ios/storage.md
  _docs/_developer_guide/platform_integration_guides/swift/storage.md
Labels: cla-signed

#4829 [SDK-3030] Swift docs - Sample Apps
  _docs/_developer_guide/platform_integration_guides/swift/sample_apps.md
Labels: cla-signed

#4856 Edit to About Content Cards
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
Labels: cla-signed

#4861 Reverting curly change
  _docs/_hidden/other/support_contact.md
Labels: cla-signed

#4862 Unscheduled deployment February 17, 2023
  _docs/_hidden/other/support_contact.md
Labels: cla-signed

#4868 Fix broken link
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
Labels: cla-signed

#4869 [SDK-3403] Add Swift snippet to React Native - Initial SDK setup
  _docs/_developer_guide/platform_integration_guides/flutter/flutter_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Labels: cla-signed

#4871 BD-1920: Update attribution and trigger order for change attribute tr…
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/attribute_triggers.md
Labels: cla-signed

#4872 BD-1923: Clarify internationalization is not available in IAM DND editor
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/campaigns_in_multiple_languages.md
Labels: cla-signed

#4873 BD-1925: Fix typo
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
Labels: cla-signed

#4859 Komo Partnership Docs
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content.md
  _docs/_partners/message_personalization/dynamic_content/komo.md
  assets/img/komo/komo_hub_publish.png
  assets/img/komo/komo_hub_settings_braze_connect.png
  assets/img/komo/komo_hub_settings_braze_key.png
  assets/img/komo/komo_hub_settings_braze_settings.png
  assets/img/komo/komo_hub_settings_integrations.png
Labels: cla-signed, Braze Partnerships

#4864 GlobalLink Translation PR
  _lang/fr/_user_guide/engagement_tools/segments/segment_extension.md
  _lang/fr/_user_guide/engagement_tools/segments/segment_funnels.md
  _lang/fr/_user_guide/engagement_tools/templates_and_media.md
  _lang/fr/_user_guide/engagement_tools/testing/global_control_group.md
  _lang/fr/_user_guide/engagement_tools/testing/multivariant_testing.md
  _lang/fr/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md
  _lang/fr/_user_guide/message_building_by_channel/content_cards.md
  _lang/fr/_user_guide/message_building_by_channel/content_cards/about.md
  _lang/fr/_user_guide/message_building_by_channel/content_cards/create.md
  _lang/fr/_user_guide/message_building_by_channel/content_cards/creative_details.md
  _lang/fr/_user_guide/message_building_by_channel/content_cards/customize.md
  _lang/fr/_user_guide/message_building_by_channel/email.md
  _lang/fr/_user_guide/message_building_by_channel/email/email_private_relay_apple_SSO.md
  _lang/fr/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _lang/fr/_user_guide/message_building_by_channel/email/templates/email_template.md
  _lang/fr/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/about.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/create.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/customize.md
  _lang/fr/_user_guide/message_building_by_channel/in-app_messages/customize/html_in-app_messages.md
  _lang/fr/_user_guide/message_building_by_channel/push/advanced_push_options/push_action_buttons.md
  _lang/fr/_user_guide/message_building_by_channel/push/best_practices/conversion_tracking.md
  _lang/fr/_user_guide/message_building_by_channel/push/best_practices/detailed_push_preferences.md
  _lang/fr/_user_guide/message_building_by_channel/push/best_practices/message_format.md
  _lang/fr/_user_guide/message_building_by_channel/push/creating_a_push_message.md
  _lang/fr/_user_guide/message_building_by_channel/push/push_reporting.md
  _lang/fr/_user_guide/message_building_by_channel/sms.md
  _lang/fr/_user_guide/message_building_by_channel/sms/campaign/create.md
  _lang/fr/_user_guide/message_building_by_channel/sms/campaign/segments.md
  _lang/fr/_user_guide/message_building_by_channel/sms/faqs.md
  _lang/fr/_user_guide/message_building_by_channel/sms/mms/about_mms.md
  _lang/fr/_user_guide/message_building_by_channel/sms/mms/create.md
  _lang/fr/_user_guide/message_building_by_channel/webhooks.md
  _lang/fr/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  _lang/fr/_user_guide/message_building_by_channel/whatsapp/create.md
  _lang/fr/_user_guide/onboarding_faq.md
  _lang/fr/_user_guide/onboarding_with_braze/email_setup/email_validation.md
  _lang/fr/_user_guide/onboarding_with_braze/learning_to_use_braze.md
  _lang/fr/_user_guide/onboarding_with_braze/spam_regulations.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/connected_content.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/liquid.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  _lang/fr/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md
  _lang/fr/_user_guide/predictive_suite.md
  _lang/fr/_user_guide/predictive_suite/predictive_purchases.md
Labels: cla-signed

#4866 GlobalLink Translation PR
  _lang/fr/_api/data_retention.md
  _lang/fr/_developer_guide/platform_integration_guides/web/cookies_and_storage.md
  _lang/fr/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
Labels: cla-signed

#4834 Nift Partnership Docs
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/channel_extensions.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/nift.md
  assets/img/nift/braze_account_linked.png
  assets/img/nift/link_your_braze_account.png
Labels: cla-signed, Braze Partnerships

#4740 Loplat Partnership Docs
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/location.md
  _docs/_partners/message_personalization/location/loplat.md
  assets/img/loplat/loplat_action_based_delivery.png
  assets/img/loplat/loplat_api_triggered_delivery.png
Labels: cla-signed, Braze Partnerships

#4814 Flywheel Partnership Docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/flywheel.md
  _docs/_partners/home.md
Labels: cla-signed, Braze Partnerships

#4877 Note about machine opens
  _docs/_user_guide/intelligence/intelligent_timing.md
Labels: cla-signed

#4863 ActionIQ and Airbyte Partnership Docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/actioniq.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/airbyte.md
  _docs/_partners/home.md
Labels: cla-signed, Braze Partnerships

#4878 BD-1921: Clarify advancement behavior for Content Cards in Canvas
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/content-cards_in_canvas.md
  assets/img_archive/content-cards-in-canvas.png
Labels: cla-signed

#4797 Sisu Data Partnership Docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/business_intelligence.md
  _docs/_partners/data_and_infrastructure_agility/business_intelligence/sisu_data.md
  _docs/_partners/home.md
  assets/img/sisudata/kda_result_negative.png
  assets/img/sisudata/kda_result_positive.png
  assets/img/sisudata/metric_creation.png
  assets/img/sisudata/segment.png
Labels: cla-signed, Braze Partnerships

#4879 Long code timeline update
  _docs/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md
  _includes/archive/short_and_long_codes.md
Labels: cla-signed

#4880 BD-1931: Update global state change currents event
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#4881 Fix alias links
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/airbyte.md
Labels: cla-signed

#4847 BD-1911: New User Update UI and use cases
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
  assets/img_archive/canvas_user_update_cep.png
  assets/img_archive/canvas_user_update_increment.png
  assets/img_archive/canvas_user_update_remove.png
  assets/img_archive/canvas_user_update_test_preview.png
  assets/img_archive/canvas_user_update_update.png
  assets/img_archive/canvas_user_update_wishlist.png
Labels: cla-signed

#4875 warning for FCM api key
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
Labels: cla-signed

#4883 Update feature_flags.md
  _docs/_developer_guide/platform_wide/feature_flags.md
Labels: cla-signed

#4888 Followup for email edits
  _docs/_user_guide/onboarding_with_braze/email_setup/import_your_email_list.md
  _docs/_user_guide/onboarding_with_braze/email_setup/setting_up_ips_and_domains.md
Labels: cla-signed

#4887 Phrase Partnership Docs
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/localization.md
  _docs/_partners/message_personalization/localization/phrase.md
Labels: Braze Partnerships

#4886 Finessed manual code removal
  _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
Labels: cla-signed

#4889 BD-1926: User Lookup
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/targeting_users.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/segments.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _docs/_user_guide/engagement_tools/segments/location_targeting.md
  _docs/_user_guide/engagement_tools/segments/regex.md
  _docs/_user_guide/engagement_tools/segments/user_lookup.md
  assets/img_archive/user_lookup.png
  assets/img_archive/user_lookup_match.png
  assets/img_archive/user_lookup_nomatch.png
Labels: cla-signed

#4890 Update integration.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/custom_styling.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/default_feed.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/key_value_pairs.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/integration.md
Labels: cla-signed

#4892 Specify that daily recurring intelligent timing campaigns don't track…
  _docs/_user_guide/intelligence/intelligent_timing.md
Labels: cla-signed

#4894 Fix typo
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/slideup.md
Labels: cla-signed

#4895 BD-1932: Clarify multichannel promotion codes
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
Labels: cla-signed

#4885 Safari Web Push
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/safari_mobile_push.md
  assets/img/push_implementation_guide/add-to-homescreen.png
  assets/img/push_implementation_guide/safari-mobile-push-prompt.png
Labels: cla-signed

#4897 branch docs
  _docs/_partners/message_orchestration/attribution/branch/branch_for_attribution.md
Labels: cla-signed

#4896 Leftover Deploy - February 23, 2023
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/custom_styling.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/default_feed.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/key_value_pairs.md
  _docs/_developer_guide/platform_integration_guides/android/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/safari_mobile_push.md
  _docs/_developer_guide/platform_wide/feature_flags.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/airbyte.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/hightouch.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/hightouch/hightouch.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/hightouch/hightouch_personalization_api.md
  _docs/_partners/home.md
  _docs/_partners/message_orchestration/attribution/branch/branch_for_attribution.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/localization.md
  _docs/_partners/message_personalization/localization/phrase.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/targeting_users.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/segments.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _docs/_user_guide/engagement_tools/segments/location_targeting.md
  _docs/_user_guide/engagement_tools/segments/regex.md
  _docs/_user_guide/engagement_tools/segments/user_lookup.md
  _docs/_user_guide/intelligence/intelligent_timing.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/slideup.md
  _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
  _docs/_user_guide/onboarding_with_braze/email_setup/import_your_email_list.md
  _docs/_user_guide/onboarding_with_braze/email_setup/setting_up_ips_and_domains.md
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
  assets/img/hightouch/cohort5.png
  assets/img/hightouch/cohort6.png
  assets/img/hightouch/cohort7.png
  assets/img/push_implementation_guide/add-to-homescreen.png
  assets/img/push_implementation_guide/safari-mobile-push-prompt.png
  assets/img_archive/canvas_user_update_cep.png
  assets/img_archive/canvas_user_update_increment.png
  assets/img_archive/canvas_user_update_remove.png
  assets/img_archive/canvas_user_update_test_preview.png
  assets/img_archive/canvas_user_update_update.png
  assets/img_archive/canvas_user_update_wishlist.png
  assets/img_archive/user_lookup.png
  assets/img_archive/user_lookup_match.png
  assets/img_archive/user_lookup_nomatch.png
Labels: cla-signed, Deploy

#4898 Update preference_center_via_api.md
  _docs/_api/endpoints/preference_center.md
  _docs/_api/endpoints/preference_center/get_create_url_preference_center.md
  _docs/_api/endpoints/preference_center/get_list_preference_center.md
  _docs/_api/endpoints/preference_center/get_view_details_preference_center.md
  _docs/_api/endpoints/preference_center/post_create_preference_center.md
  _docs/_api/endpoints/preference_center/put_update_preference_center.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/preference_center_via_api.md
Labels: cla-signed

#4900 Update safari_mobile_push.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/safari_mobile_push.md
Labels: cla-signed

#4901 One-off Deploy - February 2, 2023
  _docs/_api/endpoints/preference_center.md
  _docs/_api/endpoints/preference_center/get_create_url_preference_center.md
  _docs/_api/endpoints/preference_center/get_list_preference_center.md
  _docs/_api/endpoints/preference_center/get_view_details_preference_center.md
  _docs/_api/endpoints/preference_center/post_create_preference_center.md
  _docs/_api/endpoints/preference_center/put_update_preference_center.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/safari_mobile_push.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/preference_center_via_api.md
Labels: cla-signed

#4903 Fix typos
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/hightouch/hightouch_personalization_api.md
Labels: cla-signed

#4893 Edits for Canvas v1 sunset pt. 2 - MERGE 2/28
  _docs/_developer_guide/platform_wide/app_group_configuration.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/decision_split.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/advancement.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/branching.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/content-cards_in_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/exception_events.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/time_based_canvas.md
  _docs/_user_guide/engagement_tools/canvas/faqs.md
  _docs/_user_guide/engagement_tools/canvas/get_started/canvas_outlines.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/archiving_canvases.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
  _docs/_user_guide/engagement_tools/canvas/testing_canvases/measuring_and_testing_with_canvas_analytics.md
  _docs/_user_guide/intelligence/intelligent_timing.md
  assets/img_archive/Journey_5.png
  assets/img_archive/Journey_6.png
  assets/img_archive/archive_canvas1.png
  assets/img_archive/archived_canvas.png
  assets/img_archive/canvas_test1.png
  assets/img_archive/canvas_test2.png
  assets/img_archive/schedule_frequency_capping.png
  assets/img_archive/unarchive_canvas.png
Labels: cla-signed

#4907 Android docs/ update react docs to explicitly add Kotlin
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Labels: cla-signed

#4823 [SDK-3027] Update swift analytics section
  _docs/_developer_guide/platform_integration_guides/swift/analytics.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/disabling_tracking.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/location_tracking.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/setting_user_ids.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/tracking_custom_events.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/tracking_sessions.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/uninstall_tracking.md
  _includes/archive/setting_user_ids/aliasing.md
Labels: cla-signed

#4905 BD-1937: Update AMP clients
  _docs/_user_guide/message_building_by_channel/email/amphtml.md
Labels: cla-signed

#4909 BD-1943: Remove canvas exit detail schema
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#4910 BD-1938: Update command line testing examples for iOS and Android
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/testing.md
  _docs/_developer_guide/platform_integration_guides/ios/push_notifications/testing.md
Labels: cla-signed

#4911 BD-1940: Clarify default max length for custom attribute arrays
  _docs/_api/objects_filters/user_attributes_object.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_wide/analytics_overview.md
  _docs/_home/static_video.md
Labels: cla-signed

#4913 BD-1940 part 2: Clarify custom attribute array default length
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
Labels: cla-signed

#4914 Removing original Canvas workflow images
  _docs/_partners/canvas_steps/facebook_audience_sync.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/decision_split.md
Labels: cla-signed

#4915 Fix Canvas alerts
  _docs/_hidden/private_betas/tiktok.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
Labels: cla-signed

#4906 BD-1939: Add currents state change source codes
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#4902 Audience Sync to TikTok
  _docs/_hidden/private_betas/pinterest_audience_sync.md
  _docs/_hidden/private_betas/snapchat_audience_sync.md
  _docs/_hidden/private_betas/tiktok.md
  _docs/_partners/canvas_steps/facebook_audience_sync.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  assets/img/tiktok/tiktok10.png
  assets/img/tiktok/tiktok11.png
  assets/img/tiktok/tiktok12.png
  assets/img/tiktok/tiktok13.png
  assets/img/tiktok/tiktok14.png
  assets/img/tiktok/tiktok15.png
  assets/img/tiktok/tiktok16.png
  assets/img/tiktok/tiktok17.png
  assets/img/tiktok/tiktok2.png
  assets/img/tiktok/tiktok3.png
  assets/img/tiktok/tiktok9.png
Labels: cla-signed

#4919 Edits for Canvas branching
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/advancement.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/branching.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#4918 SDK-3419 appboy to braze
  _docs/_developer_guide/platform_integration_guides/sdk_changelogs.md
  _docs/_developer_guide/platform_integration_guides/xamarin/analytics.md
  _docs/_developer_guide/platform_integration_guides/xamarin/changelog.md
  _docs/_developer_guide/platform_integration_guides/xamarin/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/xamarin/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/xamarin/news_feed.md
  _docs/_developer_guide/platform_integration_guides/xamarin/push_notifications.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2022/10_18_22.md
  _docs/_help/release_notes/2022/11_15_22.md
  _docs/_help/release_notes/2022/7_26_22.md
  _docs/_help/release_notes/2023/12_13_22.md
  _lang/fr/_developer_guide/platform_integration_guides/react_native/changelog.md
  _lang/fr/_developer_guide/platform_integration_guides/react_native/content_cards.md
  _lang/fr/_developer_guide/platform_integration_guides/react_native/inapp_messages.md
  _lang/fr/_developer_guide/platform_integration_guides/react_native/sample_app.md
  _lang/fr/_developer_guide/platform_integration_guides/sdk_changelogs.md
  _lang/fr/_developer_guide/platform_integration_guides/xamarin/ changelog.md
  _lang/fr/_developer_guide/platform_integration_guides/xamarin/analytics.md
  _lang/fr/_developer_guide/platform_integration_guides/xamarin/changelog.md
  _lang/fr/_developer_guide/platform_integration_guides/xamarin/inapp_messages.md
  _lang/fr/_developer_guide/platform_integration_guides/xamarin/initial_sdk_setup.md
  _lang/fr/_developer_guide/platform_integration_guides/xamarin/news_feed.md
  _lang/fr/_developer_guide/platform_integration_guides/xamarin/push_notifications.md
  _lang/fr/_help/release_notes.md
  _lang/fr/_help/release_notes/2022/10_18_22.md
  _lang/fr/_help/release_notes/2022/11_15_22.md
  _lang/fr/_help/release_notes/2022/7_26_22.md
  _lang/fr/_help/release_notes/2023/12_13_22.md
Labels: cla-signed

#4908 Live activities
  _docs/_api/endpoints/messaging/live_activity.md
  _docs/_api/endpoints/messaging/live_activity/update.md
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  _docs/_developer_guide/platform_integration_guides/swift/live_activities.md
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/safari_mobile_push.md
Labels: cla-signed
