Repository braze-inc/braze-docs, pull requests merged in 2024-07, with the labels that each got.

#7473 [SDK Untracked] Clarify subscribeToSessionUpdates behavior
  _docs/_developer_guide/platform_integration_guides/swift/analytics/tracking_sessions.md
Labels: cla-signed

#7552 Add bundle ID configurations for Expo app extensions
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
Labels: cla-signed

#7610 BD-3186 Add unsubscribe note to global state change events
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#7503 [SDK-4885] Update Xamarin documentation for Swift + MAUI
  _docs/_developer_guide/platform_integration_guides/xamarin/analytics.md
  _docs/_developer_guide/platform_integration_guides/xamarin/changelog.md
  _docs/_developer_guide/platform_integration_guides/xamarin/content_cards.md
  _docs/_developer_guide/platform_integration_guides/xamarin/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/xamarin/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/xamarin/news_feed.md
  _docs/_developer_guide/platform_integration_guides/xamarin/push_notifications.md
Labels: cla-signed

#7612 BD-3217 and BD-3218: General Shopify back-in-stock notifications, and price drop notifications for catalogs GA
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/price_drop_notifications.md
  assets/img/Shopify/shopify_back-in-stock.png
Labels: cla-signed

#7614 Update internal_groups_tab.md
  _docs/_user_guide/administrative/app_settings/internal_groups_tab.md
Labels: cla-signed

#7608 BD-3213 Add rules-based merging to Duplicate Users
  _docs/_user_guide/engagement_tools/segments/user_profiles/duplicate_users.md
  assets/img/audience_management/duplicate_users/edit_rules.png
Labels: cla-signed

#7616 BD-3222 update SMS link shortening
  _docs/_hidden/private_betas/link_shortening.md
  assets/img/link_shortening/shortening1.png
Labels: cla-signed

#7611 BD-3208: Migrating from data feeds to promotion codes
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes/migrating_from_data_feeds.md
Labels: cla-signed

#7476 BD-3160 B2B Docs section and Lead Scoring
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies.md
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/lead_scoring.md
  _docs/_user_guide/message_building_by_channel/webhooks/lead_scoring.md
  assets/img/b2b/action_groups_simple.png
  assets/img/b2b/action_paths_selected_simple.png
  assets/img/b2b/action_paths_simple.png
  assets/img/b2b/entry_controls_simple.png
  assets/img/b2b/step_1_simple.png
  assets/img/b2b/step_2_simple.png
  assets/img/b2b/step_3_simple.png
  assets/img/b2b/step_3_webhook.png
  assets/img/b2b/step_4_simple.png
  assets/img/b2b/user_update_paths_simple.png
  assets/img/b2b/webhook.png
Labels: cla-signed

#7619 BD-3220: Update shopify_created_order payload and add Liquid example payload
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/using_shopify/shopify_data_in_braze.md
Labels: cla-signed

#7618 Update metadata.md
  _docs/_contributing/yaml_front_matter/metadata.md
Labels: cla-signed

#7620 BD-3214 Export all user data in a segment
  _docs/_user_guide/data_and_analytics/export_braze_data/segment_data_to_csv.md
Labels: cla-signed

#7621 BD-3227: Unhide SMS Geographic Permissions and related edits
  _docs/_user_guide/message_building_by_channel/sms.md
  _docs/_user_guide/message_building_by_channel/sms/sms_geographic_permissions.md
  assets/img/sms/sms_geographic_permissions_read_only.png
Labels: cla-signed

#7480 Updating PR template
  .github/PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla-signed

#7622 Deploy - July 2, 2024
  .github/PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE.md
  _docs/_contributing/yaml_front_matter/metadata.md
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/tracking_sessions.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/tracking_sessions.md
  _docs/_developer_guide/platform_integration_guides/xamarin/analytics.md
  _docs/_developer_guide/platform_integration_guides/xamarin/changelog.md
  _docs/_developer_guide/platform_integration_guides/xamarin/content_cards.md
  _docs/_developer_guide/platform_integration_guides/xamarin/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/xamarin/initial_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/xamarin/news_feed.md
  _docs/_developer_guide/platform_integration_guides/xamarin/push_notifications.md
  _docs/_hidden/private_betas/link_shortening.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/using_shopify/shopify_data_in_braze.md
  _docs/_user_guide/administrative/app_settings/internal_groups_tab.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/export_braze_data/segment_data_to_csv.md
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies.md
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/lead_scoring.md
  _docs/_user_guide/engagement_tools/segments/user_profiles/duplicate_users.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/style_settings.md
  _docs/_user_guide/message_building_by_channel/sms.md
  _docs/_user_guide/message_building_by_channel/sms/sms_geographic_permissions.md
  _docs/_user_guide/message_building_by_channel/webhooks/lead_scoring.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/price_drop_notifications.md
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes/migrating_from_data_feeds.md
  assets/img/Shopify/shopify_back-in-stock.png
  assets/img/audience_management/duplicate_users/edit_rules.png
  assets/img/b2b/action_groups_simple.png
  assets/img/b2b/action_paths_selected_simple.png
  assets/img/b2b/action_paths_simple.png
  assets/img/b2b/entry_controls_simple.png
  assets/img/b2b/step_1_simple.png
  assets/img/b2b/step_2_simple.png
  assets/img/b2b/step_3_simple.png
  assets/img/b2b/step_3_webhook.png
  assets/img/b2b/step_4_simple.png
  assets/img/b2b/user_update_paths_simple.png
  assets/img/b2b/webhook.png
  assets/img/link_shortening/shortening1.png
  assets/img/sms/sms_geographic_permissions_read_only.png
Labels: cla-signed, Deploy

#7617 Updating Currents docs
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#7626 Revert general Shopify back-in-stock notif
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs.md
Labels: cla-signed

#7627 Deploy pt. 2 - July 2, 2024
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed, Deploy

#7625 Fixing the JSON in Currents docs
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#7631 Update universal_links.md
  _docs/_help/help_articles/email/universal_links.md
Labels: cla-signed

#7609 Add troubleshooting docs for Swift SDK IAM networking
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/troubleshooting.md
Labels: cla-signed

#7630 BD-3231 Multi-page IAMs GA
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
Labels: cla-signed

#7628 BD-3228 Delegating your custom domain
  _docs/_hidden/private_betas/link_shortening.md
Labels: cla-signed

#7633 [CO-2618] Remove references to the catalog-in-process-error
  _docs/_api/endpoints/catalogs/catalog_selections/asynchronous/delete_catalog_selection.md
  _docs/_api/endpoints/catalogs/catalog_selections/asynchronous/post_create_catalog_selections.md
Labels: cla-signed

#7634 BD-3233: Clarify email_encrypted detail
  _docs/_hidden/private_betas/field_level_encryption.md
Labels: cla-signed

#7636 BD-3226: Add Launch Content Block permission
  _docs/_hidden/misc_reference/scim_api_appendix.md
Labels: cla-signed

#7635 BD-3223: Add method for removing custom attribute
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
Labels: cla-signed

#7637 Add article and nav title to feedback
  _includes/feedback.html
  assets/js/feedback.js
Labels: cla-signed

#7638 BD-3236 Update landing pages beta
  _docs/_user_guide/engagement_tools/landing_pages/drag_and_drop.md
  assets/img/landing_pages/create.png
  assets/img/landing_pages/dnd.png
  assets/img/landing_pages/form.png
  assets/img/landing_pages/template.png
  assets/img/landing_pages/url_handle.png
Labels: cla-signed

#7589 BD-3200 LINE channel beta
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/message_building_by_channel/line.md
  _docs/_user_guide/message_building_by_channel/line/create.md
  _docs/_user_guide/message_building_by_channel/line/line_setup.md
  _docs/_user_guide/message_building_by_channel/line/messaging_users.md
  _docs/_user_guide/message_building_by_channel/line/reporting.md
  _docs/_user_guide/message_building_by_channel/line/subscription_groups.md
  _docs/_user_guide/message_building_by_channel/push.md
  assets/img/line/csv_export_user_data.png
  assets/img/line/filter_group.png
  assets/img/line/integration.png
  assets/img/line/line_composer.png
  assets/img/line/line_performance.png
  assets/img/line/line_subscription_groups.png
  assets/img/line/message.png
  assets/img/line/response_settings.png
  assets/img/line/test_preview.png
  assets/img/line/trigger.png
  assets/img/line/trigger_word_campaign.png
  assets/img/line/trigger_word_canvas.png
  assets/img/line/webhook_settings.png
Labels: cla-signed

#7640 Deploy pt 3 - July 8, 2024
  _docs/_api/endpoints/catalogs/catalog_selections/asynchronous/delete_catalog_selection.md
  _docs/_api/endpoints/catalogs/catalog_selections/asynchronous/post_create_catalog_selections.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/troubleshooting.md
  _docs/_help/help_articles/email/universal_links.md
  _docs/_hidden/misc_reference/scim_api_appendix.md
  _docs/_hidden/private_betas/field_level_encryption.md
  _docs/_hidden/private_betas/link_shortening.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/engagement_tools/landing_pages/drag_and_drop.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _docs/_user_guide/message_building_by_channel/line.md
  _docs/_user_guide/message_building_by_channel/line/create.md
  _docs/_user_guide/message_building_by_channel/line/line_setup.md
  _docs/_user_guide/message_building_by_channel/line/messaging_users.md
  _docs/_user_guide/message_building_by_channel/line/reporting.md
  _docs/_user_guide/message_building_by_channel/line/subscription_groups.md
  _docs/_user_guide/message_building_by_channel/push.md
  _includes/feedback.html
  _lang/ja/_developer_guide/platform_wide/getting_started/platform_overview.md
  assets/img/landing_pages/create.png
  assets/img/landing_pages/dnd.png
  assets/img/landing_pages/form.png
  assets/img/landing_pages/template.png
  assets/img/landing_pages/url_handle.png
  assets/img/line/csv_export_user_data.png
  assets/img/line/filter_group.png
  assets/img/line/integration.png
  assets/img/line/line_composer.png
  assets/img/line/line_performance.png
  assets/img/line/line_subscription_groups.png
  assets/img/line/message.png
  assets/img/line/response_settings.png
  assets/img/line/test_preview.png
  assets/img/line/trigger.png
  assets/img/line/trigger_word_campaign.png
  assets/img/line/trigger_word_canvas.png
  assets/img/line/webhook_settings.png
  assets/js/feedback.js
Labels: Deploy

#7641 BD-3224: Update Managing email subscription doc and Duplicate emails doc
  _docs/_user_guide/message_building_by_channel/email/best_practices/duplicate_emails.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/managing_email_subscriptions.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#7559 Replace securiti.ai with onetrust
  _includes/analytics.html
  _includes/footer.html
  _includes/header.html
  _includes/html_include.html
  assets/css/securitiai.css
  assets/js/securitiai.js
Labels: cla-signed

#7642 BD 3230 email provider warning
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_help/help_articles.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/message_building_by_channel/email/email_setup/import_your_email_list.md
  _includes/email-via-sms-warning.md
Labels: cla-signed

#7644 Deploy - July 9, 2024
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_help/help_articles.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/duplicate_emails.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/managing_email_subscriptions.md
  _docs/_user_guide/message_building_by_channel/email/email_setup/import_your_email_list.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _includes/analytics.html
  _includes/email-via-sms-warning.md
  _includes/footer.html
  _includes/header.html
  _includes/html_include.html
  assets/css/securitiai.css
  assets/js/broken_redirect_list.js
  assets/js/securitiai.js
Labels: cla-signed, Deploy

#7624 [SDK-4819] Add log level descriptions for Android SDK
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/test_your_basic_integration.md
Labels: cla-signed

#7605 Fixing 404s - June 2024
  _lang/fr/_hidden/other/handbooks.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#7647 BD-3219 and BD-3234: Promotion codes edits
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
Labels: cla-signed

#7450 [SDK-5061] Add push received offering to subscribeToUpdates API and a new delegate method
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/integration.md
Labels: cla-signed

#7632 Update notes on non-default optional data collection
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
Labels: cla-signed

#7652 BD-3237 Glossary Audit - Part 1
  _docs/_api/endpoints/messaging/live_activity/start.md
  _docs/_api/objects_filters/messaging/android_object.md
  _docs/_api/objects_filters/messaging/apple_object.md
  _docs/_api/objects_filters/messaging/web_objects.md
  _docs/_contributing/content_management.md
  _docs/_contributing/content_management/images.md
  _docs/_developer_guide/customization_guides/content_cards/creating_custom_content_cards.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/android_google_tag_manager.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/font_customization.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/in-app_message_delivery.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_help/release_notes/2020/december.md
  _docs/_partners/canvas_steps/criteo_audience_sync.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/treasuredata.md
  _docs/_partners/message_personalization/dynamic_content/movable_ink/customer_data_api.md
  _docs/_user_guide/data_and_analytics/creating_a_formula.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/dnd_preference_center.md
  _docs/_user_guide/message_building_by_channel/sms/sms_setup/terms.md
  _docs/_user_guide/sage_ai/intelligence/faqs.md
  _docs/_user_guide/sage_ai/predictive_suite/predictive_churn/prediction_faq.md
  _docs/_user_guide/sage_ai/recommendations/about_item_recommendations.md
  _docs/_user_guide/sage_ai/recommendations/ai_item_recommendations.md
Labels: cla-signed

#7654 BD-3240 GA Multiple WhatsApp Business Accounts
  _docs/_user_guide/message_building_by_channel/whatsapp/overview/multiple_subscription_groups.md
Labels: cla-signed

#7651 Add single-channel sends
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
Labels: cla-signed

#7657 Update about.md
  _docs/_developer_guide/platform_wide/feature_flags/about.md
Labels: cla-signed

#7656 docs updates
  _docs/_developer_guide/platform_wide/feature_flags/experiments.md
Labels: cla-signed

#7658 Update create.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
Labels: cla-signed

#7655 BD-3242 GA Dynamic URL shortening and tracking
  _docs/_hidden/private_betas/link_shortening.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/retargeting.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#7659 rate limit additions
  _docs/_developer_guide/platform_wide/feature_flags/faq.md
Labels: cla-signed

#7661 BD-3243 Update POST users merge to now include phone numbers
  _docs/_api/endpoints/user_data/post_users_merge.md
Labels: cla-signed

#7662 BD-3244 Correct CSV file sample for catalog creation
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
Labels: cla-signed

#7639 BD-3232 Update Teams with explanations
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/teams.md
Labels: cla-signed

#7650 BD-3235 Add SMS Total Clicks info
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _includes/campaign_analytics.md
Labels: cla-signed

#7663 CO-2702 Update catalog documentation with array type support examples.
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/patch_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/post_create_catalog_items_bulk.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/put_update_catalog_items.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/patch_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/put_update_catalog_item.md
  _docs/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md
Labels: cla-signed

#7666 BD-3241 Update WhatsApp phone number migration section
  _docs/_user_guide/message_building_by_channel/whatsapp/overview/phone_number_migration.md
  assets/img/whatsapp/waba_manager.png
Labels: cla-signed

#7596 BD-3164, BD-3165 - AI Liquid Assistant overview and prompt guide
  _docs/_user_guide/sage_ai/generative_ai.md
  _docs/_user_guide/sage_ai/generative_ai/ai_liquid.md
  _docs/_user_guide/sage_ai/generative_ai/ai_liquid/ai_liquid_prompts.md
Labels: cla-signed

#7667 Update create.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
Labels: cla-signed

#7645 Update rate-limiting.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
Labels: cla-signed

#7672 BD-3237 Glossary alignment pt 2
  _docs/_api/endpoints/export/user_data/post_users_global_control_group.md
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_api/postman_collection.md
  _docs/_contributing/content_management/images.md
  _docs/_contributing/styling_examples.md
  _docs/_contributing/troubleshooting.md
  _docs/_developer_guide/customization_guides/content_cards/customizing_behavior.md
  _docs/_developer_guide/customization_guides/content_cards/customizing_feed.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/content_cards/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/web/content_cards/integration.md
  _docs/_developer_guide/platform_wide/feature_flags/experiments.md
  _docs/_developer_guide/platform_wide/getting_started/architecture_overview.md
  _docs/_developer_guide/platform_wide/getting_started/integration_overview.md
  _docs/_help/help_articles/email/open_rates.md
  _docs/_help/release_notes/2021/september.md
  _docs/_help/release_notes/2022/5_3_22.md
  _docs/_hidden/archived_layouts/get_endpoint.md
  _docs/_hidden/other/10dlc_application.md
  _docs/_hidden/private_betas/post_user_track_synchronous.md
  _docs/_partners/canvas_steps/criteo_audience_sync.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_partners/canvas_steps/pinterest_audience_sync.md
  _docs/_partners/canvas_steps/snapchat_audience_sync.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/ketch.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/treasure_data/treasure_data_for_currents.md
  _docs/_partners/message_orchestration/additional_channels/instant_chat/front.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/getting_started_shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_overview.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/using_shopify/shopify_data_in_braze.md
  _docs/_partners/message_personalization/dynamic_content/liftigniter.md
  _docs/_partners/message_personalization/dynamic_content/movable_ink.md
  _docs/_partners/message_personalization/dynamic_content/niftyimages.md
  _docs/_user_guide/administrative/app_settings/api_settings_tab.md
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/connected_sources.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/time_based_campaign.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties/canvas_persistent_entry_properties.md
  _docs/_user_guide/getting_started/users_segments.md
  _docs/_user_guide/getting_started/workspaces.md
  _docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_action_buttons.md
  _docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_stories.md
  _docs/_user_guide/message_building_by_channel/sms/best_practices/best_practices.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/back_in_stock_notifications.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
  _docs/_user_guide/sage_ai/generative_ai/ai_copywriting.md
  _includes/archive/setting_user_ids/best_practices.md
  _includes/archive/short_and_long_codes.md
  _includes/image_specs.md
Labels: cla-signed

#7669 Update web.md
  _docs/_user_guide/message_building_by_channel/push/web.md
Labels: cla-signed

#7674 fix layout redirect url
  _plugins/urlnavmenu_generator.rb
Labels: cla-signed

#7678 Update cross_referencing.md
  _docs/_contributing/content_management/cross_referencing.md
  _docs/_contributing/content_management/images.md
Labels: cla-signed

#7670 Fix ja table of content nav
  assets/js/documents.js
  assets/js/toc.js
  vercel.json
Labels: cla-signed

#7676 update price drop docs to look like back in stock
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/back_in_stock_notifications.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/price_drop_notifications.md
Labels: cla-signed

#7679 BD-3255: Remove note about Canvas Flow names coming soon
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#7680 Update overview.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
Labels: cla-signed

#7675 rename appboy to braze in sdk_authentication.md `Register a callback function for invalid tokens`
  _docs/_developer_guide/platform_wide/sdk_authentication.md
Labels: cla-signed

#7671 Update template_catalog_item_liquid.md
  _docs/_hidden/private_betas/template_catalog_item_liquid.md
Labels: cla-signed

#7686 Reverting SDK-5061 doc updates
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/integration.md
Labels: cla-signed

#7684 BD-3250 Add treatment sample group to User Archival
  _docs/_hidden/other/user_archival.md
  _docs/_user_guide/data_and_analytics/reporting/global_control_group_reporting.md
Labels: cla-signed

#7683 BD-3252 Add FAQ to Link aliasing
  _docs/_user_guide/message_building_by_channel/email/templates/faq.md
Labels: cla-signed

#7688 Fix missing content after a period.
  assets/js/documents.js
Labels: cla-signed

#7689 BD-3263 Add the icon for generating a nested event property schema.
  _docs/_user_guide/data_and_analytics/custom_data/custom_events/nested_objects.md
Labels: cla-signed

#7681 BD-3260 Snowflake Data Retention
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake/data_retention.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake/faqs.md
Labels: cla-signed

#7694 Minor edits
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
Labels: cla-signed

#7696 BD-3050-2 Update wording for user group sizes
  _docs/_user_guide/data_and_analytics/reporting/global_control_group_reporting.md
Labels: cla-signed

#7685 Update CDI segments for GA
  _docs/_user_guide/data_and_analytics/cloud_ingestion/connected_sources.md
  _docs/_user_guide/engagement_tools/segments/segment_extension/cdi_segments.md
Labels: cla-signed

#7701 Updated the favicon
  assets/favicon.ico
Labels: cla-signed

#7702 BD-3249: Add tip about record availability for Deliverability Center
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
Labels: cla-signed

#7703 BD-3259: Add clarity for "View Usage Data" permission
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#7705 BD-3267: Remove USERS_CANVAS_ABORT_SHARED and USERS_CAMPAIGNS_ABORT_SHARED
  _docs/_user_guide/engagement_tools/segments/sql_segments/sql_segments_tables.md
Labels: cla-signed

#7710 BD-3268: Update to "Abandoned Cart"
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/using_shopify/shopify_data_in_braze.md
Labels: cla-signed

#7709 Small style fix
  _docs/_partners/message_personalization/dynamic_content/amazon_personalize/amazon_personalize.md
Labels: cla-signed

#7706 BD-3225: Clarify TXT record
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
Labels: cla-signed

#7693 BD-3246: Autosave for campaigns beta - MERGE 7/18
  _docs/_hidden/private_betas/campaign_autosave.md
  assets/img/campaign_autosave.png
Labels: cla-signed

#7692 BD-3262: Export custom events and Export custom attributes endpoints GA - MERGE 7/18
  _docs/_api/endpoints/export/custom_attributes/get_custom_attributes.md
  _docs/_api/endpoints/export/custom_events/get_custom_events_data.md
Labels: cla-signed

#7711 add alert that both inactive and dormant users get archived
  _docs/_hidden/other/user_archival.md
Labels: cla-signed

#7682 BD-3245: Canvas templates EA - MERGE 7/18
  _docs/_hidden/private_betas/canvas_templates.md
  assets/img/canvas_template_example.png
  assets/img/save_canvas_as_template.png
Labels: cla-signed

#7728 Add back list-unsubscribe property detail
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#7727 BD-3251 About segments section
  _docs/_user_guide/engagement_tools/segments.md
Labels: cla-signed

#7725 BD-3272: Updates details for test IAMs
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md
Labels: cla-signed

#7726 Update example and minor edits
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
Labels: cla-signed

#7729 BD-3269 Add ampersand link to link aliasing
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
Labels: cla-signed

#7730 BD-3254 WhatsApp templates don't support coupon code buttons
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md
Labels: cla-signed

#7733 BD-3277: Update links
  _docs/_user_guide/personalization_and_dynamic_content.md
  _docs/_user_guide/personalization_and_dynamic_content/canvas_persistent_entry_properties.md
Labels: cla-signed

#7731 BD-3276 Update SMS Liquid functionality
  _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
Labels: cla-signed

#7718 [CO-2780] Updated users/identify users/delete document to include email as identifier
  _docs/_api/endpoints/user_data/post_user_delete.md
  _docs/_api/endpoints/user_data/post_user_identify.md
Labels: cla-signed

#7738 Fixed a bad line break
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2024/4_2_24.md
Labels: cla-signed

#7708 [PP-3841] Mark no checkout reconcileEmail support for liquid
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/getting_started_shopify.md
Labels: cla-signed

#7739 Fix link
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/analytics/setting_user_ids.md
Labels: cla-signed

#7721 Remove extra P from Appboy
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
Labels: cla-signed

#7707 BD-3238: New Currents permissions
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/adding_users_to_your_dashboard.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
  assets/img/braze_permissions/admin_level_permissions.png
  assets/img/braze_permissions/company_level_permissions.png
  assets/img/braze_permissions/exporting_user_permissions.png
  assets/img/braze_permissions/selecting_a_user.png
  assets/img/braze_permissions/workspace_level_permissions_individual.png
  assets/img/braze_permissions/workspace_level_permissions_set.png
Labels: cla-signed

#7698 [DLK-200] Add documentation about data retention policies - Merge 7/23
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
  _docs/_user_guide/data_and_analytics/braze_currents/available_partners.md
Labels: cla-signed

#7743 Minor edit
  _docs/_user_guide/administrative/app_settings/company_settings/automated_user_provisioning.md
Labels: cla-signed

#7734 July 23, 2024 release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2024.md
  _docs/_help/release_notes/2024/7_23_24.md
Labels: cla-signed

#7745 Update kramdown
  Gemfile.lock
Labels: cla-signed

#7744 Deploy - July 23, 2024
  Gemfile.lock
  _docs/_api/endpoints/user_data/post_user_delete.md
  _docs/_api/endpoints/user_data/post_user_identify.md
  _docs/_developer_guide/customization_guides/content_cards/creating_custom_content_cards.md
  _docs/_developer_guide/customization_guides/content_cards/customizing_behavior.md
  _docs/_developer_guide/customization_guides/content_cards/customizing_feed.md
  _docs/_developer_guide/customization_guides/content_cards/customizing_styles.md
  _docs/_developer_guide/customization_guides/content_cards/logging_analytics.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/analytics/setting_user_ids.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2024.md
  _docs/_help/release_notes/2024/4_2_24.md
  _docs/_help/release_notes/2024/7_23_24.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/getting_started_shopify.md
  _docs/_user_guide/administrative/app_settings/company_settings/automated_user_provisioning.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/adding_users_to_your_dashboard.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/data_and_analytics/braze_currents/available_partners.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
  _docs/_user_guide/engagement_tools/segments.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md
  _docs/_user_guide/personalization_and_dynamic_content.md
  _docs/_user_guide/personalization_and_dynamic_content/canvas_persistent_entry_properties.md
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
  assets/img/braze_permissions/admin_level_permissions.png
  assets/img/braze_permissions/company_level_permissions.png
  assets/img/braze_permissions/exporting_user_permissions.png
  assets/img/braze_permissions/selecting_a_user.png
  assets/img/braze_permissions/workspace_level_permissions_individual.png
  assets/img/braze_permissions/workspace_level_permissions_set.png
Labels: cla-signed, Deploy

#7724 BD-3264: Phrasee to Jacquard
  _docs/_help/release_notes/2021/april.md
  _docs/_help/release_notes/2022/12_13_22.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/ab_testing.md
  _docs/_partners/data_and_infrastructure_agility/ab_testing/jacquard.md
  _docs/_partners/data_and_infrastructure_agility/ab_testing/jacquard/jacquard.md
  _docs/_partners/data_and_infrastructure_agility/ab_testing/jacquard/jacquard_react.md
  _docs/_partners/data_and_infrastructure_agility/ab_testing/phrasee.md
  _docs/_partners/data_and_infrastructure_agility/ab_testing/phrasee/phrasee.md
  _docs/_partners/data_and_infrastructure_agility/ab_testing/phrasee/phrasee_react.md
  _docs/_partners/home.md
  assets/img/jacquard/10_push_two_lines.png
  assets/img/jacquard/11_push_messagebody.png
  assets/img/jacquard/1_create_apikey.png
  assets/img/jacquard/2_campaignaccess.png
  assets/img/jacquard/3_phrasee_braze1.png
  assets/img/jacquard/4_braze_emailtag.png
  assets/img/jacquard/5_copy_variant_braze.png
  assets/img/jacquard/6_braze_schedule.png
  assets/img/jacquard/7_braze_send_winner.png
  assets/img/jacquard/8_braze_int_drawer.png
  assets/img/jacquard/9_braze_push_tag.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#7749 Add back image folder for Phrasee
  assets/img/phrasee/10_push_two_lines.png
  assets/img/phrasee/11_push_messagebody.png
  assets/img/phrasee/1_create_apikey.png
  assets/img/phrasee/2_campaignaccess.png
  assets/img/phrasee/3_phrasee_braze1.png
  assets/img/phrasee/4_braze_emailtag.png
  assets/img/phrasee/5_copy_variant_braze.png
  assets/img/phrasee/6_braze_schedule.png
  assets/img/phrasee/7_braze_send_winner.png
  assets/img/phrasee/8_braze_int_drawer.png
  assets/img/phrasee/9_braze_push_tag.png
Labels: cla-signed

#7750 BD-3221: Update image
  assets/img_archive/media_library_main.png
Labels: cla-signed

#7751 BD-3292: Remove mentions of "Beginning December" and "Beginning April"
  _docs/_api/endpoints/export/user_data/post_users_segment.md
Labels: cla-signed

#7704 BD-3266 Add WhatsApp embedded signup article
  _docs/_user_guide/message_building_by_channel/whatsapp/overview.md
  _docs/_user_guide/message_building_by_channel/whatsapp/overview/embedded_signup.md
  _docs/_user_guide/message_building_by_channel/whatsapp/overview/multiple_subscription_groups.md
  _docs/_user_guide/message_building_by_channel/whatsapp/overview/phone_number_migration.md
  assets/img/whatsapp/add_phone_number.png
  assets/img/whatsapp/business_info.png
  assets/img/whatsapp/create_select_waba.png
  assets/img/whatsapp/finish.png
  assets/img/whatsapp/get_started.png
  assets/img/whatsapp/instructions.png
  assets/img/whatsapp/login_screen.png
  assets/img/whatsapp/permissions.png
  assets/img/whatsapp/two_factor.png
  assets/img/whatsapp/waba_details.png
  assets/img/whatsapp/whatsapp1.png
Labels: cla-signed

#7748 File initial_sdk_setup.md committed.
  _lang/ja/_developer_guide/customization_guides/content_cards.md
  _lang/ja/_developer_guide/customization_guides/content_cards/creating_custom_content_cards.md
  _lang/ja/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _lang/ja/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
  _lang/ja/_user_guide/engagement_tools/segments/segment_extension.md
  _lang/ja/_user_guide/engagement_tools/segments/segment_extension/cdi_segments.md
Labels: cla-signed

#7740 BD-3286 Catalog use cases and explanation
  _docs/_user_guide/personalization_and_dynamic_content/catalogs.md
Labels: cla-signed

#7754 Add note for Canvas templates
  _docs/_hidden/private_betas/canvas_templates.md
Labels: cla-signed

#7700 BD-3253: Filter for active and draft content
  _docs/_user_guide/administrative/access_braze/global_search.md
  assets/img/global_search/global_search.png
  assets/img/global_search/global_search2.png
  assets/img/global_search/show_active_draft.png
Labels: cla-signed

#7746 [PP-3871] remove reconcile email from docs
  _docs/_help/release_notes/deprecations/shopify_checkout.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/getting_started_shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_user_identity.md
  _lang/fr/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
Labels: cla-signed

#7759 Revert "Add note for Canvas templates"
  _docs/_hidden/private_betas/canvas_templates.md
Labels: cla-signed

#7762 fix ja switcher
  assets/js/documents.js
Labels: cla-signed

#7768 BD-3278 Add note about Liquid filter
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
Labels: cla-signed

#7766 BD-3295 Add 'Metrics by segments' report docs
  _docs/_user_guide/data_and_analytics/query_builder/query_templates.md
  _docs/_user_guide/data_and_analytics/reporting/data_by_segments.md
  _docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md
Labels: cla-signed

#7752 BD-3265 Add phone number acquisition docs
  _docs/_user_guide/message_building_by_channel/whatsapp/overview/phone_number_acquisition.md
  assets/img/whatsapp/active_numbers.png
  assets/img/whatsapp/buy.png
  assets/img/whatsapp/develop_buy_number.png
  assets/img/whatsapp/infoblip_10dlc.png
  assets/img/whatsapp/infoblip_buy.png
  assets/img/whatsapp/infoblip_numbers.png
  assets/img/whatsapp/infoblip_offer.png
  assets/img/whatsapp/infoblip_verify.png
  assets/img/whatsapp/verify.png
Labels: cla-signed

#7761 Update content_cards_object.md
  _docs/_api/objects_filters/messaging/content_cards_object.md
Labels: cla-signed

#7764 BD-3287 Update MMS image specs
  _docs/_user_guide/message_building_by_channel/sms/mms/create.md
Labels: cla-signed

#7646 Update ai_item_recommendations.md
  _docs/_user_guide/sage_ai/recommendations/ai_item_recommendations.md
Labels: cla-signed

#7765 BD-3279 Add tiles to Generative AI
  _docs/_user_guide/sage_ai/generative_ai.md
Labels: cla-signed

#7769 BD-3173 Update Okta SAML SSO settings
  _docs/_user_guide/administrative/access_braze/single_sign_on/okta.md
  assets/img/Okta/okta1.png
Labels: cla-signed

#7772 BD-3305: Update links
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
Labels: cla-signed

#7773 Edits from voice team meeting
  _docs/_user_guide/administrative/app_settings/workspaces.md
Labels: cla-signed

#7777 Add closing bracket to tip alert
  _docs/_user_guide/administrative/app_settings/workspaces.md
Labels: cla-signed

#7775 BD-3297: Update catalog field limit
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  assets/img_archive/catalog_CSV_upload.png
Labels: cla-signed

#7778 Add CDI to user permissions list
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#7755 bd3293 Intelligence Suite use cases
  _docs/_user_guide/sage_ai/intelligence.md
  assets/img/intelligence_suite1.png
  assets/img/intelligent_selection_canvas.png
Labels: cla-signed

#7779 Added links to catalog use cases
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_overview.md
Labels: cla-signed

#7774 BD-3301: FAQ for Canvas templates
  _docs/_hidden/private_betas/canvas_templates.md
Labels: cla-signed

#7780 Deploy - June 30, 2024
  _docs/_api/objects_filters/messaging/content_cards_object.md
  _docs/_hidden/compliance/webhook_channel.md
  _docs/_hidden/private_betas/canvas_templates.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_overview.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/okta.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/administrative/app_settings/workspaces.md
  _docs/_user_guide/data_and_analytics/query_builder/query_templates.md
  _docs/_user_guide/data_and_analytics/reporting/data_by_segments.md
  _docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md
  _docs/_user_guide/message_building_by_channel/sms/mms/create.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  _docs/_user_guide/message_building_by_channel/whatsapp/overview/phone_number_acquisition.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
  _docs/_user_guide/sage_ai/generative_ai.md
  _docs/_user_guide/sage_ai/intelligence.md
  _docs/_user_guide/sage_ai/recommendations/ai_item_recommendations.md
  assets/img/Okta/okta1.png
  assets/img/intelligence_suite1.png
  assets/img/intelligent_selection_canvas.png
  assets/img/whatsapp/active_numbers.png
  assets/img/whatsapp/buy.png
  assets/img/whatsapp/develop_buy_number.png
  assets/img/whatsapp/infoblip_10dlc.png
  assets/img/whatsapp/infoblip_buy.png
  assets/img/whatsapp/infoblip_numbers.png
  assets/img/whatsapp/infoblip_offer.png
  assets/img/whatsapp/infoblip_verify.png
  assets/img/whatsapp/verify.png
  assets/img_archive/catalog_CSV_upload.png
  assets/js/documents.js
Labels: Deploy

#7781 Update about.md
  _docs/_user_guide/message_building_by_channel/push/about.md
Labels: cla-signed

#7784 Update year for KO deprecation to 2025
  _docs/_user_guide/administrative/access_braze/navigation.md
Labels: cla-signed
