Repository braze-inc/braze-docs, pull requests merged in 2024-08, with the labels that each got.

#7786 Update credit_ratios.md
  _docs/_hidden/other/credit_ratios.md
Labels: cla-signed

#7660 BD-3064 Update types of phone numbers - Part 1
  _includes/archive/short_and_long_codes.md
Labels: cla-signed

#7716 Peer Review Workshop - Optional Edits
  _docs/_user_guide/sage_ai/generative_ai/ai_liquid.md
  assets/img/ai_liquid/add_countdown.png
  assets/img/ai_liquid/ai_assistant_icon.png
  assets/img/ai_liquid/ai_assistant_window.png
  assets/img/ai_liquid/improve_my_liquid.png
  assets/img/ai_liquid/inspire_me.png
  assets/img/ai_liquid/use_app_activity.png
Labels: cla-signed

#7787 BD-3313 Update Currents permissions
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#7788 BD-3312 Fix Created Order tab
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/using_shopify/shopify_data_in_braze.md
Labels: cla-signed

#7789 Fixed broken links
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs.md
Labels: cla-signed

#7791 BD-3296: Add note on consuming data points
  _docs/_help/help_articles/push/push_unsubscribes.md
Labels: cla-signed

#7796 Change "Manage Users" to "Company Users"
  _docs/_api/endpoints/scim/delete_existing_dashboard_user.md
  _docs/_user_guide/administrative/app_settings/company_settings/security_settings.md
Labels: cla-signed

#7797 Fix email tile
  _docs/_user_guide/message_building_by_channel/email/best_practices.md
Labels: cla-signed

#7795 BD-3299 Update catalog segments use cases
  _docs/_user_guide/engagement_tools/segments/sql_segments/catalog_segments.md
Labels: cla-signed

#7798 BD-3058 Add channel-specific behavior to segmentation filters
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#7799 BD-3321 Update security event download
  _docs/_user_guide/administrative/app_settings/company_settings/security_settings.md
Labels: cla-signed

#7800 Shrunk the request type helper text
  _docs/_hidden/other/documentation_request.md
Labels: cla-signed

#7801 Fix punctuation issue
  assets/js/documents.js
Labels: cla-signed

#7805 BD-3327: Support for templates in a catalog name
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
Labels: cla-signed

#7563 Partners: LiveRamp + Snowflake + Braze
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/advertising.md
  _docs/_partners/data_and_infrastructure_agility/advertising/liveramp.md
  _docs/_partners/home.md
Labels: cla-signed

#7809 Quick fix: Missing link
  _docs/_user_guide/message_building_by_channel/push/about.md
Labels: cla-signed

#7804 Clarify archived campaign template behavior
  _docs/_user_guide/engagement_tools/templates_and_media/managing_templates.md
Labels: cla-signed

#7808 Quick Fix: Missing Link for Xamarin
  _docs/_developer_guide/platform_integration_guides/xamarin/initial_sdk_setup.md
Labels: cla-signed

#7806 BD-3280: Update suggestion to preference center in click rates
  _docs/_help/help_articles/email/open_rates.md
Labels: cla-signed

#7757 User Import notes for brand voice
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Labels: cla-signed

#7807 BD-3294: Add workaround for Liquid abort tag in conversion events
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/conversion_events.md
Labels: cla-signed

#7811 BD-2176: Add what only admins can do
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#7812 BD-3056: Add response example for messages by channel
  _docs/_api/endpoints/export/canvas/get_canvas_details.md
Labels: cla-signed

#7814 BD-2979: Create Catalog Triggers subsection and relocate articles
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/back_in_stock_notifications.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/price_drop_notifications.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#7792 BD-3302 Update Liquid tags that trigger templated IAMs
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/faq.md
Labels: cla-signed

#7817 BD-3335 Update alphanumeric sender IDs
  _includes/archive/short_and_long_codes.md
Labels: cla-signed

#7818 Update attribute_triggers.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/attribute_triggers.md
Labels: cla-signed

#7815 BD-3322 Update DnD dark mode FAQ
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/faq.md
Labels: cla-signed

#7824 BD-3307: Update image
  _docs/_user_guide/administrative/app_settings/subscription_and_usage.md
  assets/img/subscription_and_billing4.png
Labels: cla-signed

#7821 Clarify behavior of config_only
  _docs/_contributing/yaml_front_matter/page_layouts.md
Labels: cla-signed

#7826 Deploy - August 6, 2024
  _docs/_api/endpoints/export/canvas/get_canvas_details.md
  _docs/_api/endpoints/scim/delete_existing_dashboard_user.md
  _docs/_contributing/yaml_front_matter/page_layouts.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/macOS.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/tvos.md
  _docs/_developer_guide/platform_integration_guides/xamarin/initial_sdk_setup.md
  _docs/_help/help_articles/email/open_rates.md
  _docs/_help/help_articles/push/push_unsubscribes.md
  _docs/_hidden/other/documentation_request.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/advertising.md
  _docs/_partners/data_and_infrastructure_agility/advertising/liveramp.md
  _docs/_partners/home.md
  _docs/_user_guide/administrative/app_settings/company_settings/security_settings.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/administrative/app_settings/subscription_and_usage.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/conversion_events.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/attribute_triggers.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/engagement_tools/segments/sql_segments/catalog_segments.md
  _docs/_user_guide/engagement_tools/segments/sql_segments/sql_segments_tables.md
  _docs/_user_guide/engagement_tools/templates_and_media/managing_templates.md
  _docs/_user_guide/message_building_by_channel/email/best_practices.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/faq.md
  _docs/_user_guide/message_building_by_channel/email/email_setup/authentication.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/faq.md
  _docs/_user_guide/message_building_by_channel/push/about.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/back_in_stock_notifications.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/price_drop_notifications.md
  _includes/archive/short_and_long_codes.md
  assets/img/subscription_and_billing4.png
  assets/js/broken_redirect_list.js
  assets/js/documents.js
Labels: cla-signed, Deploy

#7827 BD-3334 Update navigation page with new screenshots and info
  _docs/_user_guide/administrative/access_braze/navigation.md
  assets/img/navigation/global_header_compare.png
  assets/img/navigation/global_header_new.png
  assets/img/navigation/global_header_old.png
  assets/img/navigation/global_header_switch.png
  assets/img/navigation/sidebar_new.png
  assets/img/navigation/sidebar_old.png
Labels: cla-signed

#7823 BD-3288: Add FAQ for scheduled campaign
  _docs/_user_guide/engagement_tools/campaigns/faq.md
Labels: cla-signed

#7829 BD-3338 Apply template standards to Query Builder
  _docs/_user_guide/data_and_analytics/query_builder.md
  _docs/_user_guide/data_and_analytics/query_builder/query_templates.md
Labels: cla-signed

#7767 Example success request and notice explanation
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
Labels: cla-signed

#7834 BD-3273: Update text and replace image
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _includes/email-via-sms-warning.md
  assets/img/importcsv5.png
Labels: cla-signed

#7836 [BD-3202] Clarifying headless UI for Apple TV
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/tvos.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/tvos.md
  _docs/_developer_guide/platform_integration_guides/tv_and_ott.md
Labels: cla-signed

#7838 BD-3274: Clarify iOS considerations for IAM
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize/video.md
Labels: cla-signed

#7839 BD-3144: Clarify SQL example and minor edits
  _docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md
Labels: cla-signed

#7832 Update scim_api_appendix.md
  _docs/_hidden/misc_reference/scim_api_appendix.md
Labels: cla-signed

#7842 BD-3215: Edits to Creating a catalog article
  _docs/_user_guide/personalization_and_dynamic_content/catalogs.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/using_catalogs.md
Labels: cla-signed

#7828 Update Punchh Dynamic Code Generation liquid
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/code_generation.md
  assets/img/punchh/punchh8.png
Labels: cla-signed

#7835 [BD-2809] Adding control variant alert to CC docs
  _docs/_developer_guide/customization_guides/content_cards/logging_analytics.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/integration.md
Labels: cla-signed

#7844 BD-3346: Updates to Jacquard
  _docs/_partners/data_and_infrastructure_agility/ab_testing/jacquard.md
  _docs/_partners/data_and_infrastructure_agility/ab_testing/jacquard/jacquard.md
  _docs/_partners/data_and_infrastructure_agility/ab_testing/jacquard/jacquard_react.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#7843 BD-3257: Clarify conversion tracking rules for multiple devices
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/conversion_events.md
Labels: cla-signed

#7845 BD-3330: Add FAQ for field-level encryption
  _docs/_hidden/private_betas/field_level_encryption.md
Labels: cla-signed

#7847 BD-3010: Clarify Redshift URL
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
Labels: cla-signed

#7841 BD-3342 Update estimated real open rate
  _includes/campaign_analytics.md
Labels: cla-signed

#7753 [SDK-4699] Subscribe to "Push received" event, with upcoming breaking updates
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/integration.md
Labels: cla-signed

#7849 Leftover deploy - August 8, 2024
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
  _docs/_developer_guide/customization_guides/content_cards/logging_analytics.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/tvos.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/tvos.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/tv_and_ott.md
  _docs/_hidden/misc_reference/scim_api_appendix.md
  _docs/_hidden/private_betas/field_level_encryption.md
  _docs/_partners/data_and_infrastructure_agility/ab_testing/jacquard.md
  _docs/_partners/data_and_infrastructure_agility/ab_testing/jacquard/jacquard.md
  _docs/_partners/data_and_infrastructure_agility/ab_testing/jacquard/jacquard_react.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/code_generation.md
  _docs/_user_guide/administrative/access_braze/navigation.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md
  _docs/_user_guide/data_and_analytics/query_builder.md
  _docs/_user_guide/data_and_analytics/query_builder/query_templates.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/conversion_events.md
  _docs/_user_guide/engagement_tools/campaigns/faq.md
  _docs/_user_guide/engagement_tools/news_feed.md
  _docs/_user_guide/engagement_tools/news_feed/best_practices.md
  _docs/_user_guide/engagement_tools/news_feed/creating_a_news_feed_item.md
  _docs/_user_guide/engagement_tools/news_feed/news_feed_analytics_and_retargeting_data.md
  _docs/_user_guide/engagement_tools/news_feed/news_feed_categories.md
  _docs/_user_guide/engagement_tools/news_feed/news_feed_use_cases.md
  _docs/_user_guide/message_building_by_channel.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize/video.md
  _docs/_user_guide/message_building_by_channel/push/android/rich_notifications.md
  _docs/_user_guide/message_building_by_channel/push/ios/rich_notifications.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/using_catalogs.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  _includes/campaign_analytics.md
  _includes/email-via-sms-warning.md
  assets/img/importcsv5.png
  assets/img/navigation/global_header_compare.png
  assets/img/navigation/global_header_new.png
  assets/img/navigation/global_header_old.png
  assets/img/navigation/global_header_switch.png
  assets/img/navigation/sidebar_new.png
  assets/img/navigation/sidebar_old.png
  assets/img/punchh/punchh8.png
  assets/img_archive/rich_notification_add_image.png
  assets/img_archive/rich_notification_ios_select.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#7850 BD-3341 Add Content Blocks to search list
  _docs/_user_guide/administrative/access_braze/global_search.md
Labels: cla-signed

#7813 BD-3329 Update FAQ about empty promotion codes
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
Labels: cla-signed

#7852 BD-3352 Update broken links in Segment
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
Labels: cla-signed

#7848 BD-3143: Add option for creating catalog for CDI
  _docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md
Labels: cla-signed

#7853 BD-3207: Update articles for search relevancy
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/preview_user_paths.md
  _docs/_user_guide/engagement_tools/canvas/testing_canvases/sending_test_canvases.md
Labels: cla-signed

#7855 File subscription_groups.md committed.
  _lang/ja/_user_guide/create.md
  _lang/ja/_user_guide/line.md
  _lang/ja/_user_guide/line_setup.md
  _lang/ja/_user_guide/message_building_by_channel.md
  _lang/ja/_user_guide/messaging_users.md
  _lang/ja/_user_guide/reporting.md
  _lang/ja/_user_guide/subscription_groups.md
Labels: cla-signed

#7857 File message_building_by_channel.md committed.
  _lang/ja/_user_guide/message_building_by_channel.md
  _lang/ja/_user_guide/message_building_by_channel/line.md
  _lang/ja/_user_guide/message_building_by_channel/line/create.md
  _lang/ja/_user_guide/message_building_by_channel/line/line_setup.md
  _lang/ja/_user_guide/message_building_by_channel/line/messaging_users.md
  _lang/ja/_user_guide/message_building_by_channel/line/reporting.md
  _lang/ja/_user_guide/message_building_by_channel/line/subscription_groups.md
Labels: cla-signed

#7831 BD-3340 Update catalog Liquid
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
Labels: cla-signed

#7858 BD-3356 Add a generic sample size calculator to A/B testing
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
Labels: cla-signed

#7861 Minor edits
  _docs/_user_guide/administrative/app_settings/multi_language_settings.md
Labels: cla-signed

#7859 BD-3353: Clarify triggers for Action Paths step
  _docs/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md
Labels: cla-signed

#7870 BD-3361: Fix typo
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#7864 BD-3336 Currents IP Allowlisting
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
Labels: cla-signed

#7871 Minor edits to Creating a webhook
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
Labels: cla-signed

#7854 BD-3345 Apply template standards to Tracking docs
  _docs/_user_guide/data_and_analytics/tracking.md
  _docs/_user_guide/data_and_analytics/tracking/email_tracking.md
  _docs/_user_guide/data_and_analytics/tracking/influenced_opens.md
  _docs/_user_guide/data_and_analytics/tracking/segment_analytics_tracking.md
  _docs/_user_guide/data_and_analytics/tracking/uninstall_tracking.md
  assets/img_archive/A_Tracking_2.png
  assets/img_archive/Influenced_Opens2.png
  assets/img_archive/Revenue.png
  assets/img_archive/Uninstall_Segment.png
  assets/img_archive/Uninstall_Tracking_App2.png
  assets/img_archive/campaign_level_uninstall_tracking.png
  assets/img_archive/events_over_time2.png
  assets/img_archive/segment_revenue_multiple.png
Labels: cla-signed

#7865 BD-3358 Apply templates to non-nested data & analytics docs
  _docs/_user_guide/data_and_analytics.md
  _docs/_user_guide/data_and_analytics/creating_a_formula.md
  _docs/_user_guide/data_and_analytics/data_points.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs.md
  assets/img_archive/kpi_forms.png
Labels: cla-signed

#7873 BD-3344 Remove video from Amplitude cohort import
  _docs/_partners/data_and_infrastructure_agility/cohort_import/amplitude.md
Labels: cla-signed

#7846 [BD-2667] Gif Support for all wrappers
  _docs/_developer_guide/platform_integration_guides/cordova/content_cards.md
  _docs/_developer_guide/platform_integration_guides/cordova/other_integrations.md
  _docs/_developer_guide/platform_integration_guides/flutter/content_cards.md
  _docs/_developer_guide/platform_integration_guides/flutter/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
  _docs/_developer_guide/platform_integration_guides/react_native/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/unity/content_cards.md
  _docs/_developer_guide/platform_integration_guides/unity/in-app_messaging.md
  _docs/_developer_guide/platform_integration_guides/xamarin/content_cards.md
  _docs/_developer_guide/platform_integration_guides/xamarin/inapp_messages.md
  _includes/wrappers/gif_support/content_cards.md
  _includes/wrappers/gif_support/in_app_messaging.md
Labels: cla-signed

#7875 BD-3363: Add 6-month detail for Email Insights dashboard
  _docs/_user_guide/data_and_analytics/analytics/email_performance_dashboard.md
Labels: cla-signed

#7876 Minor edits to In-app message in Canvas
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_by_channel/in-app_messages_in_canvas.md
Labels: cla-signed

#7862 BD-3349: Updates to translation API docs
  _docs/_api/endpoints/translations/get_bulk_translations_campaigns.md
  _docs/_api/endpoints/translations/get_bulk_translations_canvases.md
  _docs/_api/endpoints/translations/get_translation_campaign.md
  _docs/_api/endpoints/translations/get_translation_canvas.md
  _docs/_api/endpoints/translations/put_update_translation_campaign.md
  _docs/_api/endpoints/translations/put_update_translation_canvas.md
Labels: cla-signed

#7868 BD-3339: Data Transformation templates and new destination
  _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
  _includes/create_transformation.md
  assets/img/data_transformation/data_transformation10.png
  assets/img/data_transformation/data_transformation3.png
Labels: cla-signed

#7881 BD-3366: Add warning to autosave campaigns
  _docs/_hidden/private_betas/campaign_autosave.md
Labels: cla-signed

#7877 #BD-3058 part 2 - Add SMS details to segmentation definitions
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#7880 BD-3365: Clarify Canvas entry properties and event properties support
  _docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md
Labels: cla-signed

#7885 BD-3370 Replace missing user permission
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#7866 BD-3331: Importing CSV events EA
  _docs/_hidden/private_betas/csv_events.md
  _includes/email-via-sms-warning.md
  assets/download_file/braze-csv-events-import-template.csv
  assets/download_file/braze-events-csv-example-user-alias.csv
  assets/img/importcsv3.png
Labels: cla-signed

#7887 Update tv_and_ott.md
  _docs/_developer_guide/platform_integration_guides/tv_and_ott.md
Labels: cla-signed

#7883 Wording fix: "composer" to "editor"
  _docs/_hidden/private_betas/campaign_autosave.md
Labels: cla-signed

#7889 [BD-2696] Update Roku docs with sample app
  _docs/_developer_guide/platform_integration_guides/roku/initial_sdk_setup.md
Labels: cla-signed

#7891 BD-3367 Update screenshot
  _docs/_user_guide/message_building_by_channel/email/using_locales.md
  assets/img/multi-language_support/dnd_editor_translation_example.png
Labels: cla-signed

#7892 BD-3372 Add 'Rate' column for WhatsApp metrics
  _includes/campaign_analytics.md
Labels: cla-signed

#7896 BD-3373 Add A/B section to rate limiting
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
Labels: cla-signed

#7895 BD-3375: Fix typo
  _docs/_user_guide/engagement_tools/segments/user_profiles/duplicate_users.md
Labels: cla-signed

#7897 BD-3374 Add A/B section to multivariate campaign
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
Labels: cla-signed

#7886 BD-3371: Add preference center browser alert
  _docs/_user_guide/message_building_by_channel/email/preference_center/dnd_preference_center.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/overview.md
  _includes/preference_center_warning.md
Labels: cla-signed

#7899 BD-3376: Bulk merging GA
  _docs/_help/release_notes/deprecations/shopify_checkout.md
  _docs/_user_guide/engagement_tools/segments/user_profiles/duplicate_users.md
Labels: cla-signed

#7863 [BD-2880] Content Cards now base re-eligibilty on send time
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
Labels: cla-signed

#7758 [SDK Untracked] Update Appsflyer integration code snippet
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
Labels: cla-signed

#7697 [SDK-5070] Add Feature Flag expanded properties for Wrapper SDKs
  _docs/_developer_guide/platform_wide/feature_flags/create.md
Labels: status: do not merge, cla-signed

#7872 [BD-3379] Adding swift webview page
  _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/adding_braze_js_interface.md
Labels: cla-signed

#7901 BD-3360: Add Liquid note for Previewing user paths
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/preview_user_paths.md
Labels: cla-signed

#7903 Partner Docs: Zendesk Chat
  _docs/_partners/message_orchestration/additional_channels/instant_chat/zendesk_chat.md
  assets/img/zendesk/instant_chat/chat1.png
  assets/img/zendesk/instant_chat/chat10.png
  assets/img/zendesk/instant_chat/chat11.png
  assets/img/zendesk/instant_chat/chat12.png
  assets/img/zendesk/instant_chat/chat13.png
  assets/img/zendesk/instant_chat/chat14.png
  assets/img/zendesk/instant_chat/chat2.png
  assets/img/zendesk/instant_chat/chat3.png
  assets/img/zendesk/instant_chat/chat4.png
  assets/img/zendesk/instant_chat/chat5.png
  assets/img/zendesk/instant_chat/chat6.png
  assets/img/zendesk/instant_chat/chat7.png
  assets/img/zendesk/instant_chat/chat8.png
  assets/img/zendesk/instant_chat/chat9.png
Labels: cla-signed

#7905 BD-3368 Add catalog views details
  _docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md
Labels: cla-signed

#7907 BD-3381: Data export GA
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
Labels: cla-signed

#7906 Style edits
  _docs/_partners/data_and_infrastructure_agility/support/zendesk.md
Labels: cla-signed

#7909 Leftover deploy - August 15, 2024
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/migrating_to_firebase_cloud_messaging.md
  _docs/_developer_guide/platform_integration_guides/react_native/analytics.md
  _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/adding_braze_js_interface.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
  _docs/_help/release_notes/2022/12_13_22.md
  _docs/_help/release_notes/2023/5_30_23.md
  _docs/_help/release_notes/deprecations/shopify_checkout.md
  _docs/_partners/data_and_infrastructure_agility/advertising/liveramp.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/zeotap/symphony.md
  _docs/_partners/data_and_infrastructure_agility/support/zendesk.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/hightouch/hightouch_personalization_api.md
  _docs/_partners/message_orchestration/additional_channels/instant_chat/zendesk_chat.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
  _docs/_partners/message_personalization/dynamic_content/sheetlabs.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/adding_users_to_your_dashboard.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/triggered_action_based.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/preview_user_paths.md
  _docs/_user_guide/engagement_tools/segments/user_profiles/duplicate_users.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
  _docs/_user_guide/getting_started/overview.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/dnd_preference_center.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/overview.md
  _docs/_user_guide/message_building_by_channel/email/using_locales.md
  _includes/campaign_analytics.md
  _includes/preference_center_warning.md
  assets/img/multi-language_support/dnd_editor_translation_example.png
  assets/img/zendesk/instant_chat/chat1.png
  assets/img/zendesk/instant_chat/chat10.png
  assets/img/zendesk/instant_chat/chat11.png
  assets/img/zendesk/instant_chat/chat12.png
  assets/img/zendesk/instant_chat/chat13.png
  assets/img/zendesk/instant_chat/chat14.png
  assets/img/zendesk/instant_chat/chat2.png
  assets/img/zendesk/instant_chat/chat3.png
  assets/img/zendesk/instant_chat/chat4.png
  assets/img/zendesk/instant_chat/chat5.png
  assets/img/zendesk/instant_chat/chat6.png
  assets/img/zendesk/instant_chat/chat7.png
  assets/img/zendesk/instant_chat/chat8.png
  assets/img/zendesk/instant_chat/chat9.png
Labels: cla-signed, Deploy

#7890 [BD-2985] Clarify the different mParticle credentials
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md
Labels: cla-signed

#7911 Leftover deploy pt. 2 - August 15, 2024
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md
Labels: cla-signed, Deploy

#7902 BD-3369 LINE update
  _docs/_user_guide/message_building_by_channel/line.md
  _docs/_user_guide/message_building_by_channel/line/line_setup.md
  _docs/_user_guide/message_building_by_channel/line/line_users.md
  _docs/_user_guide/message_building_by_channel/line/line_users/subscription_groups.md
  _docs/_user_guide/message_building_by_channel/line/line_users/user_management.md
  assets/img/line/line_contact_settings.png
Labels: cla-signed

#7690 BD-3071 Liquid tutorials
  _docs/_user_guide/personalization_and_dynamic_content/liquid.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/faq.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/tutorials.md
  assets/css/_content.scss
Labels: cla-signed

#7915 BD-3385 Updates to Personalized Paths
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/personalized_paths.md
Labels: cla-signed

#7914 Removed REST API serialization from Currents event glossaries
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#7916 BD-3386 Hide News Feed Data Export article
  _docs/_user_guide/data_and_analytics/export_braze_data.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_news_feed_data.md
Labels: cla-signed

#7919 Added some grounding text to bring attention to the Braze Learning path
  _docs/_developer_guide/platform_wide/getting_started/platform_overview.md
Labels: cla-signed

#7920 Update zendesk_chat.md
  _docs/_partners/message_orchestration/additional_channels/instant_chat/zendesk_chat.md
Labels: cla-signed

#7922 BD-3315 Remove Fire TV push screenshot
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/android_tv_push.md
Labels: cla-signed

#7912 Update data_retention.md
  _docs/_api/data_retention.md
Labels: cla-signed

#7918 Update price_drop_notifications.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/back_in_stock_notifications.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/price_drop_notifications.md
Labels: cla-signed

#7908 August 2024 release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2024.md
  _docs/_help/release_notes/2024/8_20_24.md
Labels: cla-signed, release notes

#7925 Minor edits
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2024/7_23_24.md
Labels: cla-signed

#7927 Pick up where you left off GA
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2024/8_20_24.md
  _docs/_hidden/private_betas/pick_up_where_you_left_off.md
  _docs/_user_guide/data_and_analytics/analytics/home_dashboard.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#7921 [BD-3389] Revert "Update event documentation"
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#7930 Update drag_and_drop.md
  _docs/_user_guide/engagement_tools/landing_pages/drag_and_drop.md
Labels: cla-signed

#7926 BD-3392 Add LINE Login to User ID Reconciliation
  _docs/_user_guide/message_building_by_channel/line/line_setup.md
Labels: cla-signed

#7933 Fix Administrative > Privacy landing page icon
  _docs/_user_guide/administrative/privacy.md
Labels: cla-signed

#7935 Make LINE Users doc hidden
  _docs/_user_guide/message_building_by_channel/line/line_users.md
Labels: cla-signed

#7931 Updating the WhatsApp multiplier
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2024/8_20_24.md
  _docs/_hidden/pricing/message_credits_delta_a3sy.md
  _docs/_hidden/pricing/message_credits_gamma_0dhr.md
  _docs/_hidden/pricing/message_credits_lambda_k5gh.md
  _docs/_hidden/pricing/message_credits_sigma_pow2.md
  _docs/_hidden/pricing/message_credits_theta_d9kw.md
Labels: cla-signed

#7937 Deploy part 2 - August 21, 2024
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2024/8_20_24.md
  _docs/_hidden/pricing/message_credits_delta_a3sy.md
  _docs/_hidden/pricing/message_credits_gamma_0dhr.md
  _docs/_hidden/pricing/message_credits_lambda_k5gh.md
  _docs/_hidden/pricing/message_credits_sigma_pow2.md
  _docs/_hidden/pricing/message_credits_theta_d9kw.md
  _docs/_user_guide/administrative/privacy.md
  _docs/_user_guide/engagement_tools/landing_pages/drag_and_drop.md
  _docs/_user_guide/message_building_by_channel/line/line_setup.md
  _docs/_user_guide/message_building_by_channel/line/line_users.md
Labels: cla-signed, Deploy

#7934 [FF-589] - Update cookies_and_storage.md
  _docs/_developer_guide/platform_integration_guides/web/cookies_and_storage.md
Labels: cla-signed

#7940 Fix LINE tile
  _docs/_user_guide/message_building_by_channel/line.md
Labels: cla-signed

#7932 BD-3393 Add note about multiple brands to Shopify multiple stores
  _docs/_hidden/private_betas/multiple_stores.md
Labels: cla-signed

#7879 Update React Native docs with iOS push received events
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
Labels: cla-signed

#7840 BD-3206 Add data type use cases to default values
  _docs/_user_guide/personalization_and_dynamic_content/liquid/setting_default_values.md
Labels: cla-signed

#7941 BD-3396: Clarify Connected Content caching
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
Labels: cla-signed

#7830 Update faqs.md
  _docs/_user_guide/engagement_tools/templates_and_media/faqs.md
Labels: cla-signed

#7910 SessionM Partner Docs Upload
  _docs/_partners/message_orchestration/channel_extensions/loyalty/sessionm.md
  assets/img/sessionm/ComposeWebhook.png
  assets/img/sessionm/CreateSegment.png
  assets/img/sessionm/SessionMAddMessage.png
  assets/img/sessionm/SessionMAdvancedSettings.png
  assets/img/sessionm/SessionMBrazeTemplate.png
  assets/img/sessionm/SessionMCampaignCreation.png
  assets/img/sessionm/SessionMExternalMessage.png
  assets/img/sessionm/SessionMWebhookComposer.png
  assets/img/sessionm/SessionMWebhookSettings.png
  assets/img/sessionm/apiTriggerCampaign.png
  assets/img/sessionm/apiTriggerProperties.png
Labels: cla-signed

#7942 Leftover Deploy - August 22, 2024
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/web/cookies_and_storage.md
  _docs/_hidden/private_betas/multiple_stores.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/sessionm.md
  _docs/_user_guide/engagement_tools/templates_and_media/faqs.md
  _docs/_user_guide/message_building_by_channel/line.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/setting_default_values.md
  assets/img/sessionm/ComposeWebhook.png
  assets/img/sessionm/CreateSegment.png
  assets/img/sessionm/SessionMAddMessage.png
  assets/img/sessionm/SessionMAdvancedSettings.png
  assets/img/sessionm/SessionMBrazeTemplate.png
  assets/img/sessionm/SessionMCampaignCreation.png
  assets/img/sessionm/SessionMExternalMessage.png
  assets/img/sessionm/SessionMWebhookComposer.png
  assets/img/sessionm/SessionMWebhookSettings.png
  assets/img/sessionm/apiTriggerCampaign.png
  assets/img/sessionm/apiTriggerProperties.png
Labels: cla-signed, Deploy

#7944 Hide partner doc
  _docs/_partners/message_orchestration/channel_extensions/loyalty/sessionm.md
Labels: cla-signed

#7945 Leftover deploy pt. 2 - August 22, 2024
  _docs/_partners/message_orchestration/channel_extensions/loyalty/sessionm.md
Labels: cla-signed, Deploy

#7833 [BD-2890] Sending empty PN messages
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/silent_push_notifications.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/silent_push_notifications.md
  _docs/_user_guide/message_building_by_channel/push/android/notification_options.md
  _docs/_user_guide/message_building_by_channel/push/android/rich_notifications.md
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
  _docs/_user_guide/message_building_by_channel/push/ios/rich_notifications.md
Labels: status: do not merge, cla-signed

#7939 BD-3398 Apply template standards to Your Analytics Dashboards
  _docs/_user_guide/data_and_analytics/analytics/conversions_dashboard.md
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
  _docs/_user_guide/data_and_analytics/analytics/email_performance_dashboard.md
  _docs/_user_guide/data_and_analytics/analytics/home_dashboard.md
Labels: cla-signed

#7948 BD-3402: Add remove attribute detail
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
Labels: cla-signed

#7938 BD-3377 Triggered IAMs in Canvas EA
  _docs/_hidden/private_betas/canvas_triggered_iams.md
  assets/img_archive/canvas_expiration2.png
  assets/img_archive/canvas_priority2.png
  assets/img_archive/canvas_trigger_actions.png
Labels: status: done, cla-signed

#7949 Add EA banner
  _docs/_hidden/private_betas/canvas_triggered_iams.md
Labels: cla-signed

#7951 BD-3404: Add missing fields for `push_tokens`
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
  _docs/_api/endpoints/export/user_data/post_users_segment.md
Labels: cla-signed

#7952 BD-3408: Clarify rate limit
  _includes/rate_limits.md
Labels: cla-signed

#7953 Update ai_liquid.md
  _docs/_user_guide/sage_ai/generative_ai/ai_liquid.md
Labels: cla-signed

#7954 BD-3409: Update link
  _docs/_partners/message_orchestration/attribution/adjust.md
Labels: cla-signed

#7955 BD-3391: Add note about link templates
  _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
Labels: cla-signed

#7946 BD-3400 Message Usage Report doc
  _docs/_user_guide/administrative/app_settings/subscription_and_usage/message_usage.md
  assets/img/app_settings/credit_usage_over_contract1.png
  assets/img/app_settings/sms_credit_consumption2.png
  assets/img/app_settings/sms_table_null3.png
  assets/img/app_settings/whatsapp_credit_consumption4.png
  assets/img/sms_credit_consumption2.png
Labels: cla-signed

#7957 Updating 'sdk_min_versions_tag.rb'
  _plugins/sdk_min_versions_tag.rb
Labels: cla-signed

#7958 Update drag_and_drop.md
  _docs/_user_guide/engagement_tools/landing_pages/drag_and_drop.md
Labels: cla-signed

#7446 Docs utility scripts
  bdocs
  scripts/convert_reference_links.py
  scripts/deploy_text.sh
  scripts/release_text.sh
  scripts/remove_unused_reference_links.rb
Labels: status: do not merge, cla-signed

#7962 BD-3412: Update step
  _docs/_partners/data_and_infrastructure_agility/cohort_import/mixpanel.md
Labels: cla-signed

#7960 [FF-588] - Update web_objects.md
  _docs/_api/objects_filters/messaging/web_objects.md
Labels: cla-signed

#7964 BD-3411 Update web push notification screenshot
  assets/img_archive/web_push2.png
Labels: cla-signed

#7947 BD-3403 Add Cart ID to Abandoned Cart for Shopify
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/using_shopify/shopify_data_in_braze.md
Labels: cla-signed, In Review

#7967 Add proper doc for the newly introduced fields in /campaigns/details and /canvas/details APIs
  _docs/_api/endpoints/export/campaigns/get_campaign_details.md
Labels: cla-signed
