Repository braze-inc/braze-docs, pull requests merged in 2024-10, with the labels that each got.

#8186 Added a redirect for IDFA collection
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8187 Fix ruby syntax for 'ko' docs
  _lang/ko/_api/endpoints/export/purchases/get_revenue_series.md
Labels: cla-signed

#8188 BD-3525 Update UK Marketing ratios
  _docs/_hidden/other/credit_ratios.md
  _docs/_hidden/pricing/message_credits_delta_a3sy.md
  _docs/_hidden/pricing/message_credits_gamma_0dhr.md
  _docs/_hidden/pricing/message_credits_lambda_k5gh.md
  _docs/_hidden/pricing/message_credits_sigma_pow2.md
  _docs/_hidden/pricing/message_credits_theta_d9kw.md
Labels: cla-signed

#8163 [INN-1790] Add ingestion as codeowners
  .github/CODEOWNERS
  _docs/_api/endpoints/user_data/post_user_track.md
Labels: cla-signed, In Review

#8170 BD-3479 Add detail to Unique Recipients metric
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/data_and_analytics/reporting/report_builder.md
Labels: cla-signed

#8167 BD-3531 Docs feedback- Clarify Query Builder data timeline
  _docs/_user_guide/data_and_analytics/query_builder.md
Labels: cla-signed

#8176 BD-3535: Add new section to Google Audience Sync
  _docs/_partners/canvas_steps/google_audience_sync.md
Labels: cla-signed

#8143 BD-3509 Add LINE message types
  _docs/_user_guide/message_building_by_channel/line.md
  _docs/_user_guide/message_building_by_channel/line/create/message_types.md
  assets/img/line/line_card_message.png
  assets/img/line/line_image_message.png
  assets/img/line/line_message_types.png
  assets/img/line/line_rich_message.png
  assets/img/line/line_text_message.png
Labels: cla-signed

#7531 [BD-3182] Braze sdk debugging docs | Release Date Oct 1, 2024
  _docs/_developer_guide/platform_wide/debugging.md
  _docs/_developer_guide/platform_wide/feature_flags.md
  _docs/_developer_guide/platform_wide/getting_started.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
  _docs/_developer_guide/platform_wide/sending_test_messages.md
  assets/img/sdk_debugger/close_debugging_session.png
  assets/img/sdk_debugger/copy_id_and_export_logs.png
  assets/img/sdk_debugger/search_and_select_user.png
  assets/img/sdk_debugger/select_create_debugging_session.png
  assets/img/sdk_debugger/select_sdk_debugger.png
Labels: cla-signed

#8169 BD-3528 Docs feedback - Clarify message_extras Liquid
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
Labels: cla-signed

#8190 BD-3491: Add random audience re-entry using random bucket numbers
  _docs/_user_guide/engagement_tools/testing/random_bucket_numbers.md
  assets/img_archive/random_buckets_filterexample.png
Labels: cla-signed

#8192 Remove User CSV Lambda hidden doc and add redirect to CDI
  _docs/_hidden/other/user_csv_lambda.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8191 [Docs feedback] BD-3488 - Add user alias object example
  _docs/_api/objects_filters/user_alias_object.md
Labels: cla-signed

#8197 BD-3529 Update subscription groups header and link name
  _docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
Labels: cla-signed

#8201 Update create.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
Labels: cla-signed

#8198 Fixed a typo
  _docs/_user_guide/data_and_analytics/cloud_ingestion/file_storage_integrations.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
Labels: cla-signed

#8206 BD-3542: Update deleting custom data details
  _docs/_user_guide/data_and_analytics/custom_data/managing_custom_data.md
Labels: cla-signed

#8199 Update experiments.md
  _docs/_developer_guide/platform_wide/feature_flags/experiments.md
Labels: cla-signed

#8196 BD-3537 Add tip to CDI about UPDATED_AT time
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
Labels: cla-signed

#8203 [Docs feedback] BD-3489: Add reference link to API errors and responses
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
  _docs/_api/errors.md
Labels: cla-signed, In Review

#8212 BD-3546 Fix Liquid use case that has extra bracket
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
Labels: cla-signed

#8218 BD-3544 Update Email Capture form docs
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/email_capture.md
Labels: cla-signed

#8214 Update about.md
  _docs/_developer_guide/platform_wide/feature_flags/about.md
Labels: cla-signed

#8215 Update create.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
Labels: cla-signed

#8220 Wording fix for the loudly notify runbook
  _docs/_help/help_articles/api/webhook_connected_content_errors.md
Labels: cla-signed

#8221 BD-3520 Update tips for SMS and WhatsApp Canvas properties
  _docs/_user_guide/message_building_by_channel/sms/campaign/retargeting.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md
Labels: cla-signed

#8225 Fixing bug with bdocs release
  scripts/create_release_text.sh
Labels: cla-signed

#8217 Fix 404 links
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/analytics/disabling_tracking.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/content_cards/customization/customizing_feed.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/content_cards/customization/use_cases/carousel_view.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/content_cards/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/initial_sdk_setup/overview.md
  _docs/_help/release_notes/2019/july.md
  _docs/_help/release_notes/2022/5_3_22.md
  _docs/_user_guide/administrative/access_braze/accessing_your_account.md
  _docs/_user_guide/brazeai/predictive_suite/predictive_events.md
  _docs/_user_guide/getting_started/terms_to_know.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8228 BD-3493: Update how to capture user data with web form
  _docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md
Labels: cla-signed

#8216 BD-3018 Add section for how to add Unity Push icons
  _docs/_developer_guide/platform_integration_guides/unity/push_notifications/android.md
Labels: cla-signed

#8164 CO-2975: Allow recipients to be specified via email - MERGE 10/8
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
  _docs/_api/objects_filters/recipient_object.md
Labels: cla-signed

#8230 BD-3533 Add comparison table to Company Users page
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/teams.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#8223 BD-3552 Update LINE user ID intro
  _docs/_user_guide/message_building_by_channel/line/line_setup.md
Labels: cla-signed

#8229 BD-3480: Clarify reason for seeing PreferenceCenterBrazeDefault on dashboard
  _docs/_user_guide/message_building_by_channel/email/preference_center/overview.md
Labels: cla-signed

#8232 Deploy - October 8, 2024
  _docs/_api/api_limits.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
  _docs/_api/errors.md
  _docs/_api/objects_filters/recipient_object.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/analytics/disabling_tracking.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/content_cards/customization/customizing_feed.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/content_cards/customization/use_cases/carousel_view.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/content_cards/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/initial_sdk_setup/overview.md
  _docs/_developer_guide/platform_integration_guides/swift/live_activities/faq.md
  _docs/_developer_guide/platform_integration_guides/swift/live_activities/live_activities.md
  _docs/_developer_guide/platform_integration_guides/unity/push_notifications/android.md
  _docs/_developer_guide/platform_wide/feature_flags/about.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
  _docs/_help/help_articles/api/webhook_connected_content_errors.md
  _docs/_help/release_notes/2019/july.md
  _docs/_help/release_notes/2022/5_3_22.md
  _docs/_partners/canvas_steps/criteo_audience_sync.md
  _docs/_partners/canvas_steps/facebook_audience_sync.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_partners/canvas_steps/pinterest_audience_sync.md
  _docs/_partners/canvas_steps/snapchat_audience_sync.md
  _docs/_partners/canvas_steps/tiktok_audience_sync.md
  _docs/_user_guide/administrative/access_braze/accessing_your_account.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/teams.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/brazeai/predictive_suite/predictive_events.md
  _docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md
  _docs/_user_guide/engagement_tools/landing_pages/drag_and_drop.md
  _docs/_user_guide/getting_started/terms_to_know.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/overview.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/email_capture.md
  _docs/_user_guide/message_building_by_channel/line/line_setup.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/retargeting.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
  assets/img/add_languages.png
  assets/js/broken_redirect_list.js
  scripts/create_release_text.sh
Labels: cla-signed, Deploy

#8231 BD-3543: Add info about last updated column for custom attributes
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  assets/img/export_custom_attributes.png
Labels: cla-signed

#8234 Fix alerts
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
Labels: cla-signed

#8236 Swift SDK: Update with Objective-C samples for prepareWith method
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/setting_delegates.md
Labels: cla-signed

#8235 BD-3498: Add mentions of nested attributes and array of objects
  _docs/_api/objects_filters/user_attributes_object.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md
Labels: cla-signed

#8237 BD-3560: Condense beacon and geofence support info
  _docs/_partners/message_personalization/location/gimbal.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/location_tracking.md
  _docs/_user_guide/engagement_tools/segments.md
  _docs/_user_guide/engagement_tools/segments/beacon_support.md
  _docs/_user_guide/engagement_tools/segments/location_targeting.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8240 Edit for article title in YAML
  _docs/_contributing/content_management/jekyll_collections.md
Labels: cla-signed

#8239 BD-3541: Clarify ISO8601 timestamp format example
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
Labels: cla-signed

#8241 Leftover deploy - October 10, 2024
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
  _docs/_api/objects_filters/user_attributes_object.md
  _docs/_contributing/content_management/jekyll_collections.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/setting_delegates.md
  _docs/_developer_guide/platform_wide/feature_flags/faq.md
  _docs/_partners/message_personalization/location/gimbal.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/location_tracking.md
  _docs/_user_guide/engagement_tools/segments.md
  _docs/_user_guide/engagement_tools/segments/beacon_support.md
  _docs/_user_guide/engagement_tools/segments/location_targeting.md
  _docs/_user_guide/engagement_tools/testing/global_control_group.md
  assets/img/export_custom_attributes.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#8244 Fix tab name formatting
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/accessibility.md
  _lang/ja/_developer_guide/platform_integration_guides/android/initial_sdk_setup/accessibility.md
Labels: cla-signed

#8247 BD-3565 Update Query Builder with column name
  _docs/_user_guide/data_and_analytics/query_builder.md
Labels: cla-signed

#8249 BD-3550 Clarify landing pages beta note
  _docs/_user_guide/engagement_tools/landing_pages/drag_and_drop.md
Labels: cla-signed

#8248 BD-3551 Update AI item recommendation table
  _docs/_user_guide/brazeai/recommendations/ai_item_recommendations.md
Labels: cla-signed

#8242 BD-2894 Update contributing guide
  _docs/_contributing/git_and_github.md
  _docs/_contributing/home.md
  _docs/_contributing/your_first_contribution.md
  assets/img/contributing/github/allow_maintainers_to_edit.png
  assets/img/contributing/github/menu_pull_requests.png
Labels: cla-signed

#8253 BD-3570 Remove webhook messages from LINE
  _docs/_partners/message_orchestration/additional_channels/instant_chat/line.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8254 FF-716 / remove aud and iss from JWT specs
  _docs/_developer_guide/platform_wide/sdk_authentication.md
Labels: cla-signed

#8252 File huawei_integration.md committed.
  _lang/ko/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/huawei_integration.md
Labels: cla-signed

#8246 BD-3563 Update CTIA PDF link
  _docs/_user_guide/message_building_by_channel/sms/sms_laws_and_regulations.md
Labels: cla-signed

#8251 BD-3569 Update Audience Sync to Facebook TOS links
  _docs/_partners/canvas_steps/facebook_audience_sync.md
Labels: cla-signed

#8219 BD-3318-5 Apply Diataxis standards to Liquid documentation
  _docs/_user_guide/personalization_and_dynamic_content/liquid.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md
  assets/img_archive/insert_liquid_var_arrow.png
  assets/img_archive/insert_var_shot.gif
Labels: cla-signed

#8055 BD-3089 Create `includes` file for metrics
  _docs/_help/help_articles/email/email_bounces.md
  _docs/_user_guide/data_and_analytics/query_builder/query_templates.md
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _docs/_user_guide/message_building_by_channel/email/amphtml.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/email/reporting_and_analytics/analytics_glossary.md
  _docs/_user_guide/message_building_by_channel/sms/about_sms.md
  _includes/campaign_analytics.md
  _includes/metrics.md
  _layouts/email_report_metrics.html
Labels: cla-signed

#8255 BD-3571: Fix tab header
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/personalized_paths.md
Labels: cla-signed

#8256 Fix tab headings
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/content_cards/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/initial_sdk_setup/ios_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/roku/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/delayed_initialization.md
  _docs/_hidden/archive_docs/windows_universal/analytics/setting_custom_attributes.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
  _docs/_partners/message_orchestration/additional_channels/mobile_wallet/passkit.md
  _docs/_partners/message_personalization/dynamic_content/future_anthem.md
  _docs/_partners/message_personalization/dynamic_content/komo.md
  _docs/_user_guide/data_and_analytics/reporting/data_by_segments.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/10dlc.md
Labels: cla-signed

#8257 BD-3553 Add steps for disconnecting and reconnecting a Shopify catalog
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs.md
  assets/img/Shopify/catalog_toggle.png
  assets/img/Shopify/edit_config.png
Labels: cla-signed

#8222 October 2024 release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2024.md
  _docs/_help/release_notes/2024/10_15_24.md
Labels: cla-signed, Deploy, release notes

#8250 BD-3566 Add to Aborting Liquid Messages
  _docs/_user_guide/personalization_and_dynamic_content/liquid/aborting_messages.md
Labels: cla-signed

#8202 [Docs feedback] BD-3487: Clarify columns in CSV file for promotion codes
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
Labels: cla-signed

#8262 Remove email metrics duplicate table
  _includes/campaign_analytics.md
Labels: cla-signed

#8264 update config settings
  _config.yml
Labels: cla-signed

#8265 BD-3572 Move SMS note to a Consideratinos section in User Import
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Labels: cla-signed

#8149 Update connect_subdomain.md
  _docs/_user_guide/engagement_tools/landing_pages/connect_domain.md
  _docs/_user_guide/engagement_tools/landing_pages/connect_subdomain.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8267 [DI-6567] Make Currents the codeowners for Currents event docs
  .github/CODEOWNERS
Labels: cla-signed
