Repository braze-inc/braze-docs, pull requests merged in 2024-02, with the labels that each got.

#6821 Adding a loud clarification about AWS prerequisites
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
Labels: cla-signed

#6721 Partner: Scuba Analytics
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/analytics.md
  _docs/_partners/data_and_infrastructure_agility/analytics/scuba.md
  _docs/_partners/home.md
  assets/img/scuba/analytics/filter_attribute.png
  assets/img/scuba/analytics/operator_end.png
  assets/img/scuba/analytics/segment_name.png
  assets/img/scuba/analytics/select_property.png
Labels: cla-signed, Braze Partnerships

#6823 BD-2765: Add Currents tiles to Data Export, and add description option to `dev_guide` layout
  _docs/_user_guide/data_and_analytics/export_braze_data.md
  _layouts/dev_guide.html
Labels: cla-signed

#6825 Leftover deploy - February 1, 2024
  _docs/_developer_guide/platform_integration_guides/xamarin/initial_sdk_setup.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/analytics.md
  _docs/_partners/data_and_infrastructure_agility/analytics/scuba.md
  _docs/_partners/home.md
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
  _docs/_user_guide/data_and_analytics/export_braze_data.md
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
  _includes/archive/setting_user_ids/naming_convention.md
  _layouts/dev_guide.html
  assets/img/scuba/analytics/filter_attribute.png
  assets/img/scuba/analytics/operator_end.png
  assets/img/scuba/analytics/segment_name.png
  assets/img/scuba/analytics/select_property.png
Labels: Deploy

#6778 Updating Appsflyer deep linking section to be in parity with their docs
  _docs/_home/styling_test_page.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
Labels: status: in progress, cla-signed

#6811 Privacy manifest
  _docs/_developer_guide/platform_integration_guides/swift/ios_17.md
  _docs/_developer_guide/platform_integration_guides/swift/privacy_manifest.md
Labels: cla-signed

#6828 Leftover deploy pt 2 - February 2, 2024
  _docs/_developer_guide/platform_integration_guides/swift/ios_17.md
  _docs/_developer_guide/platform_integration_guides/swift/privacy_manifest.md
  _docs/_home/styling_test_page.md
  _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
Labels: cla-signed, Deploy

#6830 broken link
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/swift/ios_17.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
Labels: cla-signed

#6832 fcm banner warning
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/migrating_to_firebase_cloud_messaging.md
Labels: cla-signed

#6836 Leftover deploy pt 3 - February 5, 2024
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/migrating_to_firebase_cloud_messaging.md
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/swift/ios_17.md
  _docs/_developer_guide/platform_integration_guides/swift/privacy_manifest.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
Labels: cla-signed, Deploy

#6837 Update email_settings.md
  _docs/_user_guide/administrative/app_settings/email_settings.md
Labels: cla-signed

#6817 Add Team names to /details endpoints for Campaigns, Canvases and Segments. - Merge 2/6
  _docs/_api/endpoints/export/campaigns/get_campaign_details.md
  _docs/_api/endpoints/export/canvas/get_canvas_details.md
  _docs/_api/endpoints/export/segments/get_segment_details.md
Labels: cla-signed

#6809 BD-2776 Shopify updates
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/Shopify_Features/shopify_user_identity.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/setting_up_shopify.md
  assets/img/Shopify/collect_email.png
  assets/img/Shopify/collect_sms.png
  assets/img/Shopify/shop_app_store.png
  assets/img/Shopify/shop_setup_1.png
  assets/img/Shopify/shop_setup_4.png
  assets/img/Shopify/shop_setup_8.png
  assets/img/Shopify/shopify_app_install.png
  assets/img/Shopify/shopify_connected_store.png
  assets/img/Shopify/shopify_step_1.png
  assets/img/Shopify/shopify_step_2_events.png
  assets/img/Shopify/shopify_step_3_email.png
  assets/img/Shopify/shopify_step_4_catalog.png
  assets/img/Shopify/shopify_step_5_channels.png
Labels: cla-signed

#6840 Removed early access banner for email capture
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/email_capture.md
Labels: cla-signed

#6841 BD-2802 WhatsApp product update Feb 2024
  _docs/_user_guide/message_building_by_channel/whatsapp/meta_resources.md
Labels: cla-signed

#6843 BD-2795: Updates to Content Block duplicating and preview
  _docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md
  assets/img/preview_tab_content_block.png
Labels: cla-signed

#6845 Deploy - February 6, 2024
  _docs/_api/endpoints/export/campaigns/get_campaign_details.md
  _docs/_api/endpoints/export/canvas/get_canvas_details.md
  _docs/_api/endpoints/export/segments/get_segment_details.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2024.md
  _docs/_help/release_notes/2024/2_6_24.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/Shopify_Features/shopify_user_identity.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/setting_up_shopify.md
  _docs/_user_guide/administrative/app_settings/email_settings.md
  _docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md
  _docs/_user_guide/message_building_by_channel/email/email_setup/email_validation.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/email_capture.md
  _docs/_user_guide/message_building_by_channel/whatsapp/meta_resources.md
  assets/img/Shopify/collect_email.png
  assets/img/Shopify/collect_sms.png
  assets/img/Shopify/shop_app_store.png
  assets/img/Shopify/shop_setup_1.png
  assets/img/Shopify/shop_setup_4.png
  assets/img/Shopify/shop_setup_8.png
  assets/img/Shopify/shopify_app_install.png
  assets/img/Shopify/shopify_connected_store.png
  assets/img/Shopify/shopify_step_1.png
  assets/img/Shopify/shopify_step_2_events.png
  assets/img/Shopify/shopify_step_3_email.png
  assets/img/Shopify/shopify_step_4_catalog.png
  assets/img/Shopify/shopify_step_5_channels.png
  assets/img/preview_tab_content_block.png
Labels: cla-signed, Deploy

#6847 BD-2801: Email edits
  _docs/_user_guide/administrative/app_settings/email_settings.md
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
Labels: cla-signed

#6838 BD-2792: Hidden doc for list-unsubscribe updates
  _docs/_hidden/private_betas/list-unsubscribe_header.md
  _docs/_user_guide/administrative/app_settings/email_settings.md
  assets/img/email_settings/email_unsubscribe_header.png
  assets/img/email_settings/email_unsubscribe_header_custom.png
  assets/img/email_settings/target_audiences_example.png
  assets/img_archive/email_unsubscribe_header_old.png
Labels: cla-signed

#6846 BD-2800: Clarify user email subscription
  _docs/_user_guide/message_building_by_channel/email/best_practices/managing_email_subscriptions.md
Labels: cla-signed

#6831 Update message_extras.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
Labels: cla-signed

#6850 BD-2797 Edit user permissions
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
  assets/img/user_permissions_selection.png
Labels: cla-signed

#6852 BD-2788: Add example for selecting property name to AI item recs
  _docs/_user_guide/sage_ai/recommendations.md
Labels: cla-signed

#6827 BD-2785 Updating Custom Attributes - MERGE 2/8
  _docs/_user_guide/administrative/app_settings/company_settings/security_settings.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
Labels: cla-signed

#6856 BD-2805 Remove oauth image for shopify setup
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/setting_up_shopify.md
  assets/img/Shopify/shop_setup_1.png
Labels: cla-signed

#6860 KB audit: Segment membership filter
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#6861 KB audit: "Changing" to "Editing"
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/change_your_campaign_after_launch.md
Labels: cla-signed

#6858 Clarifications for campaign interaction data
  _docs/_hidden/private_betas/campaign_data_retention.md
Labels: cla-signed

#6862 KB audit: Changing custom attribute data types
  _docs/_help/help_articles/data/change_custom_data_type.md
Labels: cla-signed

#6863 Update braze looker action image
  assets/img/braze-looker-action.png
Labels: cla-signed

#6796 BD-2760 Revamp Custom Attributes - operators
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
Labels: status: in progress, cla-signed

#6868 Fix typo
  _docs/_api/endpoints/export/news_feed/get_news_feed_cards.md
Labels: cla-signed

#6869 AI Recs / LLM clarification
  _docs/_user_guide/sage_ai/recommendations.md
Labels: cla-signed

#6870 BD-2736 Update Segmentation filters
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
Labels: cla-signed

#6874 BD-2804: Provide more details on how to regenerate schema
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
Labels: cla-signed

#6875 Update shopify_user_identity.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/Shopify_Features/shopify_user_identity.md
Labels: cla-signed

#6877 fix learning search results
  assets/js/algolia_header_search.js
  assets/js/algolia_main_search.js
Labels: cla-signed

#6878 Update shopify_overview.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_overview.md
Labels: cla-signed

#6876 BD-2787 Add detail to re-evaluate campaign eligibility
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/create.md
Labels: cla-signed

#6872 BD-2615: New help article for resetting push permissions
  _docs/_help/help_articles/push.md
  _docs/_help/help_articles/push/resetting_push_permissions.md
Labels: cla-signed

#6826 BD-2778 Add email capture form to back-in-stock notifs
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/Shopify_Features/shopify_catalogs/back_in_stock.md
Labels: cla-signed

#6879 Update simondata.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/simondata.md
Labels: cla-signed

#6881 Replace Bre with Isaiah in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla-signed

#6882 BD-2821: Clarify push subscription state with multiple devices
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
Labels: cla-signed

#6884 Update create.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
Labels: cla-signed

#6880 BD-2708: Condense "Managing custom data" and "Custom event and attribute management" articles
  _docs/_user_guide/administrative/app_settings.md
  _docs/_user_guide/administrative/app_settings/custom_event_and_attribute_management.md
  _docs/_user_guide/data_and_analytics/custom_data/managing_custom_data.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/templates/simple_survey.md
  assets/img_archive/manageproperties1.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6885 BD-2798: Clarify users who are ubsubscribed
  _docs/_user_guide/message_building_by_channel/email/best_practices/managing_email_subscriptions.md
Labels: cla-signed

#6886 BD-2784: Add limitation for image blocks and button links
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
Labels: cla-signed

#6887 BD-2761: Add email as an identifier for event object
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_api/objects_filters/event_object.md
Labels: cla-signed

#6853 Update ruby and jekyll version
  .ruby-version
  Gemfile
  Gemfile.lock
Labels: cla-signed

#6890 Updating docs for Ruby 3.2.2 upgrade
  README.md
  _docs/_contributing/generating_a_preview.md
  _docs/_contributing/home.md
Labels: cla-signed

#6871 BD-2762: Update campaign interaction data to messaging interaction data - MERGE 2/14
  _docs/_hidden/private_betas/campaign_data_retention.md
  _docs/_hidden/private_betas/messaging_interaction_data.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6891 Update README.md
  README.md
Labels: cla-signed

#6893 Minor edits
  _docs/_user_guide/sage_ai/intelligence/faqs.md
Labels: cla-signed

#6851 Replaced Tealium links
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_for_currents.md
Labels: cla-signed

#6894 BD-2828 Update MMS messages size
  _docs/_user_guide/message_building_by_channel/sms/mms/about_mms.md
Labels: cla-signed

#6892 Deploy pt. 2 - February 14, 2024
  README.md
  _docs/_contributing/generating_a_preview.md
  _docs/_contributing/home.md
  _docs/_hidden/private_betas/campaign_data_retention.md
  _docs/_hidden/private_betas/messaging_interaction_data.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_for_currents.md
  _docs/_user_guide/message_building_by_channel/sms/mms/about_mms.md
  _docs/_user_guide/sage_ai/intelligence/faqs.md
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#6895 BD-2829: Add quotes around `CAMPAIGN_ID`
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/code_generation.md
Labels: cla-signed

#6898 BD-2826: Remove image from Azure AD
  _docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
Labels: cla-signed

#6899 BD-2823: Clarify push action buttons not support with quick push campaigns
  _docs/_hidden/private_betas/quick_push.md
  _docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_action_buttons.md
Labels: cla-signed

#6900 BD-2822: Add note that IAMs are not included in Send calendar
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/campaign_calendar.md
Labels: cla-signed

#6901 BD-2687: Add experiment path caveat
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
Labels: cla-signed

#6897 BD-2794 Release notes template
  _docs/_contributing/templates/release_notes.md
Labels: cla-signed

#6902 Update SMS FAQs - test sends
  _docs/_user_guide/message_building_by_channel/sms/faqs.md
Labels: cla-signed

#6903 Fixing vercel bot content in contributing docs
  _docs/_contributing/generating_a_preview.md
  _docs/_contributing/git_and_github.md
  _docs/_contributing/your_first_contribution.md
  assets/img/contributing/github/tag_docs_team_in_comment.png
Labels: cla-signed

#6904 BD-2834: One-click unsubscribe header
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2024/2_6_24.md
  _docs/_hidden/private_betas/list-unsubscribe_header.md
  _docs/_user_guide/administrative/app_settings/email_settings.md
Labels: cla-signed

#6865 BD-2817: Multi-page in-app messages EA [Merge 2/15]
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/style_settings.md
  assets/img_archive/dnd_iam_mockup.png
  assets/img_archive/dnd_iam_multipage.gif
  assets/js/broken_redirect_list.js
Labels: status: done, cla-signed

#6864 BD-2786 Update Performance by Segment
  _docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md
Labels: cla-signed

#6907 BD-2835 Update back-in-stock notifications item_id
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/Shopify_Features/shopify_catalogs/back_in_stock.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/back_in_stock_notifications.md
Labels: cla-signed

#6805 Add Cordova push integration instructions for iOS app extensions
  _docs/_developer_guide/platform_integration_guides/cordova/cordova_integration.md
  _docs/_developer_guide/platform_integration_guides/cordova/push_notifications.md
Labels: cla-signed

#6909 Leftover deploy - February 15, 2024
  _docs/_contributing/generating_a_preview.md
  _docs/_contributing/git_and_github.md
  _docs/_contributing/templates/release_notes.md
  _docs/_contributing/your_first_contribution.md
  _docs/_developer_guide/platform_integration_guides/cordova/cordova_integration.md
  _docs/_developer_guide/platform_integration_guides/cordova/push_notifications.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2024/2_6_24.md
  _docs/_hidden/private_betas/list-unsubscribe_header.md
  _docs/_hidden/private_betas/messaging_interaction_data.md
  _docs/_hidden/private_betas/quick_push.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/Shopify_Features/shopify_catalogs/back_in_stock.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/code_generation.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
  _docs/_user_guide/administrative/app_settings/email_settings.md
  _docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/campaign_calendar.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/style_settings.md
  _docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_action_buttons.md
  _docs/_user_guide/message_building_by_channel/sms/faqs.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/back_in_stock_notifications.md
  assets/img/contributing/github/tag_docs_team_in_comment.png
  assets/img_archive/dnd_iam_mockup.png
  assets/img_archive/dnd_iam_multipage.gif
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#6829 Rearrange & edit "Creating a Segment" sections
  _docs/_hidden/private_betas/updated_segment_experience.md
  assets/img_archive/segment_filter_stats.png
Labels: status: in progress, cla-signed

#6912 BD-2777: Clarify details for Canvas entry limit
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
Labels: cla-signed

#6914 Update create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
Labels: cla-signed

#6919 BD-2847: Update to SCIM Provisioning
  _docs/_user_guide/administrative/app_settings/company_settings/automated_user_provisioning.md
Labels: cla-signed

#6918 BD-2838: Fix broken link
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6906 BD-2830: Quick push GA [Merge 2/20]
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message/quick_push.md
  assets/img_archive/flowchart_quickpush.png
Labels: status: done, cla-signed

#6916 BD-2845 Update Liquid string filters
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
Labels: cla-signed

#6910 BD-2833: Update analytics in Personalized Paths
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/personalized_paths.md
  assets/img_archive/ab_analytics_pv_3.png
Labels: status: done, cla-signed

#6920 BD-2844: Clarify details for AMP email editor
  _docs/_user_guide/message_building_by_channel/email/amphtml.md
Labels: cla-signed

#6733 BD-2695 Add image specs to an includes file
  _docs/_user_guide/engagement_tools/templates_and_media.md
  _docs/_user_guide/engagement_tools/templates_and_media/image_specs.md
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/modal.md
  _docs/_user_guide/message_building_by_channel/push/android/rich_notifications.md
  _includes/image_specs.md
Labels: cla-signed

#6926 Deploy - February 20, 2024
  _docs/_hidden/private_betas/updated_segment_experience.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/Shopify_Features/shopify_catalogs/back_in_stock.md
  _docs/_user_guide/administrative/app_settings/company_settings/automated_user_provisioning.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/personalized_paths.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/templates_and_media.md
  _docs/_user_guide/engagement_tools/templates_and_media/image_specs.md
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
  _docs/_user_guide/message_building_by_channel/email/amphtml.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/modal.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _docs/_user_guide/message_building_by_channel/push/android/rich_notifications.md
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message/quick_push.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/back_in_stock_notifications.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
  _includes/image_specs.md
  assets/img_archive/ab_analytics_pv_3.png
  assets/img_archive/flowchart_quickpush.png
  assets/img_archive/segment_filter_stats.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#6822 Add manual integration bundle for SDWebImage
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/installation_methods/manual_integration.md
Labels: cla-signed

#6927 Update code_generation.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/code_generation.md
Labels: cla-signed

#6922 Update html_in-app_messages.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize/html_in-app_messages.md
Labels: cla-signed

#6931 BD-2864 Unhide email capture form
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/email_capture.md
Labels: cla-signed

#6932 Update issue templates
  .github/ISSUE_TEMPLATE/report_an_issue.md
  .github/ISSUE_TEMPLATE/request_a_feature.md
Labels: cla-signed

#6929 BD-2846: Update mass offer campaign example
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/punchh.md
  assets/img/punchh/usecase4.png
  assets/img/punchh/usecase5.png
  assets/img/punchh/usecase6.png
Labels: cla-signed

#6935 Update viralsweep.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/viralsweep.md
Labels: cla-signed

#6937 BD-2858 Link Custom Attributes inside Segmentation Filters
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#6905 BD-2807 Inherited phone numbers also inherit subscription states
  _docs/_user_guide/message_building_by_channel/sms/sms_subscription_group.md
Labels: cla-signed

#6933 Fixing issue #6928 | Curl Commands
  _docs/_help/help_articles/push/push_token_migration.md
Labels: cla-signed

#6942 BD-2859 Update Cross Referencing with HTML link
  _docs/_contributing/content_management/cross_referencing.md
Labels: cla-signed

#6943 BD-2855: Include email for user attributes object
  _docs/_api/objects_filters/user_attributes_object.md
Labels: cla-signed

#6946 Update purchase_object.md
  _docs/_api/objects_filters/purchase_object.md
Labels: cla-signed

#6945 Update event_object.md
  _docs/_api/objects_filters/event_object.md
Labels: cla-signed

#6944 BD-2862 Fix broken link for viewing PII
  _docs/_user_guide/administrative/app_settings/company_settings/security_settings.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6921 BD-2840: Migrating partner docs + templates cleanup
  README.md
  _docs/_contributing/content_management/pages.md
  _docs/_contributing/content_management/sections.md
  _docs/_contributing/generating_a_preview.md
  _docs/_contributing/git_and_github.md
  _docs/_contributing/style_guide.md
  _docs/_contributing/styling_examples.md
  _docs/_contributing/templates.md
  _docs/_contributing/templates/release_notes.md
  _docs/_contributing/troubleshooting.md
  _docs/_help/help_articles/docs/contribution.md
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
  _docs/_hidden/wip_partnerships/partnership_template.md
  _includes/contributing/templates/basic.md
  _includes/contributing/templates/release_notes.md
  _includes/contributing/templates/technology_partner.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6947 Add tone control
  _docs/_user_guide/sage_ai/generative_ai/ai_copywriting.md
Labels: cla-signed

#6948 Updating redirect + troubleshooting docs
  _docs/_contributing/content_management/redirecting_urls.md
  _docs/_contributing/troubleshooting.md
  _includes/contributing/alerts/warning_urls_must_be_lowercase.md
Labels: cla-signed

#6949 Leftover deploy - February 22, 2024
  .github/ISSUE_TEMPLATE/report_an_issue.md
  .github/ISSUE_TEMPLATE/request_a_feature.md
  Gemfile.lock
  README.md
  _docs/_api/objects_filters/event_object.md
  _docs/_api/objects_filters/purchase_object.md
  _docs/_api/objects_filters/user_attributes_object.md
  _docs/_contributing/content_management/cross_referencing.md
  _docs/_contributing/content_management/pages.md
  _docs/_contributing/content_management/redirecting_urls.md
  _docs/_contributing/content_management/sections.md
  _docs/_contributing/generating_a_preview.md
  _docs/_contributing/git_and_github.md
  _docs/_contributing/style_guide.md
  _docs/_contributing/styling_examples.md
  _docs/_contributing/templates.md
  _docs/_contributing/templates/release_notes.md
  _docs/_contributing/troubleshooting.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/installation_methods/manual_integration.md
  _docs/_help/help_articles/docs/contribution.md
  _docs/_help/help_articles/push/push_token_migration.md
  _docs/_hidden/private_betas/multiple_stores.md
  _docs/_hidden/wip_partnerships/WIP_guidelines.md
  _docs/_hidden/wip_partnerships/partnership_template.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/code_generation.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/punchh.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/viralsweep.md
  _docs/_user_guide/administrative/app_settings/company_settings/security_settings.md
  _docs/_user_guide/administrative/app_settings/email_settings.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/ab_test_projection.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/email_capture.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize/html_in-app_messages.md
  _docs/_user_guide/message_building_by_channel/sms/sms_subscription_group.md
  _docs/_user_guide/sage_ai/generative_ai/ai_copywriting.md
  _docs/_user_guide/sage_ai/recommendations.md
  _includes/contributing/alerts/warning_urls_must_be_lowercase.md
  _includes/contributing/templates/basic.md
  _includes/contributing/templates/release_notes.md
  _includes/contributing/templates/technology_partner.md
  assets/img/multiple_stores.png
  assets/img/punchh/usecase4.png
  assets/img/punchh/usecase5.png
  assets/img/punchh/usecase6.png
  assets/img/shopify_add_trigger.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#6950 Update create.md to reflect new page limit
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
Labels: cla-signed

#6951 BD-2861 Add Google Cloud Storage (GCS) exports documentation
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/google_cloud_storage_for_currents.md
  assets/img/gcs7.png
Labels: cla-signed

#6952 BD-2860: Update to Google Audience Sync details
  _docs/_partners/canvas_steps/google_audience_sync.md
Labels: cla-signed

#6958 Update screenshot for AI copywriting assistant
  _docs/_user_guide/sage_ai/generative_ai/ai_copywriting.md
  assets/img/ai_copywriter/gpt3.png
Labels: cla-signed

#6959 BD-2867: Clarify Global Control Group for exporting user data
  _docs/_api/endpoints/export/user_data/post_users_global_control_group.md
Labels: cla-signed

#6915 BD-2837 Add hidden Link Shortening page and updated post/send
  _docs/_hidden/private_betas/link_shortening.md
Labels: cla-signed

#6962 Leftover Deploy p2 - February 26, 2023
  _docs/_api/endpoints/export/user_data/post_users_global_control_group.md
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/migrating_to_firebase_cloud_messaging.md
  _docs/_hidden/private_betas/link_shortening.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/google_cloud_storage_for_currents.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _docs/_user_guide/sage_ai/generative_ai/ai_copywriting.md
  assets/img/ai_copywriter/gpt3.png
  assets/img/android/push_integration/migration/verify-sender-id/verify-sender-id-firebase.png
  assets/img/gcs7.png
Labels: cla-signed, Deploy

#6940 Message Archiving support for Azure and GCS. - to be merged February 28
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
Labels: status: on hold / do not merge, cla-signed

#6966 Make SQL Table Reference public
  _docs/_user_guide/engagement_tools/segments/sql_segments/sql_segments_tables.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6967 Deploy - February 27, 2024
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
  _docs/_user_guide/engagement_tools/segments/sql_segments/sql_segments_tables.md
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#6963 Remove reference to non-native SMS
  _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
Labels: cla-signed

#6971 Custom list-unsubscribe header - MERGE 2/29
  _docs/_hidden/private_betas/list-unsubscribe_header.md
  _docs/_user_guide/administrative/app_settings/email_settings.md
  assets/img/email_settings/one-click_unsubscribe_to_email_header.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6917 BD-2731: FY25 Pricing Hidden Links
  _docs/_hidden/pricing/message_credits_delta_a3sy.md
  _docs/_hidden/pricing/message_credits_gamma_0dhr.md
  _docs/_hidden/pricing/message_credits_sigma_pow2.md
  _docs/_hidden/pricing/message_credits_theta_d9kw.md
  assets/css/_content.scss
Labels: cla-signed

#6781 Update managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#6908 BD-2733: Building out the compliance doc portal
  _docs/_contributing/yaml_front_matter/page_layouts.md
  _docs/_docs_pages/index.md
  _docs/_hidden/compliance/home.md
  _docs/_hidden/compliance/sms_channel.md
  _docs/_hidden/compliance/whatsapp.md
  _docs/_user_guide/privacy_portal.md
Labels: cla-signed

#6975 BD-2874: Add details for maximum duration in Canvas
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
Labels: cla-signed

#6941 Update user_update.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
Labels: cla-signed

#6976 Leftover deploy - February 29, 2024
  _docs/_contributing/yaml_front_matter/page_layouts.md
  _docs/_docs_pages/index.md
  _docs/_hidden/compliance/home.md
  _docs/_hidden/compliance/sms_channel.md
  _docs/_hidden/compliance/whatsapp.md
  _docs/_hidden/pricing/message_credits_delta_a3sy.md
  _docs/_hidden/pricing/message_credits_gamma_0dhr.md
  _docs/_hidden/pricing/message_credits_sigma_pow2.md
  _docs/_hidden/pricing/message_credits_theta_d9kw.md
  _docs/_hidden/private_betas/list-unsubscribe_header.md
  _docs/_user_guide/administrative/app_settings/email_settings.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
  _docs/_user_guide/privacy_portal.md
  assets/css/_content.scss
  assets/img/email_settings/one-click_unsubscribe_to_email_header.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#6970 Update talonone.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/talonone.md
Labels: cla-signed

#6977 add cloudflare ip ranges
  _docs/_api/network_connectivity_issues.md
Labels: cla-signed
