Repository braze-inc/braze-docs, pull requests merged in 2024-12, with the labels that each got.

#8523 Fix typo in link shortening FAQ
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
Labels: cla-signed

#8532 BD-3713 Remove 24-hour period for filter
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#8531 BD-3717 Update Mobile Messages Services doc
  _docs/_hidden/compliance/home.md
  _docs/_hidden/compliance/sms_channel.md
Labels: cla-signed

#8423 BD-3664 Outgrow partner docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/leads_capture.md
  _docs/_partners/data_and_infrastructure_agility/leads_capture/outgrow.md
  _docs/_partners/home.md
Labels: cla-signed

#8536 File new_features.md committed.
  _lang/es/_user_guide/administrative/app_settings/api_settings_tab.md
  _lang/es/_user_guide/data_and_analytics/analytics/conversions_dashboard.md
  _lang/es/_user_guide/data_and_analytics/custom_data/custom_events.md
  _lang/es/_user_guide/data_and_analytics/ideas_and_strategies/b2b_data_models.md
  _lang/es/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
  _lang/es/_user_guide/engagement_tools/campaigns/managing_campaigns/archiving_campaigns.md
  _lang/es/_user_guide/engagement_tools/canvas/get_started/braze_templates/lapsed_user.md
  _lang/es/_user_guide/message_building_by_channel/content_cards/create.md
  _lang/es/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _lang/es/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md
  _lang/es/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
  _lang/es/_user_guide/message_building_by_channel/sms/mms/create.md
Labels: cla-signed

#8534 BD-3679 Update Facebook Audience Export screenshot
  _docs/_partners/message_orchestration/additional_channels/retargeting/facebook.md
  assets/img/fb/afb_6.png
Labels: cla-signed

#8530 BD-3702 Add Contentful partner docs
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content.md
  _docs/_partners/message_personalization/dynamic_content/contentful.md
Labels: cla-signed

#8538 BD-3712 Update message engagement event abort type
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#8539 Minor edits to SEEN partner doc
  _docs/_partners/message_personalization/dynamic_content/seen.md
Labels: cla-signed

#8501 Correct release notes regarding rate limit
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2024/9_17_24.md
  _lang/es/_help/release_notes.md
  _lang/es/_help/release_notes/2024/9_17_24.md
  _lang/fr_fr/_help/release_notes/2024/9_17_24.md
  _lang/ja/_help/release_notes.md
  _lang/ja/_help/release_notes/2024/9_17_24.md
  _lang/ko/_help/release_notes.md
  _lang/ko/_help/release_notes/2024/9_17_24.md
Labels: cla-signed

#8533 BD-3678 Update nested object filter
  _docs/_user_guide/data_and_analytics/custom_data/custom_events/nested_objects.md
Labels: cla-signed

#8401 BD-3651 Add promo code faq
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
Labels: cla-signed

#8550 ADA Compliance Dec 2024
  _docs/_api/basics.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/integration.md
  _docs/_user_guide/brazeai/predictive_suite/predictive_events.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/conditional_logic.md
Labels: cla-signed

#8520 Converting news feed alerts to an include
  _docs/_api/basics.md
  _docs/_api/endpoints/export/news_feed/get_news_feed_card_analytics.md
  _docs/_api/endpoints/export/news_feed/get_news_feed_card_details.md
  _docs/_api/endpoints/export/news_feed/get_news_feed_cards.md
  _docs/_api/identifier_types.md
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/categories.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/customization/badges.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/customization/click_listener.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/customization/custom_styling.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/customization/gifs.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/customization/key_value_pairs.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/customization/read_and_unread.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/integration.md
  _docs/_developer_guide/platform_integration_guides/android/news_feed/refreshing_the_feed.md
  _docs/_developer_guide/platform_integration_guides/cordova/other_integrations.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/news_feed/customization/badges.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/news_feed/customization/custom_styling.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/news_feed/defining_a_news_feed_category.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/news_feed/integration.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/news_feed/refreshing_the_news_feed.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/tvos/news_feed.md
  _docs/_developer_guide/platform_integration_guides/unity/news_feed.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/customization/badges.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/customization/custom_styling.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/customization/key_value_pairs.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/customization/read_and_unread.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/defining_a_news_feed_category.md
  _docs/_developer_guide/platform_integration_guides/web/news_feed/integration.md
  _docs/_developer_guide/platform_integration_guides/xamarin/news_feed.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_news_feed_data.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md
  _docs/_user_guide/engagement_tools/news_feed/best_practices.md
  _docs/_user_guide/engagement_tools/news_feed/creating_a_news_feed_item.md
  _docs/_user_guide/engagement_tools/news_feed/news_feed_analytics_and_retargeting_data.md
  _docs/_user_guide/engagement_tools/news_feed/news_feed_categories.md
  _docs/_user_guide/engagement_tools/news_feed/news_feed_use_cases.md
  _includes/deprecations/braze_sdk/news_feed.md
Labels: cla-signed

#8551 [DI-6829] Correct field transformation documentation
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
Labels: cla-signed

#8555 Update branch_for_deeplinking.md
  _docs/_partners/message_orchestration/attribution/branch/branch_for_deeplinking.md
Labels: cla-signed

#8554 [BD-3687] Remove mention of 'automatic tracking'
  _docs/_user_guide/getting_started/users_segments.md
Labels: cla-signed

#8556 [BD-3303] Clarify CDN directives for Web SDK
  _docs/_developer_guide/platform_integration_guides/web/content_security_policy.md
Labels: cla-signed

#8559 BD-3730 Fix steps TOC in LINE setup
  _docs/_user_guide/message_building_by_channel/line/line_setup.md
  assets/img/contentcard_test.png
  assets/img/email_settings/email_unsub_header_workspaces.png
  assets/img/email_settings/email_unsubscribe_header_custom.png
  assets/img/email_settings/target_audiences_example.png
Labels: cla-signed

#8563 File push_notifications.md committed.
  _lang/ko/_developer_guide/debugging.md
  _lang/ko/_developer_guide/feature_flags/create.md
  _lang/ko/_developer_guide/platform_integration_guides/android/advanced_use_cases/adding_braze_js_interface.md
  _lang/ko/_developer_guide/platform_integration_guides/android/advanced_use_cases/android_google_tag_manager.md
  _lang/ko/_developer_guide/platform_integration_guides/android/content_cards/integration.md
  _lang/ko/_developer_guide/platform_integration_guides/android/in-app_messaging/customization/custom_styling.md
  _lang/ko/_developer_guide/platform_integration_guides/android/news_feed/integration.md
  _lang/ko/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _lang/ko/_developer_guide/platform_integration_guides/android/sample_apps.md
  _lang/ko/_developer_guide/platform_integration_guides/legacy_sdks/ios/advanced_use_cases/google_tag_manager.md
  _lang/ko/_developer_guide/platform_integration_guides/legacy_sdks/ios/content_cards/refreshing_the_feed.md
  _lang/ko/_developer_guide/platform_integration_guides/legacy_sdks/ios/in-app_messaging/implementation_guide/shareplay.md
  _lang/ko/_developer_guide/platform_integration_guides/legacy_sdks/ios/initial_sdk_setup/completing_integration.md
  _lang/ko/_developer_guide/platform_integration_guides/legacy_sdks/tvos/initial_sdk_setup.md
  _lang/ko/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _lang/ko/_developer_guide/platform_integration_guides/swift/live_activities/live_activities.md
  _lang/ko/_developer_guide/platform_integration_guides/swift/push_notifications/integration.md
  _lang/ko/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _lang/ko/_developer_guide/platform_wide/banner_cards/integration.md
Labels: cla-signed

#8567 BD-3725 Clarify last received filters
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/retargeting_campaigns.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#8575 BD-3675: Add context to push reporting about sends and unique recipients
  _includes/campaign_analytics.md
Labels: cla-signed

#8553 Add info about Canvas and campaign for Smartling partner doc
  _docs/_partners/message_personalization/localization/smartling.md
Labels: cla-signed

#8566 Add ko to dropdown
  _includes/header.html
Labels: cla-signed

#8578 File content_cards.md committed.
  _lang/fr_fr/_developer_guide/platform_integration_guides/cordova/content_cards.md
  _lang/fr_fr/_developer_guide/platform_integration_guides/cordova/initial_setup/customizations.md
  _lang/fr_fr/_developer_guide/platform_integration_guides/cordova/other_integrations.md
  _lang/fr_fr/_developer_guide/platform_integration_guides/cordova/push_notifications.md
Labels: cla-signed

#8571 File get_list_user_subscription_group_status.md committed.
  _lang/fr_fr/_api/endpoints/catalogs/catalog_items/synchronous/delete_catalog_item.md
  _lang/fr_fr/_api/endpoints/catalogs/catalog_items/synchronous/get_catalog_item_details.md
  _lang/fr_fr/_api/endpoints/catalogs/catalog_items/synchronous/put_update_catalog_item.md
  _lang/fr_fr/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md
  _lang/fr_fr/_api/endpoints/email/post_remove_hard_bounces.md
  _lang/fr_fr/_api/endpoints/export/campaigns/get_campaign_analytics.md
  _lang/fr_fr/_api/endpoints/export/campaigns/get_send_analytics.md
  _lang/fr_fr/_api/endpoints/export/canvas/get_canvas_analytics_summary.md
  _lang/fr_fr/_api/endpoints/export/canvas/get_canvas_details.md
  _lang/fr_fr/_api/endpoints/export/custom_events/get_custom_events_analytics.md
  _lang/fr_fr/_api/endpoints/export/kpi/get_kpi_daily_new_users_date.md
  _lang/fr_fr/_api/endpoints/export/kpi/get_kpi_dau_date.md
  _lang/fr_fr/_api/endpoints/export/kpi/get_kpi_uninstalls_date.md
  _lang/fr_fr/_api/endpoints/export/news_feed/get_news_feed_card_analytics.md
  _lang/fr_fr/_api/endpoints/export/news_feed/get_news_feed_card_details.md
  _lang/fr_fr/_api/endpoints/export/news_feed/get_news_feed_cards.md
  _lang/fr_fr/_api/endpoints/export/segments/get_segment_details.md
  _lang/fr_fr/_api/endpoints/export/sessions/get_sessions_analytics.md
  _lang/fr_fr/_api/endpoints/messaging/live_activity/start.md
  _lang/fr_fr/_api/endpoints/messaging/schedule_messages/get_messages_scheduled.md
  _lang/fr_fr/_api/endpoints/messaging/schedule_messages/post_delete_scheduled_triggered_canvases.md
  _lang/fr_fr/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_campaigns.md
  _lang/fr_fr/_api/endpoints/messaging/schedule_messages/post_update_scheduled_messages.md
  _lang/fr_fr/_api/endpoints/messaging/schedule_messages/post_update_scheduled_triggered_canvases.md
  _lang/fr_fr/_api/endpoints/messaging/send_messages/post_create_send_ids.md
  _lang/fr_fr/_api/endpoints/preference_center/get_view_details_preference_center.md
  _lang/fr_fr/_api/endpoints/sms/post_remove_invalid_numbers.md
  _lang/fr_fr/_api/endpoints/subscription_groups/get_list_user_subscription_groups.md
  _lang/fr_fr/_api/endpoints/templates/content_blocks_templates/post_update_content_block.md
  _lang/fr_fr/_api/endpoints/user_data/external_id_migration/post_external_ids_rename.md
  _lang/fr_fr/_api/objects_filters/messaging/sms_object.md
  _lang/fr_fr/_api/objects_filters/purchase_object.md
Labels: cla-signed

#8570 File get_list_user_subscription_group_status.md committed.
  _lang/pt_br/_api/endpoints/catalogs/catalog_fields/asynchronous/delete_catalog_field.md
  _lang/pt_br/_api/endpoints/catalogs/catalog_fields/asynchronous/post_create_catalog_fields.md
  _lang/pt_br/_api/endpoints/catalogs/catalog_items/asynchronous/patch_catalog_items_bulk.md
  _lang/pt_br/_api/endpoints/catalogs/catalog_items/asynchronous/put_update_catalog_items.md
  _lang/pt_br/_api/endpoints/catalogs/catalog_items/synchronous/delete_catalog_item.md
  _lang/pt_br/_api/endpoints/catalogs/catalog_items/synchronous/get_catalog_item_details.md
  _lang/pt_br/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md
  _lang/pt_br/_api/endpoints/catalogs/catalog_items/synchronous/put_update_catalog_item.md
  _lang/pt_br/_api/endpoints/catalogs/catalog_management/synchronous/delete_catalog.md
  _lang/pt_br/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md
  _lang/pt_br/_api/endpoints/catalogs/catalog_selections/asynchronous/delete_catalog_selection.md
  _lang/pt_br/_api/endpoints/catalogs/catalog_selections/asynchronous/post_create_catalog_selections.md
  _lang/pt_br/_api/endpoints/cdi/post_job_sync.md
  _lang/pt_br/_api/endpoints/email/post_remove_hard_bounces.md
  _lang/pt_br/_api/endpoints/export/campaigns/get_campaign_analytics.md
  _lang/pt_br/_api/endpoints/export/campaigns/get_campaign_details.md
  _lang/pt_br/_api/endpoints/export/campaigns/get_campaigns.md
  _lang/pt_br/_api/endpoints/export/campaigns/get_send_analytics.md
  _lang/pt_br/_api/endpoints/export/canvas/get_canvas_analytics_summary.md
  _lang/pt_br/_api/endpoints/export/canvas/get_canvas_details.md
  _lang/pt_br/_api/endpoints/export/canvas/get_canvases.md
  _lang/pt_br/_api/endpoints/export/custom_attributes/get_custom_attributes.md
  _lang/pt_br/_api/endpoints/export/custom_events/get_custom_events.md
  _lang/pt_br/_api/endpoints/export/custom_events/get_custom_events_analytics.md
  _lang/pt_br/_api/endpoints/export/custom_events/get_custom_events_data.md
  _lang/pt_br/_api/endpoints/export/kpi/get_kpi_daily_new_users_date.md
  _lang/pt_br/_api/endpoints/export/kpi/get_kpi_dau_date.md
  _lang/pt_br/_api/endpoints/export/kpi/get_kpi_uninstalls_date.md
  _lang/pt_br/_api/endpoints/export/news_feed/get_news_feed_card_details.md
  _lang/pt_br/_api/endpoints/export/news_feed/get_news_feed_cards.md
  _lang/pt_br/_api/endpoints/export/purchases/get_number_of_purchases.md
  _lang/pt_br/_api/endpoints/export/purchases/get_revenue_series.md
  _lang/pt_br/_api/endpoints/export/segments/get_segment.md
  _lang/pt_br/_api/endpoints/export/segments/get_segment_details.md
  _lang/pt_br/_api/endpoints/export/sessions/get_sessions_analytics.md
  _lang/pt_br/_api/endpoints/export/user_data/post_users_segment.md
  _lang/pt_br/_api/endpoints/messaging/live_activity/start.md
  _lang/pt_br/_api/endpoints/messaging/schedule_messages/get_messages_scheduled.md
  _lang/pt_br/_api/endpoints/messaging/send_messages/post_create_send_ids.md
  _lang/pt_br/_api/endpoints/preference_center/get_view_details_preference_center.md
  _lang/pt_br/_api/endpoints/sms/post_remove_invalid_numbers.md
  _lang/pt_br/_api/endpoints/subscription_groups/get_list_user_subscription_groups.md
  _lang/pt_br/_api/endpoints/templates/content_blocks_templates/post_update_content_block.md
  _lang/pt_br/_api/endpoints/templates/email_templates/post_update_email_template.md
  _lang/pt_br/_api/endpoints/user_data/external_id_migration/post_external_ids_rename.md
  _lang/pt_br/_api/objects_filters/messaging/sms_object.md
  _lang/pt_br/_api/objects_filters/purchase_object.md
Labels: cla-signed

#8569 File get_kpi_dau_date.md committed.
  _lang/es/_api/endpoints/catalogs/catalog_fields/asynchronous/delete_catalog_field.md
  _lang/es/_api/endpoints/catalogs/catalog_fields/asynchronous/post_create_catalog_fields.md
  _lang/es/_api/endpoints/catalogs/catalog_items/asynchronous/patch_catalog_items_bulk.md
  _lang/es/_api/endpoints/catalogs/catalog_items/asynchronous/put_update_catalog_items.md
  _lang/es/_api/endpoints/catalogs/catalog_items/synchronous/delete_catalog_item.md
  _lang/es/_api/endpoints/catalogs/catalog_items/synchronous/get_catalog_item_details.md
  _lang/es/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md
  _lang/es/_api/endpoints/catalogs/catalog_items/synchronous/put_update_catalog_item.md
  _lang/es/_api/endpoints/catalogs/catalog_management/synchronous/delete_catalog.md
  _lang/es/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md
  _lang/es/_api/endpoints/catalogs/catalog_selections/asynchronous/delete_catalog_selection.md
  _lang/es/_api/endpoints/catalogs/catalog_selections/asynchronous/post_create_catalog_selections.md
  _lang/es/_api/endpoints/cdi/get_integration_list.md
  _lang/es/_api/endpoints/cdi/get_job_sync_status.md
  _lang/es/_api/endpoints/cdi/post_job_sync.md
  _lang/es/_api/endpoints/email/get_list_hard_bounces.md
  _lang/es/_api/endpoints/email/get_query_by_email_or_phone.md
  _lang/es/_api/endpoints/email/get_query_unsubscribed_email_addresses.md
  _lang/es/_api/endpoints/email/post_remove_hard_bounces.md
  _lang/es/_api/endpoints/export/campaigns/get_campaign_analytics.md
  _lang/es/_api/endpoints/export/campaigns/get_send_analytics.md
  _lang/es/_api/endpoints/export/canvas/get_canvas_analytics_summary.md
  _lang/es/_api/endpoints/export/canvas/get_canvas_details.md
  _lang/es/_api/endpoints/export/custom_events/get_custom_events_analytics.md
  _lang/es/_api/endpoints/export/kpi/get_kpi_daily_new_users_date.md
  _lang/es/_api/endpoints/export/kpi/get_kpi_dau_date.md
  _lang/es/_api/endpoints/export/kpi/get_kpi_uninstalls_date.md
  _lang/es/_api/endpoints/export/news_feed/get_news_feed_card_analytics.md
  _lang/es/_api/endpoints/export/news_feed/get_news_feed_card_details.md
  _lang/es/_api/endpoints/export/news_feed/get_news_feed_cards.md
  _lang/es/_api/endpoints/export/purchases/get_number_of_purchases.md
  _lang/es/_api/endpoints/export/purchases/get_revenue_series.md
  _lang/es/_api/endpoints/export/segments/get_segment_details.md
  _lang/es/_api/endpoints/export/sessions/get_sessions_analytics.md
  _lang/es/_api/endpoints/messaging/live_activity/start.md
  _lang/es/_api/endpoints/messaging/schedule_messages/get_messages_scheduled.md
  _lang/es/_api/endpoints/messaging/send_messages/post_create_send_ids.md
  _lang/es/_api/endpoints/preference_center/get_view_details_preference_center.md
  _lang/es/_api/endpoints/sms/post_remove_invalid_numbers.md
  _lang/es/_api/endpoints/subscription_groups/get_list_user_subscription_groups.md
  _lang/es/_api/endpoints/templates/content_blocks_templates/get_list_email_content_blocks.md
  _lang/es/_api/endpoints/templates/content_blocks_templates/get_see_email_content_blocks_information.md
  _lang/es/_api/endpoints/templates/content_blocks_templates/post_create_email_content_block.md
  _lang/es/_api/endpoints/templates/content_blocks_templates/post_update_content_block.md
  _lang/es/_api/endpoints/user_data/external_id_migration/post_external_ids_rename.md
  _lang/es/_api/objects_filters/messaging/sms_object.md
  _lang/es/_api/objects_filters/purchase_object.md
Labels: cla-signed

#8577 BD-3677: Add troubleshooting for few or no direct opens for iOS push
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/push_notifications/troubleshooting.md
Labels: cla-signed

#8562 [Currents] Remove claim about dynamic allow listing from Currents documentation - PQ-6789
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
Labels: cla-signed

#8581 File use_cases.md committed.
  _lang/fr/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _lang/fr/_partners/message_personalization/location/foursquare.md
Labels: cla-signed

#8565 Update survicate.md
  _docs/_partners/message_orchestration/channel_extensions/surveys/survicate.md
  assets/img/survicate/image1.png
  assets/img/survicate/survicate_asset_2.png
  assets/img/survicate/survicate_asset_3.png
Labels: cla-signed

#8583 BD-3740 Apply Diataxis template to Currents
  _docs/_user_guide/data_and_analytics/braze_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/available_partners.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/how_braze_uses_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/s3_to_snowflake.md
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/transferring_data_to_redshift.md
  _includes/updating_currents.md
Labels: cla-signed

#8585 BD-3718 Update Amplitude Audiences to define 'user ids'
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_audiences.md
Labels: cla-signed

#8586 Fix broken nav header that links to a use case
  _docs/_user_guide/message_building_by_channel/webhooks/lead_scoring.md
Labels: cla-signed

#8584 BD-3742 Update Shopify event property
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/using_shopify/shopify_data_in_braze.md
Labels: cla-signed

#8590 BD-3724 Update links on Developer Getting Started page
  _docs/_developer_guide/getting_started.md
Labels: cla-signed

#8592 File content_cards.md committed.
  _lang/pt_br/_developer_guide/platform_integration_guides/cordova/content_cards.md
Labels: cla-signed

#8594 File analytics.md committed.
  _lang/pt_br/_developer_guide/platform_integration_guides/cordova/analytics.md
Labels: cla-signed

#8596 File customizations.md committed.
  _lang/pt_br/_developer_guide/platform_integration_guides/cordova/initial_setup/customizations.md
  _lang/pt_br/_developer_guide/platform_integration_guides/cordova/other_integrations.md
  _lang/pt_br/_developer_guide/platform_integration_guides/cordova/push_notifications.md
Labels: cla-signed

#8582 BD-3676: Add troubleshooting for push clicks unexpectedly opening in app
  _docs/_help/help_articles/push.md
  _docs/_help/help_articles/push/push_clicks_unexpectedly_open_in_app.md
  assets/img/push_on_click.png
Labels: cla-signed

#8598 BD-3737: Remove inaccurate sentence about price drop and BIS
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/price_drop_notifications.md
Labels: cla-signed

#8595 Remove space in site.baseurl
  _docs/_user_guide/getting_started/b2b_use_cases/account_based_segmentation.md
Labels: cla-signed

#8593 Minor grammatical edits
  _docs/_user_guide/engagement_tools/locations_and_geofences/location_tracking.md
Labels: cla-signed

#8548 BD-3719 Landing page edits
  _docs/_user_guide/engagement_tools/landing_pages/data_tracking.md
  _docs/_user_guide/engagement_tools/landing_pages/drag_and_drop.md
Labels: cla-signed

#8597 December 10, 2024 release notes
  _docs/_help/home.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2024.md
  _docs/_help/release_notes/2024/12_10_24.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8541 CO-3068: update catalogs settings docs for price drop and back in stock
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/back_in_stock_notifications.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/price_drop_notifications.md
  assets/img/back_in_stock_settings.png
  assets/img/catalog_settings_drawer.png
  assets/img/price_drop_notifications.png
Labels: cla-signed

#8471 Support_contact.md new translation
  _lang/ja/_hidden/other/support_contact.md
Labels: cla-signed

#8600 File zendesk_chat.md committed.
  _lang/fr_fr/_partners/message_orchestration/additional_channels/instant_chat/zendesk_chat.md
  _lang/fr_fr/_partners/message_orchestration/channel_extensions/ecommerce/olo.md
Labels: cla-signed

#8604 Hotfix: Cleaning up feature flags + banner cards
  _docs/_developer_guide/banner_cards.md
  _docs/_developer_guide/banner_cards/creating_placements.md
  _docs/_developer_guide/banner_cards/integration.md
  _docs/_developer_guide/feature_flags.md
  _docs/_developer_guide/feature_flags/about.md
  _docs/_developer_guide/home.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8576 Add use_webview attribute for Android and Apple push objects
  _docs/_api/objects_filters/messaging/android_object.md
  _docs/_api/objects_filters/messaging/apple_object.md
Labels: cla-signed

#8602 BD-3686 Edit value for IAM message events
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#8591 BD-3743 Update mobile messages documentation
  _docs/_hidden/compliance/sms_channel.md
Labels: cla-signed

#8609 Add braze docs for microsoft fabric (EA on 12/12)
  _docs/_user_guide/data_and_analytics/cloud_ingestion.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
  assets/img/cloud_ingestion/fabric_1.png
  assets/img/cloud_ingestion/fabric_setup_1.png
  assets/img/cloud_ingestion/fabric_setup_2.png
  assets/img/cloud_ingestion/fabric_setup_3.png
  assets/img/cloud_ingestion/fabric_setup_4.png
Labels: cla-signed

#8612 BD-3761: Update redirect and add alt text
  _docs/_user_guide/message_building_by_channel/email/preference_center/dnd_preference_center.md
Labels: cla-signed

#8613 BD-3763: Add supported data types for custom data deletion
  _docs/_user_guide/data_and_analytics/custom_data/managing_custom_data.md
Labels: cla-signed

#8615 Update broken_redirect_list.js
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8616 Leftover Deploy Pt. 1 - December 11, 2024
  _docs/_developer_guide/banner_cards/integration.md
  _docs/_hidden/compliance/sms_channel.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/teams.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
  _docs/_user_guide/data_and_analytics/custom_data/managing_custom_data.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/dnd_preference_center.md
  assets/img/cloud_ingestion/fabric_1.png
  assets/img/cloud_ingestion/fabric_setup_1.png
  assets/img/cloud_ingestion/fabric_setup_2.png
  assets/img/cloud_ingestion/fabric_setup_3.png
  assets/img/cloud_ingestion/fabric_setup_4.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#8614 Fix bounce rate calculation
  _docs/_user_guide/data_and_analytics/report_metrics.md
Labels: cla-signed

#8617 [MOPS-3235] Add documentation around unhealthy host detection
  _docs/_help/help_articles/api/webhook_connected_content_errors.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
Labels: cla-signed

#8619 BD-3766 Fix broken redirect link
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8580 BD-3714 Add details to Deleting Braze users
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/adding_users_to_your_dashboard.md
Labels: cla-signed

#8579 Odicci partner's docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/odicci.md
  _docs/_partners/home.md
  assets/img/odicci/braze_connect.png
  assets/img/odicci/braze_endpoint.png
  assets/img/odicci/braze_field_mapping.png
Labels: cla-signed

#8620 fix ko header
  _lang/_config_ko.yml
Labels: cla-signed

#8622 File adjust.md committed.
  _lang/ja/_partners/message_orchestration/attribution/adjust.md
Labels: cla-signed

#8608 BD-3744 Generalize mobile push page
  _docs/_developer_guide/platform_integration_guides/web/push_notifications/mobile_push.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8627 BD-3768 Add WhatsApp to Intelligent Channel filter
  _docs/_user_guide/brazeai/intelligence/intelligent_channel.md
  assets/img/intelligent_channel_filter.png
  assets/img/intelligent_example.png
Labels: cla-signed

#8628 Hotfix: Moving Odicci docs to diff section
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content.md
  _docs/_partners/message_personalization/dynamic_content/odicci.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8624 Remove incorrect sentence for Google Audience Sync
  _docs/_partners/canvas_steps/google_audience_sync.md
Labels: cla-signed

#8630 Update notify.md
  _docs/_partners/message_personalization/dynamic_content/notify.md
Labels: cla-signed

#8629 Feedback
  _docs/_partners/data_and_infrastructure_agility/ab_testing/optimizely.md
Labels: cla-signed

#8588 Various improvements to the React Native SDK integration docs
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/react_native/sample_app.md
  _docs/_developer_guide/platform_integration_guides/react_native/sdk_integration.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8631 Add portuguese brazil and use full word for dropdown.
  _includes/header.html
Labels: cla-signed

#8634 BD-3738: Fix incorrect senetence for back-in-stock notifications
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/back_in_stock_notifications.md
Labels: cla-signed

#8635 BD-3691: Add GCS and Azure credential errors included in AWS setting
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
Labels: cla-signed

#8636 BD-3691: Add GCS and Azure credential errors included in AWS setting pt. 2
  _docs/_user_guide/administrative/app_settings/company_settings/notification_preferences.md
Labels: cla-signed

#8638 Broken link audit - December 2024
  _docs/_developer_guide/content_cards.md
  _docs/_developer_guide/content_cards/creating_custom_content_cards.md
  _docs/_developer_guide/content_cards/customizing_behavior.md
  _docs/_developer_guide/content_cards/customizing_feed.md
  _docs/_developer_guide/content_cards/customizing_styles.md
  _docs/_developer_guide/feature_flags/create.md
  _docs/_developer_guide/getting_started/integration_overview.md
  _docs/_developer_guide/getting_started/platform_overview.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/sdk_changelogs.md
  _docs/_hidden/archived_layouts/overview.md
  _docs/_hidden/redirects/sdk_changelogs.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/custom_data/managing_custom_data.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/reeligibility.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/campaign_connector.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/time_based_campaign.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
  _docs/_user_guide/getting_started/terms_to_know.md
  _docs/_user_guide/message_building_by_channel/content_cards/creative_details.md
  _docs/_user_guide/message_building_by_channel/push/android/rich_notifications.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8640 migrated the changes from abelfort:patch-1 to a new branch
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/actioniq.md
Labels: cla-signed, Braze Partnerships

#8637 BD-3734: Add example response for /subscription/user/status
  _docs/_api/endpoints/subscription_groups/get_list_user_subscription_groups.md
Labels: cla-signed

#8626 BD-3767 Add Optimizely partner docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/ab_testing.md
  _docs/_partners/data_and_infrastructure_agility/ab_testing/optimizely.md
  assets/img/optimizely/image1_authorization.png
  assets/img/optimizely/image2_syncsegment.png
  assets/img/optimizely/image3_emailmapfield.png
  assets/img/optimizely/image4_mapfields.png
  assets/img/optimizely/image5_deletephonefield.png
  assets/img/optimizely/image6_segment.png
  assets/img/optimizely/image7_trigger.png
Labels: cla-signed

#8611 BD-3758 Revert changes for send_id field
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _lang/es/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _lang/fr_fr/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _lang/ja/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _lang/ko/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _lang/pt_br/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#8633 Jetpack Compose NavHost instructions
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md
Labels: cla-signed

#8643 BD-3747 Add Close Message metric
  _docs/_user_guide/data_and_analytics/report_metrics.md
  _includes/campaign_analytics.md
  _includes/metrics.md
Labels: cla-signed

#8603 BD-3652: Edits to Facebook Audience Sync article
  _docs/_partners/canvas_steps/facebook_audience_sync.md
  assets/img/fb_audience_sync/ad_account_permission.png
  assets/img/fb_audience_sync/ads_manager_accouint_overview.png
  assets/img/fb_audience_sync/confirm_accept_tos.png
  assets/img/fb_audience_sync/confirm_tasks.png
  assets/img/fb_audience_sync/fb_businessid_url.png
  assets/img/fb_audience_sync/resolve_alerts.png
Labels: cla-signed

#8642 BD-3772 Update phone number formats
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/user_phone_numbers.md
Labels: cla-signed

#8645 Update card_creation.md
  _docs/_user_guide/message_building_by_channel/content_cards/create/card_creation.md
Labels: cla-signed

#8653 auto expand current nav if possible
  _plugins/urlnavmenu_generator.rb
Labels: cla-signed

#8654 BD-3784 Update event property segmentation filter
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  assets/img/nested_object3.png
Labels: cla-signed

#8658 BD-3781 Update Unique Opens suggested rate
  _includes/campaign_analytics.md
Labels: cla-signed

#8656 Minor tweak to burst limits
  _docs/_api/endpoints/user_data/post_user_track.md
Labels: cla-signed

#8659 Update broken_redirect_list.js
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8662 Leftover deploy - December 19, 2024
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/message_building_by_channel/content_cards/create/card_creation.md
  _docs/_user_guide/message_building_by_channel/sms/phone_numbers/user_phone_numbers.md
  _includes/campaign_analytics.md
  _plugins/urlnavmenu_generator.rb
  assets/img/nested_object3.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#8650 File message_usage.md committed.
  _lang/pt_br/_includes/message_usage.md
Labels: cla-signed

#8648 File message_usage.md committed.
  _lang/ja/_includes/message_usage.md
Labels: cla-signed

#8647 File message_usage.md committed.
  _lang/fr_fr/_includes/message_usage.md
Labels: cla-signed

#8607 Update faq.md
  _docs/_developer_guide/feature_flags/faq.md
Labels: cla-signed

#8664 [DLK-2310] add ip address for au01 for CDI
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
Labels: cla-signed

#8641 BD-3769 Add Content Block width tool
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
  assets/img_archive/content_block_width.png
  assets/img_archive/dnd_content_block_composer.png
Labels: cla-signed

#8665 BD-3715 No entry or exit events for split steps
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#8668 Add other langs to rake commands
  README.md
  _docs/_contributing/generating_a_preview.md
Labels: cla-signed

#8660 normalize tab names better
  _plugins/tabs.rb
Labels: cla-signed

#8669 Making OneTrust's privacy banner right-aligned
  _includes/header.html
Labels: cla-signed

#8652 bdocs: improvements + script for updating old links
  .gitignore
  _docs/_contributing/bdocs.md
  bdocs
  scripts/create_release_text.sh
  scripts/list_new_redirect_urls.sh
  scripts/remove_unused_reference_links.rb
  scripts/tests/update_old_links.md
  scripts/transform_reference_links.py
  scripts/update_old_links.py
  scripts/utils/merge_redirect_descendants.py
Labels: cla-signed

#8670 adding 'ulinks' to './bdocs help' docs
  _docs/_contributing/bdocs.md
Labels: cla-signed
