Repository braze-inc/braze-docs, pull requests merged in 2024-01, with the labels that each got.

#6682 [CO-2237] Updated doc for custom attribute automatic type detection
  _docs/_help/help_articles/data/change_custom_data_type.md
Labels: cla-signed

#6683 BD-2706: Typo fix
  _docs/_user_guide/message_building_by_channel/sms/campaign/retargeting.md
Labels: cla-signed

#6680 Clarify message interaction data expiration behavior for campaigns with tags
  _docs/_hidden/private_betas/campaign_data_retention.md
Labels: cla-signed

#6685 Update google_audience_sync.md
  _docs/_partners/canvas_steps/google_audience_sync.md
Labels: cla-signed

#6684 BD-2702: Fix app-centric language
  _docs/_user_guide/data_and_analytics/analytics/home_dashboard.md
Labels: cla-signed

#6686 BD-2704: Remove `canvas_step_id` and `canvas_step_name` from Canvas entry events
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#6687 BD-2651: Negative purchases (refunds) impact on LTV
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  assets/img/purchase_filter_example.gif
Labels: cla-signed

#6688 BD-2709 Create hidden page for updated "Creating a segment" article
  _docs/_hidden/private_betas/updated_segment_experience.md
Labels: cla-signed

#6689 BD-2703: Remove mention of using API to update catalog fields for Sync catalogs data
  _docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md
Labels: cla-signed

#6690 Deploy - January 2, 2023
  _docs/_help/help_articles/data/change_custom_data_type.md
  _docs/_hidden/private_betas/campaign_data_retention.md
  _docs/_hidden/private_betas/updated_segment_experience.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_user_guide/data_and_analytics/analytics/home_dashboard.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/retargeting.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
  _includes/campaign_analytics.md
  assets/img/purchase_filter_example.gif
Labels: cla-signed, Deploy

#6586 BD-2617 Catalog segments article
  _docs/_user_guide/engagement_tools/segments.md
  _docs/_user_guide/engagement_tools/segments/sql_segments/catalog_segments.md
  assets/img/catalog-segments-editor.png
  assets/img/catalog-segments-template.png
Labels: cla-signed

#6691 BD-2707: Clarify UTC for time zone
  _docs/_api/endpoints/export/user_data/post_users_global_control_group.md
  _docs/_api/endpoints/export/user_data/post_users_segment.md
Labels: cla-signed

#6692 BD-2701: Clarify which integrations are Audience Sync Pro
  _docs/_partners/canvas_steps.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_partners/canvas_steps/pinterest_audience_sync.md
  _docs/_partners/canvas_steps/snapchat_audience_sync.md
  _docs/_partners/canvas_steps/tiktok_audience_sync.md
Labels: cla-signed

#6693 BD-2711: Add note about Custom Code block behavior
  _docs/_user_guide/message_building_by_channel/email/preference_center/dnd_preference_center.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/editor_blocks.md
Labels: cla-signed

#6694 BD-2656: Add detail for "duplicate" events
  _docs/_api/endpoints/user_data/post_user_track.md
Labels: cla-signed

#6557 Adds in documentation for the non-Shopify version of back in stock - MERGE 1/4
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/Shopify_Features/shopify_catalogs/back_in_stock.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/back_in_stock_notifications.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/selections.md
  assets/img/back_in_stock_settings_non_shopify.png
Labels: cla-signed

#6695 Update segment.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
Labels: cla-signed

#6584 BD-2639 Update performance by segment
  _docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md
  assets/img_archive/variables_panel.png
Labels: cla-signed

#6698 Leftover deploy - January 4, 2024
  _docs/_api/endpoints/export/user_data/post_users_global_control_group.md
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_partners/canvas_steps.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_partners/canvas_steps/pinterest_audience_sync.md
  _docs/_partners/canvas_steps/snapchat_audience_sync.md
  _docs/_partners/canvas_steps/tiktok_audience_sync.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/Shopify_Features/shopify_catalogs/back_in_stock.md
  _docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md
  _docs/_user_guide/engagement_tools/segments.md
  _docs/_user_guide/engagement_tools/segments/sql_segments/catalog_segments.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/dnd_preference_center.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/editor_blocks.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/back_in_stock_notifications.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/selections.md
  assets/img/back_in_stock_settings_non_shopify.png
  assets/img/catalog-segments-editor.png
  assets/img/catalog-segments-template.png
  assets/img_archive/variables_panel.png
Labels: cla-signed, Deploy

#6699 Update WhatsApp response messaging
  _docs/_hidden/private_betas/whatsapp_response_messaging.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6703 Update mixpanel_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
Labels: cla-signed

#6702 BD-2721: Clarify only Canvas names are searchable, not steps
  _docs/_user_guide/administrative/access_braze/global_search.md
Labels: cla-signed

#6704 Removing a link to iOS legacy content from a Swift landing page
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization.md
Labels: cla-signed

#6705 BD-2629: Follow up clarification for enqueued
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
Labels: cla-signed

#6697 remove p12 support
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/unity/push_notifications/ios.md
Labels: cla-signed

#6708 Update puma 6.4.2
  Gemfile.lock
Labels: cla-signed

#6673 BD-2698 Update WhatsApp docs for December
  _docs/_user_guide/message_building_by_channel/whatsapp.md
  _docs/_user_guide/message_building_by_channel/whatsapp/faqs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/experiments.md
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/opt-ins_and_opt-outs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/quality_rating.md
  _docs/_user_guide/message_building_by_channel/whatsapp/meta_resources.md
  _docs/_user_guide/message_building_by_channel/whatsapp/overview.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_phone_numbers.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
  _includes/campaign_analytics.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6712 BD-2725: Blocklist up to 300 custom attributes and 300 events
  _docs/_user_guide/administrative/app_settings/custom_event_and_attribute_management.md
Labels: cla-signed

#6711 push max
  _docs/_user_guide/message_building_by_channel/push/android/push_max.md
Labels: cla-signed

#6701 BD-2710 Add SQL variables to Query Builder
  _docs/_user_guide/data_and_analytics/query_builder.md
  assets/img_archive/query_builder_time_range.png
  assets/img_archive/sql_variables_campaigns.png
  assets/img_archive/sql_variables_canvases.png
  assets/img_archive/sql_variables_panel.png
  assets/img_archive/sql_variables_productname.png
Labels: cla-signed, release notes

#6710 January 2024 release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2024.md
  _docs/_help/release_notes/2024/1_9_24.md
Labels: cla-signed

#6713 Deploy - January 9, 2024
  Gemfile.lock
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/integration.md
  _docs/_developer_guide/platform_integration_guides/unity/push_notifications/ios.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2024.md
  _docs/_help/release_notes/2024/1_9_24.md
  _docs/_hidden/private_betas/whatsapp_response_messaging.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_user_guide/administrative/access_braze/global_search.md
  _docs/_user_guide/administrative/app_settings/custom_event_and_attribute_management.md
  _docs/_user_guide/data_and_analytics/query_builder.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
  _docs/_user_guide/message_building_by_channel/push/android/push_max.md
  _docs/_user_guide/message_building_by_channel/whatsapp.md
  _docs/_user_guide/message_building_by_channel/whatsapp/faqs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/experiments.md
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/opt-ins_and_opt-outs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/quality_rating.md
  _docs/_user_guide/message_building_by_channel/whatsapp/meta_resources.md
  _docs/_user_guide/message_building_by_channel/whatsapp/overview.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_phone_numbers.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md
  _includes/campaign_analytics.md
  assets/img_archive/query_builder_time_range.png
  assets/img_archive/sql_variables_campaigns.png
  assets/img_archive/sql_variables_canvases.png
  assets/img_archive/sql_variables_panel.png
  assets/img_archive/sql_variables_productname.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#6714 BD-2727 Update Query Builder variable
  _docs/_user_guide/data_and_analytics/query_builder.md
Labels: cla-signed

#6715 BD-2728 Update Segment docs
  _docs/_hidden/private_betas/updated_segment_experience.md
  _docs/_user_guide/engagement_tools/segments/sql_segments/catalog_segments.md
Labels: cla-signed

#6716 BD-2722 Catalog segments edits
  _docs/_user_guide/engagement_tools/segments/sql_segments/catalog_segments.md
  assets/img/catalog-segments-editor.png
Labels: cla-signed

#6681 Add and re-format installation instructions for Braze Swift SDK
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/installation_methods/cocoapods.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/installation_methods/swift_package_manager.md
Labels: cla-signed

#6717 Added small clarification on how the listener behaves in React
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
Labels: cla-signed

#6718 Update deprecations.md
  _docs/_help/release_notes/deprecations.md
Labels: cla-signed

#6707 [SDK-4487] Swift SDK Manual Integration Guide
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/installation_methods/manual_integration.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/overview.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/customization/rich_notifications.md
  assets/img/swift/rich_push/manual1.png
  assets/img/swift/sdk_integration/copy-bundle-resources.png
  assets/img/swift/sdk_integration/do-not-embed-and-sign.png
  assets/img/swift/sdk_integration/download-braze-swift-sdk-prebuilt.png
  assets/img/swift/sdk_integration/embed-and-sign.png
Labels: cla-signed

#6722 Add screenshots to Creating segment
  _docs/_hidden/private_betas/updated_segment_experience.md
  assets/img_archive/segmenter_and_or.png
  assets/img_archive/segmenter_exclusion_groups.png
  assets/img_archive/segmenter_filter_groups.png
  assets/img_archive/segmenter_reachable_users.png
Labels: cla-signed

#6724 Leftover Deploy - January 11, 2024
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/installation_methods/cocoapods.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/installation_methods/manual_integration.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/installation_methods/swift_package_manager.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/overview.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/customization/rich_notifications.md
  _docs/_help/release_notes/deprecations.md
  _docs/_hidden/private_betas/updated_segment_experience.md
  _docs/_user_guide/data_and_analytics/query_builder.md
  _docs/_user_guide/engagement_tools/segments/sql_segments/catalog_segments.md
  assets/img/catalog-segments-editor.png
  assets/img/swift/rich_push/manual1.png
  assets/img/swift/sdk_integration/copy-bundle-resources.png
  assets/img/swift/sdk_integration/do-not-embed-and-sign.png
  assets/img/swift/sdk_integration/download-braze-swift-sdk-prebuilt.png
  assets/img/swift/sdk_integration/embed-and-sign.png
  assets/img_archive/segmenter_and_or.png
  assets/img_archive/segmenter_exclusion_groups.png
  assets/img_archive/segmenter_filter_groups.png
  assets/img_archive/segmenter_reachable_users.png
Labels: cla-signed, Deploy

#6725 BD-2720 Update Content Card Refresh Details
  _docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
Labels: cla-signed

#6726 BD-2726 Add Custom Attributes tile to Segments page
  _docs/_user_guide/engagement_tools/segments.md
Labels: cla-signed

#6728 Partner Docs: loplat
  _docs/_partners/message_personalization/location/loplat.md
  _lang/fr/_partners/message_personalization/location/loplat.md
Labels: cla-signed

#6729 Update Lab index
  _config.yml
  _includes/html_include.html
  _includes/search_page.html
  assets/js/algolia_header_search.js
  assets/js/algolia_main_search.js
Labels: cla-signed

#6731 Add note about flattening arrays
  _docs/_user_guide/sage_ai/recommendations.md
Labels: cla-signed

#6730 Update EROR about minimum data
  _includes/campaign_analytics.md
Labels: cla-signed

#6709 BD-2713: Criteo audience sync GA - MERGE 1/12
  _docs/_partners/canvas_steps.md
  _docs/_partners/canvas_steps/criteo_audience_sync.md
  _docs/_partners/canvas_steps/overview.md
  assets/img/audience_sync/audience_sync4.png
  assets/img/audience_sync/audience_sync7.png
  assets/img/audience_sync/audience_sync_pro1.png
  assets/img/audience_sync/audience_sync_pro2.png
  assets/img/audience_sync/audience_sync_pro3a.png
  assets/img/audience_sync/audience_sync_pro3b.png
  assets/img/audience_sync/audience_sync_pro4.png
  assets/img/audience_sync/facebook_partner.png
  assets/img/audience_sync/google_ads_partner.png
Labels: cla-signed

#6706 BD-2723: Remove outdated Braze Learning link and video
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/teams.md
Labels: cla-signed

#6732 Leftover deploy pt. 2 - January 12, 2024
  _config.yml
  _docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
  _docs/_partners/canvas_steps.md
  _docs/_partners/canvas_steps/criteo_audience_sync.md
  _docs/_partners/canvas_steps/overview.md
  _docs/_partners/message_personalization/location/loplat.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/teams.md
  _docs/_user_guide/engagement_tools/segments.md
  _docs/_user_guide/sage_ai/recommendations.md
  _includes/campaign_analytics.md
  _includes/html_include.html
  _includes/search_page.html
  _lang/fr/_partners/message_personalization/location/loplat.md
  assets/img/audience_sync/audience_sync4.png
  assets/img/audience_sync/audience_sync7.png
  assets/img/audience_sync/audience_sync_pro1.png
  assets/img/audience_sync/audience_sync_pro2.png
  assets/img/audience_sync/audience_sync_pro3a.png
  assets/img/audience_sync/audience_sync_pro3b.png
  assets/img/audience_sync/audience_sync_pro4.png
  assets/img/audience_sync/facebook_partner.png
  assets/img/audience_sync/google_ads_partner.png
  assets/js/algolia_header_search.js
  assets/js/algolia_main_search.js
Labels: cla-signed, Deploy

#6737 BD-2729 Link to GIF-specs article
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/fullscreen.md
Labels: cla-signed

#6739 Update support with developerid
  _config.yml
  _docs/_hidden/other/support_contact.md
Labels: cla-signed

#6741 BD-2744 Update Custom Code Block FAQ
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
Labels: cla-signed

#6740 BD-2738: Collecting consent for EEA and UK end users
  _docs/_partners/canvas_steps/google_audience_sync.md
Labels: cla-signed

#6742 BD-2742 Update SMS double opt-in images
  _docs/_user_guide/message_building_by_channel/sms/keywords/sms_double_opt_in.md
Labels: cla-signed

#6735 [Untracked] Make the Swift SDK manual integration more explicit on `BrazeKit` being required
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/installation_methods/manual_integration.md
Labels: cla-signed

#6743 BD-2740: Clarify API campaigns only for Export send analytics endpoint
  _docs/_api/endpoints/export/campaigns/get_send_analytics.md
Labels: cla-signed

#6744 Deploy - January 16, 2024
  _config.yml
  _docs/_api/endpoints/export/campaigns/get_send_analytics.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/installation_methods/manual_integration.md
  _docs/_hidden/other/support_contact.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/fullscreen.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/sms_double_opt_in.md
  _docs/_user_guide/sage_ai/intelligence/faqs.md
Labels: cla-signed, Deploy

#6746 BD-2745 Update WhatsApp external link
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/opt-ins_and_opt-outs.md
Labels: cla-signed

#6734 Update link in loplat.md
  _docs/_partners/message_personalization/location/loplat.md
  _lang/fr/_partners/message_personalization/location/loplat.md
Labels: cla-signed

#6748 BD-2746: Fix rate limit for `/campaigns/data_series`
  _docs/_api/api_limits.md
  _docs/_api/endpoints/export/campaigns/get_campaign_analytics.md
  _includes/rate_limits.md
Labels: cla-signed

#6750 BD-2694: Add iOS reqs for Flutter's in-app messaging
  _docs/_developer_guide/platform_integration_guides/flutter/inapp_messages.md
Labels: cla-signed

#6749 BD-2697: Making default API rate limits clearer
  _docs/_api/api_limits.md
Labels: cla-signed

#6745 CO-2282 remove data points references from user archival docs
  _docs/_hidden/other/user_archival.md
Labels: cla-signed

#6752 BD-2748 Update catalog segments definition
  _docs/_user_guide/engagement_tools/segments/sql_segments/catalog_segments.md
Labels: cla-signed

#6736 BD-2741: New help article for reducing push notification payload size
  _docs/_help/help_articles/push/reducing_payload_size.md
Labels: cla-signed

#6751 Fixing incorrect cross-reference syntax
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/installation_methods/manual_integration.md
Labels: cla-signed

#6756 [Untracked] Update `requestPushPermission` documentation to reflect availability on Swifty
  _includes/archive/appboyBridge.md
Labels: cla-signed

#6755 BD-2750: Remove deprecated events
  _docs/_help/release_notes/2023/2_7_23.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed, release notes

#6747 BD-2730: Elaborate on variant distribution method for A/B testing
  _docs/_user_guide/engagement_tools/testing/multivariant_testing.md
  assets/img/variant_distribution_iam.png
Labels: cla-signed

#6758 Leftover deploy - January 18, 2024
  _docs/_api/api_limits.md
  _docs/_api/endpoints/export/campaigns/get_campaign_analytics.md
  _docs/_developer_guide/platform_integration_guides/flutter/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/installation_methods/manual_integration.md
  _docs/_help/help_articles/push/reducing_payload_size.md
  _docs/_help/release_notes/2023/2_7_23.md
  _docs/_hidden/other/user_archival.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  _docs/_partners/message_personalization/location/loplat.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/engagement_tools/segments/sql_segments/catalog_segments.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing.md
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/opt-ins_and_opt-outs.md
  _includes/archive/appboyBridge.md
  _includes/rate_limits.md
  _lang/fr/_partners/message_personalization/location/loplat.md
  assets/img/variant_distribution_iam.png
Labels: cla-signed, Deploy

#6759 Fix small typo in Sending test messages
  _docs/_developer_guide/platform_wide/sending_test_messages.md
Labels: cla-signed

#6757 Update code_generation.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/code_generation.md
Labels: cla-signed

#6763 Remove early access for FCM API
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/migrating_to_firebase_cloud_messaging.md
  _includes/firebase_cloud_messaging/early_access_banner.md
Labels: cla-signed

#6723 BD-2733 Compliance Center (to deploy on March 1st)
  _docs/_docs_pages/index.md
  _docs/_hidden/compliance/home.md
  assets/img/new-icons/circle-info-solid.svg
  assets/img/new-icons/file-contract-solid.svg
Labels: cla-signed

#6764 Leftover deploy pt. 2 - January 19, 2024
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/migrating_to_firebase_cloud_messaging.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_developer_guide/platform_wide/sending_test_messages.md
  _docs/_docs_pages/index.md
  _docs/_hidden/compliance/home.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/code_generation.md
  _includes/firebase_cloud_messaging/early_access_banner.md
  assets/img/new-icons/circle-info-solid.svg
  assets/img/new-icons/file-contract-solid.svg
Labels: cla-signed, Deploy

#6765 BD-2649: Boost search rank for geofences
  _docs/_user_guide/engagement_tools/locations_and_geofences.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md
Labels: cla-signed

#6727 Add documentation for deleting catalog items
  _docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md
Labels: cla-signed

#6760 Update snowflake.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
Labels: cla-signed

#6770 BD-2755: Fix typo
  _docs/_hidden/private_betas/preview_user_paths.md
Labels: cla-signed

#6772 BD-2754: Remove duplicate redirect that broke existing one
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6653 BD-2606: Movable Ink Customer Data API docs
  _docs/_partners/message_personalization/dynamic_content/movable_ink.md
  _docs/_partners/message_personalization/dynamic_content/movable_ink/customer_data_api.md
  assets/img/movable_ink/cd_api_webhook_ab.png
  assets/img/movable_ink/cd_api_webhook_kvp.png
  assets/img/movable_ink/cd_api_webhook_response.png
  assets/img/movable_ink/cd_api_webhook_settings.png
  assets/img/movable_ink/cd_api_webhook_url.png
Labels: cla-signed

#6774 add user-delete doc for bigquery and databricks
  _docs/_user_guide/data_and_analytics/cloud_ingestion/delete_users.md
Labels: cla-signed

#6771 [SDK-4621] Improve Flutter iOS IAM docs
  _docs/_developer_guide/platform_integration_guides/flutter/inapp_messages.md
Labels: cla-signed

#6766 Updating Snowflake integration steps (and fixing a typo)
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#6768 BD-2753 Create SQL Segment Extensions use case library
  _docs/_user_guide/engagement_tools/segments/sql_segments/use_cases.md
  _layouts/sql_segment_extensions_glossary.html
Labels: cla-signed

#6773 BD-2756: Updates for Audience Sync to Google - MERGE 1/23
  _docs/_partners/canvas_steps/google_audience_sync.md
Labels: cla-signed

#6776 Update user_profile_lifecycle.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
  assets/img_archive/Braze_User_aliases.png
Labels: cla-signed

#6753 BD-2691: Clarify how to send only deltas for CDI
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
Labels: cla-signed

#6775 BD-2758: Updates to Data Transformation - MERGE 1/23
  _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
  _docs/_user_guide/data_and_analytics/data_transformation/overview.md
  _includes/create_transformation.md
  assets/img/data_transformation/data_transformation10.png
Labels: cla-signed, release notes

#6777 Deploy - January 23, 2024
  _docs/_developer_guide/platform_integration_guides/flutter/inapp_messages.md
  _docs/_hidden/private_betas/preview_user_paths.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
  _docs/_partners/message_personalization/dynamic_content/movable_ink.md
  _docs/_partners/message_personalization/dynamic_content/movable_ink/customer_data_api.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/delete_users.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md
  _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
  _docs/_user_guide/data_and_analytics/data_transformation/overview.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
  _docs/_user_guide/engagement_tools/locations_and_geofences.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md
  _docs/_user_guide/engagement_tools/segments/sql_segments/use_cases.md
  _includes/create_transformation.md
  _layouts/sql_segment_extensions_glossary.html
  assets/img/data_transformation/data_transformation10.png
  assets/img/movable_ink/cd_api_webhook_ab.png
  assets/img/movable_ink/cd_api_webhook_kvp.png
  assets/img/movable_ink/cd_api_webhook_response.png
  assets/img/movable_ink/cd_api_webhook_settings.png
  assets/img/movable_ink/cd_api_webhook_url.png
  assets/img_archive/Braze_User_aliases.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#6779 BD-2757 fix broken link for targeting a singular app
  _docs/_user_guide/administrative/app_settings/workspaces.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#6784 BD-2767: Add information on suspending users
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/adding_users_to_your_dashboard.md
  assets/img_archive/delete_user_new.png
  assets/img_archive/suspend_user.png
  assets/img_archive/suspend_user2.png
Labels: cla-signed

#6785 BD-2764 Update screenshots Adding and Deleting Users
  assets/img/add_new_user_2.png
  assets/img/add_new_user_3.png
  assets/img_archive/delete_user_new.png
Labels: cla-signed

#6786 BD-2770 Clarify sentence in User Profile Lifecycle
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
Labels: cla-signed

#6787 Update WhatsApp imgs
  _docs/_user_guide/message_building_by_channel/whatsapp/overview.md
  _lang/fr/_user_guide/message_building_by_channel/whatsapp/overview.md
  assets/img/whatsapp/whatsapp10.png
Labels: cla-signed

#6788 BD-2751: Updates to HTML and drag-and-drop Content Block creation steps
  _docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
  _includes/create_content_block.md
  assets/img_archive/dnd_content_block_composer.png
  assets/img_archive/html_content_block_composer.png
Labels: cla-signed

#6790 BD-2763: Inbox Vision works for random users only
  _docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
  _docs/_user_guide/message_building_by_channel/email/inbox_vision.md
  assets/img/copy-content-block.png
  assets/img/template_archive_cog.png
  assets/img/unarchive-content-block.png
Labels: cla-signed

#6792 Legal update for Google Audience Sync
  _docs/_partners/canvas_steps/google_audience_sync.md
Labels: cla-signed

#6791 BD-2768: Add Canvas analytics to Your Reports section
  _docs/_user_guide/data_and_analytics/reporting.md
  _docs/_user_guide/data_and_analytics/reporting/campaign_analytics.md
  _docs/_user_guide/data_and_analytics/reporting/canvas_analytics.md
Labels: cla-signed

#6794 Nuance on the external ID in the payload
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
Labels: cla-signed

#6795 BD-2772: Clarify deduplication is only for original editor Canvases
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
Labels: cla-signed

#6782 [SDK-4425] iOS - Add more documentation around the usage of IAM display options
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/in-app_message_delivery.md
Labels: cla-signed

#6798 Link Segment Insights to Performance by Segment article
  _docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md
Labels: cla-signed

#6797 BD-2773 Remove Early Access banner for Custom Code Blocks
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/editor_blocks.md
Labels: cla-signed

#6780 update documentation for time field in events and purchases for CDI
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
Labels: cla-signed

#6799 Update screenshots in Purchase Events
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  assets/img/nested_object3.png
  assets/img/purchase2.png
  assets/img/purchase_filter_example.gif
Labels: cla-signed

#6801 BD-2774 Update merge behavior documentation
  _docs/_api/endpoints/user_data/post_users_merge.md
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
Labels: cla-signed

#6803 Update Decision Split screenshot
  assets/img/define-split-2.png
Labels: cla-signed

#6804 Fix custom attribute link
  _docs/_hidden/private_betas/updated_segment_experience.md
Labels: cla-signed

#6802 Update push_max.md
  _docs/_user_guide/message_building_by_channel/push/android/push_max.md
Labels: cla-signed

#6808 BD-2775: Clarify payload size limitation for CDI
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
Labels: cla-signed

#6812 Remove EA flag from cdi endpoints page
  _docs/_api/endpoints/cdi.md
  _docs/_api/endpoints/cdi/get_integration_list.md
  _docs/_api/endpoints/cdi/get_job_sync_status.md
  _docs/_api/endpoints/cdi/post_job_sync.md
Labels: cla-signed

#6814 Clarification for recommendations
  _docs/_user_guide/sage_ai/recommendations.md
Labels: cla-signed

#6813 BD-2783: Clarify required permissions to view Deliverability Center
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
Labels: cla-signed

#6815 Deploy - January 30, 2024
  _docs/_api/endpoints/cdi.md
  _docs/_api/endpoints/cdi/get_integration_list.md
  _docs/_api/endpoints/cdi/get_job_sync_status.md
  _docs/_api/endpoints/cdi/post_job_sync.md
  _docs/_api/endpoints/user_data/post_users_merge.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/in-app_message_delivery.md
  _docs/_hidden/private_betas/updated_segment_experience.md
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
  _docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/segments/sql_segments/use_cases.md
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/editor_blocks.md
  _docs/_user_guide/message_building_by_channel/push/android/push_max.md
  _docs/_user_guide/sage_ai/recommendations.md
  assets/img/define-split-2.png
  assets/img/nested_object3.png
  assets/img/purchase2.png
  assets/img/purchase_filter_example.gif
Labels: cla-signed, Deploy

#6816 Update deliverability_center.md
  _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
Labels: cla-signed

#6810 [SDK-4178] Xamarin docs - Swift SDK and AppboyKit version note
  _docs/_developer_guide/platform_integration_guides/xamarin/initial_sdk_setup.md
Labels: cla-signed

#6819 Removed code styling
  _includes/archive/setting_user_ids/naming_convention.md
Labels: cla-signed
