Repository braze-inc/braze-docs, pull requests merged in 2024-09, with the labels that each got.

#8008 Update mentions of "drop-down" to "dropdown"
  _docs/_api/api_campaigns.md
  _docs/_developer_guide/platform_wide/getting_started/analytics_overview.md
  _docs/_hidden/private_betas/multiple_stores.md
  _docs/_partners/data_and_infrastructure_agility/analytics/npaw.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/octolis.md
  _docs/_partners/data_and_infrastructure_agility/data_privacy/datagrail.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/dyspatch.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/taxi_for_email.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
  _docs/_user_guide/data_and_analytics/custom_data/managing_custom_data.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/retargeting_campaigns.md
  _docs/_user_guide/message_building_by_channel/sms/mms/contact_card.md
  _includes/archive/in_app_message.md
Labels: cla-signed

#8010 Added information about the self-service "Changelog" of "Changes Since Last Viewed"
  _docs/_user_guide/engagement_tools/canvas/testing_canvases/measuring_and_testing_with_canvas_analytics.md
  _docs/_user_guide/engagement_tools/segments/managing_segments.md
  _includes/campaign_analytics.md
Labels: cla-signed

#8013 Update lexer.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/lexer.md
Labels: cla-signed

#8019 Allow utf8 chars in tabids
  _docs/_developer_guide/customization_guides/content_cards/logging_analytics.md
  _plugins/tabs.rb
Labels: cla-signed

#8020 Putting in fixes for broken links from the translation process
  _lang/ja/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_audiences.md
  _lang/ja/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
  _lang/ja/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
Labels: cla-signed

#8018 Add ko setting
  .vercel/build.js
  Rakefile
  _data/i18n.yml
  _lang/_config_ko.yml
  public/index_ja.html
  public/index_ko.html
Labels: cla-signed

#8009 BD-3414: Updates for API Keys and Identifiers
  _docs/_api/basics.md
  _docs/_user_guide/administrative/app_settings/api_settings_tab.md
  assets/img_archive/api-key-ip-whitelisting.png
  assets/img_archive/api-key-options.png
  assets/img_archive/rest-api-key.png
  assets/img_archive/view-api-key.png
Labels: cla-signed

#7950 BD-3397 Update Short and Long Codes
  _includes/archive/short_and_long_codes.md
Labels: cla-signed

#8024 BD-3425 Roles GA
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#7986 [BD-2879] update ios uninstall tracking docs
  _docs/_developer_guide/platform_integration_guides/swift/analytics/uninstall_tracking.md
Labels: status: do not merge, cla-signed

#8004 BD-3419 Add Connected sources screenshot
  _docs/_user_guide/data_and_analytics/cloud_ingestion/connected_sources.md
  assets/img/cloud_ingestion/connected_source_bg_1.png
  assets/img/cloud_ingestion/connected_source_bg_2.png
  assets/img/cloud_ingestion/connected_source_databricks_1.png
  assets/img/cloud_ingestion/connected_source_db_2.png
  assets/img/cloud_ingestion/connected_source_rd_1.png
  assets/img/cloud_ingestion/connected_source_rd_2.png
  assets/img/cloud_ingestion/connected_source_rd_3.png
  assets/img/cloud_ingestion/connected_source_sf_1.png
  assets/img/cloud_ingestion/connected_source_tab.png
  assets/img/cloud_ingestion/connected_source_test_connection.png
Labels: cla-signed

#8016 Update airbyte.md prerequisites
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/airbyte.md
Labels: cla-signed

#8001 Update contentsquare.md
  _docs/_partners/data_and_infrastructure_agility/analytics/contentsquare.md
Labels: cla-signed

#8032 BD-3429: Alphabetize channels in example request
  _docs/_api/endpoints/messaging/send_messages/post_send_messages.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
Labels: cla-signed

#8029 BD-3318-2 Apply Diataxis standards to About Content Cards
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
Labels: cla-signed

#7987 BD-3418 Apply Diataxis standards to Update User Data Collection
  _docs/_user_guide/data_and_analytics/user_data_collection.md
  _docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md
  _docs/_user_guide/data_and_analytics/user_data_collection/collection_use_case.md
  _docs/_user_guide/data_and_analytics/user_data_collection/language_codes.md
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
  _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
Labels: cla-signed

#8035 Updated the language for our ISO 27001 / SOC 2 Type 2 Audits
  _docs/_developer_guide/disclosures/security_qualifications.md
  _docs/_hidden/private_betas/multiple_stores.md
  assets/pdf/Braze_ISO_Cert.pdf
Labels: cla-signed

#8038 BD-3439 Update Primary Conversions email metric name
  _docs/_user_guide/message_building_by_channel/email/reporting_and_analytics/analytics_glossary.md
Labels: cla-signed

#8041 File sending_test_messages.md committed.
  _lang/ja/_user_guide/administrative/app_settings/company_settings/security_settings.md
Labels: cla-signed

#8025 Update EA note with before and after triggered IAM behavior
  _docs/_hidden/private_betas/canvas_triggered_iams.md
Labels: cla-signed

#8037 BD-3426: Add limit for 4 filters per catalog selection
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/selections.md
Labels: cla-signed

#7924 Update branch_for_deeplinking.md
  _docs/_partners/message_orchestration/attribution/branch/branch_for_deeplinking.md
Labels: cla-signed

#8012 fix: convert UTC offset to 2 digits for the hour instead of 1 digit.
  _docs/_api/endpoints/export/canvas/get_canvas_analytics_summary.md
Labels: cla-signed

#8042 BD-3443: Fix typo and update "Contact Card" to "contact card"
  _docs/_partners/message_personalization/dynamic_content/movable_ink.md
  _docs/_partners/message_personalization/dynamic_content/movable_ink/dynamic_sms_link.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/create.md
  _docs/_user_guide/message_building_by_channel/sms/mms/contact_card.md
  _docs/_user_guide/message_building_by_channel/sms/mms/create.md
Labels: cla-signed

#8031 [SDK-5171] Push subscription when clicking a notification from Terminated state
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/customization/custom_event_callback.md
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/integration.md
Labels: cla-signed

#7869 Update creating_a_webhook.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
Labels: cla-signed

#8043 Close note alert
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
Labels: cla-signed

#8045 BD-3445 Add list of security events that are reported
  _docs/_user_guide/administrative/app_settings/company_settings/security_settings.md
Labels: cla-signed

#8047 BD-3445-2 Add sentence to security event report download
  _docs/_user_guide/administrative/app_settings/company_settings/security_settings.md
Labels: cla-signed

#8048 SessionM Partnership Doc
  _docs/_partners/message_orchestration/channel_extensions/loyalty/sessionm.md
Labels: cla-signed

#8054 update docs for MAU sku
  _docs/_api/api_limits.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _includes/rate_limits.md
Labels: cla-signed

#8053 BD-3447: Fix typo and minor edits
  _docs/_user_guide/sage_ai/recommendations/about_item_recommendations.md
Labels: cla-signed

#8057 BD-3454 Suggestion to target users with true Google consent attributes
  _docs/_partners/canvas_steps/google_audience_sync.md
Labels: cla-signed

#8052 ip country
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
Labels: cla-signed

#8059 File how_braze_uses_currents.md committed.
  _lang/ja/_user_guide/data_and_analytics/braze_currents/how_braze_uses_currents.md
  _lang/ja/_user_guide/engagement_tools/campaigns/building_campaigns/time_based_campaign.md
  _lang/ja/_user_guide/engagement_tools/canvas/create_a_canvas/time_based_canvas.md
Labels: cla-signed

#8061 Making template dropdown more visible
  _docs/_contributing/content_types.md
Labels: cla-signed

#8062 Add FAQ for feature flags in Canvas
  _docs/_hidden/private_betas/idle_campaigns.md
Labels: cla-signed

#8064 BD-3444 Update Connected Sources with how to generate new RSA key
  _docs/_user_guide/data_and_analytics/cloud_ingestion/connected_sources.md
  assets/img/cloud_ingestion/connected_source_sf_4.png
Labels: cla-signed

#8066 Troubleshooting malformed links
  _lang/ja/_partners/message_personalization/dynamic_content/movable_ink.md
Labels: cla-signed

#8060 Update user_permissions.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#8067 Leftover deploy - September 12, 2024
  _docs/_api/api_limits.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_contributing/content_types.md
  _docs/_help/help_articles/api.md
  _docs/_help/help_articles/api/attribute_name_id_across_sources.md
  _docs/_help/help_articles/api/webhook_connected_content_errors.md
  _docs/_hidden/private_betas/canvas_triggered_iams.md
  _docs/_hidden/private_betas/idle_campaigns.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/sessionm.md
  _docs/_user_guide/administrative/app_settings/company_settings/security_settings.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/connected_sources.md
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
  _docs/_user_guide/message_building_by_channel/webhooks.md
  _docs/_user_guide/message_building_by_channel/webhooks/braze_to_braze_webhooks.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content.md
  _docs/_user_guide/sage_ai/recommendations/about_item_recommendations.md
  _includes/rate_limits.md
  _lang/ja/_partners/message_personalization/dynamic_content/movable_ink.md
  _lang/ja/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
  _lang/ja/_user_guide/data_and_analytics/analytics/conversions_dashboard.md
  _lang/ja/_user_guide/data_and_analytics/braze_currents/how_braze_uses_currents.md
  _lang/ja/_user_guide/data_and_analytics/cloud_ingestion/file_storage_integrations.md
  _lang/ja/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md
  _lang/ja/_user_guide/data_and_analytics/export_braze_data/export_troubleshooting.md
  _lang/ja/_user_guide/data_and_analytics/export_braze_data/opening_csv_reports_in_excel.md
  _lang/ja/_user_guide/data_and_analytics/reporting/report_builder.md
  _lang/ja/_user_guide/engagement_tools/campaigns/building_campaigns/targeting_users.md
  _lang/ja/_user_guide/engagement_tools/campaigns/building_campaigns/time_based_campaign.md
  _lang/ja/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _lang/ja/_user_guide/engagement_tools/canvas/create_a_canvas/time_based_canvas.md
  _lang/ja/_user_guide/engagement_tools/canvas/get_started.md
  _lang/ja/_user_guide/engagement_tools/canvas/ideas_and_strategies/localization.md
  _lang/ja/_user_guide/message_building_by_channel/push/ios/rich_notifications.md
  _lang/ja/_user_guide/message_building_by_channel/whatsapp/meta_resources.md
  assets/img/cloud_ingestion/connected_source_sf_4.png
Labels: cla-signed, Deploy

#8039 BD-3440 Add Trending item recommendations
  _docs/_user_guide/sage_ai/recommendations/about_item_recommendations.md
Labels: cla-signed

#8069 BD-3460 Response messages GA
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md
Labels: cla-signed

#8050 [einfra-2073] Increase max sg limit per ws from 100 to 350
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#8068 [REP-3127] Update time window description for creating a report
  _docs/_user_guide/data_and_analytics/reporting/report_builder.md
Labels: cla-signed

#8072 BD-3458 Unhide landing pages beta
  _docs/_user_guide/engagement_tools/landing_pages.md
  _docs/_user_guide/engagement_tools/landing_pages/drag_and_drop.md
Labels: cla-signed

#8076 Update on click to on-click behavior
  _docs/_developer_guide/customization_guides/content_cards/creating_custom_content_cards.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/in-app_messaging/customization/behavior_on_click.md
  _docs/_hidden/archive_docs/previous_in-app_message_generations.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/zoom.md
Labels: cla-signed

#8074 BD-3464: Remove broken 3rd party link
  _docs/_user_guide/personalization_and_dynamic_content/deep_linking_to_in-app_content.md
Labels: cla-signed

#8075 BD-3466 Add nested custom attributes to Using Liquid
  _docs/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md
Labels: cla-signed

#8082 BD-3446 Specify that engagment reports use company time zone
  _docs/_user_guide/data_and_analytics/reporting/engagement_reports.md
Labels: cla-signed

#8081 Update movable_ink.md
  _docs/_partners/message_personalization/dynamic_content/movable_ink.md
Labels: cla-signed

#8022 add inbox monster partner doc and link to added page
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/analytics.md
  _docs/_partners/data_and_infrastructure_agility/analytics/inbox_monster.md
  _docs/_partners/home.md
Labels: cla-signed, Braze Partnerships

#8083 Update metadata.md & page_layouts.md
  _docs/_contributing/yaml_front_matter/metadata.md
  _docs/_contributing/yaml_front_matter/page_layouts.md
Labels: cla-signed

#8085 BD-3467: Add Switzerland for Google Audience Sync for Google EU user consent policy
  _docs/_partners/canvas_steps/google_audience_sync.md
Labels: cla-signed

#8079 BD-3410: Custom data deletion EA
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/managing_custom_data.md
Labels: cla-signed

#8086 Script: generate list of redirect URLs
  bdocs
  scripts/list_redirect_urls.sh
Labels: cla-signed

#8090 BD-3471 Add Email to the BrazeAI Liquid Assistant
  _docs/_user_guide/sage_ai/generative_ai/ai_liquid.md
  _docs/_user_guide/sage_ai/generative_ai/ai_liquid/ai_liquid_prompts.md
Labels: cla-signed

#8091 BD-3475: Templating catalog items using Liquid
  _docs/_hidden/private_betas/template_catalog_item_liquid.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8098 BD-3472 Add Legal content to BrazeAI Liquid Assistant
  _docs/_user_guide/brazeai/generative_ai/ai_liquid.md
Labels: cla-signed

#8077 BD-3422: Canvas templates GA - MERGE 9/17
  _docs/_hidden/private_betas/canvas_templates.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/teams.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_templates.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/templates_and_media.md
  _docs/_user_guide/engagement_tools/templates_and_media/canvas_templates.md
  assets/img/braze_canvas_templates.png
Labels: cla-signed

#8087 Release Notes - September 17, 2024
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2024.md
  _docs/_help/release_notes/2024/9_17_24.md
Labels: cla-signed, Deploy

#8101 Moving the alert outside of the tab to allow for Markdown
  _docs/_user_guide/engagement_tools/segments/regex.md
Labels: cla-signed

#8100 Removing time-bound content from article
  _docs/_user_guide/engagement_tools/landing_pages/drag_and_drop.md
Labels: cla-signed

#8096 BD-3453: Add `phone` for objects articles
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_api/objects_filters/event_object.md
  _docs/_api/objects_filters/purchase_object.md
  _docs/_api/objects_filters/user_attributes_object.md
Labels: cla-signed

#8094 BD-3474: Update to `phone` for phone number identifier
  _docs/_api/endpoints/user_data/post_users_merge.md
Labels: cla-signed

#8102 Add current release notes to main page
  _docs/_help/release_notes.md
Labels: cla-signed

#8095 Quick fix: allow arguments for 'redirects' command
  bdocs
  scripts/list_redirect_urls.sh
Labels: cla-signed

#8070 Update message_engagement_events.md remove duplication of canvas_name
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#8110 Adding the Roadmap back to Landing Pages
  _docs/_user_guide/engagement_tools/landing_pages/drag_and_drop.md
Labels: cla-signed

#8111 BD-3484: Update mentions of "Data Warehouse" to "Data Warehouse Storage"
  _docs/_partners/data_and_infrastructure_agility/data_warehouses.md
  _docs/_user_guide/data_and_analytics/braze_currents/available_partners.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
Labels: cla-signed

#8080 BD-3463 Connecting a subdomain docs
  _docs/_user_guide/engagement_tools/landing_pages.md
  _docs/_user_guide/engagement_tools/landing_pages/connect_subdomain.md
  _docs/_user_guide/engagement_tools/landing_pages/drag_and_drop.md
  assets/img/landing_pages/connect_subdomain.png
Labels: cla-signed

#8108 BD-3469: Add example for adding UTM parameter to URL in SMS
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
Labels: cla-signed

#8109 BD-3483 Update reported security event
  _docs/_user_guide/administrative/app_settings/company_settings/security_settings.md
Labels: cla-signed

#8088 I18n phrase ja
  _lang/ja/_user_guide/data_and_analytics/export_braze_data/export_campaign_results_data.md
Labels: cla-signed

#8115 BD-3424 Add trending model to AI item recommendations
  _docs/_user_guide/brazeai/recommendations/ai_item_recommendations.md
Labels: cla-signed

#8063 BD-3451 Add Segment Extensions Refresh Interval Settings panel MERGE 9/17
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  assets/img/segment/segment_interval_settings.png
Labels: cla-signed

#8116 BD-3486 Update Dall-e 2 to Dall-e 3
  _docs/_user_guide/brazeai/generative_ai/ai_copywriting.md
Labels: cla-signed

#8112 [SDK-5158] Add docs about React location library fro Android
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Labels: cla-signed

#8026 Diátaxis edits: Braze Data Transformation
  _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
  _docs/_user_guide/data_and_analytics/data_transformation/overview.md
  _docs/_user_guide/data_and_analytics/data_transformation/use_cases.md
Labels: cla-signed

#8118 BD-3481 Change Azure AD to Microsoft Entra
  _docs/_user_guide/administrative/access_braze/single_sign_on.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/entra.md
  assets/img/entra.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8117 Update PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE
Labels: cla-signed

#8121 Leftover deploy - September 19, 2024
  .github/PULL_REQUEST_TEMPLATE
  README.md
  _docs/_contributing/bdocs.md
  _docs/_contributing/content_management/redirecting_urls.md
  _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/getting_started_shopify.md
  _docs/_user_guide/administrative/access_braze/single_sign_on.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/entra.md
  _docs/_user_guide/administrative/app_settings/company_settings/security_settings.md
  _docs/_user_guide/brazeai/generative_ai/ai_copywriting.md
  _docs/_user_guide/brazeai/recommendations/ai_item_recommendations.md
  _docs/_user_guide/data_and_analytics/braze_currents/available_partners.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
  _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
  _docs/_user_guide/data_and_analytics/data_transformation/overview.md
  _docs/_user_guide/data_and_analytics/data_transformation/use_cases.md
  _docs/_user_guide/engagement_tools/landing_pages.md
  _docs/_user_guide/engagement_tools/landing_pages/connect_subdomain.md
  _docs/_user_guide/engagement_tools/landing_pages/drag_and_drop.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
  _lang/ja/_user_guide/data_and_analytics/export_braze_data/export_campaign_results_data.md
  assets/img/entra.png
  assets/img/landing_pages/connect_subdomain.png
  assets/img/segment/segment_interval_settings.png
  assets/js/broken_redirect_list.js
  bdocs
  scripts/create_deploy_text.sh
  scripts/create_release_text.sh
  scripts/list_redirect_urls.sh
  scripts/remove_unused_reference_links.rb
  scripts/transform_reference_links.py
Labels: cla-signed, Deploy

#8122 Update the rate limit for /users/export/ids from 2,500 -> 250
  _docs/_api/api_limits.md
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
  _includes/rate_limits.md
Labels: cla-signed

#8128 Updates mentions of `phone` to "phone" in object bodies for consistency
  _docs/_api/objects_filters/event_object.md
  _docs/_api/objects_filters/purchase_object.md
  _docs/_api/objects_filters/user_attributes_object.md
Labels: cla-signed

#8124 [Docs feedback] BD-3490: Reorganize API key content for API overview
  _docs/_api/basics.md
Labels: cla-signed

#8129 Fix redirect
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8130 Leftover deploy pt. 2 - September 20, 2024
  _docs/_api/api_limits.md
  _docs/_api/basics.md
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
  _docs/_api/objects_filters/event_object.md
  _docs/_api/objects_filters/purchase_object.md
  _docs/_api/objects_filters/user_attributes_object.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
  _includes/rate_limits.md
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#8113 [BD-3494] Update Live Activities FAQ
  _docs/_developer_guide/platform_integration_guides/swift/live_activities/faq.md
Labels: cla-signed

#8119 Mpmpmpmp1 patch 5
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content.md
  _docs/_partners/message_personalization/dynamic_content/future_anthem.md
  assets/img/future_anthem/braze_example_attributes.png
  assets/img/future_anthem/future_anthem_example_attributes.png
Labels: cla-signed

#8131 Leftover deploy pt. 3 | September 20, 2024
  _docs/_developer_guide/platform_integration_guides/swift/live_activities/faq.md
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content.md
  _docs/_partners/message_personalization/dynamic_content/future_anthem.md
  _lang/ko/_docs_pages/404.md
  _lang/ko/_docs_pages/404_api.md
  _lang/ko/_docs_pages/api.md
  _lang/ko/_docs_pages/blank.md
  _lang/ko/_docs_pages/cla.md
  _lang/ko/_docs_pages/contributing.md
  _lang/ko/_docs_pages/developer_guide.md
  _lang/ko/_docs_pages/help.md
  _lang/ko/_docs_pages/home.md
  _lang/ko/_docs_pages/index.md
  _lang/ko/_docs_pages/partners.md
  _lang/ko/_docs_pages/robots.txt
  _lang/ko/_docs_pages/search.md
  _lang/ko/_docs_pages/user_guide.md
  assets/img/future_anthem/braze_example_attributes.png
  assets/img/future_anthem/future_anthem_example_attributes.png
Labels: Deploy

#8132 BD-3500: Add parentheses are invalid Liquid characters
  _docs/_user_guide/personalization_and_dynamic_content/liquid/operators.md
Labels: cla-signed

#8133 BD-3485: Update AI image generator image
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
  assets/img_archive/media_library_dalle.png
Labels: cla-signed

#8134 BD-3503: Clarify sentence in things to consider after launch
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/pre_post_launch_checklist.md
Labels: cla-signed

#8135 Update event properties size from 50kb to 100kb, which went out on Sept 19.
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events/nested_objects.md
  _lang/ja/_api/objects_filters/event_object.md
  _lang/ja/_api/objects_filters/purchase_object.md
  _lang/ja/_user_guide/data_and_analytics/custom_data/custom_events.md
  _lang/ja/_user_guide/data_and_analytics/custom_data/custom_events/nested_objects.md
  _lang/ja/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _lang/ko/_api/objects_filters/event_object.md
  _lang/ko/_api/objects_filters/purchase_object.md
Labels: cla-signed

#8136 Fix redirects for BrazeAI
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8127 [UT-2091] Update Segment "Messaging Use" Docs
  _docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md
Labels: cla-signed

#8138 BD-3505 Add Caclulate Exact Statistics to Canvas and campaigns
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/targeting_users.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  assets/img_archive/canvas_exact_stats.png
  assets/img_archive/multi_channel_footer.png
Labels: cla-signed

#8139 BD-3501: Add maximum delay for in-app message campaigns
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/time_based_campaign.md
Labels: cla-signed

#8105 BD-3477 Remove "send_id" for several message events
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#8141 BD-3512: Fix typo
  _docs/_user_guide/message_building_by_channel/email/amphtml.md
Labels: cla-signed

#8140 BD-3507: Clarify post-launch details
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
Labels: cla-signed

#8144 Fix instructions for finding app_ids / API keys
  _docs/_api/identifier_types.md
Labels: cla-signed

#8142 BD-3497: Add link aliasing example for anchor and capture tag
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
Labels: cla-signed

#8145 Removing developer nav
  _includes/html_include.html
  assets/js/developer_nav.js
Labels: cla-signed

#8147 Deploy - September 24, 2024
  _docs/_api/identifier_types.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events/nested_objects.md
  _docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/targeting_users.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/time_based_campaign.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/pre_post_launch_checklist.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
  _docs/_user_guide/message_building_by_channel/email/amphtml.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/operators.md
  _includes/html_include.html
  _lang/ja/_api/objects_filters/event_object.md
  _lang/ja/_api/objects_filters/purchase_object.md
  _lang/ja/_user_guide/data_and_analytics/custom_data/custom_events.md
  _lang/ja/_user_guide/data_and_analytics/custom_data/custom_events/nested_objects.md
  _lang/ja/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _lang/ko/_api/objects_filters/event_object.md
  _lang/ko/_api/objects_filters/purchase_object.md
  assets/img_archive/canvas_exact_stats.png
  assets/img_archive/media_library_dalle.png
  assets/img_archive/multi_channel_footer.png
  assets/js/broken_redirect_list.js
  assets/js/developer_nav.js
Labels: Deploy

#8146 Fix typo
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/launching_canvas_flow.md
Labels: cla-signed

#8148 BD-3511: Add note for Treasure Data that data is sent in batches
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/treasure_data/treasure_data_for_currents.md
Labels: cla-signed

#8114 BD-3492 BrazeAI Liquid Assistant GA MERGE 9/24
  _docs/_user_guide/brazeai/generative_ai/ai_liquid.md
  _docs/_user_guide/brazeai/generative_ai/ai_liquid/ai_liquid_prompts.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8044 BD-3449 Update UI and screenshots for Billing
  _docs/_user_guide/administrative/app_settings/subscription_and_usage.md
  assets/img/app_level_total.png
  assets/img/appgroup_datapoint_usage.png
  assets/img/company_data_point_usage_time.png
  assets/img/contract_details.png
  assets/img/data_point_usage_time.png
  assets/img/event_source_stats.png
  assets/img/most_used_events_attributes_2.png
  assets/img/most_used_events_attributes_time.png
  assets/img/subscription_and_billing2.png
Labels: cla-signed

#8137 BD-3508 Add note about hourly Segment Extension refreshes
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
Labels: cla-signed

#8150 BD-3518 Fix broken Content Cards learning link
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
Labels: cla-signed

#8151 BD-3513 Update global control group
  _docs/_user_guide/engagement_tools/testing/global_control_group.md
Labels: cla-signed

#8154 Update mention of DALL E 2 to DALL E 3
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
Labels: cla-signed

#8152 Identifier field-level encryption GA
  _docs/_user_guide/administrative/app_settings.md
  _docs/_user_guide/data_and_analytics/field_level_encryption.md
  _docs/_user_guide/message_building_by_channel/email.md
  assets/img/field_level_encryption.png
Labels: cla-signed

#8156 BD-3271: Update anonymized to deleted (nulled)
  _docs/_help/help_articles/api/delete_user.md
Labels: cla-signed

#8157 BD-3519: Remove duplicate use cases section from Creating a catalog article
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/using_catalogs.md
Labels: cla-signed

#8158 BD-3519: Update language on limitations for adding multiple catalog items
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/using_catalogs.md
Labels: cla-signed

#8159 BD-3523: Add suggestion to use Liquid tag for unsubscribe link
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#8155 [BD-3522 ] Fixing redirect for legacy iOS
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/initial_sdk_setup.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8161 Leftover deploy - September 26, 2024
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/initial_sdk_setup.md
  _docs/_help/help_articles/api/delete_user.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/treasure_data/treasure_data_for_currents.md
  _docs/_user_guide/administrative/app_settings.md
  _docs/_user_guide/administrative/app_settings/subscription_and_usage.md
  _docs/_user_guide/brazeai/generative_ai/ai_liquid.md
  _docs/_user_guide/brazeai/generative_ai/ai_liquid/ai_liquid_prompts.md
  _docs/_user_guide/data_and_analytics/field_level_encryption.md
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/launching_canvas_flow.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
  _docs/_user_guide/engagement_tools/testing/global_control_group.md
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
  _docs/_user_guide/message_building_by_channel/email.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/using_catalogs.md
  assets/img/app_level_total.png
  assets/img/appgroup_datapoint_usage.png
  assets/img/company_data_point_usage_time.png
  assets/img/contract_details.png
  assets/img/data_point_usage_time.png
  assets/img/event_source_stats.png
  assets/img/field_level_encryption.png
  assets/img/most_used_events_attributes_2.png
  assets/img/most_used_events_attributes_time.png
  assets/img/subscription_and_billing2.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#8162 BD-3524 Update email analytics glossary
  _docs/_user_guide/message_building_by_channel/email/reporting_and_analytics/analytics_glossary.md
  _includes/campaign_analytics.md
Labels: cla-signed

#8153 BD-3502 Add user account linking docs
  _docs/_user_guide/message_building_by_channel/line/line_setup.md
  assets/img/line/account_link_1.png
  assets/img/line/account_link_2.png
Labels: cla-signed

#8166 BD-3532 Docs Feedback - Fix Liquid brackets
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
Labels: cla-signed

#8165 BD-3515 Update App Level Total Data Point Usage table description
  _docs/_user_guide/administrative/app_settings/subscription_and_usage.md
Labels: cla-signed

#8168 Remove old AI query builder beta alert
  _docs/_user_guide/data_and_analytics/query_builder.md
Labels: cla-signed

#8171 BD-3473 Update Content Card composer images
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
  assets/img_archive/dnd_content_block_composer.png
  assets/img_archive/dnd_content_block_personalization.png
  assets/img_archive/html_content_block_composer.png
Labels: cla-signed

#8174 Fix tables missing headers
  _docs/_user_guide/administrative/access_braze/portal.md
Labels: cla-signed

#8175 BD-3536 Multi-WABA is supported
  _docs/_user_guide/message_building_by_channel/whatsapp/overview.md
Labels: cla-signed

#8177 Fixed broken redirect
  assets/js/broken_redirect_list.js
Labels: cla-signed
