Repository braze-inc/braze-docs, pull requests merged in 2024-05, with the labels that each got.

#7283 BD-3014: Clarify details for race conditions and multiple endpoints
  _docs/_user_guide/engagement_tools/testing/race_conditions.md
Labels: cla-signed

#7284 BD-3057 Update link in CDI segments
  _docs/_user_guide/engagement_tools/segments/segment_extension/cdi_segments.md
Labels: cla-signed

#7281 BD-2971: Add Portuguese and Spanish for supported languages in dashboard - MERGE 5/2
  _docs/_user_guide/administrative/access_braze/language.md
  assets/img_archive/language_dashboard.png
Labels: cla-signed

#7285 BD-3061: Update important alert
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_approval.md
Labels: cla-signed

#7287 Fix EA notes
  _docs/_user_guide/data_and_analytics/cloud_ingestion/connected_sources.md
  _docs/_user_guide/engagement_tools/segments/segment_extension/cdi_segments.md
Labels: cla-signed

#7288 BD-3016: Add additional resource links for geofences
  _docs/_user_guide/engagement_tools/locations_and_geofences/faqs.md
Labels: cla-signed

#7289 BD-3040 Update capture form to sign-up form
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/email_capture.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/phone_number_capture.md
  assets/img_archive/dnd_iam_phone_capture_template.png
Labels: cla-signed

#7291 BD-3039: Add troubleshooting info for IAM test sends
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md
Labels: cla-signed

#7167 Matching iOS documentation line
  _docs/_developer_guide/platform_integration_guides/unity/in-app_messaging.md
Labels: cla-signed

#7294 BD-3062 Remove beta from Event Streaming in Amplitude Audiences
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_audiences.md
Labels: cla-signed

#7231 BD-3011: Translation API endpoints EA
  _docs/_api/endpoints/translations.md
  _docs/_api/endpoints/translations/get_bulk_translations_campaigns.md
  _docs/_api/endpoints/translations/get_bulk_translations_canvases.md
  _docs/_api/endpoints/translations/get_translation_campaign.md
  _docs/_api/endpoints/translations/get_translation_canvas.md
  _docs/_api/endpoints/translations/put_update_translation_campaign.md
  _docs/_api/endpoints/translations/put_update_translation_canvas.md
Labels: cla-signed

#7296 Minor clarification to Email Bounces article
  _docs/_help/help_articles/email/email_bounces.md
Labels: cla-signed

#7297 [NOTIX] Remove stray tags
  _docs/_user_guide/message_building_by_channel/sms/campaign/create.md
Labels: cla-signed

#7299 Leftover deploy - May 2, 2024
  _docs/_api/endpoints/translations.md
  _docs/_api/endpoints/translations/get_bulk_translations_campaigns.md
  _docs/_api/endpoints/translations/get_bulk_translations_canvases.md
  _docs/_api/endpoints/translations/get_translation_campaign.md
  _docs/_api/endpoints/translations/get_translation_canvas.md
  _docs/_api/endpoints/translations/put_update_translation_campaign.md
  _docs/_api/endpoints/translations/put_update_translation_canvas.md
  _docs/_api/objects_filters/messaging/android_object.md
  _docs/_developer_guide/platform_integration_guides/unity/in-app_messaging.md
  _docs/_help/help_articles/email/email_bounces.md
  _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_audiences.md
  _docs/_user_guide/administrative/access_braze/language.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/connected_sources.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_approval.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/canvas_approval.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/faqs.md
  _docs/_user_guide/engagement_tools/segments/segment_extension/cdi_segments.md
  _docs/_user_guide/engagement_tools/testing/race_conditions.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/email_capture.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/phone_number_capture.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/create.md
  assets/img_archive/dnd_iam_phone_capture_template.png
  assets/img_archive/language_dashboard.png
Labels: Deploy

#7298 Convert alert notes to alert importants for early access
  _docs/_help/help_articles/data/change_custom_data_type.md
  _docs/_partners/isv_partners/best_practices.md
  _docs/_partners/message_orchestration/additional_channels/messaging/regal.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/getting_started_shopify.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
Labels: cla-signed

#7300 BD-3063: Update image
  assets/img/punchh/usecase5.png
Labels: cla-signed

#7293 Update privacy_manifest.md
  _docs/_developer_guide/platform_integration_guides/swift/privacy_manifest.md
  assets/img/apple/privacy_manifest/add_nsprivacytracking.png
  assets/img/apple/privacy_manifest/add_nsprivacytrackingdomains.png
  assets/img/apple/privacy_manifest/check_raw_keys_and_values.png
Labels: cla-signed

#7302 Align headers
  _docs/_api/use_cases.md
Labels: cla-signed

#7303 BD-3065: Update wording
  _docs/_user_guide/data_and_analytics/data_points.md
Labels: cla-signed

#7307 BD-3012: Add description for boolean
  _docs/_api/objects_filters/user_attributes_object.md
Labels: cla-signed

#7311 BD-3068 Update security settings for 2FA
  _docs/_user_guide/administrative/app_settings/company_settings/security_settings.md
Labels: cla-signed

#7309 BD-3013: Minor edit for /users/identify
  _docs/_api/endpoints/user_data/post_user_identify.md
Labels: cla-signed

#7310 Update translation endpoint icons
  _docs/_api/endpoints/translations.md
Labels: cla-signed

#7316 BD-3078 Fix run-on sentence in Rich Notifications
  _docs/_user_guide/message_building_by_channel/push/android/rich_notifications.md
Labels: cla-signed

#7312 [DLK-1801] update public schema after adding back comments
  assets/download_file/data-sharing-raw-table-schemas.txt
Labels: cla-signed

#7292 BD-3052: Add resources to add-to-calendar links article
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/add_to_calendar_links.md
Labels: cla-signed

#7318 Update your_first_contribution.md
  _docs/_contributing/your_first_contribution.md
Labels: cla-signed

#7313 [DLK-1754] add doc for query timeouts
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
Labels: cla-signed

#7280 BD-3046 Details about editing experiment messages mid-send
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
Labels: cla-signed

#7319 SDK-4882 / fixed firebase cloud messaging gradle dependency line back
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
Labels: cla-signed

#7321 BD-3080: Update promo codes detail for test sends
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
Labels: cla-signed

#7320 BD-3081 Update export troubleshooting
  _docs/_user_guide/data_and_analytics/export_braze_data/export_troubleshooting.md
Labels: cla-signed

#7315 Adds adikteev churn prediction integration
  _docs/_partners/data_and_infrastructure_agility/analytics/adikteev.md
  assets/img/adikteev/audience.png
  assets/img/adikteev/campaign.png
Labels: cla-signed

#7304 BD-3067: Engagement by Device report EA - MERGE 5/9
  _docs/_hidden/private_betas/email_insights.md
  assets/img/engagement_by_device_type.png
Labels: cla-signed

#7323 Tweaking CSS of documentation request form
  _docs/_hidden/other/documentation_request.md
  _lang/fr/_hidden/other/documentation_request.md
Labels: cla-signed

#7324 Update sdk_data_collection.md
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
Labels: cla-signed

#7322 BD-3043: Message-level one-click list-unsubscribe
  _docs/_hidden/private_betas/one-click_list-unsubscribe.md
  _docs/_user_guide/administrative/app_settings/email_settings.md
  assets/img/email_settings/one_click_list_unsubscribe_message_level.png
Labels: cla-signed

#7306 BD-3060: Sanitization article
  _docs/_user_guide/message_building_by_channel/email/best_practices/sanitization.md
  assets/img/email_sanitization.png
Labels: cla-signed

#7325 Add tile for sanitization article
  _docs/_user_guide/message_building_by_channel/email/best_practices.md
Labels: cla-signed

#7327 Leftover deploy - May 9, 2024
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_hidden/other/documentation_request.md
  _docs/_hidden/private_betas/email_insights.md
  _docs/_hidden/private_betas/one-click_list-unsubscribe.md
  _docs/_partners/data_and_infrastructure_agility/analytics/adikteev.md
  _docs/_user_guide/administrative/app_settings/email_settings.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_troubleshooting.md
  _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
  _docs/_user_guide/engagement_tools/segments/sql_segments/sql_segments_tables.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
  _docs/_user_guide/message_building_by_channel/email/best_practices.md
  _docs/_user_guide/message_building_by_channel/email/best_practices/sanitization.md
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
  _lang/fr/_hidden/other/documentation_request.md
  assets/img/adikteev/audience.png
  assets/img/adikteev/campaign.png
  assets/img/email_sanitization.png
  assets/img/email_settings/one_click_list_unsubscribe_message_level.png
  assets/img/engagement_by_device_type.png
Labels: cla-signed, Deploy

#7326 Update user_archival.md
  _docs/_hidden/other/user_archival.md
Labels: cla-signed

#7330 BD-3096: Update description for capitalize string filter
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
Labels: cla-signed

#7331 BD-3092 Clarify Canvas variation and control group filters
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#7333 BD-3099: Clarify detail for funnel reports
  _docs/_user_guide/data_and_analytics/reporting/funnel_reports.md
Labels: cla-signed

#7332 Note about backtesting of Preview Predictions
  _docs/_user_guide/sage_ai/predictive_suite/predictive_churn/prediction_analytics/prediction_quality.md
Labels: cla-signed

#7334 BD-3100: A/B testing for multiple devices for quick push campaign
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/ab_test_projection.md
Labels: cla-signed

#7295 BD-3066 Add identifier to overview
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
Labels: cla-signed

#7338 BD-3095 last-touch attribution template - dashboard builder
  _docs/_hidden/private_betas/dashboard_builder.md
Labels: cla-signed

#7339 BD-3102: Clarify promotion code detail
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
Labels: cla-signed

#7340 Small update for bd-3095
  _docs/_hidden/private_betas/dashboard_builder.md
Labels: cla-signed

#7335 Update message_engagement_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#7337 Update Partner_Page iam-studio.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/iam_studio.md
  assets/img/iam_studio/braze_campaign_editor.png
  assets/img/iam_studio/iam_customize_button.png
  assets/img/iam_studio/iam_customize_image.png
  assets/img/iam_studio/iam_customize_text.png
  assets/img/iam_studio/iam_template_gallery.png
Labels: cla-signed

#7341 BD-3082: Update statuses for campaigns and Canvases
  _docs/_hidden/private_betas/idle_campaigns.md
  _docs/_user_guide/engagement_tools/campaigns/getting_started/understanding_campaign_status.md
  _docs/_user_guide/engagement_tools/canvas/get_started/canvas_outlines.md
  _docs/_user_guide/engagement_tools/canvas/get_started/canvas_status.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#7342 Add Understanding Canvas status tile
  _docs/_user_guide/engagement_tools/canvas/get_started.md
Labels: cla-signed

#7347 Fix tile links for Translation API
  _docs/_api/endpoints/translations.md
Labels: cla-signed

#7344 BD-3097: Multi-Language Settings GA
  _docs/_user_guide/administrative/app_settings.md
  _docs/_user_guide/administrative/app_settings/multi_language_settings.md
  _docs/_user_guide/message_building_by_channel/email.md
  _docs/_user_guide/message_building_by_channel/email/using_locales.md
Labels: cla-signed

#7348 New documentation of brand guidelines feature for copywriting assistant
  _docs/_user_guide/sage_ai/generative_ai/ai_copywriting.md
  _docs/_user_guide/sage_ai/generative_ai/ai_copywriting/brand_guidelines.md
  assets/img/ai_copywriter/gpt3.png
  assets/img/ai_copywriter/manual_brand_guidelines.png
Labels: cla-signed

#7346 [DOCS] Edit IAM-STUDIO(partner)'s Docs modify
  _docs/_partners/message_orchestration/channel_extensions/email_templates/iam_studio.md
  assets/img/iam_studio/iam_custom_font.png
  assets/img/iam_studio/iam_customize_image.png
  assets/img/iam_studio/iam_liquid.png
  assets/img/iam_studio/iam_tracking_logging.png
Labels: cla-signed

#7349 Deploy - May 14, 2024
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
  _docs/_api/endpoints/translations.md
  _docs/_hidden/other/user_archival.md
  _docs/_hidden/private_betas/dashboard_builder.md
  _docs/_hidden/private_betas/idle_campaigns.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/iam_studio.md
  _docs/_user_guide/administrative/app_settings.md
  _docs/_user_guide/administrative/app_settings/multi_language_settings.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/reporting/funnel_reports.md
  _docs/_user_guide/engagement_tools/campaigns/getting_started/understanding_campaign_status.md
  _docs/_user_guide/engagement_tools/canvas/get_started.md
  _docs/_user_guide/engagement_tools/canvas/get_started/canvas_outlines.md
  _docs/_user_guide/engagement_tools/canvas/get_started/canvas_status.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/ab_test_projection.md
  _docs/_user_guide/message_building_by_channel/email.md
  _docs/_user_guide/message_building_by_channel/email/using_locales.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
  _docs/_user_guide/sage_ai/generative_ai/ai_copywriting.md
  _docs/_user_guide/sage_ai/generative_ai/ai_copywriting/brand_guidelines.md
  _docs/_user_guide/sage_ai/predictive_suite/predictive_churn/prediction_analytics/prediction_quality.md
  assets/img/ai_copywriter/gpt3.png
  assets/img/ai_copywriter/manual_brand_guidelines.png
  assets/img/iam_studio/braze_campaign_editor.png
  assets/img/iam_studio/iam_custom_font.png
  assets/img/iam_studio/iam_customize_button.png
  assets/img/iam_studio/iam_customize_image.png
  assets/img/iam_studio/iam_customize_text.png
  assets/img/iam_studio/iam_liquid.png
  assets/img/iam_studio/iam_template_gallery.png
  assets/img/iam_studio/iam_tracking_logging.png
  assets/img/preview_tab_content_block.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#7267 [SDK-4125] [SDK-4578] Flutter deep link set up guide
  _docs/_developer_guide/platform_integration_guides/flutter/deep_linking.md
  assets/img/flutter/flutter-ios-deep-link-info-plist.png
Labels: status: on hold / do not merge, cla-signed

#7351 BD-3104 Update application/json in Zapier docs
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/zapier.md
Labels: cla-signed

#7350 Update disabling_tracking.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/disabling_tracking.md
Labels: cla-signed

#7353 BD-3107 Add Link templates title
  _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
Labels: cla-signed

#7354 BD-3109: Fix Braze Go doc
  _docs/_hidden/pricing/braze_go.md
Labels: cla-signed

#7355 Revert changes from undoing config change PR
  _docs/_hidden/redirects/okta.md
  _docs/_partners/message_personalization.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events/nested_objects.md
  _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
  _docs/_user_guide/data_and_analytics/query_builder.md
  _docs/_user_guide/data_and_analytics/query_builder/query_templates.md
  _docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/reeligibility.md
  _docs/_user_guide/engagement_tools/canvas.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/get_started.md
  _docs/_user_guide/engagement_tools/canvas/get_started/canvas_outlines.md
  _docs/_user_guide/engagement_tools/canvas/get_started/the_basics.md
  _docs/_user_guide/engagement_tools/canvas/testing_canvases.md
Labels: cla-signed

#7356 Fix sentence
  _docs/_hidden/private_betas/idle_campaigns.md
Labels: cla-signed

#7358 BD-3110: Add detail about concluding Winning Paths
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/winning_path.md
Labels: cla-signed

#7352 FCM credential faq
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/migrating_to_firebase_cloud_messaging.md
  assets/img/android/push_integration/revert-credentials.png
Labels: cla-signed

#7359 [CO-2477] Updated back in stock doc, removed Shopify specific doc
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs/back_in_stock.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/back_in_stock_notifications.md
  assets/img/back_in_stock_settings.png
  assets/img/catalog_settings_drawer.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#7361 Leftover deploy - May 16, 2024
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/migrating_to_firebase_cloud_messaging.md
  _docs/_developer_guide/platform_integration_guides/flutter/deep_linking.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/disabling_tracking.md
  _docs/_hidden/misc_reference/scim_api_appendix.md
  _docs/_hidden/pricing/braze_go.md
  _docs/_hidden/private_betas/idle_campaigns.md
  _docs/_hidden/redirects/okta.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/zapier.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs/back_in_stock.md
  _docs/_partners/message_personalization.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events/nested_objects.md
  _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
  _docs/_user_guide/data_and_analytics/query_builder.md
  _docs/_user_guide/data_and_analytics/query_builder/query_templates.md
  _docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/reeligibility.md
  _docs/_user_guide/engagement_tools/canvas.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/winning_path.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/get_started.md
  _docs/_user_guide/engagement_tools/canvas/get_started/canvas_outlines.md
  _docs/_user_guide/engagement_tools/canvas/get_started/the_basics.md
  _docs/_user_guide/engagement_tools/canvas/testing_canvases.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/back_in_stock_notifications.md
  assets/img/android/push_integration/revert-credentials.png
  assets/img/back_in_stock_settings.png
  assets/img/catalog_settings_drawer.png
  assets/img/flutter/flutter-ios-deep-link-info-plist.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#7360 [DLK-1692] updates to cdi docs
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
  assets/img/cloud_ingestion/ingestion_19.png
Labels: cla-signed

#7362 [DLK-1691]Add FAQs around navi email
  _docs/_user_guide/data_and_analytics/cloud_ingestion.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/faqs.md
Labels: cla-signed

#7363 Update adikteev.md
  _docs/_partners/data_and_infrastructure_agility/analytics/adikteev.md
Labels: cla-signed

#7364 Update outdated callout
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#7366 Diataxis tweak + new heading for content management
  _docs/_contributing/content_management.md
  _docs/_contributing/content_management/cross_referencing.md
  _docs/_contributing/content_management/images.md
  _docs/_contributing/content_management/jekyll_collections.md
  _docs/_contributing/content_management/pages.md
  _docs/_contributing/content_management/redirecting_urls.md
  _docs/_contributing/content_management/reusing_content.md
  _docs/_contributing/content_management/sections.md
  _docs/_contributing/yaml_front_matter/metadata.md
  _docs/_contributing/yaml_front_matter/page_layouts.md
  _docs/_contributing/your_first_contribution.md
Labels: cla-signed

#7368 BD-3114 Fix Liquid use case
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
Labels: cla-signed

#7369 Update setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md
Labels: cla-signed

#7371 BD-3116: Remove sentence
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#7372 BD-3115: Add maximum 50 preference centers per workspace
  _docs/_user_guide/message_building_by_channel/email/preference_center/dnd_preference_center.md
Labels: cla-signed

#7365 BD-3106 - Message-level one-click list-unsubscribe GA
  _docs/_hidden/private_betas/one-click_list-unsubscribe.md
  _docs/_user_guide/administrative/app_settings/email_settings.md
  assets/img/email_settings/email_unsub_header_workspaces.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#7373 BD-3112: Clarify note
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/exit_criteria.md
Labels: cla-signed

#7370 BD-3101 Description fields and usage reports for custom attributes an…
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
Labels: cla-signed

#7377 Add note for updated HTML editor
  _docs/_user_guide/administrative/app_settings/email_settings.md
Labels: cla-signed

#7380 BD-3118: Add permission for Google Cloud Storage
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/google_cloud_storage_for_currents.md
Labels: cla-signed

#7374 BD-3117: Compliance documentation for webhooks
  _docs/_hidden/compliance/home.md
  _docs/_hidden/compliance/webhook_channel.md
  _docs/_hidden/compliance/whatsapp.md
Labels: cla-signed

#7382 PQ-2235: Clarify "calendar days"
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
Labels: cla-signed

#7383 Add language build
  Rakefile
Labels: cla-signed

#7384 BD-3119: Fix links
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
Labels: cla-signed

#7389 Update migrating_to_firebase_cloud_messaging.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/migrating_to_firebase_cloud_messaging.md
Labels: cla-signed

#7030 Create celebrus.md
  _docs/_partners/data_and_infrastructure_agility/analytics/celebrus.md
  _docs/_partners/home.md
  _docs/_partners/isv_partners.md
Labels: cla-signed, Braze Partnerships

#7391 Add subheadings for FAQ
  _docs/_user_guide/administrative/app_settings/email_settings.md
Labels: cla-signed

#7393 BD-3122: Semicolon to colon
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/search_campaigns.md
Labels: cla-signed

#7375 Create Treasure Data Cohort Import Docs
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/treasuredata.md
  _docs/_partners/home.md
  assets/img/treasure_data/cohort/cohort1.png
  assets/img/treasure_data/cohort/cohort2.png
  assets/img/treasure_data/cohort/cohort3.png
  assets/img/treasure_data/cohort/cohort4.png
Labels: cla-signed

#7395 Update migrating_to_firebase_cloud_messaging.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/migrating_to_firebase_cloud_messaging.md
Labels: cla-signed

#7394 Update link for Manage your account tile
  _docs/_user_guide/introduction.md
Labels: cla-signed

#7396 Leftover deploy - May 23, 2024
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/migrating_to_firebase_cloud_messaging.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/analytics/celebrus.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/treasuredata.md
  _docs/_partners/home.md
  _docs/_partners/isv_partners.md
  _docs/_user_guide/administrative/app_settings/email_settings.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/search_campaigns.md
  _docs/_user_guide/introduction.md
  assets/img/treasure_data/cohort/cohort1.png
  assets/img/treasure_data/cohort/cohort2.png
  assets/img/treasure_data/cohort/cohort3.png
  assets/img/treasure_data/cohort/cohort4.png
Labels: cla-signed, Deploy

#7390 [DLK-1848] add faqs for CDI and data sharing
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake/faqs.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/faqs.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
Labels: cla-signed

#7378 BD-3111 WhatsApp opt-in/opt-out flow
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/opt-ins_and_opt-outs.md
  assets/img/whatsapp/campaigns_webhook_url.png
  assets/img/whatsapp/message_step.png
  assets/img/whatsapp/request_parameters.png
  assets/img/whatsapp/user_update.png
  assets/img/whatsapp/webhook_step.png
  assets/img/whatsapp/webhook_url.png
  assets/img/whatsapp/whatsapp_inbound_message.png
Labels: cla-signed

#7399 Update appboyBridge.md
  _includes/archive/appboyBridge.md
Labels: cla-signed

#7402 Adding batch request example to api_limits.md
  _docs/_api/api_limits.md
Labels: cla-signed

#7357 BD-3108 Movable Ink Dynamic SMS Link Preview
  _docs/_partners/message_personalization/dynamic_content/movable_ink/dynamic_sms_link.md
  assets/img/movable_ink/android_automatic.png
  assets/img/movable_ink/android_tap.png
  assets/img/movable_ink/ios_example.png
  assets/img/movable_ink/ios_link.png
  assets/img/movable_ink/ios_message.png
  assets/img/movable_ink/ios_test_launch.png
Labels: cla-signed

#7403 Fix typo in Message Archiving Docs
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
Labels: cla-signed

#7405 Add dispatch_id to missing Content card events
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#7414 BD-3134: Remove sentence
  _docs/_user_guide/engagement_tools/segments/user_profiles/duplicate_users.md
Labels: cla-signed

#7415 BD-3133: Update Azure storage requirements
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/microsoft_azure_blob_storage_for_currents.md
Labels: cla-signed

#7411 May 28, 2024 release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2024.md
  _docs/_help/release_notes/2024/5_28_24.md
Labels: cla-signed

#7423 Update email_settings.md
  _docs/_user_guide/administrative/app_settings/email_settings.md
Labels: cla-signed

#7421 Update 2024.md
  _docs/_help/release_notes/2024.md
Labels: cla-signed

#7424 Update April icons
  _docs/_help/release_notes/2024.md
Labels: cla-signed

#7416 BD-3125: SMS/MMS best practices
  _docs/_user_guide/message_building_by_channel/sms/best_practices.md
  _docs/_user_guide/message_building_by_channel/sms/best_practices/best_practices.md
  _docs/_user_guide/privacy_portal.md
Labels: cla-signed

#7398 Update migrating_to_firebase_cloud_messaging.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/migrating_to_firebase_cloud_messaging.md
Labels: cla-signed

#7425 BD-3140: Remove linked article
  _docs/_user_guide/administrative/privacy/spam_regulations.md
Labels: cla-signed

#7426 BD-3139: Update "Meta Resources" with recent changes
  _docs/_user_guide/message_building_by_channel/whatsapp/meta_resources.md
Labels: cla-signed

#7406 Update treasuredata.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/treasuredata.md
  assets/img/treasure_data/cohort/cohort5.png
Labels: cla-signed

#7427 Catalog field and selection endpoints EA
  _docs/_api/endpoints/catalogs.md
  _docs/_api/endpoints/catalogs/catalog_fields.md
  _docs/_api/endpoints/catalogs/catalog_fields/asynchronous.md
  _docs/_api/endpoints/catalogs/catalog_fields/asynchronous/delete_catalog_field.md
  _docs/_api/endpoints/catalogs/catalog_fields/asynchronous/post_create_catalog_fields.md
  _docs/_api/endpoints/catalogs/catalog_selections.md
  _docs/_api/endpoints/catalogs/catalog_selections/asynchronous.md
  _docs/_api/endpoints/catalogs/catalog_selections/asynchronous/delete_catalog_selection.md
  _docs/_api/endpoints/catalogs/catalog_selections/asynchronous/post_create_catalog_selections.md
  _docs/_api/home.md
  _includes/rate_limits.md
Labels: cla-signed

#7428 Deploy pt. 2 - May 29, 2024
  _docs/_api/endpoints/catalogs.md
  _docs/_api/endpoints/catalogs/catalog_fields.md
  _docs/_api/endpoints/catalogs/catalog_fields/asynchronous.md
  _docs/_api/endpoints/catalogs/catalog_fields/asynchronous/delete_catalog_field.md
  _docs/_api/endpoints/catalogs/catalog_fields/asynchronous/post_create_catalog_fields.md
  _docs/_api/endpoints/catalogs/catalog_selections.md
  _docs/_api/endpoints/catalogs/catalog_selections/asynchronous.md
  _docs/_api/endpoints/catalogs/catalog_selections/asynchronous/delete_catalog_selection.md
  _docs/_api/endpoints/catalogs/catalog_selections/asynchronous/post_create_catalog_selections.md
  _docs/_api/home.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/migrating_to_firebase_cloud_messaging.md
  _docs/_help/release_notes/2024.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/treasuredata.md
  _docs/_user_guide/administrative/app_settings/email_settings.md
  _docs/_user_guide/administrative/privacy/spam_regulations.md
  _docs/_user_guide/message_building_by_channel/sms/best_practices.md
  _docs/_user_guide/message_building_by_channel/sms/best_practices/best_practices.md
  _docs/_user_guide/message_building_by_channel/whatsapp/meta_resources.md
  _docs/_user_guide/privacy_portal.md
  _includes/rate_limits.md
  assets/img/treasure_data/cohort/cohort5.png
Labels: cla-signed, Deploy

#7430 fix scroll not registering
  assets/js/documents.js
Labels: cla-signed

#7429 BD-3113: Clarify detail on API keys and deleted user
  _docs/_api/basics.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/adding_users_to_your_dashboard.md
Labels: cla-signed

#7431 Remove wovn from docs
  _data/i18n.yml
  _includes/html_include.html
  _includes/wovn.html
  assets/js/documents.js
Labels: cla-signed

#7433 Fix default lang path
  assets/js/documents.js
Labels: cla-signed

#7434 BD-3131: Fix rate limit info
  _docs/_developer_guide/platform_integration_guides/swift/live_activities/faq.md
Labels: cla-signed

#7435 Leftover deploy - May 30, 2024
  .ruby-version
  Gemfile
  Gemfile.lock
  _data/i18n.yml
  _docs/_api/basics.md
  _docs/_developer_guide/platform_integration_guides/swift/live_activities/faq.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/adding_users_to_your_dashboard.md
  _includes/html_include.html
  _includes/wovn.html
  assets/js/documents.js
  vercel.json
Labels: Deploy

#7437 Update docs for ruby version 3.3.0
  README.md
  _docs/_contributing/home.md
Labels: cla-signed

#7438 BD-3128: SMS and WhatsApp Liquid properties for Canvas Flow GA
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
Labels: cla-signed

#7439 Fix catalog selection links
  _docs/_api/endpoints/catalogs.md
  _docs/_api/home.md
  _includes/rate_limits.md
Labels: cla-signed

#7441 Add japanese main pages
  _docs/_docs_pages/index.md
  _lang/ja/_api/home.md
  _lang/ja/_docs_pages/index.md
  _lang/ja/_user_guide/introduction.md
Labels: cla-signed

#7442 Leftover deploy pt. 2 - May 31, 2024
  README.md
  _docs/_api/endpoints/catalogs.md
  _docs/_api/home.md
  _docs/_contributing/home.md
  _docs/_docs_pages/index.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
  _includes/rate_limits.md
  _lang/ja/_api/home.md
  _lang/ja/_docs_pages/index.md
  _lang/ja/_user_guide/introduction.md
Labels: cla-signed, Deploy

#7443 Allow jp partners url
  _plugins/alloy_partner.rb
Labels: cla-signed

#7444 Fix api description
  _lang/ja/_api/home.md
Labels: cla-signed

#7436 BD-3141: Update external WhatsApp links
  _docs/_user_guide/message_building_by_channel/whatsapp/overview.md
Labels: cla-signed

#7445 BD-3127: Update Snowflake image
  assets/img/inbound-data-share.png
Labels: cla-signed

#7432 fcm docs
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/migrating_to_firebase_cloud_messaging.md
Labels: cla-signed

#7447 BD-3138: Expected behavior for updated email address
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed
