Repository braze-inc/braze-docs, pull requests merged in 2024-06, with the labels that each got.

#7400 Update html_in-app_messages.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize/html_in-app_messages.md
Labels: cla-signed

#7407 Add clarifying note for iOS push action buttons
  _docs/_developer_guide/platform_integration_guides/swift/push_notifications/customization/action_buttons.md
Labels: cla-signed

#7451 Clarifying updates to Cordova push documentation
  _docs/_developer_guide/platform_integration_guides/cordova/push_notifications.md
Labels: cla-signed

#7454 BD-3124: Clarify time zone as UTC
  _docs/_api/endpoints/messaging/schedule_messages/post_schedule_messages.md
Labels: cla-signed

#7455 BD-3137: Add EU domain detail
  _docs/_user_guide/administrative/access_braze/single_sign_on/set_up.md
Labels: cla-signed

#7456 BD-3154: Engagement by Device for Email Insights dashboard GA
  _docs/_hidden/private_betas/email_insights.md
  _docs/_user_guide/data_and_analytics/analytics/email_performance_dashboard.md
  assets/img/engagement_by_device_type_proxy.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#7457 BD-3148: Clarify details for schedule object
  _docs/_api/objects_filters/schedule_object.md
Labels: cla-signed

#7458 BD-3070 pt1 changing example to use case when appropriate
  _docs/_help/help_articles/campaigns_and_canvas/more_people_in_control_group.md
  _docs/_hidden/misc_reference/x-in-y-behavior.md
  _docs/_hidden/private_betas/ai_step.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/treasuredata.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/adobe/adobe.md
  _docs/_partners/data_and_infrastructure_agility/support/pypestream.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/friendbuy.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/voucherify/voucherify_fetching_data_through_braze_connected_content.md
  _docs/_partners/message_orchestration/channel_extensions/surveys/typeform.md
  _docs/_partners/message_personalization/dynamic_content/amazon_personalize/amazon_personalize.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/teams.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
  _docs/_user_guide/data_and_analytics/custom_data/events.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/reeligibility.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/new_features.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties/canvas_persistent_entry_properties.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/preview_user_paths.md
  _docs/_user_guide/engagement_tools/canvas/get_started/the_basics.md
  _docs/_user_guide/getting_started/users_segments.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize/html_in-app_messages.md
  _docs/_user_guide/message_building_by_channel/sms/sms_setup/user_data_migration.md
  _docs/_user_guide/onboarding_faq.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md
  _lang/ja/_user_guide/data_and_analytics/custom_data/events.md
Labels: cla-signed

#7308 BD-2759 Add canvas_entry_properties use cases
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
Labels: cla-signed

#7452 [MOPS-3125] Update docs with correct fields
  _docs/_help/help_articles/api/attribute_name_id_across_sources.md
Labels: cla-signed

#7459 Add bounces to email metrics table and FAQ detail
  _docs/_user_guide/administrative/app_settings/email_settings.md
  _includes/campaign_analytics.md
Labels: cla-signed

#7461 BD-3129: Update FAQ
  _docs/_partners/canvas_steps/facebook_audience_sync.md
Labels: cla-signed

#7462 BD-3070 pt2 Change sample to example
  _docs/_api/endpoints/export/user_data/post_users_global_control_group.md
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/content_cards/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/in-app_messaging/implementation_guide.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/push_notifications/customization/rich_notifications.md
  _docs/_developer_guide/platform_integration_guides/unity/Analytics/logging_purchases.md
  _docs/_developer_guide/platform_integration_guides/unity/Analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md
  _docs/_hidden/archive_docs/product_request_example.md
  _docs/_hidden/archived_layouts/api_glossary.md
  _docs/_partners/data_and_infrastructure_agility/analytics/looker.md
  _docs/_partners/message_personalization/dynamic_content/movable_ink/customer_data_api.md
  _docs/_user_guide/engagement_tools/segments/segment_funnels.md
  _docs/_user_guide/engagement_tools/segments/segment_insights.md
Labels: cla-signed

#7422 Move in-app_messaging.md to Swift SDK section
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/tvos/content_cards.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/tvos/in-app_messaging.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/integration.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/tvos.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/tvos.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#7474 Deploy pt. 2 - June 5, 2024
  _docs/_hidden/other/sms_country_blocklist.md
Labels: cla-signed, Deploy

#7468 Update ja home pages for help and partners
  _lang/ja/_help/home.md
  _lang/ja/_partners/home.md
Labels: cla-signed

#7464 BD-3044: Push subscription states
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
Labels: cla-signed

#7417 Personalized Paths in recurring Canvases
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/personalized_paths.md
  assets/img/experiment_step/experiment_personalized_recurring_analytics.png
Labels: cla-signed

#7475 SMS traffic pumping fraud FAQ
  _docs/_hidden/private_betas/sms_traffic_pumping_fraud.md
Labels: cla-signed

#7477 Deploy pt. 3 - June 5, 2024
  _docs/_hidden/private_betas/sms_traffic_pumping_fraud.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/personalized_paths.md
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
  _lang/ja/_help/home.md
  _lang/ja/_partners/home.md
  assets/img/experiment_step/experiment_personalized_recurring_analytics.png
Labels: cla-signed, Deploy

#7479 BD-3157 Update Query Builder screenshot
  _docs/_user_guide/data_and_analytics/query_builder.md
  assets/img_archive/query_builder.png
Labels: cla-signed

#7471 Change jp to ja
  _includes/header.html
Labels: cla-signed

#7481 Add feature flag segmentation docs & use case
  _docs/_developer_guide/platform_wide/feature_flags/about.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/feature_flags.md
  assets/img/feature_flags/feature-flags-filter-name.png
  assets/img/feature_flags/feature-flags-filter-selection.png
  assets/img/feature_flags/feature_flag_segmentation_filter.png
Labels: cla-signed

#7482 iOS 18
  _docs/_developer_guide/platform_integration_guides/swift/archived_updates/ios_14.md
  _docs/_developer_guide/platform_integration_guides/swift/archived_updates/ios_15.md
  _docs/_developer_guide/platform_integration_guides/swift/archived_updates/ios_16.md
  _docs/_developer_guide/platform_integration_guides/swift/archived_updates/ios_17.md
  _docs/_developer_guide/platform_integration_guides/swift/ios_18.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#7483 Leftover deploy - June 6, 2024
  _docs/_developer_guide/platform_integration_guides/swift/archived_updates/ios_14.md
  _docs/_developer_guide/platform_integration_guides/swift/archived_updates/ios_15.md
  _docs/_developer_guide/platform_integration_guides/swift/archived_updates/ios_16.md
  _docs/_developer_guide/platform_integration_guides/swift/archived_updates/ios_17.md
  _docs/_developer_guide/platform_integration_guides/swift/ios_18.md
  _docs/_developer_guide/platform_wide/feature_flags/about.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
  _docs/_hidden/private_betas/sms_traffic_pumping_fraud.md
  _docs/_user_guide/data_and_analytics/query_builder.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/feature_flags.md
  _includes/header.html
  assets/img/feature_flags/feature-flags-filter-name.png
  assets/img/feature_flags/feature-flags-filter-selection.png
  assets/img/feature_flags/feature_flag_segmentation_filter.png
  assets/img_archive/query_builder.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#7484 BD-3149 Update Content Card expiration docs
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_by_channel/content-cards_in_canvas.md
  _docs/_user_guide/message_building_by_channel/content_cards/create/card_creation.md
Labels: cla-signed

#7301 BD-3037: Message Credits hidden doc - MERGE 6/10
  _docs/_hidden/pricing/message_credits_lambda_k5gh.md
Labels: cla-signed

#7465 BD-3155: Update Message Credit pages - MERGE 6/10
  _docs/_hidden/pricing/message_credits_delta_a3sy.md
  _docs/_hidden/pricing/message_credits_gamma_0dhr.md
  _docs/_hidden/pricing/message_credits_sigma_pow2.md
  _docs/_hidden/pricing/message_credits_theta_d9kw.md
Labels: cla-signed

#7488 BD-3162 Fix Liquid use case
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
Labels: cla-signed

#7493 Small edit for translation clarity
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/search_campaigns.md
Labels: cla-signed

#7494 Update copying campaigns based on translation feedback
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/copying_to_workspace.md
Labels: cla-signed

#7495 Update copying_to_workspace.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/copying_to_workspace.md
Labels: cla-signed

#7492 Update table for Message Credits
  _docs/_hidden/pricing/message_credits_lambda_k5gh.md
Labels: cla-signed

#7499 BD-3168 Update BlueConic docs with credentials info
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/blueconic.md
Labels: cla-signed

#7500 BD-3163: Add list-unsubscribe source for subscription event
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#7501 BD-3169: Add tiles to Privacy Portal
  _docs/_user_guide/privacy_portal.md
Labels: cla-signed

#7502 Deploy - June 11, 2024
  _docs/_hidden/pricing/message_credits_lambda_k5gh.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/blueconic.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/copying_to_workspace.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/search_campaigns.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
  _docs/_user_guide/privacy_portal.md
Labels: cla-signed, Deploy

#7504 [MP-4766] Update `no_cache` docs
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
Labels: cla-signed

#7496 [DLK-1665] Add Big Query and Data bricks SQL commands
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md
Labels: cla-signed

#7506 Update event_delivery_semantics.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
Labels: cla-signed

#7508 BD-3172 Update AI item recommendation event property requirements
  _docs/_user_guide/sage_ai/recommendations/ai_item_recommendations.md
Labels: cla-signed

#7401 BD-3101: Liquid highlighting - MERGE 6/13
  _docs/_user_guide/personalization_and_dynamic_content/liquid.md
  assets/img/liquid_color_code.png
Labels: cla-signed

#7509 Add EA banner for PUWYLO
  _docs/_hidden/private_betas/pick_up_where_you_left_off.md
Labels: cla-signed

#7489 BD-2899: Field-level encryption beta - MERGE 6/13
  _docs/_hidden/private_betas/field_level_encryption.md
  assets/img/field_level_encryption.png
  assets/img/field_level_encryption_aws_prereq.png
Labels: cla-signed

#7485 Update docs for new CDI Segment sources
  _docs/_user_guide/data_and_analytics/cloud_ingestion/connected_sources.md
  _docs/_user_guide/engagement_tools/segments/segment_extension/cdi_segments.md
  assets/img/cloud_ingestion/connected_source_3.png
  assets/img/cloud_ingestion/connected_source_bq_1.png
  assets/img/cloud_ingestion/connected_source_db_1.png
  assets/img/cloud_ingestion/connected_source_rs_1.png
Labels: cla-signed

#7512 Deploy pt 2 - June 12, 2024
  _docs/_hidden/private_betas/field_level_encryption.md
  _docs/_hidden/private_betas/pick_up_where_you_left_off.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/connected_sources.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md
  _docs/_user_guide/data_and_analytics/custom_data/managing_custom_data.md
  _docs/_user_guide/engagement_tools/segments/segment_extension/cdi_segments.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid.md
  _docs/_user_guide/sage_ai/recommendations/ai_item_recommendations.md
  assets/img/cloud_ingestion/connected_source_3.png
  assets/img/cloud_ingestion/connected_source_bq_1.png
  assets/img/cloud_ingestion/connected_source_db_1.png
  assets/img/cloud_ingestion/connected_source_rs_1.png
  assets/img/field_level_encryption.png
  assets/img/field_level_encryption_aws_prereq.png
  assets/img/liquid_color_code.png
  assets/img/pick_up_where_you_left_off.png
Labels: cla-signed, Deploy

#7514 Update event_delivery_semantics.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
Labels: cla-signed

#7516 email_encrypted not encrypted_email
  _docs/_hidden/private_betas/field_level_encryption.md
Labels: cla-signed

#7511 Message Archiving to message archiving
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
Labels: cla-signed

#7517 BD-3172 Fix AI item recommendations nested properties
  _docs/_user_guide/sage_ai/recommendations/ai_item_recommendations.md
Labels: cla-signed

#7469 Update tvos.md
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/tvos.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/tvos.md
Labels: cla-signed

#7497 Update crowdin.md
  _docs/_partners/message_personalization/localization/crowdin.md
Labels: cla-signed

#7519 BD-3130: Clarify two messages promotion codes
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
Labels: cla-signed

#7521 Leftover deploy - June 13, 2024
  _docs/_developer_guide/platform_integration_guides/swift/content_cards/tvos.md
  _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/tvos.md
  _docs/_hidden/private_betas/field_level_encryption.md
  _docs/_partners/message_personalization/localization/crowdin.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
  _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
  _docs/_user_guide/sage_ai/recommendations/ai_item_recommendations.md
Labels: cla-signed, Deploy

#7518 BD-3176 WhatsApp supports more than one subscription group per workspace
  _docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
Labels: cla-signed

#7520 BD-3175 Add translation note to AI copywriting assistant and exclusio…
  _docs/_user_guide/sage_ai/generative_ai/ai_copywriting/brand_guidelines.md
Labels: cla-signed

#7524 Updated /campaigns/trigger/send docs to include newly supported attachments feature
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
Labels: cla-signed

#7523 BD-2968: Help article for tracking push unsubscribes
  _docs/_help/help_articles/push.md
  _docs/_help/help_articles/push/push_unsubscribes.md
  _includes/campaign_analytics.md
  assets/img/push_unsub_segment_example.png
Labels: cla-signed

#7525 BD-3177: Minor Liquid highlight edits
  _docs/_user_guide/personalization_and_dynamic_content/liquid.md
  assets/img/liquid_auto_complete.gif
Labels: cla-signed

#7526 Update triggered_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md
Labels: cla-signed

#7522 [DLK-1793] Updating troubleshooting tips for test connection
  _docs/_user_guide/data_and_analytics/cloud_ingestion/faqs.md
Labels: cla-signed

#7532 Update header for consistency
  _docs/_api/use_cases.md
Labels: cla-signed

#7533 BD-3059: Canvas target audience clarifications
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
Labels: cla-signed

#7534 BD-3150: Add alert for subscription status
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/attribute_triggers.md
Labels: cla-signed

#7535 BD-3171: Add detail on deleting Canvas step and Engagement Reports
  _docs/_user_guide/data_and_analytics/reporting/engagement_reports.md
Labels: cla-signed

#7513 Brand refresh tweaks
  _docs/_hidden/other/support_contact.md
  _layouts/api_glossary.html
  _layouts/self_help.html
  assets/css/_404.scss
  assets/css/_bottom_nav.scss
  assets/css/_content.scss
  assets/css/_dev_guide.scss
  assets/css/_doc_guide.scss
  assets/css/_footer.scss
  assets/css/_glossary_page.scss
  assets/css/_partner_page.scss
  assets/css/_self_help.scss
  assets/css/_toc.scss
  assets/css/_user_guide.scss
  assets/css/swipercustom.scss
  assets/js/documents.js
Labels: cla-signed

#7540 Update offerfit.md
  _docs/_partners/message_personalization/dynamic_content/offerfit.md
Labels: cla-signed

#7541 Remove extraneous line
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
Labels: cla-signed

#7542 Update user_update.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
Labels: cla-signed

#7543 Update mparticle_for_currents.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md
Labels: cla-signed

#7544 BD-2781 Add Segments troubleshooting article
  _docs/_user_guide/engagement_tools/segments.md
  _docs/_user_guide/engagement_tools/segments/troubleshooting.md
Labels: cla-signed

#7537 Update sdk_primer.md
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
Labels: cla-signed

#7539 Update personalized_paths.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/personalized_paths.md
Labels: cla-signed

#7529 Update revenue_report.md
  _docs/_user_guide/data_and_analytics/reporting/revenue_report.md
Labels: cla-signed

#7545 BD-3183 Update email settings warning
  _docs/_api/api_campaigns.md
  _docs/_user_guide/administrative/app_settings/email_settings.md
Labels: cla-signed

#7528 Update purchase_events.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
Labels: cla-signed

#7515 BD-3167: Track user sync beta - MERGE 6/18
  _docs/_hidden/private_betas/post_user_track_synchronous.md
Labels: cla-signed

#7527 Update reeligibility.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/reeligibility.md
Labels: cla-signed

#7547 Update images.md
  _docs/_contributing/content_management/images.md
Labels: cla-signed

#7546 Request page changes
  _docs/_hidden/other/documentation_request.md
Labels: cla-signed

#7548 Deploy - June 18, 2024
  _docs/_api/api_campaigns.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
  _docs/_api/use_cases.md
  _docs/_contributing/content_management/images.md
  _docs/_developer_guide/platform_integration_guides/sdk_primer.md
  _docs/_help/help_articles/push.md
  _docs/_help/help_articles/push/push_unsubscribes.md
  _docs/_hidden/other/documentation_request.md
  _docs/_hidden/other/support_contact.md
  _docs/_hidden/private_betas/post_user_track_synchronous.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md
  _docs/_partners/message_personalization/dynamic_content/offerfit.md
  _docs/_user_guide/administrative/app_settings/email_settings.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/faqs.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _docs/_user_guide/data_and_analytics/reporting/engagement_reports.md
  _docs/_user_guide/data_and_analytics/reporting/revenue_report.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/reeligibility.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/attribute_triggers.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/personalized_paths.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/segments.md
  _docs/_user_guide/engagement_tools/segments/troubleshooting.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid.md
  _docs/_user_guide/sage_ai/generative_ai/ai_copywriting/brand_guidelines.md
  _includes/campaign_analytics.md
  _layouts/api_glossary.html
  _layouts/self_help.html
  assets/css/_404.scss
  assets/css/_bottom_nav.scss
  assets/css/_content.scss
  assets/css/_dev_guide.scss
  assets/css/_doc_guide.scss
  assets/css/_footer.scss
  assets/css/_glossary_page.scss
  assets/css/_partner_page.scss
  assets/css/_self_help.scss
  assets/css/_toc.scss
  assets/css/_user_guide.scss
  assets/css/swipercustom.scss
  assets/img/liquid_auto_complete.gif
  assets/img/push_unsub_segment_example.png
  assets/js/documents.js
Labels: cla-signed, Deploy

#7550 Renaming 'messaging' to 'instant_chat' for partners
  _docs/_partners/message_orchestration/additional_channels/instant_chat.md
  _docs/_partners/message_orchestration/additional_channels/instant_chat/line.md
  _docs/_partners/message_orchestration/additional_channels/instant_chat/messenger.md
  _docs/_partners/message_orchestration/additional_channels/instant_chat/regal.md
  _docs/_partners/message_orchestration/additional_channels/instant_chat/sendbird.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#7551 Update docs for test connectors
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
Labels: cla-signed

#7554 BD-3120 Add clarity to billing tables
  _docs/_user_guide/administrative/app_settings/subscription_and_usage.md
Labels: cla-signed

#7491 [DI-6248] Update event documentation
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#7557 BD-3185 Add SMS Geographic Permissions Allowlist article
  _docs/_hidden/private_betas/sms_geographic_permissions.md
  assets/img/sms/abort_log.png
  assets/img/sms/allowlist_dropdown.png
  assets/img/sms/delete_allowlist_warning.png
  assets/img/sms/high_risk.png
  assets/img/sms/sms_geographic_permissions.png
Labels: cla-signed

#7558 Leftover Deploy - June 20, 2024
  _docs/_hidden/private_betas/sms_geographic_permissions.md
  _docs/_partners/message_orchestration/additional_channels/instant_chat.md
  _docs/_partners/message_orchestration/additional_channels/instant_chat/line.md
  _docs/_partners/message_orchestration/additional_channels/instant_chat/messenger.md
  _docs/_partners/message_orchestration/additional_channels/instant_chat/regal.md
  _docs/_partners/message_orchestration/additional_channels/instant_chat/sendbird.md
  _docs/_user_guide/administrative/app_settings/subscription_and_usage.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
  assets/img/sms/abort_log.png
  assets/img/sms/allowlist_dropdown.png
  assets/img/sms/delete_allowlist_warning.png
  assets/img/sms/high_risk.png
  assets/img/sms/sms_geographic_permissions.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#7392 Update dashboard_builder.md
  _docs/_hidden/private_betas/dashboard_builder.md
Labels: cla-signed

#7487 Update conversions_dashboard.md
  _docs/_user_guide/data_and_analytics/analytics/conversions_dashboard.md
Labels: cla-signed

#7562 Tiffanyjlin patch 2
  _docs/_hidden/private_betas/field_level_encryption.md
Labels: cla-signed

#7556 Update treasuredata.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/treasuredata.md
  assets/img/treasure_data/cohort/cohort6.png
  assets/img/treasure_data/cohort/cohort7.png
  assets/img/treasure_data/cohort/cohort8.png
Labels: cla-signed

#7555 BD-3184 Shopify checkout.liquid deprecation
  _docs/_help/release_notes/deprecations.md
  _docs/_help/release_notes/deprecations/shopify_checkout.md
Labels: cla-signed

#7560 BD-3192 WhatsApp phone number migration
  _docs/_user_guide/message_building_by_channel/whatsapp/overview/phone_number_migration.md
  assets/img/whatsapp/phone_numbers.png
Labels: cla-signed

#7564 [PP][NOTIX] fix indents on page
  _docs/_help/release_notes/deprecations/shopify_checkout.md
Labels: cla-signed

#7553 CO-2650 CO-2735 Add custom data dictionary documentation.
  _docs/_api/endpoints/export.md
  _docs/_api/endpoints/export/custom_attributes.md
  _docs/_api/endpoints/export/custom_attributes/get_custom_attributes.md
  _docs/_api/endpoints/export/custom_events/get_custom_events_data.md
  _docs/_api/home.md
  _docs/_user_guide/administrative/app_settings/tags.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _includes/rate_limits.md
Labels: cla-signed

#7561 June Release Notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2024.md
  _docs/_help/release_notes/2024/6_25_24.md
  assets/img/braze-docs-japan.png
Labels: cla-signed

#7567 Leftover deploy pt 2 - June 25, 2024
  _docs/_api/endpoints/export.md
  _docs/_api/endpoints/export/custom_attributes.md
  _docs/_api/endpoints/export/custom_attributes/get_custom_attributes.md
  _docs/_api/endpoints/export/custom_events/get_custom_events_data.md
  _docs/_api/home.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2024.md
  _docs/_help/release_notes/2024/6_25_24.md
  _docs/_help/release_notes/deprecations.md
  _docs/_help/release_notes/deprecations/shopify_checkout.md
  _docs/_hidden/private_betas/dashboard_builder.md
  _docs/_hidden/private_betas/field_level_encryption.md
  _docs/_hidden/private_betas/idle_campaigns.md
  _docs/_partners/data_and_infrastructure_agility/cohort_import/treasuredata.md
  _docs/_partners/message_orchestration/additional_channels/instant_chat/front.md
  _docs/_user_guide/administrative/app_settings/tags.md
  _docs/_user_guide/data_and_analytics/analytics/conversions_dashboard.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
  _docs/_user_guide/message_building_by_channel/whatsapp/overview/phone_number_migration.md
  _includes/rate_limits.md
  assets/img/braze-docs-japan.png
  assets/img/front/braze_delivery.png
  assets/img/front/braze_reeligibility.png
  assets/img/front/custom_event_trigger.png
  assets/img/front/data_transformation.png
  assets/img/front/front_actionbased_keyword.png
  assets/img/front/front_actionbased_other_keyword.png
  assets/img/front/front_custom_channel.png
  assets/img/front/front_custom_channel2.png
  assets/img/front/front_keyword.png
  assets/img/front/front_segment_last_received_message.png
  assets/img/front/front_target_audience.png
  assets/img/front/sms_to_braze.png
  assets/img/front/sms_to_front.png
  assets/img/front/webhook_settings.png
  assets/img/treasure_data/cohort/cohort6.png
  assets/img/treasure_data/cohort/cohort7.png
  assets/img/treasure_data/cohort/cohort8.png
  assets/img/whatsapp/phone_numbers.png
Labels: cla-signed

#7568 Update field_level_encryption.md
  _docs/_hidden/private_betas/field_level_encryption.md
Labels: cla-signed

#7569 Update header.html
  _includes/header.html
Labels: cla-signed

#7565 Update ios_18.md
  _docs/_developer_guide/platform_integration_guides/swift/ios_18.md
Labels: cla-signed

#7486 BD-3156 Landing pages beta
  _docs/_user_guide/engagement_tools/landing_pages.md
  _docs/_user_guide/engagement_tools/landing_pages/drag_and_drop.md
  assets/img/landing_pages/create.png
  assets/img/landing_pages/details.png
  assets/img/landing_pages/dnd.png
  assets/img/landing_pages/form.png
  assets/img/landing_pages/homepage.gif
  assets/img/landing_pages/page_container.png
  assets/img/landing_pages/template.png
  assets/img/landing_pages/url_handle.png
Labels: cla-signed

#7571 BD-3179: Add locales in messaging to strategies
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/localizing_a_campaign.md
Labels: cla-signed

#7573 Edits to idle campaigns and Canvases
  _docs/_hidden/private_betas/idle_campaigns.md
Labels: cla-signed

#7574 fix image names that got switched during PR review
  assets/img/cloud_ingestion/s3_ARN.png
  assets/img/cloud_ingestion/s3_find_account.png
Labels: cla-signed

#7575 Fix js punctuation error
  assets/js/documents.js
Labels: cla-signed

#7576 Update tealium.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
Labels: cla-signed

#7577 BD-3198 Add user sample size to support doc
  _docs/_help/support.md
Labels: cla-signed

#7578 BD-3204 Update revenue metric definitions
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _docs/_user_guide/data_and_analytics/reporting/revenue_report.md
Labels: cla-signed

#7566 [CO-2720] Added catalog liquid templating document
  _docs/_hidden/private_betas/template_catalog_item_liquid.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  assets/img_archive/catalog_liquid_templating.png
Labels: cla-signed

#7572 Update ip_warming.md
  _docs/_user_guide/message_building_by_channel/email/email_setup/ip_warming.md
Labels: cla-signed

#7579 BD-3203: Fix rate limit
  _docs/_api/api_limits.md
  _includes/rate_limits.md
Labels: cla-signed

#7580 Deploy - June 25, 2024
  _docs/_api/api_limits.md
  _docs/_developer_guide/platform_integration_guides/swift/ios_18.md
  _docs/_help/support.md
  _docs/_hidden/private_betas/field_level_encryption.md
  _docs/_hidden/private_betas/idle_campaigns.md
  _docs/_hidden/private_betas/template_catalog_item_liquid.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
  _docs/_user_guide/data_and_analytics/reporting/revenue_report.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/localizing_a_campaign.md
  _docs/_user_guide/engagement_tools/landing_pages.md
  _docs/_user_guide/engagement_tools/landing_pages/drag_and_drop.md
  _docs/_user_guide/message_building_by_channel/email/email_setup/ip_warming.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _includes/header.html
  _includes/rate_limits.md
  assets/img/cloud_ingestion/s3_ARN.png
  assets/img/cloud_ingestion/s3_find_account.png
  assets/img/landing_pages/create.png
  assets/img/landing_pages/details.png
  assets/img/landing_pages/dnd.png
  assets/img/landing_pages/form.png
  assets/img/landing_pages/homepage.gif
  assets/img/landing_pages/page_container.png
  assets/img/landing_pages/template.png
  assets/img/landing_pages/url_handle.png
  assets/img_archive/catalog_liquid_templating.png
  assets/js/documents.js
Labels: cla-signed, Deploy

#7582 BD-3196: Add troubleshooting tip for diagnostic logs
  _docs/_help/help_articles/campaigns_and_canvas.md
  _docs/_help/help_articles/campaigns_and_canvas/canvas_not_sending.md
  _docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
  _docs/_help/help_articles/campaigns_and_canvas/not_triggering.md
  _docs/_user_guide/engagement_tools/campaigns/faq.md
  _docs/_user_guide/engagement_tools/canvas/faqs.md
Labels: cla-signed

#7583 BD-3205: Update creating API key steps
  _docs/_api/basics.md
Labels: cla-signed

#7584 Add raw tags and use escape code for period
  _docs/_help/release_notes/deprecations/shopify_checkout.md
Labels: cla-signed

#7585 Deploy pt. 2 - June 25, 2024
  _docs/_api/basics.md
  _docs/_help/help_articles/campaigns_and_canvas.md
  _docs/_help/help_articles/campaigns_and_canvas/canvas_not_sending.md
  _docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
  _docs/_help/help_articles/campaigns_and_canvas/not_triggering.md
  _docs/_help/release_notes/deprecations/shopify_checkout.md
  _docs/_user_guide/engagement_tools/campaigns/faq.md
  _docs/_user_guide/engagement_tools/canvas/faqs.md
Labels: Deploy

#7586 Fix link not rendering properly
  _docs/_developer_guide/platform_integration_guides/web/analytics/tracking_custom_events.md
Labels: cla-signed

#7587 Update best practices links
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md
Labels: cla-signed

#7588 BD-3201: Add sending info steps to HTML email article
  _docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md
Labels: cla-signed

#7591 BD-3123: Add considerations section for merge behavior
  _docs/_api/endpoints/user_data/post_users_merge.md
Labels: cla-signed, In Review

#7595 Fix blank link reference
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_user_identity.md
Labels: cla-signed

#7598 Add back callout for Liquid in catalog
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
Labels: cla-signed

#7594 Update ios_18.md
  _docs/_developer_guide/platform_integration_guides/swift/ios_18.md
Labels: cla-signed

#7593 add feature flags to ott
  _docs/_developer_guide/platform_integration_guides/tv_and_ott.md
Labels: cla-signed

#7581 docs(react-native): clarify `getContentCards()` vs. `requestContentCardsRefresh()`
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
Labels: cla-signed

#7599 docs(react-native): clarify 'control card' impression logging
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
Labels: cla-signed

#7590 BD-3197: Clarify audience stats and reachable users
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/targeting_users.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
Labels: cla-signed

#7600 Add list-unsubscribe for property details
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#7601 BD-3126: Add note on one-click list-unsubscribe
  _docs/_user_guide/message_building_by_channel/email/transactional_message_api_campaign.md
Labels: cla-signed

#7604 Revised edit for transactional email and one-click list-unsub
  _docs/_user_guide/message_building_by_channel/email/transactional_message_api_campaign.md
Labels: cla-signed

#7602 BD-3212: Add more details for action-based delivery FAQ
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md
Labels: cla-signed

#7606 Leftover Deploy - June 27, 2024
  _docs/_api/endpoints/user_data/post_users_merge.md
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
  _docs/_developer_guide/platform_integration_guides/swift/ios_18.md
  _docs/_developer_guide/platform_integration_guides/tv_and_ott.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/tracking_custom_events.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_user_identity.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/targeting_users.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/email/transactional_message_api_campaign.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
Labels: cla-signed, Deploy

#7592 Make very large image smaller
  _docs/_developer_guide/platform_integration_guides/web/analytics/tracking_sessions.md
Labels: cla-signed

#7607 BD-3191: Clarify how to add a background image
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/style_settings.md
Labels: cla-signed
