Repository braze-inc/braze-docs, pull requests merged in 2024-04, with the labels that each got.

#7130 Update post_users_merge.md
  _docs/_api/endpoints/user_data/post_users_merge.md
Labels: cla-signed

#7123 BD-2931: Update description for global state change event
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#7098 BD-2949: Savings drafts for campaigns hidden doc - MERGE 4/2
  _docs/_hidden/private_betas/campaign_drafts.md
  assets/img/campaign_draft.png
Labels: cla-signed

#7131 Message Open Likelihood filter and related
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/sage_ai/intelligence/intelligent_channel.md
Labels: cla-signed

#7133 BD-2965: Update Braze tracking unsubscribe links detail
  _docs/_user_guide/message_building_by_channel/email/faq.md
Labels: cla-signed

#7134 AI Content QA in IAM
  _docs/_user_guide/sage_ai/generative_ai/ai_content_qa.md
Labels: cla-signed

#7136 BD-2962 and BD-2963: Add export entrants for Canvas detail
  _docs/_user_guide/data_and_analytics/export_braze_data/export_campaign_results_data.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_canvas_data.md
Labels: cla-signed

#7137 Updates to Campaign and Canvas Interactions Data for Data Retention doc
  _docs/_api/data_retention.md
Labels: cla-signed

#7132 BD-2956: API usage dashboard EA - MERGE 4/2
  _docs/_hidden/private_betas/api_usage_dashboard.md
  assets/img/api_usage_dashboard/api_usage_dashboard.png
  assets/img/api_usage_dashboard/filters.png
Labels: cla-signed

#7140 [CDI] Rename file_integrations.md to file_storage_integrations.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/file_storage_integrations.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#7138 BD-2967: Duplicate Canvases EA - MERGE 4/2
  _docs/_hidden/private_betas/post_duplicate_canvas.md
Labels: cla-signed

#7119 BD-2955 Targeting users with multiple devices - segments
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  assets/img_archive/send_to_last_device.png
Labels: cla-signed

#7011 [CO-2414] Add documentation for price drop notifications for catalogs - EA
  _docs/_hidden/private_betas/price_drop_notifications.md
  assets/img/price_drop_notifications.png
Labels: status: on hold / do not merge, cla-signed

#7144 Update permalink
  _docs/_hidden/private_betas/post_duplicate_canvas.md
Labels: cla-signed

#7145 Lowercase folder names
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/Using_Shopify/use_cases.md
Labels: cla-signed

#7146 Add Prerequisites section for Duplicate campaigns doc
  _docs/_api/endpoints/messaging/duplicate_campaigns.md
Labels: cla-signed

#7147 Renamed shopify folders
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_backfill.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs/back_in_stock.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_user_identity.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/using_shopify/shopify_data_in_braze.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/using_shopify/use_cases.md
Labels: cla-signed

#7148 BD-2974 Fix 404 error description
  _docs/_api/errors.md
Labels: cla-signed

#7128 April 2, 2024 release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2024.md
  _docs/_help/release_notes/2024/4_2_24.md
Labels: cla-signed

#7149 Deploy - April 2, 2024
  _docs/_api/data_retention.md
  _docs/_api/endpoints/messaging/duplicate_campaigns.md
  _docs/_api/endpoints/user_data/post_users_merge.md
  _docs/_api/errors.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2024.md
  _docs/_help/release_notes/2024/4_2_24.md
  _docs/_hidden/other/support_contact.md
  _docs/_hidden/private_betas/api_usage_dashboard.md
  _docs/_hidden/private_betas/campaign_drafts.md
  _docs/_hidden/private_betas/messaging_interaction_data.md
  _docs/_hidden/private_betas/post_duplicate_canvas.md
  _docs/_hidden/private_betas/price_drop_notifications.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_backfill.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs/back_in_stock.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_user_identity.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/using_shopify/shopify_data_in_braze.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/using_shopify/use_cases.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/file_storage_integrations.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_campaign_results_data.md
  _docs/_user_guide/data_and_analytics/export_braze_data/export_canvas_data.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/message_building_by_channel/email/faq.md
  _docs/_user_guide/sage_ai/generative_ai/ai_content_qa.md
  _docs/_user_guide/sage_ai/generative_ai/ai_copywriting.md
  _docs/_user_guide/sage_ai/intelligence/intelligent_channel.md
  assets/img/ai_copywriter/gpt3.png
  assets/img/api_usage_dashboard/api_usage_dashboard.png
  assets/img/api_usage_dashboard/filters.png
  assets/img/campaign_draft.png
  assets/img/price_drop_notifications.png
  assets/img_archive/send_to_last_device.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#6854 Revamping User Update step with aggregating examples
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
Labels: cla-signed

#7150 BD-2976: Fix typo
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md
Labels: cla-signed

#7153 Fix syntax typo in images.md
  _docs/_contributing/content_management/images.md
Labels: cla-signed

#7154 Update post_duplicate_canvas.md
  _docs/_hidden/private_betas/post_duplicate_canvas.md
Labels: cla-signed

#7156 Deploy pt. 2 - April 3, 2024
  _docs/_contributing/content_management/images.md
  _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md
  _docs/_hidden/private_betas/messaging_interaction_data.md
  _docs/_hidden/private_betas/post_duplicate_canvas.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
Labels: cla-signed, Deploy

#7157 BD-2935: Add note for FCM rate limit
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/migrating_to_firebase_cloud_messaging.md
Labels: cla-signed

#7142 Uploading Alpaco documentation
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/channel_extensions.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/alpaco.md
  assets/img/alpaco/alpaco_1.png
  assets/img/alpaco/alpaco_2.png
  assets/img/alpaco/alpaco_3.png
Labels: status: in progress, cla-signed, Braze Partnerships

#7162 Fixing some exposed liquid
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
Labels: cla-signed

#7163 Deploy pt. 3 - April 3, 2024
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/migrating_to_firebase_cloud_messaging.md
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/channel_extensions.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/alpaco.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
  assets/img/alpaco/alpaco_1.png
  assets/img/alpaco/alpaco_2.png
  assets/img/alpaco/alpaco_3.png
Labels: cla-signed

#6754 BD-2621: Creating Web SDK logging docs
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/other_sdk_customizations.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
Labels: cla-signed

#7161 BD-2969 Shopify data payloads updates
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/using_shopify/shopify_data_in_braze.md
  assets/img/Shopify/add_personalization_2.png
  assets/img/Shopify/copy_liquid_snippet.png
Labels: cla-signed

#7152 BD-2960 Correct Segmentation Filters for Purchase Behavior
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#7160 BD-2973 Hidden page for Dashboard Builder EA
  _docs/_hidden/private_betas/dashboard_builder.md
  assets/img/chart_type.png
  assets/img/drag_tile.png
  assets/img/sample_tile.png
Labels: cla-signed

#7168 BD-2980 Fix Shopify folder titlecase
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/using_shopify.md
Labels: cla-signed

#7170 Update message_engagement_events.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#7070 BD-2932: Update permission name and description - MERGE 4/4
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#7171 BD-2978: Update Braze Learning course links
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
Labels: cla-signed

#7175 BD-2986: Add alerts for empty fields for email open and email click events
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#7169 BD-2981: SDK versions for IAM message extras
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
Labels: cla-signed

#7173 Leftover deploy - April 4, 2024
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
  _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/other_sdk_customizations.md
  _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
  _docs/_hidden/private_betas/dashboard_builder.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/using_shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/using_shopify/shopify_data_in_braze.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
  assets/img/Shopify/add_personalization_2.png
  assets/img/Shopify/copy_liquid_snippet.png
  assets/img/chart_type.png
  assets/img/drag_tile.png
  assets/img/sample_tile.png
Labels: cla-signed, Deploy

#7176 Update query_builder.md
  _docs/_user_guide/data_and_analytics/query_builder.md
Labels: cla-signed

#7178 Update query_builder.md
  _docs/_user_guide/data_and_analytics/query_builder.md
Labels: cla-signed

#7179 BD-2987 Update SMS click events
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#7180 Update "end date" to "send date" where needed
  _docs/_hidden/private_betas/idle_campaigns.md
Labels: cla-signed

#7174 BD-2982 Update Shopify back-in-stock notifications article
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs/back_in_stock.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/back_in_stock_notifications.md
  assets/img/back_in_stock_settings.png
Labels: cla-signed

#7182 Revert deletion of email capture form
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs/back_in_stock.md
Labels: cla-signed

#7183 Remove Shopify email capture forms from back-in-stock
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs/back_in_stock.md
Labels: cla-signed

#7184 BD-2989 Braze retries webhook sends for up to 24 hrs
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
Labels: cla-signed

#7185 Update experiments.md
  _docs/_developer_guide/platform_wide/feature_flags/experiments.md
Labels: cla-signed

#7186 Update sdk_authentication.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
Labels: cla-signed

#7139 [SDK-3909] visionOS initial documentation
  _docs/_developer_guide/platform_integration_guides/swift/visionos.md
Labels: cla-signed

#7187 Update alpaco.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/alpaco.md
Labels: cla-signed

#7165 Update S3 documentation
  _docs/_user_guide/data_and_analytics/cloud_ingestion/file_storage_integrations.md
  assets/img/cloud_ingestion/s3_ARN.png
  assets/img/cloud_ingestion/s3_find_account.png
Labels: cla-signed

#7188 Added missing slash
  assets/js/broken_redirect_list.js
Labels: cla-signed

#7191 BD-2953 Add snapshots_canvas_flow_step to snowflake schema doc
  assets/download_file/data-sharing-raw-table-schemas.txt
Labels: cla-signed

#7193 Create braze_go.md
  _docs/_hidden/pricing/braze_go.md
Labels: cla-signed

#7194 Deploy - April 9, 2024
  _docs/_developer_guide/platform_integration_guides/swift/visionos.md
  _docs/_developer_guide/platform_wide/feature_flags/experiments.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
  _docs/_hidden/pricing/braze_go.md
  _docs/_hidden/private_betas/idle_campaigns.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs/back_in_stock.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/alpaco.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/file_storage_integrations.md
  _docs/_user_guide/data_and_analytics/query_builder.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/back_in_stock_notifications.md
  assets/download_file/data-sharing-raw-table-schemas.txt
  assets/img/back_in_stock_settings.png
  assets/img/cloud_ingestion/s3_ARN.png
  assets/img/cloud_ingestion/s3_find_account.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#7192 BD-2948: Update email message response example
  _docs/_api/endpoints/export/campaigns/get_campaign_details.md
Labels: cla-signed

#7172 Adding MetaRouter docs
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/metarouter.md
  assets/img/metarouter/img1.png
  assets/img/metarouter/img2.png
Labels: cla-signed, Braze Partnerships

#7197 Update data sharing schemas - 04/10/2024
  assets/download_file/data-sharing-raw-table-schemas.txt
Labels: cla-signed

#7196 [Trivial] Fix push subscription state iOS documentation link
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
Labels: cla-signed

#7198 MetaRouter Docs: Adding to landing pages
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation.md
  _docs/_partners/home.md
Labels: cla-signed, Braze Partnerships

#7200 BD-2990: Update CSV file section for catalogs
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
Labels: cla-signed

#7201 Updated with note about field latency
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#7203 BD-2997: Clarify list of scheduled campaigns and Canvases
  _docs/_api/endpoints/messaging/schedule_messages/get_messages_scheduled.md
Labels: cla-signed

#7158 Nifty Partner Docs
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content.md
  _docs/_partners/message_personalization/dynamic_content/niftyimages.md
  assets/img/niftyimages/1.png
  assets/img/niftyimages/2.png
  assets/img/niftyimages/3.png
  assets/img/niftyimages/4.png
  assets/img/niftyimages/5.png
  assets/img/niftyimages/6.png
Labels: cla-signed, Braze Partnerships

#7159 [SDK-4810] Flutter docs - Push Events in Dart layer
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/flutter/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
Labels: status: on hold / do not merge, cla-signed

#7205 Update create.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
Labels: cla-signed

#7164 Update background geofence documentation for iOS
  _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/locations_and_geofences.md
Labels: cla-signed

#7207 Leftover Deploy - April 11, 2024
  _docs/_api/endpoints/export/campaigns/get_campaign_details.md
  _docs/_api/endpoints/messaging/schedule_messages/get_messages_scheduled.md
  _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
  _docs/_developer_guide/platform_integration_guides/flutter/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platform_wide/feature_flags/create.md
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation.md
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/metarouter.md
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content.md
  _docs/_partners/message_personalization/dynamic_content/niftyimages.md
  _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  assets/download_file/data-sharing-raw-table-schemas.txt
  assets/img/metarouter/img1.png
  assets/img/metarouter/img2.png
  assets/img/niftyimages/1.png
  assets/img/niftyimages/2.png
  assets/img/niftyimages/3.png
  assets/img/niftyimages/4.png
  assets/img/niftyimages/5.png
  assets/img/niftyimages/6.png
Labels: cla-signed, Deploy

#7190 BD-2916 Add form inputs example response
  _docs/_api/endpoints/preference_center/post_create_preference_center.md
Labels: cla-signed

#7209 Small edit for post create preference center
  _docs/_api/endpoints/preference_center/post_create_preference_center.md
Labels: cla-signed

#7206 BD-3000: Braze Go article
  _docs/_hidden/pricing/braze_go.md
Labels: cla-signed

#7202 BD-2977 Create reference page for Query Builder templates
  _docs/_user_guide/data_and_analytics/query_builder.md
  _docs/_user_guide/data_and_analytics/query_builder/query_templates.md
  assets/img_archive/campaign_revenue_country.png
  assets/img_archive/canvas_revenue_country.png
  assets/img_archive/channel_engagement_revenue.png
  assets/img_archive/device_carriers.png
  assets/img_archive/device_models.png
  assets/img_archive/device_screen_resolutions.png
  assets/img_archive/email_delivery_day.png
  assets/img_archive/email_engagement_segment.png
  assets/img_archive/os_version.png
  assets/img_archive/sms_errors.png
  assets/img_archive/top-bottom-email.png
Labels: cla-signed

#7214 Minor style edits
  _docs/_api/endpoints/user_data/post_user_track.md
Labels: cla-signed

#7215 Deploy - April 14, 2024
  _docs/_api/endpoints/preference_center/post_create_preference_center.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_contributing/styling_examples.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/tracking_sessions.md
  _docs/_hidden/pricing/braze_go.md
  _docs/_user_guide/data_and_analytics/query_builder.md
  _docs/_user_guide/data_and_analytics/query_builder/query_templates.md
  assets/img_archive/campaign_revenue_country.png
  assets/img_archive/canvas_revenue_country.png
  assets/img_archive/channel_engagement_revenue.png
  assets/img_archive/device_carriers.png
  assets/img_archive/device_models.png
  assets/img_archive/device_screen_resolutions.png
  assets/img_archive/email_delivery_day.png
  assets/img_archive/email_engagement_segment.png
  assets/img_archive/os_version.png
  assets/img_archive/sms_errors.png
  assets/img_archive/test_session.png
  assets/img_archive/top-bottom-email.png
Labels: cla-signed, Deploy

#7199 [SDK-4491] GIF Support on React Native
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
  _docs/_developer_guide/platform_integration_guides/react_native/inapp_messages.md
Labels: cla-signed

#7216 Remove reference to "API Campaign" from IAM creation
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/create.md
Labels: cla-signed

#7181 BD-2975 Add automatic link shortening to keyword handling
  _docs/_developer_guide/platform_integration_guides/swift/analytics/tracking_sessions.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
  assets/img/sms/link_shortening.gif
Labels: cla-signed

#7217 BD-3003 Update POST user track
  _docs/_api/endpoints/user_data/post_user_track.md
Labels: cla-signed

#7212 Minor edits to API overview
  _docs/_api/basics.md
Labels: cla-signed

#7218 BD-2988: Catalogs feature update
  _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
  _includes/create_transformation.md
Labels: cla-signed

#7219 BD-3008 Add subscription group IDs
  _docs/_api/endpoints/subscription_groups/get_list_user_subscription_group_status.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
  _docs/_api/identifier_types.md
Labels: cla-signed

#7223 Deploy pt. 2 - April 16, 2024
  _docs/_api/basics.md
  _docs/_api/endpoints/subscription_groups/get_list_user_subscription_group_status.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_api/identifier_types.md
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
  _docs/_developer_guide/platform_integration_guides/react_native/inapp_messages.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/tracking_sessions.md
  _docs/_hidden/redirects/okta.md
  _docs/_partners/home.md
  _docs/_partners/isv_partners/best_practices.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/channel_extensions.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/friendbuy.md
  _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/create.md
  _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
  _includes/create_transformation.md
  assets/img/friendbuy/choosing_braze.png
  assets/img/friendbuy/install_form.png
  assets/img/friendbuy/install_success.png
  assets/img/friendbuy/referral_widget.png
  assets/img/sms/link_shortening.gif
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#7220 BD-2972: Campaign and Canvas delivery details
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/reeligibility.md
  assets/img_archive/ReEligible.png
  assets/img_archive/api_triggered_campaign_delivery.png
  assets/img_archive/reeligibility_controls_campaign.png
  assets/img_archive/reeligibility_controls_canvas.png
  assets/img_archive/schedule_designated.png
  assets/img_archive/schedule_immediately.png
  assets/img_archive/schedule_intelligent.png
  assets/img_archive/time_based.png
Labels: cla-signed

#7225 BD-3017: Add note for `product_handle` and `product_url` access
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs.md
Labels: cla-signed

#7229 Removing a link to a non-existent section
  _docs/_user_guide/data_and_analytics/custom_data/custom_events/nested_objects.md
Labels: cla-signed

#7230 BD-3022: Edits to handling unknown phone numbers
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/handling_unknown_numbers.md
Labels: cla-signed

#7232 Leftover deploy - April 18, 2024
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events/nested_objects.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/reeligibility.md
  _docs/_user_guide/engagement_tools/canvas.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/get_started.md
  _docs/_user_guide/engagement_tools/canvas/get_started/canvas_outlines.md
  _docs/_user_guide/engagement_tools/canvas/get_started/the_basics.md
  _docs/_user_guide/engagement_tools/canvas/testing_canvases.md
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/handling_unknown_numbers.md
  assets/img/canvas_intro/add_canvas_step.gif
  assets/img/canvas_intro/add_canvas_variant.gif
  assets/img/canvas_intro/canvas_intro.gif
  assets/img_archive/ReEligible.png
  assets/img_archive/api_triggered_campaign_delivery.png
  assets/img_archive/reeligibility_controls_campaign.png
  assets/img_archive/reeligibility_controls_canvas.png
  assets/img_archive/schedule_designated.png
  assets/img_archive/schedule_immediately.png
  assets/img_archive/schedule_intelligent.png
  assets/img_archive/time_based.png
Labels: cla-signed, Deploy

#7233 Guest edit test
  _docs/_contributing/styling_examples.md
Labels: cla-signed

#7234 BD-3024 Update Meta Resources with template pacing
  _docs/_user_guide/message_building_by_channel/whatsapp/meta_resources.md
Labels: cla-signed

#7236 BD-3032 Remove EA note for performance data by segment
  _docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md
Labels: cla-signed

#7227 Update email_capture_form.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize/email_capture_form.md
Labels: cla-signed

#7237 SDK-4844 / more thorough unity android gradle docs
  _docs/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md
Labels: cla-signed

#7241 Fix typo in SDK Authentication doc
  _docs/_developer_guide/platform_wide/sdk_authentication.md
Labels: cla-signed

#7242 BD-3021: Clarify EU consent policy and DMA requirements for Google Audience Sync
  _docs/_partners/canvas_steps/google_audience_sync.md
Labels: cla-signed

#7240 BD-3034 Update credit ratio tables - Italy SMS
  _docs/_hidden/pricing/message_credits_delta_a3sy.md
  _docs/_hidden/pricing/message_credits_gamma_0dhr.md
  _docs/_hidden/pricing/message_credits_sigma_pow2.md
  _docs/_hidden/pricing/message_credits_theta_d9kw.md
Labels: cla-signed

#7246 [CO-2499] Updated back-in-stock / price-drop documentation to include previous / new value
  _docs/_hidden/private_betas/price_drop_notifications.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/back_in_stock_notifications.md
Labels: cla-signed

#7245 BD-3036 SAML Just-in-Time Provisioning
  _docs/_user_guide/administrative/access_braze/single_sign_on/saml_jit.md
Labels: cla-signed

#7243 BD-3035 Add permission sets and roles docs
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Labels: cla-signed

#7244 Small edit
  _docs/_partners/canvas_steps/google_audience_sync.md
Labels: cla-signed

#7248 Update post_users_merge.md
  _docs/_api/endpoints/user_data/post_users_merge.md
Labels: cla-signed

#7247 on brand copy tweak
  _docs/_user_guide/sage_ai/generative_ai/ai_copywriting.md
Labels: cla-signed

#7252 Update get_messages_scheduled.md
  _docs/_api/endpoints/messaging/schedule_messages/get_messages_scheduled.md
Labels: cla-signed

#7251 BD-3038 WhatsApp Cloud API Local Storage
  _docs/_user_guide/message_building_by_channel/whatsapp/overview.md
Labels: cla-signed

#7250 Deploy - April 23, 2024
  _docs/_api/endpoints/messaging/schedule_messages/get_messages_scheduled.md
  _docs/_api/endpoints/user_data/post_users_merge.md
  _docs/_contributing/styling_examples.md
  _docs/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
  _docs/_hidden/pricing/message_credits_delta_a3sy.md
  _docs/_hidden/pricing/message_credits_gamma_0dhr.md
  _docs/_hidden/pricing/message_credits_sigma_pow2.md
  _docs/_hidden/pricing/message_credits_theta_d9kw.md
  _docs/_hidden/private_betas/price_drop_notifications.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_user_guide/administrative/access_braze/single_sign_on/saml_jit.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md
  _docs/_user_guide/engagement_tools/segments/sql_segments/sql_segments_tables.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize/email_capture_form.md
  _docs/_user_guide/message_building_by_channel/whatsapp/meta_resources.md
  _docs/_user_guide/message_building_by_channel/whatsapp/overview.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/back_in_stock_notifications.md
  _docs/_user_guide/sage_ai/generative_ai/ai_copywriting.md
Labels: cla-signed, Deploy

#7235 Update canvas rate limiting docs
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
Labels: cla-signed

#7253 Fix colons
  _docs/_api/endpoints/messaging/schedule_messages/get_messages_scheduled.md
Labels: cla-signed

#7239 BD-3023 Add CDI Segments article
  _docs/_user_guide/engagement_tools/segments/segment_extension/cdi_segments.md
  assets/img/segment/cdi_data_tables.png
  assets/img/segment/connection_schema.png
Labels: cla-signed

#7256 Fix broken link in Extole article
  _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
Labels: cla-signed

#7259 Minor edit
  _docs/_user_guide/sage_ai/predictive_suite/predictive_churn/prediction_faq.md
Labels: cla-signed

#7263 Leftover deploy - April 25, 2024
  _docs/_api/endpoints/messaging/schedule_messages/get_messages_scheduled.md
  _docs/_hidden/other/support_contact.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
  _docs/_user_guide/engagement_tools/segments/segment_extension/cdi_segments.md
  _docs/_user_guide/sage_ai/predictive_suite/predictive_churn/prediction_faq.md
  assets/img/segment/cdi_data_tables.png
  assets/img/segment/connection_schema.png
Labels: cla-signed, Deploy

#7264 add WhatsApp and Global Control Group to user archival
  _docs/_hidden/other/user_archival.md
Labels: cla-signed

#7266 BD-3045 Remove support paragraph - Datadog
  _docs/_partners/data_and_infrastructure_agility/analytics/datadog.md
Labels: cla-signed

#7255 [SDK-4885] Remove warnings about deprecated sdk auth method
  _docs/_developer_guide/platform_wide/sdk_authentication.md
Labels: cla-signed

#7226 Feature flag changelogs + naming practices
  _docs/_developer_guide/platform_wide/feature_flags/create.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/feature_flags.md
  assets/img/feature_flags/changelog/changelog.png
  assets/img/feature_flags/changelog/open_changelog.png
Labels: cla-signed

#7270 Italy message correction
  _docs/_hidden/pricing/message_credits_sigma_pow2.md
Labels: cla-signed

#7271 Leftover deploy pt. 2 - March 29, 2024
  _docs/_developer_guide/platform_wide/feature_flags/create.md
  _docs/_developer_guide/platform_wide/sdk_authentication.md
  _docs/_hidden/other/user_archival.md
  _docs/_hidden/pricing/message_credits_sigma_pow2.md
  _docs/_partners/data_and_infrastructure_agility/analytics/datadog.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/feature_flags.md
  assets/img/feature_flags/changelog/changelog.png
  assets/img/feature_flags/changelog/open_changelog.png
Labels: cla-signed, Deploy

#7268 add docs for data deletion preferences - MERGE 4/30
  _docs/_user_guide/administrative/app_settings/company_settings/security_settings.md
  assets/img/deletion_preferences_1.png
Labels: cla-signed

#7273 April 30, 2024 release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2024.md
  _docs/_help/release_notes/2024/4_30_24.md
Labels: cla-signed

#7275 Add multi lang generation support
  Rakefile
  _lang/_config_ja.yml
Labels: cla-signed

#7276 add multi_lang support for redirect in navigation
  _plugins/urlnavmenu_generator.rb
Labels: cla-signed

#7272 [SDK-4855] Cleanup mentions of `app.json` in Flutter docs
  _docs/_developer_guide/platform_integration_guides/flutter/push_notifications.md
Labels: cla-signed

#7177 New API use cases article
  _docs/_api/basics.md
  _docs/_api/use_cases.md
Labels: cla-signed

#6954 BD-2843: Contributing docs: Creating Jekyll Collections
  _docs/_contributing/content_management.md
  _docs/_contributing/content_management/cross_referencing.md
  _docs/_contributing/content_management/images.md
  _docs/_contributing/content_management/jekyll_collections.md
  _docs/_contributing/content_management/redirecting_urls.md
  _docs/_contributing/content_management/reusing_content.md
Labels: cla-signed

#7258 add connected source docs
  _docs/_user_guide/data_and_analytics/cloud_ingestion.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/connected_sources.md
  assets/img/cloud_ingestion/connected_source_sf_1.png
  assets/img/cloud_ingestion/connected_source_sf_2.png
  assets/img/cloud_ingestion/connected_source_sf_3.png
Labels: cla-signed

#7282 BD-3048: Fix incorrect link for android pn priority
  _docs/_api/objects_filters/messaging/android_object.md
Labels: cla-signed
