Repository braze-inc/braze-docs, pull requests merged in 2025-03, with the labels that each got.

#9116 File home.md committed.
  _lang/es/_hidden/home.md
  _lang/es/_hidden/sms_channel.md
  _lang/es/_hidden/user_archival.md
Labels: cla-signed

#9119 Hotfix: landing pages link
  _docs/_user_guide/engagement_tools/landing_pages/creating_pages.md
Labels: cla-signed

#9118 Update Push and CC docs
  _docs/_developer_guide/content_cards/customizing_feed.md
  _includes/developer_guide/android/push_notifications.md
Labels: cla-signed

#9110 BD-3948 Adjust language for properly creating small icons
  _includes/developer_guide/android/push_notifications.md
Labels: cla-signed

#9100 [CO-3338] Add a section to the main catalogs page clarifying how limits work
  _docs/_user_guide/personalization_and_dynamic_content/catalogs.md
Labels: cla-signed

#9124 Pull FAQ entry on timing calculations into the "How it works" section
  _docs/_user_guide/brazeai/intelligence/intelligent_timing.md
Labels: cla-signed

#9123 Add link to Machine Opens glossary entry
  _docs/_user_guide/brazeai/intelligence/faqs.md
Labels: cla-signed

#9120 Fix typo
  _docs/_partners/canvas_steps/criteo_audience_sync.md
Labels: cla-signed

#9046 BD-4019 Update screenshots and UX for targeting pages
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/targeting_users.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  assets/img_archive/additional_filters.png
  assets/img_archive/entry_controls.png
  assets/img_archive/target_segmenter.png
Labels: cla-signed

#9129 Adds back list-unsubscribe for property details
  _docs/_user_guide/data/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#9122 [DI-7219] Add event docs for email.Deferral
  _docs/_user_guide/data/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#9087 [BD-3275] Dev Guide Detangle: Content Cards
  _docs/_developer_guide/content_cards.md
  _docs/_developer_guide/content_cards/creating_cards.md
  _docs/_developer_guide/content_cards/customizing_cards.md
  _docs/_developer_guide/content_cards/customizing_cards/behavior.md
  _docs/_developer_guide/content_cards/customizing_cards/feed.md
  _docs/_developer_guide/content_cards/customizing_cards/style.md
  _docs/_developer_guide/content_cards/deep_linking.md
  _docs/_developer_guide/content_cards/embedding_gifs.md
  _docs/_developer_guide/content_cards/logging_analytics.md
  _docs/_developer_guide/platforms/android/content_cards.md
  _docs/_developer_guide/platforms/android/content_cards/custom_fonts.md
  _docs/_developer_guide/platforms/android/content_cards/deep_linking.md
  _docs/_developer_guide/platforms/android/content_cards/examples.md
  _docs/_developer_guide/platforms/android/content_cards/gif.md
  _docs/_developer_guide/platforms/android/content_cards/jetpack_compose.md
  _docs/_developer_guide/platforms/fireos/content_cards.md
  _docs/_developer_guide/platforms/fireos/content_cards/custom_fonts.md
  _docs/_developer_guide/platforms/fireos/content_cards/deep_linking.md
  _docs/_developer_guide/platforms/fireos/content_cards/examples.md
  _docs/_developer_guide/platforms/fireos/content_cards/gif.md
  _docs/_developer_guide/platforms/fireos/content_cards/jetpack_compose.md
  _docs/_developer_guide/platforms/swift/content_cards/deep_linking.md
  _includes/developer_guide/android/_global/custom_fonts.md
  _includes/developer_guide/android/_global/deep_linking.md
  _includes/developer_guide/android/_global/gifs.md
  _includes/developer_guide/android/content_cards.md
  _includes/developer_guide/cordova/content_cards.md
  _includes/developer_guide/flutter/content_cards.md
  _includes/developer_guide/react_native/content_cards.md
  _includes/developer_guide/swift/content_cards.md
  _includes/developer_guide/swift/deep_linking.md
  _includes/developer_guide/swift/gifs.md
  _includes/developer_guide/tvos/content_cards.md
  _includes/developer_guide/unity/content_cards.md
  _includes/developer_guide/web/content_cards.md
  _includes/developer_guide/xamarin/content_cards.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#9133 Docs Feedback: Fix file name for About Item Recommendations
  _docs/_user_guide/brazeai/recommendations/about_item_recommendations.md
Labels: cla-signed

#9131 March 4, 2025 release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2025.md
  _docs/_help/release_notes/2025/3_4_25.md
  assets/img/release_notes/2025_05_04/integer.png
  assets/img/release_notes/2025_05_04/location.png
  assets/img/release_notes/2025_05_04/regenerate_from_html.png
  assets/img/release_notes/2025_05_04/string.png
Labels: cla-signed, release notes

#9090 Update user_update.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
Labels: cla-signed

#9134 Docs feedback: Update UI in Fivetran
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/fivetran.md
Labels: cla-signed

#9135 Docs Feedback: Add SVG to Media Library file types
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
Labels: cla-signed

#9126 Minor grammatical edits
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#9139 File sdk_overview.md committed.
  _lang/ja/_developer_guide/getting_started/sdk_overview.md
Labels: cla-signed

#9136 BD-4198 Docs Feedback: Fix integration links
  _docs/_user_guide/getting_started/web_sdk.md
Labels: cla-signed

#9145 Update 3_4_25.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2025/3_4_25.md
Labels: cla-signed

#9144 update rack 3.1.11
  Gemfile.lock
Labels: cla-signed

#9147 BD-4214 Docs feedback: Clarify link template preview docs
  _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
Labels: cla-signed

#9148 Update faq.md
  _docs/_user_guide/message_building_by_channel/email/faq.md
Labels: cla-signed

#9149 BD-4215 Docs feedback: Remove outdated WhatsApp limitation
  _docs/_user_guide/message_building_by_channel/whatsapp/overview.md
Labels: cla-signed

#9151 Docs feedback: Update to API usage dashboard instead of API limits
  _docs/_api/endpoints/user_data/post_user_track.md
Labels: cla-signed

#9143 Update customizing_urls.md
  _docs/_user_guide/engagement_tools/landing_pages/customizing_urls.md
Labels: cla-signed

#9152 BD-4217 Docs feedback: Add examples of naming conventions for events
  _docs/_user_guide/data/custom_data/event_naming_conventions.md
Labels: cla-signed

#9154 File multivariate_analytics.md committed.
  _lang/ja/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md
Labels: cla-signed

#9155 rename url handle
  _docs/_user_guide/engagement_tools/landing_pages/creating_pages.md
  _docs/_user_guide/engagement_tools/landing_pages/tracking_users.md
Labels: cla-signed

#9156 Update beacon.md
  _includes/developer_guide/android/analytics/beacon.md
Labels: cla-signed

#9150 BD-3921: Banner Cards prioritization
  _docs/_developer_guide/banner_cards.md
  _docs/_developer_guide/banner_cards/creating_banner_cards.md
  _docs/_developer_guide/banner_cards/creating_placements.md
  _docs/_docs_pages/redirects/create_banner_card.md
Labels: cla-signed

#9158 BD-4228: Export Logs GA
  _docs/_user_guide/administrative/app_settings/exports_log.md
Labels: cla-signed

#9153 BD-4043 Create Push troubleshooting page
  _docs/_developer_guide/platforms/legacy_sdks/ios/push_notifications/troubleshooting.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _docs/_user_guide/message_building_by_channel/push.md
  _docs/_user_guide/message_building_by_channel/push/troubleshooting.md
  _includes/developer_guide/android/push_notifications/troubleshooting.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#9011 BD-3937 Update User Import troubleshooting
  _docs/_user_guide/data/user_data_collection/user_import.md
Labels: cla-signed

#9159 Leftover deploy - March 6, 2025
  Gemfile.lock
  _docs/_api/endpoints/user_data/post_user_track.md
  _docs/_developer_guide/banner_cards.md
  _docs/_developer_guide/banner_cards/creating_banner_cards.md
  _docs/_developer_guide/banner_cards/creating_placements.md
  _docs/_developer_guide/platforms/legacy_sdks/ios/push_notifications/troubleshooting.md
  _docs/_docs_pages/redirects/create_banner_card.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2025/3_4_25.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake/user_attributes.md
  _docs/_partners/message_personalization/dynamic_content/movable_ink/da_vinci.md
  _docs/_user_guide/administrative/app_settings/exports_log.md
  _docs/_user_guide/data/custom_data/event_naming_conventions.md
  _docs/_user_guide/data/user_data_collection/user_import.md
  _docs/_user_guide/engagement_tools/landing_pages/creating_pages.md
  _docs/_user_guide/engagement_tools/landing_pages/customizing_urls.md
  _docs/_user_guide/engagement_tools/landing_pages/tracking_users.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _docs/_user_guide/getting_started/web_sdk.md
  _docs/_user_guide/message_building_by_channel/email/faq.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
  _docs/_user_guide/message_building_by_channel/push.md
  _docs/_user_guide/message_building_by_channel/push/troubleshooting.md
  _docs/_user_guide/message_building_by_channel/whatsapp/overview.md
  _includes/developer_guide/android/analytics/beacon.md
  _includes/developer_guide/android/push_notifications/troubleshooting.md
  _lang/ja/_developer_guide/getting_started/sdk_overview.md
  _lang/ja/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#9170 Corrected example UK local phone number, which should include a leading 0
  _docs/_user_guide/message_building_by_channel/whatsapp/user_phone_numbers.md
Labels: cla-signed

#9162 BD-4105: Replace images with context variable in UI
  assets/img/context_step1.png
  assets/img/context_step2.png
Labels: cla-signed

#9113 BD-4000 Behavior for users frequency capped in Canvases
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
Labels: cla-signed

#9174 BD-3997 Support can assist with bulk user deletion
  _docs/_api/endpoints/user_data/post_user_delete.md
Labels: cla-signed

#9114 BD-3949 Add details to Email Available and Email Address filters
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#9070 BD-4030 Add FAQs to Segment Extensions
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
Labels: cla-signed

#9173 Rename sdk_initalization.md to sdk_initialization.md
  _docs/_developer_guide/sdk_initialization.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#9175 Fixed broken double slash links
  .gitignore
  _docs/_api/api_limits.md
  _docs/_api/endpoints/subscription_groups.md
  _docs/_docs_pages/404.md
  _docs/_docs_pages/404_api.md
  _docs/_help/release_notes/2018/march.md
  _docs/_partners/data_and_infrastructure_agility/analytics/inbox_monster.md
  _docs/_partners/data_and_infrastructure_agility/analytics/looker.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/ketch.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/getting_started_shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/setting_up_shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_user_identity.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_overview.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/zoom.md
  _docs/_user_guide/message_building_by_channel/push/android/notification_options.md
  _docs/_user_guide/message_building_by_channel/sms/best_practices/opt-ins.md
  _docs/_user_guide/onboarding_faq.md
  _includes/developer_guide/android/push_notifications/silent.md
Labels: cla-signed

#9178 fix broken CDI API docs links
  _docs/_api/api_limits.md
Labels: cla-signed

#9146 BD-4212: Importing with email address and phone number GA - MERGE 3/10
  _docs/_user_guide/data/user_data_collection/user_import.md
Labels: cla-signed

#9177 BD-4008 Add attributes to SDK data collection
  _docs/_user_guide/data/user_data_collection/sdk_data_collection.md
Labels: cla-signed

#9164 BD-4111: Add JSON parsing edge case for Context step
  _docs/_user_guide/engagement_tools/canvas/canvas_components/context.md
Labels: cla-signed

#9163 BD-4223: Update Canvas entry properties Liquid to context
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Labels: cla-signed

#9121 BD-4177 Unformatted Phone Number segmentation filter & other updates MERGE 3/10
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#9182 update rack 3.1.12
  Gemfile.lock
Labels: cla-signed

#9179 Update campaign analytics API docs
  _docs/_api/endpoints/export/campaigns/get_campaign_analytics.md
Labels: cla-signed

#9073 BD-4004 New segment calculation page & additional segmentation edits
  _docs/_user_guide/analytics/reporting/viewing_and_understanding_segment_data.md
  _docs/_user_guide/engagement_tools/segments.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _docs/_user_guide/engagement_tools/segments/measuring_segment_size.md
  _docs/_user_guide/engagement_tools/segments/troubleshooting.md
Labels: cla-signed

#9166 BD-4205: Clarify selecting iOS or Android for Push Stories
  _docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_stories.md
Labels: cla-signed

#9168 BD-4088: Add table for Audience Sync info to know at-a-glance
  _docs/_partners/canvas_steps/overview.md
Labels: cla-signed

#9161 BD-4108: Add behavior for context variable
  _docs/_user_guide/engagement_tools/canvas/canvas_components/context.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
Labels: cla-signed

#9160 BD-4109: Update Canvas entry properties to context
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
Labels: cla-signed

#9184 BD-4047: Clarify catalog item stock for user subscription
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/back_in_stock_notifications.md
Labels: cla-signed

#9027 BD-3961 Add troubleshooting items to Canvas Flow
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/launching_canvas_flow.md
Labels: cla-signed

#9186 Deploy - March 11, 2025
  .gitignore
  Gemfile.lock
  _docs/_api/api_limits.md
  _docs/_api/endpoints/export/campaigns/get_campaign_analytics.md
  _docs/_api/endpoints/subscription_groups.md
  _docs/_api/endpoints/user_data/post_user_delete.md
  _docs/_developer_guide/debugging.md
  _docs/_developer_guide/sdk_initialization.md
  _docs/_docs_pages/404.md
  _docs/_docs_pages/404_api.md
  _docs/_help/release_notes/2018/march.md
  _docs/_help/support.md
  _docs/_partners/canvas_steps/overview.md
  _docs/_partners/data_and_infrastructure_agility/analytics/inbox_monster.md
  _docs/_partners/data_and_infrastructure_agility/analytics/looker.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/ketch.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/getting_started_shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/setting_up_shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_user_identity.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_overview.md
  _docs/_user_guide/analytics/reporting/viewing_and_understanding_segment_data.md
  _docs/_user_guide/data/user_data_collection/sdk_data_collection.md
  _docs/_user_guide/data/user_data_collection/user_import.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/zoom.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/context.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/launching_canvas_flow.md
  _docs/_user_guide/engagement_tools/segments.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _docs/_user_guide/engagement_tools/segments/measuring_segment_size.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/engagement_tools/segments/troubleshooting.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/overview.md
  _docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_stories.md
  _docs/_user_guide/message_building_by_channel/push/android/notification_options.md
  _docs/_user_guide/message_building_by_channel/sms/best_practices/opt-ins.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_phone_numbers.md
  _docs/_user_guide/onboarding_faq.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/back_in_stock_notifications.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
  _includes/developer_guide/android/push_notifications/silent.md
  assets/img/context_step1.png
  assets/img/context_step2.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#9185 BD-4257: Add limit for segmentable event properties
  _docs/_user_guide/data/custom_data/custom_events.md
Labels: cla-signed

#9180 BD-4221 Add "Managing translations" section to locales
  _docs/_api/endpoints/translations/get_bulk_translations_canvases.md
  _docs/_api/endpoints/translations/get_translation_canvas.md
  _docs/_api/endpoints/translations/put_update_translation_canvas.md
  _docs/_user_guide/message_building_by_channel/email/using_locales.md
Labels: cla-signed

#9165 BD-4087: Dynamic APNs gateway management
  _docs/_developer_guide/platforms/swift/push_notifications/dynamic_apns.md
  _docs/_developer_guide/platforms/swift/push_notifications/examples.md
Labels: cla-signed

#9189 Update external Id configurations instructions
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/punchh.md
Labels: cla-signed

#9219 Leftover deploy - March 14, 2025
  .gitignore
  Gemfile.lock
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_api/endpoints/translations/get_bulk_translations_canvases.md
  _docs/_api/endpoints/translations/get_translation_canvas.md
  _docs/_api/endpoints/translations/put_update_translation_canvas.md
  _docs/_contributing/bdocs.md
  _docs/_developer_guide/content_cards/creating_cards.md
  _docs/_developer_guide/platforms/swift/push_notifications/dynamic_apns.md
  _docs/_developer_guide/platforms/swift/push_notifications/examples.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/punchh.md
  _docs/_user_guide/administrative/app_settings/email_settings.md
  _docs/_user_guide/data/cloud_ingestion/faqs.md
  _docs/_user_guide/data/cloud_ingestion/file_storage_integrations.md
  _docs/_user_guide/data/cloud_ingestion/overview.md
  _docs/_user_guide/data/custom_data/custom_events.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/message_building_by_channel/email/apple_mail/email_private_relay_apple_SSO.md
  _docs/_user_guide/message_building_by_channel/email/using_locales.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
  _docs/_user_guide/message_building_by_channel/webhooks/understanding_webhooks.md
  _includes/developer_guide/prerequisites/android.md
  _includes/developer_guide/prerequisites/cordova.md
  _includes/developer_guide/prerequisites/flutter.md
  _includes/developer_guide/prerequisites/react_native.md
  _includes/developer_guide/prerequisites/swift.md
  _includes/developer_guide/prerequisites/unity.md
  _includes/developer_guide/prerequisites/unreal_engine.md
  _includes/developer_guide/prerequisites/web.md
  _includes/developer_guide/prerequisites/xamarin.md
  _includes/html_include.html
  assets/css/_content.scss
  assets/img/audience_path/audience_path5.png
  assets/img/segment/segment_extension_disabled.png
  assets/js/broken_redirect_list.js
  assets/js/documents.js
  assets/js/mermaid.js
  bdocs
  package-lock.json
  package.json
  scripts/find_broken_links.ts
  tsconfig.json
Labels: Deploy

#9183 BD-4242 Updates for Global Control Groups docs
  _docs/_user_guide/analytics/reporting/global_control_group_reporting.md
  _docs/_user_guide/engagement_tools/testing/global_control_group.md
Labels: cla-signed

#9086 BD-3955 Add troubleshooting page for SAML/SSO setup
  _docs/_user_guide/administrative/access_braze/single_sign_on/set_up.md
  assets/img/relaystate_troubleshoot.png
Labels: cla-signed

#9093 BD-3996 Email unsubscribe rate is logged across all sources
  _docs/_user_guide/analytics/dashboard/email_performance_dashboard.md
Labels: cla-signed

#9202 [BD-3275] Dev Guide Detangle: Network Settings
  _docs/_developer_guide/network.md
  _docs/_developer_guide/platforms/android/network.md
  _docs/_developer_guide/platforms/android/network/network_offline_mode_integration.md
  _docs/_developer_guide/platforms/fireos/network.md
  _docs/_developer_guide/platforms/fireos/network/network_offline_mode_integration.md
  _docs/_developer_guide/sending_test_messages.md
  _includes/developer_guide/android/network.md
  _includes/developer_guide/swift/network.md
  assets/js/broken_redirect_list.js
Labels: In Review

#8326 Update dynamics_365_customer_insights.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/dynamics_365_customer_insights.md
Labels: cla-signed, Braze Partnerships

#9130 BD-4180 Add Use Case template to contributing docs
  _docs/_contributing/content_types.md
  _includes/contributing/templates/use_case.md
Labels: cla-signed

#9138 BD-4199: Update event object datetimes description
  _docs/_api/objects_filters/event_object.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
Labels: cla-signed

#9319 Leftover deploy pt. 2 - March 28, 2025
  _docs/_api/api_limits.md
  _docs/_api/basics.md
  _docs/_api/objects_filters/event_object.md
  _docs/_api/objects_filters/trigger_properties_object.md
  _docs/_developer_guide/banner_cards.md
  _docs/_developer_guide/banner_cards/creating_campaigns.md
  _docs/_developer_guide/banner_cards/embedding_cards.md
  _docs/_user_guide/administrative/access_braze/sdk_endpoints.md
  _docs/_user_guide/data/braze_currents/setting_up_currents.md
  _docs/_user_guide/data/cloud_ingestion/connected_sources.md
  _docs/_user_guide/data/cloud_ingestion/faqs.md
  _docs/_user_guide/data/cloud_ingestion/integrations.md
  _docs/_user_guide/data/data_centers.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/context.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties/canvas_persistent_entry_properties.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
  _includes/data_centers.md
Labels: Deploy

#9171 BD-4093 Create Push FAQs
  _docs/_help/faqs.md
  _docs/_user_guide/message_building_by_channel/push.md
  _docs/_user_guide/message_building_by_channel/push/faq.md
  assets/img/push_changelog_faq.png
Labels: cla-signed

#9096 BD-3935 Add behavior for Canvases that are stopped and reactivated
  _docs/_user_guide/engagement_tools/messaging_fundamentals/about_statuses.md
  assets/img/messaging_fundamentals/change-status.png
  assets/img/messaging_fundamentals/filter-by-status.png
Labels: cla-signed
