Repository braze-inc/braze-docs, pull requests merged in 2025-06, with the labels that each got.

#9773 Fix sub-step numbering for create canvas
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
Labels: status: done, cla-signed

#9777 OfferFit Docs Launch
  _docs/_developer_guide/disclosures/innovation_statement.md
  _docs/_developer_guide/offerfit.md
  _docs/_developer_guide/offerfit/building_use_cases.md
  _docs/_developer_guide/offerfit/integration.md
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/ab_testing/offerfit.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content/content_optimization_testing/offerfit.md
  _docs/_user_guide/offerfit.md
  _docs/_user_guide/offerfit/building_use_cases.md
  _docs/_user_guide/offerfit/integration.md
  _includes/offerfit/about.md
  _includes/offerfit/alert_multi_platform_support.md
  _includes/offerfit/api_key_permissions.md
  _includes/offerfit/building_use_cases.md
  _includes/offerfit/integration.md
  _includes/offerfit/sample_use_cases.md
  assets/download_file/Braze_Entitlements_Handbook_25.pdf
  assets/img/offerfit/example_use_cases_referral_email.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#9778 Deploy - June 2, 2025
  .github/workflows/add-label.yml
  .github/workflows/block-merge.yml
  _docs/_api/objects_filters/messaging/android_object.md
  _docs/_developer_guide/disclosures/innovation_statement.md
  _docs/_developer_guide/offerfit.md
  _docs/_developer_guide/offerfit/building_use_cases.md
  _docs/_developer_guide/offerfit/integration.md
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/ab_testing/offerfit.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content/content_optimization_testing/offerfit.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
  _docs/_user_guide/offerfit.md
  _docs/_user_guide/offerfit/building_use_cases.md
  _docs/_user_guide/offerfit/integration.md
  _includes/offerfit/about.md
  _includes/offerfit/alert_multi_platform_support.md
  _includes/offerfit/api_key_permissions.md
  _includes/offerfit/building_use_cases.md
  _includes/offerfit/integration.md
  _includes/offerfit/sample_use_cases.md
  _includes/permissions.md
  assets/download_file/Braze_Entitlements_Handbook_25.pdf
  assets/img/offerfit/example_use_cases_referral_email.png
  assets/img_archive/push_2.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#9789 web sdk initialization is not optional
  _includes/developer_guide/web/sdk_integration.md
Labels: cla-signed

#9788 save braze external id
  _includes/analytics.html
  assets/js/feedback.js
Labels: status: done, cla-signed

#9787 [PUSH-353] Clarify the behaviour of Background Push Enabled filter
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#9784 Stripe partner docs
  _docs/_partners/ecommerce.md
  _docs/_partners/ecommerce/ordering_payments_subscription/stripe.md
  _docs/_partners/home.md
  _includes/create_transformation.md
  assets/img/stripe/stripe_braze_profile_event.png
  assets/img/stripe/stripe_data_transformation.png
  assets/img/stripe/stripe_webhook_configuration.png
Labels: cla-signed, Braze Partnerships

#9791 BD-4527: Clarify test sends for Content Cards
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
Labels: cla-signed

#9786 MX-1935.md
  _docs/_api/endpoints/export/campaigns/get_campaign_details.md
  _docs/_api/endpoints/export/canvas/get_canvas_details.md
Labels: cla-signed

#9785 Update README.md
  README.md
Labels: cla-signed

#9800 Update stripe.md
  _docs/_partners/ecommerce/ordering_payments_subscription/stripe.md
Labels: cla-signed

#9801 Update Context step images for Liquid fix
  _docs/_user_guide/engagement_tools/canvas/canvas_components/context.md
  assets/img/context_example3.png
  assets/img/context_example4.png
Labels: cla-signed

#9455 BD-4372 Update segment stats docs
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/messaging_fundamentals/targeting_users.md
  _docs/_user_guide/engagement_tools/segments/measuring_segment_size.md
  _includes/segments.md
  assets/img_archive/calculation_queue.png
  assets/img_archive/cancel_calculation.png
  assets/img_archive/expand_stats.png
  assets/img_archive/historical_membership2.png
  assets/img_archive/reachable_users_breakdown.png
  assets/img_archive/reachable_users_panel.png
  assets/img_archive/reachable_users_side_panel.png
  assets/img_archive/segmenter_reachable_users.png
Labels: cla-signed

#9797 BD-4824: Remove catalogs tile from Analytics section
  _docs/_user_guide/analytics.md
  _docs/_user_guide/data/field_level_encryption.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#9803 BD-4800: Clarify any `app_id` works for all users if it's configured in your workspace for SMS and email objects
  _docs/_api/objects_filters/messaging/email_object.md
  _docs/_api/objects_filters/messaging/sms_object.md
Labels: cla-signed

#9802 BD-4818: Clarify link preview detail
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
Labels: cla-signed

#9796 BD-4761: Clarify details on delivery speed rate limiting
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
Labels: cla-signed

#9811 BD-4828 Fix hidden LINE reporting article
  _docs/_user_guide/message_building_by_channel/line/reporting.md
Labels: cla-signed

#9799 BD-4823: Update to contact account manager
  _docs/_user_guide/message_building_by_channel/sms_mms_rcs/rcs/about_rcs.md
Labels: cla-signed

#9817 Fix tile link
  _docs/_user_guide/message_building_by_channel.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#9816 Update placement_requests.md
  _includes/banners/placement_requests.md
Labels: cla-signed

#9826 Minor styling change to accessibility page
  _docs/_help/accessibility.md
Labels: cla-signed

#9810 Potential fixes for scrolly code (testing)
  assets/css/scrollycode.scss
  assets/js/scrollycode.js
Labels: cla-signed

#9696 SDK banner tutorials
  _docs/_developer_guide/banners/creating_placements.md
  _docs/_developer_guide/banners/faq.md
  _docs/_developer_guide/banners/tutorial_displaying_banners.md
  _includes/developer_guide/_shared/tutorial_feedback.md
  _includes/developer_guide/android/banners/tutorial_displaying_banners.md
  _includes/developer_guide/swift/banners/tutorial_displaying_banners.md
  _includes/developer_guide/web/banners/tutorial_displaying_banners.md
  _layouts/scrolly.html
  _plugins/scrolly_code_processor.rb
  assets/css/scrollycode.scss
  assets/js/scrollycode.js
Labels: do not merge, cla-signed

#9821 Add error handling to 'mredirects'
  scripts/make_redirects.py
Labels: cla-signed

#9813 Fix spelling error in code comment for sdk_integration.md
  _includes/developer_guide/web/sdk_integration.md
Labels: cla-signed

#9841 BD-4842 Remove EA for click tracking and WhatsApp videos
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/click_tracking.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md
Labels: cla-signed

#9840 BD-4827 Add EA alert to eCommerce use cases
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/ecommerce_use_cases.md
Labels: cla-signed

#9843 Fix merge conflict into 'master' branch
  _docs/_user_guide/brazeai/recommendations/creating_recommendations/ai.md
Labels: cla-signed

#9845 [BD-4845]: Fix minor subject consistency, testing prompts
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
Labels: cla-signed

#9847 BD-4831: Remove `quiet_hours` from `abort_type` for Currents
  _docs/_user_guide/engagement_tools/segments/sql_segments/sql_segments_tables.md
  assets/download_file/data-sharing-raw-table-schemas.txt
Labels: cla-signed

#9831 BD-4841: Remove value-based audience TOS section
  _docs/_partners/canvas_audience_sync/facebook_audience_sync.md
Labels: cla-signed

#9850 BD-4570: Clarify that variables must be wrapped in curly brackets
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/using_catalogs.md
Labels: cla-signed

#9851 Remove `{% raw %}` and `{%endraw%}` around image references
  _docs/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md
Labels: cla-signed

#9852 404 checker - June 11, 2025
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#9829 Update measuring_segment_size.md
  _docs/_user_guide/engagement_tools/segments/measuring_segment_size.md
Labels: cla-signed

#9856 Remove self-referential link
  _includes/developer_guide/react_native/push_notifications/rich.md
Labels: cla-signed

#9867 Remove incorrect limitation for link aliases
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
Labels: cla-signed

#9860 BD-4825 Update Data Protection Technical Assistance
  _docs/_hidden/other/dp-technical-assistance.md
Labels: cla-signed

#9855 BD-4712: Clarify info on custom fonts and add alt text
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
Labels: cla-signed

#9871 Leftover deploy - June 13, 2025
  _docs/_api/endpoints/email/get_list_hard_bounces.md
  _docs/_hidden/other/dp-technical-assistance.md
  _docs/_partners/canvas_audience_sync/facebook_audience_sync.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
  _docs/_user_guide/engagement_tools/landing_pages/tracking_users.md
  _docs/_user_guide/engagement_tools/segments/measuring_segment_size.md
  _docs/_user_guide/engagement_tools/segments/sql_segments/sql_segments_tables.md
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/using_catalogs.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/aborting_messages.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
  _includes/developer_guide/_shared/sample_apps.md
  _includes/developer_guide/react_native/push_notifications/rich.md
  _includes/developer_guide/web/sdk_integration.md
  assets/download_file/data-sharing-raw-table-schemas.txt
  assets/img/braze_icons/accessibility.svg
  assets/js/broken_redirect_list.js
Labels: cla-signed

#9873 Fix anchor link in Suppression lists
  _docs/_user_guide/engagement_tools/segments/suppression_lists.md
Labels: cla-signed

#9866 BD-4730 Last Did Custom Event filter supports decimals
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#9732 BD-4722 Update Background Push Enabled filter description
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#9849 Fix US-10 dashboard URL
  _includes/data_centers.md
Labels: cla-signed

#9869 add externalid to feedback
  _docs/_hidden/other/feedback.md
  assets/js/feedback.js
Labels: cla-signed

#9857 Update example error on overview.md
  _docs/_user_guide/data/cloud_ingestion/overview.md
Labels: cla-signed

#9881 [PUSH-396] Add description about the apns_priority field in Apple Push object in Braze doc
  _docs/_api/objects_filters/messaging/apple_object.md
Labels: cla-signed

#9655 BD-4731 Update Custom Domain article [MERGE JUNE 16]
  _includes/custom_domains.md
  assets/img/custom_domain_button.png
  assets/img/custom_domain_statuses.png
  assets/img/dns_record.png
  assets/img/main_page.png
Labels: cla-signed

#9884 [NO-TICKET] Add the missing brace
  _docs/_api/objects_filters/messaging/apple_object.md
Labels: cla-signed

#9886 Add alert about known issue for accessibility testing
  _docs/_user_guide/message_building_by_channel/email/inbox_vision.md
Labels: cla-signed

#9889 force utf8 encoding for content
  _plugins/algolia_hooks.rb
Labels: cla-signed

#9808 Add Reference to Banners in Segment Filters
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: status: in progress, cla-signed

#9897 BD-4865: Fix URL
  _docs/_partners/message_personalization/dynamic_content/visual_and_interactive_content/movable_ink.md
Labels: cla-signed

#9795 Adjust feedback page
  _docs/_hidden/other/feedback.md
Labels: cla-signed

#9901 additional encode to utf8
  _plugins/algolia_hooks.rb
Labels: cla-signed

#9903 BD-4868 Revert custom domain edits
  _docs/_user_guide/message_building_by_channel/sms_mms_rcs/link_shortening/custom_domains.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/custom_domains.md
  _includes/custom_domains.md
Labels: cla-signed

#9905 fix algolia indexing v3
  Gemfile.lock
Labels: cla-signed

#9906 BD-4869: Fix open tracking pixel steps
  _docs/_user_guide/administrative/app_settings/email_settings.md
Labels: cla-signed

#9909 BD-4871: Add recommendation for file size and fix typos
  _docs/_user_guide/data/cloud_ingestion/file_storage_integrations.md
Labels: cla-signed

#9836 SDK Tutorials: In-App Messages
  _docs/_developer_guide/banners/tutorial_displaying_banners.md
  _docs/_developer_guide/in_app_messages/tutorials.md
  _docs/_developer_guide/in_app_messages/tutorials/conditionally_displaying_messages.md
  _docs/_developer_guide/in_app_messages/tutorials/customizing_message_styling.md
  _docs/_developer_guide/in_app_messages/tutorials/deferring_triggered_messages.md
  _docs/_developer_guide/tutorials.md
Labels: cla-signed

#9894 June 24, 2025 release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2025.md
  _docs/_help/release_notes/2025/6_24_25.md
Labels: cla-signed

#9911 Fix incorrect breadcrumb instructions
  _docs/_user_guide/brazeai/generative_ai/images.md
Labels: cla-signed

#9904 BD-4421: Update analytics for Delay step
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
Labels: cla-signed

#9716 BD-4760 Add use case for Shopify unique discount codes
  _docs/_partners/ecommerce/shopify.md
  _docs/_partners/ecommerce/shopify/discount_codes.md
  assets/img/Shopify/configure_discount_codes.png
  assets/img/Shopify/edited_codes_csv.png
  assets/img/Shopify/export_discount_codes.png
  assets/img/Shopify/liquid_code_snippet.png
  assets/img/Shopify/liquid_promo_code.gif
  assets/img/Shopify/user_update_step.png
Labels: cla-signed, In Review

#9726 BD-4790 Add json_parse and as_json_string filters
  _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters.md
Labels: cla-signed

#9912 BD-4402: Update details for original Canvas editor
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
Labels: cla-signed

#9893 Update dashboard_builder.md
  _docs/_user_guide/analytics/reporting/dashboard_builder.md
Labels: cla-signed

#9907 Update testing.md
  _docs/_developer_guide/banners/testing.md
Labels: cla-signed

#9916 Grammar fix.
  _docs/_developer_guide/home.md
  _docs/_developer_guide/sdk_integration.md
Labels: cla-signed

#9888 [BD-4876] [SDK-5524] Android push lifecycle flowchart
  _includes/developer_guide/android/push_notifications.md
  assets/css/_content.scss
Labels: cla-signed

#9923 Fix bdocs deploy command
  scripts/create_deploy_text.sh
Labels: cla-signed

#9927 notix / Make changes to the `_includes` folder trigger a reload
  Gemfile
  Gemfile.lock
  Rakefile
  includes_watcher.rb
Labels: cla-signed

#9899 Accessibilty_Scanner_IAM
  _docs/_help/accessibility.md
  _docs/_user_guide/message_building_by_channel/email/inbox_vision.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/testing.md
  _includes/accessibility/automated_testing.md
  assets/img/Accessibilty_Scanner_IAM.png
Labels: cla-signed

#9918 BD-4401 Add IP addresses to your IP allowlist for LINE setup
  _docs/_user_guide/message_building_by_channel/line/line_setup.md
Labels: cla-signed

#9929 Leftover deploy pt 2 - June 27, 2025
  Gemfile
  Gemfile.lock
  Rakefile
  _docs/_help/accessibility.md
  _docs/_partners/ecommerce/shopify/shopify_standard_integration.md
  _docs/_partners/message_orchestration/templates/alpaco.md
  _docs/_user_guide/message_building_by_channel/email/inbox_vision.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/testing.md
  _docs/_user_guide/message_building_by_channel/line/line_setup.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/click_tracking.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/custom_domains.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/product_messages.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/user_retargeting.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/back_in_stock_notifications.md
  _includes/accessibility/automated_testing.md
  assets/img/Accessibilty_Scanner_IAM.png
  assets/img/whatsapp/catalog_experience.png
  assets/img/whatsapp/connected_content_checkout.png
  assets/img/whatsapp/liquid_generated_cart_link_checkout.png
  assets/img/whatsapp/meta_catalog.png
  assets/img/whatsapp/meta_catalog_settings.png
  assets/img/whatsapp/multi-product_catalog_opening.png
  assets/img/whatsapp/multi_product_template.png
  assets/img/whatsapp/product_message_canvas_step.png
  assets/img/whatsapp/share_meta_catalog.png
  assets/img/whatsapp/webhooks_custom_events_checkout.png
  includes_watcher.rb
  scripts/create_deploy_text.sh
Labels: cla-signed, Deploy

#9930 BD-4826: Minor update for purchase event disclaimer
  _docs/_user_guide/data/custom_data/recommended_events/ecommerce_events.md
Labels: cla-signed

#9931 BD-4792: Update user docs to specify AI Content Q/A is mobile push only, not all push
  _docs/_user_guide/brazeai/generative_ai/content_qa.md
Labels: cla-signed

#9926 SDK-5737 / Android Push Docs Audit
  _docs/_user_guide/message_building_by_channel/push/android/advanced_campaign_settings.md
  _includes/developer_guide/android/push_notifications/customization.md
  _includes/developer_guide/fireos/push_notifications/customization.md
  assets/img/android/push/collapsed-android-notification.png
  assets/img/android/push/expanded-android-notification.png
Labels: cla-signed
