Repository braze-inc/braze-docs, pull requests merged in 2025-01, with the labels that each got.

#8672 [CO-3164] Specify NULL is not supported in CSV upload.
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
Labels: cla-signed

#8678 BD-3804: Add new section to WhatsApp Meta resources doc
  _docs/_user_guide/message_building_by_channel/whatsapp/meta_resources.md
Labels: cla-signed

#8681 [BD-3806] delete fresh relevance page
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content.md
  _docs/_partners/message_personalization/dynamic_content/fresh_relevance.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8682 Fix incorrect info about redirects
  _docs/_contributing/content_management/redirecting_urls.md
  _docs/_contributing/content_management/reusing_content.md
  _docs/_contributing/troubleshooting.md
  _docs/_contributing/yaml_front_matter/metadata.md
  _docs/_contributing/yaml_front_matter/page_layouts.md
  _includes/contributing/troubleshooting/redirects.md
  assets/img/contributing/styling_examples/layouts/blank_config.png
Labels: cla-signed

#8680 [BD-3806] Hide rokt calendar page
  _docs/_partners/home.md
  _docs/_partners/message_orchestration.md
  _docs/_partners/message_orchestration/additional_channels.md
  _docs/_partners/message_orchestration/additional_channels/calendar.md
  _docs/_partners/message_orchestration/additional_channels/calendar/rokt_calendar.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8691 [BD-2923] Missing permission for Google Cloud Storage
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/google_cloud_storage_for_currents.md
  assets/img/gcs8.png
Labels: cla-signed

#8661 Add notes for iOS 18 Apple Intelligence
  _docs/_developer_guide/platform_integration_guides/swift/ios_18.md
  assets/img/apple/apple_intelligence/notification_preview_summary.png
Labels: cla-signed

#8540 BD-3090 Add anonymous users to Getting Started
  _docs/_user_guide/data_and_analytics/user_data_collection.md
  _docs/_user_guide/data_and_analytics/user_data_collection/anonymous_users.md
  _docs/_user_guide/getting_started/users_segments.md
  assets/img/getting_started/anonymous_users.png
Labels: cla-signed

#8679 BD-3739: Add 2 Canvas templates use cases
  _docs/_user_guide/engagement_tools/canvas/get_started/braze_templates.md
  _docs/_user_guide/engagement_tools/canvas/get_started/braze_templates/back_in_stock.md
  _docs/_user_guide/engagement_tools/canvas/get_started/braze_templates/email_signup.md
  _docs/_user_guide/engagement_tools/canvas/get_started/braze_templates/preference_survey.md
  assets/img/canvas_templates/email_signup1.png
  assets/img/canvas_templates/email_signup2.png
  assets/img/canvas_templates/email_signup3.png
  assets/img/canvas_templates/email_signup4.png
  assets/img/canvas_templates/email_signup5.png
  assets/img/canvas_templates/email_signup6.png
  assets/img/canvas_templates/email_signup7.png
  assets/img/canvas_templates/email_signup8.png
  assets/img/canvas_templates/preference_survey1.png
  assets/img/canvas_templates/preference_survey2.png
  assets/img/canvas_templates/preference_survey3.png
  assets/img/canvas_templates/preference_survey4.png
  assets/img/canvas_templates/preference_survey5.png
  assets/img/canvas_templates/preference_survey6.png
  assets/img/canvas_templates/preference_survey7.png
  assets/img/canvas_templates/preference_survey8.png
Labels: cla-signed

#8684 BD-3803: Update URLs for Facebook Audience Sync TOS
  _docs/_partners/canvas_steps/facebook_audience_sync.md
Labels: cla-signed

#8667 BD-3790 Apply template standards to Custom Data
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_events/nested_objects.md
  _docs/_user_guide/data_and_analytics/custom_data/event_naming_conventions.md
  _docs/_user_guide/data_and_analytics/custom_data/events.md
  _docs/_user_guide/data_and_analytics/custom_data/managing_custom_data.md
  _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
Labels: cla-signed

#8698 Add alt text and clarification for CSV file
  _docs/_user_guide/message_building_by_channel/email/using_locales.md
Labels: cla-signed

#8697 Fix link formatting and add alt text
  _docs/_partners/canvas_steps/facebook_audience_sync.md
Labels: cla-signed

#8700 BD-3808: Add section about error emails for Audience Sync
  _docs/_partners/canvas_steps/overview.md
Labels: cla-signed

#8701 BD-3810 Add soft bounced filter
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#8688 Update uninstall tracking docs
  _docs/_developer_guide/platform_integration_guides/android/analytics/uninstall_tracking.md
  _docs/_user_guide/data_and_analytics/tracking/uninstall_tracking.md
Labels: cla-signed

#8702 notix / update a few images/examples in the android docs for on-call rotation
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/optional_gaid_collection.md
  _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/test_your_basic_integration.md
  assets/img_archive/android_sessions.png
  assets/img_archive/android_support_v4.png
  assets/img_archive/androidstudio2.png
  assets/img_archive/androidstudio3.png
Labels: cla-signed

#8686 BD-3749: Remove mention of full step
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
Labels: cla-signed

#8689 [BD-3805] Partner docs - Justuno
  _docs/_partners/data_and_infrastructure_agility.md
  _docs/_partners/data_and_infrastructure_agility/leads_capture.md
  _docs/_partners/data_and_infrastructure_agility/leads_capture/justuno.md
  _docs/_partners/home.md
  assets/img/justuno/authenticate-braze.png
  assets/img/justuno/enter-subscription-groups.png
  assets/img/justuno/publish-workflow.png
  assets/img/justuno/search-for-braze.png
  assets/img/justuno/select-app.png
  assets/img/justuno/sync-another-property.png
Labels: status: do not merge, cla-signed

#8705 BD-3799 Update Global Control Group membership
  _docs/_user_guide/engagement_tools/testing/global_control_group.md
  assets/img/control_group/control_group1.png
Labels: cla-signed

#8663 BD-3727 B2B Salesforce Sales Cloud use case
  _docs/_user_guide/getting_started/b2b_use_cases.md
  _docs/_user_guide/getting_started/b2b_use_cases/b2b_salesforce_sales_cloud.md
  assets/img/b2b/create_lead_webhook.png
  assets/img/b2b/error_message_invalid_url.png
  assets/img/b2b/salesforce_canvas.png
  assets/img/b2b/salesforce_check_mql.png
  assets/img/b2b/salesforce_create_campaign.png
  assets/img/b2b/salesforce_update_mql.png
  assets/img/b2b/salesforce_webhook.png
  assets/img/b2b/update_lead_webhook.png
Labels: cla-signed

#8699 January 2025 release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2016.md
  _docs/_help/release_notes/2017.md
  _docs/_help/release_notes/2018.md
  _docs/_help/release_notes/2019.md
  _docs/_help/release_notes/2020.md
  _docs/_help/release_notes/2021.md
  _docs/_help/release_notes/2022.md
  _docs/_help/release_notes/2023.md
  _docs/_help/release_notes/2024.md
  _docs/_help/release_notes/2025.md
  _docs/_help/release_notes/2025/1_7_25.md
Labels: cla-signed, release notes

#8703 BD-3811: Clarify default behavior for `merge_behavior` parameter
  _docs/_api/endpoints/user_data/post_user_identify.md
Labels: cla-signed

#8718 Update field_level_encryption.md
  _docs/_user_guide/data_and_analytics/field_level_encryption.md
Labels: cla-signed

#8719 Update get_list_hard_bounces.md
  _docs/_api/endpoints/email/get_list_hard_bounces.md
Labels: cla-signed

#8721 Add missing metadata description to Justuno
  _docs/_partners/data_and_infrastructure_agility/leads_capture/justuno.md
Labels: cla-signed

#8722 Minor typo fixes
  _docs/_partners/canvas_steps/facebook_audience_sync.md
Labels: cla-signed

#8666 Update odicci.md
  _docs/_partners/message_personalization/dynamic_content/odicci.md
Labels: cla-signed

#8685 [BD-3796] Fix redshift tab for datawarehouse
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
Labels: cla-signed

#8725 BD-3495: Add link template settings feature
  _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
  assets/img_archive/link_template_postappend.png
  assets/img_archive/link_template_preappend.png
Labels: cla-signed

#8676 File in_app_message.md committed.
  _lang/pt_br/_includes/aliasing.md
  _lang/pt_br/_includes/appboyBridge.md
  _lang/pt_br/_includes/baidu_deprecation.md
  _lang/pt_br/_includes/best_practices.md
  _lang/pt_br/_includes/campaign_analytics.md
  _lang/pt_br/_includes/content_cards.md
  _lang/pt_br/_includes/create_content_block.md
  _lang/pt_br/_includes/create_transformation.md
  _lang/pt_br/_includes/gifs.md
  _lang/pt_br/_includes/image_specs.md
  _lang/pt_br/_includes/in_app_message.md
  _lang/pt_br/_includes/in_app_messaging.md
  _lang/pt_br/_includes/inapp_message_troubleshooting.md
  _lang/pt_br/_includes/initial_setup.md
  _lang/pt_br/_includes/metrics.md
  _lang/pt_br/_includes/naming_convention.md
  _lang/pt_br/_includes/preference_center_warning.md
  _lang/pt_br/_includes/prerequisites.md
  _lang/pt_br/_includes/release_type.md
  _lang/pt_br/_includes/sdk_auth_alert.md
  _lang/pt_br/_includes/setting_user_ids.md
  _lang/pt_br/_includes/short_and_long_codes.md
  _lang/pt_br/_includes/updating_currents.md
  _lang/pt_br/_includes/web-v4-rename.md
  _lang/pt_br/_includes/windows_deprecation.md
Labels: cla-signed

#8677 File in_app_message.md committed.
  _lang/ko/_includes/aliasing.md
  _lang/ko/_includes/baidu_deprecation.md
  _lang/ko/_includes/best_practices.md
  _lang/ko/_includes/content_cards.md
  _lang/ko/_includes/gifs.md
  _lang/ko/_includes/in_app_message.md
  _lang/ko/_includes/in_app_messaging.md
  _lang/ko/_includes/initial_setup.md
  _lang/ko/_includes/naming_convention.md
  _lang/ko/_includes/prerequisites.md
  _lang/ko/_includes/setting_user_ids.md
  _lang/ko/_includes/short_and_long_codes.md
  _lang/ko/_includes/web-v4-rename.md
  _lang/ko/_includes/windows_deprecation.md
Labels: cla-signed

#8710 BD-3779: Automated emails and Message Activity Log entries EA
  _docs/_help/help_articles/api/webhook_connected_content_errors.md
Labels: cla-signed

#8729 BD-3823 Add EA banner to importing with email and phone
  _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Labels: cla-signed

#8720 chore(nav): reordered pages
  _docs/_developer_guide/authentication.md
  _docs/_developer_guide/banner_cards.md
  _docs/_developer_guide/changelogs.md
  _docs/_developer_guide/content_cards.md
  _docs/_developer_guide/debugging.md
  _docs/_developer_guide/disclosures.md
  _docs/_developer_guide/feature_flags.md
  _docs/_developer_guide/home.md
  _docs/_developer_guide/platform_integration_guides.md
  _docs/_developer_guide/sending_test_messages.md
Labels: cla-signed

#8730 snippet
  _includes/search_page.html
Labels: cla-signed

#8731 Search snippets
  _includes/search_page.html
  assets/css/search_page.scss
Labels: cla-signed

#8723 Added SDK reference page to nav
  _docs/_developer_guide/references.md
Labels: cla-signed

#8717 BD-3813: Update mentions of Gimbal to Infillion
  _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/beacon_integration.md
  _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/advanced_use_cases/beacon_integration.md
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/location.md
  _docs/_partners/message_personalization/location/infillion.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/location_tracking.md
  _docs/_user_guide/engagement_tools/segments/location_targeting.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8734 Add note about English-language only contributions
  _docs/_contributing/home.md
Labels: cla-signed

#8736 [hotfix] Add missing article titles to search results
  _includes/search_page.html
Labels: cla-signed

#8737 Leftover deploy - January 9, 2025
  _docs/_contributing/home.md
  _includes/search_page.html
Labels: Deploy

#8739 [escalation-20250109-chrobinson-contentcardlimits] Add CC feed limit limit explanation back
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
Labels: cla-signed

#8724 Update swift_idfv.md
  _docs/_developer_guide/platform_integration_guides/swift/analytics/swift_idfv.md
Labels: cla-signed, In Review

#8735 BD-3496 Apply template standards to Cloud Ingestion
  _docs/_user_guide/data_and_analytics/cloud_ingestion.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/connected_sources.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/delete_users.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/faqs.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/file_storage_integrations.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md
Labels: cla-signed

#8740 BD-3615 Clarify criteria in user archival
  _docs/_hidden/other/user_archival.md
Labels: cla-signed

#8741 Set links on references page to 'master' branch
  _docs/_developer_guide/references.md
Labels: cla-signed

#8744 BD-3795 Add link to custom attributes in custom data
  _docs/_user_guide/data_and_analytics/custom_data/managing_custom_data.md
Labels: cla-signed

#8756 Re-adding include to fix some langs
  _includes/archive/android/gifs.md
Labels: cla-signed

#8694 BD-3757: Using an email address to trigger campaigns or Canvases GA [MERGE JAN 13]
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
  _docs/_api/objects_filters/recipient_object.md
Labels: cla-signed

#8746 BD-3826 + BD-3625: Add AU addresses
  _docs/_api/basics.md
  _docs/_contributing/styling_examples.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle.md
  _docs/_partners/isv_partners/cohort_import.md
  _docs/_user_guide/administrative/access_braze/sdk_endpoints.md
  _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
  _docs/_user_guide/data_and_analytics/cloud_ingestion/connected_sources.md
Labels: cla-signed

#8712 BD-3814 Apply template standards to Your Reports
  _docs/_user_guide/data_and_analytics/reporting/configuring_reporting.md
  _docs/_user_guide/data_and_analytics/reporting/data_by_segments.md
  _docs/_user_guide/data_and_analytics/reporting/engagement_reports.md
  _docs/_user_guide/data_and_analytics/reporting/funnel_reports.md
  _docs/_user_guide/data_and_analytics/reporting/global_control_group_reporting.md
  _docs/_user_guide/data_and_analytics/reporting/report_builder.md
  _docs/_user_guide/data_and_analytics/reporting/reports_overview.md
  _docs/_user_guide/data_and_analytics/reporting/retention_reports.md
  _docs/_user_guide/data_and_analytics/reporting/revenue_report.md
  _docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md
Labels: cla-signed

#8696 BD-3752: Price drop notifications and back-in-stock notifications GA [MERGE JAN 13]
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/back_in_stock_notifications.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/price_drop_notifications.md
Labels: cla-signed

#8713 BD-3789: Add article about Braze data centers
  _docs/_user_guide/data_and_analytics/data_centers.md
Labels: cla-signed

#8748 Update error threshold in the docs to keep them up to date
  _docs/_help/help_articles/api/webhook_connected_content_errors.md
Labels: cla-signed

#8755 make external links open its own tab
  _config.yml
  assets/js/documents.js
Labels: cla-signed

#8692 BD-3759: Phone number for identifying and deleting users GA [MERGE JAN 13]
  _docs/_api/endpoints/user_data/post_user_delete.md
  _docs/_api/endpoints/user_data/post_user_identify.md
Labels: cla-signed

#8761 BD-3821 Update max size for Custom Attributes
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md
  _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
Labels: cla-signed

#8738 File in_app_message.md committed.
  _lang/fr_fr/_includes/aliasing.md
  _lang/fr_fr/_includes/appboyBridge.md
  _lang/fr_fr/_includes/baidu_deprecation.md
  _lang/fr_fr/_includes/best_practices.md
  _lang/fr_fr/_includes/campaign_analytics.md
  _lang/fr_fr/_includes/content_cards.md
  _lang/fr_fr/_includes/create_content_block.md
  _lang/fr_fr/_includes/create_transformation.md
  _lang/fr_fr/_includes/gifs.md
  _lang/fr_fr/_includes/image_specs.md
  _lang/fr_fr/_includes/in_app_message.md
  _lang/fr_fr/_includes/in_app_messaging.md
  _lang/fr_fr/_includes/inapp_message_troubleshooting.md
  _lang/fr_fr/_includes/initial_setup.md
  _lang/fr_fr/_includes/naming_convention.md
  _lang/fr_fr/_includes/preference_center_warning.md
  _lang/fr_fr/_includes/prerequisites.md
  _lang/fr_fr/_includes/release_type.md
  _lang/fr_fr/_includes/sdk_auth_alert.md
  _lang/fr_fr/_includes/setting_user_ids.md
  _lang/fr_fr/_includes/short_and_long_codes.md
  _lang/fr_fr/_includes/updating_currents.md
  _lang/fr_fr/_includes/web-v4-rename.md
  _lang/fr_fr/_includes/windows_deprecation.md
Labels: cla-signed

#8727 BD-3755: Preview for selection GA
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/selections.md
Labels: cla-signed

#8770 Search snippets
  _includes/header_search.html
  _includes/search_page.html
  assets/js/algolia_header_search.js
  assets/js/algolia_main_search.js
Labels: cla-signed

#8771 Small typo in Android content_cards.md
  _includes/developer_guide/android/content_cards.md
Labels: cla-signed

#8674 [BD-3275] Cordova cleanup
  _docs/_developer_guide/platform_integration_guides/cordova/analytics.md
  _docs/_developer_guide/platform_integration_guides/cordova/content_cards.md
  _docs/_developer_guide/platform_integration_guides/cordova/in_app_messages.md
  _docs/_developer_guide/platform_integration_guides/cordova/initial_setup.md
  _docs/_developer_guide/platform_integration_guides/cordova/initial_setup/integration.md
  _docs/_developer_guide/platform_integration_guides/cordova/news_feed.md
  _docs/_developer_guide/platform_integration_guides/cordova/other_integrations.md
  _docs/_developer_guide/platform_integration_guides/cordova/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/cordova/sdk_integration.md
  _includes/cordova/prerequisites.md
  _includes/developer_guide/prerequisites/cordova.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8774 Move comment back in broken_redirect_list.js
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8775 BD-3830: Clarify locales aren't supported in email templates
  _docs/_user_guide/message_building_by_channel/email/using_locales.md
Labels: cla-signed

#8733 [DI-6981] Update documentation for anonymous users in Segment
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
  assets/img/segment/segment_currents_data_config.png
  assets/img/segment/segment_currents_integration_config.png
Labels: cla-signed

#8769 Add rake steps to contributing home.md
  _docs/_contributing/home.md
Labels: cla-signed

#8776 Re-adding '_/includes/cordova/prerequisites.md'
  _includes/cordova/prerequisites.md
Labels: cla-signed

#8772 BD-3815: API usage dashboard GA
  _docs/_api/api_limits.md
  _docs/_user_guide/analytics/dashboard.md
  _docs/_user_guide/analytics/dashboard/api_usage_dashboard.md
Labels: cla-signed

#8781 BD-3750: Clarify behavior for "at a specific time" for delays
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
Labels: cla-signed

#8783 Fix permalink error
  _docs/_docs_pages/redirects/api_usage_dashboard.md
Labels: cla-signed

#8784 [ES Lang] Reverting translated include
  _lang/es/_user_guide/message_building_by_channel/sms/sms_campaign_analytics/message_usage.md
  _lang/es/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign_analytics/message_usage.md
Labels: cla-signed

#8786 BD-3838 Add CORS info to heatmap docs
  _includes/campaign_analytics.md
Labels: cla-signed

#8787 Add troubleshooting steps for permalink
  _docs/_contributing/troubleshooting.md
Labels: cla-signed

#8675 [PQ-7055] Clarify Unique Recipients
  _docs/_user_guide/data/report_metrics.md
Labels: cla-signed

#8789 BD-3710: Add info about Content Blocks with Connected Content
  _docs/_user_guide/engagement_tools/canvas/testing_canvases/preview_user_paths.md
Labels: cla-signed

#8793 BD-3736: Clarify expected behavior for entry in user previews
  _docs/_user_guide/engagement_tools/canvas/testing_canvases/preview_user_paths.md
Labels: cla-signed

#8795 BD-3450: Add FAQ about building Canvases
  _docs/_user_guide/engagement_tools/canvas/faqs.md
Labels: cla-signed

#8788 BD-3837: Update behavior when external_id and alias aren't included
  _docs/_user_guide/data/user_data_collection/user_import.md
Labels: cla-signed

#8790 BD-3770: Add detail about orange connections in Canvas steps
  _docs/_user_guide/engagement_tools/canvas/canvas_components.md
Labels: cla-signed

#8796 BD-3711: Add alert for custom attribute data type check
  _docs/_user_guide/data/custom_data/custom_attributes.md
Labels: cla-signed

#8791 Add where to find API usage dashboard
  _docs/_user_guide/analytics/dashboard/api_usage_dashboard.md
Labels: cla-signed

#8797 add link to Snowflake quickstart guide (developed/hosted by snowflake)
  _docs/_user_guide/data/cloud_ingestion/integrations.md
Labels: cla-signed

#8792 BD-3716: Update intro and style edits
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
Labels: cla-signed

#8799 BD-3504 Document CSV user import behavior
  _docs/_user_guide/data/user_data_collection/user_import.md
  assets/img/csvfilter.png
Labels: cla-signed

#8762 [BD-3275] Flutter cleanup
  _docs/_developer_guide/platform_integration_guides/flutter/analytics.md
  _docs/_developer_guide/platform_integration_guides/flutter/content_cards.md
  _docs/_developer_guide/platform_integration_guides/flutter/in_app_messages.md
  _docs/_developer_guide/platform_integration_guides/flutter/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/flutter/sdk_integration.md
  _includes/developer_guide/prerequisites/flutter.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8777 [BD-3275] Xamarin cleanup
  _docs/_developer_guide/platform_integration_guides/xamarin/analytics.md
  _docs/_developer_guide/platform_integration_guides/xamarin/content_cards.md
  _docs/_developer_guide/platform_integration_guides/xamarin/in_app_messages.md
  _docs/_developer_guide/platform_integration_guides/xamarin/news_feed.md
  _docs/_developer_guide/platform_integration_guides/xamarin/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/xamarin/sdk_integration.md
  _includes/developer_guide/prerequisites/xamarin.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8773 [BD-3275] React Native cleanup
  _docs/_developer_guide/platform_integration_guides/react_native/analytics.md
  _docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
  _docs/_developer_guide/platform_integration_guides/react_native/in_app_messages.md
  _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
  _docs/_developer_guide/platform_integration_guides/react_native/sample_app.md
  _docs/_developer_guide/platform_integration_guides/react_native/sdk_integration.md
  _includes/developer_guide/prerequisites/react_native.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8709 BD-3726: Add more details for sending emails for SparkPost
  _docs/_user_guide/message_building_by_channel/email/apple_mail/email_private_relay_apple_SSO.md
Labels: cla-signed

#8802 BD-3841 Jan 2025 Meta update
  _docs/_user_guide/message_building_by_channel/whatsapp/meta_resources.md
Labels: cla-signed

#8804 [bdocs] Add command to print unique markdown syntax
  _docs/_contributing/bdocs.md
  bdocs
  scripts/print_unique_syntax.sh
Labels: cla-signed

#8803 BD-3452: Update steps and reorganize content for Inbox Vision
  _docs/_user_guide/message_building_by_channel/email/inbox_vision.md
Labels: cla-signed

#8807 BD-3696: Add info about Intelligent Channel filters
  _docs/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md
Labels: cla-signed

#8808 BD-3510: Clarify conversions dashboard and custom event metrics
  _docs/_user_guide/analytics/dashboard/conversions_dashboard.md
Labels: cla-signed

#8800 BD-3835 Update MMS message limits
  _docs/_user_guide/message_building_by_channel/sms/mms/about_mms.md
Labels: cla-signed

#8809 BD-3748: Clarify YAML description for SCIM endpoint
  _docs/_api/endpoints/scim.md
  _docs/_api/endpoints/scim/get_see_user_account_information.md
  _docs/_api/home.md
Labels: cla-signed

#8806 Update docs to add 598 code reflecting recent changes
  _docs/_help/help_articles/api/webhook_connected_content_errors.md
Labels: cla-signed

#8810 BD-3558: Updates to Destination framework options for Segment
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
Labels: cla-signed

#8811 Update drag_and_drop.md
  _docs/_user_guide/engagement_tools/landing_pages/drag_and_drop.md
Labels: cla-signed

#8812 Fix broken data link
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8814 BD-3845: Add mention of product ID naming conventions best practices
  _docs/_api/objects_filters/purchase_object.md
  _docs/_user_guide/data/custom_data/purchase_events.md
Labels: cla-signed

#8813 BD-3843: Update user identifier columns description
  _docs/_user_guide/data/cloud_ingestion/integrations.md
Labels: cla-signed

#8818 [bdocs] Fix ulinks YAML handling
  _docs/_contributing/bdocs.md
  scripts/update_old_links.py
Labels: cla-signed

#8817 [BD-3275] TV & OTT tweaks
  _docs/_developer_guide/home.md
  _docs/_developer_guide/platform_integration_guides/tv_and_ott.md
Labels: cla-signed

#8815 Banner Cards: Add instructions for Swift resizing
  _docs/_developer_guide/banner_cards/integration.md
Labels: cla-signed

#8805 [SDK-5251] Update information on `getInitialPushPayload` in React Native
  _docs/_developer_guide/platforms/react_native/push_notifications.md
Labels: cla-signed

#8820 BD-3824 Embed IAM video
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
Labels: cla-signed

#8824 BD-3833 Update Entitlements Handbook to fix broken link
  assets/download_file/Braze_Entitlements_Handbook_24.pdf
Labels: cla-signed

#8704 Update example code for Custom In-App Message Listeners `beforeInAppMessageDisplayed`
  _includes/developer_guide/android/in_app_messages/customization/listeners.md
Labels: cla-signed

#8826 Improving contributing docs
  _docs/_contributing/home.md
  _docs/_contributing/local_environment.md
  _docs/_contributing/your_first_contribution.md
  assets/img/contributing/text_editor_with_terminal.png
Labels: cla-signed

#8835 Change redirect to a number with max
  _includes/html_include.html
  _layouts/broken_page.html
  _layouts/redirect.html
  assets/js/hash_redirect.js
Labels: cla-signed

#8707 BD-3812 Suppression lists docs MERGE 1/20
  _docs/_user_guide/engagement_tools/segments.md
  _docs/_user_guide/engagement_tools/segments/suppression_lists.md
  _docs/_user_guide/engagement_tools/segments/troubleshooting.md
  assets/img/active_suppression_list.png
  assets/img/create_suppression_list.png
  assets/img/exception_tags.png
  assets/img/suppression_list_filters.png
  assets/img/suppression_lists_home.png
Labels: cla-signed

#8837 BD-3853 Correct Databricks CDI payload type
  _docs/_user_guide/data/cloud_ingestion/sync_catalogs_data.md
Labels: cla-signed

#8840 BD-3857: Fix links that include `redirected=true`
  _docs/_api/endpoints/messaging/duplicate_campaigns.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
  _docs/_partners/message_orchestration/additional_channels/mobile_wallet/passkit.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_backfill.md
  _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/punchh.md
  _docs/_partners/message_orchestration/channel_extensions/surveys/iterate.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/best_practices.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/localizing_a_campaign.md
  _includes/developer_guide/android/push_notifications/android_tv.md
Labels: cla-signed

#8827 Add `platforms` to `nav_expand_lists`
  _config.yml
Labels: cla-signed

#8836 BD-3859 Trustpilot partner docs
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/dynamic_content.md
  _docs/_partners/message_personalization/dynamic_content/trustpilot.md
  assets/img/trustpilot_connected_content_example.png
  assets/img/trustpilot_personalized_email.png
Labels: cla-signed

#8842 BD-3863 Add permissions to SCIM appendix
  _docs/_hidden/misc_reference/scim_api_appendix.md
Labels: cla-signed

#8843 BD-3834 Add note about dispatch_id to Currents events
  _docs/_user_guide/data/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#8839 Clarify endpoints with shared rate limits
  _docs/_api/api_limits.md
Labels: cla-signed

#8847 Update YAML redirects for campaign and Canvas analytics
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/campaign_funnel_report.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/retention_reports.md
  _docs/_user_guide/engagement_tools/canvas/testing_canvases/canvas_funnel_reports.md
  _docs/_user_guide/engagement_tools/canvas/testing_canvases/retention_reports.md
Labels: cla-signed

#8852 Fixing contributing docs for forks
  _docs/_contributing/git_and_github.md
  _docs/_contributing/local_environment.md
  _docs/_contributing/your_first_contribution.md
  assets/img/contributing/github/choose_base_repository.png
  assets/img/contributing/github/compare_across_forks.png
  assets/img/contributing/github/propose_changes.png
Labels: cla-signed

#8823 Update creating_a_webhook.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
Labels: cla-signed

#8854 Android small updates
  _includes/archive/setting_user_ids/aliasing.md
  _includes/developer_guide/android/_global/gifs.md
  _includes/developer_guide/android/initialization/runtime_configuration.md
Labels: cla-signed

#8859 BD-3870 Add Early Access note for custom data deletion
  _docs/_user_guide/data/custom_data/managing_custom_data.md
Labels: cla-signed

#8845 [BD-3807] List supported HTML tags
  _includes/developer_guide/android/push_notifications/customization/html_messages.md
Labels: cla-signed

#8860 Update broken_redirect_list.js
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8861 Leftover deploy - January 23, 2024
  _docs/_api/api_limits.md
  _docs/_contributing/git_and_github.md
  _docs/_contributing/local_environment.md
  _docs/_contributing/your_first_contribution.md
  _docs/_hidden/misc_reference/scim_api_appendix.md
  _docs/_user_guide/brazeai/intelligence/faqs.md
  _docs/_user_guide/data/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data/custom_data/managing_custom_data.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/campaign_funnel_report.md
  _docs/_user_guide/engagement_tools/campaigns/testing_and_more/retention_reports.md
  _docs/_user_guide/engagement_tools/canvas/testing_canvases/canvas_funnel_reports.md
  _docs/_user_guide/engagement_tools/canvas/testing_canvases/retention_reports.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  _includes/archive/setting_user_ids/aliasing.md
  _includes/developer_guide/android/_global/gifs.md
  _includes/developer_guide/android/in_app_messages.md
  _includes/developer_guide/android/initialization/runtime_configuration.md
  _includes/developer_guide/android/push_notifications/customization/html_messages.md
  assets/img/contributing/github/choose_base_repository.png
  assets/img/contributing/github/compare_across_forks.png
  assets/img/contributing/github/propose_changes.png
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#8863 Add redirect
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8865 Revert "Update creating_a_webhook.md"
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
Labels: cla-signed

#8864 add page language to feedback
  assets/js/feedback.js
Labels: cla-signed

#8858 BD-3695 Update user permissions table
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/adding_users_to_your_dashboard.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/teams.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
  _includes/permissions.md
Labels: cla-signed

#8869 Terms to know audit
  _docs/_user_guide/getting_started/terms_to_know.md
Labels: cla-signed

#8870 BD-3869: Update "SMS Delivery" to "SMS Click"
  _docs/_user_guide/analytics/dashboard/conversions_dashboard.md
Labels: cla-signed

#8825 [CO-3243] Added documentation for scheduled bulk users merge - MERGE 1/27
  _docs/_user_guide/engagement_tools/segments/user_profiles/duplicate_users.md
  assets/img/audience_management/duplicate_users/bulk_merging/select_scheduled_merge_rules.png
Labels: cla-signed

#8866 BD-3871 Update Databricks CDI payload type
  _docs/_user_guide/data/cloud_ingestion/integrations.md
  _docs/_user_guide/data/cloud_ingestion/sync_catalogs_data.md
Labels: cla-signed

#8868 BD-3867 Update landing page custom domains
  _docs/_user_guide/engagement_tools/landing_pages/connect_domain.md
Labels: cla-signed

#8873 [BD-3879] Fixing links on content_cards.md
  _docs/_developer_guide/content_cards.md
Labels: cla-signed

#8855 [Currents] Add note about why Currents requires s3:GetObject permissions - PQ-7758
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
Labels: cla-signed

#8853 BD-3840: Notifications for exceeding FCM rate limit EA
  _includes/developer_guide/android/push_notifications.md
Labels: cla-signed

#8872 BD-3873 Considerations for connected audience filters
  _docs/_api/objects_filters/connected_audience.md
Labels: cla-signed

#8874 BD-3860: Clarify column name and description for Braze user permissions
  _docs/_user_guide/getting_started/workspaces.md
Labels: cla-signed

#8875 Removing duplicate push notification info for Android
  _docs/_developer_guide/platforms/android/push_notifications/displaying_notifications.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8856 ugprade web sdk
  _docs/_docs_pages/service_worker.js
  _includes/analytics.html
Labels: cla-signed

#8879 Remove expanded TOC in Intelligence FAQ
  _docs/_user_guide/brazeai/intelligence/faqs.md
Labels: cla-signed

#8878 BD-3792: Clarify how a user moves through Canvas
  _docs/_user_guide/engagement_tools/canvas/canvas_components.md
  _docs/_user_guide/engagement_tools/canvas/get_started/the_basics.md
Labels: cla-signed

#8833 banners web
  _docs/_developer_guide/banner_cards/integration.md
Labels: cla-signed

#8882 Update privacy_manifest.md
  _docs/_developer_guide/platforms/swift/privacy_manifest.md
Labels: cla-signed

#8885 Updating 'sdk_min_versions' chips
  _plugins/sdk_min_versions_tag.rb
Labels: cla-signed

#8884 Update Loudly Notify Docs
  _docs/_help/help_articles/api/webhook_connected_content_errors.md
Labels: cla-signed

#8886 Clarify subscription status row details
  _docs/_user_guide/getting_started/workspaces.md
Labels: cla-signed
