Repository braze-inc/braze-docs, pull requests merged in 2025-09, with the labels that each got.

#10461 [BD-5127] Update image example
  assets/img/email_settings/reply_to_address.png
Labels: fixes an issue

#10476 [BD-5120] Fix Liquid tag
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/ecommerce_use_cases.md
Labels: fixes an issue

#10482 Deploy - September 4, 2025
  _docs/_api/objects_filters/purchase_object.md
  _docs/_help/release_notes/2023/4_4_23.md
  _docs/_hidden/archive_docs/scuba.md
  _docs/_hidden/other/support_contact.md
  _docs/_partners/data_and_analytics.md
  _docs/_partners/ecommerce/shopify.md
  _docs/_partners/ecommerce/shopify/discount_codes.md
  _docs/_partners/ecommerce/shopify/multiple_stores.md
  _docs/_partners/ecommerce/shopify/shopify_catalogs.md
  _docs/_partners/ecommerce/shopify/shopify_custom_integration.md
  _docs/_partners/ecommerce/shopify/shopify_data_features.md
  _docs/_partners/ecommerce/shopify/shopify_standard_integration_third_party_tagging.md
  _docs/_partners/message_personalization/dynamic_content/visual_and_interactive_content/blings.md
  _docs/_user_guide/brazeai/recommendations.md
  _docs/_user_guide/brazeai/recommendations/creating_recommendations/rules_based.md
  _docs/_user_guide/data/activation/custom_data/recommended_events/ecommerce_events.md
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/ecommerce_use_cases.md
  _docs/_user_guide/engagement_tools/templates_and_media/media_library.md
  _docs/_user_guide/message_building_by_channel/banners/creating_campaigns.md
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
  _includes/alerts/important_alerts.md
  assets/img/Shopify/third_party_enable.png
  assets/img/blings/blings_braze_campaign.png
  assets/img/connected_content/add_credential_button.png
  assets/img/connected_content/basic_auth_mgmt.png
  assets/img/connected_content/basic_auth_token.png
  assets/img/connected_content/token_auth.png
  assets/js/broken_redirect_list.js
Labels: Deploy

#10190 added content card inbox tutorial + small scrolly fix
  _docs/_developer_guide/content_cards/content_card_inbox.md
  assets/css/scrollycode.scss
Labels: cla-signed

#10533 [BD-5172] & [BD-5172] Update URLs for Liquid filters
  _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
Labels: fixes an issue

#10568 [BD-5190] Clarify IP pool selection in Target Audiences step of email composer
  _docs/_user_guide/message_building_by_channel/email/email_setup.md
Labels: fixes an issue

#10546 BD-5182 Update RCS billing and definitions
  _docs/_user_guide/message_building_by_channel/sms_mms_rcs/rcs.md
  _docs/_user_guide/message_building_by_channel/sms_mms_rcs/segments.md
Labels: status: in progress

#10615 Deploy - September 24, 2025
  _docs/_user_guide/message_building_by_channel/sms_mms_rcs/rcs.md
  _docs/_user_guide/message_building_by_channel/sms_mms_rcs/segments.md
  _docs/_user_guide/message_building_by_channel/whatsapp/overview/transfer_between_workspaces.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/product_messages.md
  _includes/developer_guide/react_native/push_notifications.md
  _includes/developer_guide/react_native/push_notifications/push_stories.md
  _includes/developer_guide/react_native/push_notifications/rich.md
  assets/img/whatsapp/archive_subscription_group.png
  assets/img/whatsapp/example_response_message.png
  assets/img/whatsapp/multi-product_message_layout.png
  assets/img/whatsapp/response_message_layouts.png
Labels: Deploy

#10616 [BD-5168] Clarify Soft Bounces and Deferrals metrics
  _docs/_user_guide/data/activation/report_metrics.md
Labels: fixes an issue
