Repository braze-inc/braze-docs, pull requests merged in 2025-08, with the labels that each got.

#10200 BD-5003-2 Update Suppression Lists
  _docs/_user_guide/engagement_tools/segments/suppression_lists.md
Labels: cla-signed

#10162 SF KB articles to Braze docs migration: CLX pt. 1
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/exit_criteria.md
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/launching_canvas_flow.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
  _docs/_user_guide/engagement_tools/canvas/testing_canvases/measuring_and_testing_with_canvas_analytics.md
  _docs/_user_guide/engagement_tools/messaging_fundamentals/reeligibility.md
  _docs/_user_guide/engagement_tools/testing/race_conditions.md
Labels: cla-signed

#10208 BD-5022 Add diagram to Managing Content page
  _docs/_contributing/content_management/pages.md
  assets/img/contributing/article_anatomy.png
Labels: cla-signed

#10209 BD-4950: Clarify time data type for Context step
  _docs/_user_guide/engagement_tools/canvas/canvas_components/context.md
Labels: cla-signed

#10224 [PP-4757] fix link with extra slash
  _docs/_partners/ecommerce/shopify/shopify_custom_integration.md
Labels: cla-signed

#10227 Update suppression_lists.md
  _docs/_user_guide/engagement_tools/segments/suppression_lists.md
Labels: cla-signed

#10171 Update faq.md
  _includes/banners/faq.md
Labels: cla-signed

#10180 Update know_before_send.md
  _docs/_user_guide/engagement_tools/messaging_fundamentals/know_before_send.md
Labels: cla-signed

#10182 Update about.md
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
Labels: cla-signed

#10216 PUSH-408: New API fields for /campaigns/details endpoint - MERGE 8/5
  _docs/_api/endpoints/export/campaigns/get_campaign_details.md
Labels: cla-signed

#10217 Minor edit to PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE
Labels: cla-signed

#10115 BD-4636: Add property details for Push Notification Token State Change events for Currents
  _docs/_user_guide/data/braze_currents/event_glossary/customer_behavior_events.md
Labels: cla-signed

#10229 Wistia embedded video support
  _docs/_contributing/styling_examples.md
  _includes/video.html
Labels: cla-signed

#10225 Refactoring additional dropdown types and adding disclosure for CoPil…
  _docs/_hidden/other/documentation_request.md
Labels: cla-signed

#10241 Notes about PR title and body for copilot-instructions.md
  .github/copilot-instructions.md
Labels: cla-signed

#10245 Added video to landing page main page
  _docs/_user_guide/engagement_tools/landing_pages.md
Labels: cla-signed

#10240 [BD-5041] Improve public/hidden handling for bdocs
  bdocs
Labels: do not merge, cla-signed

#10113 BD-3441: Clarify how Braze evaluates users in Target Audiences first then confirms entry criteria
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/messaging_fundamentals/targeting_users.md
  _docs/_user_guide/message_building_by_channel/banners/creating_campaigns.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
  _docs/_user_guide/message_building_by_channel/sms_mms_rcs/rcs/create.md
  _docs/_user_guide/message_building_by_channel/sms_mms_rcs/sms/create.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md
  _includes/target_audiences.md
Labels: cla-signed

#10281 [BD-4990] MCP server
  _docs/_developer_guide/mcp_server.md
  _docs/_developer_guide/mcp_server/available_api_functions.md
  _docs/_developer_guide/mcp_server/setup.md
  _docs/_developer_guide/mcp_server/usage.md
  _docs/_developer_guide/offerfit.md
  _docs/_user_guide/brazeai/mcp_server.md
  _docs/_user_guide/brazeai/mcp_server/available_api_functions.md
  _docs/_user_guide/brazeai/mcp_server/setup.md
  _docs/_user_guide/brazeai/mcp_server/usage.md
  _includes/mcp_server/about.md
  _includes/mcp_server/available_api_functions.md
  _includes/mcp_server/beta_alert.md
  _includes/mcp_server/legal_disclaimer.md
  _includes/mcp_server/prerequisites.md
  _includes/mcp_server/setup.md
  _includes/mcp_server/usage.md
  assets/img/mcp_server/claude/get_details_about_a_canvas_id.png
  assets/img/mcp_server/claude/show_my_recent_canvases.png
  assets/img/mcp_server/claude/what_are_my_available_braze_functions.png
  assets/img/mcp_server/cursor/get_details_about_a_canvas_id.png
  assets/img/mcp_server/cursor/show_me_my_recent_canvases.png
  assets/img/mcp_server/cursor/what_are_my_available_braze_functions.png
Labels: do not merge

#10070 BD-4549: Add a few BrazeAI use cases
  _docs/_user_guide/brazeai/predictive_churn/use_case.md
  _docs/_user_guide/brazeai/predictive_events/use_case.md
  _docs/_user_guide/brazeai/recommendations/use_case.md
  assets/img/ai_use_cases/ab_test_personalized_variant.png
  assets/img/ai_use_cases/ab_test_winning_variant.png
  assets/img/ai_use_cases/canvas_paths_by_intent.png
  assets/img/ai_use_cases/churn_definition.png
  assets/img/ai_use_cases/churn_risk_score.png
  assets/img/ai_use_cases/cta_testing_variants.png
  assets/img/ai_use_cases/event_likelihood_score.png
  assets/img/ai_use_cases/prediction_settings.png
  assets/img/ai_use_cases/recommendation_add_personalization.png
  assets/img/ai_use_cases/recommendation_liquid.png
  assets/img/ai_use_cases/recommendation_rendered.png
  assets/img/ai_use_cases/tone_testing_variants.png
  assets/img/ai_use_cases/winning_variant_results.png
Labels: status: done, cla-signed

#10380 August 2025 release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2025.md
  _docs/_help/release_notes/2025/8_19_25.md
Labels: Deploy

#10172 [SDK-5974] [BD-5080] Banner Properties
  _docs/_developer_guide/banners/analytics.md
  _docs/_developer_guide/banners/placements.md
  _docs/_developer_guide/banners/testing.md
  _docs/_developer_guide/feature_flags.md
  _docs/_developer_guide/feature_flags/create.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2025/4_1_25.md
  _docs/_user_guide/message_building_by_channel/banners/analytics.md
  _docs/_user_guide/message_building_by_channel/banners/creating_campaigns.md
  _docs/_user_guide/message_building_by_channel/banners/testing.md
  _includes/banners/about.md
  _includes/banners/faq.md
  _includes/banners/placement_requests.md
  _lang/de/_includes/banners/about.md
  _lang/de/_includes/banners/faq.md
  _lang/de/_includes/banners/placement_requests.md
  assets/img/banners/add_property.png
  assets/img/banners/example_property.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#10372 [SDK-5932] Docs Audit for Android SDK - IAMs
  _docs/_developer_guide/in_app_messages/triggering_messages.md
  _includes/developer_guide/_shared/in_app_messages/message_types/android.md
  _includes/developer_guide/android/_global/deep_linking.md
  _includes/developer_guide/android/_global/gifs.md
  _includes/developer_guide/android/in_app_messages.md
  _includes/developer_guide/android/in_app_messages/customization.md
  _includes/developer_guide/android/in_app_messages/html_messages.md
  _includes/inapp_message_troubleshooting.md
Labels: cla-signed, sdks-doc-audit

#10148 [BD-0000] GH Action: Link PRs to Issues using BD numbers
  .github/workflows/link-issue-to-pr.yml
Labels: cla-signed, fixes an issue
