Repository braze-inc/braze-docs, pull requests merged in 2025-05, with the labels that each got.

#9570 [Untracked SDKs] Update nullability syntax for `FeatureFlags.featureFlag(id:)` in all SDKs
  _docs/_developer_guide/feature_flags/create.md
Labels: sdks-doc-audit

#9598 Addressing questions around Context step
  _docs/_user_guide/engagement_tools/canvas/canvas_components/context.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
  assets/img/context_example1.png
  assets/img/context_example2.png
Labels: In Review

#9625 Deploy - May 6, 2025
  _docs/_contributing/troubleshooting.md
  _docs/_developer_guide/feature_flags/create.md
  _docs/_partners/ecommerce/shopify/shopify_data_features.md
  _docs/_user_guide/data/custom_data/custom_events/recommended_events.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/copying_to_workspace.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/context.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/ecommerce_use_cases.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases.md
  _docs/_user_guide/engagement_tools/messaging_fundamentals.md
  _docs/_user_guide/engagement_tools/messaging_fundamentals/copying_across_workspaces.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/price_drop_notifications.md
  assets/img/context_example1.png
  assets/img/context_example2.png
  assets/img/contributing/github/build_preview_404.png
  assets/img_archive/ecommerce_filters.png
  assets/js/broken_redirect_list.js
Labels: Deploy

#9577 Screenshot updates week 2 – Bre pt.1
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize/email_capture_form.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/templates/simple_survey.md
  assets/img/ai_copywriter/ai_copywriter_iam.png
  assets/img/email_capture.png
  assets/img/iam/collect-attributes.png
  assets/img/iam/color-theme-picker.png
  assets/img/iam/confirmation-option.png
  assets/img/iam/confirmation-page.png
  assets/img/iam/iam-survey.png
  assets/img/iam/iam-survey2.png
  assets/img/primary-secondary-buttons.png
  assets/img_archive/iam_compose.png
  assets/img_archive/re-evaluate-iam-membership.png
Labels: 2024-docs-brand-refresh

#9572 add language cleanup script
  scripts/clean_orphaned_translations.py
Labels: status: do not merge

#9564 Screenshots - Rachel - Small Batch
  _docs/_user_guide/message_building_by_channel/sms/mms/contact_card.md
  _docs/_user_guide/message_building_by_channel/sms/sms_geographic_permissions.md
  _docs/_user_guide/message_building_by_channel/sms/sms_subscription_group.md
  assets/img/sms/allowlist_dropdown.png
  assets/img/sms/contact_card1.png
  assets/img/sms/contact_card2.png
  assets/img/sms/delete_allowlist_warning.png
  assets/img/sms/high_risk.png
  assets/img/sms/mms_sub_group_tag.png
  assets/img/sms/sms_geographic_permissions.png
  assets/img/sms/sms_geographic_permissions_read_only.png
  assets/img/sms/sms_subgroup_select.png
Labels: 2024-docs-brand-refresh

#9644 Leftover deploy pt. 2 - May 9, 2025
  _docs/_help/release_notes/2016/july.md
  _docs/_help/release_notes/2019/march.md
  _docs/_help/release_notes/2020/december.md
  _docs/_help/release_notes/2021/december.md
  _docs/_help/release_notes/2022/4_5_22.md
  _docs/_help/release_notes/2022/7_26_22.md
  _docs/_partners/home.md
  _docs/_partners/message_personalization/dynamic_content/visual_and_interactive_content/movable_ink.md
  _docs/_user_guide/analytics/reporting.md
  _docs/_user_guide/brazeai/recommendations/rules_based_recommendations.md
  _docs/_user_guide/engagement_tools/segments.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _docs/_user_guide/engagement_tools/segments/location_targeting.md
  _docs/_user_guide/engagement_tools/segments/managing_segments.md
  _docs/_user_guide/engagement_tools/segments/measuring_segment_size.md
  _docs/_user_guide/engagement_tools/segments/regex.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _docs/_user_guide/engagement_tools/segments/segment_insights.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
  _docs/_user_guide/engagement_tools/segments/suppression_lists.md
  _docs/_user_guide/engagement_tools/segments/troubleshooting.md
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
  _docs/_user_guide/engagement_tools/segments/viewing_and_understanding_segment_data.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _lang/de/_hidden/support_contact.md
  _lang/es/_hidden/other/support_contact.md
  _lang/fr_fr/_hidden/other/support_contact.md
  _lang/ja/_developer_guide/analytics/managing_data_collection.md
  _lang/pt_br/_hidden/other/support_contact.md
  assets/js/broken_redirect_list.js
Labels: Deploy

#9647 Leftover deploy pt. 3 - May 9, 2025
  _docs/_developer_guide/banners.md
  _docs/_user_guide/administrative/access_braze/accessing_your_account.md
  _docs/_user_guide/engagement_tools/landing_pages.md
  _docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/email/preference_center/dnd_preference_center.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop.md
  _docs/_user_guide/message_building_by_channel/line.md
  _includes/developer_guide/_shared/enable_geofences_in_braze.md
  _includes/developer_guide/android/geofences.md
  _includes/developer_guide/swift/geofences.md
  _includes/developer_guide/swift/push_notifications/examples.md
  _includes/drag_and_drop_access.md
  assets/img/sdk_geofences/add-brazeLocation-module-xcode.png
  assets/img/sdk_geofences/info-plist-location-strings.png
  assets/img/sdk_geofences/xcode-background-modes-location-updates.png
Labels: Deploy

#9649 Leftover deploy - May 10, 2025
  _includes/developer_guide/cordova/sdk_integration.md
Labels: Deploy

#9567 Half hour of image work
  assets/img/current3.png
  assets/img/current4.png
  assets/img/importcsv2.png
  assets/img/importcsv5.png
  assets/img_archive/Braze_User_aliases.png
  assets/img_archive/Braze_User_flowchart.png
  assets/img_archive/currents-main-page.png
Labels: In Review, 2024-docs-brand-refresh

#9667 Deploy part 2 - May 14, 2025
  _docs/_partners/ecommerce/shopify.md
  _docs/_partners/ecommerce/shopify/multiple_stores.md
  _docs/_partners/ecommerce/shopify/shopify_custom_integration.md
  _docs/_partners/ecommerce/shopify/shopify_overview.md
  _docs/_partners/ecommerce/shopify/shopify_standard_integration.md
  _docs/_user_guide/engagement_tools/landing_pages.md
  _docs/_user_guide/engagement_tools/landing_pages/creating_pages.md
  _includes/shopify.md
  _layouts/broken_page.html
  assets/img/Shopify/activate_channels_standard.png
  assets/img/Shopify/begin_setup.png
  assets/img/Shopify/begin_setup_button.png
  assets/img/Shopify/catalog_store_name.png
  assets/img/Shopify/collect_email_subscribers.png
  assets/img/Shopify/ecommerce_order_placed.png
  assets/img/Shopify/external_id_standard.png
  assets/img/Shopify/multiple_stores.png
  assets/img/Shopify/shopify_paid_order.png
  assets/img/Shopify/standard_or_custom.png
  assets/img/Shopify/store_dropdown_menu.png
  assets/img/Shopify/sync_products_step1.png
  assets/img/landing_pages/example_landing_page.png
  assets/js/broken_redirect_list.js
Labels: Deploy

#8364 bdocs: script for auto-generating redirects
  _docs/_contributing/bdocs.md
  assets/js/broken_redirect_list.js
  bdocs
  scripts/make_redirects.py
Labels: cla-signed

#9677 Leftover deploy - May 15, 2025
  _docs/_contributing/bdocs.md
  _docs/_partners/data_and_analytics/data_warehouses/snowflake/user_attributes.md
  _docs/_partners/ecommerce/shopify/multiple_stores.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/adding_users_to_your_dashboard.md
  assets/js/broken_redirect_list.js
  bdocs
  scripts/make_redirects.py
Labels: Deploy

#9523 Accessibility best practices pt.1
  _docs/_help/accessibility.md
  _docs/_user_guide/message_building_by_channel.md
  _includes/accessibility/color.md
  _includes/accessibility/feedback.md
  _includes/accessibility/video.md
Labels: status: done

#9656 Banners GA
  _docs/_developer_guide/banners/analytics.md
  _docs/_developer_guide/banners/creating_campaigns.md
  _docs/_developer_guide/banners/creating_placements.md
  _docs/_developer_guide/banners/faq.md
  _docs/_developer_guide/banners/testing.md
  _docs/_developer_guide/content_cards/creating_cards.md
  _docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2025/4_1_25.md
  _docs/_user_guide/data/report_metrics.md
  _docs/_user_guide/getting_started/campaigns_canvases.md
  _docs/_user_guide/message_building_by_channel.md
  _docs/_user_guide/message_building_by_channel/banners.md
  _docs/_user_guide/message_building_by_channel/banners/analytics.md
  _docs/_user_guide/message_building_by_channel/banners/creating_campaigns.md
  _docs/_user_guide/message_building_by_channel/banners/faq.md
  _docs/_user_guide/message_building_by_channel/banners/testing.md
  _docs/_user_guide/message_building_by_channel/content_cards.md
  _docs/_user_guide/message_building_by_channel/content_cards/creative_details.md
  _docs/_user_guide/message_building_by_channel/email.md
  _includes/banner_cards/creating_placements.md
  _includes/banners/about.md
  _includes/banners/creating_placements.md
  _includes/banners/faq.md
  _includes/banners/testing.md
  _includes/campaign_analytics.md
  assets/img/banners/banner_card_styles.png
  assets/img/banners/banner_performance.png
  assets/img/banners/campaign_details.png
  assets/img/banners/conversion_event_details.png
  assets/img/banners/create_placement.png
  assets/img/banners/historical_performance.png
  assets/img/banners/placement_details_example.png
  assets/img/banners/preview_banner.png
  assets/img/banners/sample_banner.png
  assets/img/banners/select_preview.png
  assets/img/banners/test_recipients.png
  assets/img/getting_started/channels.png
  assets/js/broken_redirect_list.js
Labels: In Review

#9700 SalesWings Currents integration documentation
  _docs/_partners/data_and_analytics/analytics/saleswings.md
  assets/img/saleswings/example_lead_scoring_builder_braze_lead_scoring.png
  assets/img/saleswings/saleswings_braze_lead_scoring_custom_event_condition.png
  assets/img/saleswings/saleswings_braze_lead_scoring_integration_settings.png
Labels: Braze Partnerships

#9706 BD-4786: Eppo partner docs
  _docs/_partners/data_and_analytics.md
  _docs/_partners/data_and_analytics/ab_testing/eppo.md
  _docs/_partners/home.md
Labels: Braze Partnerships

#9714 Deploy part 2 - May 21, 2025
  _docs/_hidden/other/handbooks.md
  _docs/_partners/data_and_analytics.md
  _docs/_partners/data_and_analytics/ab_testing/eppo.md
  _docs/_partners/data_and_analytics/data_warehouses/snowflake.md
  _docs/_partners/ecommerce/shopify_legacy/using_shopify/shopify_data_in_braze.md
  _docs/_partners/home.md
  _docs/_user_guide/data/braze_currents/event_glossary/customer_behavior_events.md
  _docs/_user_guide/data/braze_currents/event_glossary/message_engagement_events.md
  _docs/_user_guide/data/custom_data/custom_events.md
  _docs/_user_guide/data/report_metrics.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
  _docs/_user_guide/engagement_tools/segments/sql_segments.md
  _docs/_user_guide/engagement_tools/segments/sql_segments/catalog_segments.md
  _includes/developer_guide/_shared/sending_test_messages.md
  assets/js/broken_redirect_list.js
Labels: Deploy

#9727 Leftover deploy - May 22, 2025
  LICENSE.md
  README.md
  _docs/_developer_guide/feature_flags.md
  _docs/_developer_guide/feature_flags/create.md
  _docs/_developer_guide/feature_flags/experiments.md
  _docs/_developer_guide/feature_flags/faq.md
  _docs/_developer_guide/getting_started/platform_overview.md
  _docs/_help/faqs.md
  _docs/_partners/home.md
  _docs/_user_guide/administrative/app_settings.md
  _docs/_user_guide/administrative/app_settings/push_settings.md
  _docs/_user_guide/administrative/app_settings/push_ttl_settings.md
  _docs/_user_guide/analytics/dashboard/email_performance_dashboard.md
  _docs/_user_guide/analytics/query_builder.md
  _docs/_user_guide/analytics/reporting/campaign_analytics.md
  _docs/_user_guide/brazeai/recommendations/rules_based_recommendations.md
  _docs/_user_guide/data/custom_data/recommended_events.md
  _docs/_user_guide/data/custom_data/recommended_events/ecommerce_events.md
  _docs/_user_guide/data/export_braze_data/message_archiving.md
  _docs/_user_guide/engagement_tools/canvas/get_started/the_basics.md
  _docs/_user_guide/engagement_tools/messaging_fundamentals/know_before_send.md
  _docs/_user_guide/engagement_tools/testing/global_control_group.md
  _docs/_user_guide/getting_started/campaigns_canvases.md
  _docs/_user_guide/getting_started/terms_to_know.md
  _docs/_user_guide/message_building_by_channel/in-app_messages.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/using_locales.md
  _docs/_user_guide/message_building_by_channel/push/android/advanced_campaign_settings.md
  _docs/_user_guide/message_building_by_channel/push/using_locales.md
  _docs/_user_guide/message_building_by_channel/sms_mms_rcs/best_practices.md
  _docs/_user_guide/message_building_by_channel/sms_mms_rcs/link_shortening.md
  _docs/_user_guide/message_building_by_channel/sms_mms_rcs/segments.md
  _docs/_user_guide/message_building_by_channel/sms_mms_rcs/sms/about_sms.md
  _docs/_user_guide/message_building_by_channel/sms_mms_rcs/sms/create.md
  _docs/_user_guide/message_building_by_channel/sms_mms_rcs/sms/sms_setup.md
  _docs/_user_guide/message_building_by_channel/sms_mms_rcs/sms/sms_setup/sms_sending.md
  _docs/_user_guide/message_building_by_channel/sms_mms_rcs/sms/sms_setup/terms.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/click_tracking.md
  _includes/contributing/templates/technology_partner.md
  _includes/locales.md
  assets/Braze_Primary_Icon_PURPLE.png
  assets/img/Shopify/transactions_tab.png
  assets/img/multi-language_support/dnd_iam_download_template.png
  assets/img/multi-language_support/dnd_iam_editor_translation_tags.png
  assets/img/multi-language_support/dnd_iam_upload_translations.png
  assets/img/multi-language_support/html_iam_editor_translation_tags.png
  assets/img/multi-language_support/manage_languages_modal.png
  assets/img/push_fcm_priority_settings.png
  assets/img/push_ttl.png
  assets/js/broken_redirect_list.js
Labels: Deploy

#9551 Add Mention Me integration documentation
  _docs/_partners/home.md
  _docs/_partners/message_personalization.md
  _docs/_partners/message_personalization/referrals/mention_me.md
Labels: Braze Partnerships, In Review

#9757 Leftover deploy - May 28, 2025
  _docs/_developer_guide/banners/creating_placements.md
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
  _includes/analytics.html
  assets/img/ios/interruption-level.png
  assets/img_archive/push_compose.png
  assets/img_archive/push_recent_device.png
Labels: Deploy

#9771 Update push notification image and preview step
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
  assets/img_archive/push_2.png
Labels: cla-signed

#9772 More PR types for block-merge.yml
  .github/workflows/block-merge.yml
Labels: cla-signed
