Repository braze-inc/braze-docs, pull requests merged in 2025-07, with the labels that each got.

#9949 BD-4874: Clarify Audience Sync to Google is for Google Ads, not Google Ads Manager
  _docs/_partners/canvas_audience_sync/google_audience_sync.md
Labels: cla-signed

#9950 Fix alert
  _docs/_partners/canvas_audience_sync/google_audience_sync.md
Labels: cla-signed

#9936 Adding feature flag eligibility to user_profiles.md
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
Labels: cla-signed

#9934 BD-4843: Translation email templates endpoints EA
  _docs/_api/endpoints/translations.md
  _docs/_api/endpoints/translations/campaigns.md
  _docs/_api/endpoints/translations/campaigns/get_bulk_translations_campaigns.md
  _docs/_api/endpoints/translations/campaigns/get_translation_campaign.md
  _docs/_api/endpoints/translations/campaigns/put_update_translation_campaign.md
  _docs/_api/endpoints/translations/canvas.md
  _docs/_api/endpoints/translations/canvas/get_bulk_translations_canvases.md
  _docs/_api/endpoints/translations/canvas/get_translation_canvas.md
  _docs/_api/endpoints/translations/canvas/put_update_translation_canvas.md
  _docs/_api/endpoints/translations/email_templates.md
  _docs/_api/endpoints/translations/email_templates/get_view_source_template.md
  _docs/_api/endpoints/translations/email_templates/get_view_translation_locale_template.md
  _docs/_api/endpoints/translations/email_templates/get_view_translation_template.md
  _docs/_api/endpoints/translations/email_templates/put_update_template.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#9951 BD-4748: Clarify details for eCommerce recommended events
  _docs/_user_guide/data/custom_data/recommended_events/ecommerce_events.md
Labels: cla-signed

#9953 BD-4873: Remove outdated parameter
  _docs/_api/endpoints/user_data/post_user_identify.md
Labels: cla-signed

#9956 Deploy - July 1, 2025
  _docs/_api/endpoints/messaging/live_activity/start.md
  _docs/_api/endpoints/messaging/live_activity/update.md
  _docs/_api/endpoints/messaging/send_messages/post_send_messages.md
  _docs/_api/endpoints/translations.md
  _docs/_api/endpoints/translations/campaigns.md
  _docs/_api/endpoints/translations/campaigns/get_bulk_translations_campaigns.md
  _docs/_api/endpoints/translations/campaigns/get_translation_campaign.md
  _docs/_api/endpoints/translations/campaigns/put_update_translation_campaign.md
  _docs/_api/endpoints/translations/canvas.md
  _docs/_api/endpoints/translations/canvas/get_bulk_translations_canvases.md
  _docs/_api/endpoints/translations/canvas/get_translation_canvas.md
  _docs/_api/endpoints/translations/canvas/put_update_translation_canvas.md
  _docs/_api/endpoints/translations/email_templates.md
  _docs/_api/endpoints/translations/email_templates/get_view_source_template.md
  _docs/_api/endpoints/translations/email_templates/get_view_translation_locale_template.md
  _docs/_api/endpoints/translations/email_templates/get_view_translation_template.md
  _docs/_api/endpoints/translations/email_templates/put_update_template.md
  _docs/_api/endpoints/user_data/post_user_identify.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2025/6_24_25.md
  _docs/_partners/canvas_audience_sync/google_audience_sync.md
  _docs/_user_guide/brazeai/generative_ai/content_qa.md
  _docs/_user_guide/data/cloud_ingestion/file_storage_integrations.md
  _docs/_user_guide/data/custom_data/recommended_events/ecommerce_events.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md
  _docs/_user_guide/engagement_tools/landing_pages/retargeting.md
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
  _docs/_user_guide/message_building_by_channel/push/android/advanced_campaign_settings.md
  _includes/api/payload_size_alert.md
  _includes/developer_guide/android/push_notifications/customization.md
  _includes/developer_guide/fireos/push_notifications/customization.md
  assets/img/android/push/collapsed-android-notification.png
  assets/img/android/push/expanded-android-notification.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#9952 [no-tix] make at first impression rate limit limitation more readable with <br><br>
  _docs/_user_guide/message_building_by_channel/content_cards/create/card_creation.md
Labels: cla-signed

#9957 BD-3774: Clarify supported editors for message-level one-click list-unsubscribe
  _docs/_user_guide/administrative/app_settings/email_settings.md
Labels: cla-signed

#9959 Add alias to SQL Segment Extensions
  _docs/_user_guide/brazeai/generative_ai.md
  _docs/_user_guide/brazeai/generative_ai/sql_segment_extensions.md
Labels: cla-signed

#9955 [CO-3528] update custom attributes blocklisting docs
  _docs/_user_guide/data/custom_data/managing_custom_data.md
Labels: cla-signed

#9958 BD-4892 Update Shopify integration with API information
  _docs/_partners/ecommerce/shopify/shopify_overview.md
  _docs/_partners/ecommerce/shopify/shopify_standard_integration.md
Labels: cla-signed

#9961 [BD-3773] Add 'message engagement events' to non-billable
  _docs/_user_guide/data/data_points.md
Labels: cla-signed

#9962 404 checker - July 2, 2025
  _docs/_contributing/bdocs.md
Labels: cla-signed

#9971 BD-4857 Security Export with Amazon S3
  _docs/_user_guide/administrative/app_settings/company_settings/security_settings/security_export_s3.md
  assets/img/security_export/add_permissions.png
  assets/img/security_export/credentials1.png
  assets/img/security_export/credentials2.png
  assets/img/security_export/name_review_create.png
  assets/img/security_export/policies.png
  assets/img/security_export/retrieve_access_keys.png
  assets/img/security_export/review_and_create.png
  assets/img/security_export/save_changes_button.png
  assets/img/security_export/security_event_download1.png
  assets/img/security_export/security_event_download2.png
  assets/img/security_export/security_event_download3.png
  assets/img/security_export/select_trusted_entity.png
  assets/img/security_export/specify_permissions.png
Labels: cla-signed

#9970 [BD-4903] Android push primer note
  _docs/_user_guide/message_building_by_channel/push/best_practices/push_primer_messages.md
Labels: cla-signed

#9964 BD-4897 Update Custom Domains article
  _docs/_user_guide/message_building_by_channel/sms_mms_rcs/link_shortening/custom_domains.md
Labels: cla-signed

#9974 Deploy pt 2 - July 3, 2025
  _docs/_user_guide/message_building_by_channel/sms_mms_rcs/link_shortening/custom_domains.md
Labels: cla-signed, Deploy

#9979 BD-4908: Update FY'26 Handbook with latest version
  assets/download_file/Braze_Entitlements_Handbook_25.pdf
Labels: cla-signed

#9494 BD-4439: Update "Using Intelligent Timing" to match Reactified UI screenshots and logic
  _docs/_user_guide/brazeai/intelligence/intelligent_timing.md
  assets/img/intelligent_timing/ab_testing_intelligent_timing.png
  assets/img/intelligent_timing/campaign_scheduling.png
  assets/img/intelligent_timing/first_used_app.png
  assets/img/intelligent_timing/quiet_hours.png
Labels: status: done, cla-signed

#9976 Update feed.md
  _docs/_developer_guide/content_cards/customizing_cards/feed.md
Labels: cla-signed

#9980 Update email_object.md
  _docs/_api/objects_filters/messaging/email_object.md
Labels: cla-signed

#9935 BD-4877 Updating Segment Insights page
  _docs/_user_guide/engagement_tools/segments/segment_insights.md
  assets/img_archive/Segment_Insights_Events1.png
  assets/img_archive/Segment_Insights_Info.png
  assets/img_archive/Segment_Language_Insights.png
  assets/img_archive/segment_insights.png
Labels: cla-signed

#9983 BD-4888: Bot filtering GA
  _docs/_user_guide/administrative/app_settings/email_settings/bot_filtering.md
  assets/img/bot_tracking_email.png
Labels: cla-signed

#9985 Minor edit
  _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
Labels: cla-signed

#9915 BD-4820 Drag-and-drop product blocks
  _docs/_user_guide/data/custom_data/recommended_events/product_blocks.md
  _docs/_user_guide/engagement_tools/messaging_fundamentals/product_blocks.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/product_blocks.md
  assets/download_file/ecommerce_product _catalog_sample.csv
  assets/img/ecommerce/sample_product_catalog.png
  assets/img/product_blocks/dynamic_fields.png
  assets/img/product_blocks/layout_options.png
  assets/img/product_blocks/liquid.png
  assets/img/product_blocks/preview_as_a_user.png
  assets/img/product_blocks/product_block.png
  assets/img/product_blocks/static_block_preview.png
  assets/img/product_blocks/static_fields.png
Labels: cla-signed

#9865 BD-4798 Add "span text" feature to Landing Pages and IAMs
  _docs/_user_guide/engagement_tools/landing_pages/creating_pages.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/style_settings.md
  _includes/span_text.md
  assets/img/landing_pages/span_properties.png
  assets/img/landing_pages/wrap_with_span.png
Labels: cla-signed

#9942 BD-4736 Targeting users for a specific app
  _docs/_user_guide/engagement_tools/messaging_fundamentals/targeting_users.md
  assets/img_archive/app_test_android.png
  assets/img_archive/has_app_hello_world.png
  assets/img_archive/target_users_by_segment_example.png
Labels: cla-signed

#9975 [DI-7683] Add Currents Release #2 changes - MERGE 7/9
  _docs/_user_guide/data/braze_currents/event_glossary/message_engagement_events.md
Labels: cla-signed

#9624 Removing translations from Legal pages except for English and Japanese
  _docs/_developer_guide/disclosures/innovation_statement.md
  _docs/_hidden/compliance/home.md
  _docs/_hidden/compliance/line_channel.md
  _docs/_hidden/compliance/sms_channel.md
  _docs/_hidden/compliance/webhook_channel.md
  _docs/_hidden/compliance/whatsapp.md
  _includes/braze_legal/english_language_governance.md
  _lang/de/_developer_guide/disclosures/innovation_statement.md
  _lang/es/_developer_guide/disclosures/innovation_statement.md
  _lang/es/_hidden/compliance/home.md
  _lang/es/_hidden/compliance/line_channel.md
  _lang/es/_hidden/compliance/sms_channel.md
  _lang/es/_hidden/compliance/webhook_channel.md
  _lang/es/_hidden/compliance/whatsapp.md
  _lang/fr_fr/_developer_guide/disclosures/innovation_statement.md
  _lang/fr_fr/_hidden/compliance/home.md
  _lang/fr_fr/_hidden/compliance/line_channel.md
  _lang/fr_fr/_hidden/compliance/sms_channel.md
  _lang/fr_fr/_hidden/compliance/webhook_channel.md
  _lang/fr_fr/_hidden/compliance/whatsapp.md
  _lang/fr_fr/_hidden/support_contact.md
  _lang/ja/_developer_guide/disclosures/innovation_statement.md
  _lang/ko/_developer_guide/disclosures/innovation_statement.md
  _lang/ko/_hidden/compliance/home.md
  _lang/ko/_hidden/compliance/line_channel.md
  _lang/ko/_hidden/compliance/sms_channel.md
  _lang/ko/_hidden/compliance/webhook_channel.md
  _lang/ko/_hidden/compliance/whatsapp.md
  _lang/pt_br/_developer_guide/disclosures/innovation_statement.md
  _lang/pt_br/_hidden/compliance/home.md
  _lang/pt_br/_hidden/compliance/line_channel.md
  _lang/pt_br/_hidden/compliance/sms_channel.md
  _lang/pt_br/_hidden/compliance/webhook_channel.md
  _lang/pt_br/_hidden/compliance/whatsapp.md
Labels: cla-signed

#9989 Broken link audit - Week of July 7, 2025
  _docs/_user_guide/engagement_tools/messaging_fundamentals/product_blocks.md
  _includes/offerfit/building_use_cases.md
  assets/download_file/ecommerce_product_catalog_sample.csv
Labels: cla-signed

#9988 BD-4878 Considerations for WhatsApp response messages
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/user_messages.md
  assets/img/whatsapp/ecommerce_cart_updated.png
  assets/img/whatsapp/whatsapp_inbound_message_trigger.png
Labels: cla-signed

#9730 BD-4764 Automatically populate the campaign variant name
  _docs/_user_guide/analytics/query_builder.md
  _includes/brazeai/generative_ai/building_queries.md
  assets/img_archive/create_sql_query.png
  assets/img_archive/query_builder_ai_tab.png
  assets/img_archive/report_name_field.png
Labels: cla-signed

#10000 Update intelligent_timing.md
  _docs/_user_guide/brazeai/intelligence/intelligent_timing.md
Labels: cla-signed

#9994 Clarify "safe zone" in campaign FAQ and minor edits
  _docs/_user_guide/engagement_tools/campaigns/faq.md
Labels: cla-signed

#9981 BD-4911: Add additional failure insights in Braze Currents for webhook and Connected Content - MERGE 7/10
  _docs/_help/help_articles/api/webhook_connected_content_errors.md
Labels: cla-signed

#10002 Update mentions of "(optional)" to "(Optional)" for text steps
  _docs/_user_guide/analytics/dashboard/conversions_dashboard.md
  _docs/_user_guide/engagement_tools/canvas/testing_canvases/preview_user_paths.md
  _docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
Labels: cla-signed

#10004 BD-4893 Add WhatsApp engagement events
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
Labels: cla-signed

#10003 BD-4889 send_ids aren't associated with SMS click events
  _docs/_user_guide/analytics/query_builder.md
  _docs/_user_guide/message_building_by_channel/sms_mms_rcs/link_shortening.md
Labels: cla-signed

#9992 BD-4835 Clarify multiple WABAs details
  _docs/_user_guide/message_building_by_channel/whatsapp/faqs.md
Labels: cla-signed

#9991 BD-4513 WABAs can be from different Meta Business Managers
  _docs/_user_guide/message_building_by_channel/whatsapp/overview/multiple_subscription_groups.md
Labels: cla-signed

#10006 Update Braze Learning course name
  _docs/_user_guide/administrative/app_settings/internal_groups_tab.md
Labels: cla-signed

#10005 Update authentication.md JWT terminology
  _docs/_developer_guide/sdk_integration/authentication.md
Labels: cla-signed

#10015 Add WhatsApp Custom Domains redirect
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/custom_domains.md
  _includes/custom_domains.md
Labels: cla-signed

#10013 BD-4915: Clarify bulk tagging details
  _docs/_user_guide/administrative/app_settings/tags.md
Labels: cla-signed

#10018 Leftover deploy - July 11, 2025
  _docs/_developer_guide/sdk_integration/authentication.md
  _docs/_user_guide/administrative/app_settings/tags.md
  _docs/_user_guide/message_building_by_channel/sms_mms_rcs/link_shortening/custom_domains.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/custom_domains.md
  _includes/custom_domains.md
  assets/img/sms/custom_domain.png
  assets/img/sms/custom_domain2.png
  assets/img/sms/custom_domain_button.png
  assets/img/sms/custom_domain_statuses.png
  assets/img/sms/dns_record.png
  assets/img/sms/main_page.png
Labels: cla-signed

#10022 Fix link
  _docs/_developer_guide/in_app_messages/tutorials.md
Labels: cla-signed

#10028 Minor edits
  _docs/_api/identifier_types.md
Labels: cla-signed

#10019 BD-4935 Update FAQs for workspaces
  _docs/_user_guide/administrative/app_settings/workspaces.md
Labels: cla-signed

#10009 Update creating_a_webhook.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
Labels: cla-signed

#10032 Update field_level_encryption.md
  _docs/_user_guide/data/field_level_encryption.md
Labels: cla-signed

#10020 BD-4940: Clarify supported channels for copying across workspaces
  _docs/_user_guide/engagement_tools/messaging_fundamentals/copying_across_workspaces.md
Labels: cla-signed

#10017 BD-4694: Clarify translations aren't copied across campaigns and Canvases for workspaces
  _docs/_user_guide/engagement_tools/messaging_fundamentals/copying_across_workspaces.md
Labels: cla-signed

#10034 Revert "Update field_level_encryption.md"
  _docs/_user_guide/data/field_level_encryption.md
Labels: cla-signed

#10012 [BD-4899] CSV import for users - Merge July 14, 2025
  _docs/_user_guide/data/user_data_collection/user_import.md
  _docs/_user_guide/data/user_data_collection/user_import/csv_import.md
  assets/img/csv_import/add_filter_group.png
  assets/img/csv_import/import_users_page.png
  assets/img/csv_import/upload_csv.png
Labels: cla-signed

#10041 Deploy - July 14, 2025
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
  _docs/_api/identifier_types.md
  _docs/_developer_guide/in_app_messages/tutorials.md
  _docs/_partners/canvas_audience_sync/facebook_audience_sync.md
  _docs/_partners/data_and_analytics/loyalty/punchh/punchh.md
  _docs/_user_guide/administrative/app_settings/workspaces.md
  _docs/_user_guide/data/custom_data/recommended_events/ecommerce_events.md
  _docs/_user_guide/data/user_data_collection/user_import.md
  _docs/_user_guide/data/user_data_collection/user_import/csv_import.md
  _docs/_user_guide/engagement_tools/messaging_fundamentals/copying_across_workspaces.md
  _docs/_user_guide/message_building_by_channel/sms_mms_rcs/link_shortening/custom_domains.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  _lang/fr_fr/_includes/campaign_analytics.md
  _lang/fr_fr/_user_guide/message_building_by_channel/content_cards/reporting.md
  _plugins/multi_lang_include.rb
  assets/img/audience_sync/audience_sync3.png
  assets/img/audience_sync/audience_sync4.png
  assets/img/audience_sync/audience_sync5.png
  assets/img/audience_sync/fb_sync.png
  assets/img/audience_sync/fb_sync3.png
  assets/img/csv_import/add_filter_group.png
  assets/img/csv_import/import_users_page.png
  assets/img/csv_import/upload_csv.png
  assets/img/fb/afb_1.png
  assets/img/fb/afb_5.png
Labels: cla-signed

#10011 BD-4906 Add note to spam metric definition
  _docs/_user_guide/data/report_metrics.md
Labels: cla-signed

#9977 Update create.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
Labels: cla-signed

#9996 Update about.md
  _includes/banners/about.md
Labels: cla-signed

#10035 BD-4886: Clarify default priority for Live Activity
  _docs/_api/endpoints/messaging/live_activity/start.md
  _docs/_api/endpoints/messaging/live_activity/update.md
Labels: cla-signed

#10036 BD-4895: Clarify Context variable example for references in other steps
  _docs/_user_guide/engagement_tools/canvas/canvas_components/context.md
Labels: cla-signed

#10043 BD-4707: Clarify "Touches" explanation
  _docs/_user_guide/analytics/reporting/dashboard_builder.md
Labels: cla-signed

#10048 BD-4680 Make landing pages device responsive
  _docs/_user_guide/engagement_tools/landing_pages/creating_pages.md
  assets/img/landing_pages/device_responsive_toggle.png
Labels: cla-signed

#10046 BD-4459: Clean up mentions of original Canvas editor and related
  _docs/_api/endpoints/export/canvas/get_canvas_details.md
  _docs/_developer_guide/feature_flags.md
  _docs/_help/release_notes/2024/6_25_24.md
  _docs/_partners/canvas_audience_sync/criteo_audience_sync.md
  _docs/_partners/canvas_audience_sync/facebook_audience_sync.md
  _docs/_partners/canvas_audience_sync/google_audience_sync.md
  _docs/_partners/canvas_audience_sync/tiktok_audience_sync.md
  _docs/_partners/ecommerce/shopify_legacy/getting_started_shopify.md
  _docs/_user_guide/administrative/app_settings/workspaces.md
  _docs/_user_guide/brazeai/intelligence/intelligent_timing.md
  _docs/_user_guide/engagement_tools/canvas.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/advancement.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_by_channel/in-app_messages_in_canvas.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/canvas/faqs.md
  _docs/_user_guide/engagement_tools/canvas/get_started/canvas_outlines.md
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies.md
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/pre_post_launch_checklist.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
  _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
  _docs/_user_guide/engagement_tools/messaging_fundamentals/duplicating.md
  _docs/_user_guide/getting_started/campaigns_canvases.md
  _includes/drag_and_drop/templates.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#10051 File 1_7_25.md committed.
  _lang/ja/_help/release_notes/2025/1_7_25.md
  _lang/ja/_help/release_notes/2025/2_4_25.md
  _lang/ja/_help/release_notes/2025/3_4_25.md
  _lang/ja/_help/release_notes/2025/4_1_25.md
  _lang/ja/_help/release_notes/2025/4_29_25.md
  _lang/ja/_help/release_notes/2025/5_27_25.md
  _lang/ja/_help/release_notes/2025/6_24_25.md
Labels: cla-signed

#10027 File new_features.md committed.
  _lang/ja/_user_guide/administrative/app_settings/brand_guidelines.md
  _lang/ja/_user_guide/engagement_tools/campaigns/managing_campaigns/copying_to_workspace.md
  _lang/ja/_user_guide/engagement_tools/landing_pages/tracking_users.md
  _lang/ja/_user_guide/engagement_tools/segments/segment_funnels.md
Labels: cla-signed

#10026 File sending_test_messages.md committed.
  _lang/es/_user_guide/data/user_data_collection/user_profile_lifecycle/anonymous_users.md
  _lang/es/_user_guide/engagement_tools/campaigns/managing_campaigns/copying_to_workspace.md
  _lang/es/_user_guide/engagement_tools/segments/segment_funnels.md
Labels: cla-signed

#10024 File new_features.md committed.
  _lang/pt_br/_user_guide/engagement_tools/campaigns/managing_campaigns/copying_to_workspace.md
  _lang/pt_br/_user_guide/engagement_tools/messaging_fundamentals/localization.md
  _lang/pt_br/_user_guide/engagement_tools/segments/segment_funnels.md
Labels: cla-signed

#10047 Update live_activities.md
  _docs/_developer_guide/live_notifications/live_activities.md
Labels: cla-signed

#10059 PUSH-30: Add documentation for limit on external_user_ids argument fo…
  _docs/_api/endpoints/messaging/live_activity/start.md
Labels: cla-signed

#9963 [BD-4875] Web SDK fixes for Google Tag Manager
  _docs/_developer_guide/sdk_integration/google_tag_manager.md
  _docs/_developer_guide/sdk_integration/initialization.md
  _includes/developer_guide/android/google_tag_manager.md
  _includes/developer_guide/android/sdk_integration.md
  _includes/developer_guide/swift/google_tag_manager.md
  _includes/developer_guide/swift/sdk_integration.md
  _includes/developer_guide/unreal_engine/sdk_initialization.md
  _includes/developer_guide/unreal_engine/sdk_integration.md
  _includes/developer_guide/web/content_cards.md
  _includes/developer_guide/web/google_tag_manager.md
  _includes/developer_guide/web/google_tag_manager/initialization_tag.md
  _includes/developer_guide/web/sdk_initialization.md
  _includes/developer_guide/web/sdk_integration.md
  assets/img/web-gtm/add_to_workspace.png
  assets/img/web-gtm/braze_initialization_options.png
  assets/img/web-gtm/search_tag_template_gallery.png
  assets/img/web-gtm/select_tag_template.png
  assets/img/web-gtm/template_gallery_results.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#10065 fix sitemap and prod deploy
  _lang/de/_developer_guide/sdk_integration/initialization.md
  _lang/de/_docs_pages/sitemap.xml
  _lang/es/_developer_guide/sdk_integration.md
  _lang/es/_developer_guide/sdk_integration/initialization.md
  _lang/es/_docs_pages/sitemap.xml
  _lang/fr_fr/_developer_guide/sdk_integration.md
  _lang/fr_fr/_developer_guide/sdk_integration/initialization.md
  _lang/fr_fr/_docs_pages/sitemap.xml
  _lang/ja/_developer_guide/sdk_integration.md
  _lang/ja/_developer_guide/sdk_integration/initialization.md
  _lang/ja/_docs_pages/sitemap.xml
  _lang/ko/_developer_guide/sdk_integration.md
  _lang/ko/_developer_guide/sdk_integration/initialization.md
  _lang/ko/_docs_pages/sitemap.xml
  _lang/pt_br/_developer_guide/sdk_integration.md
  _lang/pt_br/_developer_guide/sdk_integration/initialization.md
  _lang/pt_br/_docs_pages/sitemap.xml
Labels: cla-signed

#10038 BD-4939 & BD-4933: Invert SQL for SQL Segment Extensions and catalog segments and clarifications
  _docs/_user_guide/engagement_tools/segments/sql_segments/catalog_segments.md
  _includes/brazeai/generative_ai/sql_segment_extensions.md
  assets/img_archive/sql_segment_invert_sql.png
Labels: cla-signed

#10045 line: add missing verb
  _docs/_user_guide/message_building_by_channel/line/line_users/user_management.md
Labels: cla-signed

#9982 [BD-4964] Lemnisk Partner Documentation
  _docs/_partners/data_and_analytics/customer_data_platform/lemnisk.md
  assets/img/lemnisk/braze_cov.png
  assets/img/lemnisk/create_an_engagement.png
  assets/img/lemnisk/ext_api_basic_details.png
  assets/img/lemnisk/ext_api_ext_api_details.png
  assets/img/lemnisk/fr29.png
  assets/img/lemnisk/open_external_api.png
  assets/img/lemnisk/test_ext_api.png
Labels: cla-signed

#10073 Broken link audit - July 17, 2025
  _docs/_user_guide/message_building_by_channel/sms_mms_rcs.md
Labels: cla-signed

#10076 BD-4917: Include that seed groups are also not included by delivery speed rate limits
  _docs/_user_guide/administrative/app_settings/internal_groups_tab.md
Labels: cla-signed

#10063 BD-4954: New faster rate limit available for `/users/export/ids` endpoint
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
  _includes/rate_limits.md
Labels: cla-signed

#10029 BD-4490 Assets for WhatsApp templates need to be added to Braze
  _docs/_user_guide/message_building_by_channel/whatsapp/overview.md
Labels: cla-signed

#9999 Okendo Partner Docs
  _docs/_partners/ecommerce/analytics_workflow/okendo.md
Labels: cla-signed

#10060 change ja support topic to be english
  _docs/_hidden/other/support_contact.md
  _lang/ja/_hidden/other/support_contact.md
Labels: cla-signed

#10084 Hotfix: Web GTM images
  _includes/developer_guide/web/google_tag_manager/initialization_tag.md
  assets/img/web-gtm/add_to_workspace.png
  assets/img/web-gtm/braze_initialization_options.png
  assets/img/web-gtm/search_tag_template_gallery.png
  assets/img/web-gtm/select_tag_template.png
  assets/img/web-gtm/template_gallery_results.png
Labels: cla-signed

#10094 [BD-4972] IAM + FF
  _docs/_developer_guide/feature_flags/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/style_settings.md
  assets/img/feature_flags/eligibility.png
  assets/img_archive/close_x_button.png
Labels: cla-signed

#9993 BD-4839 Canvas View dropdown for Report Builder 2
  _docs/_user_guide/analytics/reporting/report_builder.md
  assets/img/report_builder_2/canvas_view_dropdown.png
Labels: cla-signed

#10106 Fix Swift prereqs for push stories
  _includes/developer_guide/swift/push_notifications/push_stories.md
Labels: cla-signed

#10095 July 22, 2025 release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2025.md
  _docs/_help/release_notes/2025/7_22_25.md
Labels: cla-signed

#10109 Deploy - July 22, 2025
  _docs/_api/endpoints/translations/email_templates/get_view_translation_locale_template.md
  _docs/_developer_guide/feature_flags/create.md
  _docs/_help/help_articles/campaigns_and_canvas/more_people_in_control_group.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2025.md
  _docs/_help/release_notes/2025/7_22_25.md
  _docs/_hidden/other/segment_funnels.md
  _docs/_hidden/other/support_contact.md
  _docs/_partners/data_and_analytics.md
  _docs/_partners/ecommerce.md
  _docs/_partners/ecommerce/analytics_workflow/okendo.md
  _docs/_partners/ecommerce/shopify/shopify_data_features.md
  _docs/_partners/home.md
  _docs/_user_guide/analytics/reporting/report_builder.md
  _docs/_user_guide/data/cloud_ingestion/file_storage_integrations.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/context.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/decision_split.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
  _docs/_user_guide/engagement_tools/messaging_fundamentals/conversion_events.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
  _docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/style_settings.md
  _docs/_user_guide/message_building_by_channel/push/best_practices.md
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
  _docs/_user_guide/message_building_by_channel/push/push_registration.md
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs.md
  _includes/developer_guide/swift/push_notifications/push_stories.md
  _includes/developer_guide/web/google_tag_manager/initialization_tag.md
  _lang/ja/_hidden/other/support_contact.md
  assets/download_file/Braze_Entitlements_Handbook_25.pdf
  assets/img/feature_flags/eligibility.png
  assets/img/report_builder_2/canvas_view_dropdown.png
  assets/img/web-gtm/add_to_workspace.png
  assets/img/web-gtm/braze_initialization_options.png
  assets/img/web-gtm/search_tag_template_gallery.png
  assets/img/web-gtm/select_tag_template.png
  assets/img/web-gtm/template_gallery_results.png
  assets/img_archive/close_x_button.png
Labels: cla-signed

#10121 [BD-3682] Syntax for logging Click on custom HTML IAMs
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize/html_in-app_messages.md
Labels: cla-signed

#10123 [BD-3720] Specify webhook User-Agent header
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
Labels: cla-signed

#10110 BD-4641: Clarify sending promotion codes to user details
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
Labels: cla-signed

#10126 Update image size
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
Labels: cla-signed

#10125 BD-4965 Invert SQL updates
  _includes/brazeai/generative_ai/sql_segment_extensions.md
Labels: cla-signed

#10085 Create copilot-instructions.md
  .github/copilot-instructions.md
Labels: cla-signed

#10137 File updating_currents.md committed.
  _lang/pt_br/_includes/archive/appboyBridge.md
  _lang/pt_br/_includes/archive/apple/initial_setup.md
  _lang/pt_br/_includes/archive/in_app_message.md
  _lang/pt_br/_includes/archive/setting_user_ids/setting_user_ids.md
  _lang/pt_br/_includes/archive/short_and_long_codes.md
  _lang/pt_br/_includes/booking_use_case.md
  _lang/pt_br/_includes/campaign_analytics.md
  _lang/pt_br/_includes/contributing/templates/technology_partner.md
  _lang/pt_br/_includes/create_content_block.md
  _lang/pt_br/_includes/create_transformation.md
  _lang/pt_br/_includes/data_centers.md
  _lang/pt_br/_includes/image_specs.md
  _lang/pt_br/_includes/locales.md
  _lang/pt_br/_includes/message_usage.md
  _lang/pt_br/_includes/metrics.md
  _lang/pt_br/_includes/rate_limits.md
Labels: cla-signed

#10138 File prerequisites.md committed.
  _lang/es/_includes/archive/appboyBridge.md
  _lang/es/_includes/archive/apple/initial_setup.md
  _lang/es/_includes/archive/in_app_message.md
  _lang/es/_includes/archive/setting_user_ids/setting_user_ids.md
  _lang/es/_includes/archive/short_and_long_codes.md
  _lang/es/_includes/booking_use_case.md
  _lang/es/_includes/campaign_analytics.md
  _lang/es/_includes/contributing/templates/technology_partner.md
  _lang/es/_includes/create_content_block.md
  _lang/es/_includes/create_transformation.md
  _lang/es/_includes/data_centers.md
  _lang/es/_includes/image_specs.md
  _lang/es/_includes/locales.md
  _lang/es/_includes/message_usage.md
  _lang/es/_includes/metrics.md
  _lang/es/_includes/rate_limits.md
Labels: cla-signed

#10139 File rate_limits.md committed.
  _lang/fr_fr/_includes/rate_limits.md
Labels: cla-signed

#10140 File rate_limits.md committed.
  _lang/de/_includes/rate_limits.md
Labels: cla-signed

#10141 File rate_limits.md committed.
  _lang/ja/_includes/rate_limits.md
Labels: cla-signed

#10142 File rate_limits.md committed.
  _lang/ko/_includes/rate_limits.md
  _lang/ko/_user_guide/message_building_by_channel/sms/campaign/link_shortening/custom_domains.md
Labels: cla-signed

#10150 Clarify workspace API rate limits in release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2025/7_22_25.md
Labels: cla-signed

#10136 Possible typo for getCurrentUser() > getUser()
  _includes/developer_guide/web/analytics/setting_user_attributes.md
Labels: cla-signed

#10086 BD-4706 Transfer User Targeting SF articles
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/new_features.md
  _docs/_user_guide/engagement_tools/canvas/faqs.md
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _docs/_user_guide/engagement_tools/segments/managing_segments.md
  _docs/_user_guide/engagement_tools/segments/measuring_segment_size.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
  _docs/_user_guide/engagement_tools/segments/troubleshooting.md
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
  _docs/_user_guide/engagement_tools/testing/global_control_group.md
  _docs/_user_guide/engagement_tools/testing/random_bucket_numbers.md
Labels: cla-signed

#10151 feat(uninstall_tracking): added a note on expected volatility in install tracking numbers
  _docs/_user_guide/analytics/tracking/uninstall_tracking.md
Labels: cla-signed

#10154 Add no-op note to SDK Auth for anonymous users
  _docs/_developer_guide/sdk_integration/authentication.md
Labels: cla-signed

#10152 support content language update
  _docs/_hidden/other/support_contact.md
  _lang/ja/_hidden/other/support_contact.md
Labels: cla-signed

#10176 Remove invalid characters listed in Microsoft Domain local part descr…
  _docs/_user_guide/message_building_by_channel/email/email_setup/email_validation.md
Labels: cla-signed

#10173 Simplify + improve CODEOWNERS
  .github/CODEOWNERS
Labels: cla-signed

#10177 BD-5009 Fuzzy opt-out messages best practices
  _docs/_user_guide/message_building_by_channel/sms_mms_rcs/keywords/fuzzy_opt_out.md
  assets/img/sms/fuzzy2.png
Labels: cla-signed

#10189 BD-4976: Clarify link identifiers behavior for duplicate emails and Content Blocks
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
Labels: cla-signed

#10174 BD-4464: Clarifications on custom unsubscribe and custom opt-in pages
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#10195 Update images and related edits for Email subscriptions
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
  assets/img/custom_optin.png
  assets/img/custom_unsubscribe.png
  assets/img/push_example.png
  assets/img/segment_sub_group.png
  assets/img/sub_group_create.png
  assets/img_archive/not_optin.png
Labels: cla-signed
