Repository braze-inc/braze-docs, pull requests merged in 2025-02, with the labels that each got.

#8892 BD-3885 Export logs EA
  _docs/_partners/data_and_infrastructure_agility/workflow_automation/fivetran.md
  _docs/_user_guide/administrative/app_settings.md
  _docs/_user_guide/administrative/app_settings/exports_log.md
  assets/img/export_logs.png
  assets/img/export_logs_cancel.png
  assets/img/export_logs_share.png
Labels: cla-signed

#8905 BD-3850: Clarify JSON object support for catalogs
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/using_catalogs.md
Labels: cla-signed

#8871 Enhance push notifications doc
  _docs/_developer_guide/platforms/legacy_sdks/ios/push_notifications/integration.md
  _docs/_developer_guide/platforms/react_native/push_notifications.md
  _includes/developer_guide/swift/apns_certificate.md
Labels: cla-signed

#8908 BD-3902 Update Quick Push with Canvas support
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message/quick_push.md
  assets/img_archive/quick_push_1.png
  assets/img_archive/quick_push_4.png
Labels: cla-signed

#8911 Update link_template.md
  _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
Labels: cla-signed

#8909 BD-3897 WhatsApp video messages EA
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md
Labels: cla-signed

#8904 BD-3878 Update user archival screenshots and steps
  _docs/_hidden/other/user_archival.md
  assets/img_archive/user_archival_policy1.png
  assets/img_archive/user_archival_policy2.png
Labels: cla-signed

#8915 Updating some outdated links
  _docs/_user_guide/getting_started/users_segments.md
Labels: cla-signed

#8910 [BD-3894] Snowflake fix: account ID to account locator
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
Labels: cla-signed

#8913 BD-3882 Suppression list updates
  _docs/_user_guide/engagement_tools/segments/suppression_lists.md
Labels: cla-signed

#8916 [BD-3499] Content cleanup + clarifying requirements
  _docs/_developer_guide/content_cards/creating_custom_content_cards.md
Labels: cla-signed

#8914 [BD-3581] Feature flag experiement filter
  _docs/_developer_guide/feature_flags/experiments.md
  assets/img/feature_flags/variant-filter-dropdown.png
Labels: cla-signed

#8907 Update content_security_policy.md
  _docs/_developer_guide/platforms/web/content_security_policy.md
Labels: cla-signed

#8918 Fixed release notes
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2025.md
  _docs/_help/release_notes/2025/2_4_25.md
Labels: cla-signed

#8917 Update integration.md
  _docs/_developer_guide/banner_cards/integration.md
Labels: cla-signed

#8867 Create includes for HTTP event postback and new user guide article
  _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
  _docs/_user_guide/message_building_by_channel/email/transactional_message_api_campaign/tracking_transactional_emails.md
  _includes/http_event_postback.md
  assets/img/transactional_webhook_url.png
Labels: cla-signed

#8921 Update ecommerce to eCommerce
  _docs/_developer_guide/platforms/web/google_tag_manager.md
  _docs/_help/release_notes.md
  _docs/_help/release_notes/2021/december.md
  _docs/_help/release_notes/2021/october.md
  _docs/_help/release_notes/2022/5_31_22.md
  _docs/_help/release_notes/2024/12_10_24.md
  _docs/_partners/data_and_infrastructure_agility/analytics/wunderkind.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack/rudderstack.md
  _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/getting_started_shopify.md
  _docs/_partners/message_orchestration/channel_extensions/ecommerce/yotpo.md
  _docs/_partners/message_personalization/dynamic_content/amazon_personalize/workshop.md
  _docs/_partners/message_personalization/dynamic_content/constructor.md
  _docs/_partners/message_personalization/dynamic_content/movable_ink/customer_data_api.md
  _docs/_user_guide/administrative/app_settings/tags.md
  _docs/_user_guide/brazeai/intelligence.md
  _docs/_user_guide/brazeai/recommendations/about_item_recommendations.md
  _docs/_user_guide/data/creating_a_formula.md
  _docs/_user_guide/data/custom_data/custom_events.md
  _docs/_user_guide/data/custom_data/events.md
  _docs/_user_guide/data/custom_data/purchase_events.md
  _docs/_user_guide/data/user_data_collection/user_profile_lifecycle.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/install_attribution.md
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties/canvas_persistent_entry_properties.md
  _docs/_user_guide/engagement_tools/segments/segment_insights.md
  _docs/_user_guide/engagement_tools/segments/sql_segments/catalog_segments.md
  _docs/_user_guide/getting_started/workspaces.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
Labels: cla-signed

#8923 BD-3864: Add notification for campaign and Canvas volume limit
  _docs/_user_guide/administrative/app_settings/company_settings/notification_preferences.md
Labels: cla-signed

#8925 BD-3900: Alert for webhook and Connected Content errors is per workspace
  _docs/_help/help_articles/api/webhook_connected_content_errors.md
Labels: cla-signed

#8927 fix typo
  _docs/_developer_guide/platforms/swift/content_cards.md
Labels: cla-signed

#8928 BD-3906, BD-3839: Clarify email identifier and prioritization value
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
Labels: cla-signed

#8930 Fix: Add missing ';' in broken_redirect_list.js
  assets/js/broken_redirect_list.js
Labels: cla-signed

#8936 File sms_channel.md committed.
  _lang/ko/_hidden/home.md
  _lang/ko/_hidden/sms_channel.md
  _lang/ko/_hidden/user_archival.md
  _lang/ko/_includes/campaign_analytics.md
  _lang/ko/_includes/gifs.md
  _lang/ko/_includes/metrics.md
Labels: cla-signed

#8935 File sms_channel.md committed.
  _lang/pt_br/_hidden/home.md
  _lang/pt_br/_hidden/sms_channel.md
  _lang/pt_br/_hidden/user_archival.md
  _lang/pt_br/_includes/campaign_analytics.md
  _lang/pt_br/_includes/gifs.md
  _lang/pt_br/_includes/metrics.md
Labels: cla-signed

#8938 File metrics.md committed.
  _lang/es/_includes/campaign_analytics.md
  _lang/es/_includes/gifs.md
  _lang/es/_includes/metrics.md
Labels: cla-signed

#8937 File sms_channel.md committed.
  _lang/fr_fr/_hidden/home.md
  _lang/fr_fr/_hidden/sms_channel.md
  _lang/fr_fr/_hidden/user_archival.md
  _lang/fr_fr/_includes/campaign_analytics.md
  _lang/fr_fr/_includes/gifs.md
  _lang/fr_fr/_includes/metrics.md
Labels: cla-signed

#8726 BD-3800 Add brand guidelines settings page docs
  _docs/_user_guide/administrative/app_settings.md
  _docs/_user_guide/administrative/app_settings/brand_guidelines.md
  _docs/_user_guide/brazeai/generative_ai/ai_copywriting.md
  _docs/_user_guide/brazeai/generative_ai/ai_copywriting/brand_guidelines.md
  assets/img/ai_copywriter/manual_brand_guidelines.png
  assets/img/guidelines_ai_assistant.png
  assets/img/guidelines_create.png
  assets/img/guidelines_edited_assistant.png
  assets/img/unarchive_brand_guideline.png
Labels: cla-signed

#8940 Update image and add alt text
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/copying_to_workspace.md
  assets/img_archive/clone_campaign.png
Labels: cla-signed

#8933 Fix link issue found during BD-3855
  _docs/_user_guide/brazeai/recommendations.md
  assets/js/broken_redirect_list.js
  assets/js/hash_redirect.js
Labels: cla-signed

#8920 BD-2544 Add multivariate and AB testing FAQs
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/faq.md
Labels: cla-signed

#8931 BD-3899: Clarify same custom event for previewing user paths
  _docs/_user_guide/engagement_tools/canvas/testing_canvases/preview_user_paths.md
Labels: cla-signed

#8900 add dedicated feedback page
  _docs/_hidden/other/feedback.md
  assets/css/_feedback.scss
Labels: cla-signed

#8932 [BD-3912] Android Updates Activities
  _docs/_developer_guide/platforms/android/live_updates.md
  _docs/_developer_guide/platforms/swift/live_activities.md
  assets/img/android/android-live-activity-superb-owl-example.jpg
Labels: cla-signed

#8877 [BD-3275] Dev Guide Detangle: Integrating the Braze SDK
  _docs/_developer_guide/platforms/android/sdk_integration.md
  _docs/_developer_guide/platforms/fireos/sdk_integration.md
  _docs/_developer_guide/sdk_integration.md
  _includes/developer_guide/android/sdk_integration.md
  _includes/developer_guide/cordova/sdk_integration.md
  _includes/developer_guide/flutter/sdk_integration.md
  _includes/developer_guide/react_native/sdk_integration.md
  _includes/developer_guide/roku/sdk_integration.md
  _includes/developer_guide/swift/sdk_integration.md
  _includes/developer_guide/unity/sdk_integration.md
  _includes/developer_guide/unreal_engine/sdk_integration.md
  _includes/developer_guide/web/sdk_integration.md
  _includes/developer_guide/xamarin/sdk_integration.md
  assets/js/broken_redirect_list.js
  convert_to_includes.sh
  scripts/utils/convert_to_includes_OLD.sh
Labels: cla-signed

#8977 Leftover deploy - February 11, 2025
  _layouts/broken_page.html
  assets/js/hash_redirect.js
Labels: Deploy

#8991 Clarify detail for arrays limit
  _docs/_developer_guide/platforms/web/analytics/setting_custom_attributes.md
Labels: cla-signed

#8985 BD-3884: Clarify geofences are available for all platforms
  _docs/_developer_guide/platforms/legacy_sdks/ios/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platforms/swift/geofences.md
  _includes/developer_guide/android/geofences.md
Labels: cla-signed

#8982 Bd-3898 Add warning about adding a/b test to launched campaign
  _docs/_user_guide/engagement_tools/testing/multivariant_testing.md
Labels: cla-signed

#8984 Clarify details for best practices
  _docs/_user_guide/engagement_tools/testing/race_conditions.md
Labels: cla-signed

#8996 Leftover deploy - February 13, 2025
  Gemfile.lock
  _docs/_api/endpoints/messaging/live_activity/start.md
  _docs/_api/endpoints/messaging/live_activity/update.md
  _docs/_developer_guide/debugging.md
  _docs/_developer_guide/platforms/legacy_sdks/ios/advanced_use_cases/locations_and_geofences.md
  _docs/_developer_guide/platforms/legacy_sdks/macOS/initial_sdk_setup.md
  _docs/_developer_guide/platforms/react_native/in_app_messages.md
  _docs/_developer_guide/platforms/swift/geofences.md
  _docs/_developer_guide/platforms/swift/ios_18.md
  _docs/_developer_guide/platforms/swift/live_activities.md
  _docs/_developer_guide/platforms/tv_and_ott.md
  _docs/_developer_guide/platforms/web/analytics/setting_custom_attributes.md
  _docs/_help/help_articles/api/webhook_connected_content_errors.md
  _docs/_help/help_articles/push/no_push_notification_was_received.md
  _docs/_hidden/redirects/content_cards_for_ios.md
  _docs/_partners/data_and_infrastructure_agility/analytics/looker.md
  _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
  _docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing.md
  _docs/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md
  _docs/_user_guide/engagement_tools/testing/race_conditions.md
  _docs/_user_guide/message_building_by_channel/content_cards/about.md
  _includes/developer_guide/android/geofences.md
  _includes/developer_guide/android/push_notifications/troubleshooting.md
  _includes/metrics.md
  assets/js/broken_redirect_list.js
Labels: cla-signed, Deploy

#8989 BD-3901 Right-to-Left messages docs
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/localizing_a_campaign/right_to_left_messages.md
  _docs/_user_guide/message_building_by_channel/content_cards/create.md
  _docs/_user_guide/message_building_by_channel/content_cards/create/card_creation.md
  _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
  _docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
  _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/create.md
  _docs/_user_guide/message_building_by_channel/line/create.md
  _docs/_user_guide/message_building_by_channel/line/create/message_types.md
  _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
  _docs/_user_guide/message_building_by_channel/sms/campaign/create.md
  _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
  _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md
  assets/img/rtl_button.png
Labels: cla-signed

#8990 BD-3953 Update link aliasing for URLs generated by Liquid
  _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
Labels: cla-signed

#8941 BD-3791 Update Report Metrics Glossary
  _docs/_user_guide/data/report_metrics.md
  _includes/metrics.md
Labels: cla-signed

#9000 Update outdated Appboy method doc links
  _docs/_developer_guide/authentication.md
  _docs/_user_guide/data/user_data_collection/user_profile_lifecycle.md
  _docs/_user_guide/message_building_by_channel/sms/sms_subscription_group.md
  _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/opt-ins_and_opt-outs.md
  _docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
Labels: cla-signed

#9001 Update currents integration docs
  _docs/_partners/isv_partners/currents_integration.md
Labels: cla-signed

#9005 Update making_an_api_call.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
Labels: cla-signed

#9002 BD-3952 Explain why double-nested segments aren't allowed
  _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
  _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Labels: cla-signed

#9007 BD-3982 Apply Diàtaxis standards to Dynamic Content
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/back_in_stock_notifications.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/price_drop_notifications.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/selections.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/using_catalogs.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/aborting_connected_content.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/connected_content_retries.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/public_apis.md
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/user_profile_fields_connected_content.md
  _docs/_user_guide/personalization_and_dynamic_content/deep_linking_to_in-app_content.md
  _docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
  _docs/_user_guide/personalization_and_dynamic_content/promotion_codes/migrating_from_data_feeds.md
Labels: cla-signed

#9003 BD-3974: Update intro and mentions of properties
  _docs/_user_guide/engagement_tools/canvas/canvas_components/context.md
Labels: cla-signed

#9010 fix missing partner
  _layouts/partner_page.html
Labels: cla-signed

#8929 [BD-3911] Landing pages + data merging
  _docs/_user_guide/engagement_tools/landing_pages.md
  _docs/_user_guide/engagement_tools/landing_pages/about_tracking_data.md
  _docs/_user_guide/engagement_tools/landing_pages/creating_pages.md
  _docs/_user_guide/engagement_tools/landing_pages/customizing_urls.md
  _docs/_user_guide/engagement_tools/landing_pages/drag_and_drop.md
  _docs/_user_guide/engagement_tools/landing_pages/tracking_users.md
  assets/img/landing_pages/analytics.png
  assets/img/landing_pages/copy-url.png
  assets/img/landing_pages/dnd.png
  assets/img/landing_pages/editor.png
  assets/img/landing_pages/get-snippet.png
  assets/img/landing_pages/landing-pages-homepage.png
  assets/img/landing_pages/message-content-options.png
  assets/img/landing_pages/select-edit-landing-page.png
  assets/img/landing_pages/select-personalization.png
  assets/img/landing_pages/url-handle-example.png
  assets/js/broken_redirect_list.js
Labels: cla-signed

#9008 Clean up in-app messages for Canvas article
  _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_by_channel/in-app_messages_in_canvas.md
Labels: cla-signed

#9012 Add Constructor to partners list
  _docs/_partners/home.md
Labels: cla-signed

#9013 Remove "_" from link
  _docs/_partners/message_personalization.md
Labels: cla-signed

#9004 [BD-3798] Braze Entity Relationship Diagram
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake/entity_relationships.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake/faqs.md
  _includes/snowflake_users_messages/contentcard.md
  _includes/snowflake_users_messages/email.md
  _includes/snowflake_users_messages/featureflag.md
  _includes/snowflake_users_messages/inappmessage.md
  _includes/snowflake_users_messages/newsfeedcard.md
  _includes/snowflake_users_messages/pushnotification.md
  _includes/snowflake_users_messages/sms.md
  _includes/snowflake_users_messages/webhook.md
  _includes/snowflake_users_messages/whatsapp.md
  assets/img/placeholder_entity_relationship_diagram.jpg
  scripts/utils/erd_generate_markdown.py
  scripts/utils/erd_get_json.py
Labels: cla-signed

#9015 Leftover deploy - February 18, 2025
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake/entity_relationships.md
  _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake/faqs.md
  _includes/snowflake_users_messages/contentcard.md
  _includes/snowflake_users_messages/email.md
  _includes/snowflake_users_messages/featureflag.md
  _includes/snowflake_users_messages/inappmessage.md
  _includes/snowflake_users_messages/newsfeedcard.md
  _includes/snowflake_users_messages/pushnotification.md
  _includes/snowflake_users_messages/sms.md
  _includes/snowflake_users_messages/webhook.md
  _includes/snowflake_users_messages/whatsapp.md
  assets/img/placeholder_entity_relationship_diagram.jpg
  scripts/utils/erd_generate_markdown.py
  scripts/utils/erd_get_json.py
Labels: cla-signed, Deploy

#9018 Update title for React Native integration docs
  _includes/developer_guide/react_native/sdk_integration.md
Labels: cla-signed

#9017 Update tracking_users.md
  _docs/_user_guide/engagement_tools/landing_pages/tracking_users.md
Labels: cla-signed

#9019 Add DE build options
  Rakefile
  _data/i18n.yml
  _lang/_config_de.yml
  public/index_de.html
  public/index_es.html
  public/index_pt-br.html
Labels: cla-signed

#8961 Add clarifying documentation for iOS Live Activities `brazeActivityId`
  _docs/_developer_guide/platforms/swift/live_activities.md
Labels: cla-signed

#9022 BD-3969: Clarify Engagement Report by Device details
  _docs/_user_guide/analytics/dashboard/email_performance_dashboard.md
Labels: cla-signed

#9021 Bd-4011 Update RTL messages with screenshot and best practice
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/localizing_a_campaign/right_to_left_messages.md
  assets/img/rtl_comparison.png
Labels: cla-signed

#9025 BD-4002: Remove EA banner
  _includes/message_usage.md
Labels: cla-signed

#9024 BD-3970: Add FAQ and minor detail to Audience Sync articles
  _docs/_partners/canvas_steps/faq.md
  _docs/_partners/canvas_steps/google_audience_sync.md
Labels: cla-signed

#8993 BD-3659 Liquid Operator tutorials
  _docs/_user_guide/personalization_and_dynamic_content/liquid/operators.md
  assets/img/liquid-if-elsif-games.png
  assets/img/liquid-if-totalspend.png
Labels: cla-signed

#9023 BD-4007: Improve Push TTL docs
  _docs/_user_guide/administrative/app_settings/push_ttl_settings.md
  _docs/_user_guide/message_building_by_channel/push/android/advanced_campaign_settings.md
Labels: cla-signed

#9028 BD-4013: Update Liquid for Context step
  _docs/_user_guide/engagement_tools/canvas/canvas_components/context.md
Labels: cla-signed

#9026 BD-3947: Add info about email hard bounces
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Labels: cla-signed

#9030 [MP-5920] Update /campaigns/trigger/schedule/update Docs With Local Time Disclaimer
  _docs/_api/endpoints/messaging/schedule_messages/post_update_scheduled_triggered_campaigns.md
Labels: cla-signed

#8997 BD-3950 Clear browser cache and cookies to solve performance issues
  _docs/_user_guide/administrative/access_braze.md
Labels: cla-signed

#9032 BD-3971: Copying campaigns with feature flags edit
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/copying_to_workspace.md
Labels: cla-signed

#9036 Add files via upload
  assets/img/landing_pages/segmentation selected.png
  assets/img/landing_pages/segmentation.png
  assets/img/landing_pages/trigger.png
Labels: cla-signed

#9033 BD-3957 Error messages for an outdated browser
  _docs/_user_guide/administrative/access_braze.md
Labels: cla-signed

#9034 BD-3983: Add detail to /canvas/trigger/send doc
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
Labels: cla-signed

#9039 Leftover deploy - February 20, 2025
  Rakefile
  _data/i18n.yml
  _docs/_api/endpoints/messaging/schedule_messages/post_update_scheduled_triggered_campaigns.md
  _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
  _docs/_developer_guide/platforms/swift/live_activities.md
  _docs/_partners/canvas_steps/faq.md
  _docs/_partners/canvas_steps/google_audience_sync.md
  _docs/_user_guide/administrative/access_braze.md
  _docs/_user_guide/administrative/app_settings/push_ttl_settings.md
  _docs/_user_guide/analytics/dashboard/email_performance_dashboard.md
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/localizing_a_campaign/right_to_left_messages.md
  _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/copying_to_workspace.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/context.md
  _docs/_user_guide/engagement_tools/landing_pages/tracking_users.md
  _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
  _docs/_user_guide/message_building_by_channel/push/android/advanced_campaign_settings.md
  _docs/_user_guide/personalization_and_dynamic_content/liquid/operators.md
  _includes/developer_guide/cordova/sdk_integration.md
  _includes/developer_guide/react_native/sdk_integration.md
  _includes/message_usage.md
  _lang/_config_de.yml
  assets/img/landing_pages/segmentation selected.png
  assets/img/landing_pages/segmentation.png
  assets/img/landing_pages/trigger.png
  assets/img/liquid-if-elsif-games.png
  assets/img/liquid-if-totalspend.png
  assets/img/rtl_comparison.png
  public/index_de.html
  public/index_es.html
  public/index_pt-br.html
Labels: cla-signed, Deploy

#9040 BD-3945 Update names of reported security events
  _docs/_user_guide/administrative/app_settings/company_settings/security_settings.md
Labels: cla-signed

#8999 BD-3855: Using item recommendations in messages
  _docs/_user_guide/brazeai/recommendations/about_item_recommendations copy.md
  _docs/_user_guide/brazeai/recommendations/using_recommendations.md
  assets/img/image_with_liquid.png
Labels: cla-signed

#9047 Fix image reference
  _docs/_user_guide/brazeai/recommendations/using_recommendations.md
Labels: cla-signed

#9049 Update creating_pages.md
  _docs/_user_guide/engagement_tools/landing_pages/creating_pages.md
Labels: cla-signed

#9051 CO-3334: update usage report limit
  _docs/_user_guide/data/custom_data/custom_attributes.md
  _docs/_user_guide/data/custom_data/custom_events.md
Labels: cla-signed

#9054 CO-3335: remove EA banner for exporting data
  _docs/_user_guide/data/custom_data/custom_events.md
Labels: cla-signed

#9053 CO-3333 Remove Sep 2021 reference from rate limit section.
  _includes/rate_limits.md
Labels: cla-signed

#9045 CO-3328: update docs on blocklisting limits from 10 to 100
  _docs/_user_guide/data/custom_data/custom_attributes.md
  _docs/_user_guide/data/custom_data/custom_events.md
  _docs/_user_guide/data/custom_data/managing_custom_data.md
Labels: cla-signed

#9043 [CO-3331] Clarifies data point consumption
  _docs/_user_guide/data/custom_data/custom_attributes/nested_custom_attribute_support.md
Labels: cla-signed

#9042 [MOPS-3266] Fix Message Archiving push platforms
  _docs/_user_guide/data/export_braze_data/message_archiving.md
Labels: cla-signed

#9044 BD-3968 How to add designated support contacts
  _docs/_help/support.md
  assets/img_archive/designated_support_contact.png
  assets/img_archive/get_help.png
Labels: cla-signed

#8922 Improve Segment Extensions to remove FUD
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
Labels: cla-signed, In Review

#9041 [MOPS-3265] Fix Message Archiving file path structure
  _docs/_user_guide/data/export_braze_data/message_archiving.md
Labels: cla-signed

#9052 [CO-3332] Updated valid year range for nested custom events page
  _docs/_user_guide/data/custom_data/custom_events/nested_objects.md
Labels: cla-signed

#9056 CO-3341: clarify PUT behaviour for catalog/items endpoint
  _docs/_api/endpoints/catalogs.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/put_update_catalog_items.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/put_update_catalog_item.md
  _docs/_api/home.md
Labels: cla-signed

#9057 BD-4038 Add 5XX error information
  _docs/_api/errors.md
Labels: cla-signed

#9006 BD-3914 Add details to Message Activity Log
  _docs/_user_guide/administrative/app_settings/message_activity_log_tab.md
Labels: cla-signed

#9048 add rate limit info for CY24-25
  _docs/_developer_guide/getting_started/integration_overview.md
Labels: cla-signed

#9062 CO-3343: update users merge API error message
  _docs/_api/endpoints/user_data/post_users_merge.md
Labels: cla-signed

#9060 BD-4012: Add new Deferrals event
  _docs/_help/release_notes.md
  _includes/campaign_analytics.md
  _includes/metrics.md
Labels: cla-signed, release notes

#9031 Add 'jq' check to bdocs
  bdocs
Labels: cla-signed

#9037 [MP-5923] Add Disclaimer Stating That We May Slightly Exceed Rate Limit
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
Labels: cla-signed

#9064 Deploy - February 25, 2025
  _docs/_api/endpoints/catalogs.md
  _docs/_api/endpoints/catalogs/catalog_items/asynchronous/put_update_catalog_items.md
  _docs/_api/endpoints/catalogs/catalog_items/synchronous/put_update_catalog_item.md
  _docs/_api/endpoints/user_data/post_users_merge.md
  _docs/_api/errors.md
  _docs/_api/home.md
  _docs/_developer_guide/getting_started/integration_overview.md
  _docs/_help/release_notes.md
  _docs/_help/support.md
  _docs/_user_guide/administrative/app_settings/company_settings/security_settings.md
  _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
  _docs/_user_guide/administrative/app_settings/message_activity_log_tab.md
  _docs/_user_guide/brazeai/recommendations/about_item_recommendations copy.md
  _docs/_user_guide/brazeai/recommendations/using_recommendations.md
  _docs/_user_guide/data/cloud_ingestion/connected_sources.md
  _docs/_user_guide/data/custom_data/custom_attributes.md
  _docs/_user_guide/data/custom_data/custom_attributes/nested_custom_attribute_support.md
  _docs/_user_guide/data/custom_data/custom_events.md
  _docs/_user_guide/data/custom_data/custom_events/nested_objects.md
  _docs/_user_guide/data/custom_data/managing_custom_data.md
  _docs/_user_guide/data/export_braze_data/message_archiving.md
  _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
  _docs/_user_guide/engagement_tools/landing_pages/creating_pages.md
  _docs/_user_guide/engagement_tools/landing_pages/tracking_users.md
  _docs/_user_guide/engagement_tools/segments/segment_extension.md
  _includes/campaign_analytics.md
  _includes/metrics.md
  _includes/rate_limits.md
  assets/img/image_with_liquid.png
  assets/img/landing_pages/segmentation_selected.png
  assets/img_archive/designated_support_contact.png
  assets/img_archive/get_help.png
  bdocs
Labels: cla-signed, Deploy

#9061 CO-3347 Custom data: clarify data type coercion.
  _docs/_user_guide/data/custom_data/managing_custom_data.md
Labels: cla-signed

#9063 [CO-3344] Update users export doc
  _docs/_api/endpoints/export/user_data/post_users_global_control_group.md
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
  _docs/_api/endpoints/export/user_data/post_users_segment.md
Labels: cla-signed

#9065 Fix time spacing
  _docs/_help/release_notes.md
Labels: cla-signed

#9035 Create retargeting_with_landing_pages - MERGE 2/25
  _docs/_user_guide/engagement_tools/landing_pages/creating_pages.md
  _docs/_user_guide/engagement_tools/landing_pages/retargeting.md
  _docs/_user_guide/engagement_tools/landing_pages/tracking_users.md
  assets/img/landing_pages/segmentation.png
  assets/img/landing_pages/segmentation_selected.png
Labels: cla-signed, In Review

#9072 Deploy pt 2 - February 25, 2025
  _docs/_api/endpoints/export/user_data/post_users_global_control_group.md
  _docs/_api/endpoints/export/user_data/post_users_identifier.md
  _docs/_api/endpoints/export/user_data/post_users_segment.md
  _docs/_help/release_notes.md
  _docs/_user_guide/data/custom_data/managing_custom_data.md
  _docs/_user_guide/engagement_tools/landing_pages/creating_pages.md
  _docs/_user_guide/engagement_tools/landing_pages/retargeting.md
  _docs/_user_guide/engagement_tools/landing_pages/tracking_users.md
  assets/img/landing_pages/segmentation.png
  assets/img/landing_pages/segmentation_selected.png
Labels: cla-signed, Deploy

#9066 CO-3336 add note about aliases with the same label
  _docs/_api/endpoints/user_data/post_user_identify.md
Labels: cla-signed

#9071 [MP-5815] Clarify lack of rerendering with catalogs tags
  _docs/_user_guide/personalization_and_dynamic_content/connected_content/user_profile_fields_connected_content.md
Labels: cla-signed

#9068 CO-3342 add note that unsubscribe events are optional
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/back_in_stock_notifications.md
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/price_drop_notifications.md
Labels: cla-signed

#9075 Fix images
  assets/img/abort-if.png
  assets/img/liquid-if-elsif-games.png
  assets/img/liquid-if-totalspend.png
  assets/img_archive/choose_email_creation.png
  assets/img_archive/designated_support_contact.png
  assets/img_archive/get_help.png
  assets/img_archive/user_archival_policy1.png
  assets/img_archive/user_archival_policy2.png
Labels: cla-signed

#9077 CO-3346: move EA banner for custom data deletion to a more visible section
  _docs/_user_guide/data/custom_data/managing_custom_data.md
Labels: cla-signed

#9074 Add missing info for scheduling campaigns and Canvases
  _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/best_practices.md
  _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/best_practices.md
Labels: cla-signed

#7507 [BD-3161] Feature flag experiments
  _docs/_developer_guide/feature_flags/experiments.md
  _docs/_user_guide/analytics/reporting/campaign_analytics.md
  _docs/_user_guide/data/report_metrics.md
Labels: status: do not merge, cla-signed

#9069 CO-3340: remove catalog tier table and add short description instead
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
Labels: cla-signed

#9067 CO-3339: update permissions required for catalogs in-browser editing
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
Labels: cla-signed

#9038 BD-3941 You can't delete workspaces or app instances that are in use
  _docs/_user_guide/administrative/app_settings/workspaces.md
Labels: cla-signed

#9076 CO-3329 Custom data: _merge_objects won't delete data from array of objects.
  _docs/_user_guide/data/custom_data/custom_attributes/array_of_objects.md
  _docs/_user_guide/data/custom_data/custom_attributes/nested_custom_attribute_support.md
Labels: cla-signed

#9082 CO-3355: update user profile lifecycle page to clarify a static braze_id + add email and phone identifiers
  _docs/_user_guide/data/user_data_collection/user_profile_lifecycle.md
Labels: cla-signed

#9085 Updated nav date was outdated
  _docs/_user_guide/administrative/access_braze/navigation.md
Labels: cla-signed

#9079 CO-3345 add note about cooldown and permissions
  _docs/_user_guide/data/custom_data/custom_events/nested_objects.md
Labels: cla-signed

#9080 Email love partner docs
  _docs/_partners/home.md
  _docs/_partners/message_orchestration/channel_extensions.md
  _docs/_partners/message_orchestration/channel_extensions/email_templates/email_love.md
  assets/img/email_love/emaillove1_content.png
  assets/img/email_love/emaillove2_components.png
  assets/img/email_love/emaillove3_exportbraze.png
Labels: cla-signed

#9091 Email Love Docs team edits
  _docs/_partners/message_orchestration/channel_extensions/email_templates/email_love.md
Labels: cla-signed

#9083 CO-3354 add LINE to inactive users explanation and clarify treatment sample group
  _docs/_hidden/other/user_archival.md
Labels: cla-signed

#9081 [BD-3275] Dev Guide Detangle: SDK Initialization
  _docs/_developer_guide/content_cards.md
  _docs/_developer_guide/platforms/android/initialization.md
  _docs/_developer_guide/platforms/android/initialization/google_tag_manager.md
  _docs/_developer_guide/platforms/android/initialization/runtime_configuration.md
  _docs/_developer_guide/platforms/fireos/initialization.md
  _docs/_developer_guide/platforms/fireos/initialization/google_tag_manager.md
  _docs/_developer_guide/platforms/fireos/initialization/runtime_configuration.md
  _docs/_developer_guide/platforms/swift/initialization.md
  _docs/_developer_guide/platforms/swift/initialization/delayed_initialization.md
  _docs/_developer_guide/sdk_initalization.md
  _includes/developer_guide/android/initialization/runtime_configuration.md
  _includes/developer_guide/android/sdk_initialization.md
  _includes/developer_guide/swift/sdk_initialization.md
  _includes/developer_guide/unreal_engine/sdk_initialization.md
  assets/js/broken_redirect_list.js
Labels: cla-signed

#9088 BD-4057: Update old links to GA4
  _docs/_user_guide/personalization_and_dynamic_content/deep_linking_to_in-app_content.md
Labels: cla-signed

#9084 BD-4024: Add that Braze ID can be found on user profiles
  _docs/_user_guide/engagement_tools/segments/user_profiles.md
Labels: cla-signed

#8958 [SDK-5420] rn banners
  _docs/_developer_guide/banner_cards/integration.md
Labels: cla-signed

#9092 Always update toc nav
  _plugins/sdktabs.rb
  assets/js/documents.js
Labels: cla-signed

#9095 BD-4098: Update mobile advertiser ID description for audience sync
  _docs/_partners/canvas_steps/google_audience_sync.md
Labels: cla-signed

#9089 BD-3973: Personalized delay and extended delay EA
  _docs/_user_guide/engagement_tools/canvas/canvas_components/context.md
  _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
Labels: cla-signed

#9098 Update header to be more accurate with current EA
  _docs/_user_guide/engagement_tools/canvas/canvas_components/context.md
Labels: cla-signed

#9102 BD-3876: Add detail about same phone numbers for external IDs
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
Labels: cla-signed

#9103 [BD-4094] Add Swift option to Aliasing users code
  _includes/archive/setting_user_ids/aliasing.md
Labels: cla-signed

#9104 BD-4102: Add missing parameter use_double_opt_in_logic
  _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
Labels: cla-signed

#9105 [BD-4096] Considerations for web push tokens
  _docs/_help/help_articles/push/push_token_migration.md
Labels: cla-signed

#9078 VWO partner docs
  _docs/_partners/data_and_infrastructure_agility/ab_testing/vwo.md
  assets/img/vwo/vwo1_settings.png
  assets/img/vwo/vwo2_enable_braze.png
  assets/img/vwo/vwo3_braze_segment.png
  assets/img/vwo/vwo4_braze_segment_calculate_size.png
  assets/img/vwo/vwo5_troubleshooting.png
Labels: cla-signed

#9055 BD-3946 Can't log in with password after using SSO
  _docs/_user_guide/administrative/access_braze/accessing_your_account.md
Labels: cla-signed

#9108 BD-4117 Fix Liquid snippet brackets
  _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/back_in_stock_notifications.md
Labels: cla-signed

#9097 [DLK-2766] add field level comments for datalake views
  assets/download_file/data-sharing-raw-table-schemas.txt
Labels: cla-signed

#9109 BD-4086 Risk of using emails or hashed emails as external IDs
  _docs/_user_guide/data/user_data_collection/user_profile_lifecycle.md
Labels: cla-signed
